export const lessons = [
  {
    id: 'l37-mdp',
    title: '37.1 · Learning from reward',
    sections: ['Not supervised learning', 'States, actions, rewards', 'Return and discount', 'Policies and values', 'Put it into practice'],
    skill: 'Formulate a sequential decision problem as a Markov decision process and explain how it differs from supervised learning.',
    prerequisite: 'Core labs 01–33; probability (Lab 04), optimization (Lab 22).',
    paragraphs: [
      'In supervised learning every example comes with the correct answer. In **reinforcement learning** (RL) an agent acts, and the world responds with a new situation and a number — a **reward**. Nobody labels the right move; rewards may arrive many steps after the decision that earned them; and the data the agent sees depends on what it chose to do.',
      'A **Markov decision process** has states s (the robot\'s cell), actions a (up, right, down, left), transition probabilities P(s′ | s, a) (with slip, moves sometimes go astray), and rewards r (−0.1 per move, +10 at the star, −10 in the ditch). "Markov" means the current state contains everything needed to predict what happens next.',
      'The agent maximizes the **return**: the sum of future rewards, each discounted by γ per step — G = r₁ + γr₂ + γ²r₃ + … With γ = 0.95, a reward 10 steps away is worth 0.95¹⁰ ≈ 0.60 of the same reward now. Discounting favours faster success and keeps sums finite.',
      'A **policy** π maps each state to an action. Its **value** V(s) is the expected return from s following π; the **action value** Q(s, a) is the expected return from taking a in s and following π afterwards. The best policy picks argmaxₐ Q(s, a) in every state.',
      'Procedure: define the state (what the agent observes), the actions, the episode end, and the reward — the only way you tell the agent what you want. Before any learning, write a simple hand-coded policy as a baseline.',
    ],
    formula: 'G = Σₖ γᵏ rₖ₊₁     V^π(s) = E[G | s, π]     Q^π(s, a) = E[G | s, a, then π]',
    experiment: 'Set slip to 0 and show the hand-written policy. Then raise slip to 20%. How often does the baseline fall in the ditch?',
    question: 'With γ = 0.9, what is a reward of 10 received 3 steps from now worth today? (10 × γ³, two decimals.)',
    answer: 7.29, tolerance: 0.01,
    explanation: '10 × 0.9³ = 10 × 0.729 = 7.29.',
    reflection: 'Describe a decision in your work that is sequential: today\'s choice changes tomorrow\'s situation. What would the reward be?',
  },
  {
    id: 'l37-planning',
    title: '37.2 · Planning when the rules are known',
    sections: ['The Bellman equation', 'Value iteration', 'Risk from randomness', 'When you cannot plan', 'Baselines again'],
    skill: 'Compute an optimal policy by value iteration and interpret how randomness changes it.',
    prerequisite: 'Lesson 37.1.',
    paragraphs: [
      'The optimal values satisfy the **Bellman equation**: V*(s) = maxₐ Σ P(s′ | s, a) [r + γ V*(s′)]. A state is worth the best action\'s immediate reward plus the discounted value of where it leads.',
      '**Value iteration** turns the equation into an update: start with V = 0 and repeatedly replace each V(s) by the right-hand side. Each sweep propagates value one step further back from the goal; after enough sweeps V stops changing and the greedy policy is optimal.',
      'With no slip, the optimal path runs right along the ditch: 8 moves. With 10% slip, a move next to the ditch has a real chance of falling in, so the optimal policy climbs one row higher and accepts a longer path. The goal is the same — only the uncertainty changed the best plan.',
      'Value iteration needs the full model: every transition probability and reward. Real problems — a warehouse robot, a recommendation sequence, a chemical process — rarely provide it. The agent must learn from experience instead (next lesson).',
      'Always compare with simple policies. The hand-written "walk along the ditch" is optimal without slip. An RL system that cannot beat a reasonable rule is not worth its complexity.',
    ],
    formula: 'V(s) ← maxₐ Σₛ′ P(s′|s,a) [r(s,a,s′) + γ V(s′)]',
    experiment: 'Show "Value iteration" and move slip from 0% to 30%. Watch the arrows near the ditch and the average number of moves.',
    question: 'A state next to the goal: moving right reaches the star (+10, episode ends) with probability 0.9, and with probability 0.1 the robot stays in a state worth V = 8. With γ = 0.95 and a step reward of 0 for staying, what is the expected value of moving right? (Two decimals.)',
    answer: 9.76, tolerance: 0.01,
    explanation: '0.9 × 10 + 0.1 × (0 + 0.95 × 8) = 9 + 0.76 = 9.76.',
    reflection: 'For a process you know, which parts of the "model" (transitions and rewards) could you write down, and which would have to be learned?',
  },
  {
    id: 'l37-qlearning',
    title: '37.3 · Q-learning from trial and error',
    sections: ['Temporal-difference updates', 'Exploration versus exploitation', 'Learning rate and noise', 'Sample efficiency', 'From tables to networks'],
    skill: 'Train a tabular Q-learning agent and tune exploration, learning rate and training length.',
    prerequisite: 'Lessons 37.1–37.2; gradient-based learning (Labs 20–22).',
    paragraphs: [
      '**Q-learning** estimates Q(s, a) without a model. After each move it compares its estimate with a **target** built from what just happened: r + γ maxₐ′ Q(s′, a′). It moves the estimate a fraction α toward the target: Q(s, a) ← Q(s, a) + α [target − Q(s, a)]. At the end of an episode the target is just r.',
      'If the agent always takes the best-looking action, it may never try the one that is actually better. **ε-greedy** exploration takes a random action with probability ε. Too little exploration can lock in a poor route; too much keeps the agent stumbling into the ditch while it learns.',
      'The learning rate α trades speed for stability: with slip, rewards are random, and a large α makes Q chase the latest outcome. Retrain with a new seed and results differ — always report RL results over several seeds.',
      'Even this tiny world needs around a hundred episodes of experience. Real tasks need far more, which is why RL is often trained in simulators — and why the simulator\'s realism becomes the next risk.',
      'When states are too many for a table (images, continuous sensors), a neural network approximates Q (deep Q-networks) or the policy directly (policy gradients). The ideas — returns, exploration, bootstrapped targets — stay the same; stability becomes much harder.',
    ],
    formula: 'Q(s,a) ← Q(s,a) + α [r + γ maxₐ′ Q(s′,a′) − Q(s,a)]     act randomly with probability ε',
    experiment: 'Set training episodes to 25, 50, 100 and 400. When does Q-learning start reaching the star reliably? Then retrain with new seeds.',
    question: 'Q(s, a) = 2, reward r = −0.1, γ = 0.9, the next state\'s best Q is 5, and α = 0.5. What is the updated Q(s, a)? (Two decimals.)',
    answer: 3.2, tolerance: 0.01,
    explanation: 'Target = −0.1 + 0.9 × 5 = 4.4. Update: 2 + 0.5 × (4.4 − 2) = 3.2.',
    reflection: 'Why is it risky to let an agent explore in the real system rather than in a simulator? What would exploration cost in your domain?',
  },
  {
    id: 'l37-reward',
    title: '37.4 · Reward misspecification',
    sections: ['The agent optimizes what you wrote', 'Reward hacking', 'Measure the real objective', 'Safer reward design', 'Demonstrate understanding'],
    skill: 'Diagnose reward misspecification by comparing the optimized reward with the true objective.',
    prerequisite: 'Lessons 37.1–37.3; responsible decisions (Lab 31).',
    paragraphs: [
      'The reward is the only specification the agent receives. It will exploit any gap between the reward and what you meant, and it is very good at finding such gaps.',
      'The checkpoint bonus was meant to help: +2 for passing a cell on the safe route. But entering it again pays again. Circling between two cells earns +1.8 every two moves; over 60 moves that beats the +10 star by far. At the default discount, value iteration — which knows the rules exactly — circles too — proof that the fault lies in the reward, not the learner. The policy never finishes, and the reward it optimizes is higher than ever — **reward hacking**.',
      'Detect it by measuring the true objective separately from the training reward: success rate, time to goal, safety events. Watch the agent\'s behaviour, not just the curve. A training reward that rises while the real outcome falls is the signature.',
      'Safer designs: reward outcomes, not proxies for progress; make bonuses one-time (or potential-based shaping, which provably does not change the optimal policy); cap episode length; and test against a simple baseline policy. In high-stakes settings, keep a human in the loop and constrain actions.',
      'You have completed this specialization when you can: formulate an MDP; explain return, discounting, values and policies; solve a known model by value iteration; train and tune Q-learning over several seeds; compare with a hand-written baseline; and diagnose reward misspecification by measuring the objective you actually care about. The Python challenge implements value iteration and Q-learning.',
    ],
    formula: 'training reward ↑ while task outcome ↓  ⇒  the reward is misspecified',
    experiment: 'Switch to the checkpoint bonus and compare the two curves in the progress plot. Then run an episode and describe what the robot does.',
    question: 'Circling earns +2 every 2 moves and costs 0.1 per move. Ignoring discounting, what does circling earn over 60 moves?',
    answer: 54,
    explanation: '30 checkpoint entries × 2 − 60 × 0.1 = 60 − 6 = 54, far more than the best honest episode: +10 for the star minus 0.8 for 8 moves.',
    reflection: 'Think of a metric people in your organization are rewarded on. How could someone raise it without achieving what it was meant to measure?',
  },
]

export const sources = [
  { title: 'Sutton & Barto · Reinforcement Learning: An Introduction (free book)', url: 'http://incompleteideas.net/book/the-book-2nd.html' },
  { title: 'Watkins & Dayan (1992) · Q-learning', url: 'https://doi.org/10.1007/BF00992698' },
  { title: 'Ng, Harada & Russell (1999) · Policy invariance under reward transformations', url: 'https://people.eecs.berkeley.edu/~russell/papers/icml99-shaping.pdf' },
  { title: 'DeepMind · Specification gaming: the flip side of AI ingenuity', url: 'https://deepmind.google/discover/blog/specification-gaming-the-flip-side-of-ai-ingenuity/' },
]
