// Lesson order for Lab 24: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l24-why': [
    { p: 0 },
    { cell: 0 },
    { predict: { prompt: 'A 28 × 28 grayscale image feeds a dense layer of 128 units. How many parameters does that layer have?', answer: 100480, explain: '28 × 28 × 1 = 784 inputs; 784 × 128 = 100,352 weights plus 128 biases = 100,480.', misconceptions: [{ answer: 100352, feedback: 'Add one bias per unit: 128 more.' }] } },
    { p: 1 }, { p: 2 },
    { cell: 1 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l24-conv': [
    { p: 0 }, { p: 1 },
    { figure: 'ConvSlide', caption: 'A digit, a 3 × 3 kernel and its feature map. Choose an output cell to see the patch and the nine products that make it.' },
    { cell: 0 },
    { predict: { prompt: 'Sobel x, [[−1, 0, 1], [−2, 0, 2], [−1, 0, 1]], sits on a patch where every pixel is 1. What does it output?', answer: 0, explain: 'Its weights sum to zero, so any uniform patch gives 0: (−1 − 2 − 1) + (1 + 2 + 1) = 0. It responds only where brightness changes from left to right.', misconceptions: [{ answer: 8, feedback: 'That adds the absolute values. The negative column cancels the positive one.' }] } },
    { p: 2 }, { p: 3 },
    { cell: 1 },
    { predict: { prompt: 'A 32 × 32 input, a 3 × 3 kernel, stride 1, no padding. What is the output width?', answer: 30, explain: '⌊(32 + 0 − 3)/1⌋ + 1 = 30: the kernel cannot be centred on the outermost pixels.', misconceptions: [{ answer: 32, feedback: 'That needs padding p = 1 (“same”). Without padding the output loses k − 1 = 2.' }] } },
    { p: 4 },
    { math: true },
  ],
  'l24-sharing': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { p: 2 },
    { cell: 1 },
    { figure: 'ShiftFeatures', caption: 'Move the digit: the pixels and the feature map move with it, the pooled features barely change.' },
    { p: 3 },
    { cell: 2 },
    { predict: { prompt: 'How many parameters does a 3 × 3 convolution from 64 to 128 channels have, including biases?', answer: 73856, explain: '3 × 3 × 64 × 128 = 73,728 weights plus 128 biases = 73,856, for any image size.', misconceptions: [{ answer: 73728, feedback: 'Add one bias per output channel.' }, { answer: 1152, feedback: 'Each of the 128 kernels spans all 64 input channels: 3 × 3 × 64 weights each.' }] } },
    { p: 4 },
    { math: true },
  ],
  'l24-depth': [
    { p: 0 },
    { figure: 'RFGrowth', caption: 'How many input pixels one output can see, for L stacked layers with kernel k and stride s.' },
    { cell: 0 },
    { predict: { prompt: 'Three stacked 5 × 5 convolutions with stride 1. What is the receptive field size?', answer: 13, explain: '1 + L(k − 1) = 1 + 3 × 4 = 13.', misconceptions: [{ answer: 15, feedback: 'Each layer adds k − 1 = 4, not k: 1 + 3 × 4.' }] } },
    { p: 1 }, { p: 2 }, { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l24-practice': [
    { p: 0 },
    { cell: 0 },
    { p: 1 }, { p: 2 }, { p: 3 },
    { cell: 1 },
    { predict: { prompt: '50 cameras took 40 images each. You hold out 10% of the cameras. How many images are in the test set?', answer: 200, explain: '5 cameras × 40 images = 200 test images; no camera appears on both sides.', misconceptions: [{ answer: 5, feedback: 'That is the number of held-out cameras. Each brings all 40 of its images.' }] } },
    { p: 4 },
    { math: true },
    { ladder: 'conv' },
  ],
}
