export const lessons = [
  {
    id: 'l24-why',
    title: '24.1 · Images break dense layers',
    sections: ['An image is a grid', 'Too many weights', 'Local patterns', 'Position should not matter', 'Put it into practice'],
    skill: 'Explain why fully connected layers suit images poorly and which structure convolutions exploit.',
    prerequisite: 'Labs 01–23; dense networks (Lab 21), PCA on images (Lab 18).',
    paragraphs: [
      'A 224×224 colour image has 224 × 224 × 3 = 150,528 numbers. A dense layer with 1,000 units needs 150 million weights for its first layer alone — far more than the data can fit reliably, and far too slow.',
      'Worse, a dense layer ignores the grid. It treats pixel (10, 10) and pixel (10, 11) as unrelated inputs, even though neighbouring pixels are strongly related, and edges, corners and textures are made of neighbourhoods.',
      'And it ties every weight to one location. A dense model that learns "a cat\'s ear at the top left" must learn it again for every other position. The playground\'s shifted-digit experiment makes this concrete: a model trained on left-placed digits fails completely on right-placed ones.',
      'Two assumptions fix this: **locality** (useful features depend on small neighbourhoods) and **translation equivariance** (the same feature can appear anywhere, so the same detector should be used everywhere). Convolutional layers build both in.',
      'Procedure for image problems: check image size and channels; look at examples from every class and source; decide which invariances make sense (a shifted cat is still a cat, but a flipped "6" becomes a "9"); then choose architecture and augmentation accordingly.',
    ],
    formula: 'dense first layer: (H·W·C) × units weights     conv layer: k·k·C_in × C_out weights, independent of H and W',
    experiment: 'In "Experiment: shifted digits", train on raw pixels without augmentation. Compare accuracy at training positions and at unseen positions.',
    question: 'How many numbers are in a 32 × 32 colour image with 3 channels?',
    answer: 3072,
    explanation: '32 × 32 × 3 = 3,072 inputs; a dense layer of 100 units would already need 307,200 weights.',
    reflection: 'Which invariances should a model for your image (or signal) data have? Which transformations would change the correct label?',
  },
  {
    id: 'l24-conv',
    title: '24.2 · The convolution operation',
    sections: ['Slide, multiply, sum', 'Kernels as feature detectors', 'Stride and padding', 'Output size', 'Channels'],
    skill: 'Compute a 2D convolution by hand, including stride and padding, and predict the output shape.',
    prerequisite: 'Lesson 24.1; dot products (Lab 01).',
    paragraphs: [
      'Place a small **kernel** (filter), say 3×3, over a 3×3 patch of the image. Multiply corresponding entries and add them up: one output number. Slide the kernel one position and repeat. The grid of outputs is a **feature map**. (Libraries compute cross-correlation — no kernel flip — and call it convolution; so do we.)',
      'The kernel decides what the output responds to. Sobel x, `[[−1, 0, 1], [−2, 0, 2], [−1, 0, 1]]`, is large where brightness increases from left to right: a vertical edge. A blur kernel averages; a sharpen kernel exaggerates differences. In a CNN the kernel values are **learned** by backpropagation.',
      '**Stride** s moves the kernel s pixels at a time, shrinking the output. **Padding** p adds p rings of zeros around the input so that border pixels are covered and, with p = 1 for a 3×3 kernel and stride 1, the output keeps the input size ("same" padding).',
      'For an n × n input, kernel k, stride s and padding p: output size `⌊(n + 2p − k)/s⌋ + 1`. A 12×12 image with k = 3, p = 1, s = 1 gives 12×12; with s = 2 it gives 6×6; with p = 0, s = 1 it gives 10×10.',
      'Colour images have 3 input channels; a kernel then has shape k × k × C_in and sums over all channels too. A layer applies C_out different kernels, producing C_out feature maps: weights k·k·C_in·C_out + C_out biases, regardless of image size.',
    ],
    formula: 'out[i, j] = Σ_{a,b} K[a, b] · x[i·s − p + a, j·s − p + b]     size = ⌊(n + 2p − k)/s⌋ + 1',
    experiment: 'In the explorer, load the digit, select "Vertical edges", and click a strongly orange output cell. Check by hand which input patch produced it.',
    question: 'An input is 12 × 12, the kernel 3 × 3, stride 2, padding 1. What is the output width?',
    answer: 6,
    explanation: '⌊(12 + 2 − 3)/2⌋ + 1 = ⌊11/2⌋ + 1 = 5 + 1 = 6.',
    reflection: 'Design (on paper) a 3×3 kernel that responds to a horizontal line. Test it in the explorer.',
  },
  {
    id: 'l24-sharing',
    title: '24.3 · Weight sharing, equivariance and pooling',
    sections: ['One detector, every position', 'Equivariance', 'Pooling', 'Invariance', 'Parameter efficiency'],
    skill: 'Explain weight sharing, translation equivariance and pooling, and quantify their parameter savings.',
    prerequisite: 'Lessons 24.1–24.2; shared inputs in backprop (Lab 20).',
    paragraphs: [
      'A convolutional layer uses the same kernel at every position: **weight sharing**. During backprop the kernel\'s gradient is the sum of contributions from every position — the accumulation rule from Lab 20.',
      'If the input shifts by one pixel, the feature map shifts by one pixel and is otherwise unchanged. This **translation equivariance** means a feature learned in one place is automatically detected everywhere.',
      '**Pooling** summarizes neighbourhoods: 2×2 max-pooling keeps the largest value in each 2×2 block, halving height and width. The exact position of a feature within the block no longer matters.',
      'Stack convolution, nonlinearity and pooling a few times, then pool globally over position, and the network becomes approximately **invariant** to shifts. The playground\'s fixed-filter model does exactly this and classifies digits at unseen positions with about 99% accuracy, where the pixel model manages about 20%.',
      'Parameter savings are dramatic: a 3×3 conv from 64 to 64 channels has 3·3·64·64 + 64 = 36,928 parameters whatever the image size; a dense layer between two 32×32×64 maps would need more than 4 billion.',
    ],
    formula: 'conv(shift(x)) = shift(conv(x))     max-pool 2×2: out[i, j] = max of x[2i:2i+2, 2j:2j+2]',
    experiment: 'Run the shifted-digit experiment with pixel features, then with convolutional features. Then enable augmentation for the pixel model and compare.',
    question: 'How many parameters does a 3 × 3 convolution from 16 input channels to 32 output channels have (including biases)?',
    answer: 4640,
    explanation: '3 × 3 × 16 × 32 = 4,608 weights plus 32 biases = 4,640.',
    reflection: 'When would translation invariance be wrong for your data? (Think of positions that carry meaning.)',
  },
  {
    id: 'l24-depth',
    title: '24.4 · Receptive fields and deep CNNs',
    sections: ['What one output sees', 'Growth through depth', 'A typical architecture', 'Why small kernels', 'Batch normalization and residuals'],
    skill: 'Compute receptive fields of stacked layers and describe a standard CNN architecture.',
    prerequisite: 'Lessons 24.1–24.3; vanishing gradients (Labs 20–22).',
    paragraphs: [
      'The **receptive field** of an output is the set of input pixels that can affect it. One 3×3 layer: 3×3. Two stacked 3×3 layers (stride 1): 5×5. L layers: (2L + 1) × (2L + 1). With stride or pooling the field grows much faster, because each later step covers more pixels.',
      'Early layers therefore see small patches and learn edges and colours; middle layers combine them into textures and parts; late layers, whose fields span most of the image, respond to objects. Clicking outputs in the explorer shows the single-layer field.',
      'A classic CNN repeats blocks of [convolution → nonlinearity → (pooling or strided convolution)], doubling channels as resolution halves, then global average pooling and a dense softmax layer. Two stacked 3×3 layers see as much as one 5×5 but use fewer parameters (18 versus 25 per channel pair) and add an extra nonlinearity.',
      'Very deep CNNs train well thanks to **batch normalization** (standardizing each channel over the mini-batch, which stabilizes gradients) and **residual connections** (`x + f(x)`, which give gradients a direct path back — the fix for vanishing gradients seen in Lab 22).',
      'You rarely design these from scratch: well-studied architectures (ResNet, EfficientNet, ConvNeXt) are the starting point, often with pretrained weights (Lesson 24.5).',
    ],
    formula: 'RF after L layers (kernel k, stride 1) = 1 + L(k − 1)',
    experiment: 'In "Receptive fields", compare 4 layers of k = 3 with stride 1 and with stride 2. How many layers does stride 1 need to reach a 17-pixel field?',
    question: 'What is the receptive field size of 4 stacked 3 × 3 convolutions with stride 1?',
    answer: 9,
    explanation: '1 + 4 × (3 − 1) = 9: each output sees a 9 × 9 patch.',
    reflection: 'For an object that fills about 60 pixels of your images, roughly how deep (or how strided) must a CNN be before a single unit can see all of it?',
  },
  {
    id: 'l24-practice',
    title: '24.5 · Augmentation, transfer learning and honest evaluation',
    sections: ['Augmentation', 'Transfer learning', 'Fine-tuning', 'Image-source leakage', 'Demonstrate understanding'],
    skill: 'Use augmentation and transfer learning, and evaluate image models without source leakage.',
    prerequisite: 'Lessons 24.1–24.4; evaluation (Lab 06).',
    paragraphs: [
      '**Data augmentation** creates label-preserving variations of training images — random crops and shifts, flips (when meaningful), small rotations, colour jitter. It encodes invariances you know to be true and acts as a strong regularizer. In the playground, shift augmentation lifts the pixel model from about 20% to about 85% on unseen positions. Apply it to training data only.',
      '**Transfer learning**: a network pretrained on millions of general images has learned broadly useful features. Replace its final layer with one for your classes and train only that layer (a "linear probe") — often excellent with a few hundred labeled images.',
      '**Fine-tuning** then unfreezes some or all layers and trains them with a small learning rate, adapting the features to your domain. Use the pretrained model\'s exact preprocessing (resizing and normalization statistics), or the features will not mean what they learned to mean.',
      'Images leak in their own ways: several photos of the same object, frames from the same video, patches from the same slide, images from the same camera or hospital. Split by **source** (Lab 06\'s group split), or the model will learn to recognize sources, backgrounds or watermarks instead of the target. Check a sample of correct predictions for suspicious cues.',
      'You have completed this lab when you can: compute a convolution and its output size; explain weight sharing, equivariance and pooling; compute receptive fields; choose augmentations; apply transfer learning; and design a leakage-free split for image data. The Python challenge implements convolution and pooling.',
    ],
    formula: 'linear probe: freeze pretrained f(·); train softmax(W f(x) + b)     fine-tune: unfreeze with lr ≈ 1/10',
    experiment: 'Run the pixel model with and without augmentation. Explain in the notebook why augmentation helped, and why the convolutional features barely needed it.',
    question: 'A dataset has 100 patients with 20 scans each. Using a patient-level split with 20% of patients held out, how many scans are in the test set?',
    answer: 400,
    explanation: '20 patients × 20 scans = 400 test scans; no patient appears on both sides.',
    reflection: 'List the ways images in your domain could share a source. Which split would you use?',
  },
]

export const sources = [
  { title: 'Dive into Deep Learning · Chapters 7–8: convolutional networks', url: 'https://d2l.ai/chapter_convolutional-neural-networks/index.html' },
  { title: 'CS231n · Convolutional neural networks', url: 'https://cs231n.github.io/convolutional-networks/' },
  { title: 'Dumoulin & Visin · A guide to convolution arithmetic for deep learning', url: 'https://arxiv.org/abs/1603.07285' },
  { title: 'He et al. (2016) · Deep residual learning for image recognition', url: 'https://arxiv.org/abs/1512.03385' },
]
