// Lesson order for Lab 30: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l30-tests': [
    { p: 0 }, { p: 1 }, { p: 2 }, { p: 3 },
    { cell: 0 },
    { predict: { prompt: 'The model test requires MAE < 12 s; the current model scores 8.3 s. A data bug in a retrain doubles every error. Does the model test still pass? (1 = yes, 0 = no)', answer: 0, explain: 'No: 2 × 8.3 = 16.6 s, above 12 s. That is the model test doing its job — the retrained model is blocked before it ships.' } },
    { p: 4 },
    { math: true },
  ],
  'l30-drift': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { predict: { prompt: 'Shares move from (0.5, 0.5) to (0.6, 0.4). What is the PSI? (Three decimals.)', answer: 0.041, tolerance: 0.001, explain: '0.1 · ln(0.6/0.5) + (−0.1) · ln(0.4/0.5) = 0.0182 + 0.0223 = 0.0405: “small” by the rule of thumb, although 10% of the traffic moved.', misconceptions: [{ answer: 0.018, feedback: 'Both bins contribute: the one that shrank adds (−0.1)·ln(0.8) = +0.022 too.' }] } },
    { p: 2 }, { p: 3 },
    { figure: 'PsiNoise', caption: 'PSI of n fresh values against a 3,000-value reference, over 300 simulated days. Change n and the real shift.' },
    { cell: 1 },
    { predict: { prompt: 'With 400 values per day and nothing changed, on roughly what percentage of days does PSI exceed 0.1?', answer: 0, tolerance: 1, explain: 'About 0%: the median is about 0.023 and even the 99th percentile about 0.06. With 80 values per day it is about 63% of days.' } },
    { p: 4 },
    { math: true },
  ],
  'l30-labels': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { figure: 'DriftMonitor', caption: 'Sixty days of monitoring for each scenario; the change starts on day 25. Change the label delay and the persistence.' },
    { predict: { prompt: 'In the concept-drift scenario, roughly what is the runner PSI? (Two decimals.)', answer: 0, tolerance: 0.01, explain: 'About 0 (0.004 in the cell): the inputs did not change, so no input monitor can see concept drift. Only the error — known when the labels arrive — reveals it.' } },
    { p: 2 },
    { cell: 1 },
    { predict: { prompt: 'A change starts on day 25, the error alert needs 2 consecutive bad days, and labels arrive 20 days late. On which day can the alert fire at the earliest?', answer: 46, explain: '25 + (2 − 1) + 20 = 46: the second bad day (26) becomes measurable 20 days later.', misconceptions: [{ answer: 45, feedback: 'Persistence 2 needs day 26 as well: 26 + 20 = 46.' }, { answer: 26, feedback: 'That would be the day with immediate labels. Add the 20-day delay.' }] } },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l30-alerts': [
    { p: 0 }, { p: 1 },
    { predict: { prompt: 'A threshold sits at the 99th percentile of quiet days. With persistence 1, how many false alarms do you expect in 365 quiet days? (One decimal.)', answer: 3.65, tolerance: 0.06, explain: 'Each quiet day exceeds the 99th percentile with probability 1%: 365 × 0.01 = 3.65 a year. The cell’s simulated year had 4.', misconceptions: [{ answer: 0, feedback: 'A 99th percentile is exceeded by 1% of quiet days by definition.' }] } },
    { p: 2 },
    { cell: 0 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l30-respond': [
    { p: 0 },
    { predict: { prompt: 'In the playground’s pipeline bug, an upstream service starts sending sizes in KB instead of MB. By what factor is every size inflated?', answer: 1024, explain: '1 MB = 1024 KB, so every size is 1024 times too large — a size PSI above 8 and predictions of hours. A guard on the prediction range blocks them at once.', misconceptions: [{ answer: 1000, feedback: 'The engine uses 1 MB = 1024 KB; either way, a jump of three orders of magnitude.' }] } },
    { p: 1 }, { p: 2 },
    { cell: 0 },
    { p: 3 }, { p: 4 },
    { math: true },
    { ladder: 'monitor' },
  ],
}
