export const lessons = [
  {
    id: 'l30-tests',
    title: '30.1 · Tests for ML systems',
    sections: ['Code, data and model', 'Unit tests', 'Data tests', 'Model tests', 'Put it into practice'],
    skill: 'Write unit, data and model tests that catch ML failures before deployment.',
    prerequisite: 'Labs 01–29; contracts (Lab 28) and serving tests (Lab 29).',
    paragraphs: [
      'An ML system can break in its code, its data or its model. Ordinary software tests cover the first; ML adds the other two. All three belong in continuous integration, running on every change.',
      '**Unit tests** check deterministic pieces with known answers: a feature function on hand-made inputs, a loss against a hand calculation, a gradient against finite differences (Lab 20), a split that never overlaps (Lab 06).',
      '**Data tests** apply the contract (Lab 28) to training and serving data: schema, ranges, uniqueness, missing-value rates, and distribution checks against reference statistics.',
      '**Model tests** check behaviour rather than code: minimum accuracy on a fixed evaluation set; performance on important slices (each language, each runner); invariance tests (renaming a job should not change its prediction); directional tests (a larger build should not be predicted faster, all else equal); and the golden-set and parity tests from Lab 29.',
      'Procedure: for each failure you have seen or can imagine, write the test that would catch it; run the fast tests on every commit and the slow ones before each release; treat a failing model test like a failing unit test — it blocks the release.',
    ],
    formula: 'CI = unit tests (code) + data tests (contract, drift) + model tests (thresholds, slices, invariance, direction)',
    experiment: 'For each of the four production scenarios, name one pre-deployment test that could have caught it — or explain why none could.',
    question: 'A directional test checks that doubling a build\'s size never lowers its prediction. It runs on 200 test builds and 3 fail. What fraction failed? (Three decimals.)',
    answer: 0.015, tolerance: 0.0001,
    explanation: '3/200 = 0.015. Any failure deserves investigation; a monotonic relationship the model violates is a bug or a data problem.',
    reflection: 'Write one invariance test and one directional test for a model you know.',
  },
  {
    id: 'l30-drift',
    title: '30.2 · Measuring drift',
    sections: ['Kinds of change', 'Population Stability Index', 'Other distances', 'Noise in the measurement', 'Categorical features'],
    skill: 'Quantify input and prediction drift with PSI and understand its sampling noise.',
    prerequisite: 'Lesson 30.1; distributions (Lab 04), distribution checks (Lab 28).',
    paragraphs: [
      '**Covariate shift**: the input distribution changes (more jobs on shared runners). **Concept drift**: the relationship between inputs and target changes (a new cache makes hits faster). **Label shift**: the target distribution changes. Pipeline bugs look like extreme covariate shift. Each needs a different response.',
      'The **Population Stability Index** compares a current distribution with a reference: bin the reference (e.g. into deciles), compute the share of reference (e) and current (a) values per bin, and sum `(a − e)·ln(a/e)`. With shares (0.5, 0.5) moving to (0.7, 0.3): 0.2·ln(1.4) + (−0.2)·ln(0.6) ≈ 0.067 + 0.102 = 0.170.',
      'Common rules of thumb: PSI below 0.1 is small, 0.1–0.25 moderate, above 0.25 large. Alternatives include the Kolmogorov–Smirnov statistic for continuous features and the Jensen–Shannon distance; all summarize "how different are these distributions" in one number.',
      'Every drift statistic is noisy for small samples: comparing 80 fresh values in 10 bins with the reference gives a typical PSI near 0.17 even when nothing changed — which would trip a 0.1 threshold daily. The playground uses 400 requests per day. Estimate the no-change distribution of your statistic from quiet historical periods before choosing thresholds.',
      'For categories, compute PSI directly on category shares, and treat never-seen categories as an alert on their own. Monitor prediction drift the same way; it needs no labels.',
    ],
    formula: 'PSI = Σ_bins (a_i − e_i) · ln(a_i / e_i)',
    experiment: 'Choose "Nothing changes" and lower the PSI threshold to 0.05. How many false alarms appear? Then set persistence to 3 days.',
    question: 'Shares move from (0.5, 0.5) to (0.7, 0.3). What is the PSI? (Three decimals.)',
    answer: 0.1695, tolerance: 0.001,
    explanation: '0.2·ln(0.7/0.5) + (−0.2)·ln(0.3/0.5) = 0.2·0.336 + 0.2·0.511 ≈ 0.169.',
    reflection: 'Which of your features would you monitor for drift, and at what sample size per window?',
  },
  {
    id: 'l30-labels',
    title: '30.3 · Delayed labels and proven performance loss',
    sections: ['Drift is not harm', 'Harm without drift', 'Waiting for labels', 'Proxies', 'Deciding with incomplete information'],
    skill: 'Distinguish input drift from measured performance loss and plan for delayed labels.',
    prerequisite: 'Lessons 30.1–30.2.',
    paragraphs: [
      'In the covariate-shift scenario, most jobs move to shared runners. Input drift alarms fire — but the model already knows how shared runners behave, and its error barely changes. Drift is a reason to look, not proof of harm.',
      'In the concept-drift scenario, a new cache makes cache hits much faster. The inputs look exactly as before, so every input monitor stays quiet — yet predictions are now too high. Only comparing predictions with true outcomes reveals it.',
      'True durations are known only after builds finish; in many domains labels arrive days or months later (loan defaults, churn), or never (rejected applications). With a 7-day delay, the error curve lags a week behind reality — the shaded region in the playground.',
      'Proxies can shorten the wait: early partial labels, user feedback, a sample labeled quickly by humans, or agreement with a simpler reference model. Each is imperfect; say what it measures.',
      'Decide with what you know: input and prediction drift justify investigation and closer watching; confirmed error increases justify retraining or rollback; sudden extreme jumps in everything at once point to a pipeline bug and justify immediate rollback.',
    ],
    formula: 'error measurable on day t only for predictions made before t − delay',
    experiment: 'Run the concept-drift scenario with label delays 0, 7 and 20. On which day is the problem first provable in each case?',
    question: 'A change begins on day 25, an error alert needs 2 consecutive bad days, and labels arrive 7 days late. On which day, at the earliest, can the alert fire?',
    answer: 33,
    explanation: 'The second bad day is day 26; its labels arrive 7 days later, on day 33.',
    reflection: 'How long are labels delayed in your domain? What proxy could you monitor in the meantime?',
  },
  {
    id: 'l30-alerts',
    title: '30.4 · Alerts that people trust',
    sections: ['Alert fatigue', 'Thresholds from quiet periods', 'Persistence and severity', 'Guards', 'Runbooks'],
    skill: 'Design alerts with sensible thresholds, persistence rules, guards and runbooks.',
    prerequisite: 'Lessons 30.1–30.3; thresholds and costs (Lab 09).',
    paragraphs: [
      'An alert that fires daily for nothing gets ignored — and then the real one is ignored too. Every alert is a classifier with false positives and false negatives, and the costs of each (Lab 09) should set its threshold.',
      'Set thresholds from the statistic\'s behaviour during quiet periods: for example, above the 99th percentile of historical daily values. Use separate severities: "investigate" for moderate drift, "page someone" for guard violations and confirmed error increases.',
      'Require persistence — N consecutive windows above threshold — to filter one-day noise. Persistence delays detection by N − 1 windows: a trade-off between false alarms and reaction time.',
      '**Guards** are hard limits enforced on every prediction, not statistics: a predicted duration outside [1 s, 24 h] is rejected and replaced by the fallback (Lab 29). In the bug scenario, a guard would have stopped absurd predictions before any user saw them — no drift statistic needed.',
      'Every alert links to a **runbook**: what it means, what to check first (recent deployments, upstream changes, the contract report), and how to roll back. The best time to write the runbook is before the alert first fires.',
    ],
    formula: 'alert if statistic > threshold for N consecutive windows · guard: reject predictions outside [min, max]',
    experiment: 'In the bug scenario, compare persistence 1 and 3. How many days of absurd predictions does each allow without a guard?',
    question: 'A metric is checked daily with persistence N = 3. A change starts on day 40 and exceeds the threshold every day after. On which day does the alert fire?',
    answer: 42,
    explanation: 'Days 40, 41 and 42 are the three consecutive days; the alert fires on day 42.',
    reflection: 'Write the runbook entry for the most likely failure of a model you know.',
  },
  {
    id: 'l30-respond',
    title: '30.5 · Responding: investigate, retrain or roll back',
    sections: ['Match the response to the cause', 'Rollback', 'Retraining', 'After the incident', 'Demonstrate understanding'],
    skill: 'Choose and execute a safe response to a detected problem.',
    prerequisite: 'Lessons 30.1–30.4; versioning (Lab 28).',
    paragraphs: [
      'Pipeline bug (inputs and predictions jump together, contract or guard violations): roll back the change or block the bad feed immediately; fix upstream. Retraining would teach the model the bug.',
      'Concept drift (error rises with confirmed labels, inputs stable): retrain on recent data, validate on the most recent period (Lab 19\'s forward-chaining logic), and compare with the current model before promoting (Lab 32).',
      'Covariate shift without error increase: keep serving, keep watching, and check slices — the average may hide a segment that got worse. Consider collecting more data where the distribution moved.',
      '**Rollback** requires the previous artifact and its exact preprocessing to still exist (Lab 28\'s immutable versions) and a tested procedure to switch. Practise it before you need it.',
      'You have completed this lab when you can: write unit, data and model tests; compute PSI and understand its noise; separate drift from proven performance loss under delayed labels; design alerts with thresholds, persistence and guards; and choose the right response. Write a short post-incident review for each playground scenario: what happened, how it was detected, what fixed it, and what test or alert will catch it next time.',
    ],
    formula: 'bug → rollback · concept drift → retrain + validate · covariate shift → investigate + watch slices',
    experiment: 'Diagnose each of the four scenarios before revealing it. Record your diagnosis, the evidence, and your response.',
    question: 'You can roll back only if the previous model version\'s artifact still exists. If you keep the last 3 versions and deploy weekly, how many weeks back can you roll back at most?',
    answer: 3,
    explanation: 'With the last 3 artifacts retained and one deployment per week, the oldest reachable version is 3 weeks old.',
    reflection: 'What would your team need to do today to be able to roll back a model within 10 minutes?',
  },
]

export const sources = [
  { title: 'Breck et al. (2017) · The ML test score: a rubric for ML production readiness', url: 'https://research.google/pubs/pub46555/' },
  { title: 'Ribeiro et al. (2020) · Beyond accuracy: behavioral testing with CheckList', url: 'https://arxiv.org/abs/2005.04118' },
  { title: 'Rabanser et al. (2019) · Failing loudly: detecting dataset shift', url: 'https://arxiv.org/abs/1810.11953' },
  { title: 'Evidently AI · data drift concepts', url: 'https://docs.evidentlyai.com/' },
]
