export const lessons = [
  {
    id: 'l56-scarce',
    title: '56.1 · When labels are the bottleneck',
    sections: ['Cheap data, expensive labels', 'Three strategies', 'Assumptions that make it work', 'Honest evaluation', 'Put it into practice'],
    skill: 'Choose among semi-supervised, active and self-supervised learning for a label-scarce problem.',
    prerequisite: 'Evaluation (Lab 06), clustering (Lab 17), autoencoders (Lab 53), embeddings (Labs 25, 34).',
    paragraphs: [
      'Raw data are often plentiful — logs, images, documents — while labels need experts, time and money. Three families of methods make the most of a small labelling budget.',
      '**Semi-supervised learning** uses the unlabelled data to shape the model directly (this lab: label propagation and self-training). **Active learning** chooses which examples are worth labelling. **Self-supervised learning** invents a training task from unlabelled data alone, learns a representation, and then needs few labels on top.',
      'They rely on assumptions: the **cluster assumption** (points in one dense region share a label), the **manifold assumption** (labels vary smoothly along the data’s shape), and for self-supervision, that the invented task requires features useful for the real one. When these fail, unlabelled data can hurt.',
      'Evaluation must stay honest: keep a random, labelled test set that no method chose or pseudo-labelled; compare with the supervised baseline on the same labels; and repeat over several choices of labelled points — with two labels, which two matters enormously.',
      'Procedure: start with a supervised baseline on the labels you have; try the cheapest method that exploits your unlabelled data; and consider spending part of the budget on labels chosen by active learning rather than at random.',
    ],
    formula: 'data = few labelled (x, y) + many unlabelled x     test on a separate random labelled set',
    derivation: {
      title: 'The value of a label',
      steps: [
        { prompt: 'Labelling costs 2 minutes per image. How many hours for 3,000 images?', number: 100, show: '`6,000 min = 100 h`' },
        { prompt: 'If active learning reaches the same accuracy with a third of the labels, how many hours are saved?', number: 100 * 2 / 3, tolerance: 0.01, show: '`≈ 66.7 h`' },
      ],
      result: 'Methods that save labels often matter more than a better model architecture.',
    },
    experiment: 'In the semi-supervised view with 1 label per class, move the seed through all five choices of labelled points. How much does the supervised classifier’s accuracy vary?',
    question: 'You have 20 labels and 20,000 unlabelled examples. Which set must never be touched by pseudo-labelling or active selection? (1 = the test set, 2 = the unlabelled pool)',
    answer: 1,
    explanation: 'The test set: it must remain a random, independently labelled sample, or the evaluation is biased.',
    reflection: 'Where in your work are labels the bottleneck? Estimate what a label costs.',
  },
  {
    id: 'l56-semi',
    title: '56.2 · Semi-supervised learning',
    sections: ['Graphs over all the data', 'Label propagation', 'Self-training and pseudo-labels', 'Confirmation bias', 'Consistency regularization'],
    skill: 'Apply label propagation and self-training and recognize when they fail.',
    prerequisite: 'Lesson 56.1; k-nearest neighbours (Lab 10); graphs (Lab 45).',
    paragraphs: [
      '**Label propagation** builds a graph connecting each point to its nearest neighbours (edge weights decay with distance), then repeatedly lets every point take a weighted average of its neighbours’ label scores while labelled points keep pulling toward their true labels. Labels flow along dense regions and stop at gaps.',
      'On two moons with one label per class, the playground’s supervised classifier can only separate the two labelled points; label propagation follows each moon and reaches far higher accuracy from the same two labels.',
      '**Self-training** fits a model on the labels, predicts the unlabelled pool, adds the most confident predictions as **pseudo-labels**, and retrains, repeatedly. It works with any classifier and is widely used in practice (e.g. with large pretrained models).',
      'Its weakness is **confirmation bias**: if the first model is wrong about a region, it confidently pseudo-labels that region wrongly and then trains on its own mistake. With two labels it can end up worse than the supervised baseline — the playground shows this for some seeds.',
      'Modern methods add **consistency regularization**: the model should predict the same label for different augmentations of an unlabelled input (FixMatch combines this with confident pseudo-labels). All rely on the cluster and manifold assumptions.',
    ],
    formula: 'label propagation: F ← α S F + (1 − α) Y,  S = D^(−1/2) W D^(−1/2)     self-training: add {x : max p(y | x) > τ}',
    derivation: {
      title: 'One propagation step',
      intro: 'A point connected to two neighbours with normalized weights 0.6 and 0.4. Neighbour scores for class 1: 0.9 and 0.2. The point is unlabelled (its own Y is 0). α = 0.99.',
      steps: [
        { prompt: 'Weighted neighbour average?', number: 0.62, tolerance: 1e-9, show: '`0.6×0.9 + 0.4×0.2 = 0.62`' },
        { prompt: 'New score after one step: α × average + (1 − α) × 0? (Four decimals.)', number: 0.99 * 0.62, tolerance: 1e-4, show: '`≈ 0.6138`' },
      ],
      result: 'Scores diffuse through the graph; labelled points act as sources that keep them anchored.',
    },
    experiment: 'In the semi-supervised view, compare the three methods’ decision regions with 1, 3 and 10 labels per class. When does the advantage of unlabelled data disappear?',
    question: 'Self-training adds 300 pseudo-labels of which 60 are wrong. What fraction of the added labels are wrong?',
    answer: 0.2, tolerance: 1e-9,
    explanation: '60 / 300 = 20% — and the model will now be trained to repeat those mistakes.',
    reflection: 'Which assumption — clusters or smoothness — would hold for your data, and how would you check?',
  },
  {
    id: 'l56-active',
    title: '56.3 · Active learning',
    sections: ['Let the model ask', 'Uncertainty sampling', 'Other strategies', 'Pitfalls', 'In production'],
    skill: 'Run pool-based active learning and evaluate it correctly.',
    prerequisite: 'Lessons 56.1–56.2; calibration (Lab 09); bandits (Lab 50).',
    paragraphs: [
      'In **pool-based active learning**, the model is trained on the current labels, scores every unlabelled point, and asks an annotator to label the most useful one; then it retrains and repeats.',
      '**Uncertainty sampling** queries the point the model is least sure about — probability closest to 0.5 for two classes, or the smallest margin between the top two classes. Those points sit near the current boundary, exactly where a label moves it most. In the playground, after 4 random labels plus 8 queries, uncertainty sampling reaches close to 99% accuracy while random labels reach about 88%.',
      'Alternatives: query-by-committee (where an ensemble disagrees), expected model change, diversity or density weighting (avoid querying many near-duplicates or outliers), and batch-mode selection when labels are gathered in rounds.',
      'Pitfalls: a badly wrong initial model may never ask about regions it is confidently wrong about (a sampling bias similar to Lab 35’s feedback loops); uncertainty relies on reasonably calibrated probabilities; and the labelled set is not a random sample, so it cannot serve as a test set.',
      'Active learning resembles the bandit trade-off of Lab 50: exploit (label near the boundary) versus explore (label elsewhere to catch surprises). Mixing in a few random queries is a cheap safeguard.',
    ],
    formula: 'query = argmin_x |p(y = 1 | x) − 0.5|     (margin: argmin p₁ − p₂ for the top two classes)',
    derivation: {
      title: 'Pick the next query',
      steps: [
        { prompt: 'Candidates have predicted probabilities 0.93, 0.58, 0.12 and 0.47. Which probability does uncertainty sampling pick?', number: 0.47, tolerance: 1e-9, show: '`0.47` (|0.47 − 0.5| = 0.03)' },
        { prompt: 'Write the uncertainty score |p − 0.5| as a function of p.', answer: 'abs(p - 0.5)', show: '`|p − 0.5|`', vars: { p: [0, 1] } },
      ],
      result: 'The query is the point the model finds hardest — informative, but also possibly an outlier.',
    },
    experiment: 'In the active-learning view, step through the queries with uncertainty sampling and watch where they land. Then switch to random and compare the learning curves.',
    question: 'Random labelling needs 20 labels to reach 95% accuracy; uncertainty sampling needs 8. By what fraction does active learning cut the labelling cost?',
    answer: 0.6, tolerance: 1e-9,
    explanation: '(20 − 8) / 20 = 0.6: 60% fewer labels for the same accuracy.',
    reflection: 'If you ran active learning in your domain, who would label the queries, and how fast would they need to be?',
  },
  {
    id: 'l56-contrastive',
    title: '56.4 · Self-supervised and contrastive learning',
    sections: ['Invent a task', 'Pretext tasks', 'Contrastive learning', 'InfoNCE', 'Linear probes'],
    skill: 'Explain contrastive self-supervised learning and evaluate representations with linear probes.',
    prerequisite: 'Lessons 56.1–56.3; augmentation (Lab 52); information theory (Lab 46).',
    paragraphs: [
      'Self-supervised learning creates labels from the data itself. Pretext tasks include predicting a hidden part of the input (masked words in BERT, masked image patches), predicting the next token (language models, Lab 55), or recognizing which transformation was applied.',
      '**Contrastive learning** creates pairs: two random augmentations of the same example are a positive pair; views of other examples in the batch are negatives. An encoder maps each view to an embedding, and training pulls positives together and pushes negatives apart.',
      'The **InfoNCE** loss treats this as classification: for each view, pick its partner out of all 2N − 1 other views, with similarities (cosine, divided by a temperature τ) as logits: −log[exp(s⁺/τ) / Σ exp(s/τ)]. Minimizing it maximizes a lower bound on the mutual information between the two views (Lab 46).',
      'Augmentations define what the representation ignores: here, one-pixel shifts and ink noise, so the embedding keeps the digit identity. Choose augmentations that preserve the label you will eventually care about (Lab 52).',
      'Evaluate a representation with a **linear probe**: freeze the encoder and train a linear classifier on a few labels. In the playground, with one label per digit, the probe on learned embeddings is far more accurate than the same probe on raw pixels.',
    ],
    formula: 'ℓᵢ = −log [ exp(sim(zᵢ, zᵢ⁺)/τ) / Σ_{j≠i} exp(sim(zᵢ, z_j)/τ) ]     sim = cosine',
    derivation: {
      title: 'InfoNCE for one view',
      intro: 'A view has cosine similarity 0.9 with its partner and 0.1, 0.2 with two negatives; τ = 0.5.',
      steps: [
        { prompt: 'Logits s/τ: partner?', number: 1.8, tolerance: 1e-9, show: '`1.8`' },
        { prompt: 'Loss −log[e^1.8 / (e^1.8 + e^0.2 + e^0.4)]? (Four decimals.)', number: -Math.log(Math.exp(1.8) / (Math.exp(1.8) + Math.exp(0.2) + Math.exp(0.4))), tolerance: 1e-4, show: '`≈ 0.3576`' },
        { prompt: 'Write the loss for partner logit a and negative logits b, c.', answer: '-a + log(exp(a) + exp(b) + exp(c))', show: '`−a + log(e^a + e^b + e^c)`', vars: { a: [-2, 2], b: [-2, 2], c: [-2, 2] } },
      ],
      result: 'InfoNCE is softmax cross-entropy where the “class” is the matching view.',
    },
    experiment: 'In the contrastive view, pretrain the encoder and compare the two PCA maps. Which one groups digits? Then read the probe table at 1 label per digit.',
    question: 'A contrastive batch has N = 50 images and 2 views each. How many candidates does each view choose its partner from?',
    answer: 99,
    explanation: 'All 2N = 100 views except itself: 99 candidates, one positive and 98 negatives.',
    reflection: 'Which augmentations of your data would preserve the property you care about, and which would destroy it?',
  },
  {
    id: 'l56-practice',
    title: '56.5 · Putting it together',
    sections: ['Pretrain, then adapt', 'Combining strategies', 'Weak supervision', 'Cost and quality of labels', 'Demonstrate understanding'],
    skill: 'Design a label-efficient learning pipeline and state its assumptions and evaluation.',
    prerequisite: 'Lessons 56.1–56.4.',
    paragraphs: [
      'The dominant modern recipe: **pretrain** a large encoder with self-supervision on unlabelled data (or reuse a public one), then **adapt** it with few labels — a linear probe, fine-tuning, or prompting a language model (Lab 55).',
      'Strategies combine: active learning to choose labels, semi-supervised learning to use the rest, self-supervised pretraining under both. Each adds assumptions; add them one at a time and measure each on the same held-out set.',
      '**Weak supervision** replaces hand labels with noisy sources — heuristics, keyword rules, existing databases, or model predictions — combined into probabilistic labels. It scales labelling cheaply, at the cost of label noise that must be modelled or audited.',
      'Label quality matters as much as quantity: write clear guidelines, measure annotator agreement, relabel disagreements, and track the cost per label. A small, clean labelled set often beats a large noisy one — especially as the test set.',
      'You have completed this lab when you can: state the assumptions behind using unlabelled data; apply label propagation and self-training and recognize confirmation bias; run and evaluate active learning; explain contrastive learning and InfoNCE and evaluate with linear probes; and design a label-efficient pipeline. The Python challenge implements label propagation, uncertainty sampling, pseudo-labelling and the InfoNCE loss.',
    ],
    formula: 'pipeline: self-supervised pretraining → (active) labelling → semi-supervised or fine-tuned adaptation → honest test',
    derivation: {
      title: 'Annotator agreement',
      steps: [
        { prompt: 'Two annotators agree on 170 of 200 items. Raw agreement rate?', number: 0.85, tolerance: 1e-9, show: '`0.85`' },
        { prompt: 'If chance agreement is 0.5, Cohen’s κ = (0.85 − 0.5)/(1 − 0.5)?', number: 0.7, tolerance: 1e-9, show: '`0.7`' },
      ],
      result: 'κ corrects agreement for chance; below about 0.6, labels are too noisy to trust without review.',
    },
    experiment: 'Using all three views, decide how you would label a new dataset of 10,000 images with a budget of 100 labels. Which methods would you combine, and in what order?',
    question: 'A linear probe on pretrained features uses 10 labels per class for 10 classes. How many labelled examples in total?',
    answer: 100,
    explanation: '10 × 10 = 100 labelled examples; everything else came from unlabelled data.',
    reflection: 'Sketch a label-efficient pipeline for a problem you care about. Which assumption is most likely to fail?',
  },
]

export const sources = [
  { title: 'Zhou et al. (2004) · Learning with local and global consistency (label propagation)', url: 'https://papers.nips.cc/paper/2003/hash/87682805257e619d49b8e0dfdc14affa-Abstract.html' },
  { title: 'Settles (2009) · Active learning literature survey', url: 'https://burrsettles.com/pub/settles.activelearning.pdf' },
  { title: 'Chen et al. (2020) · A simple framework for contrastive learning of visual representations (SimCLR)', url: 'https://arxiv.org/abs/2002.05709' },
  { title: 'Sohn et al. (2020) · FixMatch: simplifying semi-supervised learning with consistency and confidence', url: 'https://arxiv.org/abs/2001.07685' },
]
