// Where the math behind each ML lesson is taught in depth elsewhere in the app.
// Lessons teach the math they use themselves; these links are for going deeper,
// practising, or reviewing a prerequisite. `href` is a hash route.
//   course lessons: /chapter/<course>-<chapter>/<lesson-slug>  (checked by mathLinks.test.js)
//   tools:          the lab's own route from its meta.js
const lesson = (course, chapter, slug, title, note) => ({ kind: 'lesson', href: `/chapter/${course}-${chapter}/${slug}`, course, chapter, slug, title, note })
const tool = (href, title, note, lab) => ({ kind: 'tool', href, title, note, lab })
const reference = (href, title, note) => ({ kind: 'reference', href, title, note })

export const COURSE_NAMES = {
  'linear-algebra': 'Linear Algebra', calculus: 'Calculus', precalculus: 'Precalculus', 'applied-statistics': 'Applied Statistics',
  'discrete-math': 'Discrete Math', 'dynamic-programming': 'Dynamic Programming', 'ai-engineering': 'AI Engineering', 'data-science': 'Data Science',
  'machine-learning': 'Machine Learning',
}

export const MATH_LINKS = {
  // ---------- Linear algebra ----------
  'la.vectors': lesson('linear-algebra', 1, 'what-is-a-vector', 'What is a vector?'),
  'la.span': lesson('linear-algebra', 1, 'linear-combinations', 'Linear combinations, span and basis'),
  'la.dot': lesson('linear-algebra', 1, 'dot-and-cross-products', 'Dot and cross products'),
  'la.systems': lesson('linear-algebra', 1, 'systems-of-linear-equations', 'Systems of linear equations'),
  'la.independence': lesson('linear-algebra', 1, 'linear-independence', 'Linear independence'),
  'la.transform': lesson('linear-algebra', 2, 'matrices-as-transformations', 'Matrices as linear transformations'),
  'la.matmul': lesson('linear-algebra', 2, 'matrix-multiplication', 'Matrix multiplication as composition'),
  'la.inverse': lesson('linear-algebra', 2, 'inverse-matrices', 'Inverse matrices and determinants'),
  'la.subspaces': lesson('linear-algebra', 2, 'four-fundamental-subspaces', 'The four fundamental subspaces'),
  'la.special': lesson('linear-algebra', 2, 'special-matrices', 'Symmetric, orthogonal and positive definite matrices'),
  'la.matcalc': lesson('linear-algebra', 2, 'matrix-calculus', 'Matrix calculus: gradients, Jacobians and Hessians'),
  'la.eigen': lesson('linear-algebra', 3, 'eigenvectors-and-eigenvalues', 'Eigenvectors and eigenvalues'),
  'la.diag': lesson('linear-algebra', 3, 'diagonalization', 'Change of basis and diagonalization'),
  'la.markov': lesson('linear-algebra', 3, 'markov-chains', 'Markov chains and steady states'),
  'la.projection': lesson('linear-algebra', 4, 'orthogonal-projections', 'Orthogonal projections'),
  'la.gramschmidt': lesson('linear-algebra', 4, 'gram-schmidt', 'Gram–Schmidt orthogonalization'),
  'la.leastsq': lesson('linear-algebra', 4, 'least-squares', 'Least squares'),
  'la.svd': lesson('linear-algebra', 4, 'svd', 'Singular value decomposition'),
  'la.inner': lesson('linear-algebra', 4, 'inner-product-spaces', 'Inner product spaces'),
  'la.spectral': lesson('linear-algebra', 4, 'spectral-theorem', 'The spectral theorem'),
  'la.quadratic': lesson('linear-algebra', 4, 'quadratic-forms', 'Quadratic forms and principal axes'),
  'la.pinv': lesson('linear-algebra', 4, 'pseudoinverse', 'The pseudoinverse'),
  'la.lowrank': lesson('linear-algebra', 4, 'low-rank-approximation', 'Low-rank approximation'),
  'la.numpy': lesson('linear-algebra', 5, 'numpy-scipy-intro', 'NumPy and SciPy for linear algebra'),
  'la.pysolve': lesson('linear-algebra', 5, 'solving-systems-python', 'Solving linear systems in Python'),
  'la.pyeig': lesson('linear-algebra', 5, 'eigenvalues-python', 'Eigenvalues and eigenvectors in Python'),
  'la.pysvd': lesson('linear-algebra', 5, 'svd-applications', 'SVD applications in Python'),
  'la.factor': lesson('linear-algebra', 5, 'scipy-factorizations', 'LU, Cholesky and QR in SciPy'),
  'la.implement': lesson('linear-algebra', 5, 'implement-algorithms', 'Implementing algorithms from scratch'),
  'la.basis': lesson('linear-algebra', 6, 'coordinates-change-of-basis', 'Coordinates and change of basis'),
  'la.qr': lesson('linear-algebra', 7, 'qr-decomposition', 'QR decomposition'),
  'la.cholesky': lesson('linear-algebra', 7, 'cholesky-decomposition', 'Cholesky decomposition'),
  'la.conditioning': lesson('linear-algebra', 7, 'matrix-norms-conditioning', 'Matrix norms and conditioning'),
  'la.stability': lesson('linear-algebra', 7, 'numerical-stability', 'Numerical stability and pivoting'),
  'la.sparse': lesson('linear-algebra', 7, 'sparse-matrices', 'Sparse matrices'),
  'la.pca': lesson('linear-algebra', 8, 'pca-dimensionality-reduction', 'PCA and dimensionality reduction'),
  'la.pagerank': lesson('linear-algebra', 8, 'markov-pagerank', 'Markov chains and PageRank'),
  'la.iterative': lesson('linear-algebra', 9, 'jacobi-gauss-seidel', 'Jacobi and Gauss–Seidel iteration'),
  'la.cg': lesson('linear-algebra', 9, 'conjugate-gradient', 'Conjugate gradient'),
  'la.tensor': lesson('linear-algebra', 10, 'tensor-products', 'Tensor products'),
  'la.hilbert': lesson('linear-algebra', 10, 'banach-hilbert-spaces', 'Banach and Hilbert spaces'),

  // ---------- Calculus and precalculus ----------
  'calc.functions': lesson('calculus', 1, 'functions', 'Functions'),
  'calc.exp': lesson('calculus', 1, 'exponentials', 'Exponentials and logarithms'),
  'calc.rate': lesson('calculus', 2, 'rate-of-change', 'Rate of change and the difference quotient'),
  'calc.limits': lesson('calculus', 2, 'limits-at-infinity', 'Limits at infinity'),
  'calc.derivative': lesson('calculus', 3, 'derivatives-introduction', 'Derivatives: the slope machine'),
  'calc.rules': lesson('calculus', 3, 'differentiation-rules', 'Differentiation rules'),
  'calc.chain': lesson('calculus', 3, 'chain-rule', 'The chain rule'),
  'calc.explog': lesson('calculus', 3, 'exp-log-derivatives', 'Derivatives of exponentials and logarithms'),
  'calc.linapprox': lesson('calculus', 4, 'linear-approximation', 'Linear approximation'),
  'calc.secondderiv': lesson('calculus', 4, 'concavity-second-derivative-test', 'Concavity and the second derivative test'),
  'calc.optim': lesson('calculus', 4, 'optimization', 'Optimization'),
  'calc.newton': lesson('calculus', 4, 'newtons-method', 'Newton’s method'),
  'calc.sum': lesson('calculus', 5, 'summation-notation', 'Summation notation'),
  'calc.integral': lesson('calculus', 5, 'definite-integral', 'The definite integral'),
  'calc.improper': lesson('calculus', 5, 'improper-integrals', 'Improper integrals'),
  'calc.numint': lesson('calculus', 5, 'numerical-integration', 'Numerical integration'),
  'calc.sequences': lesson('calculus', 6, 'sequences', 'Sequences'),
  'calc.series': lesson('calculus', 6, 'series-intro', 'Infinite series (including geometric series)'),
  'calc.taylor': lesson('calculus', 6, 'taylor-maclaurin', 'Taylor and Maclaurin series'),
  'calc.vectors': lesson('calculus', 7, 'vectors', 'Vectors in 2D and 3D'),
  'pre.log': lesson('precalculus', 4, 'log-properties', 'Properties of logarithms'),
  'pre.exp': lesson('precalculus', 4, 'exponential-functions', 'Exponential functions'),
  'pre.dot': lesson('precalculus', 5, 'vectors-dot-product', 'The dot product'),
  'pre.lp': lesson('precalculus', 2, 'linear-programming', 'Linear programming and optimization'),
  'pre.trig': lesson('precalculus', 3, 'graphing-trig-functions', 'Graphing trig functions'),

  // ---------- Probability and statistics ----------
  'stat.sampling': lesson('applied-statistics', 1, 'sampling-methods', 'Sampling methods'),
  'stat.bias': lesson('applied-statistics', 1, 'study-design-and-bias', 'Study design and bias'),
  'stat.ci': lesson('applied-statistics', 1, 'confidence-intervals', 'Confidence intervals from first principles'),
  'stat.pandas': lesson('applied-statistics', 2, 'data-frames-with-pandas', 'Data frames with pandas'),
  'stat.plotting': lesson('applied-statistics', 2, 'python-for-data-visualization', 'Python for data visualization'),
  'stat.center': lesson('applied-statistics', 3, 'measures-of-center', 'Measures of center'),
  'stat.spread': lesson('applied-statistics', 3, 'measures-of-spread', 'Measures of spread'),
  'stat.percentiles': lesson('applied-statistics', 3, 'percentiles-and-quartiles', 'Percentiles and quartiles'),
  'stat.distributions': lesson('applied-statistics', 3, 'shape-of-a-distribution', 'Shape of a distribution'),
  'stat.prob': lesson('applied-statistics', 4, 'introduction-to-probability', 'Introduction to probability'),
  'stat.conditional': lesson('applied-statistics', 4, 'conditional-probability', 'Conditional probability and independence'),
  'stat.bayes': lesson('applied-statistics', 4, 'bayes-theorem', 'Bayes’ theorem'),
  'stat.counting': lesson('applied-statistics', 4, 'counting-principles', 'Permutations and combinations'),
  'stat.rv': lesson('applied-statistics', 5, 'discrete-random-variables', 'Discrete random variables and expected value'),
  'stat.binomial': lesson('applied-statistics', 5, 'binomial-distribution', 'The binomial distribution'),
  'stat.poisson': lesson('applied-statistics', 5, 'poisson-distribution', 'The Poisson distribution'),
  'stat.normal': lesson('applied-statistics', 5, 'normal-distribution', 'The normal distribution'),
  'stat.clt': lesson('applied-statistics', 5, 'central-limit-theorem', 'The central limit theorem'),
  'stat.testing': lesson('applied-statistics', 6, 'logic-of-hypothesis-testing', 'The logic of hypothesis testing'),
  'stat.ttest': lesson('applied-statistics', 6, 't-tests', 't-tests'),
  'stat.chisq': lesson('applied-statistics', 6, 'chi-squared-tests', 'Chi-squared tests'),
  'stat.proportions': lesson('applied-statistics', 6, 'inference-for-proportions', 'Inference for proportions'),
  'stat.regression': lesson('applied-statistics', 7, 'simple-linear-regression', 'Simple linear regression'),
  'stat.multireg': lesson('applied-statistics', 7, 'multiple-regression', 'Multiple regression'),
  'stat.correlation': lesson('applied-statistics', 7, 'correlation', 'Correlation'),

  // ---------- Discrete math and algorithms ----------
  'dm.proof': lesson('discrete-math', 1, 'propositions-and-proof-techniques', 'Propositions and proof techniques'),
  'dm.sets': lesson('discrete-math', 2, 'sets-and-functions-for-discrete', 'Sets and functions'),
  'dm.induction': lesson('discrete-math', 3, 'induction-and-recursion', 'Induction and recursion'),
  'dm.counting': lesson('discrete-math', 3, 'counting-and-combinatorics', 'Counting and combinatorics'),
  'dm.recurrence': lesson('discrete-math', 3, 'recurrence-relations', 'Recurrence relations'),
  'dm.prob': lesson('discrete-math', 4, 'discrete-probability', 'Discrete probability'),
  'dm.graphs': lesson('discrete-math', 5, 'graph-theory', 'Graph theory and networks'),
  'dm.trees': lesson('discrete-math', 5, 'trees-and-hierarchies', 'Trees and hierarchies'),
  'dm.complexity': lesson('discrete-math', 6, 'algorithms-and-complexity', 'Algorithms and complexity'),
  'dm.automata': lesson('discrete-math', 6, 'automata-theory', 'Automata theory'),
  'dp.intro': lesson('dynamic-programming', 1, 'what-is-dynamic-programming', 'What is dynamic programming?'),
  'dp.grids': lesson('dynamic-programming', 1, '2d-dp-grids', '2D DP: grids and the table mindset'),
  'dp.sequence': lesson('dynamic-programming', 1, 'sequence-dp', 'Sequence DP: LCS and edit distance'),
  'dp.dag': lesson('dynamic-programming', 2, 'dp-on-dags', 'DP on DAGs'),
  'dp.expected': lesson('dynamic-programming', 7, 'expected-value-dp', 'Expected-value DP'),
  'dp.game': lesson('dynamic-programming', 7, 'game-theory-dp', 'Game theory DP: minimax'),
  'dp.statemachine': lesson('dynamic-programming', 8, 'stock-trading-state-machines', 'State-machine DP'),

  // ---------- Math for ML (AI Engineering and Data Science courses) ----------
  'ai.linalg': lesson('ai-engineering', 2, 'linear-algebra-intuition', 'Linear algebra intuition'),
  'ai.calculus': lesson('ai-engineering', 2, 'calculus-for-ml', 'Calculus for machine learning'),
  'ai.autodiff': lesson('ai-engineering', 2, 'chain-rule-and-autodiff', 'The chain rule and automatic differentiation'),
  'ai.probability': lesson('ai-engineering', 2, 'probability-distributions', 'Probability and distributions'),
  'ai.optim': lesson('ai-engineering', 2, 'optimization', 'Optimization: GD, momentum and Adam'),
  'ai.info': lesson('ai-engineering', 2, 'information-theory', 'Information theory'),
  'ai.pca': lesson('ai-engineering', 2, 'dimensionality-reduction', 'Dimensionality reduction and PCA'),
  'ai.tensors': lesson('ai-engineering', 2, 'tensor-operations', 'Tensor operations'),
  'ai.stability': lesson('ai-engineering', 2, 'numerical-stability', 'Numerical stability'),
  'ai.norms': lesson('ai-engineering', 2, 'norms-distances', 'Norms and distances'),
  'ai.stats': lesson('ai-engineering', 2, 'statistics-for-ml', 'Statistics for machine learning'),
  'ai.sampling': lesson('ai-engineering', 2, 'sampling-methods', 'Sampling methods'),
  'ai.convex': lesson('ai-engineering', 2, 'convex-optimization', 'Convex optimization'),
  'ai.fourier': lesson('ai-engineering', 2, 'fourier-transform', 'The Fourier transform'),
  'ai.graphs': lesson('ai-engineering', 2, 'graph-theory', 'Graph theory for machine learning'),
  'ai.stochastic': lesson('ai-engineering', 2, 'stochastic-processes', 'Stochastic processes'),
  'ai.embeddings': lesson('ai-engineering', 4, 'embeddings-and-vector-search', 'Embeddings and vector search'),
  'ai.rag': lesson('ai-engineering', 4, 'retrieval-augmented-generation', 'Retrieval-augmented generation'),
  'ai.lora': lesson('ai-engineering', 4, 'fine-tuning-and-lora', 'Fine-tuning and LoRA'),
  'ai.evals': lesson('ai-engineering', 4, 'llm-evals', 'LLM evals'),
  'ai.jupyter': lesson('ai-engineering', 1, 'jupyter-notebooks', 'Jupyter notebooks'),
  'ds.vectorize': lesson('data-science', 2, 'arrays-and-vectorization', 'Arrays and vectorization'),
  'ds.explog': lesson('data-science', 2, 'exponentials-and-logarithms', 'Exponentials and logarithms'),
  'ds.linreg': lesson('data-science', 4, 'linear-regression-from-scratch', 'Linear regression from scratch'),
  'ds.gd': lesson('data-science', 4, 'gradient-descent', 'Gradient descent and optimization'),
  'ds.evaluation': lesson('data-science', 4, 'model-evaluation-and-overfitting', 'Model evaluation and overfitting'),
  'ds.eda': lesson('data-science', 3, 'exploratory-data-analysis', 'Exploratory data analysis'),
  'ds.cleaning': lesson('data-science', 3, 'data-cleaning', 'Data cleaning'),
  'ds.features': lesson('data-science', 3, 'data-transformation', 'Data transformation and feature engineering'),
  'ml.learning': lesson('machine-learning', 1, 'what-is-learning', 'What learning actually is'),

  // ---------- Tools ----------
  'tool.openmat': tool('/openmat', 'OpenMAT', 'Graph any formula from a lesson in 2D or 3D, do the algebra symbolically, and work with matrices.', 'openmat'),
  'tool.notebook': tool('/notebook-lab', 'Notebook Lab', 'Run Python notebooks in the browser; import and export .ipynb.', 'notebook-lab'),
  'tool.matrix': tool('/lab/matrix-lab', 'Matrix Lab', 'Row operations, elimination, inverses and Gram–Schmidt, coded step by step.', 'matrix-lab'),
  'tool.matrix3d': tool('/lab/matrix-3d-lab', 'Matrix 3D Lab', 'Watch a matrix act on a 3D object; eigenvalues and determinants, visually.', 'matrix-3d-lab'),
  'tool.odds': tool('/lab/odds-lab', 'Probability Casino Lab', 'Expected value and conditional probability by simulation.', 'odds-lab'),
  'tool.dp': tool('/lab/dp-lab', 'Dynamic Programming Lab', 'Fill DP tables step by step — the same backward recursion as value iteration.', 'dp-lab'),
  'tool.calc': tool('/universal-calc', 'Universal Calc', 'Numerical methods and quick calculations.', 'universal-calc'),

  // ---------- References ----------
  'ref.la': reference('/linear-algebra', 'Linear algebra reference', 'Definitions, identities and worked patterns.'),
  'ref.laExplorer': reference('/la-explorer', 'Linear algebra concept explorer', 'How the linear algebra concepts connect.'),
  'ref.all': reference('/reference', 'Math reference', 'The app’s reference sheets.'),
}

export const resolveLinks = keys => (keys ?? []).map(k => ({ key: k, ...MATH_LINKS[k] })).filter(l => l.href)
