export const lessons = [
  {
    id: 'l57-graphs',
    title: '57.1 · Graphs as data',
    sections: ['Relations everywhere', 'Adjacency and features', 'Tasks on graphs', 'Why ordinary networks struggle', 'Put it into practice'],
    skill: 'Represent relational data as a graph and name the prediction tasks it supports.',
    prerequisite: 'Neural networks (Labs 20–23), attention (Lab 26), label propagation (Lab 56), graphical models (Lab 45).',
    paragraphs: [
      'Many datasets are about relationships: people and friendships, molecules and bonds, services and API calls, papers and citations, transactions between accounts. A **graph** has nodes (with feature vectors) and edges (optionally with features and directions).',
      'Store the structure as an adjacency matrix A (Aᵢⱼ = 1 if i and j are connected) — or, for large sparse graphs, as neighbour lists — alongside a node-feature matrix X with one row per node.',
      'Tasks: **node classification** (label unlabelled nodes, e.g. fraud accounts), **link prediction** (which edges are missing or will form, e.g. recommendations), and **graph classification** (label whole graphs, e.g. whether a molecule is toxic).',
      'Ordinary networks need a fixed input size and order. A graph has neither: nodes have different numbers of neighbours, and relabelling the nodes must not change the answer. Models must be **permutation invariant** (for graph-level outputs) or **equivariant** (for node-level outputs).',
      'Procedure: decide what nodes, edges and features are; check whether connected nodes tend to share labels (**homophily**) — the assumption most GNNs lean on; and establish baselines: features alone (MLP) and structure alone (label propagation, Lab 56).',
    ],
    formula: 'G = (V, E),  A ∈ {0,1}^(n×n),  X ∈ ℝ^(n×d)     equivariance: f(PAPᵀ, PX) = P f(A, X)',
    derivation: {
      title: 'Counting what a graph stores',
      steps: [
        { prompt: 'An undirected graph with 90 nodes and 230 edges: how many nonzero entries does its adjacency matrix have?', number: 460, show: '`460` (each edge appears twice)' },
        { prompt: 'Average degree = 2 × edges / nodes? (One decimal.)', number: 2 * 230 / 90, tolerance: 0.05, show: '`≈ 5.1`' },
        { prompt: 'What fraction of the 90 × 90 matrix is nonzero? (Four decimals.)', number: 460 / 8100, tolerance: 1e-4, show: '`≈ 0.0568`', why: 'Real graphs are far sparser: store neighbour lists, not dense matrices.' },
      ],
      result: 'Sparsity is why GNNs are implemented as message passing over edges.',
    },
    experiment: 'In the node-classification view, compare the MLP and the GCN with 2 labels per community. What does the graph provide that the features do not?',
    question: 'You renumber the nodes of a graph and ask a node-classification GNN again. Should each node’s predicted label change?',
    choices: [
      { text: 'Yes — the input matrix changed', why: 'The rows are reordered, but the graph is the same.' },
      { text: 'No — relabelling nodes only relabels the outputs', why: 'Node-level GNNs are permutation equivariant.' },
      { text: 'Only for nodes with many neighbours', why: 'Equivariance holds for every node.' },
    ],
    answer: 1,
    explanation: 'No — node-level GNNs are permutation equivariant: relabelling the nodes only relabels the outputs.',
    reflection: 'Name a dataset in your work that is really a graph. What would the nodes, edges and features be?',
  },
  {
    id: 'l57-mp',
    title: '57.2 · Message passing',
    sections: ['Collect, aggregate, update', 'Aggregators', 'Receptive fields', 'Weight sharing', 'Edge features and directions'],
    skill: 'Describe a message-passing layer and reason about its receptive field.',
    prerequisite: 'Lesson 57.1; convolution and weight sharing (Lab 24).',
    paragraphs: [
      'A **message-passing** layer updates every node in three moves: each neighbour sends a message (usually a transformed copy of its features); the node **aggregates** the incoming messages with a permutation-invariant function; and it **updates** its state from the aggregate and its own previous state.',
      'Aggregators: sum (sensitive to degree — counts neighbours), mean (degree-independent), max (picks the strongest signal), or attention-weighted sums (graph attention networks, like Lab 26 restricted to neighbours).',
      'After L layers, a node’s representation depends on every node within L hops: its **receptive field**. In small-world graphs a few hops already reach much of the network.',
      'The same weights are applied at every node, exactly as a convolution applies the same kernel at every pixel (Lab 24) — so the parameter count does not grow with the graph, and the model works on graphs of any size.',
      'Edge features (bond types, transaction amounts) enter the messages; directed graphs use separate weights for incoming and outgoing edges. Graph-level outputs pool all node states at the end with a permutation-invariant readout (sum or mean).',
    ],
    formula: 'hᵥ′ = UPDATE(hᵥ, AGG{ MSG(h_u, h_v, e_uv) : u ∈ N(v) })',
    derivation: {
      title: 'One mean-aggregation step',
      intro: 'A node with feature 2 has neighbours with features 1, 4 and 7. Update: new = 0.5·own + 0.5·mean(neighbours).',
      steps: [
        { prompt: 'Mean of the neighbour features?', number: 4, show: '`4`' },
        { prompt: 'New feature of the node?', number: 3, show: '`0.5×2 + 0.5×4 = 3`' },
        { prompt: 'With a sum aggregator instead of a mean, what is the aggregate?', number: 12, show: '`12`', why: 'Sum grows with degree — useful for counting, harmful for comparing nodes of very different degree.' },
      ],
      result: 'Choice of aggregator decides what a GNN can distinguish.',
    },
    experiment: 'In the message-passing view, click a well-connected node and a poorly connected one, and compare their receptive fields at 1, 2 and 3 layers.',
    question: 'In a graph where every node has 5 neighbours (and no cycles nearby), about how many nodes are exactly 2 hops away from a node?',
    answer: 20,
    explanation: 'Each of the 5 neighbours has 4 further neighbours: 5 × 4 = 20 nodes at distance 2.',
    reflection: 'Which aggregator — sum, mean or max — suits the relationships in your graph, and why?',
  },
  {
    id: 'l57-gcn',
    title: '57.3 · Graph convolutional networks',
    sections: ['A simple, effective layer', 'Self-loops and normalization', 'Semi-supervised node classification', 'Why it works', 'Baselines matter'],
    skill: 'Implement a GCN layer and train it for semi-supervised node classification.',
    prerequisite: 'Lessons 57.1–57.2; label propagation (Lab 56).',
    paragraphs: [
      'The **graph convolutional network** (GCN) layer is H′ = σ(Â H W): multiply the node features by a shared weight matrix W, average them over each node’s neighbourhood with Â, then apply a nonlinearity.',
      'Â = D^(−1/2)(A + I)D^(−1/2): self-loops (+ I) keep each node’s own features in the average; the symmetric degree normalization prevents high-degree nodes from producing huge values.',
      'Train on the few labelled nodes with cross-entropy, while the forward pass uses the whole graph (the **transductive** setting). In the playground, with 2 labels per community, the GCN labels about 80% of the unlabelled nodes correctly, while an MLP on the same noisy features is close to chance.',
      'Averaging over neighbours denoises features within a community (homophily) and spreads label information along edges — a learned blend of feature classification and label propagation.',
      'Always compare against both baselines: a features-only MLP (does structure help?) and label propagation (do features help?). On graphs where neighbours tend to differ (heterophily — e.g. buyers and sellers), plain GCN averaging can hurt.',
    ],
    formula: 'H^(l+1) = σ(Â H^(l) W^(l)),  Â = D̃^(−1/2) Ã D̃^(−1/2),  Ã = A + I',
    derivation: {
      title: 'A normalized adjacency weight',
      intro: 'Nodes i and j are connected. With self-loops, i has degree 4 and j has degree 9.',
      steps: [
        { prompt: 'Âᵢⱼ = 1/√(dᵢ dⱼ)? (Four decimals.)', number: 1 / 6, tolerance: 1e-4, show: '`1/6 ≈ 0.1667`' },
        { prompt: 'Âᵢᵢ (the self-loop weight of i)?', number: 0.25, show: '`1/4`' },
        { prompt: 'Write Âᵢⱼ for degrees di and dj.', answer: '1/sqrt(di*dj)', show: '`1/√(dᵢ dⱼ)`', vars: { di: [1, 20], dj: [1, 20] } },
      ],
      result: 'High-degree neighbours contribute less each, keeping every node’s aggregate on a comparable scale.',
    },
    experiment: 'In the node-classification view, vary the labels per community from 1 to 10 for both models. Where are the red-ringed mistakes?',
    question: 'A GCN layer maps 8 input features to 16 hidden units. How many weights (excluding biases) does it have — for a graph of any size?',
    answer: 128,
    explanation: 'W is 8 × 16 = 128, shared by all nodes: the parameter count does not depend on the graph.',
    reflection: 'In your graph, do connected nodes tend to share labels? What would a GCN do if they did not?',
  },
  {
    id: 'l57-depth',
    title: '57.4 · Depth and over-smoothing',
    sections: ['More hops, more context', 'Averaging too much', 'Measuring it', 'Remedies', 'Limits of expressiveness'],
    skill: 'Diagnose over-smoothing and know the remedies and limits of message-passing GNNs.',
    prerequisite: 'Lessons 57.1–57.3; residual connections (Lab 52).',
    paragraphs: [
      'Each layer extends the receptive field by one hop, so more layers let distant information in. In the playground, accuracy rises from one layer to about four.',
      'But repeated averaging is a diffusion: apply Â many times and every node’s features converge toward the same (degree-weighted) global average. This **over-smoothing** erases the differences we need. With untrained propagation, a simple probe’s accuracy climbs to about 97% after 4 steps, then falls to about 61% after 32 as the feature spread collapses toward zero.',
      'Remedies: keep networks shallow (2–4 layers is common), add residual or skip connections (Lab 52), mix initial features back in at each layer, use normalization designed for graphs, or let attention weight neighbours unequally.',
      'Message passing also has an expressiveness ceiling: standard GNNs cannot distinguish some non-isomorphic graphs (they are at most as powerful as the Weisfeiler–Lehman graph isomorphism test). Adding node identifiers, positional encodings or higher-order structures lifts it.',
      'And information from far away must squeeze through a few edges (**over-squashing**). Graph transformers, rewiring and virtual “global” nodes address long-range dependencies.',
    ],
    formula: 'Âᵏ X → (degree-weighted average) as k → ∞     remedy: H^(l+1) = H^(l) + σ(Â H^(l) W^(l))',
    derivation: {
      title: 'Averaging on a two-node graph',
      intro: 'Two connected nodes with self-loops, features 0 and 1; each step replaces both by the mean of their two values.',
      steps: [
        { prompt: 'After one step, what are both features?', number: 0.5, show: '`0.5 and 0.5`' },
        { prompt: 'After another step?', number: 0.5, show: '`0.5` — identical forever' },
      ],
      result: 'Averaging destroys differences; how fast depends on how the graph is connected.',
    },
    experiment: 'In the over-smoothing view, read the accuracy and feature spread at 0, 4 and 32 steps. Then in the node-classification view, compare GCNs with 2, 4 and 6 layers.',
    question: 'The feature spread falls from 20 at step 0 to 0.032 at step 32. By what factor did it shrink?',
    answer: 625, tolerance: 1,
    explanation: '20 / 0.032 = 625 — nodes have become nearly indistinguishable.',
    reflection: 'Why might a very deep GNN perform worse than a shallow one even on training data?',
  },
  {
    id: 'l57-practice',
    title: '57.5 · GNNs in practice',
    sections: ['Inductive learning and sampling', 'Link prediction', 'Graph-level tasks', 'Leakage on graphs', 'Demonstrate understanding'],
    skill: 'Apply GNNs to realistic tasks and evaluate them without graph leakage.',
    prerequisite: 'Lessons 57.1–57.4; evaluation (Lab 06).',
    paragraphs: [
      'Large graphs do not fit in one forward pass. **GraphSAGE**-style models sample a fixed number of neighbours per hop and learn aggregators that work on new nodes and new graphs (**inductive** learning) — essential when users or products keep arriving.',
      '**Link prediction** scores pairs: e.g. the dot product of two node embeddings, trained on existing edges versus sampled non-edges. It powers recommendation and knowledge-graph completion.',
      '**Graph classification** pools node states into one vector per graph (sum, mean or attention pooling) — the backbone of molecular property prediction.',
      'Graphs leak easily: test nodes’ edges and features are visible during training in the transductive setting; for link prediction, test edges must be removed from the graph used for message passing; for time-evolving graphs, split by time (Lab 19). Random splits can wildly overstate performance.',
      'You have completed this lab when you can: represent relational data as graphs; explain message passing, aggregators and receptive fields; implement and train a GCN and compare it with feature-only and structure-only baselines; diagnose over-smoothing and name the expressiveness limits; and evaluate GNNs without leakage. The Python challenge implements the normalized adjacency, a GCN forward and backward pass, and over-smoothing.',
    ],
    formula: 'link score: s(u, v) = σ(z_uᵀ z_v)     graph readout: z_G = Σᵥ hᵥ (or mean, or attention)',
    derivation: {
      title: 'Scoring a link',
      steps: [
        { prompt: 'Node embeddings z_u = (1, 2) and z_v = (0.5, −0.25). Dot product?', number: 0, show: '`0.5 − 0.5 = 0`' },
        { prompt: 'Link probability σ(0)?', number: 0.5, show: '`0.5` — the model is undecided' },
      ],
      result: 'Embeddings that point in similar directions predict links; orthogonal ones are uncertain.',
    },
    experiment: 'Using the node-classification view, find a labelling seed where the GCN makes many mistakes. What do the mistaken nodes have in common?',
    question: 'For a link-prediction test, you forgot to remove the test edges from the message-passing graph. Will the test score be too optimistic?',
    choices: [
      { text: 'Yes', why: 'The model sees the very edges it is asked to predict — a textbook leak.' },
      { text: 'No — message passing does not use labels', why: 'The edges themselves are the labels in link prediction.' },
      { text: 'Only if the graph is small', why: 'The leak exists at any size.' },
    ],
    answer: 0,
    explanation: 'Yes: the model sees the very edges it is asked to predict — a textbook leak.',
    reflection: 'How would you split your own graph data into training and test sets without leakage?',
  },
]

export const sources = [
  { title: 'Kipf & Welling (2017) · Semi-supervised classification with graph convolutional networks', url: 'https://arxiv.org/abs/1609.02907' },
  { title: 'Hamilton, Ying & Leskovec (2017) · Inductive representation learning on large graphs (GraphSAGE)', url: 'https://arxiv.org/abs/1706.02216' },
  { title: 'Xu et al. (2019) · How powerful are graph neural networks?', url: 'https://arxiv.org/abs/1810.00826' },
  { title: 'Hamilton · Graph Representation Learning (free book)', url: 'https://www.cs.mcgill.ca/~wlh/grl_book/' },
]
