// Famous algorithms for the CodeLens library (library.ts), in Python and JavaScript, small
// enough to step through and to show whole in the Picture tab (Picture.tsx): sorting and
// shuffling, two pointers, dynamic programming, graphs, backtracking, game logic and machine
// learning. Every example is the same program in both languages, and library.test.ts checks
// each prints its output.
//
// Generated from one source (each program written once per language, then run in Python and
// in the CodeLens JavaScript interpreter to check both print the same thing), so edit an
// example here directly and keep both variants in step.
import type { LibraryExample } from './library'

const lines = (...text: string[]) => text.join('\n')

export const ALGORITHM_EXAMPLES: LibraryExample[] = [
  {
    id: "algo-fisher-yates",
    title: "Fisher-Yates shuffle",
    group: "Sorting and Shuffling",
    difficulty: "Beginner",
    concept: "Fisher-Yates shuffles a list in place so that every ordering is equally likely. It walks from the last position down to the second, and swaps each position with a random position at or before it (including itself). Each step fixes one position for good: after the step for i, position i holds its final card, chosen fairly from the cards not yet placed. The program uses a tiny random-number generator of its own, so every run shuffles the same way and you can compare runs.",
    prerequisites: ["Lists", "for loops counting down", "Swapping two items"],
    watch: [
      "In the Picture tab, the arc between i and j: the swap. Positions to the right of i never change again.",
      "j is chosen from 0 to i inclusive: sometimes j equals i and nothing moves. That is part of being fair, not a bug.",
      "Python swaps in one line, a[i], a[j] = a[j], a[i]; JavaScript does the same with [a[i], a[j]] = [a[j], a[i]].",
    ],
    complexity: "O(n) time, O(1) extra space: one swap per position.",
    invariants: [
      "After the step for i, positions i to the end hold their final cards, and positions 0 to i - 1 hold the cards not yet placed.",
    ],
    edgeCases: [
      "A list of one item (the loop never runs).",
      "j equal to i (the card stays where it is).",
    ],
    exercises: [
      "Change next_random(i + 1) to next_random(len(cards)), the most common shuffle bug. Run it many times and count which card ends up first: the orderings are no longer equally likely (with 3 cards there are 3 x 3 x 3 = 27 equally likely paths but 6 orderings, and 27 isn't divisible by 6).",
      "Shuffle by walking forwards instead: for i from 0 to n - 2, swap with a random position from i to n - 1.",
      "Pick k random cards without replacement by stopping the shuffle after k steps.",
    ],
    variants: {
      py: {
        code: lines(
          "seed = 7",
          "",
          "def next_random(limit):",
          "    # A tiny random-number generator, so every run shuffles the same way.",
          "    global seed",
          "    seed = (seed * 75 + 74) % 65537",
          "    return seed % limit",
          "",
          "cards = [\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"]",
          "for i in range(len(cards) - 1, 0, -1):",
          "    j = next_random(i + 1)   # any position from 0 to i, including i itself",
          "    cards[i], cards[j] = cards[j], cards[i]",
          "print(\" \".join(cards))",
        ),
        output: ["C B D A E F"],
      },
      js: {
        code: lines(
          "let seed = 7;",
          "",
          "function nextRandom(limit) {",
          "  // A tiny random-number generator, so every run shuffles the same way.",
          "  seed = (seed * 75 + 74) % 65537;",
          "  return seed % limit;",
          "}",
          "",
          "const cards = [\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"];",
          "for (let i = cards.length - 1; i > 0; i--) {",
          "  const j = nextRandom(i + 1); // any position from 0 to i, including i itself",
          "  [cards[i], cards[j]] = [cards[j], cards[i]];",
          "}",
          "console.log(cards.join(\" \"));",
        ),
        output: ["C B D A E F"],
      },
    },
  },
  {
    id: "algo-insertion-sort",
    title: "Insertion sort",
    group: "Sorting and Shuffling",
    difficulty: "Beginner",
    concept: "Insertion sort grows a sorted section at the front of the list, one item at a time. It takes the next item (key), then shifts every larger item in the sorted section one place to the right, opening a gap, and drops key into the gap. It is how most people sort a hand of cards, and it is fast on lists that are already nearly sorted.",
    prerequisites: ["Lists", "while loops"],
    watch: [
      "The dashed arrows in the Picture tab: a[j + 1] = a[j] copies a value one place right. It is a shift, not a swap, so the value briefly appears twice.",
      "key holds the item being placed while the gap moves left; it goes back in on the last line of the loop.",
      "j stops at the first item that is not larger than key, or at -1.",
    ],
    complexity: "O(n²) comparisons in the worst case (a reversed list), O(n) on an already sorted list; O(1) extra space.",
    invariants: [
      "Before the step for i, positions 0 to i - 1 are sorted.",
    ],
    edgeCases: [
      "An already sorted list: the while loop never runs.",
      "Equal values: > (not >=) keeps them in their original order, so the sort is stable.",
    ],
    exercises: [
      "Count the shifts for a sorted, a reversed and a random list of the same length.",
      "Sort in descending order by changing one character.",
      "Use binary search to find where key goes. Does it make the sort faster? (Count the shifts.)",
    ],
    variants: {
      py: {
        code: lines(
          "def insertion_sort(a):",
          "    for i in range(1, len(a)):",
          "        key = a[i]",
          "        j = i - 1",
          "        while j >= 0 and a[j] > key:",
          "            a[j + 1] = a[j]   # shift the larger item one place right",
          "            j -= 1",
          "        a[j + 1] = key        # drop key into the gap",
          "",
          "nums = [5, 2, 9, 1, 6]",
          "insertion_sort(nums)",
          "print(\" \".join(str(n) for n in nums))",
        ),
        output: ["1 2 5 6 9"],
      },
      js: {
        code: lines(
          "function insertionSort(a) {",
          "  for (let i = 1; i < a.length; i++) {",
          "    const key = a[i];",
          "    let j = i - 1;",
          "    while (j >= 0 && a[j] > key) {",
          "      a[j + 1] = a[j]; // shift the larger item one place right",
          "      j--;",
          "    }",
          "    a[j + 1] = key; // drop key into the gap",
          "  }",
          "}",
          "",
          "const nums = [5, 2, 9, 1, 6];",
          "insertionSort(nums);",
          "console.log(nums.join(\" \"));",
        ),
        output: ["1 2 5 6 9"],
      },
    },
  },
  {
    id: "algo-selection-sort",
    title: "Selection sort",
    group: "Sorting and Shuffling",
    difficulty: "Beginner",
    concept: "Selection sort finds the smallest item in the unsorted part of the list and swaps it into the next position of the sorted part. Each pass makes exactly one swap, so it does the fewest writes of the simple sorts, but it always does every comparison, even on a sorted list.",
    prerequisites: ["Lists", "Nested loops"],
    watch: [
      "smallest moving right as a smaller value turns up, while j scans.",
      "One swap per pass: the arc between i and smallest.",
      "The sorted section on the left growing by one each pass.",
    ],
    complexity: "O(n²) comparisons always; at most n - 1 swaps; O(1) extra space.",
    invariants: [
      "Before pass i, positions 0 to i - 1 hold the i smallest values, in order.",
    ],
    edgeCases: [
      "The smallest is already in place: smallest == i, and the swap changes nothing.",
    ],
    exercises: [
      "Count comparisons and swaps, and compare with insertion sort on the same lists.",
      "Find the largest instead, and fill the list from the end.",
    ],
    variants: {
      py: {
        code: lines(
          "def selection_sort(a):",
          "    for i in range(len(a) - 1):",
          "        smallest = i",
          "        for j in range(i + 1, len(a)):",
          "            if a[j] < a[smallest]:",
          "                smallest = j",
          "        a[i], a[smallest] = a[smallest], a[i]",
          "",
          "nums = [29, 10, 14, 37, 13]",
          "selection_sort(nums)",
          "print(\" \".join(str(n) for n in nums))",
        ),
        output: ["10 13 14 29 37"],
      },
      js: {
        code: lines(
          "function selectionSort(a) {",
          "  for (let i = 0; i < a.length - 1; i++) {",
          "    let smallest = i;",
          "    for (let j = i + 1; j < a.length; j++) {",
          "      if (a[j] < a[smallest]) smallest = j;",
          "    }",
          "    [a[i], a[smallest]] = [a[smallest], a[i]];",
          "  }",
          "}",
          "",
          "const nums = [29, 10, 14, 37, 13];",
          "selectionSort(nums);",
          "console.log(nums.join(\" \"));",
        ),
        output: ["10 13 14 29 37"],
      },
    },
  },
  {
    id: "algo-merge-sort",
    title: "Merge sort",
    group: "Sorting and Shuffling",
    difficulty: "Intermediate",
    concept: "Merge sort splits the list in half, sorts each half by calling itself, and then merges the two sorted halves by repeatedly taking the smaller of their two front items. Splitting stops at lists of one item, which are already sorted. Because each level of splitting does n units of merging work and there are about log₂ n levels, it takes O(n log n) time on every input.",
    prerequisites: ["Recursion", "Lists and slicing"],
    watch: [
      "The call stack (Calls tab) going down to one-item lists, then coming back up.",
      "In the Picture tab, i in left and j in right: the two front items being compared; merged growing by one each step.",
      "The leftovers copied at the end once one half runs out.",
    ],
    complexity: "O(n log n) time in every case; O(n) extra space for the merged lists.",
    invariants: [
      "merged is always sorted and holds exactly left[:i] and right[:j].",
    ],
    edgeCases: [
      "Lists of length 0 and 1 are returned unchanged.",
      "Equal values: <= takes from the left first, keeping the sort stable.",
    ],
    exercises: [
      "Count how many times merge_sort is called for 8 items. Why is it 15?",
      "Merge two already-sorted lists without sorting anything else.",
      "Change <= to <. Is the sort still stable? Try it on pairs like (2, \"a\") and (2, \"b\").",
    ],
    variants: {
      py: {
        code: lines(
          "def merge_sort(a):",
          "    if len(a) <= 1:",
          "        return a",
          "    mid = len(a) // 2",
          "    left = merge_sort(a[:mid])",
          "    right = merge_sort(a[mid:])",
          "    merged = []",
          "    i = j = 0",
          "    while i < len(left) and j < len(right):",
          "        if left[i] <= right[j]:",
          "            merged.append(left[i])",
          "            i += 1",
          "        else:",
          "            merged.append(right[j])",
          "            j += 1",
          "    merged.extend(left[i:])",
          "    merged.extend(right[j:])",
          "    return merged",
          "",
          "print(\" \".join(str(n) for n in merge_sort([38, 27, 43, 3, 9, 82])))",
        ),
        output: ["3 9 27 38 43 82"],
      },
      js: {
        code: lines(
          "function mergeSort(a) {",
          "  if (a.length <= 1) return a;",
          "  const mid = Math.floor(a.length / 2);",
          "  const left = mergeSort(a.slice(0, mid));",
          "  const right = mergeSort(a.slice(mid));",
          "  const merged = [];",
          "  let i = 0;",
          "  let j = 0;",
          "  while (i < left.length && j < right.length) {",
          "    if (left[i] <= right[j]) {",
          "      merged.push(left[i]);",
          "      i++;",
          "    } else {",
          "      merged.push(right[j]);",
          "      j++;",
          "    }",
          "  }",
          "  while (i < left.length) merged.push(left[i++]);",
          "  while (j < right.length) merged.push(right[j++]);",
          "  return merged;",
          "}",
          "",
          "console.log(mergeSort([38, 27, 43, 3, 9, 82]).join(\" \"));",
        ),
        output: ["3 9 27 38 43 82"],
      },
    },
  },
  {
    id: "algo-quicksort",
    title: "Quicksort (Lomuto partition)",
    group: "Sorting and Shuffling",
    difficulty: "Intermediate",
    concept: "Quicksort picks a pivot (here the last item) and partitions the list so that everything smaller than the pivot comes before it and everything else after it. The pivot is then in its final place, and the two sides are sorted the same way, by recursion. The partition uses two pointers: j scans every item, and i marks where the next small item goes.",
    prerequisites: ["Recursion", "Swapping items", "Two pointers"],
    watch: [
      "In the Picture tab, i and j: everything left of i is smaller than the pivot; between i and j is not.",
      "The final swap that drops the pivot at i, its sorted position.",
      "lo and hi narrowing in the recursive calls (Calls tab).",
    ],
    complexity: "O(n log n) on average; O(n²) when the pivot is always the smallest or largest (an already sorted list with this pivot choice); O(log n) stack space on average.",
    invariants: [
      "During partition: a[lo..i-1] < pivot and a[i..j-1] >= pivot.",
    ],
    edgeCases: [
      "A sorted list: every partition is lopsided, the slow case.",
      "Duplicates of the pivot go to the right side.",
    ],
    exercises: [
      "Run it on [1, 2, 3, 4, 5, 6, 7] and count the calls. Then pick the middle item as the pivot (swap it to the end first) and count again.",
      "Count the swaps that change nothing (i == j) and skip them.",
    ],
    variants: {
      py: {
        code: lines(
          "def partition(a, lo, hi):",
          "    pivot = a[hi]",
          "    i = lo",
          "    for j in range(lo, hi):",
          "        if a[j] < pivot:",
          "            a[i], a[j] = a[j], a[i]",
          "            i += 1",
          "    a[i], a[hi] = a[hi], a[i]   # the pivot lands in its final place",
          "    return i",
          "",
          "def quicksort(a, lo, hi):",
          "    if lo < hi:",
          "        p = partition(a, lo, hi)",
          "        quicksort(a, lo, p - 1)",
          "        quicksort(a, p + 1, hi)",
          "",
          "nums = [7, 2, 9, 4, 1, 8, 3]",
          "quicksort(nums, 0, len(nums) - 1)",
          "print(\" \".join(str(n) for n in nums))",
        ),
        output: ["1 2 3 4 7 8 9"],
      },
      js: {
        code: lines(
          "function partition(a, lo, hi) {",
          "  const pivot = a[hi];",
          "  let i = lo;",
          "  for (let j = lo; j < hi; j++) {",
          "    if (a[j] < pivot) {",
          "      [a[i], a[j]] = [a[j], a[i]];",
          "      i++;",
          "    }",
          "  }",
          "  [a[i], a[hi]] = [a[hi], a[i]]; // the pivot lands in its final place",
          "  return i;",
          "}",
          "",
          "function quicksort(a, lo, hi) {",
          "  if (lo < hi) {",
          "    const p = partition(a, lo, hi);",
          "    quicksort(a, lo, p - 1);",
          "    quicksort(a, p + 1, hi);",
          "  }",
          "}",
          "",
          "const nums = [7, 2, 9, 4, 1, 8, 3];",
          "quicksort(nums, 0, nums.length - 1);",
          "console.log(nums.join(\" \"));",
        ),
        output: ["1 2 3 4 7 8 9"],
      },
    },
  },
  {
    id: "algo-dutch-flag",
    title: "Sort colours (Dutch national flag)",
    group: "Sorting and Shuffling",
    difficulty: "Intermediate",
    concept: "Sort a list of 0s, 1s and 2s in one pass with three pointers (LeetCode 75). Everything left of lo is 0, everything from lo to mid - 1 is 1, everything right of hi is 2, and mid scans the unknown middle. A 0 is swapped down to lo, a 1 is left where it is, a 2 is swapped up to hi. It shows how pointer invariants turn a sort into a single pass.",
    prerequisites: ["Lists", "while loops", "Swapping items"],
    watch: [
      "The three pointers lo, mid and hi in the Picture tab, and the four regions they mark.",
      "After swapping with hi, mid does not move: the value that came from hi has not been looked at yet.",
    ],
    complexity: "O(n) time, one pass; O(1) extra space.",
    invariants: [
      "a[0..lo-1] are 0, a[lo..mid-1] are 1, a[hi+1..] are 2; a[mid..hi] is unknown.",
    ],
    edgeCases: [
      "All one colour.",
      "Already sorted.",
    ],
    exercises: [
      "Explain why mid += 1 happens after a swap with lo but not after a swap with hi.",
      "Change it to sort four colours. (It gets harder: why?)",
    ],
    variants: {
      py: {
        code: lines(
          "colors = [2, 0, 2, 1, 1, 0]",
          "lo, mid, hi = 0, 0, len(colors) - 1",
          "while mid <= hi:",
          "    if colors[mid] == 0:",
          "        colors[lo], colors[mid] = colors[mid], colors[lo]",
          "        lo += 1",
          "        mid += 1",
          "    elif colors[mid] == 1:",
          "        mid += 1",
          "    else:",
          "        colors[mid], colors[hi] = colors[hi], colors[mid]",
          "        hi -= 1",
          "print(\" \".join(str(c) for c in colors))",
        ),
        output: ["0 0 1 1 2 2"],
      },
      js: {
        code: lines(
          "const colors = [2, 0, 2, 1, 1, 0];",
          "let lo = 0;",
          "let mid = 0;",
          "let hi = colors.length - 1;",
          "while (mid <= hi) {",
          "  if (colors[mid] === 0) {",
          "    [colors[lo], colors[mid]] = [colors[mid], colors[lo]];",
          "    lo++;",
          "    mid++;",
          "  } else if (colors[mid] === 1) {",
          "    mid++;",
          "  } else {",
          "    [colors[mid], colors[hi]] = [colors[hi], colors[mid]];",
          "    hi--;",
          "  }",
          "}",
          "console.log(colors.join(\" \"));",
        ),
        output: ["0 0 1 1 2 2"],
      },
    },
  },
  {
    id: "algo-two-sum-sorted",
    title: "Two sum on a sorted list (two pointers)",
    group: "Searching and Two Pointers",
    difficulty: "Beginner",
    concept: "Find two numbers in a sorted list that add up to a target, with one pointer at each end. If the sum is too small, the only way to make it bigger is to move lo right; if it is too big, move hi left. Each step rules out one number for good, so it takes one pass instead of checking every pair.",
    prerequisites: ["Lists", "while loops"],
    watch: [
      "lo and hi walking towards each other in the Picture tab.",
      "Which pointer moves, and why: compare total with target.",
    ],
    complexity: "O(n) time, O(1) space, against O(n²) for checking every pair.",
    invariants: [
      "If an answer exists, it lies between lo and hi.",
    ],
    edgeCases: [
      "No pair adds up: the loop ends when lo meets hi.",
      "The list must be sorted, or the reasoning fails.",
    ],
    exercises: [
      "Make it print -1 -1 when there is no pair.",
      "Find all pairs, not just one.",
      "Why does moving lo right never skip the answer? Write the argument down.",
    ],
    variants: {
      py: {
        code: lines(
          "nums = [1, 3, 4, 6, 8, 11]",
          "target = 10",
          "lo, hi = 0, len(nums) - 1",
          "while lo < hi:",
          "    total = nums[lo] + nums[hi]",
          "    if total == target:",
          "        break",
          "    if total < target:",
          "        lo += 1",
          "    else:",
          "        hi -= 1",
          "print(lo, hi, nums[lo], nums[hi])",
        ),
        output: ["2 3 4 6"],
      },
      js: {
        code: lines(
          "const nums = [1, 3, 4, 6, 8, 11];",
          "const target = 10;",
          "let lo = 0;",
          "let hi = nums.length - 1;",
          "while (lo < hi) {",
          "  const total = nums[lo] + nums[hi];",
          "  if (total === target) break;",
          "  if (total < target) lo++;",
          "  else hi--;",
          "}",
          "console.log(lo, hi, nums[lo], nums[hi]);",
        ),
        output: ["2 3 4 6"],
      },
    },
  },
  {
    id: "algo-sliding-window",
    title: "Sliding window: best sum of k in a row",
    group: "Searching and Two Pointers",
    difficulty: "Beginner",
    concept: "Find the largest sum of k consecutive numbers. Instead of adding up every window from scratch (k additions each), slide the window one place: add the number that enters on the right and subtract the one that leaves on the left. Every window then costs two operations, whatever k is.",
    prerequisites: ["Lists", "for loops"],
    watch: [
      "left and right one window-width apart in the Picture tab.",
      "window changing by exactly nums[right] - nums[left] each step.",
    ],
    complexity: "O(n) time instead of O(n·k); O(1) space.",
    invariants: [
      "window is the sum of nums[left + 1 .. right] after each step.",
    ],
    edgeCases: [
      "k equal to the length: one window.",
      "Negative numbers: still correct.",
    ],
    exercises: [
      "Return where the best window starts, too.",
      "Find the shortest window whose sum is at least a target (the window grows and shrinks).",
    ],
    variants: {
      py: {
        code: lines(
          "nums = [2, 1, 5, 1, 3, 2]",
          "k = 3",
          "window = 0",
          "for i in range(k):",
          "    window += nums[i]",
          "best = window",
          "for right in range(k, len(nums)):",
          "    left = right - k",
          "    window += nums[right] - nums[left]   # one number enters, one leaves",
          "    best = max(best, window)",
          "print(best)",
        ),
        output: ["9"],
      },
      js: {
        code: lines(
          "const nums = [2, 1, 5, 1, 3, 2];",
          "const k = 3;",
          "let window = 0;",
          "for (let i = 0; i < k; i++) window += nums[i];",
          "let best = window;",
          "for (let right = k; right < nums.length; right++) {",
          "  const left = right - k;",
          "  window += nums[right] - nums[left]; // one number enters, one leaves",
          "  best = Math.max(best, window);",
          "}",
          "console.log(best);",
        ),
        output: ["9"],
      },
    },
  },
  {
    id: "algo-binary-heap",
    title: "Binary heap: push and pop",
    group: "Data Structures",
    difficulty: "Intermediate",
    concept: "A min-heap keeps the smallest item at the front of a list, so it can be taken in O(log n). The list is a tree in disguise: the children of position i are at 2i + 1 and 2i + 2, and its parent is at (i - 1) // 2. Pushing appends and swaps the new item up past larger parents; popping moves the last item to the front and swaps it down past smaller children. Priority queues, Dijkstra and heapsort are built on this.",
    prerequisites: ["Lists", "Integer division", "while loops"],
    watch: [
      "The swaps in the Picture tab: up towards the front when pushing, down towards the back when popping.",
      "parent, i, left, right and smallest as positions in the one list.",
      "The numbers come out of pop in sorted order.",
    ],
    complexity: "push and pop are O(log n): each swap moves one level, and a heap of n items has about log₂ n levels.",
    invariants: [
      "Every item is <= its children: heap[i] <= heap[2i + 1] and heap[i] <= heap[2i + 2].",
    ],
    edgeCases: [
      "Popping the last item.",
      "Pushing an item smaller than everything (it swaps all the way to the front).",
    ],
    exercises: [
      "Draw the list as a tree on paper after each push.",
      "Turn it into a max-heap by flipping two comparisons.",
      "Write heapsort: push everything, then pop everything.",
    ],
    variants: {
      py: {
        code: lines(
          "heap = []",
          "",
          "def push(value):",
          "    heap.append(value)",
          "    i = len(heap) - 1",
          "    while i > 0:",
          "        parent = (i - 1) // 2",
          "        if heap[parent] <= heap[i]:",
          "            break",
          "        heap[parent], heap[i] = heap[i], heap[parent]",
          "        i = parent",
          "",
          "def pop():",
          "    top = heap[0]",
          "    last = heap.pop()",
          "    if heap:",
          "        heap[0] = last",
          "        i = 0",
          "        while True:",
          "            left, right = 2 * i + 1, 2 * i + 2",
          "            smallest = i",
          "            if left < len(heap) and heap[left] < heap[smallest]:",
          "                smallest = left",
          "            if right < len(heap) and heap[right] < heap[smallest]:",
          "                smallest = right",
          "            if smallest == i:",
          "                break",
          "            heap[i], heap[smallest] = heap[smallest], heap[i]",
          "            i = smallest",
          "    return top",
          "",
          "for v in [5, 3, 8, 1, 4]:",
          "    push(v)",
          "out = []",
          "while heap:",
          "    out.append(pop())",
          "print(\" \".join(str(v) for v in out))",
        ),
        output: ["1 3 4 5 8"],
      },
      js: {
        code: lines(
          "const heap = [];",
          "",
          "function push(value) {",
          "  heap.push(value);",
          "  let i = heap.length - 1;",
          "  while (i > 0) {",
          "    const parent = Math.floor((i - 1) / 2);",
          "    if (heap[parent] <= heap[i]) break;",
          "    [heap[parent], heap[i]] = [heap[i], heap[parent]];",
          "    i = parent;",
          "  }",
          "}",
          "",
          "function pop() {",
          "  const top = heap[0];",
          "  const last = heap.pop();",
          "  if (heap.length > 0) {",
          "    heap[0] = last;",
          "    let i = 0;",
          "    while (true) {",
          "      const left = 2 * i + 1;",
          "      const right = 2 * i + 2;",
          "      let smallest = i;",
          "      if (left < heap.length && heap[left] < heap[smallest]) smallest = left;",
          "      if (right < heap.length && heap[right] < heap[smallest]) smallest = right;",
          "      if (smallest === i) break;",
          "      [heap[i], heap[smallest]] = [heap[smallest], heap[i]];",
          "      i = smallest;",
          "    }",
          "  }",
          "  return top;",
          "}",
          "",
          "for (const v of [5, 3, 8, 1, 4]) push(v);",
          "const out = [];",
          "while (heap.length > 0) out.push(pop());",
          "console.log(out.join(\" \"));",
        ),
        output: ["1 3 4 5 8"],
      },
    },
  },
  {
    id: "algo-climbing-stairs",
    title: "Climbing stairs (1-D dynamic programming)",
    group: "Dynamic Programming",
    difficulty: "Beginner",
    concept: "How many ways can you climb n stairs taking 1 or 2 steps at a time? The last step was either a 1 (from stair n - 1) or a 2 (from stair n - 2), so ways[n] = ways[n - 1] + ways[n - 2]. Filling a table from the bottom up means each answer is computed once, from two answers already in the table: that is dynamic programming in its simplest form.",
    prerequisites: ["Lists", "for loops"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "Each new entry reads exactly the two before it.",
    ],
    complexity: "O(n) time and space; only the last two entries are ever read, so O(1) space is possible (an exercise).",
    invariants: [
      "ways[k] is the number of ways to reach stair k, for every k filled in so far.",
    ],
    edgeCases: [
      "n = 0 and n = 1: one way each (do nothing, or one step).",
    ],
    exercises: [
      "Allow steps of 1, 2 or 3.",
      "Keep only two variables instead of the whole list.",
      "Write the plain recursive version and count its calls for n = 20. Why so many?",
    ],
    variants: {
      py: {
        code: lines(
          "n = 6",
          "ways = [0] * (n + 1)",
          "ways[0] = 1",
          "ways[1] = 1",
          "for i in range(2, n + 1):",
          "    ways[i] = ways[i - 1] + ways[i - 2]",
          "print(ways[n])",
        ),
        output: ["13"],
      },
      js: {
        code: lines(
          "const n = 6;",
          "const ways = new Array(n + 1).fill(0);",
          "ways[0] = 1;",
          "ways[1] = 1;",
          "for (let i = 2; i <= n; i++) {",
          "  ways[i] = ways[i - 1] + ways[i - 2];",
          "}",
          "console.log(ways[n]);",
        ),
        output: ["13"],
      },
    },
  },
  {
    id: "algo-kadane",
    title: "Maximum subarray (Kadane)",
    group: "Dynamic Programming",
    difficulty: "Intermediate",
    concept: "Find the largest sum of consecutive numbers (LeetCode 53). best_ending_here[i] is the best sum of a run that ends exactly at i: either nums[i] alone, or nums[i] added to the best run ending at i - 1, whichever is bigger. The answer is the largest of these. Keeping the whole list makes the dynamic-programming idea visible; the usual version keeps only the last value.",
    prerequisites: ["Lists", "max"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "The moments a run is abandoned: when nums[i] alone beats extending, best_ending_here starts again.",
    ],
    complexity: "O(n) time; O(n) space here, O(1) with a single variable.",
    invariants: [
      "best_ending_here[i] is the largest sum of a run ending exactly at i.",
    ],
    edgeCases: [
      "All negative numbers: the answer is the largest single number.",
    ],
    exercises: [
      "Also report where the best run starts and ends.",
      "Rewrite it with one variable instead of the list.",
    ],
    variants: {
      py: {
        code: lines(
          "nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]",
          "best_ending_here = [0] * len(nums)",
          "best_ending_here[0] = nums[0]",
          "for i in range(1, len(nums)):",
          "    best_ending_here[i] = max(nums[i], best_ending_here[i - 1] + nums[i])",
          "print(max(best_ending_here))",
        ),
        output: ["6"],
      },
      js: {
        code: lines(
          "const nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4];",
          "const bestEndingHere = new Array(nums.length).fill(0);",
          "bestEndingHere[0] = nums[0];",
          "for (let i = 1; i < nums.length; i++) {",
          "  bestEndingHere[i] = Math.max(nums[i], bestEndingHere[i - 1] + nums[i]);",
          "}",
          "console.log(Math.max(...bestEndingHere));",
        ),
        output: ["6"],
      },
    },
  },
  {
    id: "algo-coin-change",
    title: "Coin change: fewest coins",
    group: "Dynamic Programming",
    difficulty: "Intermediate",
    concept: "What is the fewest coins that make an amount (LeetCode 322)? dp[a] is the answer for amount a. To make a, the last coin was some coin c, and before it you made a - c as cheaply as possible, so dp[a] = min over coins of dp[a - c] + 1. Greedy (always take the biggest coin) fails here: for 6 with coins 1, 3 and 4 it takes 4 + 1 + 1, but 3 + 3 is better, and the table finds it.",
    prerequisites: ["Lists", "Nested loops", "min"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "dp[a - c] for each coin c: the blue cells jump back by the coin values.",
      "INF marks amounts that can't be made (yet).",
    ],
    complexity: "O(amount × number of coins) time, O(amount) space.",
    invariants: [
      "dp[x] is the fewest coins for x, for every x < a.",
    ],
    edgeCases: [
      "An amount that can't be made at all (try coins [5] and amount 3): dp stays INF.",
    ],
    exercises: [
      "Print which coins make up the answer (store the last coin used for each amount).",
      "Count the number of different ways to make the amount instead.",
    ],
    variants: {
      py: {
        code: lines(
          "coins = [1, 3, 4]",
          "amount = 6",
          "INF = amount + 1          # more coins than could ever be needed",
          "dp = [INF] * (amount + 1)",
          "dp[0] = 0",
          "for a in range(1, amount + 1):",
          "    for c in coins:",
          "        if c <= a:",
          "            dp[a] = min(dp[a], dp[a - c] + 1)",
          "print(dp[amount])",
        ),
        output: ["2"],
      },
      js: {
        code: lines(
          "const coins = [1, 3, 4];",
          "const amount = 6;",
          "const INF = amount + 1; // more coins than could ever be needed",
          "const dp = new Array(amount + 1).fill(INF);",
          "dp[0] = 0;",
          "for (let a = 1; a <= amount; a++) {",
          "  for (const c of coins) {",
          "    if (c <= a) dp[a] = Math.min(dp[a], dp[a - c] + 1);",
          "  }",
          "}",
          "console.log(dp[amount]);",
        ),
        output: ["2"],
      },
    },
  },
  {
    id: "algo-lcs",
    title: "Longest common subsequence",
    group: "Dynamic Programming",
    difficulty: "Intermediate",
    concept: "The longest common subsequence of two sequences is the longest sequence of items appearing in both, in order but not necessarily side by side. dp[i][j] is the answer for the first i items of a and the first j of b. If a[i - 1] and b[j - 1] match, extend the answer without them: dp[i - 1][j - 1] + 1. Otherwise drop one item from either sequence and keep the better: max(dp[i - 1][j], dp[i][j - 1]). diff tools and DNA comparison work this way.",
    prerequisites: ["Nested lists (a grid)", "Nested loops"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "A match reads the diagonal neighbour; a mismatch reads the cells above and to the left.",
      "dp has one more row and column than the sequences: row 0 and column 0 mean \"nothing taken yet\". So the letters compared are a[i - 1] and b[j - 1], outlined in blue in their own lists.",
    ],
    complexity: "O(len(a) × len(b)) time and space.",
    invariants: [
      "dp[i][j] is the LCS length of a[:i] and b[:j].",
    ],
    edgeCases: [
      "One sequence empty: the answer is 0.",
      "Identical sequences: the answer is their length.",
    ],
    exercises: [
      "Recover the subsequence itself by walking back from dp[len(a)][len(b)].",
      "Use it to count how many lines differ between two versions of a file.",
    ],
    variants: {
      py: {
        code: lines(
          "a = [\"A\", \"B\", \"C\", \"B\", \"D\"]",
          "b = [\"B\", \"D\", \"C\", \"A\", \"B\"]",
          "dp = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]",
          "for i in range(1, len(a) + 1):",
          "    for j in range(1, len(b) + 1):",
          "        if a[i - 1] == b[j - 1]:",
          "            dp[i][j] = dp[i - 1][j - 1] + 1",
          "        else:",
          "            dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])",
          "print(dp[len(a)][len(b)])",
        ),
        output: ["3"],
      },
      js: {
        code: lines(
          "const a = [\"A\", \"B\", \"C\", \"B\", \"D\"];",
          "const b = [\"B\", \"D\", \"C\", \"A\", \"B\"];",
          "const dp = [];",
          "for (let i = 0; i <= a.length; i++) dp.push(new Array(b.length + 1).fill(0));",
          "for (let i = 1; i <= a.length; i++) {",
          "  for (let j = 1; j <= b.length; j++) {",
          "    if (a[i - 1] === b[j - 1]) {",
          "      dp[i][j] = dp[i - 1][j - 1] + 1;",
          "    } else {",
          "      dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);",
          "    }",
          "  }",
          "}",
          "console.log(dp[a.length][b.length]);",
        ),
        output: ["3"],
      },
    },
  },
  {
    id: "algo-edit-distance",
    title: "Edit distance (Levenshtein)",
    group: "Dynamic Programming",
    difficulty: "Advanced",
    concept: "The fewest single-letter insertions, deletions and replacements that turn one word into another (LeetCode 72). dp[i][j] is the answer for the first i letters of a and the first j of b. If the last letters match, nothing new is needed: dp[i - 1][j - 1]. Otherwise take the cheapest of replacing (diagonal), deleting from a (above) or inserting into a (left), plus one. Spell checkers rank suggestions this way.",
    prerequisites: ["Nested lists (a grid)", "Nested loops", "min"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "Row 0 and column 0 are filled first: turning \"\" into j letters takes j insertions.",
      "Each cell reads three neighbours: up-left, up and left.",
    ],
    complexity: "O(len(a) × len(b)) time and space.",
    invariants: [
      "dp[i][j] is the edit distance between a[:i] and b[:j].",
    ],
    edgeCases: [
      "One word empty: the distance is the other word's length.",
    ],
    exercises: [
      "Print the actual edits by walking back from the bottom-right cell.",
      "Make a replacement cost 2. Which answers change?",
    ],
    variants: {
      py: {
        code: lines(
          "a = list(\"kitten\")",
          "b = list(\"sitting\")",
          "dp = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]",
          "for i in range(len(a) + 1):",
          "    dp[i][0] = i",
          "for j in range(len(b) + 1):",
          "    dp[0][j] = j",
          "for i in range(1, len(a) + 1):",
          "    for j in range(1, len(b) + 1):",
          "        if a[i - 1] == b[j - 1]:",
          "            dp[i][j] = dp[i - 1][j - 1]",
          "        else:",
          "            dp[i][j] = 1 + min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1])",
          "print(dp[len(a)][len(b)])",
        ),
        output: ["3"],
      },
      js: {
        code: lines(
          "const a = \"kitten\".split(\"\");",
          "const b = \"sitting\".split(\"\");",
          "const dp = [];",
          "for (let i = 0; i <= a.length; i++) dp.push(new Array(b.length + 1).fill(0));",
          "for (let i = 0; i <= a.length; i++) dp[i][0] = i;",
          "for (let j = 0; j <= b.length; j++) dp[0][j] = j;",
          "for (let i = 1; i <= a.length; i++) {",
          "  for (let j = 1; j <= b.length; j++) {",
          "    if (a[i - 1] === b[j - 1]) {",
          "      dp[i][j] = dp[i - 1][j - 1];",
          "    } else {",
          "      dp[i][j] = 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]);",
          "    }",
          "  }",
          "}",
          "console.log(dp[a.length][b.length]);",
        ),
        output: ["3"],
      },
    },
  },
  {
    id: "algo-knapsack",
    title: "0/1 knapsack",
    group: "Dynamic Programming",
    difficulty: "Advanced",
    concept: "Choose items to carry, each at most once, to get the most value without going over a weight limit. dp[i][w] is the best value using the first i items with capacity w. For item i, either leave it (dp[i - 1][w]) or take it, if it fits, and add its value to the best you could do with the weight that is left (dp[i - 1][w - weight] + value). Every row only reads the row above.",
    prerequisites: ["Nested lists (a grid)", "Nested loops"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "Taking an item reads a cell further left in the row above: the capacity left after carrying it.",
    ],
    complexity: "O(items × capacity) time and space.",
    invariants: [
      "dp[i][w] is the best value from the first i items within weight w.",
    ],
    edgeCases: [
      "An item heavier than the capacity is never taken.",
      "Capacity 0: value 0.",
    ],
    exercises: [
      "Walk back from dp[n][capacity] to list the items taken.",
      "Use one row instead of a grid. (Why must w then go from high to low?)",
    ],
    variants: {
      py: {
        code: lines(
          "weights = [1, 3, 4, 5]",
          "values = [1, 4, 5, 7]",
          "capacity = 7",
          "n = len(weights)",
          "dp = [[0] * (capacity + 1) for _ in range(n + 1)]",
          "for i in range(1, n + 1):",
          "    for w in range(capacity + 1):",
          "        dp[i][w] = dp[i - 1][w]                 # leave item i - 1",
          "        if weights[i - 1] <= w:                 # or take it, if it fits",
          "            dp[i][w] = max(dp[i][w], dp[i - 1][w - weights[i - 1]] + values[i - 1])",
          "print(dp[n][capacity])",
        ),
        output: ["9"],
      },
      js: {
        code: lines(
          "const weights = [1, 3, 4, 5];",
          "const values = [1, 4, 5, 7];",
          "const capacity = 7;",
          "const n = weights.length;",
          "const dp = [];",
          "for (let i = 0; i <= n; i++) dp.push(new Array(capacity + 1).fill(0));",
          "for (let i = 1; i <= n; i++) {",
          "  for (let w = 0; w <= capacity; w++) {",
          "    dp[i][w] = dp[i - 1][w]; // leave item i - 1",
          "    if (weights[i - 1] <= w) { // or take it, if it fits",
          "      dp[i][w] = Math.max(dp[i][w], dp[i - 1][w - weights[i - 1]] + values[i - 1]);",
          "    }",
          "  }",
          "}",
          "console.log(dp[n][capacity]);",
        ),
        output: ["9"],
      },
    },
  },
  {
    id: "algo-lis",
    title: "Longest increasing subsequence",
    group: "Dynamic Programming",
    difficulty: "Intermediate",
    concept: "The longest subsequence whose numbers keep increasing (LeetCode 300). dp[i] is the length of the longest one that ends with nums[i]: look back at every earlier j with a smaller number, and extend the best of those by one. The answer is the largest dp value.",
    prerequisites: ["Lists", "Nested loops"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "j scanning back over every earlier position while i stays put.",
    ],
    complexity: "O(n²) here; an O(n log n) version uses binary search.",
    invariants: [
      "dp[k] is the longest increasing run ending with nums[k], for every k < i.",
    ],
    edgeCases: [
      "A strictly decreasing list: every dp value is 1.",
    ],
    exercises: [
      "Print one of the longest subsequences.",
      "Allow equal neighbours (non-decreasing).",
    ],
    variants: {
      py: {
        code: lines(
          "nums = [10, 9, 2, 5, 3, 7, 101, 18]",
          "dp = [1] * len(nums)",
          "for i in range(1, len(nums)):",
          "    for j in range(i):",
          "        if nums[j] < nums[i]:",
          "            dp[i] = max(dp[i], dp[j] + 1)",
          "print(max(dp))",
        ),
        output: ["4"],
      },
      js: {
        code: lines(
          "const nums = [10, 9, 2, 5, 3, 7, 101, 18];",
          "const dp = new Array(nums.length).fill(1);",
          "for (let i = 1; i < nums.length; i++) {",
          "  for (let j = 0; j < i; j++) {",
          "    if (nums[j] < nums[i]) dp[i] = Math.max(dp[i], dp[j] + 1);",
          "  }",
          "}",
          "console.log(Math.max(...dp));",
        ),
        output: ["4"],
      },
    },
  },
  {
    id: "algo-unique-paths",
    title: "Unique paths in a grid",
    group: "Dynamic Programming",
    difficulty: "Beginner",
    concept: "A robot at the top-left of a grid moves only right or down. How many routes reach the bottom-right (LeetCode 62)? Every cell is reached either from the cell above or from the cell to the left, so paths[r][c] = paths[r - 1][c] + paths[r][c - 1]. The first row and column have exactly one route each.",
    prerequisites: ["Nested lists (a grid)", "Nested loops"],
    watch: [
      "In the Picture tab: the orange cell is the one just filled in, and the cells outlined in blue are the earlier answers it was built from. That arrow from small answers to bigger ones is what dynamic programming is.",
      "The numbers growing across the grid: they are Pascal's triangle, turned on its side.",
    ],
    complexity: "O(rows × cols) time and space.",
    invariants: [
      "paths[r][c] is the number of routes from the top-left to (r, c).",
    ],
    edgeCases: [
      "A 1 × n grid: one route.",
    ],
    exercises: [
      "Add obstacles: a blocked cell has 0 routes.",
      "Check the answer against the formula C(rows + cols - 2, rows - 1).",
    ],
    variants: {
      py: {
        code: lines(
          "rows, cols = 3, 4",
          "paths = [[1] * cols for _ in range(rows)]",
          "for r in range(1, rows):",
          "    for c in range(1, cols):",
          "        paths[r][c] = paths[r - 1][c] + paths[r][c - 1]",
          "print(paths[rows - 1][cols - 1])",
        ),
        output: ["10"],
      },
      js: {
        code: lines(
          "const rows = 3;",
          "const cols = 4;",
          "const paths = [];",
          "for (let r = 0; r < rows; r++) paths.push(new Array(cols).fill(1));",
          "for (let r = 1; r < rows; r++) {",
          "  for (let c = 1; c < cols; c++) {",
          "    paths[r][c] = paths[r - 1][c] + paths[r][c - 1];",
          "  }",
          "}",
          "console.log(paths[rows - 1][cols - 1]);",
        ),
        output: ["10"],
      },
    },
  },
  {
    id: "algo-bfs-grid",
    title: "Breadth-first search: shortest path in a maze",
    group: "Graphs",
    difficulty: "Intermediate",
    concept: "Breadth-first search explores outward from the start one ring at a time, using a queue: take the oldest cell, and add each open neighbour that has not been reached yet, one step further away. Because nearer cells always leave the queue first, the first time a cell is reached is by a shortest route. Game pathfinding, the \"six degrees\" of a social network and web crawlers all work this way.",
    prerequisites: ["Nested lists (a grid)", "Queues", "while loops"],
    watch: [
      "The dist grid in the Picture tab filling in ring by ring: 1s, then 2s, then 3s.",
      "The queue: cells join at the back and leave from the front.",
      "r and c (the cell being expanded) and nr and nc (the neighbour being tried) as row and column pointers.",
    ],
    complexity: "O(rows × cols): every cell joins the queue at most once.",
    invariants: [
      "The queue holds cells in order of distance, never more than one step apart.",
      "dist[r][c] is final as soon as it is set.",
    ],
    edgeCases: [
      "The goal can't be reached: its dist stays -1.",
      "A wall at the start or the goal.",
    ],
    exercises: [
      "Record where each cell was reached from, and print the path.",
      "Allow diagonal moves.",
      "Use a stack instead of a queue. Is the answer still the shortest? Why not?",
    ],
    variants: {
      py: {
        code: lines(
          "from collections import deque",
          "",
          "grid = [",
          "    [0, 0, 0, 1],",
          "    [1, 1, 0, 1],",
          "    [0, 0, 0, 0],",
          "    [0, 1, 1, 0],",
          "]",
          "rows, cols = len(grid), len(grid[0])",
          "dist = [[-1] * cols for _ in range(rows)]",
          "dist[0][0] = 0",
          "queue = deque([(0, 0)])",
          "while queue:",
          "    r, c = queue.popleft()",
          "    for dr, dc in [(1, 0), (-1, 0), (0, 1), (0, -1)]:",
          "        nr, nc = r + dr, c + dc",
          "        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == 0 and dist[nr][nc] == -1:",
          "            dist[nr][nc] = dist[r][c] + 1",
          "            queue.append((nr, nc))",
          "print(dist[rows - 1][cols - 1])",
        ),
        output: ["6"],
      },
      js: {
        code: lines(
          "const grid = [",
          "  [0, 0, 0, 1],",
          "  [1, 1, 0, 1],",
          "  [0, 0, 0, 0],",
          "  [0, 1, 1, 0],",
          "];",
          "const rows = grid.length;",
          "const cols = grid[0].length;",
          "const dist = [];",
          "for (let r = 0; r < rows; r++) dist.push(new Array(cols).fill(-1));",
          "dist[0][0] = 0;",
          "const queue = [[0, 0]];",
          "while (queue.length > 0) {",
          "  const [r, c] = queue.shift();",
          "  for (const [dr, dc] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {",
          "    const nr = r + dr;",
          "    const nc = c + dc;",
          "    if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && grid[nr][nc] === 0 && dist[nr][nc] === -1) {",
          "      dist[nr][nc] = dist[r][c] + 1;",
          "      queue.push([nr, nc]);",
          "    }",
          "  }",
          "}",
          "console.log(dist[rows - 1][cols - 1]);",
        ),
        output: ["6"],
      },
    },
  },
  {
    id: "algo-flood-fill",
    title: "Flood fill (depth-first, recursive)",
    group: "Game Logic",
    difficulty: "Beginner",
    concept: "Paint-bucket fill: change a cell, then do the same to each neighbour that still has the old colour. The recursion goes as deep as it can in one direction before backing up, which is depth-first search. Minesweeper uncovering empty areas and Go counting captured stones work the same way.",
    prerequisites: ["Recursion", "Nested lists (a grid)"],
    watch: [
      "The 2s spreading through the image in the Picture tab, one cell per call.",
      "The call stack growing (Calls tab) as the fill goes deeper, then shrinking as it backs up.",
      "The two base cases: off the edge, or not the old colour.",
    ],
    complexity: "O(cells): each cell is painted once; the recursion can be as deep as the region is big.",
    invariants: [
      "Every painted cell was the old colour and is connected to the start.",
    ],
    edgeCases: [
      "new equal to old: it would recurse forever. (Why? Add a check.)",
      "Filling from a cell that is a different colour: nothing happens.",
    ],
    exercises: [
      "Count the cells painted.",
      "Rewrite it with an explicit stack instead of recursion.",
      "Fill diagonally too.",
    ],
    variants: {
      py: {
        code: lines(
          "image = [",
          "    [1, 1, 1, 0],",
          "    [1, 1, 0, 0],",
          "    [1, 0, 1, 1],",
          "]",
          "",
          "def fill(r, c, old, new):",
          "    if r < 0 or r >= len(image) or c < 0 or c >= len(image[0]):",
          "        return",
          "    if image[r][c] != old:",
          "        return",
          "    image[r][c] = new",
          "    fill(r + 1, c, old, new)",
          "    fill(r - 1, c, old, new)",
          "    fill(r, c + 1, old, new)",
          "    fill(r, c - 1, old, new)",
          "",
          "fill(0, 0, 1, 2)",
          "for row in image:",
          "    print(\" \".join(str(v) for v in row))",
        ),
        output: ["2 2 2 0", "2 2 0 0", "2 0 1 1"],
      },
      js: {
        code: lines(
          "const image = [",
          "  [1, 1, 1, 0],",
          "  [1, 1, 0, 0],",
          "  [1, 0, 1, 1],",
          "];",
          "",
          "function fill(r, c, old, newColour) {",
          "  if (r < 0 || r >= image.length || c < 0 || c >= image[0].length) return;",
          "  if (image[r][c] !== old) return;",
          "  image[r][c] = newColour;",
          "  fill(r + 1, c, old, newColour);",
          "  fill(r - 1, c, old, newColour);",
          "  fill(r, c + 1, old, newColour);",
          "  fill(r, c - 1, old, newColour);",
          "}",
          "",
          "fill(0, 0, 1, 2);",
          "for (const row of image) console.log(row.join(\" \"));",
        ),
        output: ["2 2 2 0", "2 2 0 0", "2 0 1 1"],
      },
    },
  },
  {
    id: "algo-dijkstra",
    title: "Dijkstra's shortest paths",
    group: "Graphs",
    difficulty: "Advanced",
    concept: "Shortest distances from one node when edges have different lengths. Repeatedly pick the unvisited node with the smallest known distance: no shorter route to it can exist, because every other route would pass through a node that is already at least as far. Mark it visited, then try each of its edges: if going through it gives a neighbour a shorter distance, update it. This version picks the next node with a simple scan; real implementations use a heap (see the binary heap example).",
    prerequisites: ["Dictionaries", "Nested loops"],
    watch: [
      "dist in the Picture tab: values only ever go down, and each is final once its node is visited.",
      "B: first reached at distance 4 straight from A, then improved to 3 through C.",
    ],
    complexity: "O(V²) with this scan; O((V + E) log V) with a heap.",
    invariants: [
      "Every visited node's dist is its true shortest distance.",
    ],
    edgeCases: [
      "A node that can't be reached keeps INF.",
      "Negative edge lengths break the reasoning (use Bellman-Ford).",
    ],
    exercises: [
      "Record each node's previous node and print the route to D.",
      "Replace the scan with a heap.",
    ],
    variants: {
      py: {
        code: lines(
          "graph = {",
          "    \"A\": {\"B\": 4, \"C\": 1},",
          "    \"B\": {\"D\": 1},",
          "    \"C\": {\"B\": 2, \"D\": 5},",
          "    \"D\": {},",
          "}",
          "INF = 999",
          "dist = {node: INF for node in graph}",
          "dist[\"A\"] = 0",
          "visited = {node: False for node in graph}",
          "for _ in range(len(graph)):",
          "    current = None",
          "    for node in graph:   # the unvisited node with the smallest distance",
          "        if not visited[node] and (current is None or dist[node] < dist[current]):",
          "            current = node",
          "    visited[current] = True",
          "    for neighbour, length in graph[current].items():",
          "        if dist[current] + length < dist[neighbour]:",
          "            dist[neighbour] = dist[current] + length",
          "print(\" \".join(f\"{node}:{dist[node]}\" for node in graph))",
        ),
        output: ["A:0 B:3 C:1 D:4"],
      },
      js: {
        code: lines(
          "const graph = {",
          "  A: { B: 4, C: 1 },",
          "  B: { D: 1 },",
          "  C: { B: 2, D: 5 },",
          "  D: {},",
          "};",
          "const INF = 999;",
          "const nodes = Object.keys(graph);",
          "const dist = {};",
          "const visited = {};",
          "for (const node of nodes) {",
          "  dist[node] = INF;",
          "  visited[node] = false;",
          "}",
          "dist.A = 0;",
          "for (let k = 0; k < nodes.length; k++) {",
          "  let current = null;",
          "  for (const node of nodes) { // the unvisited node with the smallest distance",
          "    if (!visited[node] && (current === null || dist[node] < dist[current])) current = node;",
          "  }",
          "  visited[current] = true;",
          "  for (const neighbour of Object.keys(graph[current])) {",
          "    const length = graph[current][neighbour];",
          "    if (dist[current] + length < dist[neighbour]) dist[neighbour] = dist[current] + length;",
          "  }",
          "}",
          "console.log(nodes.map(node => node + \":\" + dist[node]).join(\" \"));",
        ),
        output: ["A:0 B:3 C:1 D:4"],
      },
    },
  },
  {
    id: "algo-topological-sort",
    title: "Topological sort (getting dressed)",
    group: "Graphs",
    difficulty: "Intermediate",
    concept: "Put tasks in an order that respects every \"this before that\" rule. Count, for each task, how many rules point at it (its in-degree). Tasks with none can go first; doing one removes its rules, which may free more tasks. If tasks are left over that never reach zero, the rules contain a cycle and no order exists. Build systems, course prerequisites and spreadsheet recalculation all do this (Kahn's algorithm).",
    prerequisites: ["Dictionaries", "Lists", "while loops"],
    watch: [
      "indegree in the Picture tab: each count goes down as its prerequisites are done, and the task joins the queue at zero.",
      "order growing at the end.",
    ],
    complexity: "O(tasks + rules).",
    invariants: [
      "Every task in order has all of its prerequisites earlier in order.",
    ],
    edgeCases: [
      "A cycle (add \"jacket\": [\"shirt\"]): order ends up shorter than the number of tasks.",
    ],
    exercises: [
      "Detect a cycle and print a message.",
      "Among the tasks that are ready, always take the alphabetically first.",
    ],
    variants: {
      py: {
        code: lines(
          "before = {",
          "    \"shirt\": [\"tie\", \"belt\"],",
          "    \"tie\": [\"jacket\"],",
          "    \"pants\": [\"shoes\", \"belt\"],",
          "    \"belt\": [\"jacket\"],",
          "    \"socks\": [\"shoes\"],",
          "    \"shoes\": [],",
          "    \"jacket\": [],",
          "}",
          "indegree = {task: 0 for task in before}",
          "for task in before:",
          "    for after in before[task]:",
          "        indegree[after] += 1",
          "queue = [task for task in before if indegree[task] == 0]",
          "order = []",
          "while queue:",
          "    task = queue.pop(0)",
          "    order.append(task)",
          "    for after in before[task]:",
          "        indegree[after] -= 1",
          "        if indegree[after] == 0:",
          "            queue.append(after)",
          "print(\" \".join(order))",
        ),
        output: ["shirt pants socks tie belt shoes jacket"],
      },
      js: {
        code: lines(
          "const before = {",
          "  shirt: [\"tie\", \"belt\"],",
          "  tie: [\"jacket\"],",
          "  pants: [\"shoes\", \"belt\"],",
          "  belt: [\"jacket\"],",
          "  socks: [\"shoes\"],",
          "  shoes: [],",
          "  jacket: [],",
          "};",
          "const tasks = Object.keys(before);",
          "const indegree = {};",
          "for (const task of tasks) indegree[task] = 0;",
          "for (const task of tasks) {",
          "  for (const after of before[task]) indegree[after]++;",
          "}",
          "const queue = tasks.filter(task => indegree[task] === 0);",
          "const order = [];",
          "while (queue.length > 0) {",
          "  const task = queue.shift();",
          "  order.push(task);",
          "  for (const after of before[task]) {",
          "    indegree[after]--;",
          "    if (indegree[after] === 0) queue.push(after);",
          "  }",
          "}",
          "console.log(order.join(\" \"));",
        ),
        output: ["shirt pants socks tie belt shoes jacket"],
      },
    },
  },
  {
    id: "algo-union-find",
    title: "Union-find (disjoint sets)",
    group: "Graphs",
    difficulty: "Intermediate",
    concept: "Keep track of which items are connected as connections are added. Each item points to a parent; an item that is its own parent is the root, the name of its group. find follows parents up to the root; union joins two groups by pointing one root at the other. Path halving (pointing each item at its grandparent on the way up) keeps the chains short. Kruskal's spanning tree and \"are these two pixels in the same region\" use it.",
    prerequisites: ["Lists", "while loops", "Functions"],
    watch: [
      "parent in the Picture tab: union changes one entry; find's path halving shortens chains as a side effect.",
      "x climbing towards the root inside find.",
    ],
    complexity: "Almost O(1) per operation with path compression and union by size; path halving alone is already fast in practice.",
    invariants: [
      "Two items are in the same group exactly when find gives the same root.",
    ],
    edgeCases: [
      "Joining two items already in the same group changes nothing.",
    ],
    exercises: [
      "Count the groups at the end.",
      "Add union by size: always hang the smaller group under the larger.",
    ],
    variants: {
      py: {
        code: lines(
          "parent = [0, 1, 2, 3, 4, 5]",
          "",
          "def find(x):",
          "    while parent[x] != x:",
          "        parent[x] = parent[parent[x]]   # path halving",
          "        x = parent[x]",
          "    return x",
          "",
          "def union(a, b):",
          "    ra, rb = find(a), find(b)",
          "    if ra != rb:",
          "        parent[rb] = ra",
          "",
          "for a, b in [(0, 1), (2, 3), (1, 3), (4, 5)]:",
          "    union(a, b)",
          "print(find(3), find(2), find(5))",
        ),
        output: ["0 0 4"],
      },
      js: {
        code: lines(
          "const parent = [0, 1, 2, 3, 4, 5];",
          "",
          "function find(x) {",
          "  while (parent[x] !== x) {",
          "    parent[x] = parent[parent[x]]; // path halving",
          "    x = parent[x];",
          "  }",
          "  return x;",
          "}",
          "",
          "function union(a, b) {",
          "  const ra = find(a);",
          "  const rb = find(b);",
          "  if (ra !== rb) parent[rb] = ra;",
          "}",
          "",
          "for (const [a, b] of [[0, 1], [2, 3], [1, 3], [4, 5]]) union(a, b);",
          "console.log(find(3), find(2), find(5));",
        ),
        output: ["0 0 4"],
      },
    },
  },
  {
    id: "algo-reverse-linked-list",
    title: "Reverse a linked list",
    group: "Data Structures",
    difficulty: "Beginner",
    concept: "Reverse a linked list in place by turning each node's next arrow around, one node at a time (LeetCode 206). Three pointers do it: prev (the reversed part so far), cur (the node being turned) and nxt (saved before cur.next is overwritten, or the rest of the list would be lost).",
    prerequisites: ["Classes and objects", "References"],
    watch: [
      "The Picture tab: the arrow that changes colour each time round is cur.next being turned to point at prev.",
      "The list splits into two chains, the reversed part and the rest, and the tags prev, cur and nxt mark where.",
      "Why nxt must be saved first: try deleting that line.",
    ],
    complexity: "O(n) time, O(1) extra space.",
    invariants: [
      "prev heads the reversed part; cur heads the part still to do; nothing is ever lost.",
    ],
    edgeCases: [
      "An empty list, and a list of one node.",
    ],
    exercises: [
      "Reverse it recursively.",
      "Reverse only the first k nodes.",
    ],
    variants: {
      py: {
        code: lines(
          "class Node:",
          "    def __init__(self, value, next=None):",
          "        self.value = value",
          "        self.next = next",
          "",
          "head = Node(1, Node(2, Node(3, Node(4))))",
          "prev = None",
          "cur = head",
          "while cur:",
          "    nxt = cur.next      # save the rest of the list",
          "    cur.next = prev     # turn the arrow around",
          "    prev = cur",
          "    cur = nxt",
          "head = prev",
          "",
          "values = []",
          "node = head",
          "while node:",
          "    values.append(str(node.value))",
          "    node = node.next",
          "print(\" \".join(values))",
        ),
        output: ["4 3 2 1"],
      },
      js: {
        code: lines(
          "class Node {",
          "  constructor(value, next = null) {",
          "    this.value = value;",
          "    this.next = next;",
          "  }",
          "}",
          "",
          "let head = new Node(1, new Node(2, new Node(3, new Node(4))));",
          "let prev = null;",
          "let cur = head;",
          "while (cur) {",
          "  const nxt = cur.next; // save the rest of the list",
          "  cur.next = prev; // turn the arrow around",
          "  prev = cur;",
          "  cur = nxt;",
          "}",
          "head = prev;",
          "",
          "const values = [];",
          "for (let node = head; node; node = node.next) values.push(node.value);",
          "console.log(values.join(\" \"));",
        ),
        output: ["4 3 2 1"],
      },
    },
  },
  {
    id: "algo-floyd-cycle",
    title: "Floyd's cycle detection (tortoise and hare)",
    group: "Data Structures",
    difficulty: "Intermediate",
    concept: "Does a linked list loop back on itself? Move one pointer one step at a time (slow) and another two steps (fast). Without a cycle, fast reaches the end. With one, fast laps slow inside the loop and they meet, because the gap between them shrinks by one every step. Then a pointer from the head and one from the meeting point, both moving one step, meet exactly where the cycle starts.",
    prerequisites: ["Classes and objects", "References", "while loops"],
    watch: [
      "The Picture tab draws the list as a graph: node 5 points back to node 3.",
      "The slow and fast tags moving around the loop until they land on the same node.",
      "The second phase: slow restarts at head, and both now move one step.",
    ],
    complexity: "O(n) time, O(1) extra space (no set of visited nodes needed).",
    invariants: [
      "Inside the cycle, the distance from fast to slow shrinks by one every step.",
    ],
    edgeCases: [
      "No cycle.",
      "A cycle that is the whole list (the last node points to the head).",
    ],
    exercises: [
      "Measure the cycle length once they meet.",
      "Prove (or check on paper) why the second phase finds the start.",
    ],
    variants: {
      py: {
        code: lines(
          "class Node:",
          "    def __init__(self, value):",
          "        self.value = value",
          "        self.next = None",
          "",
          "nodes = [Node(v) for v in [1, 2, 3, 4, 5]]",
          "for a, b in zip(nodes, nodes[1:]):",
          "    a.next = b",
          "nodes[4].next = nodes[2]          # 5 points back to 3: a cycle",
          "head = nodes[0]",
          "",
          "slow = fast = head",
          "while fast and fast.next:",
          "    slow = slow.next",
          "    fast = fast.next.next",
          "    if slow is fast:",
          "        break",
          "slow = head                       # find where the cycle starts",
          "while slow is not fast:",
          "    slow = slow.next",
          "    fast = fast.next",
          "print(\"cycle starts at\", slow.value)",
        ),
        output: ["cycle starts at 3"],
      },
      js: {
        code: lines(
          "class Node {",
          "  constructor(value) {",
          "    this.value = value;",
          "    this.next = null;",
          "  }",
          "}",
          "",
          "const nodes = [1, 2, 3, 4, 5].map(v => new Node(v));",
          "for (let i = 0; i < nodes.length - 1; i++) nodes[i].next = nodes[i + 1];",
          "nodes[4].next = nodes[2]; // 5 points back to 3: a cycle",
          "const head = nodes[0];",
          "",
          "let slow = head;",
          "let fast = head;",
          "while (fast && fast.next) {",
          "  slow = slow.next;",
          "  fast = fast.next.next;",
          "  if (slow === fast) break;",
          "}",
          "slow = head; // find where the cycle starts",
          "while (slow !== fast) {",
          "  slow = slow.next;",
          "  fast = fast.next;",
          "}",
          "console.log(\"cycle starts at\", slow.value);",
        ),
        output: ["cycle starts at 3"],
      },
    },
  },
  {
    id: "algo-n-queens",
    title: "N-Queens (backtracking)",
    group: "Backtracking",
    difficulty: "Advanced",
    concept: "Place n queens on an n × n board so that no two share a row, column or diagonal. Place one queen per row: try each column, and if it is safe, place the queen and go on to the next row. If a row has no safe column, back up: remove the last queen and try its next column. That undo step is backtracking, and the same shape solves Sudoku, crosswords and puzzle searches.",
    prerequisites: ["Recursion", "Nested lists (a grid)"],
    watch: [
      "The board in the Picture tab: a Q appears, the search goes a row deeper, and when it gets stuck the Q is taken back off.",
      "cols[r] records the column of the queen in row r; safe() only needs that.",
      "Two queens are on the same diagonal when their row distance equals their column distance.",
    ],
    complexity: "Exponential in the worst case, but cutting off unsafe placements early prunes most of the search.",
    invariants: [
      "The queens in rows 0 to row - 1 never attack each other.",
    ],
    edgeCases: [
      "n = 2 and n = 3 have no solutions.",
    ],
    exercises: [
      "Count the calls to place. How many would there be without the safe() check?",
      "Print every solution as a board.",
      "Speed safe() up with sets of used columns and diagonals.",
    ],
    variants: {
      py: {
        code: lines(
          "n = 4",
          "board = [[\".\"] * n for _ in range(n)]",
          "cols = [-1] * n",
          "solutions = 0",
          "first = None",
          "",
          "def safe(row, col):",
          "    for r in range(row):",
          "        if cols[r] == col or abs(cols[r] - col) == row - r:",
          "            return False",
          "    return True",
          "",
          "def place(row):",
          "    global solutions, first",
          "    if row == n:",
          "        solutions += 1",
          "        if first is None:",
          "            first = cols[:]",
          "        return",
          "    for col in range(n):",
          "        if safe(row, col):",
          "            cols[row] = col",
          "            board[row][col] = \"Q\"",
          "            place(row + 1)",
          "            board[row][col] = \".\"   # take it back and try the next column",
          "            cols[row] = -1",
          "",
          "place(0)",
          "print(solutions, \" \".join(str(c) for c in first))",
        ),
        output: ["2 1 3 0 2"],
      },
      js: {
        code: lines(
          "const n = 4;",
          "const board = [];",
          "for (let r = 0; r < n; r++) board.push(new Array(n).fill(\".\"));",
          "const cols = new Array(n).fill(-1);",
          "let solutions = 0;",
          "let first = null;",
          "",
          "function safe(row, col) {",
          "  for (let r = 0; r < row; r++) {",
          "    if (cols[r] === col || Math.abs(cols[r] - col) === row - r) return false;",
          "  }",
          "  return true;",
          "}",
          "",
          "function place(row) {",
          "  if (row === n) {",
          "    solutions++;",
          "    if (first === null) first = cols.slice();",
          "    return;",
          "  }",
          "  for (let col = 0; col < n; col++) {",
          "    if (safe(row, col)) {",
          "      cols[row] = col;",
          "      board[row][col] = \"Q\";",
          "      place(row + 1);",
          "      board[row][col] = \".\"; // take it back and try the next column",
          "      cols[row] = -1;",
          "    }",
          "  }",
          "}",
          "",
          "place(0);",
          "console.log(solutions, first.join(\" \"));",
        ),
        output: ["2 1 3 0 2"],
      },
    },
  },
  {
    id: "algo-permutations",
    title: "All permutations (backtracking)",
    group: "Backtracking",
    difficulty: "Intermediate",
    concept: "List every ordering of some items (LeetCode 46). Build an ordering one item at a time in path: for each item not yet used, add it, explore everything that can follow, then remove it again and try the next. used records which items are in path. The pattern choose, explore, un-choose is the heart of every backtracking search.",
    prerequisites: ["Recursion", "Lists (append and pop)"],
    watch: [
      "path and used in the Picture tab growing and shrinking together: one push and one pop per choice.",
      "The call stack depth (Calls tab) equals the length of path.",
    ],
    complexity: "n! orderings, each built in O(n): O(n · n!).",
    invariants: [
      "used[i] is True exactly when nums[i] is in path.",
    ],
    edgeCases: [
      "Repeated items give repeated orderings (an exercise fixes it).",
    ],
    exercises: [
      "Generate all subsets instead (each item is in or out).",
      "Skip duplicate orderings when nums has repeated values.",
    ],
    variants: {
      py: {
        code: lines(
          "nums = [1, 2, 3]",
          "path = []",
          "used = [False] * len(nums)",
          "results = []",
          "",
          "def backtrack():",
          "    if len(path) == len(nums):",
          "        results.append(\"\".join(str(v) for v in path))",
          "        return",
          "    for i in range(len(nums)):",
          "        if not used[i]:",
          "            used[i] = True          # choose",
          "            path.append(nums[i])",
          "            backtrack()             # explore",
          "            path.pop()              # un-choose",
          "            used[i] = False",
          "",
          "backtrack()",
          "print(len(results), \" \".join(results))",
        ),
        output: ["6 123 132 213 231 312 321"],
      },
      js: {
        code: lines(
          "const nums = [1, 2, 3];",
          "const path = [];",
          "const used = new Array(nums.length).fill(false);",
          "const results = [];",
          "",
          "function backtrack() {",
          "  if (path.length === nums.length) {",
          "    results.push(path.join(\"\"));",
          "    return;",
          "  }",
          "  for (let i = 0; i < nums.length; i++) {",
          "    if (!used[i]) {",
          "      used[i] = true; // choose",
          "      path.push(nums[i]);",
          "      backtrack(); // explore",
          "      path.pop(); // un-choose",
          "      used[i] = false;",
          "    }",
          "  }",
          "}",
          "",
          "backtrack();",
          "console.log(results.length, results.join(\" \"));",
        ),
        output: ["6 123 132 213 231 312 321"],
      },
    },
  },
  {
    id: "algo-game-of-life",
    title: "Conway's Game of Life: one generation",
    group: "Game Logic",
    difficulty: "Beginner",
    concept: "Each cell of a grid is alive or dead. In the next generation a live cell survives with 2 or 3 live neighbours, and a dead cell comes alive with exactly 3. Every cell is decided from the current grid, so the new generation goes into a separate grid: writing into the same one would let early cells change the counts of later ones. The vertical bar of three (a \"blinker\") turns horizontal.",
    prerequisites: ["Nested lists (a grid)", "Nested loops"],
    watch: [
      "In the Picture tab, the eight cells outlined in blue around r, c: the neighbours being counted.",
      "nxt filling in while grid stays the same: the reason for two grids.",
    ],
    complexity: "O(rows × cols × 8) per generation.",
    invariants: [
      "grid is not changed while nxt is being computed.",
    ],
    edgeCases: [
      "Cells on the edge have fewer neighbours (the bounds check).",
    ],
    exercises: [
      "Write into grid directly instead of nxt, and see the blinker break.",
      "Run several generations of a glider.",
      "Make the grid wrap around at the edges.",
    ],
    variants: {
      py: {
        code: lines(
          "grid = [",
          "    [0, 0, 0, 0, 0],",
          "    [0, 0, 1, 0, 0],",
          "    [0, 0, 1, 0, 0],",
          "    [0, 0, 1, 0, 0],",
          "    [0, 0, 0, 0, 0],",
          "]",
          "rows, cols = len(grid), len(grid[0])",
          "nxt = [[0] * cols for _ in range(rows)]",
          "for r in range(rows):",
          "    for c in range(cols):",
          "        alive = 0",
          "        for dr in (-1, 0, 1):",
          "            for dc in (-1, 0, 1):",
          "                if (dr != 0 or dc != 0) and 0 <= r + dr < rows and 0 <= c + dc < cols:",
          "                    alive += grid[r + dr][c + dc]",
          "        if grid[r][c] == 1:",
          "            nxt[r][c] = 1 if alive in (2, 3) else 0",
          "        else:",
          "            nxt[r][c] = 1 if alive == 3 else 0",
          "for row in nxt:",
          "    print(\"\".join(\"#\" if v else \".\" for v in row))",
        ),
        output: [".....", ".....", ".###.", ".....", "....."],
      },
      js: {
        code: lines(
          "const grid = [",
          "  [0, 0, 0, 0, 0],",
          "  [0, 0, 1, 0, 0],",
          "  [0, 0, 1, 0, 0],",
          "  [0, 0, 1, 0, 0],",
          "  [0, 0, 0, 0, 0],",
          "];",
          "const rows = grid.length;",
          "const cols = grid[0].length;",
          "const nxt = [];",
          "for (let r = 0; r < rows; r++) nxt.push(new Array(cols).fill(0));",
          "for (let r = 0; r < rows; r++) {",
          "  for (let c = 0; c < cols; c++) {",
          "    let alive = 0;",
          "    for (const dr of [-1, 0, 1]) {",
          "      for (const dc of [-1, 0, 1]) {",
          "        if ((dr !== 0 || dc !== 0) && r + dr >= 0 && r + dr < rows && c + dc >= 0 && c + dc < cols) {",
          "          alive += grid[r + dr][c + dc];",
          "        }",
          "      }",
          "    }",
          "    if (grid[r][c] === 1) nxt[r][c] = alive === 2 || alive === 3 ? 1 : 0;",
          "    else nxt[r][c] = alive === 3 ? 1 : 0;",
          "  }",
          "}",
          "for (const row of nxt) console.log(row.map(v => (v ? \"#\" : \".\")).join(\"\"));",
        ),
        output: [".....", ".....", ".###.", ".....", "....."],
      },
    },
  },
  {
    id: "algo-minimax",
    title: "Minimax: perfect tic-tac-toe",
    group: "Game Logic",
    difficulty: "Advanced",
    concept: "Minimax decides a move by imagining every possible continuation of the game. X picks the move with the highest score and O the lowest, each assuming the other plays perfectly, down to finished games scored +1 (X wins), -1 (O wins) or 0 (draw). The score of a position is the score of its best continuation for the player to move. Chess and Go engines are built on this, with pruning and evaluation functions because the full tree is far too big.",
    prerequisites: ["Recursion", "Lists"],
    watch: [
      "O threatens the middle row (squares 3, 4, 5), so the only good move for X is to block at 5, and perfect play from there is a draw: score 0.",
      "The board in the Picture tab: a move is tried, explored, and undone (board[i] = \" \").",
      "The call stack (Calls tab) alternating between X and O.",
      "scores collecting the result of each move before max or min picks one.",
    ],
    complexity: "Exponential: up to 9! continuations from an empty board. This position has only three empty squares.",
    invariants: [
      "minimax returns the result of perfect play from this position.",
    ],
    edgeCases: [
      "A position that is already won or full.",
    ],
    exercises: [
      "Start from an empty board and count the positions explored.",
      "Add alpha-beta pruning and count again.",
      "Make O the player to move.",
    ],
    variants: {
      py: {
        code: lines(
          "LINES = [(0, 1, 2), (3, 4, 5), (6, 7, 8), (0, 3, 6), (1, 4, 7), (2, 5, 8), (0, 4, 8), (2, 4, 6)]",
          "board = [\"X\", \"O\", \"X\",",
          "         \"O\", \"O\", \" \",",
          "         \" \", \"X\", \" \"]",
          "",
          "def winner(b):",
          "    for p, q, r in LINES:",
          "        if b[p] != \" \" and b[p] == b[q] == b[r]:",
          "            return b[p]",
          "    return None",
          "",
          "def minimax(b, player):",
          "    w = winner(b)",
          "    if w == \"X\":",
          "        return 1",
          "    if w == \"O\":",
          "        return -1",
          "    if \" \" not in b:",
          "        return 0",
          "    scores = []",
          "    for i in range(9):",
          "        if b[i] == \" \":",
          "            b[i] = player",
          "            scores.append(minimax(b, \"O\" if player == \"X\" else \"X\"))",
          "            b[i] = \" \"",
          "    return max(scores) if player == \"X\" else min(scores)",
          "",
          "best_move, best_score = None, -2",
          "for i in range(9):",
          "    if board[i] == \" \":",
          "        board[i] = \"X\"",
          "        score = minimax(board, \"O\")",
          "        board[i] = \" \"",
          "        if score > best_score:",
          "            best_move, best_score = i, score",
          "print(\"best move\", best_move, \"score\", best_score)",
        ),
        output: ["best move 5 score 0"],
      },
      js: {
        code: lines(
          "const LINES = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];",
          "const board = [\"X\", \"O\", \"X\",",
          "               \"O\", \"O\", \" \",",
          "               \" \", \"X\", \" \"];",
          "",
          "function winner(b) {",
          "  for (const [p, q, r] of LINES) {",
          "    if (b[p] !== \" \" && b[p] === b[q] && b[q] === b[r]) return b[p];",
          "  }",
          "  return null;",
          "}",
          "",
          "function minimax(b, player) {",
          "  const w = winner(b);",
          "  if (w === \"X\") return 1;",
          "  if (w === \"O\") return -1;",
          "  if (b.indexOf(\" \") === -1) return 0;",
          "  const scores = [];",
          "  for (let i = 0; i < 9; i++) {",
          "    if (b[i] === \" \") {",
          "      b[i] = player;",
          "      scores.push(minimax(b, player === \"X\" ? \"O\" : \"X\"));",
          "      b[i] = \" \";",
          "    }",
          "  }",
          "  return player === \"X\" ? Math.max(...scores) : Math.min(...scores);",
          "}",
          "",
          "let bestMove = null;",
          "let bestScore = -2;",
          "for (let i = 0; i < 9; i++) {",
          "  if (board[i] === \" \") {",
          "    board[i] = \"X\";",
          "    const score = minimax(board, \"O\");",
          "    board[i] = \" \";",
          "    if (score > bestScore) {",
          "      bestMove = i;",
          "      bestScore = score;",
          "    }",
          "  }",
          "}",
          "console.log(\"best move\", bestMove, \"score\", bestScore);",
        ),
        output: ["best move 5 score 0"],
      },
    },
  },
  {
    id: "algo-gradient-descent",
    title: "Gradient descent: fitting a line",
    group: "Machine Learning",
    difficulty: "Intermediate",
    concept: "Fit y = w·x + b to some points by repeatedly nudging w and b downhill on the mean squared error. For each point, the error is prediction minus target; the gradient (how the loss changes as w or b changes) averages 2·error·x for w and 2·error for b. Stepping a little against the gradient lowers the loss. The data was made from y = 2x + 1, so w should approach 2 and b approach 1.",
    prerequisites: ["Lists", "for loops", "A little algebra (a line y = w·x + b)"],
    watch: [
      "preds in the Picture tab: each epoch rewrites all four predictions, and they creep towards ys.",
      "grad_w and grad_b shrinking as the line gets closer: the steps get smaller on their own.",
    ],
    complexity: "O(epochs × points).",
    invariants: [
      "Each step changes w and b in the direction that lowers the loss, for a small enough learning rate.",
    ],
    edgeCases: [
      "A learning rate that is too big: the loss grows instead (try lr = 0.2).",
    ],
    exercises: [
      "Print the loss every 20 epochs and watch it fall.",
      "Try lr = 0.2 and lr = 0.005, and explain what you see.",
      "Fit y = w·x² + b instead.",
    ],
    variants: {
      py: {
        code: lines(
          "xs = [1, 2, 3, 4]",
          "ys = [3, 5, 7, 9]           # made from y = 2x + 1",
          "w, b = 0.0, 0.0",
          "lr = 0.05",
          "preds = [0.0] * len(xs)",
          "for epoch in range(60):",
          "    grad_w, grad_b = 0.0, 0.0",
          "    for i in range(len(xs)):",
          "        preds[i] = w * xs[i] + b",
          "        error = preds[i] - ys[i]",
          "        grad_w += 2 * error * xs[i] / len(xs)",
          "        grad_b += 2 * error / len(xs)",
          "    w -= lr * grad_w         # step downhill",
          "    b -= lr * grad_b",
          "print(f\"w={w:.2f} b={b:.2f}\")",
        ),
        output: ["w=2.04 b=0.88"],
      },
      js: {
        code: lines(
          "const xs = [1, 2, 3, 4];",
          "const ys = [3, 5, 7, 9]; // made from y = 2x + 1",
          "let w = 0;",
          "let b = 0;",
          "const lr = 0.05;",
          "const preds = new Array(xs.length).fill(0);",
          "for (let epoch = 0; epoch < 60; epoch++) {",
          "  let gradW = 0;",
          "  let gradB = 0;",
          "  for (let i = 0; i < xs.length; i++) {",
          "    preds[i] = w * xs[i] + b;",
          "    const error = preds[i] - ys[i];",
          "    gradW += (2 * error * xs[i]) / xs.length;",
          "    gradB += (2 * error) / xs.length;",
          "  }",
          "  w -= lr * gradW; // step downhill",
          "  b -= lr * gradB;",
          "}",
          "console.log(\"w=\" + w.toFixed(2) + \" b=\" + b.toFixed(2));",
        ),
        output: ["w=2.04 b=0.88"],
      },
    },
  },
  {
    id: "algo-k-means",
    title: "k-means clustering",
    group: "Machine Learning",
    difficulty: "Intermediate",
    concept: "Split points into k groups by alternating two steps: assign every point to its nearest centroid, then move each centroid to the mean of its points. Neither step can make the total distance worse, so it settles, usually within a few rounds. Starting both centroids on the left shows them being pulled apart into the two groups.",
    prerequisites: ["Lists", "abs and averages"],
    watch: [
      "labels in the Picture tab being rewritten in the assign step.",
      "centroids moving in the update step: 1 and 3 become 2 and 11.",
    ],
    complexity: "O(rounds × points × k).",
    invariants: [
      "After the update step, each centroid is the mean of the points labelled with it.",
    ],
    edgeCases: [
      "A centroid with no points (its mean is undefined: try starting both at 100).",
    ],
    exercises: [
      "Use 2-D points (x, y) and distance squared.",
      "Stop when no label changes instead of after 3 rounds.",
      "Try k = 3.",
    ],
    variants: {
      py: {
        code: lines(
          "points = [1, 2, 3, 10, 11, 12]",
          "centroids = [1.0, 3.0]",
          "labels = [0] * len(points)",
          "for round_ in range(3):",
          "    for i in range(len(points)):          # assign each point to the nearest centroid",
          "        if abs(points[i] - centroids[0]) <= abs(points[i] - centroids[1]):",
          "            labels[i] = 0",
          "        else:",
          "            labels[i] = 1",
          "    for k in range(2):                    # move each centroid to its points' mean",
          "        members = [points[i] for i in range(len(points)) if labels[i] == k]",
          "        centroids[k] = sum(members) / len(members)",
          "print(\" \".join(f\"{c:.1f}\" for c in centroids))",
        ),
        output: ["2.0 11.0"],
      },
      js: {
        code: lines(
          "const points = [1, 2, 3, 10, 11, 12];",
          "const centroids = [1, 3];",
          "const labels = new Array(points.length).fill(0);",
          "for (let round = 0; round < 3; round++) {",
          "  for (let i = 0; i < points.length; i++) { // assign each point to the nearest centroid",
          "    if (Math.abs(points[i] - centroids[0]) <= Math.abs(points[i] - centroids[1])) labels[i] = 0;",
          "    else labels[i] = 1;",
          "  }",
          "  for (let k = 0; k < 2; k++) { // move each centroid to its points' mean",
          "    const members = points.filter((p, i) => labels[i] === k);",
          "    centroids[k] = members.reduce((s, v) => s + v, 0) / members.length;",
          "  }",
          "}",
          "console.log(centroids.map(c => c.toFixed(1)).join(\" \"));",
        ),
        output: ["2.0 11.0"],
      },
    },
  },
  {
    id: "algo-perceptron",
    title: "Perceptron: learning AND",
    group: "Machine Learning",
    difficulty: "Intermediate",
    concept: "A perceptron outputs 1 when w·x + b is positive and 0 otherwise: a straight line splitting the inputs. It learns by correcting itself: on a wrong answer it moves each weight by learning rate × error × input, nudging the line towards the point it got wrong. If a straight line can separate the classes, as for AND, it stops making mistakes after a few passes.",
    prerequisites: ["Lists", "Nested loops"],
    watch: [
      "w in the Picture tab changing only on mistakes.",
      "mistakes counting down to 0, which ends the training.",
    ],
    complexity: "O(epochs × examples × inputs).",
    invariants: [
      "A correct answer leaves the weights unchanged.",
    ],
    edgeCases: [
      "XOR: no line separates it, so it never reaches zero mistakes (try it).",
    ],
    exercises: [
      "Teach it OR.",
      "Try XOR and explain why it fails; this is why networks have hidden layers.",
    ],
    variants: {
      py: {
        code: lines(
          "data = [([0, 0], 0), ([0, 1], 0), ([1, 0], 0), ([1, 1], 1)]",
          "w = [0.0, 0.0]",
          "b = 0.0",
          "lr = 0.1",
          "for epoch in range(20):",
          "    mistakes = 0",
          "    for x, target in data:",
          "        out = 1 if w[0] * x[0] + w[1] * x[1] + b > 0 else 0",
          "        error = target - out",
          "        if error != 0:",
          "            mistakes += 1",
          "            w[0] += lr * error * x[0]",
          "            w[1] += lr * error * x[1]",
          "            b += lr * error",
          "    if mistakes == 0:",
          "        break",
          "print(f\"w={w[0]:.1f},{w[1]:.1f} b={b:.1f} epochs={epoch + 1}\")",
        ),
        output: ["w=0.2,0.1 b=-0.2 epochs=6"],
      },
      js: {
        code: lines(
          "const data = [[[0, 0], 0], [[0, 1], 0], [[1, 0], 0], [[1, 1], 1]];",
          "const w = [0, 0];",
          "let b = 0;",
          "const lr = 0.1;",
          "let epoch = 0;",
          "for (epoch = 0; epoch < 20; epoch++) {",
          "  let mistakes = 0;",
          "  for (const [x, target] of data) {",
          "    const out = w[0] * x[0] + w[1] * x[1] + b > 0 ? 1 : 0;",
          "    const error = target - out;",
          "    if (error !== 0) {",
          "      mistakes++;",
          "      w[0] += lr * error * x[0];",
          "      w[1] += lr * error * x[1];",
          "      b += lr * error;",
          "    }",
          "  }",
          "  if (mistakes === 0) break;",
          "}",
          "console.log(\"w=\" + w[0].toFixed(1) + \",\" + w[1].toFixed(1) + \" b=\" + b.toFixed(1) + \" epochs=\" + (epoch + 1));",
        ),
        output: ["w=0.2,0.1 b=-0.2 epochs=6"],
      },
    },
  },
  {
    id: "algo-value-iteration",
    title: "Value iteration on a grid",
    group: "Reinforcement Learning",
    difficulty: "Advanced",
    concept: "How good is each square of a grid, if you play perfectly from it? Value iteration answers by repeated sweeps: a square's new value is the best, over its moves, of the reward for the move plus gamma times the value of where it lands. Values spread out from the goal one square per sweep. Q-learning learns the same numbers without knowing the rules, by trying moves (see the Reinforcement Learning examples).",
    prerequisites: ["Nested lists (a grid)", "Nested loops"],
    watch: [
      "In the Picture tab, new being filled from the cells of V outlined in blue: a square looks at its four neighbours.",
      "Each sweep, the values reach one square further from the goal.",
      "Values fall by a factor of gamma (0.9) per step away from the goal.",
    ],
    complexity: "O(sweeps × squares × moves).",
    invariants: [
      "After sweep k, V is exact for every square within k moves of the goal.",
    ],
    edgeCases: [
      "The goal square itself stays 0: the episode ends there.",
    ],
    exercises: [
      "Add a wall that blocks a square.",
      "Add a -1 trap square and see the values route around it.",
      "Print the best move from each square (the policy).",
    ],
    variants: {
      py: {
        code: lines(
          "ROWS, COLS = 3, 3",
          "GOAL = (0, 2)",
          "GAMMA = 0.9",
          "V = [[0.0] * COLS for _ in range(ROWS)]",
          "for sweep in range(4):",
          "    new = [[0.0] * COLS for _ in range(ROWS)]",
          "    for r in range(ROWS):",
          "        for c in range(COLS):",
          "            if (r, c) == GOAL:",
          "                continue",
          "            best = None",
          "            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:",
          "                nr = min(max(r + dr, 0), ROWS - 1)",
          "                nc = min(max(c + dc, 0), COLS - 1)",
          "                reward = 1.0 if (nr, nc) == GOAL else 0.0",
          "                value = reward + GAMMA * V[nr][nc]",
          "                if best is None or value > best:",
          "                    best = value",
          "            new[r][c] = best",
          "    V = new",
          "for row in V:",
          "    print(\" \".join(f\"{v:.2f}\" for v in row))",
        ),
        output: ["0.90 1.00 0.00", "0.81 0.90 1.00", "0.73 0.81 0.90"],
      },
      js: {
        code: lines(
          "const ROWS = 3;",
          "const COLS = 3;",
          "const GOAL_R = 0;",
          "const GOAL_C = 2;",
          "const GAMMA = 0.9;",
          "let V = [];",
          "for (let r = 0; r < ROWS; r++) V.push(new Array(COLS).fill(0));",
          "for (let sweep = 0; sweep < 4; sweep++) {",
          "  const next = [];",
          "  for (let r = 0; r < ROWS; r++) next.push(new Array(COLS).fill(0));",
          "  for (let r = 0; r < ROWS; r++) {",
          "    for (let c = 0; c < COLS; c++) {",
          "      if (r === GOAL_R && c === GOAL_C) continue;",
          "      let best = null;",
          "      for (const [dr, dc] of [[-1, 0], [1, 0], [0, -1], [0, 1]]) {",
          "        const nr = Math.min(Math.max(r + dr, 0), ROWS - 1);",
          "        const nc = Math.min(Math.max(c + dc, 0), COLS - 1);",
          "        const reward = nr === GOAL_R && nc === GOAL_C ? 1 : 0;",
          "        const value = reward + GAMMA * V[nr][nc];",
          "        if (best === null || value > best) best = value;",
          "      }",
          "      next[r][c] = best;",
          "    }",
          "  }",
          "  V = next;",
          "}",
          "for (const row of V) console.log(row.map(v => v.toFixed(2)).join(\" \"));",
        ),
        output: ["0.90 1.00 0.00", "0.81 0.90 1.00", "0.73 0.81 0.90"],
      },
    },
  },
]
