// The CodeLens learning library: examples to load, step through, change and compare across
// languages. Each example says what it teaches, what to watch while stepping, its
// complexity and invariants where they matter, edge cases to try, and exercises; each
// language variant has the output it prints (library.test.ts runs every variant this
// machine can run and checks that output).
//
// Variants are the same program in each language, written the way that language is
// normally written (a Python swap is `a, b = b, a`; C# sorts with a for loop the same way
// but prints with string.Join), so comparing them teaches the differences that matter.
// C# and C++ run in the desktop app only.
import type { Lang } from './types'
import { SNIPPET_CATEGORIES } from './snippets'

export type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced'

export interface LibraryVariant {
  code: string
  /** What the program prints, line by line, as CodeLens shows it (with `input`, if any). */
  output: string[]
  /** What goes in the Input box (scriptedInput.ts): the lines the program reads, and for
   *  pygame programs the scripted keys and clicks. Loaded with the code. */
  input?: string
}

export interface LibraryExample {
  id: string
  title: string
  group: 'Data Structures' | 'Algorithms' | 'Design Patterns' | 'Functional Programming' | 'Input and Games' | 'React Internals'
  difficulty: Difficulty
  /** What the example teaches, in a few sentences. */
  concept: string
  prerequisites: string[]
  /** What to look at while stepping through it. */
  watch: string[]
  /** Reviewed by hand: CodeLens doesn't infer complexity. */
  complexity?: string
  /** Facts that stay true at every step; checking them is how you know the code is right. */
  invariants?: string[]
  edgeCases?: string[]
  exercises: string[]
  variants: Partial<Record<Lang, LibraryVariant>>
}

export const LANGUAGE_LABELS: Record<Lang, string> = {
  js: 'JavaScript', ts: 'TypeScript', py: 'Python', cs: 'C#', cpp: 'C++', c: 'C', go: 'Go',
}

// The original JavaScript snippets, for examples that only exist in JavaScript.
function snippet(name: string): string {
  for (const category of SNIPPET_CATEGORIES) {
    const found = category.items.find(item => item.name === name)
    if (found) return found.code
  }
  throw new Error(`No snippet named ${name}`)
}

const lines = (...text: string[]) => text.join('\n')

export const LIBRARY: LibraryExample[] = [
  // ── Data structures ────────────────────────────────────────────────────────
  {
    id: 'linked-list',
    title: 'Linked list traversal',
    group: 'Data Structures',
    difficulty: 'Beginner',
    concept: 'A linked list is a chain of small objects, each holding a value and a reference to the next one. There is no index: to reach the third value you start at the head and follow the links. Walking the list with a `current` reference that moves one node at a time is the pattern behind almost every linked-list algorithm.',
    prerequisites: ['Variables and loops', 'Classes or structs'],
    watch: [
      'The heap view: three node objects, each pointing at the next; the last one points at nothing.',
      '`current` moving along the chain: it holds a reference to a node, not a copy of it.',
      'The loop ending when `current` becomes null (None in Python, nullptr in C++).',
    ],
    complexity: 'O(n) time to visit every node; O(1) extra space.',
    invariants: ['`total` is the sum of the nodes before `current`.'],
    edgeCases: ['An empty list: `head` is null, so the loop never runs and the total is 0.', 'A list with one node.'],
    exercises: [
      'Count the nodes instead of adding their values.',
      'Add a fourth node at the front: make it point at the old head, then make it the head.',
      'Find the largest value in the list.',
    ],
    variants: {
      js: {
        code: lines(
          'class Node {',
          '  constructor(value) {',
          '    this.value = value',
          '    this.next = null',
          '  }',
          '}',
          '',
          'const head = new Node(1)',
          'head.next = new Node(2)',
          'head.next.next = new Node(3)',
          '',
          'let current = head',
          'let total = 0',
          'while (current !== null) {',
          '  total += current.value',
          '  current = current.next',
          '}',
          'console.log("total:", total)',
        ),
        output: ['total: 6'],
      },
      ts: {
        code: lines(
          'class ListNode {',
          '  next: ListNode | null = null',
          '  constructor(public value: number) {}',
          '}',
          '',
          'const head = new ListNode(1)',
          'head.next = new ListNode(2)',
          'head.next.next = new ListNode(3)',
          '',
          'let current: ListNode | null = head',
          'let total = 0',
          'while (current !== null) {',
          '  total += current.value',
          '  current = current.next',
          '}',
          'console.log("total:", total)',
        ),
        output: ['total: 6'],
      },
      py: {
        code: lines(
          'class Node:',
          '    def __init__(self, value):',
          '        self.value = value',
          '        self.next = None',
          '',
          'head = Node(1)',
          'head.next = Node(2)',
          'head.next.next = Node(3)',
          '',
          'current = head',
          'total = 0',
          'while current is not None:',
          '    total += current.value',
          '    current = current.next',
          'print("total:", total)',
        ),
        output: ['total: 6'],
      },
      cs: {
        code: lines(
          'var head = new Node(1);',
          'head.Next = new Node(2);',
          'head.Next.Next = new Node(3);',
          '',
          'Node? current = head;',
          'int total = 0;',
          'while (current != null)',
          '{',
          '    total += current.Value;',
          '    current = current.Next;',
          '}',
          'Console.WriteLine($"total: {total}");',
          '',
          'class Node',
          '{',
          '    public int Value;',
          '    public Node? Next;',
          '    public Node(int value) { Value = value; }',
          '}',
        ),
        output: ['total: 6'],
      },
      cpp: {
        code: lines(
          '#include <iostream>',
          '',
          'struct Node {',
          '    int value;',
          '    Node* next;',
          '};',
          '',
          'int main() {',
          '    Node* head = new Node{1, nullptr};',
          '    head->next = new Node{2, nullptr};',
          '    head->next->next = new Node{3, nullptr};',
          '',
          '    Node* current = head;',
          '    int total = 0;',
          '    while (current != nullptr) {',
          '        total += current->value;',
          '        current = current->next;',
          '    }',
          '    std::cout << "total: " << total << std::endl;',
          '    return 0;',
          '}',
        ),
        output: ['total: 6'],
      },
    },
  },
  {
    id: 'balanced-brackets',
    title: 'Stack: balanced brackets',
    group: 'Data Structures',
    difficulty: 'Beginner',
    concept: 'A stack gives back items in the reverse order they went in: last in, first out. That is exactly what matching brackets need, because the most recently opened bracket must be the first one closed. Push each opening bracket; on a closing bracket, pop and check that it is the matching opener.',
    prerequisites: ['Loops over a string', 'Arrays or lists'],
    watch: [
      'The stack growing on each opening bracket and shrinking on each closing one.',
      'The early `return false` in the second call, the moment a closer meets the wrong opener.',
      'The final check: the text is balanced only if the stack is empty at the end.',
    ],
    complexity: 'O(n) time; up to O(n) space for the stack.',
    invariants: ['The stack holds the brackets opened so far that are not yet closed, innermost on top.'],
    edgeCases: ['An empty string (balanced).', 'Only openers: `"((("` (the stack is not empty at the end).', 'A closer first: `")("` (the stack is empty when it is popped).'],
    exercises: ['Ignore every character that is not a bracket, so `"f(a[1])"` works.', 'Return the position of the first unmatched bracket instead of true/false.'],
    variants: {
      js: {
        code: lines(
          'function isBalanced(text) {',
          '  const pairs = { ")": "(", "]": "[", "}": "{" }',
          '  const stack = []',
          '  for (const ch of text) {',
          '    if (ch === "(" || ch === "[" || ch === "{") {',
          '      stack.push(ch)',
          '    } else if (ch in pairs) {',
          '      if (stack.length === 0 || stack.pop() !== pairs[ch]) return false',
          '    }',
          '  }',
          '  return stack.length === 0',
          '}',
          '',
          'console.log(isBalanced("{[()]}"))',
          'console.log(isBalanced("([)]"))',
        ),
        output: ['true', 'false'],
      },
      py: {
        code: lines(
          'def is_balanced(text):',
          '    pairs = {")": "(", "]": "[", "}": "{"}',
          '    stack = []',
          '    for ch in text:',
          '        if ch in "([{":',
          '            stack.append(ch)',
          '        elif ch in pairs:',
          '            if not stack or stack.pop() != pairs[ch]:',
          '                return False',
          '    return not stack',
          '',
          'print(is_balanced("{[()]}"))',
          'print(is_balanced("([)]"))',
        ),
        output: ['True', 'False'],
      },
      cs: {
        code: lines(
          'Console.WriteLine(IsBalanced("{[()]}"));',
          'Console.WriteLine(IsBalanced("([)]"));',
          '',
          'bool IsBalanced(string text)',
          '{',
          '    var pairs = new Dictionary<char, char> { [\')\'] = \'(\', [\']\'] = \'[\', [\'}\'] = \'{\' };',
          '    var stack = new Stack<char>();',
          '    foreach (var ch in text)',
          '    {',
          '        if (ch == \'(\' || ch == \'[\' || ch == \'{\')',
          '        {',
          '            stack.Push(ch);',
          '        }',
          '        else if (pairs.ContainsKey(ch))',
          '        {',
          '            if (stack.Count == 0 || stack.Pop() != pairs[ch]) return false;',
          '        }',
          '    }',
          '    return stack.Count == 0;',
          '}',
        ),
        output: ['True', 'False'],
      },
    },
  },
  {
    id: 'bst',
    title: 'Binary search tree',
    group: 'Data Structures',
    difficulty: 'Intermediate',
    concept: 'In a binary search tree every node keeps smaller values in its left subtree and larger ones in its right. Inserting walks down from the root, going left or right at each node, until it finds an empty spot. Visiting left subtree, node, right subtree (in-order) then reads the values back sorted.',
    prerequisites: ['Recursion', 'Linked list traversal'],
    watch: [
      'The recursive `insert` calls stacking up as a value walks down the tree, then returning.',
      'The heap view: the tree taking shape one node at a time.',
      'In-order traversal pushing values in sorted order.',
    ],
    complexity: 'Insert and search: O(height): O(log n) while the tree stays balanced, O(n) if values arrive already sorted.',
    invariants: ['For every node: everything in its left subtree is smaller, everything in its right subtree is larger or equal.'],
    edgeCases: ['Inserting values in sorted order (the tree becomes a linked list).', 'Inserting a duplicate.'],
    exercises: ['Write `contains(node, value)` without recursion.', 'Insert 1, 2, 3, 4, 5 and look at the shape of the tree.', 'Compute the height of the tree.'],
    variants: {
      js: {
        code: lines(
          'class TreeNode {',
          '  constructor(value) {',
          '    this.value = value',
          '    this.left = null',
          '    this.right = null',
          '  }',
          '}',
          '',
          'function insert(node, value) {',
          '  if (node === null) return new TreeNode(value)',
          '  if (value < node.value) node.left = insert(node.left, value)',
          '  else node.right = insert(node.right, value)',
          '  return node',
          '}',
          '',
          'function inOrder(node, out) {',
          '  if (node === null) return',
          '  inOrder(node.left, out)',
          '  out.push(node.value)',
          '  inOrder(node.right, out)',
          '}',
          '',
          'let root = null',
          'for (const value of [10, 5, 15, 2, 12]) {',
          '  root = insert(root, value)',
          '}',
          'const sorted = []',
          'inOrder(root, sorted)',
          'console.log(sorted.join(" "))',
        ),
        output: ['2 5 10 12 15'],
      },
      py: {
        code: lines(
          'class TreeNode:',
          '    def __init__(self, value):',
          '        self.value = value',
          '        self.left = None',
          '        self.right = None',
          '',
          'def insert(node, value):',
          '    if node is None:',
          '        return TreeNode(value)',
          '    if value < node.value:',
          '        node.left = insert(node.left, value)',
          '    else:',
          '        node.right = insert(node.right, value)',
          '    return node',
          '',
          'def in_order(node, out):',
          '    if node is None:',
          '        return',
          '    in_order(node.left, out)',
          '    out.append(node.value)',
          '    in_order(node.right, out)',
          '',
          'root = None',
          'for value in [10, 5, 15, 2, 12]:',
          '    root = insert(root, value)',
          'result = []',
          'in_order(root, result)',
          'print(" ".join(str(v) for v in result))',
        ),
        output: ['2 5 10 12 15'],
      },
      cs: {
        code: lines(
          'TreeNode? root = null;',
          'foreach (var value in new[] { 10, 5, 15, 2, 12 })',
          '{',
          '    root = Insert(root, value);',
          '}',
          'var sorted = new List<int>();',
          'InOrder(root, sorted);',
          'Console.WriteLine(string.Join(" ", sorted));',
          '',
          'TreeNode Insert(TreeNode? node, int value)',
          '{',
          '    if (node == null) return new TreeNode(value);',
          '    if (value < node.Value) node.Left = Insert(node.Left, value);',
          '    else node.Right = Insert(node.Right, value);',
          '    return node;',
          '}',
          '',
          'void InOrder(TreeNode? node, List<int> output)',
          '{',
          '    if (node == null) return;',
          '    InOrder(node.Left, output);',
          '    output.Add(node.Value);',
          '    InOrder(node.Right, output);',
          '}',
          '',
          'class TreeNode',
          '{',
          '    public int Value;',
          '    public TreeNode? Left;',
          '    public TreeNode? Right;',
          '    public TreeNode(int value) { Value = value; }',
          '}',
        ),
        output: ['2 5 10 12 15'],
      },
      cpp: {
        code: lines(
          '#include <iostream>',
          '#include <vector>',
          '',
          'struct TreeNode {',
          '    int value;',
          '    TreeNode* left;',
          '    TreeNode* right;',
          '};',
          '',
          'TreeNode* insert(TreeNode* node, int value) {',
          '    if (node == nullptr) {',
          '        return new TreeNode{value, nullptr, nullptr};',
          '    }',
          '    if (value < node->value) {',
          '        node->left = insert(node->left, value);',
          '    } else {',
          '        node->right = insert(node->right, value);',
          '    }',
          '    return node;',
          '}',
          '',
          'void inOrder(TreeNode* node, std::vector<int>& out) {',
          '    if (node == nullptr) {',
          '        return;',
          '    }',
          '    inOrder(node->left, out);',
          '    out.push_back(node->value);',
          '    inOrder(node->right, out);',
          '}',
          '',
          'int main() {',
          '    TreeNode* root = nullptr;',
          '    int values[] = {10, 5, 15, 2, 12};',
          '    for (int value : values) {',
          '        root = insert(root, value);',
          '    }',
          '    std::vector<int> sorted;',
          '    inOrder(root, sorted);',
          '    for (size_t i = 0; i < sorted.size(); i++) {',
          '        std::cout << (i > 0 ? " " : "") << sorted[i];',
          '    }',
          '    std::cout << std::endl;',
          '    return 0;',
          '}',
        ),
        output: ['2 5 10 12 15'],
      },
    },
  },

  // ── Algorithms ─────────────────────────────────────────────────────────────
  {
    id: 'bubble-sort',
    title: 'Bubble sort',
    group: 'Algorithms',
    difficulty: 'Beginner',
    concept: 'Bubble sort repeatedly walks the list comparing neighbours and swapping any pair that is out of order. After each pass the largest remaining value has "bubbled" to the end, so each pass can stop one place earlier. It is slow, but every step is visible, which makes it the clearest first look at nested loops and in-place swaps.',
    prerequisites: ['Arrays or lists', 'Nested loops'],
    watch: [
      'The swap: three assignments through a temporary variable (Python swaps in one line).',
      'The end of the array filling up with the largest values after each pass.',
      'The inner loop getting one step shorter each pass (`n - 1 - i`).',
    ],
    complexity: 'O(n²) comparisons in the worst and average case; O(1) extra space (it sorts in place).',
    invariants: ['After pass i, the last i + 1 positions hold the largest values in their final order.'],
    edgeCases: ['An already sorted array (still O(n²) here; see the exercise).', 'Equal values (they never swap, so the sort is stable).'],
    exercises: [
      'Stop early: track whether a pass made any swap, and stop when one did not.',
      'Sort in descending order.',
      'Count the swaps and print the count.',
    ],
    variants: {
      js: {
        code: lines(
          'function bubbleSort(items) {',
          '  const n = items.length',
          '  for (let i = 0; i < n - 1; i++) {',
          '    for (let j = 0; j < n - 1 - i; j++) {',
          '      if (items[j] > items[j + 1]) {',
          '        const temp = items[j]',
          '        items[j] = items[j + 1]',
          '        items[j + 1] = temp',
          '      }',
          '    }',
          '  }',
          '  return items',
          '}',
          '',
          'const numbers = [5, 3, 8, 4, 2]',
          'bubbleSort(numbers)',
          'console.log(numbers.join(" "))',
        ),
        output: ['2 3 4 5 8'],
      },
      ts: {
        code: lines(
          'function bubbleSort(items: number[]): number[] {',
          '  const n = items.length',
          '  for (let i = 0; i < n - 1; i++) {',
          '    for (let j = 0; j < n - 1 - i; j++) {',
          '      if (items[j] > items[j + 1]) {',
          '        const temp = items[j]',
          '        items[j] = items[j + 1]',
          '        items[j + 1] = temp',
          '      }',
          '    }',
          '  }',
          '  return items',
          '}',
          '',
          'const numbers: number[] = [5, 3, 8, 4, 2]',
          'bubbleSort(numbers)',
          'console.log(numbers.join(" "))',
        ),
        output: ['2 3 4 5 8'],
      },
      py: {
        code: lines(
          'def bubble_sort(items):',
          '    n = len(items)',
          '    for i in range(n - 1):',
          '        for j in range(n - 1 - i):',
          '            if items[j] > items[j + 1]:',
          '                items[j], items[j + 1] = items[j + 1], items[j]',
          '    return items',
          '',
          'numbers = [5, 3, 8, 4, 2]',
          'bubble_sort(numbers)',
          'print(" ".join(str(n) for n in numbers))',
        ),
        output: ['2 3 4 5 8'],
      },
      cs: {
        code: lines(
          'int[] numbers = { 5, 3, 8, 4, 2 };',
          'BubbleSort(numbers);',
          'Console.WriteLine(string.Join(" ", numbers));',
          '',
          'void BubbleSort(int[] items)',
          '{',
          '    int n = items.Length;',
          '    for (int i = 0; i < n - 1; i++)',
          '    {',
          '        for (int j = 0; j < n - 1 - i; j++)',
          '        {',
          '            if (items[j] > items[j + 1])',
          '            {',
          '                int temp = items[j];',
          '                items[j] = items[j + 1];',
          '                items[j + 1] = temp;',
          '            }',
          '        }',
          '    }',
          '}',
        ),
        output: ['2 3 4 5 8'],
      },
      cpp: {
        code: lines(
          '#include <iostream>',
          '#include <vector>',
          '',
          'void bubbleSort(std::vector<int>& items) {',
          '    int n = items.size();',
          '    for (int i = 0; i < n - 1; i++) {',
          '        for (int j = 0; j < n - 1 - i; j++) {',
          '            if (items[j] > items[j + 1]) {',
          '                int temp = items[j];',
          '                items[j] = items[j + 1];',
          '                items[j + 1] = temp;',
          '            }',
          '        }',
          '    }',
          '}',
          '',
          'int main() {',
          '    std::vector<int> numbers = {5, 3, 8, 4, 2};',
          '    bubbleSort(numbers);',
          '    for (size_t i = 0; i < numbers.size(); i++) {',
          '        std::cout << (i > 0 ? " " : "") << numbers[i];',
          '    }',
          '    std::cout << std::endl;',
          '    return 0;',
          '}',
        ),
        output: ['2 3 4 5 8'],
      },
    },
  },
  {
    id: 'binary-search',
    title: 'Binary search',
    group: 'Algorithms',
    difficulty: 'Beginner',
    concept: 'Binary search finds a value in a sorted array by checking the middle and throwing away the half that cannot contain it. Each step halves the range, so even a million items take about twenty steps. It only works because the array is sorted.',
    prerequisites: ['Arrays', 'while loops', 'Integer division'],
    watch: [
      '`low` and `high` closing in on the target from both sides.',
      '`mid` being recomputed each pass, and the comparison deciding which half to keep.',
      'The second search: the range becomes empty (`low > high`) and the function returns -1.',
    ],
    complexity: 'O(log n) time; O(1) space.',
    invariants: ['If the target is in the array, it is somewhere between `low` and `high` (inclusive).'],
    edgeCases: ['An empty array (`high` starts at -1).', 'The target is the first or last item.', 'The target is smaller than everything.'],
    exercises: ['Count how many passes each search takes.', 'Return where the target would be inserted when it is missing.', 'Write it recursively.'],
    variants: {
      js: {
        code: lines(
          'function binarySearch(items, target) {',
          '  let low = 0',
          '  let high = items.length - 1',
          '  while (low <= high) {',
          '    const mid = Math.floor((low + high) / 2)',
          '    if (items[mid] === target) return mid',
          '    if (items[mid] < target) low = mid + 1',
          '    else high = mid - 1',
          '  }',
          '  return -1',
          '}',
          '',
          'const sorted = [2, 5, 8, 12, 16, 23, 38]',
          'console.log(binarySearch(sorted, 23))',
          'console.log(binarySearch(sorted, 7))',
        ),
        output: ['5', '-1'],
      },
      py: {
        code: lines(
          'def binary_search(items, target):',
          '    low = 0',
          '    high = len(items) - 1',
          '    while low <= high:',
          '        mid = (low + high) // 2',
          '        if items[mid] == target:',
          '            return mid',
          '        if items[mid] < target:',
          '            low = mid + 1',
          '        else:',
          '            high = mid - 1',
          '    return -1',
          '',
          'sorted_items = [2, 5, 8, 12, 16, 23, 38]',
          'print(binary_search(sorted_items, 23))',
          'print(binary_search(sorted_items, 7))',
        ),
        output: ['5', '-1'],
      },
      cs: {
        code: lines(
          'int[] sorted = { 2, 5, 8, 12, 16, 23, 38 };',
          'Console.WriteLine(BinarySearch(sorted, 23));',
          'Console.WriteLine(BinarySearch(sorted, 7));',
          '',
          'int BinarySearch(int[] items, int target)',
          '{',
          '    int low = 0;',
          '    int high = items.Length - 1;',
          '    while (low <= high)',
          '    {',
          '        int mid = (low + high) / 2;',
          '        if (items[mid] == target) return mid;',
          '        if (items[mid] < target) low = mid + 1;',
          '        else high = mid - 1;',
          '    }',
          '    return -1;',
          '}',
        ),
        output: ['5', '-1'],
      },
      cpp: {
        code: lines(
          '#include <iostream>',
          '#include <vector>',
          '',
          'int binarySearch(const std::vector<int>& items, int target) {',
          '    int low = 0;',
          '    int high = items.size() - 1;',
          '    while (low <= high) {',
          '        int mid = (low + high) / 2;',
          '        if (items[mid] == target) {',
          '            return mid;',
          '        }',
          '        if (items[mid] < target) {',
          '            low = mid + 1;',
          '        } else {',
          '            high = mid - 1;',
          '        }',
          '    }',
          '    return -1;',
          '}',
          '',
          'int main() {',
          '    std::vector<int> sorted = {2, 5, 8, 12, 16, 23, 38};',
          '    std::cout << binarySearch(sorted, 23) << std::endl;',
          '    std::cout << binarySearch(sorted, 7) << std::endl;',
          '    return 0;',
          '}',
        ),
        output: ['5', '-1'],
      },
    },
  },
  {
    id: 'fib-recursion',
    title: 'Fibonacci with recursion',
    group: 'Algorithms',
    difficulty: 'Beginner',
    concept: 'A recursive function calls itself on a smaller problem until it reaches a base case it can answer directly. Each call gets its own frame on the call stack with its own `n`. Plain recursive Fibonacci recomputes the same values again and again, which is why it is slow, and why the memoized version exists.',
    prerequisites: ['Functions and return values'],
    watch: [
      'The call stack growing to depth n, then shrinking as calls return.',
      'Each frame having its own `n`: the same name, a different variable in every call.',
      'The same `fib(2)` being computed more than once.',
    ],
    complexity: 'O(2ⁿ) time without memoization (each call makes two more); O(n) stack depth.',
    edgeCases: ['n = 0 and n = 1 (the base cases).', 'A large n: count the calls and watch the step limit.'],
    exercises: ['Count how many times `fib` is called for n = 5.', 'Write an iterative version with a loop and two variables.'],
    variants: {
      js: {
        code: lines(
          'function fib(n) {',
          '  if (n <= 1) return n',
          '  return fib(n - 1) + fib(n - 2)',
          '}',
          '',
          'console.log(fib(5))',
        ),
        output: ['5'],
      },
      py: {
        code: lines(
          'def fib(n):',
          '    if n <= 1:',
          '        return n',
          '    return fib(n - 1) + fib(n - 2)',
          '',
          'print(fib(5))',
        ),
        output: ['5'],
      },
      cs: {
        code: lines(
          'Console.WriteLine(Fib(5));',
          '',
          'int Fib(int n)',
          '{',
          '    if (n <= 1) return n;',
          '    return Fib(n - 1) + Fib(n - 2);',
          '}',
        ),
        output: ['5'],
      },
      cpp: {
        code: lines(
          '#include <iostream>',
          '',
          'int fib(int n) {',
          '    if (n <= 1) {',
          '        return n;',
          '    }',
          '    return fib(n - 1) + fib(n - 2);',
          '}',
          '',
          'int main() {',
          '    std::cout << fib(5) << std::endl;',
          '    return 0;',
          '}',
        ),
        output: ['5'],
      },
    },
  },
  {
    id: 'fib-memo',
    title: 'Fibonacci with memoization',
    group: 'Algorithms',
    difficulty: 'Intermediate',
    concept: 'Memoization stores each result the first time it is computed and looks it up after that. The recursion still has to reach a base case before anything is stored, so the memo starts empty; once calls start returning it fills up, and the repeated calls that made plain recursion slow become lookups.',
    prerequisites: ['Fibonacci with recursion', 'Maps or dictionaries'],
    watch: [
      'The memo staying empty until the recursion bottoms out: that is expected.',
      'The memo filling in as calls return, smallest n first.',
      'Later calls returning straight from the memo instead of recursing.',
    ],
    complexity: 'O(n) time and O(n) space: each value is computed once.',
    invariants: ['Every entry memo[k] holds fib(k).'],
    exercises: ['Compare the number of steps with the plain recursive version for the same n.', 'Fill the memo bottom-up with a loop instead (dynamic programming).'],
    variants: {
      js: {
        code: lines(
          'function fib(n, memo) {',
          '  if (n <= 1) return n',
          '  if (memo.has(n)) return memo.get(n)',
          '  const result = fib(n - 1, memo) + fib(n - 2, memo)',
          '  memo.set(n, result)',
          '  return result',
          '}',
          '',
          'const memo = new Map()',
          'console.log(fib(8, memo))',
        ),
        output: ['21'],
      },
      py: {
        code: lines(
          'def fib(n, memo):',
          '    if n <= 1:',
          '        return n',
          '    if n in memo:',
          '        return memo[n]',
          '    result = fib(n - 1, memo) + fib(n - 2, memo)',
          '    memo[n] = result',
          '    return result',
          '',
          'memo = {}',
          'print(fib(8, memo))',
        ),
        output: ['21'],
      },
      cs: {
        code: lines(
          'var memo = new Dictionary<int, long>();',
          'Console.WriteLine(Fib(8, memo));',
          '',
          'long Fib(int n, Dictionary<int, long> memo)',
          '{',
          '    if (n <= 1) return n;',
          '    if (memo.TryGetValue(n, out var known)) return known;',
          '    long result = Fib(n - 1, memo) + Fib(n - 2, memo);',
          '    memo[n] = result;',
          '    return result;',
          '}',
        ),
        output: ['21'],
      },
    },
  },

  // ── Design patterns ────────────────────────────────────────────────────────
  {
    id: 'factory',
    title: 'Factory',
    group: 'Design Patterns',
    difficulty: 'Intermediate',
    concept: 'A factory is one function that decides which class to create, so the code that uses the objects never names the classes. The callers only rely on what the objects can do (here, `speak`). Adding a new kind of object then changes the factory, not every caller.',
    prerequisites: ['Classes', 'Interfaces (C#, TypeScript) or duck typing (JavaScript, Python)'],
    watch: [
      'The factory call choosing a branch from the string it is given.',
      'Two different kinds of object in the heap, used through the same `speak` call.',
    ],
    edgeCases: ['An unknown kind: the factory throws instead of returning null, so the mistake surfaces where it happened.'],
    exercises: ['Add a Cow.', 'Replace the if chain with a map from name to class.', 'Discuss: when is a plain `new Dog()` better than a factory?'],
    variants: {
      js: {
        code: lines(
          'class Dog { speak() { return "Woof" } }',
          'class Cat { speak() { return "Meow" } }',
          '',
          'function createAnimal(kind) {',
          '  if (kind === "dog") return new Dog()',
          '  if (kind === "cat") return new Cat()',
          '  throw new Error("Unknown animal: " + kind)',
          '}',
          '',
          'const pets = [createAnimal("dog"), createAnimal("cat")]',
          'for (const pet of pets) {',
          '  console.log(pet.speak())',
          '}',
        ),
        output: ['Woof', 'Meow'],
      },
      ts: {
        code: lines(
          'interface Animal {',
          '  speak(): string',
          '}',
          'class Dog implements Animal { speak() { return "Woof" } }',
          'class Cat implements Animal { speak() { return "Meow" } }',
          '',
          'function createAnimal(kind: "dog" | "cat"): Animal {',
          '  if (kind === "dog") return new Dog()',
          '  return new Cat()',
          '}',
          '',
          'const pets: Animal[] = [createAnimal("dog"), createAnimal("cat")]',
          'for (const pet of pets) {',
          '  console.log(pet.speak())',
          '}',
        ),
        output: ['Woof', 'Meow'],
      },
      py: {
        code: lines(
          'class Dog:',
          '    def speak(self):',
          '        return "Woof"',
          '',
          'class Cat:',
          '    def speak(self):',
          '        return "Meow"',
          '',
          'def create_animal(kind):',
          '    if kind == "dog":',
          '        return Dog()',
          '    if kind == "cat":',
          '        return Cat()',
          '    raise ValueError("Unknown animal: " + kind)',
          '',
          'pets = [create_animal("dog"), create_animal("cat")]',
          'for pet in pets:',
          '    print(pet.speak())',
        ),
        output: ['Woof', 'Meow'],
      },
      cs: {
        code: lines(
          'var pets = new List<IAnimal> { CreateAnimal("dog"), CreateAnimal("cat") };',
          'foreach (var pet in pets)',
          '{',
          '    Console.WriteLine(pet.Speak());',
          '}',
          '',
          'IAnimal CreateAnimal(string kind) => kind switch',
          '{',
          '    "dog" => new Dog(),',
          '    "cat" => new Cat(),',
          '    _ => throw new ArgumentException($"Unknown animal: {kind}"),',
          '};',
          '',
          'interface IAnimal { string Speak(); }',
          'class Dog : IAnimal { public string Speak() => "Woof"; }',
          'class Cat : IAnimal { public string Speak() => "Meow"; }',
        ),
        output: ['Woof', 'Meow'],
      },
    },
  },
  {
    id: 'singleton',
    title: 'Singleton',
    group: 'Design Patterns',
    difficulty: 'Intermediate',
    concept: 'A singleton makes sure only one instance of something exists and hands everyone that same instance. Watch the two variables: they hold references to one object, so a change made through one is seen through the other. Singletons are easy to overuse; they are global state in disguise, which makes code harder to test.',
    prerequisites: ['Objects and references', 'Closures (JavaScript) or static members (C#, Python)'],
    watch: [
      'Both variables pointing at the same object number in the heap.',
      'The instance being created on the first request only.',
    ],
    exercises: ['Print whether the two variables refer to the same object.', 'Discuss: how would you test code that uses this singleton? What would dependency injection change?'],
    variants: {
      js: {
        code: lines(
          'const Database = (function () {',
          '  let instance = null',
          '  return {',
          '    getInstance: function () {',
          '      if (instance === null) {',
          '        instance = { rows: [] }',
          '      }',
          '      return instance',
          '    }',
          '  }',
          '})()',
          '',
          'const first = Database.getInstance()',
          'const second = Database.getInstance()',
          'first.rows.push("user_1")',
          'console.log(second.rows.length)',
          'console.log(first === second)',
        ),
        output: ['1', 'true'],
      },
      py: {
        code: lines(
          'class Database:',
          '    _instance = None',
          '',
          '    @classmethod',
          '    def get_instance(cls):',
          '        if cls._instance is None:',
          '            cls._instance = Database()',
          '            cls._instance.rows = []',
          '        return cls._instance',
          '',
          'first = Database.get_instance()',
          'second = Database.get_instance()',
          'first.rows.append("user_1")',
          'print(len(second.rows))',
          'print(first is second)',
        ),
        output: ['1', 'True'],
      },
      cs: {
        code: lines(
          'var first = Database.Instance;',
          'var second = Database.Instance;',
          'first.Rows.Add("user_1");',
          'Console.WriteLine(second.Rows.Count);',
          'Console.WriteLine(ReferenceEquals(first, second));',
          '',
          'class Database',
          '{',
          '    private static Database? _instance;',
          '    public static Database Instance => _instance ??= new Database();',
          '    public List<string> Rows { get; } = new();',
          '    private Database() { }',
          '}',
        ),
        output: ['1', 'True'],
      },
    },
  },

  // ── Functional programming ─────────────────────────────────────────────────
  {
    id: 'closures',
    title: 'Closures and currying',
    group: 'Functional Programming',
    difficulty: 'Intermediate',
    concept: 'A closure is a function that keeps the variables it was created next to. `multiply(2)` returns a new function that still sees `x = 2` after `multiply` has returned, so `double` and `triple` are two functions sharing code but remembering different values.',
    prerequisites: ['Functions as values'],
    watch: ['The returned function being stored in `double` and `triple`.', 'Calling `double(5)`: its frame can read `x` from the call that created it.'],
    exercises: ['Write `adder(n)` that returns a function adding n.', 'Make a counter: a function that returns a new number each time it is called.'],
    variants: {
      js: { code: snippet('Closures & Currying') + '\nconsole.log(res1, res2)', output: ['10 15'] },
      py: {
        code: lines(
          'def multiply(x):',
          '    def by(y):',
          '        return x * y',
          '    return by',
          '',
          'double = multiply(2)',
          'triple = multiply(3)',
          'print(double(5), triple(5))',
        ),
        output: ['10 15'],
      },
    },
  },
  {
    id: 'map-filter-reduce',
    title: 'Map, filter, reduce',
    group: 'Functional Programming',
    difficulty: 'Beginner',
    concept: 'Instead of one loop doing everything, the work is split into steps: keep the even numbers (filter), scale each one (map), add them up (reduce). Each step takes a small function. Python writes the same idea as a comprehension; C# as a LINQ query, which does nothing until something asks for its results.',
    prerequisites: ['Arrays or lists', 'Functions as values (lambdas)'],
    watch: [
      'The callbacks running once per element.',
      'C#: the query variable holds a LINQ query, not numbers; `Sum()` is what runs it.',
    ],
    complexity: 'O(n): each step passes over the items once.',
    exercises: ['Also compute the largest even number.', 'Rewrite it as one plain loop and compare.'],
    variants: {
      js: {
        code: lines(
          'const nums = [1, 2, 3, 4, 5]',
          '',
          'const total = nums',
          '  .filter(n => n % 2 === 0)',
          '  .map(n => n * 10)',
          '  .reduce((sum, n) => sum + n, 0)',
          '',
          'console.log(total)',
        ),
        output: ['60'],
      },
      ts: {
        code: lines(
          'const nums: number[] = [1, 2, 3, 4, 5]',
          '',
          'const total: number = nums',
          '  .filter((n: number) => n % 2 === 0)',
          '  .map((n: number) => n * 10)',
          '  .reduce((sum: number, n: number) => sum + n, 0)',
          '',
          'console.log(total)',
        ),
        output: ['60'],
      },
      py: {
        code: lines(
          'nums = [1, 2, 3, 4, 5]',
          '',
          'scaled = [n * 10 for n in nums if n % 2 == 0]',
          'total = sum(scaled)',
          '',
          'print(total)',
        ),
        output: ['60'],
      },
      cs: {
        code: lines(
          'int[] nums = { 1, 2, 3, 4, 5 };',
          '',
          'var scaled = nums',
          '    .Where(n => n % 2 == 0)',
          '    .Select(n => n * 10);',
          'int total = scaled.Sum();',
          '',
          'Console.WriteLine(total);',
        ),
        output: ['60'],
      },
    },
  },

  // ── Input and games: programs that read the Input box ──────────────────────
  {
    id: 'asking-questions',
    title: 'Asking questions: reading input',
    group: 'Input and Games',
    difficulty: 'Beginner',
    concept: 'A program that asks questions waits for an answer at each read. CodeLens records the whole run before you step through it, so the answers are written in advance, in the Input box, one per line: every read takes the next line. The Input box loaded with this example holds the answers Ada, 3, 10, 20 and 12. Each language reads a line its own way: input() in Python, prompt() in JavaScript, Console.ReadLine() in C#, std::getline and std::cin >> in C++, scanf in C.',
    prerequisites: [],
    watch: [
      'The Input box under the editor: each line is one answer.',
      'The step after each read: its explanation says what was read, and the new variable holds it.',
      'In Python, JavaScript and C#, the Output shows each answer after its question, the way a terminal shows what was typed.',
      'In C and C++, the program reads the Input box as a file (like `program < input.txt`), so the answers don\'t appear in the Output.',
    ],
    edgeCases: [
      'Delete the last line of the Input box: the program asks for an answer that isn\'t there. Python stops with EOFError, JavaScript\'s prompt() returns null, C#\'s Console.ReadLine() returns null, and C++\'s std::cin >> fails and leaves the variable unchanged.',
      'Type "three" instead of 3: converting it to a number fails, each language in its own way.',
    ],
    exercises: [
      'Ask for the numbers on one line, separated by spaces, and split it.',
      'Ask again when an answer isn\'t a number (and add a wrong answer to the Input box to test it).',
    ],
    variants: {
      py: {
        code: lines(
          'name = input("Name? ")',
          'count = int(input("How many numbers? "))',
          'total = 0',
          'for i in range(count):',
          '    total += int(input(f"Number {i + 1}? "))',
          'print(f"{name}, the total is {total}")',
        ),
        input: 'Ada\n3\n10\n20\n12\n',
        output: ['Name? Ada', 'How many numbers? 3', 'Number 1? 10', 'Number 2? 20', 'Number 3? 12', 'Ada, the total is 42'],
      },
      js: {
        code: lines(
          "const name = prompt('Name? ')",
          "const count = Number(prompt('How many numbers? '))",
          'let total = 0',
          'for (let i = 0; i < count; i++) {',
          '  total += Number(prompt(`Number ${i + 1}? `))',
          '}',
          'console.log(`${name}, the total is ${total}`)',
        ),
        input: 'Ada\n3\n10\n20\n12\n',
        output: ['Name? Ada', 'How many numbers? 3', 'Number 1? 10', 'Number 2? 20', 'Number 3? 12', 'Ada, the total is 42'],
      },
      cs: {
        code: lines(
          'Console.Write("Name? ");',
          'var name = Console.ReadLine();',
          'Console.Write("How many numbers? ");',
          'var count = int.Parse(Console.ReadLine());',
          'var total = 0;',
          'for (int i = 0; i < count; i++)',
          '{',
          '    Console.Write($"Number {i + 1}? ");',
          '    total += int.Parse(Console.ReadLine());',
          '}',
          'Console.WriteLine($"{name}, the total is {total}");',
        ),
        input: 'Ada\n3\n10\n20\n12\n',
        output: ['Name? Ada', 'How many numbers? 3', 'Number 1? 10', 'Number 2? 20', 'Number 3? 12', 'Ada, the total is 42'],
      },
      cpp: {
        code: lines(
          '#include <iostream>',
          '#include <string>',
          'int main() {',
          '    std::string name;',
          '    std::cout << "Name?" << std::endl;',
          '    std::getline(std::cin, name);',
          '    int count;',
          '    std::cout << "How many numbers?" << std::endl;',
          '    std::cin >> count;',
          '    int total = 0;',
          '    for (int i = 0; i < count; i++) {',
          '        int number;',
          '        std::cout << "Number " << i + 1 << "?" << std::endl;',
          '        std::cin >> number;',
          '        total += number;',
          '    }',
          '    std::cout << name << ", the total is " << total << std::endl;',
          '}',
        ),
        input: 'Ada\n3\n10\n20\n12\n',
        output: ['Name?', 'How many numbers?', 'Number 1?', 'Number 2?', 'Number 3?', 'Ada, the total is 42'],
      },
      c: {
        code: lines(
          '#include <stdio.h>',
          'int main(void) {',
          '    char name[50];',
          '    int count, total = 0;',
          '    printf("Name?\\n");',
          '    scanf("%49s", name);',
          '    printf("How many numbers?\\n");',
          '    scanf("%d", &count);',
          '    for (int i = 0; i < count; i++) {',
          '        int number;',
          '        printf("Number %d?\\n", i + 1);',
          '        scanf("%d", &number);',
          '        total += number;',
          '    }',
          '    printf("%s, the total is %d\\n", name, total);',
          '    return 0;',
          '}',
        ),
        input: 'Ada\n3\n10\n20\n12\n',
        output: ['Name?', 'How many numbers?', 'Number 1?', 'Number 2?', 'Number 3?', 'Ada, the total is 42'],
      },
    },
  },
  {
    id: 'until-the-input-ends',
    title: 'Reading until the input ends',
    group: 'Input and Games',
    difficulty: 'Beginner',
    concept: 'A program doesn\'t have to know in advance how much input there is. It can read until the input ends: the end of a file, or Ctrl+Z / Ctrl+D at a terminal. Each language signals the end differently, and this loop is the same idea in each: read, stop at the end, otherwise use what was read. Here the Input box holds three numbers, so the loop runs three times and the fourth read finds the end.',
    prerequisites: ['Asking questions: reading input'],
    watch: [
      'The loop\'s condition on its last check: the read that finds no more input.',
      'Python: `for line in sys.stdin` stops by itself; JavaScript\'s prompt() and C#\'s ReadLine() return null; C++\'s `std::cin >> number` is false; C\'s scanf returns how many values it read, here 0 or EOF.',
      'Each `line` in Python and C# still ends where the line did: int() and int.Parse() ignore the surrounding whitespace.',
    ],
    edgeCases: [
      'Empty the Input box: the loop never runs, and the count is 0.',
      'Add a blank line between two numbers: Python\'s int("\\n") fails, but C++\'s >> skips blank lines.',
    ],
    exercises: ['Print the largest number as well.', 'Read words instead of numbers and count how often each appears (a dictionary or map).'],
    variants: {
      py: {
        code: lines(
          'import sys',
          '',
          'total = 0',
          'count = 0',
          'for line in sys.stdin:',
          '    total += int(line)',
          '    count += 1',
          'print(f"{count} numbers, total {total}")',
        ),
        input: '5\n8\n13\n',
        output: ['5', '8', '13', '3 numbers, total 26'],
      },
      js: {
        code: lines(
          'let total = 0',
          'let count = 0',
          'let line = prompt()',
          'while (line !== null) {',
          '  total += Number(line)',
          '  count++',
          '  line = prompt()',
          '}',
          'console.log(`${count} numbers, total ${total}`)',
        ),
        input: '5\n8\n13\n',
        output: ['5', '8', '13', '3 numbers, total 26'],
      },
      cs: {
        code: lines(
          'var total = 0;',
          'var count = 0;',
          'string line;',
          'while ((line = Console.ReadLine()) != null)',
          '{',
          '    total += int.Parse(line);',
          '    count++;',
          '}',
          'Console.WriteLine($"{count} numbers, total {total}");',
        ),
        input: '5\n8\n13\n',
        output: ['5', '8', '13', '3 numbers, total 26'],
      },
      cpp: {
        code: lines(
          '#include <iostream>',
          'int main() {',
          '    int total = 0;',
          '    int count = 0;',
          '    int number;',
          '    while (std::cin >> number) {',
          '        total += number;',
          '        count++;',
          '    }',
          '    std::cout << count << " numbers, total " << total << std::endl;',
          '}',
        ),
        input: '5\n8\n13\n',
        output: ['3 numbers, total 26'],
      },
      c: {
        code: lines(
          '#include <stdio.h>',
          'int main(void) {',
          '    int total = 0, count = 0, number;',
          '    while (scanf("%d", &number) == 1) {',
          '        total += number;',
          '        count++;',
          '    }',
          '    printf("%d numbers, total %d\\n", count, total);',
          '    return 0;',
          '}',
        ),
        input: '5\n8\n13\n',
        output: ['3 numbers, total 26'],
      },
    },
  },
  {
    id: 'pygame-scripted',
    title: 'A pygame game on scripted keys',
    group: 'Input and Games',
    difficulty: 'Intermediate',
    concept: 'A game is a loop that runs once per frame: take the events (keys, clicks, the close button), update the game, draw it, show the picture with display.flip(), and wait for the next frame with clock.tick(). CodeLens can\'t give a traced program a live window, so it runs the game on the moves written in the Input box ("@frame 1 keydown right": the → key goes down while frame 1 is being drawn) and keeps every picture the program shows. Step through the trace and the Screen panel shows the window as it was at that step.',
    prerequisites: ['Asking questions: reading input'],
    watch: [
      'The Screen panel: it changes only at display.flip(). Everything drawn before that is off screen.',
      '`pygame.event.get()` on frame 1: it returns the KEYDOWN that the Input box scripted for frame 1.',
      '`keys[pygame.K_RIGHT]` staying true on frames 1, 2 and 3: a key is held from its keydown to its keyup, which is how get_pressed() makes smooth movement.',
      'clock.tick(30) returning 33 without waiting: CodeLens\'s clock is pretend, so every run takes the same steps.',
    ],
    edgeCases: [
      'Remove "@frame 10 quit": CodeLens closes the window one frame after the last event, so the loop still ends.',
      'Script a tap with "@frame 6 key left": it is held for exactly one frame.',
      'Draw the square after display.flip() instead of before: the Screen shows each picture one frame late.',
    ],
    exercises: [
      'Add ↑ and ↓ (K_UP, K_DOWN), and script them in the Input box.',
      'Keep the square inside the window: clamp x between 10 and 230.',
      'Move by speed × time instead of 20 per frame: use the milliseconds clock.tick() returns.',
    ],
    variants: {
      py: {
        code: lines(
          'import pygame',
          '',
          'pygame.init()',
          'screen = pygame.display.set_mode((240, 120))',
          'clock = pygame.time.Clock()',
          'x, y = 30, 60',
          'running = True',
          'while running:',
          '    for event in pygame.event.get():',
          '        if event.type == pygame.QUIT:',
          '            running = False',
          '        elif event.type == pygame.MOUSEBUTTONDOWN:',
          '            x, y = event.pos',
          '    keys = pygame.key.get_pressed()',
          '    if keys[pygame.K_RIGHT]:',
          '        x += 20',
          '    if keys[pygame.K_LEFT]:',
          '        x -= 20',
          '    screen.fill((25, 25, 45))',
          '    pygame.draw.rect(screen, (90, 200, 120), (x - 10, y - 10, 20, 20))',
          '    pygame.display.flip()',
          '    clock.tick(30)',
          '',
          'pygame.quit()',
          'print(f"ended at ({x}, {y}) after {pygame.time.get_ticks()} ms")',
        ),
        input: lines(
          '@# Hold → for frames 1-3, tap ← on frame 6, click on frame 8, close on frame 10.',
          '@frame 1 keydown right',
          '@frame 4 keyup right',
          '@frame 6 key left',
          '@frame 8 click 180 40',
          '@frame 10 quit',
        ) + '\n',
        output: ['ended at (180, 40) after 363 ms'],
      },
    },
  },

  // ── JavaScript only ────────────────────────────────────────────────────────
  {
    id: 'use-state',
    title: 'Simulating React useState',
    group: 'React Internals',
    difficulty: 'Advanced',
    concept: 'React keeps a component\'s state outside the component function, so it survives between renders. This sketch keeps it in a closure: `useState` returns the stored value and a setter that replaces it, and the next render reads the new value.',
    prerequisites: ['Closures and currying'],
    watch: ['`_state` living in the module closure, not in `CounterComponent`.', 'The second render reading the value the setter stored.'],
    exercises: ['Support two pieces of state (React stores them in call order).'],
    variants: {
      js: { code: snippet('Simulating useState'), output: ['Render count: 0', 'Render count: 1'] },
    },
  },
]

/** The examples in a group, in library order. */
export function libraryGroups(): { group: LibraryExample['group']; examples: LibraryExample[] }[] {
  const groups: { group: LibraryExample['group']; examples: LibraryExample[] }[] = []
  for (const example of LIBRARY) {
    let entry = groups.find(g => g.group === example.group)
    if (!entry) groups.push(entry = { group: example.group, examples: [] })
    entry.examples.push(example)
  }
  return groups
}
