// Lesson order for Lab 01: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  arrays: [
    { p: 0 },
    { figure: 'ListVsArray', caption: 'The same expression on a Python list and on a NumPy array.' },
    { cell: 0 },
    { p: 1 },
    { figure: 'ShapeBoxes', caption: 'Two arrays holding the same three numbers, with different shapes.' },
    { p: 2 },
    { predict: { prompt: 'At 4 seconds per MB, how many seconds does a 3 MB input contribute?', answer: 12, explain: '3 MB × 4 seconds/MB = 12 seconds. The weight turns an amount of input into seconds.' } },
    { p: 3 },
    { p: 4 },
    { figure: 'WeightedSum', caption: 'Each input times its own weight, then added. Change any input or weight and watch its bar.' },
    { cell: 1 },
    { p: 5 },
    { predict: { prompt: 'What is the dot product of `[1, 2]` and `[3, 4]`?', answer: 11, explain: '1×3 + 2×4 = 3 + 8 = 11: multiply matching entries, then add.', misconceptions: [{ answer: 10, feedback: 'That adds all four numbers. Multiply matching entries first: 1×3 and 2×4.' }] } },
    { p: 6 },
    { cell: 2 },
    { cell: 3 },
    { p: 7 },
    { figure: 'ShapeTrap', caption: 'Predictions minus targets, with matching shapes and with a column against a flat vector.' },
    { cell: 4 },
    { p: 8 },
  ],
  slopes: [
    { p: 0 },
    { p: 1 },
    { figure: 'SecantToTangent', caption: 'Shrink h: the average slope between t = 2 and t = 2 + h approaches the derivative, 4.' },
    { p: 2 },
    { cell: 0 },
    { predict: { prompt: 'What is the derivative of t² at t = 5?', answer: 10, explain: 'The derivative of t² is 2t, so at t = 5 it is 10.' } },
    { p: 3 },
    { figure: 'ChainTracer', caption: 'Each link in the chain has its own local rate; the overall rate is their product.' },
    { cell: 1 },
    { p: 4 },
    { figure: 'PartialSlices', caption: 'The same loss, sliced two ways: change only w (left) or only b (right). Each slice has its own slope.' },
    { cell: 2 },
    { p: 5 },
  ],
  model: [
    { p: 0 },
    { p: 1 },
    { figure: 'LineClaim', caption: 'The model is a line. w tilts it; b moves where it crosses x = 0.' },
    { predict: { prompt: 'With w = 2 and b = 1, what does the model predict at x = 0?', answer: 1, explain: 'ŷ = 2×0 + 1 = 1: at x = 0 the prediction is just b.' } },
    { cell: 0 },
    { cell: 1 },
    { p: 2 },
    { figure: 'SplitScatter', caption: 'Circles train the model; diamonds are held back to check it. The grey line is the mean baseline.' },
    { p: 3 },
    { cell: 2 },
    { p: 4 },
  ],
  loss: [
    { p: 0 },
    { p: 1 },
    { figure: 'Residuals', caption: 'Each red segment is one error. Move the line and watch the squared errors and their average.' },
    { cell: 0 },
    { p: 2 },
    { p: 3 },
    { figure: 'OutlierPull', caption: 'Squaring makes one large error dominate the sum.' },
    { cell: 1 },
    { p: 4 },
    { predict: { prompt: 'A model’s MSE is 9 seconds². What is its RMSE, in seconds?', answer: 3, explain: '√9 = 3 seconds: the square root returns the error to the target’s units.' } },
    { cell: 2 },
  ],
  gradient: [
    { p: 0 },
    { p: 1 },
    { figure: 'LossTangent', caption: 'The loss of one observation as w changes, with its slope at the current w.' },
    { predict: { prompt: 'Same example (x = 2, y = 5, w = 1, b = 0). What is ∂(e²)/∂b?', answer: -6, explain: 'e = 2 − 5 = −3 and ∂(e²)/∂b = 2e = −6. Negative: raising b lowers the loss too.', misconceptions: [{ answer: -12, feedback: 'That is the w derivative, 2e·x. For b the chain rule multiplies by ∂e/∂b = 1.' }] } },
    { cell: 0 },
    { p: 2 },
    { p: 3 },
    { figure: 'GradientTable', caption: 'Each observation contributes 2e·x to the weight derivative and 2e to the bias derivative; the gradient averages them.' },
    { cell: 1 },
    { p: 4 },
    { figure: 'FiniteDiff', caption: 'Compare the formula with a centered difference. Move ε to very small values and watch precision break down.' },
    { cell: 2 },
  ],
  training: [
    { p: 0 },
    { figure: 'OneUpdate', caption: 'One gradient step from w = 1, b = 0 on the point (2, 5). The dashed line is before the step.' },
    { predict: { prompt: 'In the same update (∂J/∂b = −6, α = 0.1, b = 0), what is the new b?', answer: 0.6, tolerance: 0.001, explain: 'b_new = 0 − 0.1 × (−6) = 0.6.' } },
    { cell: 0 },
    { p: 1 },
    { p: 2 },
    { p: 3 },
    { p: 4 },
    { figure: 'ValleySteps', caption: 'Steps on the loss valley. Raise α, or raise the scale of x, until the steps overshoot.' },
    { cell: 1 },
  ],
  evaluate: [
    { p: 0 },
    { figure: 'BaselineBars', caption: 'Validation MSE of the model against always predicting the training mean.' },
    { p: 1 },
    { figure: 'SplitScatter', caption: 'Reshuffle the split: the line and both validation numbers move. One split is one sample.' },
    { p: 2 },
    { cell: 0 },
    { p: 3 },
    { figure: 'SplitTimeline', caption: 'Twenty observations in time order. Orange cells are validation.' },
    { p: 4 },
    { predict: { prompt: 'Training targets are 2, 4 and 9; validation targets are 100 and 110. What should the mean baseline predict?', answer: 5, explain: 'The mean of the training targets only: (2 + 4 + 9)/3 = 5. Using validation values to set it would leak them.', misconceptions: [{ answer: 45, feedback: 'That averages training and validation together. The baseline may only use training data.' }] } },
    { p: 5 },
    { figure: 'SplitScatter', props: { shape: 'curved' }, caption: 'The curved dataset: the best straight line still misses in a systematic pattern.' },
    { cell: 1 },
  ],
  transfer: [
    { p: 0 },
    { p: 1 },
    { figure: 'OverheadPerItem', caption: 'Fixed overhead plus a cost per item.' },
    { predict: { prompt: 'w = 0.4 seconds per item and b = 2 seconds. How long do 25 items take?', answer: 12, explain: '2 + 25 × 0.4 = 2 + 10 = 12 seconds.' } },
    { p: 2 },
    { p: 3 },
    { cell: 1 },
    { p: 4 },
    { p: 5 },
    { figure: 'ClosedFormSteps', caption: 'The direct solution, one step at a time, on four points.' },
    { cell: 0 },
    { p: 6 },
  ],
}
