export const lessons = [
  {
    id: 'l60-kinds',
    title: '60.1 · Two kinds of uncertainty',
    sections: ['Why a single number is not enough', 'Aleatoric uncertainty', 'Epistemic uncertainty', 'Heteroscedastic networks', 'Deep ensembles', 'The limits of ensembles'],
    skill: 'Separate aleatoric from epistemic uncertainty and estimate both with a deep ensemble.',
    prerequisite: 'Maximum likelihood (Lab 05), Bayesian linear regression (Lab 41), Gaussian processes (Lab 42), neural networks (Lab 21), bagging (Lab 13).',
    paragraphs: [
      'A point prediction such as “the build will take 31 minutes” hides how sure the model is. A decision often depends on that: page an engineer only if a failure is likely, or buy spare capacity only if demand could plausibly spike. **Uncertainty quantification** attaches a measure of doubt to each prediction.',
      '**Aleatoric uncertainty** (from Latin *alea*, dice) is noise in the data itself: identical inputs can still produce different outcomes. More data does not reduce it, but a model can learn how large it is. In the playground, the noise standard deviation grows from 0.1 at x = 0 to 0.85 at |x| = 3, so an honest model must widen its predictions at the edges.',
      '**Epistemic uncertainty** is the model’s own ignorance: it had too little data to pin down the function. It shrinks as data accumulates and is largest where there was no data at all, in the gap between 0.4 and 1.8 and beyond ±3. A Gaussian process (Lab 42) and Bayesian linear regression (Lab 41) compute epistemic uncertainty exactly for their model classes; neural networks need approximations.',
      'A **heteroscedastic** network outputs both a mean μ(x) and a variance σ²(x), and is trained by the Gaussian negative log-likelihood ½[log σ²(x) + (y − μ(x))²/σ²(x)]. For a fixed residual, the loss is smallest when σ² equals the squared residual, so the variance head learns how big the errors are. In practice, fit the mean alone for a while first; otherwise the network can wave away hard points by inflating σ² early on.',
      'A **deep ensemble** (Lakshminarayanan et al. 2017) trains M such networks from different random starts and treats them as a mixture. By the law of total variance, the mixture’s variance is the mean of the members’ σ² (aleatoric) plus the variance of their means (epistemic). Members agree where data pins the function down and disagree where it does not. Other approximations include MC dropout (keep dropout on at test time and average), Laplace approximations and variational Bayesian networks; ensembles are simple and often the strongest.',
      'The epistemic estimate only reflects disagreement that the members actually show. In the playground, all members bridge the gap with similar smooth curves, so they agree there and are all wrong by about 0.3. Far outside the data they disagree, but the error is still two to three times their spread. Treat ensemble spread as a warning signal, not a calibrated probability, and calibrate it on held-out data (Lessons 60.3–60.4).',
    ],
    formula: 'Var[y | x] = E_m[σ_m²(x)] + Var_m[μ_m(x)]     (aleatoric + epistemic)     NLL = ½[log σ²(x) + (y − μ(x))²/σ²(x)]',
    derivation: {
      title: 'The variance of an ensemble',
      steps: [
        { prompt: 'Two members predict Gaussians with means m1 and m2 and the same variance v. An equal mixture of them has what mean?', answer: '(m1+m2)/2', show: '`(m₁ + m₂)/2`', vars: { m1: [-3, 3], m2: [-3, 3], v: [0.1, 2] } },
        { prompt: 'For one Gaussian, E[y²] = v + m². Write E[y²] for the equal mixture.', answer: 'v+(m1^2+m2^2)/2', show: '`v + (m₁² + m₂²)/2`', vars: { m1: [-3, 3], m2: [-3, 3], v: [0.1, 2] } },
        { prompt: 'Subtract the squared mixture mean to get the mixture variance. Write it in terms of v, m1 and m2.', answer: 'v+(m1-m2)^2/4', show: '`v + (m₁ − m₂)²/4` — noise plus disagreement', vars: { m1: [-3, 3], m2: [-3, 3], v: [0.1, 2] }, hint: '(m₁² + m₂²)/2 − ((m₁ + m₂)/2)² = (m₁ − m₂)²/4.' },
        { prompt: 'With v = 0.36, m1 = 1 and m2 = 1.6, what is the mixture variance?', number: 0.45, tolerance: 1e-6, show: '`0.36 + 0.36/4 = 0.45`' },
        { prompt: 'The Gaussian NLL for one point is ½[log σ² + r²/σ²], where r is the residual. Write the value of σ² that minimizes it.', answer: 'r^2', show: '`σ² = r²`: the derivative ½[1/σ² − r²/σ⁴] is zero there', vars: { r: [0.1, 3] }, why: 'On average over many points, the variance head therefore learns the expected squared residual at each x.' },
      ],
      result: 'An ensemble’s predictive variance is the average noise its members expect plus how much they disagree with one another.',
    },
    experiment: 'Slide the ensemble from 1 to 8 members and watch the epistemic curve. Where does it grow? Compare the error of the mean in the gap with the epistemic spread there.',
    question: 'At some input, the aleatoric variance is 0.25 and the epistemic variance is 0.11. What is the total predictive standard deviation?',
    answer: 0.6,
    tolerance: 0.001,
    explanation: 'Variances add: 0.25 + 0.11 = 0.36, and √0.36 = 0.6.',
    reflection: 'For a prediction you rely on at work, which kind of uncertainty dominates, and would more data help?',
  },
  {
    id: 'l60-quantile',
    title: '60.2 · Quantile regression',
    sections: ['Predict a quantile, not a mean', 'The pinball loss', 'Why it finds the quantile', 'Bands without a distribution', 'Why coverage falls short'],
    skill: 'Train quantile regressors with the pinball loss and check their coverage on held-out data.',
    prerequisite: 'Lesson 60.1; the median and robust statistics (Lab 05); loss functions (Lab 01).',
    paragraphs: [
      'Squared error leads a model to the conditional mean, and absolute error leads it to the conditional median. **Quantile regression** (Koenker & Bassett 1978) generalizes this: for any τ between 0 and 1 it learns q_τ(x), the value below which a fraction τ of outcomes at x fall. A pair such as τ = 0.05 and 0.95 gives a 90% prediction band.',
      'The **pinball loss** is asymmetric. A point above the prediction costs τ times the gap, and a point below costs (1 − τ) times the gap. For τ = 0.9, being too low is 9 times as costly as being too high, so the prediction moves up until only 10% of points lie above it.',
      'Why this gives the quantile: moving q up by a small amount changes the expected loss by (1 − τ)·P(y < q) − τ·P(y > q) = F(q) − τ per unit, where F is the conditional distribution function. The expected loss is smallest where F(q) = τ, which is the definition of the τ-quantile.',
      'Quantile regression assumes no distribution: skewed, heavy-tailed or heteroscedastic noise are all handled, and any model trained by gradients can take the loss, from linear models to gradient boosting (with the quantile loss) to the playground’s two-output network. Two practical cautions: separately trained quantile curves can cross, so sort them or train them jointly, and extreme quantiles need a lot of data because few points lie beyond them.',
      'The band is only as good as the fit. In the playground the nominal 90% band covers about 87% of the training points, because the fit is imperfect, and about 83% of test points, because the network partly fit the noise in its sample; the nominal 50% band covers about 44% of test points. Nothing in the method guarantees coverage on new data. Conformal prediction (next lessons) fixes the coverage while keeping the adaptive shape.',
    ],
    formula: 'ρ_τ(y − q) = τ·(y − q) if y ≥ q, else (1 − τ)·(q − y)     argmin_q E[ρ_τ(y − q)] = F⁻¹(τ)',
    derivation: {
      title: 'The pinball loss finds the quantile',
      steps: [
        { prompt: 'Write the pinball loss for a point above the prediction (y > q), in terms of τ, y and q.', answer: 'τ*(y-q)', show: '`τ(y − q)`', vars: { τ: [0.05, 0.95], y: [2, 4], q: [-1, 1] } },
        { prompt: 'Raising q by a small amount costs (1 − τ) for each point below q and saves τ for each point above. With F = P(y < q), write the derivative of the expected loss with respect to q, in terms of F and τ.', answer: 'F-τ', show: '`(1 − τ)F − τ(1 − F) = F − τ`', vars: { F: [0, 1], τ: [0.05, 0.95] } },
        { prompt: 'For standard normal noise, which q minimizes the expected pinball loss at τ = 0.95? (Two decimals.)', number: 1.645, tolerance: 0.01, show: '`q ≈ 1.645`, where the normal CDF equals 0.95' },
        { prompt: 'The data are 1, 2, 3, 4 and 10, and τ = 0.5. Which q minimizes the total pinball loss?', number: 3, tolerance: 1e-9, show: '`3`, the median — at τ = 0.5 the pinball loss is half the absolute error', why: 'The outlier 10 does not move the median, which is why quantile losses are robust.' },
      ],
      result: 'The expected pinball loss has derivative F(q) − τ, so its minimizer is the τ-quantile of the conditional distribution.',
    },
    experiment: 'Switch between the three quantile pairs and compare nominal, training and test coverage. Move the τ slider and describe how the loss’s two slopes change.',
    question: 'With τ = 0.9, a point lies 2 units below the predicted quantile. What is its pinball loss?',
    answer: 0.2,
    tolerance: 1e-6,
    explanation: 'Below the prediction the slope is 1 − τ = 0.1, so the loss is 0.1 × 2 = 0.2.',
    reflection: 'Name a decision where you would want the 90th percentile rather than the mean, and say why.',
  },
  {
    id: 'l60-conformal',
    title: '60.3 · Split conformal prediction',
    sections: ['A guarantee for any model', 'Scores and the calibration set', 'The conformal quantile', 'Why the guarantee holds', 'What the guarantee says — and does not', 'Put it into practice'],
    skill: 'Wrap any trained model in prediction intervals with guaranteed coverage, and prove why the guarantee holds.',
    prerequisite: 'Lessons 60.1–60.2; held-out evaluation (Lab 06); probability (Lab 04).',
    paragraphs: [
      '**Conformal prediction** (Vovk, Gammerman & Shafer 2005) turns any predictor into prediction intervals or sets with a finite-sample coverage guarantee: P(y_new ∈ C(x_new)) ≥ 1 − α. It assumes no distribution and no correct model, only that the calibration points and the new point are **exchangeable**, meaning their order carries no information. Independent draws from one distribution are exchangeable.',
      'The **split** version is the practical one. Train a model on one part of the data. On a separate **calibration set** of n points, compute a **conformity score** that measures how badly the model did, such as s = |y − μ(x)|. Nothing about the model needs to be good for the guarantee; a better model only gives narrower intervals.',
      'Take q = the ⌈(n + 1)(1 − α)⌉-th smallest calibration score, and predict C(x) = [μ(x) − q, μ(x) + q]: every y whose score would be at most q. If ⌈(n + 1)(1 − α)⌉ > n, q is infinite, because too few calibration points cannot support such a small α. For α = 0.05 you need at least 19 points.',
      'Why it works: by exchangeability, the new point’s score is equally likely to take any of the n + 1 rank positions among all n + 1 scores. It lands among the k smallest with probability k/(n + 1), and choosing k = ⌈(n + 1)(1 − α)⌉ makes this at least 1 − α. With no ties, it is also less than 1 − α + 1/(n + 1), so the intervals are not wastefully conservative.',
      'The guarantee is **marginal**: it averages over the random calibration set and over new points x. Any one calibration draw can give coverage somewhat above or below the target, as the playground’s re-split histogram shows. It also says nothing about coverage for a particular kind of input (next lesson). And it requires exchangeability, which breaks under distribution shift, time trends, or feedback loops.',
      'Procedure: hold out a calibration set the model never trained on, choose a score, compute q with the (n + 1) correction, and report the interval together with α and n. Verify on a test set. Cross-conformal and jackknife+ methods reuse data more efficiently at some computational cost.',
    ],
    formula: 'q = ⌈(n + 1)(1 − α)⌉-th smallest of s₁ … sₙ     C(x) = {y : s(x, y) ≤ q}     1 − α ≤ P(y ∈ C(x)) < 1 − α + 1/(n + 1)',
    derivation: {
      title: 'The coverage guarantee',
      steps: [
        { prompt: 'There are n = 99 calibration scores and α = 0.1. Which rank k gives q?', number: 90, tolerance: 1e-9, show: '`⌈100 × 0.9⌉ = 90`' },
        { prompt: 'The new score is equally likely to take any of the n + 1 ranks. Write the probability that it is among the k smallest, in terms of k and n.', answer: 'k/(n+1)', show: '`k/(n + 1)`', vars: { k: [1, 50], n: [50, 200] } },
        { prompt: 'With n = 20 and α = 0.1, what is the exact coverage k/(n + 1)? (Four decimals.)', number: 19 / 21, tolerance: 1e-4, show: '`k = ⌈21 × 0.9⌉ = ⌈18.9⌉ = 19`, so coverage `19/21 ≈ 0.9048`', why: 'Rounding k up makes coverage at least 1 − α; it exceeds 1 − α by less than 1/(n + 1) = 0.048.' },
        { prompt: 'With α = 0.05, what is the smallest n for which q is finite?', number: 19, tolerance: 1e-9, show: '`n = 19`: `⌈20 × 0.95⌉ = 19 ≤ 19`, while n = 18 needs rank `⌈19 × 0.95⌉ = 19 > 18`' },
      ],
      result: 'Exchangeability makes the new score’s rank uniform, so the ⌈(n + 1)(1 − α)⌉-th calibration score covers it with probability at least 1 − α, for any model and any distribution.',
    },
    experiment: 'Set n = 20 and move α from 0.3 down to 0.05: when does q become infinite? Then compare the width of the re-split histogram at n = 20 and n = 300.',
    question: 'With 199 calibration scores and α = 0.05, which rank (counting from the smallest) gives the conformal quantile?',
    answer: 190,
    explanation: '⌈(199 + 1) × 0.95⌉ = ⌈190⌉ = 190.',
    reflection: 'In your own data, what could make calibration and future points non-exchangeable?',
  },
  {
    id: 'l60-adaptive',
    title: '60.4 · Adaptive intervals and conditional coverage',
    sections: ['Marginal coverage hides who pays', 'Normalized scores', 'Conformalized quantile regression', 'Conditional coverage is impossible in general', 'Distribution shift', 'Choosing a score'],
    skill: 'Choose conformity scores that adapt interval width, and check coverage across regions and under shift.',
    prerequisite: 'Lessons 60.1–60.3; fairness across groups (Lab 31).',
    paragraphs: [
      'The absolute-residual score gives intervals of the same width everywhere. With noise that grows with |x|, 90% overall coverage comes from 100% coverage in the quiet middle and about 80% at the noisy edges. Anyone whose inputs sit at the edges gets intervals that fail twice as often as advertised.',
      'A **normalized score** divides by a predicted scale: s = |y − μ(x)|/σ(x), using the variance head from Lesson 60.1. The interval becomes μ(x) ± q·σ(x), wide where σ is large and narrow where it is small. The guarantee is untouched, because any score works; only efficiency and balance improve.',
      '**Conformalized quantile regression** (CQR, Romano et al. 2019) starts from learned quantile curves lo(x) and hi(x) (Lesson 60.2) and scores s = max(lo(x) − y, y − hi(x)). The score is negative inside the band and positive outside. The interval [lo(x) − q, hi(x) + q] widens the band if it under-covered and narrows it (q < 0) if it over-covered, while keeping its shape.',
      'Ideally coverage would hold at every x: P(y ∈ C(x) | x) ≥ 1 − α. **Exact conditional coverage is impossible** without assumptions, because with finite data an interval cannot be guaranteed for a region with no calibration points (Foygel Barber et al. 2021). Practical middle grounds: check coverage by region or group, as the playground table does, and use **group-conditional (Mondrian) conformal**, which calibrates separately within each group you care about.',
      'Under **distribution shift**, exchangeability fails and so does the guarantee. Shift the test inputs toward the noisy edges and the constant-width interval’s coverage drops to about 81%. The adaptive scores hold up better here, but only because their σ(x) or quantiles happen to be accurate. **Weighted conformal prediction** (Tibshirani et al. 2019) restores coverage under a known covariate shift by weighting calibration points by the likelihood ratio p_test(x)/p_train(x) (Lab 61).',
      'Choosing a score: use the absolute residual for a quick, robust baseline; a normalized score when you have a decent variance estimate; CQR when quantile models fit well. Whatever you choose, report coverage overall and by the slices that matter.',
    ],
    formula: 's_norm = |y − μ(x)|/σ(x) → μ(x) ± q·σ(x)     s_CQR = max(lo(x) − y, y − hi(x)) → [lo(x) − q, hi(x) + q]',
    derivation: {
      title: 'Adaptive scores and marginal coverage',
      steps: [
        { prompt: 'With the normalized score s = |y − μ|/σ, a new y is covered when s ≤ q. Write the upper end of the interval in terms of μ, q and σ.', answer: 'μ+q*σ', show: '`μ + q·σ`', vars: { μ: [-3, 3], q: [0.5, 3], σ: [0.1, 2] } },
        { prompt: 'CQR score for y = 2 with a learned band lo = 0 and hi = 3?', number: -1, tolerance: 1e-9, show: '`max(0 − 2, 2 − 3) = −1`: inside the band, so the score is negative' },
        { prompt: 'The CQR quantile comes out at q = −0.2 for the band [0, 3]. What is the width of the final interval?', number: 2.6, tolerance: 1e-9, show: '`[0.2, 2.8]` has width `2.6`: the band over-covered, so conformal shrinks it' },
        { prompt: '60% of points lie in a quiet region with 100% coverage, and 40% in a noisy region with 75% coverage. What is the overall coverage?', number: 0.9, tolerance: 1e-9, show: '`0.6 × 1 + 0.4 × 0.75 = 0.9`', why: 'The marginal guarantee is met while the noisy region fails one time in four.' },
      ],
      result: 'Any conformity score keeps the marginal guarantee. Adaptive scores decide how evenly coverage is spread and how wide the intervals are.',
    },
    experiment: 'Compare the coverage table for the three scores, then turn on the shift. Which score’s worst slice is best, and which has the narrowest intervals?',
    question: 'Group A (70% of points) has 96% coverage, and overall coverage is exactly 90%. What is the coverage in group B, the other 30%? (Two decimals.)',
    answer: 0.76,
    tolerance: 0.005,
    explanation: '0.9 = 0.7 × 0.96 + 0.3 × c, so c = (0.9 − 0.672)/0.3 = 0.76.',
    reflection: 'Which groups in your application would you check coverage for separately, and why?',
  },
  {
    id: 'l60-sets',
    title: '60.5 · Prediction sets for classification',
    sections: ['Sets instead of labels', 'A score from probabilities', 'Set size as uncertainty', 'Why naive sets miss', 'Empty sets and adaptive scores', 'When the guarantee breaks'],
    skill: 'Build conformal prediction sets for a classifier and interpret set size, coverage and failure under shift.',
    prerequisite: 'Lessons 60.3–60.4; softmax classifiers (Lab 21); calibration (Lab 09).',
    paragraphs: [
      'For classification, conformal prediction returns a **set** of labels guaranteed to contain the true one with probability at least 1 − α. A confident case gets a single label. An ambiguous case gets two or three, which tells the user “it is one of these” instead of forcing a guess.',
      'The simplest score uses the classifier’s probability for the true class: s = 1 − p̂(true class | x). Compute it on the calibration set, take q as before, and include in the set every class k with 1 − p̂(k | x) ≤ q, which is every class with p̂(k | x) ≥ 1 − q. The classifier does not have to be calibrated.',
      'Set size is an honest uncertainty report. In the playground, the shading marks where sets have two or three labels: exactly where the three clusters overlap. The average set size summarizes how useful the classifier is at a given α, and it is a better way to compare models than accuracy alone when uncertainty matters.',
      'Why not just add labels in order of probability until they sum to 1 − α? That trusts the classifier’s probabilities, and they are rarely calibrated (Lab 09). Here the network is underconfident, so these naive sets are too large and over-cover. An overconfident network would under-cover. The conformal step measures how the probabilities actually behave on calibration data.',
      'At large α, some conformal sets are empty: no class is plausible enough. That is allowed by the guarantee and is informative, since it flags inputs unlike the calibration data. **Adaptive prediction sets** (APS, Romano et al. 2020) score by the cumulative probability down to the true class. Their sizes adapt better to how hard each input is, and they are rarely empty.',
      'The guarantee rests on exchangeability. Make the test data noisier than the calibration data and coverage falls far below the target. Deployment data drifts (Labs 30 and 61), so recalibrate regularly on recent labelled data, monitor coverage and set sizes, and use weighted or online conformal methods when shift is expected.',
    ],
    formula: 's(x, y) = 1 − p̂(y | x)     C(x) = {k : p̂(k | x) ≥ 1 − q}     P(y ∈ C(x)) ≥ 1 − α',
    derivation: {
      title: 'From a score to a set',
      steps: [
        { prompt: 'A calibration point’s true class has p̂ = 0.7. What is its score?', number: 0.3, tolerance: 1e-9, show: '`1 − 0.7 = 0.3`' },
        { prompt: 'Class k is included when 1 − p̂_k ≤ q. Write the probability threshold t, with the rule “include if p̂_k ≥ t”.', answer: '1-q', show: '`t = 1 − q`', vars: { q: [0, 1] } },
        { prompt: 'With q = 0.776, how many classes does the set contain for probabilities (0.6, 0.3, 0.1)?', number: 2, tolerance: 1e-9, show: '`t = 0.224`, so 0.6 and 0.3 are in and 0.1 is out: `2` classes' },
        { prompt: 'Under covariate shift, weighted conformal gives each calibration point weight p_test(x)/p_cal(x). Write it in terms of pt and pc.', answer: 'pt/pc', show: '`pt/pc`, the likelihood ratio, as in importance sampling (Lab 44)', vars: { pt: [0.01, 2], pc: [0.01, 2] } },
      ],
      result: 'A conformal set keeps every label whose probability is at least 1 − q, with q calibrated so that the true label is included at the promised rate.',
    },
    experiment: 'Slide α from 0.02 to 0.3 and record the coverage, the average set size and the share of empty sets. Then make the test data noisier and compare the coverage with the target.',
    question: 'With q = 0.7, how many labels are in the set for class probabilities (0.5, 0.35, 0.15)?',
    answer: 2,
    explanation: 'Include classes with p̂ ≥ 1 − 0.7 = 0.3: 0.5 and 0.35 are in, 0.15 is out.',
    reflection: 'Where in your work would a set of plausible answers be more useful than a single best guess?',
  },
]

export const sources = [
  { title: 'Angelopoulos & Bates · A gentle introduction to conformal prediction and distribution-free uncertainty quantification', url: 'https://arxiv.org/abs/2107.07511' },
  { title: 'Vovk, Gammerman & Shafer · Algorithmic Learning in a Random World (2005; 2nd ed. 2022)', url: 'https://doi.org/10.1007/978-3-031-06649-8' },
  { title: 'Lakshminarayanan, Pritzel & Blundell (2017) · Simple and scalable predictive uncertainty estimation using deep ensembles', url: 'https://arxiv.org/abs/1612.01474' },
  { title: 'Koenker & Bassett (1978) · Regression quantiles', url: 'https://doi.org/10.2307/1913643' },
  { title: 'Romano, Patterson & Candès (2019) · Conformalized quantile regression', url: 'https://arxiv.org/abs/1905.03222' },
  { title: 'Tibshirani, Foygel Barber, Candès & Ramdas (2019) · Conformal prediction under covariate shift', url: 'https://arxiv.org/abs/1904.06019' },
  { title: 'Foygel Barber, Candès, Ramdas & Tibshirani (2021) · The limits of distribution-free conditional predictive inference', url: 'https://arxiv.org/abs/1903.04684' },
  { title: 'Romano, Sesia & Candès (2020) · Classification with valid and adaptive coverage (APS)', url: 'https://arxiv.org/abs/2006.02544' },
]
