export const lessons = [
  {
    id: 'l53-ae',
    title: '53.1 · Autoencoders',
    sections: ['Learning to copy through a bottleneck', 'Encoder and decoder', 'What the code captures', 'Relation to PCA', 'Put it into practice'],
    skill: 'Build an autoencoder and interpret its bottleneck representation.',
    prerequisite: 'Neural networks and regularization (Labs 21–23, 52), PCA (Lab 18), cross-entropy (Lab 46).',
    paragraphs: [
      'An **autoencoder** is trained to reproduce its input: an **encoder** maps x to a short code z, a **decoder** maps z back to x̂, and the loss measures how different x̂ is from x. No labels are needed — the data supervise themselves.',
      'Copying is only interesting through a **bottleneck**. With 35 pixels squeezed into 2 numbers, the network must discover which few factors explain the images; similar images end up with similar codes. In the playground, the 2D codes group by digit even though labels were never used.',
      'For binary or [0, 1]-valued pixels, the natural loss is binary cross-entropy per pixel (Lab 46); for real values, squared error. Wider bottlenecks reconstruct more detail but compress less.',
      'A linear autoencoder with squared error learns the same subspace as PCA (Lab 18). Nonlinear layers let it follow curved structure, like the manifold methods of Lab 51, while giving an explicit encoder for new data.',
      'Uses: compression, feature learning for downstream tasks, anomaly detection (inputs that reconstruct badly are unusual), and denoising. Procedure: choose a loss matching the data, pick a bottleneck by validation reconstruction error, and inspect reconstructions and codes.',
    ],
    formula: 'z = enc(x),  x̂ = dec(z),  minimize Σᵢ ℓ(xᵢ, x̂ᵢ)     BCE: ℓ = −Σⱼ [xⱼ log x̂ⱼ + (1 − xⱼ) log(1 − x̂ⱼ)]',
    derivation: {
      title: 'Reconstruction loss for one pixel',
      steps: [
        { prompt: 'Write the binary cross-entropy for a pixel with target t and reconstruction r.', answer: '-(t*log(r) + (1-t)*log(1-r))', show: '`−[t log r + (1 − t) log(1 − r)]`', vars: { t: [0, 1], r: [0.05, 0.95] } },
        { prompt: 'Its derivative with respect to the decoder’s logit a (where r = σ(a)). Write it in terms of r and t.', answer: 'r - t', show: '`r − t`', vars: { r: [0.05, 0.95], t: [0, 1] } },
        { prompt: 'Compression ratio for 35 pixels into a 2-number code?', number: 17.5, show: '`17.5`' },
      ],
      result: 'The same “prediction minus target” gradient as logistic regression (Lab 39), one pixel at a time.',
    },
    experiment: 'In the autoencoder view, compare bottlenecks of 2, 4 and 8. How much does the reconstruction error improve, and which digits are hardest to reconstruct with 2?',
    question: 'An autoencoder maps 784-pixel images to 16 numbers. By what factor does the code compress each image?',
    answer: 49,
    explanation: '784 / 16 = 49.',
    reflection: 'Which data in your work could be summarized by a few learned numbers? How would you check the summary is useful?',
  },
  {
    id: 'l53-denoise',
    title: '53.2 · Denoising and anomaly detection',
    sections: ['Stopping the trivial copy', 'Denoising autoencoders', 'Reconstruction error as an alarm', 'Pitfalls', 'Regularized autoencoders'],
    skill: 'Train denoising autoencoders and use reconstruction error for anomaly detection responsibly.',
    prerequisite: 'Lesson 53.1; anomaly detection (Lab 17); monitoring (Lab 30).',
    paragraphs: [
      'Without a narrow bottleneck, an autoencoder can learn the identity and nothing else. One fix is to corrupt the input — add noise, mask pixels — and train the network to output the **clean** original. It can no longer copy; it must learn what typical data look like.',
      'A **denoising autoencoder** therefore learns the shape of the data distribution: it pulls a corrupted point back toward the region of typical examples. In the playground, trained with noise, it cleans noisy test digits about 40% better (by squared error) than the same network trained without noise.',
      'Because the model reconstructs typical inputs well, a large **reconstruction error** signals an unusual input: a faulty sensor, a fraudulent pattern, a drifted data source (Lab 30). Set the alarm threshold on a clean validation set’s error distribution.',
      'Pitfalls: autoencoders can reconstruct some anomalies well (especially simple ones); errors depend on the input’s complexity; and a model trained on data containing anomalies learns to reconstruct them. Evaluate detection with labelled incidents where possible.',
      'Other regularizations of the code: sparsity penalties (few active units), contractive penalties (codes insensitive to small input changes), and — most influential — the probabilistic regularization of the VAE (next lessons).',
    ],
    formula: 'minimize ℓ(x, dec(enc(x̃))),  x̃ = corrupt(x)     anomaly score = ℓ(x, x̂)',
    derivation: {
      title: 'Setting an alarm threshold',
      steps: [
        { prompt: 'Clean validation reconstruction errors have mean 10 and standard deviation 2. A threshold at mean + 3 sd is?', number: 16, show: '`16`' },
        { prompt: 'If errors were Gaussian, what fraction of clean inputs would exceed it? (Four decimals.)', number: 0.00135, tolerance: 0.0001, show: '`≈ 0.0013`' },
      ],
      result: 'Choose the threshold from the clean error distribution — and check how many real anomalies it catches.',
    },
    experiment: 'Turn on denoising and compare the noisy inputs with the reconstructions. Which digits come back cleanly, and which are confused?',
    question: 'A monitor flags inputs whose reconstruction error exceeds the 99th percentile of clean validation errors. With 10,000 clean inputs a day, about how many false alarms per day?',
    answer: 100,
    explanation: '1% of 10,000 = 100 false alarms a day — a threshold is also a workload decision (Lab 30).',
    reflection: 'What would count as an anomaly in your data, and would an autoencoder be likely to reconstruct it badly?',
  },
  {
    id: 'l53-vae',
    title: '53.3 · Variational autoencoders',
    sections: ['From codes to distributions', 'The generative model', 'The ELBO again', 'The reparameterization trick', 'Two terms, one trade-off'],
    skill: 'Derive the VAE objective and implement the reparameterization trick.',
    prerequisite: 'Lessons 53.1–53.2; the ELBO (Labs 43–44); KL divergence (Lab 46).',
    paragraphs: [
      'A **variational autoencoder** (VAE) is a generative model: draw z ~ N(0, I), then x ~ p_θ(x | z) given by the decoder. To train it we need log p_θ(x) = log ∫ p(z) p_θ(x | z) dz — intractable, like the posteriors of Lab 44.',
      'Variational inference to the rescue: an **encoder** outputs a Gaussian q_φ(z | x) = N(μ(x), diag σ²(x)) approximating the posterior. The ELBO (Labs 43–44) gives log p(x) ≥ E_q[log p_θ(x | z)] − KL(q_φ(z | x) ‖ N(0, I)): a **reconstruction** term plus a **KL** term.',
      'The KL between two Gaussians has a closed form: for each latent dimension, ½(σ² + μ² − 1 − log σ²). It pulls every code distribution toward the standard normal.',
      'We cannot backpropagate through “sample z”. The **reparameterization trick** writes z = μ + σ·ε with ε ~ N(0, I): randomness moves into ε, and gradients flow through μ and σ. The encoder usually outputs log σ² for stability.',
      'Training maximizes the ELBO: reconstruct well, but keep each code distribution close to the prior. The result is a latent space with no holes, where every region decodes to something plausible.',
    ],
    formula: 'ELBO = E_{q(z|x)}[log p(x|z)] − KL(q(z|x) ‖ N(0, I))     KL = ½ Σₖ (σₖ² + μₖ² − 1 − log σₖ²)     z = μ + σ ε',
    derivation: {
      title: 'The Gaussian KL term and its gradients',
      intro: 'One latent dimension with mean m and log-variance l (so σ² = e^l).',
      steps: [
        { prompt: 'Write the KL term ½(σ² + μ² − 1 − log σ²) in terms of m and l.', answer: '0.5*(exp(l) + m^2 - 1 - l)', show: '`½(e^l + m² − 1 − l)`', vars: { m: [-2, 2], l: [-2, 2] } },
        { prompt: 'Its derivative with respect to m.', answer: 'm', show: '`m` — pulls the mean toward 0', vars: { m: [-2, 2], l: [-2, 2] } },
        { prompt: 'Its derivative with respect to l.', answer: '0.5*(exp(l) - 1)', show: '`½(e^l − 1)` — pulls the variance toward 1', vars: { m: [-2, 2], l: [-2, 2] } },
        { prompt: 'Evaluate the KL for m = 0, l = 0.', number: 0, show: '`0` — the code already is the prior' },
      ],
      result: 'These two gradients, plus the decoder’s gradient through z = μ + σε, are the entire VAE backward pass for the latent.',
    },
    experiment: 'In the VAE view at β = 1, compare the latent scatter with the plain autoencoder’s. Which one fills the dashed square evenly?',
    question: 'A latent dimension has mean 1 and variance 1. What is its KL term ½(σ² + μ² − 1 − log σ²)?',
    answer: 0.5,
    explanation: '½(1 + 1 − 1 − 0) = 0.5 nats.',
    reflection: 'Explain to a classmate why we cannot backpropagate through “draw a random sample” — and how reparameterization fixes it.',
  },
  {
    id: 'l53-generate',
    title: '53.4 · Generating and the β trade-off',
    sections: ['Sampling new data', 'Interpolation', 'β-VAE', 'Posterior collapse', 'Blurry samples'],
    skill: 'Generate data with a VAE and diagnose the reconstruction–regularization trade-off.',
    prerequisite: 'Lesson 53.3.',
    paragraphs: [
      'To generate, draw z ~ N(0, I) and decode. For the VAE with β = 1, more than 90% of random codes decode to a clear digit and all ten digits appear. For the plain autoencoder, whose codes have no prescribed distribution, fewer samples are clear and only some of the digits ever appear.',
      'Walking in a straight line between two codes and decoding along the way **interpolates** smoothly between images — useful evidence that the latent space is organized rather than memorized.',
      'Weighting the KL term by β ≠ 1 gives the **β-VAE**. Larger β pushes codes harder toward the prior (sometimes yielding more “disentangled” factors) at the cost of reconstruction; smaller β reconstructs better but leaves gaps in the latent space.',
      'Push β too far and the encoder gives up: KL → 0, the codes carry no information, and the decoder outputs the same average image whatever z is — **posterior collapse**. In the playground at β = 4 the KL term falls to nearly zero and every random code produces the same digit. Powerful decoders (e.g. autoregressive ones) collapse even at β = 1; KL annealing and free-bits tricks help.',
      'VAE samples tend to be **blurry**: the Gaussian decoder and the averaging in the ELBO favour safe, average-looking outputs. GANs and diffusion models (Lab 54) produce sharper samples; VAEs remain valued for their encoder, likelihood bound and smooth latent space — and as the compression stage of latent diffusion models.',
    ],
    formula: 'β-VAE: maximize E_q[log p(x|z)] − β·KL(q(z|x) ‖ p(z))     collapse: KL → 0, x̂ independent of z',
    derivation: {
      title: 'Linear interpolation in latent space',
      steps: [
        { prompt: 'Write the code a fraction s of the way from z_a to z_b (use za, zb).', answer: '(1-s)*za + s*zb', show: '`(1 − s)·z_a + s·z_b`', vars: { s: [0, 1], za: [-2, 2], zb: [-2, 2] } },
        { prompt: 'Halfway between codes −2 and 1?', number: -0.5, show: '`−0.5`' },
      ],
      result: 'In a well-regularized latent space, every point on that line decodes to a plausible image.',
    },
    experiment: 'In the VAE view, switch β between 0.1, 1 and 4. Watch the decoded grid and the number of different digits among random samples.',
    question: 'A VAE reports a KL term of 0.01 nats per image after training, and its samples all look the same. What has happened?',
    choices: [
      { text: 'Overfitting', why: 'Overfitting would show as memorized, varied training images — not a near-zero KL.' },
      { text: 'Posterior collapse', why: 'KL ≈ 0 means z carries almost no information about the input, so the decoder ignores it.' },
      { text: 'The learning rate is too low', why: 'A slow optimizer would leave a large KL or reconstruction loss, not this pattern.' },
    ],
    answer: 1,
    explanation: 'KL ≈ 0 means the codes carry almost no information about the input: the decoder ignores z. That is posterior collapse.',
    reflection: 'For a generative application you can imagine, would you rather have sharp samples or a smooth, meaningful latent space?',
  },
  {
    id: 'l53-uses',
    title: '53.5 · Representation learning in practice',
    sections: ['Codes as features', 'Semi-supervised learning', 'Latent diffusion', 'Evaluating generative models', 'Demonstrate understanding'],
    skill: 'Use autoencoder representations downstream and evaluate generative models sensibly.',
    prerequisite: 'Lessons 53.1–53.4.',
    paragraphs: [
      'The encoder is a learned feature extractor. Train it on plentiful unlabeled data, then fit a small classifier on the codes with few labels — often far better than training from scratch on the labels alone (more in Lab 56).',
      'VAEs model p(x) and can be combined with a label variable for semi-supervised learning: the unlabeled data shape the latent space, the few labels name its regions.',
      'Modern image generators first compress images with an autoencoder (a VAE-like model) into a smaller latent space and run a diffusion model there (**latent diffusion**, Lab 54) — cheaper and faster than working on pixels.',
      'Evaluating generators is hard: likelihood (or its ELBO bound) measures fit but not sample quality; sample-based metrics (FID, precision and recall of samples) compare distributions of features; and human inspection remains essential. Always check for memorized training examples.',
      'You have completed this lab when you can: build and interpret autoencoders; train denoising autoencoders and use reconstruction error responsibly for anomalies; derive the VAE objective, its KL term and the reparameterization trick; generate and interpolate, diagnosing β and posterior collapse; and use learned codes downstream. The Python challenge implements the VAE objective and its gradients.',
    ],
    formula: 'pipeline: pretrain encoder on unlabeled x → small classifier on z with few labels',
    derivation: {
      title: 'Counting the value of pretraining',
      steps: [
        { prompt: 'A classifier on 784 raw pixels with 10 classes has how many weights (no bias)?', number: 7840, show: '`7,840`' },
        { prompt: 'On a 16-number code instead?', number: 160, show: '`160`', why: 'Far fewer parameters to learn from scarce labels.' },
      ],
      result: 'A good code moves most of the learning to the unlabeled data.',
    },
    experiment: 'In the autoencoder view with a 2D bottleneck, could a simple classifier separate the digits using only the two code values? Which digits overlap?',
    question: 'You have 50 labelled and 50,000 unlabelled images. What should the encoder be trained on?',
    choices: [
      { text: 'Only the 50 labelled images', why: 'An autoencoder needs no labels; this throws away 99.9% of the data.' },
      { text: 'All 50,050 images; then fit a classifier on the 50 labelled codes', why: 'Pretrain on everything without labels, then use the labels only where they are needed.' },
      { text: 'The 50,000 unlabelled images only, and never the labelled ones', why: 'There is no reason to exclude the labelled images from unsupervised training (the test set is different).' },
    ],
    answer: 1,
    explanation: 'No — train the autoencoder on all 50,050 images (it needs no labels), then fit the classifier on the 50 labelled codes.',
    reflection: 'Where do you have lots of unlabeled data and few labels? What would you pretrain on?',
  },
]

export const sources = [
  { title: 'Kingma & Welling (2014) · Auto-encoding variational Bayes', url: 'https://arxiv.org/abs/1312.6114' },
  { title: 'Vincent et al. (2008) · Extracting and composing robust features with denoising autoencoders', url: 'https://doi.org/10.1145/1390156.1390294' },
  { title: 'Higgins et al. (2017) · β-VAE: learning basic visual concepts with a constrained variational framework', url: 'https://openreview.net/forum?id=Sy2fzU9gl' },
  { title: 'Goodfellow, Bengio & Courville · Deep Learning, ch. 14 and 20 (free online)', url: 'https://www.deeplearningbook.org/' },
]
