export const lessons = [
  {
    id: 'l45-bn',
    title: '45.1 · Bayesian networks',
    sections: ['Joint distributions are too big', 'Factorize along a graph', 'Counting parameters', 'Inference by enumeration', 'Put it into practice'],
    skill: 'Write the factorization of a Bayesian network, count its parameters and answer queries by enumeration.',
    prerequisite: 'Bayes’ rule and conditional probability (Lab 04), Labs 40–44.',
    paragraphs: [
      'A joint distribution over n yes/no variables needs 2ⁿ − 1 numbers — about a million for 20 variables. Nobody can estimate or even write that down. Structure rescues us: most variables depend directly on only a few others.',
      'A **Bayesian network** is a directed acyclic graph with one node per variable. The joint distribution factorizes as p(x₁, …, xₙ) = Πᵢ p(xᵢ | parents(xᵢ)). In the CI example: p(bad, outage, fails, pager, status) = p(bad)·p(outage)·p(fails | bad, outage)·p(pager | fails)·p(status | outage).',
      'Each node stores a conditional probability table with one entry per combination of its parents: here 1 + 1 + 4 + 2 + 2 = 10 numbers instead of 2⁵ − 1 = 31. With 20 variables and at most 3 parents each, the saving is from a million to at most 160.',
      'Any query can be answered exactly by **enumeration**: P(bad | fails) = Σ over the other variables of the joint with bad = 1 and fails = 1, divided by the same sum without fixing bad. The playground does exactly this. It costs exponential time in general; variable elimination and belief propagation exploit the graph to do far better on sparse graphs.',
      'Procedure: list the variables; draw arrows from direct causes to effects; fill each table from data or expert knowledge; check the model by asking it questions whose answers you know.',
    ],
    formula: 'p(x₁, …, xₙ) = Πᵢ p(xᵢ | parents(xᵢ))',
    derivation: {
      title: 'A joint probability from the tables',
      intro: 'Tables: P(bad) = 0.1, P(outage) = 0.05, P(fails | bad, no outage) = 0.9, P(pager | fails) = 0.95, P(status red | no outage) = 0.02.',
      steps: [
        { prompt: 'P(bad = yes, outage = no, fails = yes, pager = yes, status = not red)? (Five decimals.)', number: 0.1 * 0.95 * 0.9 * 0.95 * 0.98, tolerance: 1e-5, show: '`0.1 × 0.95 × 0.9 × 0.95 × 0.98 ≈ 0.07960`' },
        { prompt: 'How many numbers does the table for “fails” need (two binary parents)?', number: 4, show: '`4`', why: 'One probability of “yes” per parent combination.' },
        { prompt: 'A node with k binary parents needs 2^k numbers. Write the total for n nodes that each have k parents.', answer: 'n*2^k', show: '`n·2^k` — linear in n, not exponential', vars: { n: [1, 20], k: [0, 4] } },
      ],
      result: 'The factorization turns an exponential table into a sum of small local ones.',
    },
    experiment: 'In the Bayesian-network view, click “Only the pager fired”. Which causes become more likely, and by how much compared with observing the failed build directly?',
    question: 'A network over 6 binary variables: two roots, and four nodes each with two binary parents. How many table entries does it need?',
    answer: 18,
    explanation: '2 × 1 + 4 × 4 = 18, compared with 2⁶ − 1 = 63 for the full joint.',
    reflection: 'Sketch a five-node network for an incident you have debugged. Which arrows are you unsure about?',
  },
  {
    id: 'l45-dsep',
    title: '45.2 · Independence and explaining away',
    sections: ['Chains', 'Forks', 'Colliders', 'd-separation', 'Explaining away in practice'],
    skill: 'Read conditional independences from a graph with d-separation and predict explaining away.',
    prerequisite: 'Lesson 45.1.',
    paragraphs: [
      'Three patterns decide everything. A **chain** A → B → C: A and C are dependent, but independent given B (B carries all the information). Here, bad commit → build fails → pager: once you know the build failed, the pager adds nothing about the commit.',
      'A **fork** A ← B → C: a common cause makes A and C dependent, and observing B makes them independent. Here, build fails ← outage → status page.',
      'A **collider** A → B ← C is the opposite: A and C are independent — until B (or a descendant of B) is observed, which makes them dependent. Bad commits and outages are independent causes, but given a failed build, evidence for one is evidence against the other.',
      '**d-separation**: A and C are independent given a set Z if every path between them is blocked — a chain or fork node that is in Z, or a collider that is not in Z and has no descendant in Z. The playground’s independence tool checks the answer numerically.',
      'That collider effect is **explaining away**: P(bad commit) rises from 10% to 63% when the build fails, then drops to 12% once an outage is known, and to 16% with only a red status page. It also explains a classic data trap: selecting on a common effect (only analysing failed builds, only admitted patients) creates correlations between causes that do not exist in the population.',
    ],
    formula: 'chain / fork: blocked when the middle node is observed     collider: blocked unless it (or a descendant) is observed',
    derivation: {
      title: 'Explaining away with two causes',
      intro: 'Causes A and B, each true with probability 0.5, independent. The effect E is true exactly when at least one cause is true (a noiseless OR).',
      steps: [
        { prompt: 'P(A = true | E = true)? (Four decimals.)', number: 2 / 3, tolerance: 1e-4, show: '`(0.5)/(0.75) ≈ 0.6667`', why: 'E rules out only the case where both are false.' },
        { prompt: 'P(A = true | E = true, B = true)?', number: 0.5, show: '`0.5`', why: 'B already explains E, so A goes back to its prior.' },
        { prompt: 'P(A = true | E = true, B = false)?', number: 1, show: '`1`', why: 'Something must explain E, and it is not B.' },
      ],
      result: 'Observing one cause changes belief in the other only because their common effect was observed.',
    },
    experiment: 'Use the independence tool: check bad commit versus outage given nothing, then given the build failure, then given the pager alert. Explain each answer with chains, forks and colliders.',
    question: 'In the network, are “bad commit” and “status page red” independent when the build failure is observed? (1 = yes, 0 = no)',
    answer: 0,
    explanation: 'No. The path bad → fails ← outage → status passes through the collider “fails”, which is observed, so it is open: evidence of a red status page explains away the bad commit.',
    reflection: 'Name a dataset you have seen that was filtered on an outcome. What spurious correlation could that create?',
  },
  {
    id: 'l45-hmm',
    title: '45.3 · Hidden Markov models and filtering',
    sections: ['A hidden state that evolves', 'Three tables', 'The forward algorithm', 'Why it is fast', 'Filtering in production'],
    skill: 'Define an HMM and compute filtered state probabilities with the forward algorithm.',
    prerequisite: 'Lessons 45.1–45.2; Markov chains (Lab 37).',
    paragraphs: [
      'Many systems have a state we cannot see that changes over time: a server’s health, a speaker’s phoneme, a patient’s condition. We see noisy signals of it. A **hidden Markov model** (HMM) is the Bayesian network z₁ → z₂ → … with an observation xₜ hanging off each zₜ.',
      'It has three tables: the initial distribution π, the **transition** matrix A with Aᵢⱼ = P(zₜ = j | zₜ₋₁ = i), and the **emission** matrix B with Bⱼₖ = P(xₜ = k | zₜ = j). The Markov assumption: given today’s state, tomorrow does not depend on yesterday.',
      '**Filtering** asks P(zₜ | x₁..ₜ) — what is the state now, given everything so far? The **forward algorithm** keeps αₜ(j) ∝ P(zₜ = j, x₁..ₜ) and updates it: predict with the transitions, αₜ(j) ∝ Bⱼ(xₜ) Σᵢ αₜ₋₁(i) Aᵢⱼ, then renormalize. Summing the unnormalized totals gives the likelihood P(x₁..T).',
      'Naively, the likelihood sums over Kᵀ state sequences — 3¹⁰⁰ for 100 minutes. The recursion reuses work and costs O(TK²). Normalize at every step (or work in logs) to avoid underflow.',
      'Filtering is what a live system can use: an alert on P(Down | readings so far) above a threshold. Because states persist, one timeout amid fast readings barely moves it, while a run of timeouts does — the filter debounces noise the way a hand-written rule tries to.',
    ],
    formula: 'αₜ(j) ∝ Bⱼ(xₜ) Σᵢ αₜ₋₁(i) Aᵢⱼ     P(x₁..T) = Π normalizers',
    derivation: {
      title: 'One forward step by hand',
      intro: 'Two states. Yesterday’s filtered belief: (0.9, 0.1). Transitions: stay with 0.8, switch with 0.2. Today’s reading has probability 0.1 under state 1 and 0.7 under state 2.',
      steps: [
        { prompt: 'Predicted probability of state 1 before seeing today’s reading: 0.9·0.8 + 0.1·0.2 = ?', number: 0.74, show: '`0.74`' },
        { prompt: 'Multiply by the emission and normalize: P(state 1 | readings)? (Four decimals.)', number: 0.074 / (0.074 + 0.182), tolerance: 1e-4, show: '`0.074 / (0.074 + 0.26 × 0.7) ≈ 0.2891`' },
        { prompt: 'Write the unnormalized update for state 1 in terms of yesterday’s beliefs a1, a2, stay probability s and emission e1.', answer: 'e1*(a1*s + a2*(1-s))', show: '`e1·(a1·s + a2·(1 − s))`', vars: { e1: [0, 1], a1: [0, 1], a2: [0, 1], s: [0.5, 0.99] } },
      ],
      result: 'One surprising reading moved belief from 90% to 29% — strong emissions can overturn a strong prior.',
    },
    experiment: 'In the HMM view, lower the persistence from 0.92 to 0.4 and compare filtering with the raw readings. Why does the advantage vanish?',
    question: 'A 3-state HMM runs for T = 1,000 steps. About how many multiply-adds does the forward algorithm need (T·K²)?',
    answer: 9000,
    explanation: '1,000 × 3² = 9,000 — versus 3¹⁰⁰⁰ sequences for brute force.',
    reflection: 'Where in your systems is a hand-written “n failures in a row” rule really an HMM filter in disguise?',
  },
  {
    id: 'l45-decode',
    title: '45.4 · Smoothing and Viterbi decoding',
    sections: ['Using the future', 'Forward–backward', 'The most probable path', 'Two different questions', 'Linear-Gaussian cousins'],
    skill: 'Compute smoothed marginals with forward–backward and the most probable path with Viterbi, and choose between them.',
    prerequisite: 'Lesson 45.3.',
    paragraphs: [
      'After the fact, later readings are informative too: a timeout followed by recovery was probably a blip. **Smoothing** computes P(zₜ | x₁..T) using all observations.',
      'The **backward** recursion βₜ(i) = Σⱼ Aᵢⱼ Bⱼ(xₜ₊₁) βₜ₊₁(j) summarizes the future; the smoothed marginal is ∝ αₜ(i)·βₜ(i). One forward and one backward pass: O(TK²).',
      '**Viterbi** answers a different question: the single most probable whole sequence argmax P(z₁..T | x). Replace the sum in the forward recursion by a max (in log space), remember which predecessor achieved it, and trace back.',
      'The two can disagree: the sequence of individually most likely states may even be impossible (it could use a transition with probability 0), while the Viterbi path is always a coherent story. Use smoothed marginals for per-time decisions and uncertainty; Viterbi for a consistent segmentation (speech, gene finding, incident timelines).',
      'Replace the discrete states by continuous Gaussian ones with linear dynamics and you get the **Kalman filter** — the same predict-and-update recursion, used for tracking and sensor fusion.',
    ],
    formula: 'βₜ(i) = Σⱼ Aᵢⱼ Bⱼ(xₜ₊₁) βₜ₊₁(j)     P(zₜ | x₁..T) ∝ αₜ βₜ     Viterbi: δₜ(j) = Bⱼ(xₜ) maxᵢ δₜ₋₁(i) Aᵢⱼ',
    derivation: {
      title: 'One Viterbi step',
      intro: 'Two states. Yesterday’s best-path probabilities δ = (0.3, 0.2). Stay 0.8, switch 0.2. Today’s emissions: 0.5 under state 1, 0.4 under state 2.',
      steps: [
        { prompt: 'Best way into state 1 today: max(0.3·0.8, 0.2·0.2) × 0.5 = ?', number: 0.12, show: '`0.24 × 0.5 = 0.12` (from state 1)' },
        { prompt: 'Best way into state 2: max(0.3·0.2, 0.2·0.8) × 0.4 = ?', number: 0.064, show: '`0.16 × 0.4 = 0.064` (from state 2)' },
        { prompt: 'Replace the max by a sum for state 1 (that is the forward step). Value?', number: (0.24 + 0.04) * 0.5, tolerance: 1e-9, show: '`(0.24 + 0.04) × 0.5 = 0.14`', why: 'Forward sums over all paths; Viterbi keeps only the best one.' },
      ],
      result: 'Same recursion, different semiring: sum-product for probabilities, max-product for the best path.',
    },
    experiment: 'In the HMM view, compare the Viterbi strip with the true state strip, and compare the filtered and smoothed curves around a short Down episode. Where does smoothing revise the filter?',
    question: 'Filtering gets 73% of states right and smoothing 77% on the same run. How many more of 300 states does smoothing get right?',
    answer: 12,
    explanation: '(0.77 − 0.73) × 300 = 12 — the value of waiting for later readings.',
    reflection: 'For an incident review, would you want smoothed marginals or a Viterbi timeline? Why?',
  },
  {
    id: 'l45-learn',
    title: '45.5 · Learning graphical models',
    sections: ['With labels: count', 'Without labels: Baum–Welch', 'Local optima again', 'Beyond HMMs', 'Demonstrate understanding'],
    skill: 'Learn HMM parameters with and without labelled states and place HMMs among other structured models.',
    prerequisite: 'Lessons 45.1–45.4; EM (Lab 43).',
    paragraphs: [
      'If the hidden states were recorded (an incident log), learning is counting: Aᵢⱼ = (transitions i → j)/(visits to i), Bⱼₖ = (times state j showed reading k)/(visits to j) — maximum likelihood, like GDA (Lab 40). Add pseudo-counts to avoid zeros.',
      'Without labels, **Baum–Welch** is EM for HMMs (Lab 43): the E-step runs forward–backward to get expected state occupancies and expected transitions; the M-step replaces counts by those expectations and normalizes. The log-likelihood never decreases.',
      'In the playground, most of six random starts reach a log-likelihood slightly above the true model’s (maximum likelihood fits this particular sample), and one stalls on a lower peak. States come out in arbitrary order — match them by their emissions.',
      'Graphical models extend far: **conditional random fields** model p(z | x) discriminatively for sequence labelling; **factor graphs** and belief propagation perform inference on general graphs (exactly on trees); and deep sequence models (Labs 25–26) replace hand-built structure with learned representations, at the cost of interpretability.',
      'You have completed this lab when you can: factorize a joint distribution along a graph and count parameters; answer queries by enumeration; read independences with d-separation and predict explaining away; run the forward, backward and Viterbi recursions; and learn HMMs by counting or Baum–Welch. The Python challenge implements the HMM algorithms and checks them against brute force.',
    ],
    formula: 'Baum–Welch: Aᵢⱼ ← Σₜ ξₜ(i, j) / Σₜ γₜ(i),   Bⱼₖ ← Σₜ γₜ(j)·1[xₜ = k] / Σₜ γₜ(j)',
    derivation: {
      title: 'Learning by counting (supervised)',
      intro: 'An incident log: H H H D H H D D D H (H = Healthy, D = Degraded).',
      steps: [
        { prompt: 'How many transitions leave H (count every H except the last element)?', number: 5, show: '`5`' },
        { prompt: 'How many of those go H → D?', number: 2, show: '`2`' },
        { prompt: 'Maximum-likelihood estimate of P(D | previous H)?', number: 0.4, show: '`2/5 = 0.4`' },
      ],
      result: 'With labels, every HMM parameter is a ratio of counts. Baum–Welch replaces the counts by expected counts.',
    },
    experiment: 'In the Baum–Welch view, identify the start that stalled. Compare its final log-likelihood with the best, then match the best start’s learned states to Healthy, Degraded and Down using the reading table.',
    question: 'Expected counts from the E-step: state 1 is occupied 40 times (excluding the last step), with 30 expected self-transitions. What is the updated A₁₁?',
    answer: 0.75,
    explanation: '30 / 40 = 0.75 — the same ratio as counting, with fractional counts.',
    reflection: 'Which process in your work would you model as an HMM, and what would the hidden states be?',
  },
]

export const sources = [
  { title: 'Koller & Friedman · Probabilistic Graphical Models (MIT Press)', url: 'https://mitpress.mit.edu/9780262013192/probabilistic-graphical-models/' },
  { title: 'Rabiner (1989) · A tutorial on hidden Markov models and selected applications in speech recognition', url: 'https://doi.org/10.1109/5.18626' },
  { title: 'Bishop · Pattern Recognition and Machine Learning, ch. 8 and 13 (free PDF)', url: 'https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/' },
  { title: 'Jurafsky & Martin · Speech and Language Processing, appendix A: HMMs (free draft)', url: 'https://web.stanford.edu/~jurafsky/slp3/' },
]
