import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l31-data',
    title: '31.1 · Permission, privacy and purpose',
    sections: ['Can you use this data?', 'Purpose limitation', 'Minimize and protect', 'Sensitive attributes', 'Put it into practice'],
    skill: 'Check permissions, minimize data and handle sensitive attributes responsibly before modelling.',
    prerequisite: 'Labs 01–30; data contracts and lineage (Lab 28).',
    paragraphs: [
      'Before asking whether a model is accurate, ask whether you may build it. Data collected for one purpose (resolving support tickets) is not automatically permitted for another (evaluating employees). Check the agreement, the policy and, where they apply, laws such as the GDPR — and record the answer with the dataset version (Lab 28).',
      '**Purpose limitation**: write down the decision the model supports and use data only for that. **Data minimization**: collect and keep only the fields the model needs; drop free-text fields that contain personal details unless they are essential.',
      'Protect what you keep: access controls, retention limits, removing direct identifiers, and care with logs — prediction logs (Lab 29) often contain more personal data than the training set. Aggregates can still leak information about individuals, especially in small groups.',
      'Sensitive attributes (region, age, gender, disability) raise a tension: using them as model inputs may be inappropriate or unlawful, yet you may need them to **check** whether the model treats groups differently. Where permitted, keep them separately for auditing rather than as features.',
      'Procedure: purpose statement → data inventory with permissions → minimization → protection and retention plan → decision about sensitive attributes (feature, audit-only, or not held). Put the answers in the model card (Lesson 31.5).',
    ],
    formula: 'purpose → permitted data → minimum necessary fields → protection → audit plan',
    experiment: 'Read the draft model card. Which statements about data and permissions would you need evidence for before publishing it?',
    question: 'A dataset has 14 columns; the model uses 5 and an audit needs 1 more. Under data minimization, how many columns should the training extract contain at most?',
    answer: 6,
    explanation: '5 model features + 1 audit attribute = 6. The other 8 columns should not be copied into the training pipeline.',
    reflection: 'For a model you might build, write its purpose statement and list which fields you would not need to collect.',
  },
  {
    id: 'l31-subgroups',
    title: '31.2 · Subgroup evaluation',
    sections: ['Averages hide groups', 'Slice every metric', 'Calibration by group', 'Uncertainty in small groups', 'Why errors differ'],
    skill: 'Evaluate a model separately for relevant groups and interpret the differences carefully.',
    prerequisite: 'Lesson 31.1; metrics and calibration (Lab 09).',
    paragraphs: [
      'An overall recall of 82% can combine 91% in one region with 75% in another. The people in the second region experience the second number. Evaluate every important metric separately for each relevant group: base rate, selection rate, recall, false-positive rate, precision, calibration.',
      'In the playground, one scoring function serves both regions, but region B\'s input is noisier. The model misses more of B\'s urgent tickets and raises more false alarms there. Nothing in the code mentions region; the difference comes from the data.',
      'Check calibration per group (Lab 09): a pooled model can be calibrated overall and miscalibrated within each group in opposite directions — too cautious for A, too confident for B. A score of 0.7 then means different things for different people.',
      'Small groups give noisy metrics. Report the number of examples and an interval (Lab 05) for each group metric; a 10-point gap measured on 30 examples may be noise, while a 3-point gap on 30,000 is real.',
      'An audit shows **that** errors differ, not **why**. Data quality, a different case mix, or labels recorded differently are all possible. Investigate before concluding, and avoid causal language the evidence does not support (Lab 05).',
    ],
    formula: 'for each group g: base_g, selection_g, TPR_g, FPR_g, PPV_g, calibration_g (with n_g and intervals)',
    experiment: 'Set region B\'s noise equal to A\'s (0.8). Which gaps disappear, and which remain because of the different base rates?',
    question: 'Region A has recall 0.906 and region B 0.746. What is the gap in percentage points? (One decimal.)',
    answer: 16, tolerance: 0.05,
    explanation: '90.6 − 74.6 = 16.0 points: among tickets that truly need escalation, B\'s are missed far more often.',
    reflection: 'Which groups should a model you know be evaluated on? Would you be permitted to hold the attributes needed to do so?',
  },
  {
    id: 'l31-fairness',
    title: '31.3 · Fairness criteria and their trade-offs',
    sections: ['Several definitions', 'They conflict', 'Thresholds by group', 'Choosing is a decision about harm', 'What not to claim'],
    skill: 'State common fairness criteria, recognize their incompatibility, and choose with stakeholders.',
    prerequisite: 'Lessons 31.1–31.2; thresholds and costs (Lab 09).',
    paragraphs: [
      '**Demographic parity**: equal selection rates across groups. **Equal opportunity**: equal true-positive rates (qualified cases found equally often). **Equalized odds**: equal true-positive and false-positive rates. **Predictive parity**: equal precision (a flag means the same in each group). **Calibration within groups**: a score means the same probability in each group.',
      'When base rates differ and the model is imperfect, these cannot all hold together — a mathematical result, not a failure of effort. Equal selection rates with different base rates force different error rates; equal error rates force different precision; and so on.',
      'Separate thresholds per group can equalize one criterion (turn on the toggle and match recall) while moving others. Whether group-specific treatment is appropriate — or permitted — depends on law and context.',
      'Choosing which criterion matters is a decision about harms: in escalation triage, a missed urgent ticket (false negative) may matter most, pointing toward equal opportunity. Make the choice with the people affected and the owners of the decision, write down why, and monitor it (Lab 30).',
      'Do not claim a model is "fair" or "unbiased" in general. State which criteria were measured, on which groups and data, with what uncertainty, and what the remaining gaps are.',
    ],
    formula: 'parity: P(ŷ=1|g) equal · opportunity: TPR_g equal · odds: TPR_g and FPR_g equal · predictive parity: PPV_g equal',
    experiment: 'Enable separate thresholds and adjust region B\'s until recall matches region A. Record what happens to B\'s false-positive rate and precision.',
    question: 'Region A has a base rate of 20% and region B 35%. A model flags exactly the true positives in each region (perfect). What is the gap in selection rates, in points?',
    answer: 15,
    explanation: 'A perfect model flags 20% of A and 35% of B: demographic parity is violated by 15 points even though every decision is correct.',
    reflection: 'For a decision you know, which kind of error is most harmful to the people affected? Which fairness criterion does that suggest?',
  },
  {
    id: 'l31-oversight',
    title: '31.4 · Explainability and human oversight',
    sections: ['What explanations can do', 'Their limits', 'Human review bands', 'Meaningful oversight', 'Appeals and feedback'],
    skill: 'Use explanations and human review appropriately, and design meaningful oversight.',
    prerequisite: 'Lessons 31.1–31.3; feature importance (Labs 12, 14), attention caveats (Lab 26).',
    paragraphs: [
      'Explanations — a readable tree path (Lab 12), per-word contributions (Lab 11), importance scores — help people understand, debug and contest predictions. Give them in the terms the reader uses: "flagged mainly because severity words appeared and the account had three recent outages".',
      'They have limits: importance scores describe the model, not the world (Lab 05); attention weights are not explanations (Lab 26); post-hoc explanations of complex models can be unstable or misleading. Test explanations by checking whether changing the highlighted inputs changes the prediction.',
      'Route uncertain cases to people: a review band around the threshold automates the confident decisions and sends the rest to a reviewer. In the playground, reviewing about 9% of tickets raises the accuracy of the automated ones from about 92% to about 94%.',
      'Oversight is meaningful only if reviewers have time, context, authority to override, and a way to feed corrections back. Measure how often reviewers disagree with the model; a reviewer who always agrees is not oversight.',
      'Provide a route to contest decisions and correct data, especially where outcomes affect people. Appeals are also a data source: patterns in successful appeals point to model or data problems.',
    ],
    formula: 'defer if |score − 0.5| ≤ w     automated share and accuracy traded by w',
    experiment: 'Sweep the review band from 0 to 0.4. What width would you choose if a reviewer can handle 200 tickets per 3,000?',
    question: 'Out of 3,000 tickets, 263 fall inside the review band. What share is automated? (Three decimals.)',
    answer: 0.9123, tolerance: 0.0006,
    explanation: '(3000 − 263)/3000 = 2737/3000 ≈ 0.912.',
    reflection: 'Design the review step for a model you know: who reviews, what they see, and how their corrections improve the model.',
  },
  {
    id: 'l31-card',
    title: '31.5 · Model cards and honest communication',
    sections: ['Documentation others can use', 'What a model card contains', 'Write limitations from evidence', 'Communicating uncertainty', 'Demonstrate understanding'],
    skill: 'Write a model card with intended use, limitations and subgroup results, and communicate uncertainty honestly.',
    prerequisite: 'Lessons 31.1–31.4.',
    paragraphs: [
      'A **model card** is a short document that travels with the model: what it is for, what it is not for, the data it was built on, how it was evaluated (overall and by group), its limitations, how humans oversee it, and ethical considerations. Datasets deserve similar **datasheets**.',
      'Write limitations from evidence, not boilerplate: "recall in region B is 16 points lower than in region A (n = 1,265), likely related to less structured severity data; B tickets in the review band are always escalated to a human." The playground fills the evaluation table from the audit; the limitations are yours to write.',
      'Communicate uncertainty in forms people use: intervals, frequencies ("about 1 in 4 flags in region B is a false alarm"), and explicit conditions ("evaluated on 2025–2026 tickets; not tested on the new product line").',
      'Update the card with every model version (Lab 32) and link it from the prediction API and the monitoring dashboard (Labs 29–30). An out-of-date card is worse than none: it gives false assurance.',
      'You have completed this lab when you can: check permissions and minimize data; evaluate and calibrate by subgroup with uncertainty; explain the trade-offs between fairness criteria; design meaningful human oversight; and write a model card whose claims are supported by evidence. The Python challenge computes the group metrics and generates a validated model card.',
    ],
    formula: 'model card = intended use + out of scope + data + evaluation by group + limitations + oversight + ethics',
    experiment: 'Complete the limitations and ethical considerations in the model card from your audit results, then download it.',
    question: 'In region B, precision is 0.781. Out of 100 flagged tickets in B, about how many are false alarms?',
    answer: 22, tolerance: 0.5,
    explanation: '(1 − 0.781) × 100 ≈ 22 false alarms per 100 flags — a clearer statement than "precision 78%" for many readers.',
    reflection: 'Which claim in a model you have seen described was not supported by evidence? How would you rewrite it?',
  },
]

export const sources = [
  { title: 'Mitchell et al. (2019) · Model cards for model reporting', url: 'https://arxiv.org/abs/1810.03993' },
  { title: 'Gebru et al. (2021) · Datasheets for datasets', url: 'https://arxiv.org/abs/1803.09010' },
  { title: 'Barocas, Hardt & Narayanan · Fairness and Machine Learning (free book)', url: 'https://fairmlbook.org/' },
  { title: 'Kleinberg, Mullainathan & Raghavan (2016) · Inherent trade-offs in the fair determination of risk scores', url: 'https://arxiv.org/abs/1609.05807' },
  { title: 'NIST · AI Risk Management Framework', url: 'https://www.nist.gov/itl/ai-risk-management-framework' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
