// “Jumping in here from a course?” — three prerequisite checks for every lab after Lab 01.
// Each check: the question, choices as [text, why] (why explains that option — for a wrong
// option, the misconception it reveals), the index of the right choice, and the lesson ids
// that teach the missing idea. jumpIn.test.js checks every id exists in an earlier lab.
const q = (question, answer, review, ...choices) => ({ question, answer, review: [].concat(review), choices: choices.map(([text, why]) => ({ text, why })) })

export const jumpIns = {
  2: { checks: [
    q('`x = [1, 2, 3]` is a plain Python list. What is `2 * x`?', 1, 'arrays',
      ['`[2, 4, 6]`', 'That is what a NumPy array does. A list treats `*` as repetition, which is exactly the kind of silent difference Lab 02 builds habits against.'],
      ['`[1, 2, 3, 1, 2, 3]`', 'A list repeats; a NumPy array multiplies each entry.'],
      ['An error', 'Python accepts it — and returns something you may not expect.']),
    q('A model has training MSE 2 and validation MSE 9. Which number estimates how it will do on new data?', 2, 'evaluate',
      ['Training MSE, because the model saw more data there', 'Training error rewards memorization; it is measured on the rows the model was fitted to.'],
      ['Their average, 5.5', 'Averaging mixes an optimistic number with an honest one. The two answer different questions.'],
      ['Validation MSE', 'Validation rows were not used for fitting, so they stand in for future data.']),
    q('Predictions have shape `(4, 1)` and targets have shape `(4,)`. What shape is `pred - y`?', 1, 'arrays',
      ['`(4,)`', 'Broadcasting does not line them up that way: a column meets a row and every pair is subtracted.'],
      ['`(4, 4)`', 'Broadcasting stretches the column and the row into a 4 × 4 grid — 16 “errors”, most of them meaningless.'],
      ['An error', 'NumPy happily broadcasts these shapes, which is why the bug is silent.']),
  ]},
  3: { checks: [
    q('What is the dot product of `[1, 2, 3]` and `[4, 0, −1]`?', 0, 'arrays',
      ['1', '4 + 0 − 3 = 1: multiply matching entries, then add.'],
      ['`[4, 0, −3]`', 'That is the elementwise product. The dot product also adds the entries.'],
      ['7', 'Check the sign of the last product: 3 × (−1) = −3.']),
    q('With prediction `w·x + b` and error `e = ŷ − y`, which is ∂MSE/∂w?', 0, ['gradient', 'slopes'],
      ['`2·mean(e·x)`', 'The chain rule gives 2e from the square and x from the prediction.'],
      ['`2·mean(e)`', 'That is the derivative with respect to b: the prediction changes at rate 1 when b moves, not x.'],
      ['`mean(e²)`', 'That is the loss itself, not its slope.']),
    q('`X` has shape `(100, 3)`. What is the shape of `X.mean(axis=0)`?', 1, 'l02-indexing',
      ['`(100,)`', 'That is `axis=1`, one mean per row. `axis=0` collapses the rows.'],
      ['`(3,)`', 'One mean per column: axis 0 (the rows) is averaged away.'],
      ['A single number', 'That is `X.mean()` with no axis.']),
  ]},
  4: { checks: [
    q('`x = np.array([1, 5, 7, 2])`. What is `(x > 3).mean()`?', 2, 'l02-indexing',
      ['An error — you cannot average booleans', 'NumPy treats True as 1 and False as 0. This is how every simulation in Lab 04 counts events.'],
      ['6', 'That is the mean of the values above 3. `(x > 3)` is a boolean mask, not the selected values.'],
      ['0.5', 'Two of four entries are True, so the fraction is 0.5.']),
    q('You create `rng = np.random.default_rng(42)` twice and draw ten numbers from each. What happens?', 1, 'l02-seeds',
      ['Different numbers each time', 'A generator is deterministic given its seed; that is what makes a simulation reproducible.'],
      ['The same ten numbers both times', 'Same seed, same sequence.'],
      ['The same numbers only if you restart Python', 'A new generator with the same seed restarts the sequence, with no restart needed.']),
    q('Why pass `rng` or `seed` into a simulation function rather than using a global generator?', 0, 'l02-functions',
      ['Every value the result depends on is then visible in the call', 'Hidden state is what makes a number impossible to regenerate.'],
      ['It makes the code run faster', 'Speed is not the point; reproducibility is.'],
      ['Global generators are not random', 'They are; the problem is that nobody can see or control their state.']),
  ]},
  5: { checks: [
    q('A random variable has variance 4. What is its standard deviation?', 0, 'l04-expectation',
      ['2', 'Standard deviation is the square root of variance, in the original units.'],
      ['4', 'That is the variance itself, in squared units.'],
      ['16', 'Squaring goes the wrong way: variance is the square of the standard deviation.']),
    q('Two fair coins are tossed independently. What is P(both heads)?', 1, 'l04-conditional',
      ['0.5', 'That is P(one coin is heads). Both must happen.'],
      ['0.25', 'Independent events multiply: 0.5 × 0.5.'],
      ['0.75', 'That is P(at least one head).']),
    q('A simulated proportion is 0.5 from 100 trials. Roughly how uncertain is it?', 2, 'l04-verify',
      ['Not at all — 0.5 is exact', 'A different seed gives a different estimate. Every simulated number has sampling error.'],
      ['About ±0.5', 'That would mean we know nothing. The error shrinks like 1/√n.'],
      ['Standard error about 0.05', '√(0.5 × 0.5 / 100) = 0.05.']),
  ]},
  6: { checks: [
    q('Model A has validation MSE 10.2 and model B 10.0 on one random split of 40 rows. What can you conclude?', 2, ['l05-clt', 'l05-interval'],
      ['B is better', 'A 2% gap on 40 rows is well within what a different split would change.'],
      ['A is better, because lower is worse', 'Lower MSE is better, and the gap is still too small to call.'],
      ['Not much yet: the difference may be sampling noise', 'Without a measure of variation (folds, bootstrap), one split cannot separate them.']),
    q('You standardize with the mean and standard deviation of the whole dataset, then split. What is wrong?', 0, 'l03-scaling',
      ['Validation rows influenced the preprocessing', 'Statistics must come from training rows only and be reused unchanged on validation.'],
      ['Nothing; standardization has no parameters', 'It has two per column: the mean and the standard deviation.'],
      ['Only that it is slower', 'The issue is leakage, not speed.']),
    q('Why compare every model against a simple baseline such as the training mean?', 1, 'evaluate',
      ['Baselines are required by scikit-learn', 'They are required by honest evaluation, not by a library.'],
      ['A score means little until you know what doing nothing clever achieves', 'MSE 9 is excellent or useless depending on the baseline.'],
      ['Baselines are always worse', 'Sometimes the baseline wins — and that is an important result.']),
  ]},
  7: { checks: [
    q('You add a column of random noise to a linear regression. What happens to training MSE?', 0, 'l03-projection',
      ['It stays the same or goes down', 'A bigger column space can only bring the projection closer to y.'],
      ['It goes up, because noise hurts', 'Noise hurts validation error. On training data the fit can use it to chase random patterns.'],
      ['It is unchanged, always', 'It usually drops a little — that is the problem with judging by training error.']),
    q('You try 50 settings and report the best one’s validation score. That score is…', 1, 'l06-discipline',
      ['An unbiased estimate of future performance', 'Picking the maximum of 50 noisy scores selects luck as well as quality.'],
      ['Optimistic: selecting the best also selects favorable noise', 'The winner’s curse. A fresh test set gives the honest number.'],
      ['Pessimistic', 'Selection pushes the reported score up, not down.']),
    q('5-fold cross-validation on 100 rows. How many rows fit the model in each fold?', 2, 'l06-cv',
      ['20', 'That is the held-out part of each fold.'],
      ['100', 'Then nothing would be held out.'],
      ['80', 'Four folds of 20 train; one validates.']),
  ]},
  8: { checks: [
    q('10 independent trials give 7 successes. What is the maximum-likelihood estimate of p?', 1, 'l05-likelihood',
      ['0.5', 'That ignores the data. The likelihood p⁷(1−p)³ peaks elsewhere.'],
      ['0.7', 'The observed proportion maximizes the Bernoulli likelihood.'],
      ['7', 'A probability must lie between 0 and 1.']),
    q('`X` has shape `(n, p)`. What is the shape of the gradient `Xᵀ(Xw − y)`?', 0, 'l03-gradient',
      ['`(p,)`', 'One partial derivative per weight.'],
      ['`(n,)`', 'That is the error vector. Multiplying by Xᵀ sums over observations.'],
      ['`(n, p)`', 'A gradient has one entry per parameter, not per cell of X.']),
    q('Why do we maximize the log of a likelihood instead of the likelihood itself?', 2, 'l05-likelihood',
      ['The log changes where the maximum is', 'Log is increasing, so the maximizer is the same.'],
      ['Logs make probabilities larger', 'They make them negative; that is fine.'],
      ['A product of many probabilities becomes a sum, which is stable and easy to differentiate', 'log(ab) = log a + log b, and the maximizer does not move.']),
  ]},
  9: { checks: [
    q('A classifier gives p = 0.3 for an example. With threshold 0.5, what does it predict?', 0, 'l08-decision',
      ['Negative', '0.3 < 0.5. The probability is not yet the decision — the threshold is.'],
      ['Positive, since p > 0', 'Any non-zero probability is not a positive prediction; the threshold decides.'],
      ['Nothing until retrained', 'The model output is fine; the threshold turns it into a decision.']),
    q('An alarm catches 90% of faults. Does that mean P(fault | alarm) = 0.9?', 1, 'l04-bayes',
      ['Yes, they are the same number', 'That confuses a conditional probability with its reverse.'],
      ['No — it depends on how rare faults are and how often the alarm fires falsely', 'Bayes’ rule: with rare faults, most alarms can be false.'],
      ['No, it is always 0.1', 'It is not the complement; it needs the base rate.']),
    q('90% of emails are not spam. What accuracy does “always predict not spam” get?', 2, 'l06-baselines',
      ['0.5', 'The baseline copies the class balance, not a coin flip.'],
      ['0.1', 'That is its accuracy on spam alone.'],
      ['0.9', 'Which is why accuracy alone can mislead on imbalanced data.']),
  ]},
  10: { checks: [
    q('Feature A ranges 0–1 and feature B ranges 0–10,000. Without scaling, which dominates a Euclidean distance?', 1, 'l03-scaling',
      ['A, because it is more precise', 'Distance adds squared differences; the larger scale wins.'],
      ['B', 'Its differences are thousands of times larger, so A barely counts.'],
      ['Neither; distance is scale-free', 'Euclidean distance depends directly on units.']),
    q('A model gets 0 training error and high validation error. What is the likely diagnosis?', 0, 'l07-fit',
      ['Overfitting (high variance)', 'It has memorized the training set.'],
      ['Underfitting', 'Underfitting shows high error on training data too.'],
      ['A bug in validation', 'Possible, but the classic signature is overfitting.']),
    q('Inside cross-validation, where should a scaler’s mean and standard deviation be computed?', 2, 'l06-leakage',
      ['On all rows, once, before splitting', 'That leaks each validation fold into its own preprocessing.'],
      ['On the validation fold', 'Validation is for measuring, never for fitting.'],
      ['On each fold’s training rows', 'Refit per fold, then apply unchanged to that fold’s validation rows — a pipeline does this.']),
  ]},
  11: { checks: [
    q('Which is Bayes’ rule?', 1, 'l04-bayes',
      ['P(A | B) = P(B | A)', 'That confuses a conditional with its reverse.'],
      ['P(A | B) = P(B | A)·P(A) / P(B)', 'Prior times likelihood, normalized.'],
      ['P(A | B) = P(A)·P(B)', 'That is P(A and B) for independent events.']),
    q('If A and B are independent, what is P(A and B)?', 0, 'l04-conditional',
      ['P(A)·P(B)', 'Independence means knowing one does not change the other, so they multiply.'],
      ['P(A) + P(B)', 'Adding is for mutually exclusive events, and even then gives “or”.'],
      ['min(P(A), P(B))', 'That is only an upper bound.']),
    q('Why add log-probabilities instead of multiplying hundreds of word probabilities?', 2, ['l08-loss', 'l05-likelihood'],
      ['Logs are more accurate probabilities', 'They are the same information, just transformed.'],
      ['Multiplication is not allowed for probabilities', 'It is — it just underflows.'],
      ['The product underflows to 0 in floating point', 'A sum of logs stays in range and compares the same way.']),
  ]},
  12: { checks: [
    q('Training accuracy 100%, validation accuracy 70%. What does this pattern suggest?', 0, 'l07-fit',
      ['Overfitting', 'The model fits noise that does not repeat.'],
      ['Underfitting', 'An underfit model is poor on training data too.'],
      ['A perfect model', 'Validation is what counts.']),
    q('Which single number minimizes squared error on targets `[4, 6, 11]`?', 1, 'evaluate',
      ['6, the median', 'The median minimizes absolute error.'],
      ['7, the mean', 'The mean is the constant that minimizes squared error — what a regression leaf predicts.'],
      ['11, the largest', 'That makes the other errors large.']),
    q('You choose a tree depth by its test-set score. What is the problem?', 2, 'l06-discipline',
      ['None — the test set is for choosing', 'Choosing is the validation set’s job.'],
      ['Depth cannot be tuned', 'It can; the question is where.'],
      ['The test score is no longer an unbiased estimate', 'Tune with cross-validation; touch the test set once.']),
  ]},
  13: { checks: [
    q('You average T independent estimates, each with variance σ². What is the variance of the average?', 0, 'l05-clt',
      ['σ²/T', 'Averaging independent noise shrinks variance by T. Forests fight the fact that trees are not independent.'],
      ['σ²', 'That is the variance of one estimate.'],
      ['σ²/√T', 'The standard deviation shrinks by √T; the variance by T.']),
    q('A bootstrap resample of n rows is drawn…', 1, 'l05-bootstrap',
      ['without replacement, n rows', 'That just reorders the data.'],
      ['with replacement, n rows', 'Some rows appear several times and about 37% are left out.'],
      ['with replacement, n/2 rows', 'The standard bootstrap keeps the original size.']),
    q('A fully grown, unpruned decision tree typically has…', 2, 'l12-overfit',
      ['high bias and low variance', 'It can fit almost any pattern, so its bias is low.'],
      ['low bias and low variance', 'Then there would be nothing for averaging to fix.'],
      ['low bias and high variance', 'Small data changes reshape it — exactly what bagging averages away.']),
  ]},
  14: { checks: [
    q('In gradient descent, `w ← w − α·∂J/∂w`. Why the minus sign?', 0, 'training',
      ['The gradient points uphill; we step the other way', 'Minus the gradient is the direction of steepest decrease.'],
      ['To keep w positive', 'Weights can be any sign.'],
      ['It is a convention with no effect', 'Using + would climb the loss.']),
    q('What does a regression-tree leaf predict?', 1, 'l12-regression',
      ['The largest target in the leaf', 'That is not what minimizes squared error.'],
      ['The mean of its training targets', 'Boosting fits these leaves to residuals.'],
      ['A new linear model', 'Standard trees predict a constant per leaf.']),
    q('Training error keeps falling while validation error starts rising. What should you do?', 2, ['l07-fit', 'l07-learning'],
      ['Train longer', 'The rise is overfitting; more training makes it worse.'],
      ['Nothing; validation is noisy', 'A consistent rise is a signal.'],
      ['Stop at the validation minimum (early stopping)', 'Boosting chooses its number of stages this way.']),
  ]},
  15: { checks: [
    q('Boundary w·x + b = 0 with w = (1, 1) and b = −2. Which side is x = (3, 3) on?', 0, 'l08-boundary',
      ['Positive: 3 + 3 − 2 = 4 > 0', 'The sign of the score picks the side.'],
      ['Negative', 'Check the score: it is positive.'],
      ['On the boundary', 'The score would be exactly 0.']),
    q('Increasing λ in an L2 penalty λ‖w‖² tends to…', 1, 'l07-ridge',
      ['increase the weights', 'The penalty grows with the weights, so it shrinks them.'],
      ['shrink the weights, trading fit for stability', 'An SVM’s C plays the inverse role.'],
      ['remove features exactly', 'That is L1 (lasso).']),
    q('For a confident, correct prediction, logistic loss is…', 2, 'l08-loss',
      ['exactly zero', 'Close, but log loss only reaches 0 in the limit — unlike the hinge loss.'],
      ['large', 'Large loss is for confident mistakes.'],
      ['close to zero but positive', 'The hinge loss, by contrast, is exactly zero past the margin.']),
  ]},
  16: { checks: [
    q('A feature is “time the ticket was closed”, used to predict ticket duration at creation. What is wrong?', 0, 'l06-leakage',
      ['It is not known at prediction time: leakage', 'It encodes the answer. Features must exist at the moment you predict.'],
      ['Nothing — it is highly predictive', 'Too predictive to be true is a leakage warning.'],
      ['It needs scaling', 'Scaling cannot fix information from the future.']),
    q('Which data do you use to choose hyperparameters?', 1, 'l06-roles',
      ['The test set', 'Then the test score is no longer honest.'],
      ['Validation data or cross-validation on the development set', 'The test set is used once at the end.'],
      ['The training set', 'Training error rewards complexity.']),
    q('Model A: CV MAE 10.4 ± 1.9. Model B: 9.5 ± 0.8. Is B clearly better?', 2, ['l06-cv', 'l05-interval'],
      ['Yes, lower MAE always wins', 'The spread across folds is as large as the gap.'],
      ['No, A is better because its spread is larger', 'A larger spread means less consistency, not better performance.'],
      ['Not clearly: compare fold by fold and consider the simpler model', 'Paired fold-by-fold differences are more informative than overlapping means.']),
  ]},
  17: { checks: [
    q('Why should features usually be scaled before distance-based methods?', 0, 'l10-distance',
      ['Otherwise the feature with the largest units dominates the distance', 'Scaling makes each feature’s contribution a choice, not an accident of units.'],
      ['Scaling improves accuracy by definition', 'Sometimes raw units are what you want; it is a choice.'],
      ['Distances cannot be computed on raw data', 'They can; they just may be dominated by one feature.']),
    q('Which point minimizes the sum of squared distances to a set of points?', 1, 'evaluate',
      ['The median', 'That minimizes absolute distances.'],
      ['Their mean (centroid)', 'This is why k-means updates each center to its cluster’s mean.'],
      ['The point farthest from the others', 'That maximizes, not minimizes.']),
    q('k-means with two different seeds gives different clusters. What does this show?', 2, 'l02-seeds',
      ['A bug', 'Initialization is random; different local optima are expected.'],
      ['The seed is irrelevant', 'The seed controls initialization.'],
      ['Results depend on initialization — record seeds and check stability', 'Stability across seeds is evidence; one run is not.']),
  ]},
  18: { checks: [
    q('What does Av = λv say about v?', 0, 'l03-conditioning',
      ['A only stretches v by λ, without turning it', 'v is an eigenvector; λ is how much it is stretched.'],
      ['v is perpendicular to Av', 'Av points along v.'],
      ['A is the identity', 'Only if λ = 1 for every vector.']),
    q('Two vectors have dot product 0. They are…', 1, 'l03-projection',
      ['parallel', 'Parallel vectors have dot product ±‖u‖‖v‖.'],
      ['orthogonal (perpendicular)', 'Projection and PCA rely on this.'],
      ['equal', 'A non-zero vector’s dot product with itself is positive.']),
    q('After subtracting its mean, a column has mean…', 2, 'l04-expectation',
      ['1', 'That is what dividing by the standard deviation gives for the spread.'],
      ['its original standard deviation', 'Centering moves the data, not its spread.'],
      ['0', 'PCA needs centered data so that directions describe variation, not location.']),
  ]},
  19: { checks: [
    q('With time-ordered data, a fair validation scheme is…', 1, 'l06-splits',
      ['a random shuffle into folds', 'That trains on the future and validates on the past.'],
      ['forward chaining: train on the past, validate on the next block', 'Matches how the model will be used.'],
      ['validating on the training period', 'That measures memory, not forecasting.']),
    q('A feature is “average load over the next hour” when predicting load now. What is it?', 0, 'l06-leakage',
      ['Leakage from the future', 'It will not exist when you make the prediction.'],
      ['A good lag feature', 'Lags look back, not forward.'],
      ['Fine after scaling', 'Scaling does not change when information becomes available.']),
    q('Why compare a forecast with “tomorrow equals today”?', 2, 'l06-baselines',
      ['It is always the best model', 'It is often hard to beat, not always best.'],
      ['It is required for time series', 'It is a sanity check, not a rule.'],
      ['A naive baseline shows whether the model adds anything', 'Beating persistence is the minimum bar.']),
  ]},
  20: { checks: [
    q('What is d/dt (3t − 1)² at t = 1?', 1, 'slopes',
      ['4', 'That is (3·1 − 1)². The question asks for the slope.'],
      ['12', 'Chain rule: 2(3t − 1)·3 = 2·2·3.'],
      ['6', 'Missing the factor from the outer square: 2e·3 with e = 2.']),
    q('A partial derivative ∂L/∂w means…', 0, 'slopes',
      ['the rate L changes as w changes, all other inputs held fixed', 'Backprop computes one of these for every parameter.'],
      ['the total change in L', 'A derivative is a rate, not a change.'],
      ['the value of L at w', 'That is the function value, not its slope.']),
    q('How do you check a gradient formula numerically?', 2, 'l03-gradient',
      ['Compare it to the loss value', 'A slope and a value are different things.'],
      ['Train and see if the loss falls', 'A wrong gradient can still lower the loss for a while.'],
      ['[L(w + ε) − L(w − ε)] / 2ε for each parameter', 'Centered finite differences, one parameter at a time.']),
  ]},
  21: { checks: [
    q('What is the shape of `(32, 10) @ (10, 4)`?', 0, 'l03-matmul',
      ['`(32, 4)`', 'Inner dimensions match and disappear: a batch of 32, 4 outputs each.'],
      ['`(10, 10)`', 'The inner dimensions vanish; the outer ones remain.'],
      ['An error', 'The inner dimensions (10 and 10) match.']),
    q('For logistic regression with cross-entropy, the gradient with respect to the score z is…', 1, 'l08-gradient',
      ['`y − p`', 'The sign is reversed: descent subtracts the gradient.'],
      ['`p − y`', 'Prediction minus target — the same form the softmax output layer has.'],
      ['`p(1 − p)`', 'That is the sigmoid’s own derivative; the loss cancels it.']),
    q('A value feeds into two later operations. Its gradient is…', 2, 'l20-accumulate',
      ['the gradient from the first use', 'Both uses affect the loss.'],
      ['the larger of the two', 'Effects add, not compete.'],
      ['the sum of the gradients from both uses', 'Gradients accumulate over every path.']),
  ]},
  22: { checks: [
    q('The loss grows to infinity after a few gradient steps. The most likely cause is…', 0, 'training',
      ['a learning rate that is too large', 'Each step overshoots more than the last.'],
      ['too few features', 'That underfits; it does not diverge.'],
      ['too much training data', 'Data volume does not cause divergence.']),
    q('A loss surface is a long, narrow valley (large condition number). Plain gradient descent is…', 1, 'l03-conditioning',
      ['fast', 'The stable step is set by the steep direction, so the flat one crawls.'],
      ['slow along the valley and prone to zig-zag', 'Momentum and Adam target exactly this.'],
      ['unaffected', 'The shape determines the stable learning rate and the speed.']),
    q('Training loss falls smoothly; validation loss rises. Is this an optimization failure?', 2, 'l07-fit',
      ['Yes — change the optimizer', 'The optimizer is doing its job on the training loss.'],
      ['Yes — the learning rate is too high', 'That would show in the training loss too.'],
      ['No — it is overfitting, a generalization problem', 'Separate optimization failures from generalization failures.']),
  ]},
  23: { checks: [
    q('A dense layer computes `H = X @ W` with X `(n, d)`. What shape is ∂L/∂W?', 0, 'l21-backprop',
      ['`(d, k)` — the same shape as W', 'A gradient always has the shape of its parameter: `Xᵀ @ ∂L/∂H`.'],
      ['`(n, k)`', 'That is the shape of ∂L/∂H.'],
      ['`(n, d)`', 'That is the shape of ∂L/∂X.']),
    q('Gradients from two backward passes land in the same buffer without being cleared. What happens?', 1, 'l20-accumulate',
      ['The second overwrites the first', 'Frameworks accumulate — which is why `zero_grad()` exists.'],
      ['They add up', 'Gradient accumulation is the rule from Lab 20.'],
      ['The first is kept', 'Nothing is discarded; they sum.']),
    q('Adam keeps, for every parameter…', 2, 'l22-adam',
      ['nothing — it is stateless like plain SGD', 'Adam carries state, which a checkpoint must save.'],
      ['only the last gradient', 'It keeps running averages.'],
      ['running averages of the gradient and of its square', 'This state is why you save the optimizer, not just the model.']),
  ]},
  24: { checks: [
    q('What is the dot product of the patch `[1, 0, 2]` with the kernel `[3, 1, −1]`?', 0, 'arrays',
      ['1', '3 + 0 − 2 = 1. One convolution output is one such dot product.'],
      ['`[3, 0, −2]`', 'That is the elementwise product; add the entries.'],
      ['5', 'Watch the sign: 2 × (−1) = −2.']),
    q('A dense layer maps 100 inputs to 10 outputs with biases. How many parameters?', 1, 'l21-layers',
      ['1000', 'Add one bias per output.'],
      ['1010', '100 × 10 weights plus 10 biases. Convolution shares weights to avoid this growth.'],
      ['110', 'Every input connects to every output: 100 × 10.']),
    q('Several images come from the same patient. How should you split?', 2, 'l06-splits',
      ['Randomly by image', 'Near-identical images end up on both sides.'],
      ['By file name order', 'Arbitrary order still mixes patients.'],
      ['By patient (a grouped split)', 'Every patient on one side only.']),
  ]},
  25: { checks: [
    q('The outputs of a softmax…', 0, 'l21-softmax',
      ['are positive and sum to 1', 'A probability distribution over classes (or over positions, in attention).'],
      ['are between −1 and 1', 'That is tanh.'],
      ['are 0 or 1', 'That is a hard argmax.']),
    q('A one-hot row vector times a matrix W gives…', 1, 'l03-matmul',
      ['the sum of all rows of W', 'Only one entry is 1, so only one row survives.'],
      ['one row of W', 'An embedding layer is exactly this, done as a lookup.'],
      ['a matrix', 'A row vector times a matrix gives a row vector.']),
    q('Many texts are near-duplicates. What is the risk with a random split?', 2, 'l06-splits',
      ['None', 'Duplicates across splits inflate the score.'],
      ['Slower training', 'The concern is evaluation, not speed.'],
      ['Near-copies in train and test inflate the score', 'Deduplicate or group before splitting.']),
  ]},
  26: { checks: [
    q('Q has shape `(5, 8)` and K has shape `(5, 8)`. What is the shape of `Q @ K.T`?', 0, 'l03-matmul',
      ['`(5, 5)`', 'One score for every (query, key) pair.'],
      ['`(8, 8)`', 'That would be `Q.T @ K`.'],
      ['An error', '`K.T` is `(8, 5)`, so the inner dimensions match.']),
    q('What is softmax(`[2, 2]`)?', 1, 'l21-softmax',
      ['`[1, 1]`', 'Softmax outputs sum to 1.'],
      ['`[0.5, 0.5]`', 'Equal scores give equal weights — adding the same constant to every score changes nothing.'],
      ['`[2, 2]`', 'Softmax exponentiates and normalizes.']),
    q('Why do sequence models use a padding mask?', 2, 'l25-padding',
      ['To make sequences longer', 'Padding makes them longer; the mask hides that padding.'],
      ['To speed up training', 'Masks exist for correctness.'],
      ['So padding positions cannot affect real outputs', 'In attention, masked scores are set to −∞ before the softmax.']),
  ]},
  27: { checks: [
    q('Before training a deep model, what should you establish first?', 0, 'l06-baselines',
      ['A simple baseline on the same split', 'Deep learning has to earn its cost against something simpler.'],
      ['The largest model that fits in memory', 'Size is not evidence.'],
      ['The test score', 'The test set comes last.']),
    q('Fine-tuning a pretrained network usually means…', 1, 'l24-practice',
      ['training every layer from random weights', 'That discards the pretrained features.'],
      ['reusing learned features and training a new head, often with a small learning rate', 'Transfer learning.'],
      ['only changing the input size', 'The key idea is reusing learned weights.']),
    q('A new network’s loss will not fall at all. A good first debugging step is…', 2, 'l22-diagnose',
      ['add more data', 'If it cannot learn at all, more data will not help.'],
      ['add more layers', 'More capacity does not fix a pipeline bug.'],
      ['try to overfit one small batch', 'If it cannot memorize eight examples, something is broken.']),
  ]},
  28: { checks: [
    q('A cleaning function calls `rows.pop(0)` on the list it received. What is the risk?', 0, 'l02-functions',
      ['It mutates the caller’s data, so rerunning changes the result', 'Pure functions return new values; they do not edit their inputs.'],
      ['It is slow', 'The problem is correctness, not speed.'],
      ['None, it returns the right value', 'Its side effect makes the pipeline unreproducible.']),
    q('A duration column uses −1 to mean “timed out”. What should happen before computing its mean?', 1, 'l02-look',
      ['Nothing; −1 is a valid number', 'It is a sentinel, not a duration.'],
      ['Treat −1 as missing', 'Sentinels must be decoded before any statistic.'],
      ['Replace it with 0', 'That invents a duration.']),
    q('Why record the random seed with every run?', 2, 'l02-seeds',
      ['It improves accuracy', 'A seed does not make a model better.'],
      ['Libraries require it', 'Nothing forces you; reproducibility does.'],
      ['Without it you cannot regenerate the same split or initialization', 'Seeds are part of the run’s configuration.']),
  ]},
  29: { checks: [
    q('At serving time, how should inputs be standardized?', 0, ['l03-scaling', 'l06-leakage'],
      ['With the training mean and standard deviation saved with the model', 'Preprocessing belongs to the model artifact.'],
      ['With statistics of the incoming batch', 'A single request has no meaningful batch statistics, and results would drift.'],
      ['Not at all', 'The model expects the same inputs it was trained on.']),
    q('What must you record to rebuild a model exactly?', 1, 'l28-versioning',
      ['Just the code', 'Data and configuration change results too.'],
      ['The data version, code version, configuration and environment', 'All four produce the artifact.'],
      ['The final metric', 'A metric describes a model; it cannot rebuild it.']),
    q('A request arrives with a negative file size. What should the service do?', 2, 'l28-validation',
      ['Predict anyway', 'Garbage in, confident garbage out.'],
      ['Crash', 'Fail loudly, yes — but with a clear, handled error.'],
      ['Reject it with a clear validation error', 'The input contract is enforced at the boundary.']),
  ]},
  30: { checks: [
    q('Weekly accuracy moves from 0.91 to 0.89 on 200 labelled cases. Is that proof of a drop?', 0, 'l05-clt',
      ['No: with 200 cases, the standard error is about 0.02, so this is within noise', 'Alert thresholds should respect sampling variation.'],
      ['Yes: any drop is a drop', 'Every estimate fluctuates.'],
      ['Yes, because 0.89 < 0.9', 'A round number is not a threshold.']),
    q('An alert system has TP = 30 and FP = 10. What is its precision?', 1, 'l09-precision',
      ['0.25', 'That is FP / (TP + FP).'],
      ['0.75', '30 / (30 + 10).'],
      ['0.3', 'Precision is a ratio of alerts, not a count.']),
    q('Why keep “golden” input–output test cases for a served model?', 2, 'l29-test',
      ['To improve accuracy', 'Tests do not change the model.'],
      ['To measure latency', 'That is a separate test.'],
      ['To catch changes in the prediction contract', 'The same inputs must give the same outputs after every change.']),
  ]},
  31: { checks: [
    q('Feature X correlates strongly with the outcome. Can you say changing X changes the outcome?', 0, 'l05-causation',
      ['No — correlation can come from confounding or reverse causation', 'Causal claims need design, not just association.'],
      ['Yes, if the correlation is strong', 'Strength does not establish direction.'],
      ['Yes, if the p-value is small', 'Small p-values do not rule out confounding.']),
    q('Two groups have the same TPR and FPR but different base rates. Their precision is…', 1, 'l09-imbalance',
      ['the same', 'Precision depends on prevalence.'],
      ['different', 'The group with the rarer positive class has lower precision.'],
      ['undefined', 'It is defined; it just differs.']),
    q('A subgroup has 12 examples and 75% accuracy. How confident can you be?', 2, 'l05-interval',
      ['Very confident', 'Twelve examples give a very wide interval.'],
      ['It is exactly 75%', 'That is an estimate with large uncertainty.'],
      ['Not very: the interval is wide, so report it', 'Small subgroups need intervals, not bare numbers.']),
  ]},
  32: { checks: [
    q('You evaluate each of 20 candidates on the same test set and ship the best. What is wrong?', 0, 'l06-discipline',
      ['The test set has become a selection set, so its score is optimistic', 'Use validation to choose and a fresh set to confirm.'],
      ['Nothing', 'Repeated selection on one set inflates the winner.'],
      ['20 is too few candidates', 'More candidates make it worse.']),
    q('Monitoring fires a real alert after a release. What is the first safe move?', 1, 'l30-respond',
      ['Retrain immediately on recent data', 'Retraining on possibly bad data can make things worse.'],
      ['Roll back to the last good version, then investigate', 'A tested rollback is part of the release.'],
      ['Silence the alert', 'The alert is doing its job.']),
    q('A model decides which loan applicants get loans, and you only observe outcomes for those accepted. What is the risk?', 2, 'l30-labels',
      ['None', 'The model shapes its own future training data.'],
      ['Labels arrive faster', 'The problem is which labels arrive.'],
      ['A feedback loop: retraining sees only cases the model let through', 'Selective labels bias the next model.']),
  ]},
  33: { checks: [
    q('A feature is recorded after the outcome it helps predict. What is it?', 0, 'l06-leakage',
      ['Leakage — it will not exist at prediction time', 'Check when every feature becomes available.'],
      ['A strong feature', 'Suspiciously strong features are often leaks.'],
      ['Fine for validation only', 'A leak inflates validation too.']),
    q('Your data is time-ordered and the model will forecast next month. How do you evaluate?', 1, 'l19-walkforward',
      ['Random k-fold', 'It lets the model see the future.'],
      ['Walk-forward evaluation over past periods', 'The evaluation should reproduce deployment.'],
      ['Training error', 'Training error is not evidence.']),
    q('What belongs in a model card?', 2, 'l31-card',
      ['Just the accuracy', 'A single number hides intended use and limits.'],
      ['The training code', 'Code goes in the repository.'],
      ['Intended use, data, results by slice, limitations and oversight', 'Written from evidence, for the next person.']),
  ]},
  34: { checks: [
    q('Attention weights come from dot products between a query and keys. A higher dot product means…', 0, 'l26-lookup',
      ['more similar vectors (for similar lengths)', 'Retrieval ranks documents the same way.'],
      ['less similar vectors', 'It is the other way round.'],
      ['nothing about similarity', 'Dot products measure alignment.']),
    q('A search returns 10 documents, 6 of them relevant. What is its precision@10?', 1, 'l09-precision',
      ['0.4', 'That is the irrelevant fraction.'],
      ['0.6', '6 of 10.'],
      ['6', 'Precision is a fraction.']),
    q('You tune prompts and retrieval on the same questions you report. What is wrong?', 2, 'l06-roles',
      ['Nothing', 'Tuning on the reporting set inflates the result.'],
      ['Too few questions', 'Size is a separate issue.'],
      ['The evaluation set was used for tuning', 'Keep a held-out set of questions.']),
  ]},
  35: { checks: [
    q('A user vector `[1, 2]` and an item vector `[3, −1]`. What is their predicted affinity (dot product)?', 0, 'arrays',
      ['1', '3 − 2 = 1. Matrix factorization predicts with exactly this.'],
      ['`[3, −2]`', 'Add the elementwise products.'],
      ['5', 'Check the sign: 2 × (−1) = −2.']),
    q('How should you split interaction logs to evaluate a recommender?', 1, 'l06-splits',
      ['Randomly by interaction', 'That trains on future behavior.'],
      ['By time: train on the past, test on later interactions', 'Matches deployment and avoids future leakage.'],
      ['By item name', 'Arbitrary and leaky.']),
    q('Recommendations shape what users see, which shapes what they click. This is…', 2, 'l32-loops',
      ['random noise', 'It is systematic.'],
      ['a data-quality bug', 'It is a structural property of the system.'],
      ['a feedback loop', 'Logged clicks reflect what the model chose to show.']),
  ]},
  36: { checks: [
    q('Ice-cream sales and drownings rise together. What is the most plausible explanation?', 0, 'l05-causation',
      ['A confounder (hot weather) drives both', 'Adjusting for confounders is the subject of this lab.'],
      ['Ice cream causes drowning', 'Correlation alone does not show causation.'],
      ['Drowning causes ice-cream sales', 'Reverse causation is implausible here.']),
    q('P(A | B) is…', 1, 'l04-conditional',
      ['the same as P(B | A)', 'Conditionals are not symmetric.'],
      ['P(A and B) / P(B)', 'Restrict to the cases where B holds.'],
      ['P(A)·P(B)', 'That is P(A and B) under independence.']),
    q('A 95% interval for an effect is [−0.5, 3.0]. What does this say?', 2, 'l05-interval',
      ['The effect is positive', 'The interval includes zero and negative values.'],
      ['There is no effect', 'It includes large positive effects too.'],
      ['The data are consistent with no effect and with a sizable positive one', 'Report the interval, not only “significant or not”.']),
  ]},
  37: { checks: [
    q('A reward is +10 with probability 0.3 and −1 otherwise. What is its expected value?', 0, 'l04-expectation',
      ['2.3', '0.3 × 10 + 0.7 × (−1) = 3 − 0.7.'],
      ['4.5', 'That is the unweighted average of 10 and −1.'],
      ['3', 'Include the −1 with probability 0.7.']),
    q('p(s′ | s, a) is…', 1, 'l04-conditional',
      ['the probability of taking action a', 'That is the policy π(a | s).'],
      ['the probability of the next state s′ given the current state and action', 'The environment’s model.'],
      ['a reward', 'Rewards come from p(s′, r | s, a).']),
    q('Two training runs with different seeds give different returns. What should you report?', 2, 'l02-seeds',
      ['The best run', 'Cherry-picking hides variance.'],
      ['The first run', 'One seed is an anecdote.'],
      ['Results over several seeds', 'RL is especially seed-sensitive.']),
  ]},
  38: { checks: [
    q('A paper reports accuracy 0.84 against a baseline of 0.83, from one run each. What is your first question?', 0, 'l05-interval',
      ['How much does the result vary across seeds or resamples?', 'Without variation, a 0.01 gap is uninterpretable.'],
      ['Which library they used', 'Useful, but secondary.'],
      ['None — it is published', 'Publication is not replication.']),
    q('The authors tuned hyperparameters on the test set. What does that do to the reported score?', 1, 'l06-discipline',
      ['Nothing', 'Selection on the test set inflates it.'],
      ['Makes it optimistic', 'The winner’s curse.'],
      ['Makes it pessimistic', 'Selection pushes the score up.']),
    q('To reproduce a result exactly you need…', 2, 'l02-seeds',
      ['only the final model', 'Replication means regenerating it.'],
      ['only the code', 'Data, seeds and configuration change results.'],
      ['code, data, configuration and seeds', 'Everything that determines the run.']),
  ]},
  39: { checks: [
    q('The Bernoulli log-likelihood of one observation is…', 0, 'l05-likelihood',
      ['`y log p + (1 − y) log(1 − p)`', 'Its negative average is binary cross-entropy.'],
      ['`(y − p)²`', 'That is squared error.'],
      ['`p^y`', 'Missing the (1 − p)^(1−y) term.']),
    q('The logistic-regression gradient is `Xᵀ(p − y)/n`. What is its shape for X `(n, d)`?', 1, 'l08-gradient',
      ['`(n,)`', 'That is p − y.'],
      ['`(d,)`', 'One entry per weight.'],
      ['`(n, d)`', 'Xᵀ sums over rows.']),
    q('The eigenvalues of the Hessian describe…', 2, 'l03-conditioning',
      ['the loss value', 'They are second derivatives.'],
      ['the learning rate', 'They limit it, but they are not it.'],
      ['the curvature of the loss along its principal directions', 'Newton’s method divides by this curvature.']),
  ]},
  40: { checks: [
    q('Bayes’ rule for classes: P(y | x) is proportional to…', 0, 'l04-bayes',
      ['P(x | y)·P(y)', 'Class-conditional density times prior — the generative recipe.'],
      ['P(y | x)·P(x)', 'That is circular.'],
      ['P(x)·P(y)', 'That assumes x and y are independent.']),
    q('What does a covariance matrix hold?', 1, 'l18-centering',
      ['The means of each feature', 'Means are a vector, not a matrix.'],
      ['Variances on the diagonal and covariances off it', 'Its shape sets the shape of each Gaussian.'],
      ['Correlations only', 'Correlations are covariances rescaled.']),
    q('Logistic regression’s decision boundary w·x + b = 0 is…', 2, 'l08-boundary',
      ['a circle', 'Only with a nonlinear feature map.'],
      ['always through the origin', 'b shifts it.'],
      ['a line (a hyperplane)', 'Shared-covariance GDA gives a boundary of the same form.']),
  ]},
  41: { checks: [
    q('Prior 1%, sensitivity 0.9, false alarms 5%. Is P(fault | alarm) close to 0.9?', 1, 'l04-bayes',
      ['Yes', 'That confuses P(alarm | fault) with P(fault | alarm).'],
      ['No, it is about 0.15', 'The prior matters — that is Bayesian updating.'],
      ['No, it is 0.01', 'The alarm raises it above the prior.']),
    q('The maximum-likelihood estimate of p from 7 successes in 10 trials is…', 0, 'l05-likelihood',
      ['0.7', 'A prior pulls this toward its own mean.'],
      ['0.5', 'That ignores the data.'],
      ['uncertain until a prior is chosen', 'MLE needs no prior.']),
    q('Ridge regression adds λ‖w‖² to the loss. Its effect on weights is…', 2, 'l07-ridge',
      ['to set some exactly to zero', 'That is lasso.'],
      ['to enlarge them', 'The penalty shrinks them.'],
      ['to shrink them toward zero', 'Equivalent to a Gaussian prior (MAP).']),
  ]},
  42: { checks: [
    q('A kernel k(x, x′) can be read as…', 0, 'l15-kernel',
      ['a dot product in a feature space', 'In a GP it becomes the covariance between function values.'],
      ['a distance that must be large for similar points', 'A kernel is large for similar points.'],
      ['a loss function', 'It measures similarity.']),
    q('Bayesian linear regression’s predictive uncertainty far from the data is…', 1, 'l41-blr',
      ['smaller', 'The posterior on the slope makes it grow away from the data.'],
      ['larger', 'GPs show the same behavior.'],
      ['constant', 'It varies with x.']),
    q('The marginal likelihood (evidence) is used to…', 2, 'l41-evidence',
      ['fit the weights', 'Weights are integrated out.'],
      ['measure test accuracy', 'It uses training data only.'],
      ['compare models or choose hyperparameters', 'GP length scales are tuned this way.']),
  ]},
  43: { checks: [
    q('In k-means, after assigning points, each centroid is updated to…', 0, 'l17-kmeans',
      ['the mean of its assigned points', 'EM’s M-step does the same with soft weights.'],
      ['a random point', 'That is initialization.'],
      ['the farthest point', 'That would increase the loss.']),
    q('Maximizing a likelihood means…', 1, 'l05-likelihood',
      ['making parameters as small as possible', 'That is a penalty.'],
      ['choosing parameters that make the observed data most probable', 'EM does this with hidden variables.'],
      ['minimizing the number of parameters', 'That is model selection.']),
    q('Gaussian discriminant analysis estimates each class’s mean and covariance from…', 2, 'l40-fit',
      ['all data, ignoring labels', 'Labels choose which rows belong to each class.'],
      ['the test set', 'Never.'],
      ['the labelled rows of that class', 'Without labels, EM estimates these with soft assignments.']),
  ]},
  44: { checks: [
    q('A Monte Carlo average from n samples has standard error proportional to…', 0, 'l04-verify',
      ['1/√n', 'Four times the samples halve the error.'],
      ['1/n', 'That is too optimistic.'],
      ['n', 'Error shrinks as n grows.']),
    q('A posterior is…', 1, 'l41-update',
      ['the prior with the data ignored', 'That is still the prior.'],
      ['proportional to likelihood × prior', 'Sampling methods target this when it has no closed form.'],
      ['the likelihood alone', 'The prior is part of it.']),
    q('E[f(X)] can be estimated by…', 2, 'l04-expectation',
      ['f(E[X])', 'Only for linear f.'],
      ['the largest f(x)', 'An expectation is an average.'],
      ['averaging f over samples of X', 'The Monte Carlo principle.']),
  ]},
  45: { checks: [
    q('P(A, B) can always be factored as…', 0, 'l04-conditional',
      ['P(A | B)·P(B)', 'The chain rule of probability — graphical models are built from it.'],
      ['P(A)·P(B)', 'Only when A and B are independent.'],
      ['P(A) + P(B)', 'That is not a joint probability.']),
    q('Naive Bayes assumes the features are…', 1, 'l11-bayes',
      ['independent of the label', 'Then they would be useless.'],
      ['conditionally independent given the label', 'A simple graphical model.'],
      ['correlated', 'The “naive” part is ignoring correlation.']),
    q('Bayes’ rule turns P(evidence | cause) into…', 2, 'l04-bayes',
      ['P(evidence)', 'That is the normalizer.'],
      ['P(cause)', 'That is the prior.'],
      ['P(cause | evidence)', 'Inference in graphical models generalizes this.']),
  ]},
  46: { checks: [
    q('Binary cross-entropy for a positive example with p = 0.5 is…', 0, 'l08-loss',
      ['ln 2 ≈ 0.693', 'One bit, in nats. Cross-entropy is an information quantity.'],
      ['0.5', 'The loss is −log p.'],
      ['0', 'Only a confident correct prediction approaches 0.']),
    q('Expected value E[g(X)] is…', 1, 'l04-expectation',
      ['g(most likely x)', 'That is the mode.'],
      ['Σ P(x)·g(x)', 'Entropy is E[−log P(X)].'],
      ['the largest g(x)', 'An expectation is a weighted average.']),
    q('Summing log-probabilities is equivalent to…', 2, 'l11-logs',
      ['summing probabilities', 'log(ab) is not a + b.'],
      ['taking the maximum', 'It is a product.'],
      ['multiplying the probabilities', 'Information adds where probabilities multiply.']),
  ]},
  47: { checks: [
    q('Testing 20 useless models at the 5% level, the chance at least one looks good is about…', 0, 'l06-discipline',
      ['64%', '1 − 0.95²⁰. Union bounds in learning theory control exactly this.'],
      ['5%', 'That is for one model.'],
      ['100%', 'High, but not certain.']),
    q('The standard error of a mean shrinks like…', 1, 'l05-clt',
      ['1/n', 'Too fast.'],
      ['1/√n', 'Concentration bounds give the same rate.'],
      ['it does not shrink', 'More data reduces it.']),
    q('Expected error = bias² + variance + noise. More model complexity usually…', 2, 'l07-bias-variance',
      ['lowers both bias and variance', 'Usually there is a trade-off.'],
      ['raises bias', 'Flexibility lowers bias.'],
      ['lowers bias and raises variance', 'Capacity bounds formalize this.']),
  ]},
  48: { checks: [
    q('At the least-squares solution, Xᵀ(y − Xw) = 0. This says…', 0, 'l03-projection',
      ['the residual is orthogonal to every column of X', 'A first-order optimality condition — KKT generalizes it.'],
      ['the residual is zero', 'Only with a perfect fit.'],
      ['the weights are zero', 'It constrains the residual, not w.']),
    q('A hard-margin SVM minimizes ‖w‖² subject to…', 1, 'l15-hardmargin',
      ['‖w‖ = 1', 'The constraints are on the data.'],
      ['yᵢ(w·xᵢ + b) ≥ 1 for every i', 'A constrained convex problem — the subject of duality.'],
      ['no constraints', 'That gives w = 0.']),
    q('Soft thresholding S(3, 1) is…', 2, 'l07-lasso',
      ['3', 'Soft thresholding shrinks.'],
      ['1', 'It subtracts the threshold.'],
      ['2', 'sign(3)·max(3 − 1, 0). This is the proximal operator of L1.']),
  ]},
  49: { checks: [
    q('The degree-2 polynomial kernel (x·x′)² for x = (1, 2), x′ = (3, 1) is…', 0, 'l15-kernel',
      ['25', '(3 + 2)² = 25, a dot product in feature space without building the features.'],
      ['5', 'That is x·x′ before squaring.'],
      ['10', 'Square the dot product.']),
    q('Ridge regression’s closed form involves inverting…', 1, 'l07-ridge',
      ['XᵀX', 'Ridge adds λI to it.'],
      ['XᵀX + nλI', 'Kernel ridge swaps this for a kernel matrix.'],
      ['X', 'X is generally not square.']),
    q('PCA projects data onto…', 2, 'l18-projection',
      ['random directions', 'The directions are chosen to keep variance.'],
      ['the original axes', 'It rotates to new axes.'],
      ['the top eigenvectors of the covariance', 'Kernel PCA does this in feature space.']),
  ]},
  50: { checks: [
    q('An arm pays 1 with probability 0.3 and 0 otherwise. What is its expected reward?', 0, 'l04-expectation',
      ['0.3', 'Bandits estimate this for each arm.'],
      ['1', 'That is its best case.'],
      ['0.5', 'That ignores the probabilities.']),
    q('After 10 pulls with average 0.6, how confident are you in the arm’s mean?', 1, 'l05-interval',
      ['Certain', 'Ten pulls leave wide uncertainty.'],
      ['Not very — the interval is wide', 'Confidence bounds drive exploration.'],
      ['Totally uncertain', 'Ten pulls tell you something.']),
    q('The logistic-regression update moves w by…', 2, 'l08-gradient',
      ['a random amount', 'The step is set by the error.'],
      ['the input alone', 'It is scaled by the error.'],
      ['a step proportional to (y − p)·x', 'The perceptron uses the same error-times-input form.']),
  ]},
  51: { checks: [
    q('PCA finds the direction that…', 0, 'l18-maxvar',
      ['maximizes projected variance', 'Linear — this lab goes beyond it.'],
      ['minimizes variance', 'That would keep the least information.'],
      ['separates classes best', 'PCA ignores labels.']),
    q('Distances on unscaled features are dominated by…', 1, 'l10-distance',
      ['the feature with the smallest range', 'The largest differences dominate.'],
      ['the feature with the largest range', 'Neighbour-based embeddings inherit this.'],
      ['no feature', 'Units matter.']),
    q('Independence of A and B means…', 2, 'l04-conditional',
      ['they are uncorrelated only', 'Uncorrelated is weaker than independent.'],
      ['P(A | B) = P(B)', 'It is P(A | B) = P(A).'],
      ['P(A, B) = P(A)·P(B)', 'ICA seeks components that are independent in this sense.']),
  ]},
  52: { checks: [
    q('Adding λ‖w‖² to a loss…', 0, 'l07-ridge',
      ['shrinks weights, trading training fit for stability', 'Weight decay in deep learning.'],
      ['always lowers training error', 'It raises training error.'],
      ['removes features', 'That is L1.']),
    q('Training loss is still falling but validation loss has been rising for 20 epochs. What is happening?', 1, 'l21-train',
      ['Underfitting', 'Training error is low.'],
      ['Overfitting', 'The regularizers in this lab target this.'],
      ['A learning-rate bug', 'That would show in the training loss.']),
    q('How do you tell an optimization problem from a generalization problem?', 2, 'l22-diagnose',
      ['Look at validation loss only', 'You need both curves.'],
      ['Change the model size', 'That is a response, not a diagnosis.'],
      ['Compare training and validation curves', 'Training stuck: optimization. Gap growing: generalization.']),
  ]},
  53: { checks: [
    q('Projecting onto the top k principal components and back gives…', 0, 'l18-projection',
      ['the best rank-k linear reconstruction', 'A linear autoencoder learns the same subspace.'],
      ['the original data exactly', 'Only with k equal to the full dimension.'],
      ['random noise', 'It keeps the main structure.']),
    q('KL(q ‖ p) is…', 1, 'l46-kl',
      ['symmetric', 'KL(q ‖ p) ≠ KL(p ‖ q) in general.'],
      ['non-negative, zero only when q = p', 'The VAE loss uses it as a regularizer.'],
      ['a distance satisfying the triangle inequality', 'It is not a metric.']),
    q('Backpropagation through a network computes…', 2, 'l21-backprop',
      ['only the output gradient', 'It goes back through every layer.'],
      ['a numerical approximation', 'It is exact (up to floating point).'],
      ['the gradient of the loss for every parameter via the chain rule', 'The reparameterization trick lets it pass through sampling.']),
  ]},
  54: { checks: [
    q('A VAE’s loss combines…', 0, 'l53-vae',
      ['reconstruction error and a KL term', 'The ELBO.'],
      ['only reconstruction error', 'That is a plain autoencoder.'],
      ['a discriminator’s loss', 'That is a GAN.']),
    q('KL(p ‖ q) = 0 exactly when…', 1, 'l46-kl',
      ['p and q have the same mean', 'Matching means is not enough.'],
      ['p = q', 'Generative models aim to match these distributions.'],
      ['q is uniform', 'Not in general.']),
    q('Adam adapts the step size per parameter using…', 2, 'l22-adam',
      ['the loss value', 'It uses gradient statistics.'],
      ['a fixed schedule', 'Schedules are separate.'],
      ['running averages of the gradient and its square', 'GANs are often trained with it.']),
  ]},
  55: { checks: [
    q('Scaled dot-product attention divides scores by √d because…', 0, 'l26-scaled',
      ['dot products grow with dimension and saturate the softmax', 'Scaling keeps gradients usable.'],
      ['to normalize the output', 'The softmax normalizes.'],
      ['it is required for masking', 'Masking is separate.']),
    q('Entropy is highest when a distribution is…', 1, 'l46-entropy',
      ['concentrated on one outcome', 'Then it is zero.'],
      ['uniform', 'Perplexity is the exponential of the cross-entropy.'],
      ['Gaussian', 'For discrete outcomes the uniform maximizes it.']),
    q('Tokenization turns text into…', 2, 'l25-tokens',
      ['probabilities', 'Probabilities come later.'],
      ['embeddings directly', 'Embeddings are looked up from ids.'],
      ['a sequence of integer ids', 'Each id indexes an embedding row.']),
  ]},
  56: { checks: [
    q('With few labels, which set should never be used for model selection?', 0, 'l06-roles',
      ['The test set', 'Scarce labels make this temptation stronger.'],
      ['The validation set', 'Selection is its job.'],
      ['The unlabelled pool', 'It cannot measure accuracy.']),
    q('Clustering unlabelled data finds…', 1, 'l17-kmeans',
      ['the true classes', 'Clusters are not classes.'],
      ['groups by distance, which may or may not match labels', 'Semi-supervised methods lean on this assumption.'],
      ['nothing useful', 'Structure can help.']),
    q('A model says 0.9 on cases that are right 60% of the time. It is…', 2, 'l09-calibration',
      ['well calibrated', 'Then 90% would be right.'],
      ['under-confident', 'It claims more than it delivers.'],
      ['over-confident', 'Pseudo-labelling on over-confident predictions amplifies errors.']),
  ]},
  57: { checks: [
    q('An adjacency matrix A `(n, n)` times node features H `(n, d)` gives…', 0, 'l03-matmul',
      ['`(n, d)`: each row sums its neighbours’ features', 'Message passing in one line.'],
      ['`(d, d)`', 'That would be Hᵀ H.'],
      ['an error', 'Inner dimensions match.']),
    q('A dense layer maps d inputs to k outputs. It has how many weights (no bias)?', 1, 'l21-layers',
      ['d + k', 'Each input connects to each output.'],
      ['d × k', 'GNN layers share this matrix across all nodes.'],
      ['d', 'There are k outputs.']),
    q('Why is a random node split risky on a graph?', 2, 'l06-splits',
      ['It is not', 'Neighbours carry information across the split.'],
      ['It is slow', 'The issue is leakage.'],
      ['Test nodes’ neighbours in training leak information', 'Graphs need grouped or temporal splits.']),
  ]},
  58: { checks: [
    q('The Q-learning target for a step is…', 0, 'l37-qlearning',
      ['R + γ·max over a′ of Q(s′, a′)', 'Policy gradients replace this value target with sampled returns.'],
      ['R only', 'That ignores the future.'],
      ['Q(s, a)', 'That is the current estimate.']),
    q('The expected value of a random return G is estimated by…', 1, 'l04-expectation',
      ['its largest sample', 'Expectation averages.'],
      ['the average of sampled returns', 'REINFORCE averages over episodes.'],
      ['G squared', 'That is a second moment.']),
    q('d/dθ log p(θ) equals…', 2, 'l20-local',
      ['log p′(θ)', 'The log is outside.'],
      ['p′(θ)·p(θ)', 'The chain rule divides by p.'],
      ['p′(θ)/p(θ)', 'The log-derivative trick behind REINFORCE.']),
  ]},
  59: { checks: [
    q('Feature X has a large weight. Does changing X change the outcome?', 0, 'l05-causation',
      ['Not necessarily — a model’s weight is an association', 'Explanations describe the model, not the world.'],
      ['Yes', 'That is a causal claim the model cannot support.'],
      ['Only if the model is accurate', 'Accuracy does not make weights causal.']),
    q('Two features are nearly collinear. Their individual weights are…', 1, 'l03-rank',
      ['very reliable', 'Credit can swing between them.'],
      ['unstable, while their combined effect is stable', 'Importance methods inherit this.'],
      ['zero', 'They can be large and opposite.']),
    q('A regression tree’s impurity-based importance measures…', 2, 'l12-regression',
      ['the causal effect of a feature', 'It is a training-data statistic.'],
      ['the feature’s correlation with the target', 'It depends on the splits chosen.'],
      ['how much the splits on a feature reduced training error', 'It can be biased toward features with many values.']),
  ]},
  60: { checks: [
    q('What does a 95% confidence interval procedure guarantee?', 0, 'l05-interval',
      ['About 95% of intervals it produces cover the true value', 'A statement about the procedure. Conformal prediction gives a similar guarantee.'],
      ['The value is in this interval with 95% probability', 'The common misreading.'],
      ['95% of data points are inside', 'That is a prediction interval.']),
    q('Calibration asks whether…', 1, 'l09-calibration',
      ['accuracy is high', 'A model can be accurate and badly calibrated.'],
      ['predicted probabilities match observed frequencies', 'Conformal sets need a held-out calibration set.'],
      ['the loss is low', 'Low loss does not guarantee calibration.']),
    q('Conformal prediction needs a calibration set that is…', 2, 'l06-roles',
      ['the training set', 'Scores on training data are optimistic.'],
      ['the test set', 'The test set must stay untouched.'],
      ['held out from training', 'Its scores stand in for new data.']),
  ]},
  61: { checks: [
    q('Training on 2023 data and testing on a 2025 sample from a new region measures…', 0, 'l06-splits',
      ['performance under distribution shift', 'The split should reflect the shift you expect.'],
      ['ordinary generalization', 'Both time and population changed.'],
      ['training error', 'It is a held-out test.']),
    q('For logistic regression, the gradient of the loss with respect to the input x is proportional to…', 1, 'l08-gradient',
      ['x', 'It depends on the weights.'],
      ['(p − y)·w', 'Adversarial examples move x along this direction.'],
      ['zero', 'The loss depends on x.']),
    q('Under shift, a model’s predicted probabilities often become…', 2, 'l09-calibration',
      ['better calibrated', 'Rarely.'],
      ['exactly the same', 'Inputs changed.'],
      ['miscalibrated', 'Monitor calibration, not only accuracy.']),
  ]},
}
