// Ordered curriculum. Availability comes from the lab registry (labs/index.js).
// Each lab ends with observable evidence rather than a “read = mastered” badge.
export const phases = [
  { title: 'Start from first principles', goal: 'Connect measurements, mathematics, code, and honest evaluation.', labs: [
    ['Foundations & your first learning algorithm', 'Arrays, shapes, weights, dot products, derivatives, chain rule, regression and batch gradient descent.', 'Build a NumPy regression model and inspect every update.', 'Explain each parameter, derive the gradient, diagnose divergence, and compare against a mean baseline.'],
    ['Data handling & reproducible experiments', 'Python functions, NumPy indexing and broadcasting, pandas, missing values, plots, seeds and basic tests.', 'Turn a small CSV into a documented, repeatable experiment.', 'Reproduce a result from a clean run and explain every data-cleaning decision.'],
    ['Vectors, matrices & multiple inputs', 'Features versus observations, matrix multiplication, projections, rank, least squares and training-only scaling.', 'Extend regression to several features and compare gradient descent with a numerical least-squares solver.', 'Track every array shape and explain what correlated or constant inputs do to the solution.'],
  ]},
  { title: 'Learn to reason about evidence', goal: 'Understand uncertainty and decide whether a model is useful.', labs: [
    ['Probability through simulation', 'Random variables, distributions, expectation, variance, conditional probability, independence and Bayes’ rule.', 'Simulate a noisy sensor and update a probability after observing evidence.', 'Distinguish a conditional probability from its reverse and verify calculations by simulation.'],
    ['Statistics & estimation', 'Samples versus populations, estimators, sampling variation, bootstrap intervals, likelihood and correlation versus causation.', 'Repeat an experiment on resampled datasets and quantify uncertainty.', 'Explain what an interval means and why a single score is insufficient evidence.'],
    ['Evaluation without leakage', 'Train/validation/test roles, cross-validation, grouped and temporal splits, baselines, preprocessing pipelines and test-set discipline.', 'Audit a deliberately leaky experiment, then repair it.', 'Choose a split that matches future use and show why the original score was misleading.'],
    ['Overfitting, regularization & learning curves', 'Polynomial features, bias/variance, L1/L2 penalties, model complexity and sample size.', 'Fit increasingly flexible models and compare training and validation curves.', 'Diagnose underfitting versus overfitting and justify a model choice without tuning on the test set.'],
  ]},
  { title: 'Build classical machine learning', goal: 'Derive core methods and choose them based on evidence.', labs: [
    ['Logistic regression from scratch', 'Linear scores, sigmoid, log odds, Bernoulli likelihood, binary cross-entropy and gradients.', 'Implement a probabilistic classifier and draw its decision boundary.', 'Derive the objective, check gradients, and explain why a probability is not yet a decision.'],
    ['Classification decisions & metrics', 'Confusion matrices, precision/recall, ROC/PR curves, imbalance, thresholds, calibration and error costs.', 'Choose a threshold for a simulated alert system.', 'Defend a threshold using costs and explain when accuracy is misleading.'],
    ['Nearest neighbors & distance', 'Distances, feature scales, local decision rules and the curse of dimensionality.', 'Build k-NN and inspect which examples determine each prediction.', 'Explain how scaling and k alter predictions, runtime and generalization.'],
    ['Naive Bayes & text features', 'Conditional independence, class priors, counts, smoothing, log probabilities and bag-of-words representations.', 'Build a small text classifier using training-only vocabulary fitting.', 'Trace a prediction numerically and identify where the independence assumption fails.'],
    ['Decision trees', 'Recursive splitting, thresholds, impurity, information gain, depth and pruning.', 'Build and visualize a small tree from scratch.', 'Calculate a split score, explain a prediction path and diagnose an overfit tree.'],
    ['Bagging & random forests', 'Bootstrap samples, feature subsampling, ensemble variance and out-of-bag estimates.', 'Combine trees and compare their errors and correlations.', 'Explain why an ensemble may generalize better and where its evaluation can fail.'],
    ['Boosting', 'Sequential error correction, residual fitting, shrinkage, tree depth and early stopping.', 'Build a small gradient-boosting regressor before using a library.', 'Explain what each new learner fits and diagnose overfitting through validation.'],
    ['Margins & support vector machines', 'Hyperplanes, margins, hinge loss, regularization and the kernel idea.', 'Explore maximum-margin classification on small 2D datasets.', 'Explain support vectors and compare a linear margin model with logistic regression.'],
    ['Capstone: a useful tabular model', 'Feature engineering, systematic comparisons, bounded tuning, error analysis and reproducible reporting.', 'Predict processing time, output size or another measured project outcome.', 'Beat a justified baseline on an untouched test set—or document why the model should be rejected.'],
  ]},
  { title: 'Understand geometry and hidden structure', goal: 'Find structure without confusing it with ground truth.', labs: [
    ['Clustering & anomaly detection', 'k-means, initialization, centroid updates, density-based clustering and anomaly scores.', 'Cluster synthetic and real observations; inspect cases where distance-based methods fail.', 'Explain why a cluster is not automatically a real category and evaluate stability.'],
    ['Eigenvectors, SVD & PCA', 'Bases, projections, covariance, eigenvectors, singular values, explained variance and reconstruction error.', 'Implement PCA and compress a small dataset.', 'Derive the projection, explain centering and compare reconstruction against retained variance.'],
    ['Time-dependent data', 'Lags, rolling features, autocorrelation, forecasting horizons, walk-forward evaluation and temporal leakage.', 'Forecast a measured resource usage series with a simple baseline and lagged model.', 'Ensure every feature exists at prediction time and compare against a seasonal or persistence baseline.'],
  ]},
  { title: 'Derive and implement neural networks', goal: 'Understand the computation before relying on automatic differentiation.', labs: [
    ['Computation graphs & backpropagation', 'Local derivatives, chain rule through branches, gradient accumulation and numerical checking.', 'Build a tiny scalar automatic-differentiation engine.', 'Trace forward values and backward derivatives by hand, including shared inputs.'],
    ['A neural network in NumPy', 'Dense layers, nonlinear activations, matrix shapes, softmax, stable cross-entropy and training loops.', 'Train a small network on XOR and synthetic classification data.', 'Implement forward and backward passes and check every layer’s gradients.'],
    ['Optimization & training failures', 'Batch versus stochastic gradients, mini-batches, momentum, Adam, schedules, initialization and gradient scale.', 'Compare optimizers on controlled landscapes and neural networks.', 'Explain optimizer state and distinguish numerical bugs from optimization or generalization failures.'],
    ['PyTorch with understanding', 'Tensors, autograd, modules, data loaders, device placement, train/eval modes and checkpointing.', 'Reproduce the NumPy model in PyTorch.', 'Match a forward pass and gradients, resume training and explain what the framework handles.'],
    ['Convolution & computer vision', 'Kernels, stride, padding, feature maps, receptive fields, augmentation and transfer learning.', 'Implement a convolution, then train or adapt a small image classifier.', 'Trace which pixels affect an output and evaluate without image-source leakage.'],
    ['Embeddings & sequence models', 'Tokens, embedding tables, sequence order, recurrent state, padding and masking.', 'Build a small sequence classifier with a baseline.', 'Explain representation shapes and identify shortcut learning or split contamination.'],
    ['Attention & a tiny transformer', 'Queries, keys, values, scaled dot-product attention, masking, positional information, residuals and normalization.', 'Implement attention and assemble a small transformer.', 'Trace attention dimensions and explain what attention weights do and do not establish.'],
    ['Capstone: a deep-learning investigation', 'Dataset suitability, transfer learning, ablations, compute budgets and qualitative error analysis.', 'Solve a modest image or text problem and compare with a simpler model.', 'Show which changes help, report failures, and justify the computational cost.'],
  ]},
  { title: 'Engineer reliable ML systems', goal: 'Turn an experiment into maintainable software with measurable behavior.', labs: [
    ['Data contracts & reproducible training', 'Schema checks, data quality, versioned datasets, configurations, environments and experiment tracking.', 'Package a repeatable training pipeline with validated inputs.', 'Rebuild a model from recorded data/code/configuration versions and catch bad inputs early.'],
    ['Serving & integration', 'Batch versus online prediction, preprocessing parity, model serialization, APIs, latency and resource limits.', 'Integrate a trained model into an everyday application.', 'Test the full prediction contract and compare served predictions with offline results.'],
    ['Testing, monitoring & drift', 'Unit/integration tests, data and prediction monitoring, delayed labels, drift, alerts and rollback.', 'Introduce a controlled data shift into a deployed demo.', 'Detect a meaningful failure, separate drift from proven performance loss, and recover safely.'],
    ['Responsible decisions & communication', 'Privacy, dataset permissions, subgroup evaluation, explainability limits, human review and model documentation.', 'Write a model card and audit one model’s failure cases.', 'State intended use, limitations and who may be affected; avoid unsupported fairness or causal claims.'],
    ['Retraining & delivery', 'CI checks, release artifacts, promotion criteria, staged deployment, feedback loops and retraining triggers.', 'Ship a versioned update with a rollback path.', 'Demonstrate that an update improves the chosen criteria without silently changing the prediction contract.'],
    ['Final capstone: an end-to-end ML product', 'Problem framing, data collection, baselines, modeling, deployment, monitoring and maintenance.', 'Build one useful application using your own measured project data.', 'Deliver reproducible evidence, tested software, a working demo, a model card and an honest maintenance plan.'],
  ]},
  { title: 'Optional specializations after the core', goal: 'Choose a branch because your project needs it; these are not required for every ML engineer.', optional: true, labs: [
    ['Retrieval & language-model applications', 'Embeddings for retrieval, ranking, retrieval-augmented generation, evaluation sets, grounding and operational costs.', 'Build a small document-search assistant with a measured retrieval baseline.', 'Evaluate retrieval and answer quality separately, with failure cases and data permissions documented.'],
    ['Recommender systems', 'Implicit/explicit feedback, collaborative filtering, ranking and offline-versus-online evaluation.', 'Build a recommendation prototype.', 'Avoid user/time leakage and explain cold-start and feedback-loop limitations.'],
    ['Causal inference & experimentation', 'Confounding, interventions, randomized experiments and assumptions behind causal estimates.', 'Design an experiment for a product decision.', 'Distinguish predicting an outcome from estimating the effect of changing an input.'],
    ['Reinforcement learning', 'States, actions, rewards, policies, value functions and exploration.', 'Train a small agent in a controlled simulator.', 'Compare with a simple policy and diagnose reward misspecification without confusing it with supervised learning.'],
    ['Research replication & advanced modeling', 'Reading papers, reproducing baselines, ablations, uncertainty and choosing deeper work such as generative modeling.', 'Reproduce a small published result within a stated compute budget.', 'Separate replicated findings, deviations and unsupported conclusions.'],
  ]},
  { title: 'Advanced I · Probabilistic machine learning', goal: 'Model uncertainty explicitly: likelihoods, priors, latent variables and inference.', advanced: true, labs: [
    ['Generalized linear models & Newton’s method', 'Exponential families, link functions, softmax and Poisson regression, Newton’s method and IRLS, locally weighted regression.', 'Fit multiclass and count models with Newton’s method and compare with gradient descent.', 'Derive a GLM’s gradient and Hessian from its likelihood and explain quadratic convergence.'],
    ['Generative classifiers: GDA, LDA & QDA', 'Class-conditional Gaussians, shared versus separate covariances, Bayes-optimal boundaries, generative versus discriminative learning.', 'Fit Gaussian discriminant analysis and compare it with logistic regression as data grows.', 'Derive why shared covariances give a linear boundary and when the generative model wins.'],
    ['Bayesian inference & priors', 'Priors, posteriors, conjugacy, MAP as regularization, Bayesian linear regression, posterior predictive and marginal likelihood.', 'Update beliefs about a parameter and a regression line as data arrive.', 'Show that ridge and lasso are MAP estimates and use the evidence to compare models.'],
    ['Gaussian processes', 'Kernels as covariances, GP priors, exact regression, predictive uncertainty and hyperparameters by marginal likelihood.', 'Fit a GP to noisy measurements and tune its length scale.', 'Explain every term of the predictive mean and variance and why uncertainty grows away from data.'],
    ['Mixture models & the EM algorithm', 'Latent variables, Gaussian mixtures, responsibilities, EM as coordinate ascent on a lower bound, soft k-means.', 'Implement EM for a Gaussian mixture and watch the likelihood rise.', 'Derive the E and M steps and diagnose local optima and collapsing components.'],
    ['Sampling & approximate inference', 'Monte Carlo, importance sampling, Metropolis–Hastings, Gibbs sampling, diagnostics, variational inference and the ELBO.', 'Sample a posterior with MCMC and approximate it with variational inference.', 'Judge convergence and explain the bias of each approximation.'],
    ['Graphical models & hidden Markov models', 'Bayesian networks, conditional independence, d-separation, HMMs, forward algorithm, Viterbi and Baum–Welch.', 'Decode hidden states from noisy observations.', 'Read independence from a graph and derive the forward recursion.'],
    ['Information theory for ML', 'Entropy, cross-entropy, KL divergence, mutual information, coding and why log-loss is the natural loss.', 'Measure information in data and compare distributions.', 'Connect maximum likelihood, cross-entropy and KL divergence exactly.'],
  ]},
  { title: 'Advanced II · Theory & optimization', goal: 'Know why learning works, when it provably fails, and how the solvers behind it work.', advanced: true, labs: [
    ['Learning theory & generalization', 'PAC learning, finite-class bounds, VC dimension, bias–complexity, uniform convergence, double descent.', 'Measure the gap between training and test error as capacity and data change.', 'Compute a generalization bound and explain what it does and does not promise.'],
    ['Convex optimization & duality', 'Convex sets and functions, Lagrangians, KKT conditions, the SVM dual, SMO, proximal gradient and Newton methods.', 'Solve the SVM dual and a lasso with proximal gradient.', 'Derive the dual of the SVM and read support vectors from the KKT conditions.'],
    ['Kernel methods', 'Feature maps, positive-definite kernels, the representer theorem, kernel ridge regression, kernel PCA and kernel choice.', 'Fit kernel ridge regression and kernel PCA from the Gram matrix.', 'Prove the representer theorem’s consequence and pick a kernel with validation.'],
    ['Online learning & bandits', 'The perceptron and its mistake bound, regret, multiplicative weights, ε-greedy, UCB and Thompson sampling.', 'Run bandit algorithms against each other and measure regret.', 'Explain the exploration–exploitation trade-off with regret curves and bounds.'],
  ]},
  { title: 'Advanced III · Representations & generative models', goal: 'Learn representations and models that can generate data.', advanced: true, labs: [
    ['Nonlinear dimensionality reduction & ICA', 'Manifolds, t-SNE, UMAP ideas, independent component analysis and the limits of 2D maps.', 'Unmix mixed signals with ICA and embed high-dimensional data.', 'Explain what a t-SNE plot preserves and what it distorts.'],
    ['Deep-learning regularization & normalization', 'Dropout, weight decay, batch and layer normalization, residual connections, early stopping and augmentation.', 'Train the same network with and without each technique.', 'Explain each technique’s mechanism and measure its effect with controlled ablations.'],
    ['Autoencoders & variational autoencoders', 'Bottlenecks, denoising, latent spaces, the reparameterization trick and the ELBO.', 'Train an autoencoder and a VAE and explore their latent spaces.', 'Derive the VAE objective and explain the KL term’s effect.'],
    ['GANs & diffusion models', 'Adversarial training, mode collapse, forward noising, denoising score matching and sampling.', 'Train a small GAN and a small diffusion model on 2D data.', 'Explain why each objective produces samples and diagnose common failures.'],
    ['Language models', 'Tokenization and BPE, n-gram and neural language models, perplexity, sampling, fine-tuning, LoRA and preference optimization.', 'Train a character-level language model and control its sampling.', 'Compute perplexity, explain sampling trade-offs and describe how assistants are tuned.'],
    ['Self-supervised, semi-supervised & active learning', 'Pretext tasks, contrastive learning, pseudo-labeling, consistency and query strategies.', 'Learn from few labels by combining unlabeled data and smart labeling.', 'Measure how many labels each strategy saves and when it fails.'],
    ['Graph neural networks', 'Graphs as data, message passing, graph convolution, over-smoothing and node classification.', 'Classify nodes in a graph by passing messages.', 'Trace message passing by hand and explain over-smoothing.'],
  ]},
  { title: 'Advanced IV · Decisions, trust & robustness', goal: 'Act under uncertainty and know when a model can be trusted.', advanced: true, labs: [
    ['Policy gradients & actor–critic', 'Stochastic policies, REINFORCE, baselines and variance, advantage estimation and actor–critic.', 'Train a policy directly by gradient ascent on reward.', 'Derive the policy-gradient theorem’s estimator and show how a baseline reduces variance.'],
    ['Interpretability', 'Permutation importance, partial dependence and ICE, Shapley values, local surrogates and counterfactual explanations.', 'Explain a model globally and locally and test the explanations.', 'Compute exact Shapley values and show where explanations mislead.'],
    ['Uncertainty & conformal prediction', 'Aleatoric versus epistemic uncertainty, ensembles, quantile regression and split conformal prediction with guarantees.', 'Wrap any model in prediction intervals with guaranteed coverage.', 'Prove the conformal coverage guarantee and show when it breaks.'],
    ['Robustness & distribution shift', 'Adversarial examples, FGSM, adversarial training, covariate shift, importance weighting and domain adaptation.', 'Attack a classifier and then defend it; correct a shifted dataset.', 'Explain why small perturbations fool models and when reweighting fixes shift.'],
  ]},
]

let sequence = 0
export const roadmap = phases.map(phase => ({
  ...phase,
  labs: phase.labs.map(([title, topics, build, evidence]) => ({
    number: ++sequence, title, topics, build, evidence,
  })),
}))
