export const lessons = [
  {
    id: 'l49-trick',
    title: '49.1 · Feature maps and the kernel trick',
    sections: ['Linear models on richer features', 'The cost of explicit features', 'Inner products are enough', 'Expanding a polynomial kernel', 'Put it into practice'],
    skill: 'Explain the kernel trick and compute a kernel as an inner product of feature maps.',
    prerequisite: 'Labs 42 (kernels as covariances) and 48 (the SVM dual); polynomial features (Lab 07).',
    paragraphs: [
      'A linear model on transformed inputs φ(x) can represent curved functions: Lab 07 used polynomial features for exactly this. The trouble is size: all monomials up to degree 5 in 100 input variables number about 96 million.',
      'Many algorithms touch the data only through inner products φ(xᵢ)ᵀφ(xⱼ): the SVM dual (Lab 48), ridge regression in its dual form (Lesson 49.3), PCA via the Gram matrix (Lesson 49.4), k-means distances.',
      'If some function k(x, z) computes φ(x)ᵀφ(z) directly — cheaply — the algorithm can run in the feature space without ever forming φ. That is the **kernel trick**, and k is a **kernel**.',
      'Example: for scalars, (1 + xz)² = 1 + 2xz + x²z² = φ(x)ᵀφ(z) with φ(x) = (1, √2·x, x²). One multiplication and a square replace three features — and in d dimensions, (1 + xᵀz)ᵖ costs O(d) while its features number O(dᵖ).',
      'Procedure: write the algorithm so that data appear only in inner products; replace them by k; keep one coefficient per training example instead of one weight per feature.',
    ],
    formula: 'k(x, z) = φ(x)ᵀφ(z)     (1 + xz)² = φ(x)ᵀφ(z),  φ(x) = (1, √2 x, x²)',
    derivation: {
      title: 'Expand the degree-2 polynomial kernel',
      steps: [
        { prompt: 'Expand (1 + x·z)² as a polynomial in x and z.', answer: '1 + 2*x*z + x^2*z^2', show: '`1 + 2xz + x²z²`', vars: { x: [-2, 2], z: [-2, 2] } },
        { prompt: 'With φ(x) = (1, √2·x, x²), compute φ(x)ᵀφ(z).', answer: '1 + 2*x*z + x^2*z^2', show: '`1·1 + (√2x)(√2z) + x²z²` — the same', vars: { x: [-2, 2], z: [-2, 2] } },
        { prompt: 'Evaluate the kernel for x = 2, z = 3.', number: 49, show: '`(1 + 6)² = 49`' },
      ],
      result: 'The kernel computes the feature-space inner product without building the features.',
    },
    experiment: 'In the kernel ridge view, choose the polynomial kernel and turn on the explicit-feature overlay. Change the degree from 1 to 9. Do the two curves ever differ?',
    question: 'How many monomials of degree exactly 2 are there in 3 variables (x₁², x₁x₂, …)?',
    answer: 6,
    explanation: 'x₁², x₂², x₃², x₁x₂, x₁x₃, x₂x₃ — six, i.e. C(3 + 2 − 1, 2) = 6.',
    reflection: 'Which of the algorithms you know touch the data only through inner products or distances?',
  },
  {
    id: 'l49-valid',
    title: '49.2 · Which functions are kernels?',
    sections: ['Positive semidefinite Gram matrices', 'Mercer’s condition', 'Building kernels from kernels', 'The RBF kernel', 'Impostors'],
    skill: 'Test whether a function is a valid kernel and construct valid kernels.',
    prerequisite: 'Lesson 49.1; eigenvalues (Lab 18).',
    paragraphs: [
      'If k(x, z) = φ(x)ᵀφ(z), then for any points the **Gram matrix** Kᵢⱼ = k(xᵢ, xⱼ) satisfies cᵀKc = ‖Σ cᵢφ(xᵢ)‖² ≥ 0: it is positive semidefinite (PSD).',
      'The converse holds too (**Mercer’s theorem**): a symmetric function whose Gram matrices are always PSD is an inner product in some feature space — possibly infinite-dimensional.',
      'Kernels combine: sums, products, positive scalings, and k(f(x), f(z)) for any function f are all kernels; so is exp(k). This is how the RBF kernel arises: exp(−γ‖x − z‖²) = exp(−γ‖x‖²)·exp(−γ‖z‖²)·exp(2γxᵀz), and the last factor’s Taylor series contains polynomial kernels of every degree — infinitely many features.',
      'The RBF kernel’s Gram matrix eigenvalues decay very fast (the playground’s bars): in practice only a modest number of feature directions carry weight, which is why approximations such as random Fourier features (Lab 15) and Nyström work.',
      'Not every similarity is a kernel. tanh(xᵀz − 1), the old “sigmoid kernel”, produces negative eigenvalues; so do many hand-made similarity scores. With an indefinite “kernel” the SVM and kernel ridge problems are no longer convex, and solvers can return nonsense.',
    ],
    formula: 'k valid  ⇔  every Gram matrix K ⪰ 0     k₁ + k₂, k₁·k₂, c·k (c > 0), exp(k) are kernels',
    derivation: {
      title: 'Check a 2 × 2 Gram matrix',
      intro: 'Two points with k(x₁, x₁) = k(x₂, x₂) = 1 and k(x₁, x₂) = r.',
      steps: [
        { prompt: 'The eigenvalues of [[1, r], [r, 1]] are 1 + r and 1 − r. Which is the smallest when r > 0? Write it.', answer: '1 - r', show: '`1 − r`', vars: { r: [0, 1] } },
        { prompt: 'For which values of r is the matrix PSD? Give the largest allowed r.', number: 1, show: '`|r| ≤ 1`' },
        { prompt: 'A “similarity” gives self-similarity 1 and cross-similarity 1.3. Smallest eigenvalue?', number: -0.3, tolerance: 1e-9, show: '`−0.3` — not a valid kernel', why: 'Two points cannot be more similar to each other than to themselves in an inner-product space (Cauchy–Schwarz).' },
      ],
      result: 'Valid kernels obey Cauchy–Schwarz: k(x, z)² ≤ k(x, x)·k(z, z).',
    },
    experiment: 'In the Gram-matrix view, compare the eigenvalues of each kernel. Then choose the tanh impostor. What is its smallest eigenvalue?',
    question: 'Is k(x, z) = 3·exp(−‖x − z‖²) + (xᵀz)² a valid kernel? (1 = yes, 0 = no)',
    answer: 1,
    explanation: 'Yes: a positive multiple of the RBF kernel plus a polynomial kernel — sums and positive scalings of kernels are kernels.',
    reflection: 'You designed a custom similarity between documents. How would you check whether it is safe to use in an SVM?',
  },
  {
    id: 'l49-representer',
    title: '49.3 · The representer theorem and kernel ridge regression',
    sections: ['Where the solution lives', 'Kernel ridge regression', 'Identical to explicit features', 'Cost', 'Connection to Gaussian processes'],
    skill: 'Derive kernel ridge regression from the representer theorem and relate it to explicit features and GPs.',
    prerequisite: 'Lessons 49.1–49.2; ridge regression (Lab 07), GPs (Lab 42).',
    paragraphs: [
      'The **representer theorem**: for any loss on the training predictions plus a penalty ‖w‖² in feature space, the optimal w lies in the span of the training features, w = Σ αᵢ φ(xᵢ). Anything orthogonal to them increases the penalty without changing the predictions.',
      'For ridge regression, minimizing ‖y − Φw‖² + λ‖w‖² with w = Φᵀα gives **α = (K + λI)⁻¹y** and predictions f(x) = Σ αᵢ k(xᵢ, x). One coefficient per training example; the features never appear.',
      'With the polynomial kernel, kernel ridge and ridge on the explicitly expanded features produce identical predictions — the playground overlays them. With the RBF kernel there is no explicit alternative: its feature space is infinite.',
      'The price moves from features to examples: solving (K + λI)α = y costs O(n³) time and O(n²) memory, and every prediction needs n kernel evaluations. Kernel methods shine with thousands of examples and rich structure, and struggle with millions.',
      'The kernel ridge prediction equals the **posterior mean of a Gaussian process** with covariance k and noise variance λ (Lab 42). The GP adds the predictive variance; kernel ridge is its point estimate.',
    ],
    formula: 'α = (K + λI)⁻¹y     f(x) = Σᵢ αᵢ k(xᵢ, x)     = GP posterior mean with noise λ',
    derivation: {
      title: 'Kernel ridge with one training point',
      intro: 'One example (x₁, y), kernel value k₁₁ = k(x₁, x₁).',
      steps: [
        { prompt: 'Write α for a single example in terms of y, k11 and λ.', answer: 'y/(k11 + λ)', show: '`y / (k₁₁ + λ)`', vars: { y: [-2, 2], k11: [0.5, 2], λ: [0.01, 1] }, hint: 'Type λ as lambda.' },
        { prompt: 'Prediction at a point x with k(x₁, x) = kx. Write f(x).', answer: 'kx*y/(k11 + λ)', show: '`kx·y / (k₁₁ + λ)`', vars: { y: [-2, 2], k11: [0.5, 2], λ: [0.01, 1], kx: [0, 1] } },
        { prompt: 'RBF kernel (k₁₁ = 1), y = 2, λ = 0.25, and k(x₁, x) = 0.5: f(x)?', number: 0.8, show: '`0.5 × 2 / 1.25 = 0.8`' },
      ],
      result: 'Identical to the one-point GP posterior mean in Lab 42 — with λ playing the noise variance.',
    },
    experiment: 'In the kernel ridge view with the RBF kernel, set λ to 0.0001 and γ to 30, then to 0.01. What happens between the data points in each case?',
    question: 'Kernel ridge regression on 10,000 examples. How many coefficients αᵢ does it learn?',
    answer: 10000,
    explanation: 'One per training example — regardless of how many (even infinitely many) features the kernel implies.',
    reflection: 'For your largest dataset, would kernel ridge regression fit in memory? What would you do instead?',
  },
  {
    id: 'l49-kpca',
    title: '49.4 · Kernel PCA and other kernelized algorithms',
    sections: ['PCA from the Gram matrix', 'Centering in feature space', 'Untangling rings', 'Kernelizing everything', 'The pre-image problem'],
    skill: 'Compute kernel PCA from a centred Gram matrix and recognize kernelizable algorithms.',
    prerequisite: 'Lessons 49.1–49.3; PCA (Lab 18).',
    paragraphs: [
      'PCA diagonalizes the covariance (Lab 18). Its nonzero eigenvalues equal those of the n × n Gram matrix of the centred data, and projections can be computed from the Gram matrix alone. Replace inner products by a kernel and you get **kernel PCA**.',
      'The features must be centred in feature space, which we cannot compute directly — but the Gram matrix of the centred features can: K̃ = K − 1K/n − K1/n + 1K1/n², i.e. subtract row and column means and add back the overall mean.',
      'On two concentric rings, ordinary PCA only rotates the plane; no direction separates the rings. With an RBF kernel of suitable width, one of the leading kernel components separates them perfectly — a nonlinear feature learned without labels.',
      'The same move kernelizes many algorithms: SVMs (Lab 48), ridge regression, k-means (distances via kernels), canonical correlation analysis, and two-sample tests (maximum mean discrepancy).',
      'The catch: a point in feature space has no obvious counterpart in the input space (the **pre-image problem**), so kernel PCA cannot simply reconstruct or denoise inputs the way linear PCA can.',
    ],
    formula: 'K̃ = HKH,  H = I − 11ᵀ/n     projection of xᵢ on component c: √λ_c · v_c[i]',
    derivation: {
      title: 'Centre a small Gram matrix',
      intro: 'K = [[2, 0], [0, 2]] for two points.',
      steps: [
        { prompt: 'Row means are 1 and 1, overall mean 1. Centred entry K̃₁₁ = K₁₁ − 1 − 1 + 1 = ?', number: 1, show: '`1`' },
        { prompt: 'Centred entry K̃₁₂ = 0 − 1 − 1 + 1 = ?', number: -1, show: '`−1`', why: 'After centring, the two points sit on opposite sides of their mean.' },
      ],
      result: 'Centring removes the common component so that the leading eigenvectors describe variation, not the mean.',
    },
    experiment: 'In the kernel PCA view, compare the linear kernel with RBF at γ = 0.1, 2 and 5. Which setting separates the rings, and on which component?',
    question: 'Kernel PCA on 2,000 points: what is the size of the matrix whose eigenvectors are computed?',
    answer: 2000,
    explanation: 'The Gram matrix is 2,000 × 2,000 — independent of the (possibly infinite) feature dimension.',
    reflection: 'Where might unsupervised nonlinear features help your work before any labels exist?',
  },
  {
    id: 'l49-practice',
    title: '49.5 · Choosing kernels and scaling up',
    sections: ['Kernels encode assumptions', 'Tuning γ and λ', 'The median heuristic', 'Approximations for large n', 'Demonstrate understanding'],
    skill: 'Choose and tune kernels and decide when kernel methods are the right tool.',
    prerequisite: 'Lessons 49.1–49.4; cross-validation (Lab 06).',
    paragraphs: [
      'A kernel is an assumption about similarity: RBF says nearby inputs behave alike at one scale; Laplacian allows rougher functions; polynomial kernels suit interactions of bounded order; specialized kernels exist for strings, graphs and sets. Scale features first — an RBF kernel on unscaled inputs lets one variable dominate distances.',
      'γ sets the width of each bump: small γ means smooth, nearly linear fits; large γ means spiky fits that memorize. λ trades fit for smoothness. They interact, so tune both with cross-validation over a logarithmic grid, as in the playground heatmap.',
      'A good starting γ is the **median heuristic**: 1/(2·median squared distance between points), so a typical pair of points has kernel value around e^(−1/2).',
      'For large n: Nyström approximations (a low-rank Gram matrix from m landmark points) and random Fourier features (Lab 15) turn kernel methods back into linear models with m features, O(nm²) instead of O(n³).',
      'You have completed this lab when you can: explain and verify the kernel trick; test and construct valid kernels; derive kernel ridge regression from the representer theorem and relate it to GPs; compute kernel PCA; and tune and scale kernel methods. The Python challenge implements kernels, kernel ridge and kernel PCA and checks them against scikit-learn.',
    ],
    formula: 'median heuristic: γ = 1 / (2 · median ‖xᵢ − xⱼ‖²)     Nyström: K ≈ K_nm K_mm⁻¹ K_mn',
    derivation: {
      title: 'The median heuristic',
      steps: [
        { prompt: 'Write γ so that exp(−γ·m) = e^(−1/2), where m is the median squared distance.', answer: '1/(2*m)', show: '`γ = 1/(2m)`', vars: { m: [0.1, 10] } },
        { prompt: 'Median squared distance 4: γ?', number: 0.125, show: '`1/8 = 0.125`' },
      ],
      result: 'A data-driven starting point for the grid search, not a replacement for it.',
    },
    experiment: 'In the kernel ridge view, find the best cell in the cross-validation heatmap. Then set the sliders to it and compare the curve with the true function.',
    question: 'Nyström with m = 500 landmarks on n = 100,000 points costs about n·m² operations. How many is that?',
    answer: 25000000000,
    explanation: '100,000 × 500² = 2.5 × 10¹⁰ — versus n³ = 10¹⁵ for exact kernel ridge regression.',
    reflection: 'For a problem you know, would you reach for a kernel method, gradient-boosted trees or a neural network — and why?',
  },
]

export const sources = [
  { title: 'Schölkopf & Smola · Learning with Kernels (MIT Press)', url: 'https://mitpress.mit.edu/9780262536578/learning-with-kernels/' },
  { title: 'Shawe-Taylor & Cristianini · Kernel Methods for Pattern Analysis', url: 'https://doi.org/10.1017/CBO9780511809682' },
  { title: 'Schölkopf, Smola & Müller (1998) · Nonlinear component analysis as a kernel eigenvalue problem', url: 'https://doi.org/10.1162/089976698300017467' },
  { title: 'scikit-learn · Kernel ridge regression and kernel approximation', url: 'https://scikit-learn.org/stable/modules/kernel_ridge.html' },
]
