export const lessons = [
  {
    id: 'l50-regret',
    title: '50.1 · Learning one decision at a time',
    sections: ['A different setting', 'The protocol', 'Regret', 'Why no statistics?', 'Put it into practice'],
    skill: 'Formulate online learning problems and measure them by regret.',
    prerequisite: 'Learning theory (Lab 47), Bayesian updating (Lab 41), experiments (Lab 36), reinforcement learning (Lab 37).',
    paragraphs: [
      'Batch learning trains once on a fixed dataset. Many systems instead decide continually: which ad to show, which route to take, which server gets the next request. Each decision is made before seeing its outcome, and each outcome arrives in time for the next decision.',
      'The **online protocol**: for t = 1, …, T, the learner chooses an action (or prediction), the environment reveals a loss, and the learner updates. With **full information** it sees every action’s loss; with **bandit feedback** only the loss of the action it chose.',
      'The yardstick is **regret**: the learner’s total loss minus the total loss of the best fixed action in hindsight. Good algorithms have **sublinear** regret — regret/T → 0 — so on average they do as well as the best fixed choice.',
      'Remarkably, many online guarantees make no statistical assumption at all: they hold for any sequence, even one chosen by an adversary reacting to the learner. Where Lab 47 needed i.i.d. data, online learning needs only bounded losses.',
      'Procedure: name the actions, the feedback you actually observe, and the horizon; pick an algorithm with a regret guarantee for that feedback; and log what was chosen and with what probability (Lab 35) so the system can be evaluated later.',
    ],
    formula: 'Regret_T = Σₜ ℓₜ(aₜ) − min_a Σₜ ℓₜ(a)     good: Regret_T / T → 0',
    derivation: {
      title: 'Linear versus sublinear regret',
      steps: [
        { prompt: 'An algorithm with regret 0.01·T. What is its average regret per round?', number: 0.01, show: '`0.01` — it never catches up' },
        { prompt: 'Another has regret 5·√T. Write its average regret per round as a function of T.', answer: '5/sqrt(T)', show: '`5/√T` → 0', vars: { T: [1, 10000] } },
        { prompt: 'At T = 10,000, what is that average?', number: 0.05, show: '`5/100 = 0.05`' },
      ],
      result: 'Sublinear regret means the learner’s average performance converges to the best fixed action’s.',
    },
    experiment: 'In the bandit view, compare the four policies at 1,000 rounds and at 20,000. Which regret curves keep rising steeply, and which flatten?',
    question: 'Over 1,000 rounds, a learner lost 310 times; the best single action in hindsight lost 270 times. What is the regret?',
    answer: 40,
    explanation: '310 − 270 = 40.',
    reflection: 'Name a decision in your work that is made repeatedly with feedback. Is the feedback full or bandit?',
  },
  {
    id: 'l50-perceptron',
    title: '50.2 · The perceptron and its mistake bound',
    sections: ['The oldest online learner', 'Update only on mistakes', 'The margin', 'The bound', 'Beyond separable data'],
    skill: 'Derive the perceptron mistake bound and interpret it.',
    prerequisite: 'Lesson 50.1; margins (Labs 15, 48).',
    paragraphs: [
      'The **perceptron** predicts sign(wᵀx). When it is wrong on (x, y), it updates w ← w + y·x; when right, it does nothing.',
      'Suppose a unit vector u separates the stream with **margin** γ: y·uᵀx ≥ γ for every example, and every ‖x‖ ≤ R.',
      'Each mistake increases wᵀu by at least γ, so after M mistakes wᵀu ≥ Mγ. Each mistake increases ‖w‖² by at most R² (because y·wᵀx ≤ 0 on a mistake), so ‖w‖ ≤ R√M. Since wᵀu ≤ ‖w‖, Mγ ≤ R√M, hence **M ≤ (R/γ)²**.',
      'The bound holds for any order and any length of stream — it does not grow with T. Larger margins mean fewer mistakes. It is loose in practice (the playground makes far fewer mistakes than the bound), but it needs no probability at all.',
      'On non-separable data the perceptron never settles; averaged or voted perceptrons and online gradient descent on the hinge loss fix this. The same “bounded mistakes from a margin” idea underlies the SVM (Lab 48).',
    ],
    formula: 'on a mistake: w ← w + y x     M ≤ (R/γ)²',
    derivation: {
      title: 'The two inequalities behind the bound',
      steps: [
        { prompt: 'After M mistakes, wᵀu ≥ ? Write it in terms of M and γ.', answer: 'M*γ', show: '`M·γ`', vars: { M: [1, 50], γ: [0.1, 1] }, hint: 'Type γ as gamma.' },
        { prompt: 'And ‖w‖ ≤ ? in terms of M and R.', answer: 'R*sqrt(M)', show: '`R·√M`', vars: { M: [1, 50], R: [1, 5] } },
        { prompt: 'Combine them: with R = 2 and γ = 0.5, the most mistakes possible?', number: 16, show: '`(2/0.5)² = 16`' },
      ],
      result: 'Progress per mistake (γ) against growth per mistake (R²) caps the number of mistakes.',
    },
    experiment: 'In the perceptron view, move the margin from 1.5 down to 0.05. How do the actual mistakes and the bound change?',
    question: 'Data with radius R = 3 and margin γ = 0.25. What is the perceptron mistake bound?',
    answer: 144,
    explanation: '(3/0.25)² = 12² = 144 mistakes at most, on any sequence.',
    reflection: 'Why does a larger margin make learning easier, in plain words?',
  },
  {
    id: 'l50-experts',
    title: '50.3 · Learning from expert advice',
    sections: ['Many advisers, one decision', 'Follow the leader fails', 'Multiplicative weights', 'The regret guarantee', 'Choosing η'],
    skill: 'Run the Hedge algorithm and explain its regret guarantee.',
    prerequisite: 'Lessons 50.1–50.2.',
    paragraphs: [
      'N experts — forecasters, models, heuristics — each suggest an action every round, and afterwards you see everyone’s loss in [0, 1]. You want to do almost as well as the best expert, without knowing in advance which one it is.',
      '**Follow the leader** (use whoever has the lowest loss so far) works on friendly data, but an adversary can make the current leader wrong every round: in the playground’s alternating sequence it loses 1,000 more than the best expert over 2,000 rounds — linear regret.',
      '**Hedge** (multiplicative weights) keeps a weight per expert, starts them equal, and after each round multiplies each by e^(−η·loss). It follows the weighted mix (or picks an expert at random in proportion). Bad experts fade exponentially; no single round can swing the decision completely.',
      'With η = √(8 ln N / T), Hedge’s regret is at most **√(T ln N / 2)** for any loss sequence. Regret grows like √T — sublinear — and only logarithmically in the number of experts, so you can afford many.',
      'η trades speed for stability: large η reacts fast (like follow-the-leader, fragile); small η averages too long. The same multiplicative-weights idea appears in boosting (AdaBoost reweights examples), game theory and linear programming.',
    ],
    formula: 'wᵢ ← wᵢ · e^(−η ℓᵢ)     p = w / Σw     Regret ≤ √(T ln N / 2) with η = √(8 ln N / T)',
    derivation: {
      title: 'Two rounds of Hedge',
      intro: 'Two experts, equal starting weights 1 and 1, η = ln 2 (so e^(−η) = ½).',
      steps: [
        { prompt: 'Round 1 losses: expert 1 loses 1, expert 2 loses 0. New weight of expert 1?', number: 0.5, show: '`1 × ½ = 0.5`' },
        { prompt: 'Probability of following expert 1 in round 2? (Four decimals.)', number: 1 / 3, tolerance: 1e-4, show: '`0.5/1.5 ≈ 0.3333`' },
        { prompt: 'Regret bound for T = 2,000 rounds and N = 2 experts (one decimal).', number: Math.sqrt(2000 * Math.log(2) / 2), tolerance: 0.1, show: '`√(1000 ln 2) ≈ 26.3`' },
      ],
      result: 'Weights shrink exponentially with accumulated loss, but never to zero in one step.',
    },
    experiment: 'In the experts view, switch to the adversarial sequence and compare Hedge with follow-the-leader. Then multiply η by 5 and by 0.1. What happens to Hedge?',
    question: 'Hedge with N = 100 experts over T = 5,000 rounds. What is its regret guarantee? (Nearest whole number.)',
    answer: 107, tolerance: 1,
    explanation: '√(5000 × ln 100 / 2) = √(5000 × 4.605 / 2) ≈ √11513 ≈ 107.',
    reflection: 'Which set of “experts” (models, rules, people) could you combine with multiplicative weights?',
  },
  {
    id: 'l50-bandits',
    title: '50.4 · Multi-armed bandits',
    sections: ['Only your own outcome', 'Explore versus exploit', 'ε-greedy', 'UCB: optimism under uncertainty', 'Logarithmic regret'],
    skill: 'Compare greedy, ε-greedy and UCB bandit strategies and explain their regret.',
    prerequisite: 'Lessons 50.1–50.3; confidence intervals (Lab 05).',
    paragraphs: [
      'In a **bandit** problem you see only the reward of the arm you pulled — as with ads, recommendations (Lab 35) or treatment choices. To learn an arm’s value you must spend rounds on it, even if it may be worse: **exploration** versus **exploitation**.',
      '**Greedy** always pulls the arm with the best average so far. An unlucky start can lock it onto a bad arm forever: in the playground its average regret is high and wildly variable across runs.',
      '**ε-greedy** explores a random arm with probability ε. It never gets stuck, but it keeps exploring bad arms at a constant rate, so its regret grows **linearly**: at 20,000 rounds it falls behind UCB1 on the clear-winner arms.',
      '**UCB1** pulls the arm with the highest upper confidence bound: average + √(2 ln t / nₐ). Arms pulled rarely get a large bonus — they might be better than they look — and the bonus shrinks as evidence accumulates. Its regret grows only **logarithmically** in T, matching the theoretical lower bound up to constants.',
      'Constants matter: UCB1’s bonus assumes rewards could lie anywhere in [0, 1], so with 5% click rates it explores far too much (the playground’s ad arms). Variance-aware versions (UCB-V, KL-UCB) or Thompson sampling fix this.',
    ],
    formula: 'UCB1: aₜ = argmaxₐ [ μ̂ₐ + √(2 ln t / nₐ) ]     regret = O(Σₐ ln T / Δₐ)',
    derivation: {
      title: 'Compute UCB indices',
      intro: 'After t = 100 rounds: arm A has average 0.5 from 80 pulls; arm B has average 0.4 from 20 pulls.',
      steps: [
        { prompt: 'UCB index of A = 0.5 + √(2 ln 100 / 80)? (Four decimals.)', number: 0.5 + Math.sqrt(2 * Math.log(100) / 80), tolerance: 1e-4, show: '`≈ 0.8393`' },
        { prompt: 'UCB index of B? (Four decimals.)', number: 0.4 + Math.sqrt(2 * Math.log(100) / 20), tolerance: 1e-4, show: '`≈ 1.0786`', why: 'B is pulled next: its average is lower, but so little is known about it that it might be better.' },
        { prompt: 'Write the exploration bonus as a function of t and n.', answer: 'sqrt(2*log(t)/n)', show: '`√(2 ln t / n)`', vars: { t: [2, 1000], n: [1, 500] } },
      ],
      result: 'The bonus grows slowly with time (every arm is eventually retried) and shrinks with evidence about that arm.',
    },
    experiment: 'In the bandit view, compare the share of rounds spent on the best variant for each policy. Then switch to the ad click-through rates and explain UCB1’s result.',
    question: 'ε-greedy with ε = 0.1 and 5 arms explores uniformly. Over 10,000 rounds, about how many rounds are spent exploring the four non-best arms?',
    answer: 800,
    explanation: '10,000 × 0.1 = 1,000 exploration rounds, 4/5 of which land on non-best arms: 800 — forever, no matter how clear the winner is.',
    reflection: 'Where do you currently run a fixed A/B split that a bandit could shorten?',
  },
  {
    id: 'l50-thompson',
    title: '50.5 · Thompson sampling and bandits in practice',
    sections: ['Probability matching', 'Why it works so well', 'Bandits or A/B tests?', 'Contextual bandits', 'Demonstrate understanding'],
    skill: 'Implement Thompson sampling and choose between bandits and experiments.',
    prerequisite: 'Lessons 50.1–50.4; Beta posteriors (Lab 41), experiments (Lab 36), recommenders (Lab 35).',
    paragraphs: [
      '**Thompson sampling** keeps a posterior for each arm’s success rate — Beta(1 + successes, 1 + failures), exactly Lab 41 — draws one sample from each, and pulls the arm whose sample is largest. Each arm is chosen with the probability that it is the best.',
      'Uncertain arms produce widely spread samples and so get tried; clearly bad arms almost never win a draw. The exploration adapts automatically to the reward scale, which is why Thompson sampling is best or near-best in every playground setting — including the 5% click rates where UCB1 over-explores. It also has logarithmic regret guarantees.',
      'Bandits and A/B tests (Lab 36) answer different questions. A bandit minimizes regret **during** the experiment, shifting traffic to winners; an A/B test with a fixed split estimates the difference between variants with valid confidence intervals. Adaptive allocation biases naive estimates — if you need an unbiased effect size for a lasting decision, run the experiment or use corrected estimators.',
      '**Contextual bandits** choose actions based on features (user, time, device): LinUCB and Thompson sampling with a Bayesian linear model (Lab 41) are standard. Log the probability of every action taken, so new policies can be evaluated offline with importance weighting (Labs 35, 44).',
      'You have completed this lab when you can: define regret and explain sublinear regret; derive the perceptron mistake bound; run Hedge and state its guarantee and why follow-the-leader fails; compare greedy, ε-greedy, UCB and Thompson sampling; and decide between a bandit and an A/B test. The Python challenge implements these algorithms and checks their regret.',
    ],
    formula: 'θₐ ~ Beta(1 + sₐ, 1 + fₐ),  pull argmaxₐ θₐ     P(pull a) = P(a is best | data)',
    derivation: {
      title: 'The posterior Thompson samples from',
      steps: [
        { prompt: 'An arm had 7 successes and 13 failures. Its posterior is Beta(1 + 7, 1 + 13). Posterior mean? (Four decimals.)', number: 8 / 22, tolerance: 1e-4, show: '`8/22 ≈ 0.3636`' },
        { prompt: 'Write the posterior mean after s successes and f failures.', answer: '(1+s)/(2+s+f)', show: '`(1 + s)/(2 + s + f)`', vars: { s: [0, 50], f: [0, 50] } },
      ],
      result: 'Thompson sampling needs nothing beyond the conjugate updates of Lab 41 — plus one random draw per arm.',
    },
    experiment: 'In the bandit view, compare Thompson sampling with UCB1 on all three arm sets at 5,000 rounds. On which set is the difference largest?',
    question: 'Two arms have posterior means 0.30 and 0.35 with wide posteriors. Will Thompson sampling ever pull the 0.30 arm? (1 = yes, 0 = no)',
    answer: 1,
    explanation: 'Yes: whenever its sampled value happens to exceed the other’s — with probability equal to the posterior probability that it is actually the better arm.',
    reflection: 'For a product decision you know, would you rather minimize regret during the test or measure the effect precisely? Why?',
  },
]

export const sources = [
  { title: 'Lattimore & Szepesvári · Bandit Algorithms (free book)', url: 'https://tor-lattimore.com/downloads/book/book.pdf' },
  { title: 'Auer, Cesa-Bianchi & Fischer (2002) · Finite-time analysis of the multiarmed bandit problem', url: 'https://doi.org/10.1023/A:1013689704352' },
  { title: 'Arora, Hazan & Kale (2012) · The multiplicative weights update method: a meta-algorithm and applications', url: 'https://theoryofcomputing.org/articles/v008a006/' },
  { title: 'Russo et al. (2018) · A tutorial on Thompson sampling', url: 'https://arxiv.org/abs/1707.02038' },
]
