export const lessons = [
  {
    id: 'l51-beyond',
    title: '51.1 · When straight lines are not enough',
    sections: ['PCA’s limits', 'The manifold hypothesis', 'What should a map preserve?', 'Three different goals', 'Put it into practice'],
    skill: 'Choose a dimensionality-reduction goal — independence, geodesic geometry or neighbourhoods — for a given problem.',
    prerequisite: 'PCA and SVD (Lab 18), kernel PCA (Lab 49), information theory (Lab 46).',
    paragraphs: [
      'PCA (Lab 18) finds orthogonal directions of maximal variance and projects onto them. It is optimal for linear structure and Gaussian-like data — and blind to anything else.',
      'The **manifold hypothesis**: real high-dimensional data (images, sensor streams, embeddings) often lie near a much lower-dimensional curved surface. A photo of a face varies along a handful of factors — pose, light, expression — not along each of its million pixels independently.',
      'No 2D picture can preserve everything about high-dimensional data. Every method chooses: variance (PCA), statistical independence (ICA), distances along the surface (Isomap), or who is near whom (t-SNE, UMAP).',
      'Those goals answer different questions. ICA separates mixed signals; Isomap recovers a curved coordinate system; t-SNE draws a picture of neighbourhoods for exploration. Using a visualization method as a measurement tool is the most common misuse.',
      'Procedure: say what you want to preserve before choosing a method; run the linear baseline (PCA) first; and check any structure you see with an independent method or the original data.',
    ],
    formula: 'PCA: max variance     ICA: max non-Gaussianity     Isomap: geodesic distances     t-SNE: neighbourhoods',
    derivation: {
      title: 'Why a projection loses information',
      intro: 'Two points on a swiss roll: straight-line distance 1.0 across neighbouring layers, but 9.4 along the sheet.',
      steps: [
        { prompt: 'By how much does straight-line distance understate the along-sheet distance? (Ratio, one decimal.)', number: 9.4, tolerance: 0.05, show: '`9.4`' },
        { prompt: 'A linear projection can only shrink straight-line distances. After projection, can the two points be farther apart than 1.0? (1 = yes, 0 = no)', number: 0, show: '`0` — projections never increase distances' },
      ],
      result: 'No projection can separate points that the straight-line geometry puts together; you need a different notion of distance.',
    },
    experiment: 'In the Isomap view, compare the side view of the roll with the PCA and Isomap maps. Which one lets colour change smoothly along a single axis?',
    question: 'A 256 × 256 grayscale image has how many pixel dimensions?',
    answer: 65536,
    explanation: '256 × 256 = 65,536 — yet natural images of one object vary along only a few factors.',
    reflection: 'Which high-dimensional data in your work might lie on a low-dimensional curved surface? What would its coordinates mean?',
  },
  {
    id: 'l51-ica',
    title: '51.2 · Independent component analysis',
    sections: ['The cocktail party', 'Uncorrelated is not independent', 'Non-Gaussianity', 'Whitening and FastICA', 'What ICA cannot resolve'],
    skill: 'Explain and apply ICA to separate mixed signals, and recognize when it cannot work.',
    prerequisite: 'Lesson 51.1; central limit theorem (Lab 05).',
    paragraphs: [
      'Two microphones each record a mix of two voices: x = A·s, with an unknown mixing matrix A. We want the sources s. PCA decorrelates the recordings, but many rotations of decorrelated data are also decorrelated, so PCA’s outputs are still mixtures (about 73% match in the playground).',
      'Independence is stronger than uncorrelatedness. The key insight comes from the central limit theorem: a mixture of independent signals is **more Gaussian** than the signals themselves. So we look for directions whose projections are as non-Gaussian as possible.',
      'Non-Gaussianity can be measured by excess kurtosis (0 for a Gaussian, positive for spiky signals such as speech, negative for flat ones such as sine waves) or by approximations of negentropy. **FastICA** first whitens the data (centre, decorrelate, scale to unit variance) and then, for each component, iterates a fixed-point update w ← E[z·g(wᵀz)] − E[g′(wᵀz)]·w with g = tanh, keeping components orthogonal.',
      'ICA recovers sources only up to **order, sign and scale** — any of these could be absorbed into A. In the playground it matches the sources almost perfectly for sine/sawtooth and spiky “voices”.',
      'If the sources are **Gaussian**, ICA cannot work: whitened Gaussian data look the same in every direction, so every rotation is equally good and different random starts return different answers. At most one source may be Gaussian.',
    ],
    formula: 'x = A s     z = whiten(x)     FastICA: w ← E[z g(wᵀz)] − E[g′(wᵀz)] w,  w ← w/‖w‖',
    derivation: {
      title: 'Whitening a single variable',
      steps: [
        { prompt: 'Whitening divides a centred variable by its standard deviation. Write the whitened value of x with mean m and variance v.', answer: '(x - m)/sqrt(v)', show: '`(x − m)/√v`', vars: { x: [-5, 5], m: [-2, 2], v: [0.5, 4] } },
        { prompt: 'Excess kurtosis of a standard Gaussian?', number: 0, show: '`0`' },
        { prompt: 'Excess kurtosis of a Laplace distribution (a common model for speech)?', number: 3, show: '`3` — spikier than Gaussian' },
      ],
      result: 'After whitening, only rotations remain to be found — and non-Gaussianity picks the right one.',
    },
    experiment: 'In the ICA view, compare the three source types. With Gaussian noise sources, move the random start: does ICA return the same components each time?',
    question: 'How many of the sources can be Gaussian for ICA to still recover all of them (up to order, sign and scale)?',
    answer: 1,
    explanation: 'At most one: with two or more Gaussian sources, rotations within their subspace cannot be distinguished.',
    reflection: 'Where might your data be a mixture of independent causes you would like to separate?',
  },
  {
    id: 'l51-isomap',
    title: '51.3 · Manifold learning with Isomap',
    sections: ['Geodesic distance', 'A neighbourhood graph', 'Classical MDS', 'Choosing k', 'Other manifold methods'],
    skill: 'Compute Isomap from a neighbourhood graph and classical MDS and choose its neighbourhood size.',
    prerequisite: 'Lessons 51.1–51.2; eigenvectors (Lab 18); shortest paths.',
    paragraphs: [
      'On a curved surface, the meaningful distance between two points is along the surface — the **geodesic** — not straight through space.',
      '**Isomap** approximates geodesics: connect each point to its k nearest neighbours (short straight hops are good approximations of the surface), then take the shortest path through that graph between every pair of points (Dijkstra’s algorithm).',
      '**Classical MDS** turns a distance matrix into coordinates: square the distances, double-centre them (B = −½ H D² H), and use the top eigenvectors scaled by the square roots of their eigenvalues. For Euclidean distances it reproduces PCA exactly; for geodesic distances it unrolls the manifold.',
      'In the playground, Isomap’s first axis tracks the position along the swiss roll perfectly (rank correlation 1.00) where PCA reaches 0.23. The neighbourhood size matters: k = 4–8 works, but at k ≥ 15 the graph gains “short-circuit” edges between adjacent layers and the unrolling collapses.',
      'Relatives: locally linear embedding (LLE) preserves how each point is reconstructed from its neighbours; Laplacian eigenmaps preserve graph smoothness. All depend on a good neighbourhood graph and struggle with noise and holes.',
    ],
    formula: 'Isomap: kNN graph → shortest-path distances D → B = −½ H D² H → top eigenvectors √λ v',
    derivation: {
      title: 'Double centring in classical MDS',
      intro: 'Three points on a line at positions 0, 1 and 3.',
      steps: [
        { prompt: 'Squared distance between the first and third points?', number: 9, show: '`9`' },
        { prompt: 'The mean position is 4/3. What is B₁₁ = (0 − 4/3)²? (Four decimals.)', number: 16 / 9, tolerance: 1e-4, show: '`16/9 ≈ 1.7778`', why: 'Double centring −½HD²H recovers exactly the Gram matrix of the centred positions.' },
      ],
      result: 'Classical MDS recovers coordinates from distances alone, up to rotation and reflection.',
    },
    experiment: 'In the Isomap view, raise k from 4 to 30. At what k does the colour stop varying smoothly along one axis?',
    question: 'Isomap on 1,000 points: how many shortest-path distances does it compute?',
    answer: 1000000,
    explanation: '1,000 × 1,000 = 10⁶ entries (half of them by symmetry) — Isomap scales poorly to very large datasets.',
    reflection: 'What would a “short circuit” look like in your data — two things close in raw features but far apart in reality?',
  },
  {
    id: 'l51-tsne',
    title: '51.4 · t-SNE',
    sections: ['Similarities as probabilities', 'Perplexity', 'The crowding problem', 'Optimization', 'Cost'],
    skill: 'Explain how t-SNE turns neighbourhoods into a 2D map and the role of perplexity.',
    prerequisite: 'Lessons 51.1–51.3; KL divergence and perplexity (Lab 46).',
    paragraphs: [
      't-SNE converts distances into probabilities: p(j | i) ∝ exp(−‖xᵢ − xⱼ‖² / 2σᵢ²), “how likely i would pick j as a neighbour”. Symmetrized, these form a distribution P over pairs.',
      'Each point gets its own σᵢ, set so the neighbour distribution has a chosen **perplexity** 2^H — roughly the number of effective neighbours (Lab 46). Dense regions get small σ, sparse ones large σ, which is why t-SNE equalizes densities.',
      'In 2D there is not enough room to keep all moderately distant points moderately distant (the **crowding problem**). t-SNE uses a heavy-tailed Student-t similarity in the map, q_ij ∝ (1 + ‖yᵢ − yⱼ‖²)⁻¹, so dissimilar points can be placed far apart cheaply.',
      'It minimizes KL(P ‖ Q) by gradient descent, with “early exaggeration” (P multiplied by 12 at first) to form clusters, then momentum. KL(P ‖ Q) punishes separating true neighbours far more than bringing non-neighbours close — a local, not global, objective.',
      'The exact version costs O(n²) per iteration; Barnes–Hut and FFT-based approximations reach millions of points. Results depend on perplexity, learning rate, iterations and random seed.',
    ],
    formula: 'p(j|i) ∝ exp(−‖xᵢ − xⱼ‖²/2σᵢ²)     q_ij ∝ (1 + ‖yᵢ − yⱼ‖²)⁻¹     minimize KL(P ‖ Q)',
    derivation: {
      title: 'Heavy tails in the map',
      steps: [
        { prompt: 'Write the unnormalized Student-t similarity for map distance d.', answer: '1/(1 + d^2)', show: '`1/(1 + d²)`', vars: { d: [0, 5] } },
        { prompt: 'At d = 3, compare with a Gaussian exp(−d²/2): the Student-t value? (Two decimals.)', number: 0.1, tolerance: 0.005, show: '`1/10 = 0.10`' },
        { prompt: 'The Gaussian value at d = 3? (Four decimals.)', number: Math.exp(-4.5), tolerance: 1e-4, show: '`e^(−4.5) ≈ 0.0111`', why: 'Nine times larger for the Student-t: moderate map distances still count as somewhat similar, so clusters can spread out.' },
      ],
      result: 'Heavy tails give t-SNE room to separate clusters without crushing each one.',
    },
    experiment: 'In the t-SNE view, switch perplexity between 5, 20 and 50 and read the spread and distance ratios. Which setting distorts the true 4 : 1 ratios most?',
    question: 'A point’s neighbour distribution has entropy 4.32 bits. What is its perplexity, 2^H? (Nearest whole number.)',
    answer: 20, tolerance: 0.5,
    explanation: '2^4.32 ≈ 20: the point behaves as if it had about 20 equally likely neighbours.',
    reflection: 'Why might a t-SNE plot of your model’s embeddings look clustered even if the embeddings are not?',
  },
  {
    id: 'l51-honest',
    title: '51.5 · Reading maps honestly — and UMAP',
    sections: ['What t-SNE preserves', 'What it does not', 'Checks before believing', 'UMAP', 'Demonstrate understanding'],
    skill: 'Interpret nonlinear embeddings without over-reading them and choose between t-SNE, UMAP and simpler methods.',
    prerequisite: 'Lessons 51.1–51.4.',
    paragraphs: [
      't-SNE reliably shows which points are neighbours, and often which groups exist. That is useful for exploring embeddings, spotting mislabelled examples and finding sub-populations.',
      'It does **not** preserve cluster sizes (a tight and a wide cluster come out similar), distances between clusters (a far cluster may look close), densities, or the meaning of axes. In the playground, at perplexity 5 the 4 : 1 spread ratio becomes about 1 : 1 and the 4.2 : 1 distance ratio about 1.2 : 1; PCA keeps both roughly.',
      'Before believing a structure: compare several perplexities and seeds; check that the “clusters” exist in the original space (e.g. with k-means or distances); colour the map by known variables; and never compute statistics or train models on t-SNE coordinates.',
      '**UMAP** builds a fuzzy neighbourhood graph and optimizes a cross-entropy between graph and map. It is faster, scales better and tends to keep somewhat more global structure than t-SNE, but the same cautions apply; its n_neighbors and min_dist parameters play the role of perplexity.',
      'You have completed this lab when you can: choose what a reduction should preserve; separate mixed signals with ICA and explain its limits; compute Isomap from a neighbourhood graph and classical MDS; explain perplexity, crowding and the t-SNE objective; and read nonlinear maps honestly. The Python challenge implements whitening, FastICA, t-SNE’s perplexity calibration and classical MDS.',
    ],
    formula: 'trust: neighbourhoods     do not trust: sizes, gaps, densities, axes',
    derivation: {
      title: 'Spot the distortion',
      steps: [
        { prompt: 'True cluster spreads 0.5 and 2 give a ratio of? ', number: 4, show: '`4`' },
        { prompt: 'In a t-SNE map the spreads are 2.8 and 4.9. Ratio? (Two decimals.)', number: 4.9 / 2.8, tolerance: 0.01, show: '`1.75`', why: 'The wide cluster looks less than half as “wide” as it is, relative to the tight one.' },
      ],
      result: 'Sizes in a t-SNE map say more about perplexity than about the data.',
    },
    experiment: 'In the t-SNE view, change the random start at perplexity 20. Which features of the picture stay the same, and which change?',
    question: 'In a t-SNE map, cluster A looks twice as large as cluster B. What can you conclude about their spread in the original space?',
    choices: [
      { text: 'A is about twice as spread out', why: 't-SNE adapts to local density and tends to equalize cluster sizes; map size is not original spread.' },
      { text: 'Nothing reliable — measure it in the original space', why: 'Sizes and gaps between clusters in t-SNE are not faithful.' },
      { text: 'A has twice as many points', why: 'Area in the map does not track counts either.' },
    ],
    answer: 1,
    explanation: 'Nothing reliable: t-SNE adapts to local density and equalizes cluster sizes. Measure spreads in the original space.',
    reflection: 'Find a t-SNE or UMAP plot you have seen presented as evidence. What claim did it support, and would it survive these checks?',
  },
]

export const sources = [
  { title: 'Hyvärinen & Oja (2000) · Independent component analysis: algorithms and applications', url: 'https://doi.org/10.1016/S0893-6080(00)00026-5' },
  { title: 'Tenenbaum, de Silva & Langford (2000) · A global geometric framework for nonlinear dimensionality reduction (Isomap)', url: 'https://doi.org/10.1126/science.290.5500.2319' },
  { title: 'van der Maaten & Hinton (2008) · Visualizing data using t-SNE', url: 'https://www.jmlr.org/papers/v9/vandermaaten08a.html' },
  { title: 'Wattenberg, Viégas & Johnson (2016) · How to use t-SNE effectively (Distill)', url: 'https://distill.pub/2016/misread-tsne/' },
]
