export const lessons = [
  {
    id: 'l35-feedback',
    title: '35.1 · Feedback, not labels',
    sections: ['What a recommender does', 'Explicit and implicit feedback', 'Missing is not negative', 'The popularity baseline', 'Put it into practice'],
    skill: 'Frame a recommendation problem on implicit feedback and establish a popularity baseline.',
    prerequisite: 'Core labs 01–33; evaluation (Lab 06), k-NN similarity (Lab 10), matrices (Lab 03).',
    paragraphs: [
      'A recommender ranks items — products, articles, tutorials — for each user. Its output is an ordered list, and only the first few positions matter, because users rarely look further.',
      '**Explicit feedback** is a stated opinion: ratings, thumbs up or down. It is informative but scarce. **Implicit feedback** is behaviour: opens, clicks, purchases, watch time. It is plentiful but ambiguous — an open may be curiosity, and most items were simply never seen.',
      'Store implicit data as a users × items matrix of 0s and 1s. A 0 means "no interaction observed", **not** "disliked": the user may never have been shown the item. Treating every 0 as negative teaches the model to reproduce whatever the old system happened to show.',
      'The first baseline is **popularity**: recommend the most-opened items the user has not seen yet. It needs no personal data, works for new users, and is surprisingly hard to beat on accuracy — but every user gets the same list, and most of the catalog is never shown.',
      'Procedure: define the interaction that counts (opened? finished?), the moment of recommendation, and the list length. Build the matrix from past interactions only, compute the popularity baseline, and measure it before anything else.',
    ],
    formula: 'R[u, i] = 1 if user u interacted with item i, else 0 (unknown)     popularity(i) = Σᵤ R[u, i]',
    experiment: 'Choose "Most popular" and look at several users. Then open a user whose favourite topic is not Python. How many of the popular items suit them (true click chance above 50%)?',
    question: 'A catalog has 24 tutorials and 120 users each opened 6 on average. What fraction of the user × item matrix is filled with 1s? (Decimal.)',
    answer: 0.25,
    explanation: '120 × 6 = 720 ones out of 120 × 24 = 2880 cells: 0.25. Real catalogs are far sparser — often below 0.1%.',
    reflection: 'In a product you use, what counts as positive implicit feedback? What does an ignored recommendation tell you?',
  },
  {
    id: 'l35-cf',
    title: '35.2 · Collaborative filtering',
    sections: ['People who opened this also opened…', 'Cosine similarity between items', 'Scoring unseen items', 'Matrix factorization', 'Cold start'],
    skill: 'Implement item-item collaborative filtering and explain matrix factorization and cold start.',
    prerequisite: 'Lesson 35.1; cosine similarity (Lab 34), least squares and regularization (Labs 02, 07), PCA (Lab 18).',
    paragraphs: [
      '**Collaborative filtering** uses the behaviour of all users, not item descriptions. Item-item filtering asks: which items tend to be opened by the same people?',
      'Each item is a column of the matrix — a vector over users. The **cosine similarity** of two columns is the number of users who opened both, divided by √(count₁ · count₂). Items with no users in common score 0.',
      'To score an unseen item j for user u, add up its similarity to every item u has opened: `score(u, j) = Σᵢ R[u, i] · S[i, j]`. Recommend the top k unseen items. Item similarities change slowly, so they can be precomputed.',
      '**Matrix factorization** approximates R ≈ U Vᵀ: each user and item gets a short vector of learned "taste" numbers (here 4), and a score is their dot product. Alternating least squares fixes V and solves a ridge regression for each user, then swaps (Labs 02, 07). Unobserved cells get a small weight because they are uncertain, not negative.',
      '**Cold start**: a new user has no history, so every personalized score is 0 and the order is arbitrary; a new item has no interactions, so it is never recommended. Fall back to popularity, ask for interests at sign-up, or use content features such as the item\'s topic.',
    ],
    formula: 'S[i, j] = Rᵢ·Rⱼ / (‖Rᵢ‖ ‖Rⱼ‖)     score(u, j) = Σᵢ R[u, i] S[i, j]     R ≈ U Vᵀ',
    experiment: 'Compare item-item and matrix-factorization lists for the same user, then choose "Brand-new user". What happens to the scores?',
    question: 'Item A was opened by 9 users, item B by 4, and 3 users opened both. What is their cosine similarity? (Decimal.)',
    answer: 0.5,
    explanation: '3 / √(9 × 4) = 3 / 6 = 0.5.',
    reflection: 'For a new user in your product, what could you ask or observe in the first minute to escape the cold start?',
  },
  {
    id: 'l35-offline',
    title: '35.3 · Offline evaluation without leakage',
    sections: ['Hold out the future', 'Hit rate and NDCG', 'Beyond accuracy', 'Offline is not online', 'A/B tests'],
    skill: 'Evaluate recommenders with a time-aware split and ranking metrics, and state what offline evaluation cannot show.',
    prerequisite: 'Lessons 35.1–35.2; leakage and time splits (Lab 06), ranking metrics (Lab 34).',
    paragraphs: [
      'Recommendation predicts the **next** interaction from the past. Hold out each user\'s most recent interaction, train on everything before, and check whether it appears in the top k. Hiding a random interaction instead lets the model learn from things the user did later — a leak that inflates every score.',
      '**Hit rate@k**: the share of users whose held-out item appears in their top k. **NDCG@k** also rewards rank: a hit at position p scores 1/log₂(p + 1), so first place scores 1, second 0.63, third 0.5.',
      'Accuracy is not everything. **Coverage** — the share of the catalog that is ever recommended — and diversity matter to users and to the business. A popularity list can score well while recommending only a handful of items.',
      'Offline evaluation replays logged data, and the log only contains what the old system chose to show. A new model that recommends items the old one never showed gets no credit for them, even if users would have loved them. Offline results rank candidates; they do not measure real impact.',
      'Real impact is measured online with a randomized experiment (Lab 36): randomly assign users to the old and new recommender and compare the outcome that matters, such as tutorials completed.',
    ],
    formula: 'hit@k = mean(1[held-out ∈ top k])     NDCG@k = mean(1 / log₂(rank + 1)) for hits, 0 otherwise',
    experiment: 'In "Offline evaluation", switch between the time-aware and random hold-out. By how many points does each method\'s hit rate change?',
    question: 'The held-out item appears at rank 3 of the top 5. What is its NDCG contribution, 1/log₂(rank + 1)? (Decimal.)',
    answer: 0.5,
    explanation: 'log₂(4) = 2, so 1/2 = 0.5. At rank 1 it would be 1, and outside the top k it would be 0.',
    reflection: 'Name one thing your offline evaluation could never reward, because the old system never showed it.',
  },
  {
    id: 'l35-loops',
    title: '35.4 · Feedback loops and exploration',
    sections: ['The system shapes its data', 'Rich get richer', 'Exploration', 'Logging for the future', 'Demonstrate understanding'],
    skill: 'Explain recommendation feedback loops and use exploration to counter them.',
    prerequisite: 'Lessons 35.1–35.3; monitoring (Lab 30), responsible decisions (Lab 31).',
    paragraphs: [
      'A deployed recommender decides what users see, users can only click what they see, and those clicks train the next model. The system writes its own future training data.',
      'The loop concentrates exposure: popular items get shown, get clicked and become more popular, while items never shown can never gain clicks — however good they are. The playground\'s popularity recommender initially shows about a fifth of the catalog to everyone.',
      '**Exploration** reserves some slots for items the model is unsure about (here: random unseen tutorials). It costs a little immediate click-through, but reveals preferences the model could not otherwise learn. In the simulator, item-item filtering with about 30% exploration finds more of what users like after 12 rounds than with none — and purely random lists do worse than both.',
      'Log what was shown, not only what was clicked, and the probability with which each item was chosen. These logs make it possible to evaluate a new policy on old data fairly (off-policy evaluation), and to spot items that are never shown.',
      'You have completed this specialization when you can: frame a problem on implicit feedback; build popularity, item-item and factorization recommenders; evaluate them with a time-aware split, ranking metrics and coverage; handle cold start; and explain feedback loops, exploration and why online experiments are the final judge. The Python challenge implements item-item filtering and its evaluation.',
    ],
    formula: 'slate = (1 − ε) · model\'s top picks + ε · exploration     log (shown, clicked, probability)',
    experiment: 'In "Feedback loop over time", move exploration from 0% to 100%. Where is discovery after 12 rounds highest? What happens to first-round click-through?',
    question: 'Each user sees 3 tutorials per round and exploration is 30%. On average, how many slots per user per round go to exploration? (Decimal.)',
    answer: 0.9,
    explanation: '3 × 0.3 = 0.9 slots: about one exploratory tutorial per user per round.',
    reflection: 'Which items in your product might never get a chance because the current system never shows them?',
  },
]

export const sources = [
  { title: 'Hu, Koren & Volinsky (2008) · Collaborative filtering for implicit feedback datasets', url: 'https://doi.org/10.1109/ICDM.2008.22' },
  { title: 'Sarwar et al. (2001) · Item-based collaborative filtering recommendation algorithms', url: 'https://doi.org/10.1145/371920.372071' },
  { title: 'Chaney, Stewart & Engelhardt (2018) · How algorithmic confounding in recommendation systems increases homogeneity', url: 'https://arxiv.org/abs/1710.11214' },
  { title: 'Google · Recommendation systems course', url: 'https://developers.google.com/machine-learning/recommendation' },
]
