// Lesson order for Lab 33: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l33-choose': [
    { p: 0 }, { p: 1 },
    { predict: { prompt: 'A build’s timeout is set by a documented table: a limit per language, doubled on shared runners. A lookup table implements the table exactly. What is its mean absolute error, in seconds?', answer: 0, explain: '0: the rule is the definition of the target. A linear model on the same inputs does worse (97.6 s in the cell) because the doubling is multiplicative — and it would need data, training and monitoring for nothing.' } },
    { cell: 0 },
    { p: 2 },
    { bridge: { label: 'Data for your project: what is bundled, and how to collect your own', title: '', body: ["**Bundled, licensed data you can start from today.** The build log of this lab (`python buildtime_app.py data`, 3,000 builds over 60 days, generated — so no permissions are needed); and the real datasets bundled with scikit-learn, which run in these notebooks: diabetes (442 patients, a regression target), breast cancer (569 cases, a binary label), wine (178 samples, three classes) and digits (1,797 small images, Lab 27).", "**Collecting your own.** (1) Name the decision and the moment it is made. (2) At that moment, log one row per event with a timestamp and only the inputs that exist then. (3) When the outcome is known, log it against the same event id. (4) Write the data contract (Lab 28) before the first row and validate every batch. (5) Check you may use the data for this purpose (Lab 31). (6) Collect for two to four weeks before modelling; a few hundred rows is enough for a first honest comparison.", "**When not to use ML.** If a documented rule or a lookup table already defines the answer — a timeout table, a price list, a routing policy — implement the rule. ML earns its cost only where patterns exist in data but no reliable explicit rule does."] } },
    { p: 3 }, { p: 4 },
    { cell: 1 },
    { math: true },
  ],
  'l33-evidence': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { predict: { prompt: 'The full model’s fold-by-fold improvements over the baseline are +28.80, +32.17, +28.04 and +24.75 s. What is the mean? (Two decimals.)', answer: 28.44, tolerance: 0.01, explain: '(28.80 + 32.17 + 28.04 + 24.75)/4 = 28.44 s — and even the smallest fold (+24.75 s) is far above a 2 s threshold, so here the fold picture is unambiguous.' } },
    { p: 2 },
    { figure: 'PairedFolds', caption: 'Five paired fold differences, their mean and the threshold you set in advance. Compare the three sets.' },
    { figure: 'FoldDesign', caption: '240 builds in time order, during which shared runners get busier. The same comparison with random folds and with forward chaining.' },
    { p: 3 },
    { cell: 1 },
    { predict: { prompt: 'The test improvement is 29.86 s with a 95% interval of 26.32 to 33.59 s. If the threshold set in advance had been 30 s, what would the decision rule give? (1 = ship, 2 = inconclusive, 3 = reject)', answer: 3, explain: 'Reject: the point estimate 29.86 s is below 30 s. (Ship needs the lower bound above the threshold; inconclusive needs at least the point estimate above it.) The threshold is a product decision, made before seeing results — which is exactly why it can bite.', misconceptions: [{ answer: 2, feedback: 'Inconclusive needs the point estimate above the threshold; 29.86 is below 30.' }] } },
    { p: 4 },
    { cell: 2 },
    { math: true },
  ],
  'l33-ship': [
    { p: 0 }, { p: 1 },
    { cell: 0 }, { cell: 1 },
    { p: 2 }, { p: 3 },
    { predict: { prompt: 'With 50 builds a day, the daily size PSI on quiet development days has a median of about 0.19. Would the 0.1 rule of thumb make a sensible alert threshold here? (1 = yes, 0 = no)', answer: 0, explain: 'No: more than half of all quiet days would alert. The cell sets the threshold at the 99th percentile of quiet days (0.410), as in Lab 30.' } },
    { cell: 2 },
    { bridge: { label: 'The same project as a real application (run on your own machine)', title: '', body: ["A browser page cannot run a server, so the worked exemplar also ships as `buildtime_app.py` (Implement tab). It uses the same generator, split, candidates and decision as the cells, so the numbers agree. `python buildtime_app.py check` writes the data, trains and evaluates, writes `artifact.json` and `model_card.md`, starts the HTTP service, sends real requests, and runs the monitor on a normal day and on a day with sizes in KB. Its output when it was run for this lesson (Python 3.12, NumPy 2):"], output: "3000 builds over 60 days; development days 0-47 (2400 builds), test days 48-59 (600 builds)\n  mean   forward-fold MAE: 36.87  40.24  36.27  31.95   mean 36.33 s\n  simple forward-fold MAE: 22.64  22.16  22.29  19.64   mean 21.68 s\n  full   forward-fold MAE:  8.07   8.07   8.24   7.19   mean  7.89 s\n  baseline − simple, fold by fold: +14.23  +18.08  +13.99  +12.31   (mean +14.65 s)\n  baseline − full, fold by fold: +28.80  +32.17  +28.04  +24.75   (mean +28.44 s)\ntest: baseline MAE 37.91 s, full MAE 8.05 s; improvement 29.86 s (95% interval 26.32 to 33.59); threshold 2.0 s -> ship\ntest MAE by segment: dedicated runner, cache hit 9.1 s (n = 144), dedicated runner, cache miss 8.2 s (n = 149), shared runner, cache hit 7.6 s (n = 130), shared runner, cache miss 7.4 s (n = 177)\nwrote artifact.json and model_card.md (decision: ship)\nPASS the evidence clears the pre-set threshold (decision: ship)\nPASS artifact.json and model_card.md were written\nPASS parity over HTTP on 20 requests (largest difference 2.8e-14 s)\nPASS unknown language -> 422\nPASS broken JSON -> 400\nPASS a JSON list -> 400\nquiet.csv: 50 builds; size PSI 0.206 (threshold 0.410) -> ok; predictions outside the guard: 0\nPASS a normal day raises no alert\nkb_bug.csv: 50 builds; size PSI 8.283 (threshold 0.410) -> ALERT; predictions outside the guard: 7\nPASS sizes sent in KB: drift alert and guard violations\nPASS: data, evidence, artifact, service and monitoring all work end to end" } },
    { p: 4 },
    { math: true },
  ],
  'l33-mastery': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { predict: { prompt: 'The exemplar’s test MAE is 8.05 s against a baseline of 37.91 s. By what percentage is the error lower? (Nearest whole percent.)', answer: 79, tolerance: 0.5, explain: '1 − 8.05/37.91 = 0.788: 79% lower. Report both the absolute improvement (29.86 s, with its interval) and the relative one; readers need both.' } },
    { p: 2 }, { p: 3 },
    { bridge: { label: 'Milestones and rubric for your final project', title: '', body: ["**Milestone 1 — frame and collect.** Problem framing (decision, target, prediction moment, success threshold) and a data contract, in the workbench. Collect or choose the data.", "**Milestone 2 — evidence.** Test set set aside; baseline with uncertainty; two or three declared candidates on the same folds; error analysis by segment; one test evaluation; a decision against the threshold.", "**Milestone 3 — ship.** An artifact with its preprocessing; a batch job or small API with contract, parity and golden tests; a model card whose limitations come from your evidence.", "**Milestone 4 — operate.** Monitoring thresholds from quiet data, a guard, a runbook with a tested rollback, a retraining trigger with gates, and a named owner.", "**Rubric.** The next cell checks each criterion against the exemplar’s actual artifacts. Your project passes when every criterion is backed by something a reviewer can open and re-run. “The baseline was as good, so we did not deploy” can pass every criterion."] } },
    { cell: 1 },
    { p: 4 },
    { math: true },
    { ladder: 'capstone' },
  ],
}
