export const lessons = [
  {
    id: 'l33-choose',
    title: '33.1 · Choose a problem worth solving',
    sections: ['Start from a decision', 'Is ML the right tool?', 'Data you can actually get', 'Scope small', 'Put it into practice'],
    skill: 'Select a capstone problem with a real decision, obtainable data and a measurable baseline.',
    prerequisite: 'Labs 01–32. This lab ties them together.',
    paragraphs: [
      'A good capstone starts from a decision someone makes repeatedly — which build runner to use, which ticket to review first, how much capacity to reserve — where a better prediction would change what they do. "Predict X" without a decision attached produces a model nobody uses.',
      'Check that ML is the right tool (Lab 01): if an exact rule already computes the answer, use it. ML earns its cost when patterns exist in data but no reliable explicit rule does, and when errors are tolerable and measurable.',
      'Choose data you can actually obtain, legally use and keep collecting (Labs 28, 31). Your own measured project data — build logs, sensor readings, support tickets — is ideal: you understand its quirks, and the model will face the same process after deployment.',
      'Scope small: one target, a handful of features, a few hundred to a few thousand rows, one decision. A complete, honest small project teaches more than an ambitious one that never reaches evaluation, deployment and monitoring.',
      'Procedure: list three candidate problems; for each write the decision, the target, the prediction moment, the data source and the simplest baseline; pick the one with the clearest decision and most accessible data. Record it in the project workbench.',
    ],
    formula: 'good problem = repeated decision + measurable target + obtainable data + simple baseline',
    experiment: 'In the workbench, write the "Problem framing" section for your chosen project. Then paste a small sample of its data into "Try it on your own data".',
    question: 'You have logged 30 builds per day for 20 working days. How many rows is that?',
    answer: 600,
    explanation: '30 × 20 = 600 rows — enough for an honest first model with cross-validation and a held-out test period.',
    reflection: 'Write the one-sentence decision your capstone model will support, and who makes it.',
  },
  {
    id: 'l33-evidence',
    title: '33.2 · Build the evidence',
    sections: ['A test set first', 'Baseline before model', 'Honest comparison', 'Error analysis', 'Decide on evidence'],
    skill: 'Run the modelling phase of a capstone with honest splits, baselines and error analysis.',
    prerequisite: 'Lesson 33.1; evaluation (Lab 06), the tabular and deep-learning capstones (Labs 16, 27).',
    paragraphs: [
      'Before exploring, set aside a test set — for time-ordered data, the most recent period (Labs 06, 19). Do everything else on the development data.',
      'Build the baseline first and report it with uncertainty (Lab 05). Then try a small, pre-declared set of candidates on the same folds (Labs 16, 27). The "try your own data" view gives a first feasibility check: does a simple linear model beat the mean at all?',
      'Treat a small dataset\'s cross-validation with humility: with 20 rows, one fold can swing the picture. Look at the per-fold results, not just the mean, and prefer the simpler model when the difference is within noise.',
      'Analyse errors by segment and by reading examples (Labs 16, 31): which cases does the model get badly wrong, and why? Each finding suggests the next feature, more data, or a limitation to document.',
      'Decide against the success threshold you wrote before modelling. Evaluate once on the test set. "The baseline is as good; we recommend not deploying" is a valid and valuable outcome.',
    ],
    formula: 'test set aside → baseline ± uncertainty → candidates on the same folds → errors → one test evaluation → decision',
    experiment: 'With the sample data, compare random folds and forward chaining (time order). Remove features one at a time: which one matters most?',
    question: 'In 5-fold cross-validation, the model beats the baseline in 3 folds and loses in 2. Is that strong evidence of improvement? (1 = yes, 0 = no)',
    answer: 0,
    explanation: '3 of 5 is close to a coin flip; the evidence is weak. Collect more data, examine the losing folds, or report the result as inconclusive.',
    reflection: 'What success threshold did you set for your capstone before seeing any results?',
  },
  {
    id: 'l33-ship',
    title: '33.3 · Ship it responsibly',
    sections: ['Package', 'Serve', 'Document', 'Monitor', 'Maintain'],
    skill: 'Plan the deployment, documentation, monitoring and maintenance of a capstone model.',
    prerequisite: 'Lessons 33.1–33.2; Labs 28–32.',
    paragraphs: [
      'Package a reproducible run: versioned data, configuration, code and environment (Lab 28), with the model artifact containing its preprocessing (Lab 29).',
      'Serve it the simplest way that meets the need — often a batch job writing predictions to a table, or a small API with a documented contract, parity and golden tests (Lab 29). Measure latency on real hardware.',
      'Write the model card from your evidence: intended use, out-of-scope uses, data and permissions, results by relevant slices, limitations, human oversight (Lab 31).',
      'Monitor inputs, predictions and outcomes with thresholds tuned on quiet periods, guards on the output range, and a runbook with a tested rollback (Labs 30, 32).',
      'Plan maintenance: who owns the model, when it is retrained, which gates a new version must pass, and when the model should be retired. A model without an owner is technical debt from the day it ships.',
    ],
    formula: 'ship = reproducible artifact + tested serving path + model card + monitoring + rollback + owner',
    experiment: 'Fill in the Deployment and Operation sections of the workbench. Download the plan and read it as if you were the new owner.',
    question: 'The workbench has 15 items. You have drafted 12. What is your readiness percentage?',
    answer: 80,
    explanation: '12/15 = 0.8, i.e. 80%. The remaining items are exactly where the project is most likely to fail after launch.',
    reflection: 'Who would own your capstone model after you? What would they need from you on day one?',
  },
  {
    id: 'l33-mastery',
    title: '33.4 · What mastery looks like — and what comes next',
    sections: ['The whole loop', 'Signs of mastery', 'Keep practising', 'Optional specializations', 'Demonstrate understanding'],
    skill: 'Assess your own mastery against the full ML engineering loop and plan further study.',
    prerequisite: 'Lessons 33.1–33.3.',
    paragraphs: [
      'You have practised the full loop: frame a decision, collect and validate data, establish baselines, derive and implement models, evaluate honestly, deploy, monitor, retrain and document — from a line of algebra in Lab 01 to a release pipeline in Lab 32.',
      'Signs of mastery: you can derive and implement the core algorithms without looking them up; you predict how a change will affect results before running it; you diagnose failures by their signatures; you choose evaluation designs that match deployment; and you can explain every decision to someone who will maintain the system.',
      'Keep the skills alive: revisit a lab\'s Python challenge from a blank file after a break; re-run the playground experiments predicting each outcome first; and apply the capstone loop to a second, different problem.',
      'The optional specializations — retrieval and language-model applications, recommender systems, causal inference, reinforcement learning, research replication — build on this core. Choose one because a project needs it.',
      'You have completed the core curriculum when your capstone has: reproducible evidence, a tested serving path, a working demo, a model card with evidence-based limitations, and an honest maintenance plan. The Python challenge assembles a compact version of that pipeline.',
    ],
    formula: 'frame → data → baseline → model → evaluate → deploy → monitor → retrain → document → repeat',
    experiment: 'Download your project plan. Beside each item, write the lab you would revisit if you got stuck on it.',
    question: 'There are 33 core labs. If you complete one per week, how many weeks does the core take?',
    answer: 33,
    explanation: '33 weeks — and revisiting earlier labs as you go is part of the plan, not a detour.',
    reflection: 'Which lab felt hardest? Write down one experiment you will repeat to solidify it.',
  },
]

export const sources = [
  { title: 'Google · Rules of Machine Learning', url: 'https://developers.google.com/machine-learning/guides/rules-of-ml' },
  { title: 'Chip Huyen · Designing Machine Learning Systems', url: 'https://huyenchip.com/books/' },
  { title: 'Mitchell et al. (2019) · Model cards for model reporting', url: 'https://arxiv.org/abs/1810.03993' },
]
