export const lessons = [
  {
    id: 'l33-choose',
    title: '33.1 · Choose a problem worth solving',
    sections: ['Start from a decision', 'Is ML the right tool?', 'Data you can actually get', 'Scope small', 'Put it into practice'],
    skill: 'Select a capstone problem with a real decision, obtainable data and a measurable baseline.',
    prerequisite: 'Labs 01–32. This lab ties them together.',
    paragraphs: [
      'A good capstone starts from a decision someone makes repeatedly — which build runner to use, which ticket to review first, how much capacity to reserve — where a better prediction would change what they do. "Predict X" without a decision attached produces a model nobody uses.',
      'Check that ML is the right tool (Lab 01): if an exact rule already computes the answer, use it. ML earns its cost when patterns exist in data but no reliable explicit rule does, and when errors are tolerable and measurable.',
      'Choose data you can actually obtain, legally use and keep collecting (Labs 28, 31). Your own measured project data — build logs, sensor readings, support tickets — is ideal: you understand its quirks, and the model will face the same process after deployment.',
      'Scope small: one target, a handful of features, a few hundred to a few thousand rows, one decision. A complete, honest small project teaches more than an ambitious one that never reaches evaluation, deployment and monitoring.',
      'Procedure: list three candidate problems; for each write the decision, the target, the prediction moment, the data source and the simplest baseline; pick the one with the clearest decision and most accessible data. Record it in the project workbench.',
    ],
    formula: 'good problem = repeated decision + measurable target + obtainable data + simple baseline',
    experiment: 'In the workbench, write the "Problem framing" section for your chosen project. Then paste a small sample of its data into "Try it on your own data".',
    question: 'Which of these candidates is ready to become your capstone?',
    choices: [
      { text: 'Predict each build’s duration from the commit’s size, changed modules and runner type. The release team uses the prediction to reserve fast runners, and 18 months of build logs already exist.', why: 'It has a repeated decision (reserve a runner), a measurable target (duration), features known before the build starts, data you already hold, and an obvious baseline (the median duration per module).' },
      { text: 'Predict a file’s SHA-256 checksum from its contents.', why: 'An exact rule already computes the answer. ML earns its cost only where no reliable explicit rule exists (Lab 01).' },
      { text: 'Predict which customers will leave next year, using a table we will start collecting next quarter. Nobody has said what they would do with the prediction.', why: 'Two blockers: there is no data yet, and no decision is attached. A prediction that changes nothing is a model nobody uses.' },
      { text: 'Predict whether a pull request will be merged, using the reviewer’s final comment as a feature.', why: 'The final comment is written after the outcome is known — leakage (Lab 06). The model would look excellent and be useless at prediction time.' },
    ],
    answer: 0,
    explanation: 'Check each candidate against the formula: repeated decision + measurable target + obtainable data + simple baseline — and confirm every feature exists at the moment of prediction.',
    reflection: 'Write the one-sentence decision your capstone model will support, and who makes it.',
  },
  {
    id: 'l33-evidence',
    title: '33.2 · Build the evidence',
    sections: ['A test set first', 'Baseline before model', 'Honest comparison', 'Error analysis', 'Decide on evidence'],
    skill: 'Run the modelling phase of a capstone with honest splits, baselines and error analysis.',
    prerequisite: 'Lesson 33.1; evaluation (Lab 06), the tabular and deep-learning capstones (Labs 16, 27).',
    paragraphs: [
      'Before exploring, set aside a test set — for time-ordered data, the most recent period (Labs 06, 19). Do everything else on the development data.',
      'Build the baseline first and report it with uncertainty (Lab 05). Then try a small, pre-declared set of candidates on the same folds (Labs 16, 27). The "try your own data" view gives a first feasibility check: does a simple linear model beat the mean at all?',
      'Treat a small dataset\'s cross-validation with humility: with 20 rows, one fold can swing the picture. Compare models **fold by fold on the same folds** and look at the size of each difference, not only who won: “3 wins out of 5” says nothing about whether the wins were large and the losses tiny, or the reverse. Fold scores also share most of their training rows, so they are not independent — even a careful average of the differences overstates your certainty. Prefer the simpler model when the difference is small next to the success threshold you set in advance.',
      'Analyse errors by segment and by reading examples (Labs 16, 31): which cases does the model get badly wrong, and why? Each finding suggests the next feature, more data, or a limitation to document.',
      'Decide against the success threshold you wrote before modelling. Evaluate once on the test set. "The baseline is as good; we recommend not deploying" is a valid and valuable outcome.',
    ],
    formula: 'test set aside → baseline ± uncertainty → candidates on the same folds → errors → one test evaluation → decision',
    experiment: 'With the sample data, compare random folds and forward chaining (time order). Remove features one at a time: which one matters most?',
    question: 'On the same five folds, baseline MAE minus model MAE is +4.1, +3.8, +5.0, −0.4 and −0.6 seconds. Before modelling, you set a success threshold of a 2-second improvement. What is the most defensible next step?',
    choices: [
      { text: 'Reject the model: it won only 3 of 5 folds, which is close to a coin flip.', why: 'Counting wins throws away the sizes. Here the three wins are large and the two losses tiny; five other differences could also give 3 of 5 and mean the opposite.' },
      { text: 'Ship it: the mean improvement of 2.4 s beats the threshold.', why: 'The mean clears the bar, but five correlated fold scores are thin evidence, and two folds went the other way. You have not yet asked why, or confirmed on untouched data.' },
      { text: 'Treat it as promising: inspect what the two losing folds contain, then evaluate once on the untouched test set against the 2-second threshold.', why: 'This uses the effect sizes, investigates the disagreement, and makes the decision on data that played no part in choosing the model.' },
    ],
    answer: 2,
    explanation: 'The mean paired difference is (4.1 + 3.8 + 5.0 − 0.4 − 0.6)/5 = 2.38 s. Whether that convinces depends on the effect size relative to your threshold, the spread of the differences and the evaluation design — not on a win count. Fold scores share training rows, so use cross-validation to choose, and the single test evaluation as the evidence.',
    reflection: 'What success threshold did you set for your capstone before seeing any results?',
  },
  {
    id: 'l33-ship',
    title: '33.3 · Ship it responsibly',
    sections: ['Package', 'Serve', 'Document', 'Monitor', 'Maintain'],
    skill: 'Plan the deployment, documentation, monitoring and maintenance of a capstone model.',
    prerequisite: 'Lessons 33.1–33.2; Labs 28–32.',
    paragraphs: [
      'Package a reproducible run: versioned data, configuration, code and environment (Lab 28), with the model artifact containing its preprocessing (Lab 29).',
      'Serve it the simplest way that meets the need — often a batch job writing predictions to a table, or a small API with a documented contract, parity and golden tests (Lab 29). Measure latency on real hardware.',
      'Write the model card from your evidence: intended use, out-of-scope uses, data and permissions, results by relevant slices, limitations, human oversight (Lab 31).',
      'Monitor inputs, predictions and outcomes with thresholds tuned on quiet periods, guards on the output range, and a runbook with a tested rollback (Labs 30, 32).',
      'Plan maintenance: who owns the model, when it is retrained, which gates a new version must pass, and when the model should be retired. A model without an owner is technical debt from the day it ships.',
    ],
    formula: 'ship = reproducible artifact + tested serving path + model card + monitoring + rollback + owner',
    experiment: 'Fill in the Deployment and Operation sections of the workbench. Download the plan and read it as if you were the new owner.',
    question: 'A retrained model improves test MAE by 12% over the one in production. Which pre-release finding should block the release?',
    choices: [
      { text: 'p95 latency rose from 40 ms to 55 ms; the documented budget is 100 ms.', why: 'Worth recording, but inside the agreed budget. A release gate is a threshold decided in advance, not any change at all.' },
      { text: 'On the golden test inputs, the served model’s predictions differ from the offline predictions by up to 30%, because the service computes a rolling-mean feature over a different window.', why: 'A parity failure (Lab 29): the model users would receive is not the model you evaluated, so the 12% improvement no longer describes it.' },
      { text: 'The model card lists poor accuracy on builds over 2 GB — 1% of traffic, which is already routed to manual review.', why: 'A documented, measured limitation with a human fallback is what a model card is for. Hiding it would be the problem.' },
    ],
    answer: 1,
    explanation: 'Evidence only transfers to deployment if the served prediction path matches the evaluated one. Golden tests and offline–online parity checks exist to catch exactly this before users see it.',
    reflection: 'Who would own your capstone model after you? What would they need from you on day one?',
  },
  {
    id: 'l33-mastery',
    title: '33.4 · What mastery looks like — and what comes next',
    sections: ['The whole loop', 'Signs of mastery', 'Keep practising', 'Optional specializations', 'Demonstrate understanding'],
    skill: 'Assess your own mastery against the full ML engineering loop and plan further study.',
    prerequisite: 'Lessons 33.1–33.3.',
    paragraphs: [
      'You have practised the full loop: frame a decision, collect and validate data, establish baselines, derive and implement models, evaluate honestly, deploy, monitor, retrain and document — from a line of algebra in Lab 01 to a release pipeline in Lab 32.',
      'Signs of mastery: you can derive and implement the core algorithms without looking them up; you predict how a change will affect results before running it; you diagnose failures by their signatures; you choose evaluation designs that match deployment; and you can explain every decision to someone who will maintain the system.',
      'Keep the skills alive: revisit a lab\'s Python challenge from a blank file after a break; re-run the playground experiments predicting each outcome first; and apply the capstone loop to a second, different problem.',
      'The optional specializations — retrieval and language-model applications, recommender systems, causal inference, reinforcement learning, research replication — build on this core. Choose one because a project needs it.',
      'You have completed the core curriculum when your capstone has: reproducible evidence, a tested serving path, a working demo, a model card with evidence-based limitations, and an honest maintenance plan. The Python challenge assembles a compact version of that pipeline.',
    ],
    formula: 'frame → data → baseline → model → evaluate → deploy → monitor → retrain → document → repeat',
    experiment: 'Download your project plan. Beside each item, write the lab you would revisit if you got stuck on it.',
    question: 'Which is the strongest evidence that you can do this work without the course?',
    choices: [
      { text: 'Every checkpoint in all 33 core labs shows a tick.', why: 'Checkpoints test one idea at a time, with the lesson open beside you. They are practice, not proof of independent skill.' },
      { text: 'A week after finishing, you rebuild a lab’s Python challenge from a blank file, predict playground results before running them, and a colleague reruns your capstone from its README and gets your numbers.', why: 'Recall without prompts, correct predictions and a reproducible project are what independent skill looks like from the outside.' },
      { text: 'Your capstone model has the best test accuracy of the eight models you tried.', why: 'Choosing among eight models on the test set turns it into a selection set (Lab 06), and one accuracy number says nothing about framing, deployment or maintenance.' },
    ],
    answer: 1,
    explanation: 'Mastery shows up as transfer: doing the work from a blank page, predicting before measuring, and leaving evidence someone else can reproduce.',
    reflection: 'Which lab felt hardest? Write down one experiment you will repeat to solidify it.',
  },
]

export const sources = [
  { title: 'Google · Rules of Machine Learning', url: 'https://developers.google.com/machine-learning/guides/rules-of-ml' },
  { title: 'Chip Huyen · Designing Machine Learning Systems', url: 'https://huyenchip.com/books/' },
  { title: 'Mitchell et al. (2019) · Model cards for model reporting', url: 'https://arxiv.org/abs/1810.03993' },
]
