export const lessons = [
  {
    id: 'l61-adversarial',
    title: '61.1 · Adversarial examples',
    sections: ['Small changes, wrong answers', 'The threat model', 'FGSM', 'Why linear models are vulnerable', 'Stronger attacks', 'Evaluating robustness honestly'],
    skill: 'Construct adversarial examples with FGSM and PGD and explain why high-dimensional models are vulnerable.',
    prerequisite: 'Backpropagation (Lab 20), a neural network classifier (Lab 21), logistic regression (Lab 08), norms (Lab 03).',
    paragraphs: [
      'An **adversarial example** is an input changed slightly and on purpose so that a model gets it wrong. Szegedy et al. (2014) found that image classifiers with excellent test accuracy could be fooled by changes invisible to people. The effect is not a quirk of one model: it appears in speech, text and tabular models too, and attacks crafted for one model often transfer to another.',
      'An attack is defined by a **threat model**: what the attacker may change and by how much. The most studied is the **L∞ ball**, where every input feature may change by at most ε. For images with pixels in [0, 1], ε = 0.03 is often invisible. The playground uses 5 × 7 digit images, where ε = 0.1 is a visible but faint change and the digit is still obvious.',
      'The **fast gradient sign method** (FGSM, Goodfellow et al. 2015) takes one step: x_adv = clip(x + ε·sign(∇ₓ L(x, y)), 0, 1). It computes the gradient of the loss with respect to the input rather than the weights, which is the same backward pass as training (Lab 20) carried one layer further, and moves every pixel by ε in whichever direction increases the loss.',
      'Why does such a small change work? Take a linear score wᵀx. The perturbation δ = ε·sign(w) changes it by ε·Σ|wⱼ| = ε‖w‖₁, which grows with the number of features d. Random ±ε noise changes the score by about ε·‖w‖₂, which grows only like √d. In high dimensions, many tiny aligned changes add up while random ones cancel. In the playground, random noise of size 0.1 leaves accuracy near 89%, and FGSM of the same size drops it to roughly 30%.',
      '**Projected gradient descent** (PGD, Madry et al. 2018) repeats smaller signed steps. After each step it projects back into the ε-box around x and into [0, 1], and it usually starts from a random point in the box. It is at least as strong as FGSM and is the standard first-order attack. Other threat models include L2 and L0 (few pixels) budgets, patches, rotations and, for text, word swaps.',
      'Robustness claims need strong, adaptive attacks. Many proposed defences only hid the gradient (gradient masking), and they fell to attacks designed around them (Athalye et al. 2018). Report accuracy under PGD with several restarts and many steps across a range of ε, check that accuracy reaches zero as ε grows, and use established benchmarks such as AutoAttack.',
    ],
    formula: 'x_FGSM = clip₀¹(x + ε·sign(∇ₓ L(f(x), y)))     x_{k+1} = Π_{‖x′ − x‖∞ ≤ ε}(x_k + α·sign(∇ₓ L))     Δ(wᵀx) ≤ ε‖w‖₁',
    derivation: {
      title: 'Why many tiny changes add up',
      steps: [
        { prompt: 'One pixel has weight w = −0.3 in a linear score. Which change δ in [−0.1, 0.1] increases the score the most?', number: -0.1, tolerance: 1e-9, show: '`δ = −0.1 = ε·sign(w)`: the score changes by `0.03`' },
        { prompt: 'Every one of d pixels has a weight of magnitude m. Write the largest possible change in the score for budget ε.', answer: 'ε*d*m', show: '`ε·d·m`, which is ε‖w‖₁', vars: { ε: [0.01, 0.3], d: [1, 1000], m: [0.01, 1] } },
        { prompt: 'With d = 35 pixels, m = 0.2 and ε = 0.1, how large is that change?', number: 0.7, tolerance: 1e-9, show: '`0.1 × 35 × 0.2 = 0.7`' },
        { prompt: 'If each pixel instead moves by a random ±ε, the changes are independent with variance ε²m² each. Write the standard deviation of the total change.', answer: 'ε*m*sqrt(d)', show: '`ε·m·√d`', vars: { ε: [0.01, 0.3], d: [1, 1000], m: [0.01, 1] } },
        { prompt: 'How many times larger is the targeted change than the random one’s standard deviation, for d = 35? (Two decimals.)', number: Math.sqrt(35), tolerance: 0.01, show: '`√35 ≈ 5.92`; for a 224 × 224 colour image, `√150528 ≈ 388`', why: 'The advantage of aiming grows with the square root of the dimension, which is why high-dimensional inputs are so exposed.' },
      ],
      result: 'An aligned perturbation changes a linear score by ε‖w‖₁ ∝ d, while random noise changes it by about ε‖w‖₂ ∝ √d: in high dimensions, small targeted changes win.',
    },
    experiment: 'Pick an image and raise ε until the prediction flips, first with FGSM and then with PGD. Compare the size of ε needed with how different the attacked image looks. Then compare the random-noise curve with the attack curves.',
    question: 'A logistic model has ‖w‖₁ = 12. By how much can an L∞ perturbation with ε = 0.05 change its logit at most?',
    answer: 0.6,
    tolerance: 1e-6,
    explanation: 'The maximum is ε‖w‖₁ = 0.05 × 12 = 0.6, reached by δ = ε·sign(w).',
    reflection: 'Who would have a reason to attack a model you know of, and what could they change about its input?',
  },
  {
    id: 'l61-advtrain',
    title: '61.2 · Adversarial training',
    sections: ['A min–max problem', 'Training on attacks', 'What robustness costs', 'Robust margins for linear models', 'Certified defences'],
    skill: 'Train a model against PGD attacks and measure the trade-offs between clean and robust accuracy.',
    prerequisite: 'Lesson 61.1; regularization (Lab 07); SVM margins (Lab 15).',
    paragraphs: [
      '**Adversarial training** (Madry et al. 2018) changes the objective from the average loss to the average worst-case loss inside the threat model: min_θ E[ max_{‖δ‖∞ ≤ ε} L(f_θ(x + δ), y) ]. The inner maximization is the attack and the outer minimization is training. By Danskin’s theorem, the gradient of the inner max is the gradient at the maximizing δ, so each step can find δ with PGD and then take an ordinary gradient step on x + δ.',
      'In practice, each training batch is replaced (or mixed) with attacked versions of itself, generated against the current weights. PGD training is several times more expensive than normal training, since each PGD step costs one forward and one backward pass. Single-step FGSM training is cheaper but can fail through **catastrophic overfitting**, where the model becomes robust to FGSM but not to PGD. Random starts and careful step sizes help.',
      'Robustness has costs. Robust models usually lose some clean accuracy, which is more pronounced on large, realistic datasets than in the playground. They also need more data and capacity, and their robustness is specific to the threat model: a model trained for ε = 0.15 in L∞ still fails at ε = 0.3 and may fail under rotations. In the playground, PGD training raises accuracy at ε = 0.15 from almost none to about a third.',
      'For a linear classifier with margin m = y·wᵀx, the worst L∞ perturbation lowers the margin to m − ε‖w‖₁. The robust logistic loss is then log(1 + exp(−(m − ε‖w‖₁))), so adversarial training acts like a margin requirement coupled with an L1 penalty (Lab 07) that grows with ε. It also reduces the size of the input gradient: in the playground, the average ‖∇ₓ loss‖₁ drops by more than half.',
      '**Certified defences** prove that no perturbation within ε can change the prediction. Examples are interval bound propagation, Lipschitz-constrained networks, and **randomized smoothing**, which predicts the majority class under Gaussian noise and certifies an L2 radius. Certificates are guarantees rather than the outcome of one attack, but they usually come with lower accuracy.',
    ],
    formula: 'min_θ E_{(x, y)} [ max_{‖δ‖∞ ≤ ε} L(f_θ(x + δ), y) ]     linear: worst margin = y·wᵀx − ε‖w‖₁',
    derivation: {
      title: 'Projection and the robust margin',
      steps: [
        { prompt: 'A pixel has x = 0.4 and ε = 0.1. A PGD step proposes 0.57. What value does it take after projecting onto [x − ε, x + ε]?', number: 0.5, tolerance: 1e-9, show: '`min(0.5, max(0.3, 0.57)) = 0.5`' },
        { prompt: 'A pixel has x = 0.95 and ε = 0.1, and a step proposes 1.04. After projecting onto the ε-box and onto [0, 1], what is its value?', number: 1, tolerance: 1e-9, show: '`1`: the ε-box allows up to 1.05, but pixels stop at 1' },
        { prompt: 'A linear classifier has margin m = y·wᵀx and ‖w‖₁ = L. Write the margin after the worst L∞ perturbation of size ε.', answer: 'm-ε*L', show: '`m − ε·L`', vars: { m: [0, 5], ε: [0, 0.3], L: [0, 30] } },
        { prompt: 'With m = 2, ‖w‖₁ = 12 and ε = 0.1, what is the worst-case margin?', number: 0.8, tolerance: 1e-9, show: '`2 − 1.2 = 0.8`: still correct, with less room' },
      ],
      result: 'Robust training asks every point to be correct with margin at least ε‖w‖₁, which is why it behaves like a margin-scaled L1 penalty for linear models.',
    },
    experiment: 'Compare the three curves at ε = 0.1, 0.15 and 0.2 and read the clean accuracy of each model. Then compare the gradient-norm numbers for the standard and robust models.',
    question: 'A linear classifier has margin 1.5 on a point and ‖w‖₁ = 20. What is the largest L∞ budget ε that cannot flip its prediction? (Three decimals.)',
    answer: 0.075,
    tolerance: 0.0005,
    explanation: 'The worst-case margin is 1.5 − 20ε, which stays positive while ε < 1.5/20 = 0.075.',
    reflection: 'Which threat model would matter for a model you know, and what would robustness to it cost?',
  },
  {
    id: 'l61-covariate',
    title: '61.3 · Covariate shift and importance weighting',
    sections: ['Kinds of distribution shift', 'Why a misspecified model cares', 'Importance weighting', 'Estimating the weights', 'The variance cost', 'Detecting shift'],
    skill: 'Correct a model for covariate shift with importance weights estimated by a domain classifier, and judge when it is safe.',
    prerequisite: 'Importance sampling (Lab 44), logistic regression (Lab 08), drift monitoring (Lab 30), least squares (Lab 03).',
    paragraphs: [
      'Training and deployment data rarely come from the same distribution. Write the joint distribution as p(x, y) = p(x)·p(y | x). **Covariate shift** changes p(x) and keeps p(y | x), for example the same patients seen at a different hospital. **Label shift** changes p(y) and keeps p(x | y), for example a disease becoming more common (Lesson 61.4). **Concept shift** changes p(y | x) itself, and no reweighting can fix it without new labels.',
      'If the model were correct everywhere, covariate shift would not matter. Real models are **misspecified**: they trade accuracy in one region for accuracy in another, and they spend their capacity where the training data are. In the playground, a straight line fitted to a curved function under training inputs from N(0, 1) is poor where the test inputs lie.',
      '**Importance weighting** (Shimodaira 2000) weights each training point by w(x) = p_test(x)/p_train(x). The weighted training loss is then an unbiased estimate of the test loss, the same identity as importance sampling (Lab 44): E_train[w(x)·ℓ] = E_test[ℓ]. The fitted line moves to where the test inputs are, and in the playground the test error falls from about 0.54 to 0.10.',
      'The densities are rarely known, but their ratio can be estimated without estimating either density. Train a **domain classifier** to tell training inputs (label 0) from unlabeled test inputs (label 1). Then w(x) = [c(x)/(1 − c(x))]·(n_train/n_test), where c(x) is its predicted probability of “test”. Its AUC is also a **shift detector**: near 0.5 means the domains look alike, and near 1 means they barely overlap.',
      'Weights have a cost. When the test distribution sits where training data are sparse, a few points get huge weights, and the **effective sample size** (Σw)²/Σw² collapses. The fit then rests on a handful of points. Common remedies are flattening (w^λ with λ < 1), clipping large weights, and regularizing. Reweighting cannot help at all where the training data have no support: then you need new data.',
      'Detect shift before correcting it. Monitor input distributions (Lab 30), run two-sample tests or a domain classifier on recent inputs, and watch prediction distributions. Decide in advance what size of shift triggers reweighting, recalibration or retraining.',
    ],
    formula: 'w(x) = p_test(x)/p_train(x)     E_train[w(x)·ℓ(x, y)] = E_test[ℓ(x, y)]     ŵ(x) = [c(x)/(1 − c(x))]·(n_train/n_test)',
    derivation: {
      title: 'Importance weights for a shifted Gaussian',
      steps: [
        { prompt: 'Write the importance weight in terms of the test density pt and the training density pr.', answer: 'pt/pr', show: '`pt/pr`', vars: { pt: [0.01, 2], pr: [0.01, 2] } },
        { prompt: 'Training inputs are N(0, 1) and test inputs N(μ, 1). Write log w(x).', answer: 'μ*x-μ^2/2', show: '`μx − μ²/2`: −(x − μ)²/2 + x²/2', vars: { μ: [-2, 2], x: [-3, 3] } },
        { prompt: 'With μ = 1.5, what is the weight of a training point at x = 2? (Two decimals.)', number: Math.exp(1.875), tolerance: 0.01, show: '`exp(3 − 1.125) = e^1.875 ≈ 6.52`' },
        { prompt: 'A domain classifier gives c = P(test | x). Write the weight in terms of c and the sample sizes nr (training) and nt (test).', answer: 'c/(1-c)*nr/nt', show: '`c/(1 − c) · nr/nt`: the odds, corrected for how many points of each kind the classifier saw', vars: { c: [0.05, 0.95], nr: [50, 500], nt: [50, 500] } },
        { prompt: 'Four training points have weights 3, 1, 1 and 1. What is the effective sample size?', number: 3, tolerance: 1e-9, show: '`6²/12 = 3`', why: 'One heavy weight makes four points count as three.' },
      ],
      result: 'For a mean shift of μ, the weights grow like e^(μx): points far out in the direction of the shift dominate, which is where the variance cost comes from.',
    },
    experiment: 'Move the test mean from 0 to 2.5 and watch the three test errors, the effective sample size and the AUC. At mean 2.5, compare λ = 1 with λ = 0.5.',
    question: 'Four training points have importance weights 2, 2, 0.5 and 0.5. What is their effective sample size? (Two decimals.)',
    answer: 2.94,
    tolerance: 0.005,
    explanation: '(Σw)² / Σw² = 5² / (4 + 4 + 0.25 + 0.25) = 25/8.5 ≈ 2.94.',
    reflection: 'Describe a covariate shift your model could meet, and how you would detect it before the errors pile up.',
  },
  {
    id: 'l61-label',
    title: '61.4 · Label shift and prior correction',
    sections: ['When only the class balance changes', 'Re-weighting probabilities', 'Estimating the new balance', 'Accuracy versus calibration', 'Assumptions and failure'],
    skill: 'Estimate a changed class prior from unlabeled data and correct a classifier’s probabilities.',
    prerequisite: 'Lesson 61.3; Bayes’ rule (Lab 04); confusion matrices and calibration (Lab 09).',
    paragraphs: [
      '**Label shift** changes how common each class is while each class looks the same: p(y) changes and p(x | y) does not. Disease prevalence rises in flu season, and fraud rates change with a new product, while the symptoms of flu and the pattern of a fraudulent transaction stay the same. The playground’s classifier was trained with 50% of each class and is deployed where class 1 is much rarer.',
      'Bayes’ rule says exactly how to correct the model. Since p(y | x) ∝ p(x | y)·p(y) and p(x | y) is unchanged, the new posterior is the old one re-weighted by the ratio of priors: p′(y | x) ∝ p(y | x)·π′(y)/π(y), then normalized. No retraining is needed, only the new prior.',
      'The new prior is unknown, because deployment data are unlabeled. **Black-box shift estimation** (BBSE, Lipton et al. 2018) uses the classifier itself. On labelled validation data, measure the confusion matrix C[i][j] = P(ŷ = i | y = j). On deployment data, measure how often each label is predicted, μ. Since p(x | y) is unchanged, μ = C·π′, so solve for π′. With two classes this is one line: π′₁ = (μ₁ − C[1][0])/(C[1][1] − C[1][0]). An EM alternative (Saerens et al. 2002) iterates between re-weighting and re-estimating the prior.',
      'The correction moves the decision boundary toward the rare class, which improves accuracy, and it fixes the probabilities themselves, which the log loss measures. Calibrated probabilities matter whenever decisions depend on thresholds or costs (Lab 09). In the playground at a 10% share, accuracy rises from about 88% to 94%, and log loss almost halves.',
      'The method assumes p(x | y) truly stayed fixed and that the confusion matrix is invertible; a classifier no better than chance cannot reveal the prior. With very rare classes, the estimate is noisy, because a few validation errors move it a lot. If the classes themselves change appearance, as when fraudsters adapt, this is concept shift and needs fresh labels.',
    ],
    formula: 'p′(y | x) ∝ p(y | x)·π′(y)/π(y)     μ = C·π′  ⇒  π̂′ = C⁻¹μ     two classes: π̂′₁ = (μ₁ − C₁₀)/(C₁₁ − C₁₀)',
    derivation: {
      title: 'Correcting for a new class balance',
      steps: [
        { prompt: 'A model trained with π = 0.5 outputs p = 0.5. The deployment prior is π′ = 0.1. What is the corrected probability?', number: 0.1, tolerance: 1e-9, show: '`0.5·0.2 / (0.5·0.2 + 0.5·1.8) = 0.1`: with no evidence either way, the prior decides' },
        { prompt: 'Same prior change, but the model outputs p = 0.8. What is the corrected probability? (Four decimals.)', number: 0.16 / 0.52, tolerance: 1e-4, show: '`0.8·0.2 / (0.8·0.2 + 0.2·1.8) = 0.16/0.52 ≈ 0.3077`' },
        { prompt: 'With a = P(ŷ = 1 | y = 0) and b = P(ŷ = 1 | y = 1), the predicted rate is μ = a(1 − π′) + bπ′. Solve for π′.', answer: '(μ-a)/(b-a)', show: '`π′ = (μ − a)/(b − a)`', vars: { μ: [0.1, 0.9], a: [0, 0.3], b: [0.6, 1] } },
        { prompt: 'With a = 0.12, b = 0.88 and μ = 0.2, what is the estimated share of class 1? (Four decimals.)', number: 0.08 / 0.76, tolerance: 1e-4, show: '`0.08/0.76 ≈ 0.1053`', why: 'The model predicts class 1 for 20% of points, but 12% of the negatives are false positives, so the true share is much lower.' },
      ],
      result: 'Under label shift, the classifier’s own predictions on unlabeled data, together with its validation confusion matrix, identify the new prior, and Bayes’ rule does the rest.',
    },
    experiment: 'Slide the deployment share from 50% down to 2%. Track the BBSE estimate against the truth, and the accuracy and log loss of the three rows. Where does the estimate start to fail?',
    question: 'On validation data, P(ŷ = 1 | y = 0) = 0.1 and P(ŷ = 1 | y = 1) = 0.9. On deployment data, 26% of points are predicted as class 1. What is the BBSE estimate of the share of class 1?',
    answer: 0.2,
    tolerance: 1e-6,
    explanation: '(0.26 − 0.1)/(0.9 − 0.1) = 0.16/0.8 = 0.2.',
    reflection: 'Which classes in a problem you know change in frequency over time, and would their appearance stay the same?',
  },
  {
    id: 'l61-adapt',
    title: '61.5 · Domain adaptation and robust models',
    sections: ['Labelled source, unlabeled target', 'Aligning feature statistics', 'Learning invariant features', 'What adaptation can promise', 'Spurious correlations', 'A robustness checklist'],
    skill: 'Adapt a model to a new domain by aligning feature statistics, and state the assumptions that make adaptation possible.',
    prerequisite: 'Lessons 61.1–61.4; PCA and covariance (Lab 18); fairness and subgroup evaluation (Lab 31).',
    paragraphs: [
      '**Unsupervised domain adaptation** has labelled data from a source domain and only unlabeled data from a target domain: last year’s annotated images and this year’s camera, or one hospital’s records and another’s. The goal is a model that works on the target. In the playground, the source model scores about 95% on the source and drops sharply on the target, which is the source after a stretch, an offset and a rotation.',
      '**CORAL** (correlation alignment, Sun et al. 2016) matches second-order statistics. It whitens the source features by their covariance, re-colours them with the target’s covariance, shifts them to the target’s mean, and then trains on the transformed labelled source. When the difference between domains is a stretch and a shift, this recovers almost all of the lost accuracy. **Deep CORAL** and **maximum mean discrepancy** penalties apply the same idea to a network’s hidden features.',
      '**Domain-adversarial training** (DANN, Ganin et al. 2016) learns features that a domain classifier cannot use to tell source from target, while a label classifier on the same features stays accurate. It connects Lesson 61.3’s domain classifier with Lesson 61.2’s min–max training. A gradient-reversal layer makes the feature extractor maximize the domain classifier’s loss.',
      'Adaptation cannot succeed without an assumption about what stayed the same. Ben-David et al. (2010) bound the target error by the source error, plus a divergence between the domains as seen by the model class, plus λ: the error of the best single classifier on both domains. If no classifier does well on both, alignment can even hurt, by matching the wrong clusters to each other. In the playground, CORAL helps less as the rotation grows: matching the overall spread cannot tell which direction separated the classes.',
      'A related failure is **spurious correlation**. A model learns a shortcut that holds in the training data but not elsewhere, such as a hospital’s scanner type predicting disease, or backgrounds predicting the object in an image. Average accuracy can look excellent while a subgroup fails badly. **Group DRO** (Sagawa et al. 2020) minimizes the worst group’s loss instead of the average, and evaluating by subgroup (Lab 31) reveals the problem.',
      'A robustness checklist: name the shifts you expect, whether inputs, class balance, concepts or adversaries. Measure performance under each, with held-out domains, time-based splits, subgroup slices and strong attacks. Monitor for shift in deployment (Lab 30). Keep a way to collect labels from the new domain, because a few hundred target labels often beat any unsupervised correction.',
    ],
    formula: 'CORAL: x ↦ Σ_T^{1/2} Σ_S^{−1/2}(x − m_S) + m_T     ε_T(h) ≤ ε_S(h) + ½ d_{HΔH}(S, T) + λ',
    derivation: {
      title: 'Alignment in one dimension',
      steps: [
        { prompt: 'In one dimension, CORAL standardizes with the source mean ms and standard deviation ss, then rescales with the target’s mt and st. Write the aligned value of x.', answer: 'st*(x-ms)/ss+mt', show: '`st·(x − ms)/ss + mt`', vars: { x: [-3, 3], ms: [-2, 2], ss: [0.3, 2], mt: [-2, 2], st: [0.3, 2] } },
        { prompt: 'Source mean 0 and standard deviation 1; target mean 1.5 and standard deviation 2. Where does x = 1 go?', number: 3.5, tolerance: 1e-9, show: '`2 × 1 + 1.5 = 3.5`' },
        { prompt: 'The source error is 0.05, the divergence term ½d is 0.1, and λ is 0.02. What is the bound on the target error?', number: 0.17, tolerance: 1e-9, show: '`0.05 + 0.1 + 0.02 = 0.17`', why: 'Alignment lowers the divergence term. Nothing done without target labels can lower λ.' },
        { prompt: 'A source classifier is perfect on two symmetric classes. The target is the source rotated by 180°, which puts each class where the other one was. Means and covariances already match, so CORAL changes nothing. What accuracy does the classifier get on the target, as a fraction?', number: 0, tolerance: 1e-9, show: '`0`: the aligned statistics are identical, so every point is assigned to the wrong class', why: 'Unlabeled statistics cannot tell a swap from no change.' },
      ],
      result: 'Aligning statistics makes the domains look alike to the model, but only an assumption about what stayed the same, or some target labels, can make that alignment correct.',
    },
    experiment: 'Move the rotation from 0 to 1.4 and record the source-only, CORAL and oracle accuracies at a few values. Turn the aligned data on and off to see what CORAL did to the source.',
    question: 'In one dimension, the source has mean 2 and standard deviation 1, and the target has mean 0 and standard deviation 0.5. Where does CORAL map the source value x = 3?',
    answer: 0.5,
    tolerance: 1e-6,
    explanation: '0.5 × (3 − 2)/1 + 0 = 0.5.',
    reflection: 'What is one shortcut a model in your domain could learn, and which subgroup evaluation would expose it?',
  },
]

export const sources = [
  { title: 'Goodfellow, Shlens & Szegedy (2015) · Explaining and harnessing adversarial examples (FGSM)', url: 'https://arxiv.org/abs/1412.6572' },
  { title: 'Madry et al. (2018) · Towards deep learning models resistant to adversarial attacks (PGD, adversarial training)', url: 'https://arxiv.org/abs/1706.06083' },
  { title: 'Athalye, Carlini & Wagner (2018) · Obfuscated gradients give a false sense of security', url: 'https://arxiv.org/abs/1802.00420' },
  { title: 'Shimodaira (2000) · Improving predictive inference under covariate shift by weighting the log-likelihood function', url: 'https://doi.org/10.1016/S0378-3758(00)00115-4' },
  { title: 'Lipton, Wang & Smola (2018) · Detecting and correcting for label shift with black box predictors (BBSE)', url: 'https://arxiv.org/abs/1802.03916' },
  { title: 'Sun, Feng & Saenko (2016) · Return of frustratingly easy domain adaptation (CORAL)', url: 'https://arxiv.org/abs/1511.05547' },
  { title: 'Ganin et al. (2016) · Domain-adversarial training of neural networks', url: 'https://arxiv.org/abs/1505.07818' },
  { title: 'Ben-David et al. (2010) · A theory of learning from different domains', url: 'https://doi.org/10.1007/s10994-009-5152-4' },
  { title: 'Sagawa et al. (2020) · Distributionally robust neural networks for group shifts (Group DRO)', url: 'https://arxiv.org/abs/1911.08731' },
]
