// Lesson order for Lab 02: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l02-functions': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'MutationDemo', caption: 'A function that mutates its argument versus one that returns a new value.' },
    { cell: 0 }, { cell: 1 },
    { predict: { prompt: '`def drop_first(xs): xs.pop(0)` is called three times on the same list of 5 rows. How many rows are left?', answer: 2, explain: 'Each call removes one more row from the caller’s list: 5 − 3 = 2. A pure version would leave all 5.' } },
    { figure: 'FillBeforeSplit', caption: 'The same two pure stages in two orders. Only one of them keeps validation out of preprocessing.' },
    { cell: 2 },
    { p: 3 },
    { figure: 'SeedAsParameter', caption: 'A seed passed as an argument versus randomness that other code can disturb.' },
    { p: 4 },
  ],
  'l02-indexing': [
    { p: 0 }, { p: 1 },
    { figure: 'IndexExplorer', caption: 'Pick an expression; the selected positions of x = [4, 9, 2, 7] are marked.' },
    { predict: { prompt: 'x = `[4, 9, 2, 7]`. How many values does `x[x > 3]` contain?', answer: 3, explain: 'The mask is [True, True, False, True], so it keeps 4, 9 and 7.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'AxisReduce', caption: 'The axis you name is the one that disappears.' },
    { cell: 1 },
    { p: 3 },
    { figure: 'BroadcastRule', caption: 'Line the shapes up from the right. Each pair must match or contain a 1.' },
    { predict: { prompt: '`X` has shape `(100, 3)` and `means` has shape `(3,)`. How many numbers does `X - means` contain?', answer: 300, explain: '(3,) behaves like (1, 3) and stretches to (100, 3): 300 numbers, one per entry of X.' } },
    { cell: 2 },
    { p: 4 },
    { cell: 3 },
  ],
  'l02-pandas': [
    { p: 0 },
    { cell: 0 },
    { p: 1 },
    { figure: 'DtypeTrap', caption: 'One unrecognised word turns a numeric column into text.' },
    { cell: 1 },
    { p: 2 },
    { cell: 2 },
    { p: 3 },
    { figure: 'GroupMeans', caption: 'Group means, the overall mean, and the misleading mean of the group means.' },
    { predict: { prompt: 'Branch A has durations 10 and 30; branch B has one build of 50. What is the overall mean duration of all three builds?', answer: 30, explain: '(10 + 30 + 50)/3 = 30. The mean of the group means would be (20 + 50)/2 = 35 — it gives the single B build as much weight as both A builds.', misconceptions: [{ answer: 35, feedback: 'That averages the two group means. The overall mean weights every build equally.' }] } },
    { cell: 3 },
    { p: 4 },
  ],
  'l02-missing': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'MeanVsMedian', caption: 'Drag the largest value and compare how the mean and the median respond.' },
    { predict: { prompt: 'What is the median of `[3, 1, 8, 6, 100]`?', answer: 6, explain: 'Sorted: 1, 3, 6, 8, 100. The middle value is 6. The mean would be 23.6.' } },
    { cell: 0 },
    { p: 3 },
    { figure: 'LearnedFill', caption: 'The pipeline on the real build log: where the fill value is learned, and the indicator it leaves behind.' },
    { cell: 1 },
    { p: 4 },
    { cell: 2 },
  ],
  'l02-look': [
    { p: 0 },
    { figure: 'SentinelDescribe', caption: 'describe() before and after treating the sentinel as missing.' },
    { cell: 0 },
    { p: 1 },
    { figure: 'UnitOutlier', caption: 'One build logged in KB instead of MB, and what it does to a fitted line.' },
    { p: 2 },
    { figure: 'DuplicateSplit', caption: 'Six rows, one of them an exact copy. Change the seed and watch where the copies land.' },
    { predict: { prompt: 'A log of 83 rows contains 3 exact duplicate rows (each ingested twice). How many rows remain after `drop_duplicates()`?', answer: 80, explain: '83 − 3 = 80: one copy of each duplicated row is removed.' } },
    { p: 3 },
    { p: 4 },
    { cell: 1 },
  ],
  'l02-seeds': [
    { p: 0 },
    { figure: 'SeededShuffle', caption: 'Permutations of 0–9 from seeded generators.' },
    { cell: 0 },
    { p: 1 },
    { p: 2 },
    { figure: 'SplitInvariants', caption: 'Four invariants every correct split satisfies. Introduce a bug and see which ones fail.' },
    { predict: { prompt: 'n = 45 rows, `k = int(n * 0.8)` training rows. How many validation rows are there?', answer: 9, explain: 'int(45 × 0.8) = int(36.0) = 36 training rows, so 45 − 36 = 9 validation rows.' } },
    { cell: 1 },
    { p: 3 }, { p: 4 },
  ],
}
