import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l02-functions',
    title: '02.1 · An experiment is a function of its inputs',
    sections: ['A result nobody can reproduce', 'Name the stages', 'Pure functions', 'Parameters instead of hidden state', 'Put it into practice'],
    skill: 'Structure an experiment as small functions whose outputs depend only on their arguments.',
    prerequisite: 'Lab 01. Python functions, arguments, return values and lists.',
    paragraphs: [
      'You fit a model in a notebook on Monday and get validation MSE 14.2. On Tuesday you run the cells again and get 15.8. Nothing was edited. The cause: cell 7 was run twice on Monday, dropping a row the second time, and a random split used a different shuffle. **The number was real, but you cannot say what produced it.** A result you cannot regenerate is an anecdote, not evidence.',
      'Every supervised experiment has the same stages: **load** raw data → **clean** it → **split** it → **fit** on the training part → **evaluate** on held-out data. Write each stage as its own function: `load(path)`, `clean(rows)`, `split(rows, seed)`, `fit(train)`, `evaluate(model, validation)`. A run is then one line that calls them in order, and every decision lives in exactly one visible place.',
      'A **pure function** returns a value computed only from its arguments and changes nothing outside itself. `def double(xs): return [2 * x for x in xs]` is pure. `def drop_first(xs): xs.pop(0)` is not: it mutates the caller\'s list, so calling it twice silently removes two rows. Pure stages can be rerun and tested in isolation, and give the same answer every time. Purity does **not** make stages interchangeable: `split(clean(rows))` and `clean(split(rows))` are different experiments when cleaning drops rows, and imputing before splitting leaks validation data. The order of stages is a decision to write down, not a detail purity settles. Make a copy (`rows = list(rows)` or `df = df.copy()`) before changing anything you were given.',
      'Hidden state is any value a function uses without receiving it as an argument: a global `SEED`, a variable left over from an earlier cell, the current time. Pass it in instead: `split(rows, seed=42, test_fraction=0.25)`. The function signature now documents every choice that can change the result, and an experiment configuration is simply the dictionary of those arguments.',
      'Procedure: write the stages as functions; give every choice a named parameter with a default; never mutate inputs; restart the Python process and run the whole pipeline top to bottom before trusting a number. The playground records its decisions and computes a **fingerprint** (a short hash) of the result, so you can see when two runs are truly identical.',
    ],
    formula: 'result = evaluate(fit(split(clean(load(path)), seed).train), …)     same inputs → same result',
    experiment: 'Note the fingerprint. Press “Reproduce from a clean run” — the log is regenerated from the seed and the decisions are replayed. Predict whether the fingerprint matches. Then change only the seed and reproduce again.',
    question: '`def add_row(rows): rows.append(0); return len(rows)` is called twice on the same list that starts with 3 items. What does the second call return?',
    answer: 5,
    misconceptions: [{ answer: 4, feedback: 'That is what a pure version would return. The first call already appended to the caller’s list, so the second call starts from 4 items.' }],
    explanation: 'The first call mutates the caller\'s list to 4 items and returns 4; the second finds 4, appends again and returns 5. A pure version would build `rows + [0]` and return 4 both times.',
    reflection: 'List every value your last experiment depended on that was not an explicit function argument. How would you make each one a parameter?',
  },
  {
    id: 'l02-indexing',
    title: '02.2 · Select, mask and broadcast',
    sections: ['Pick rows by position', 'Pick rows by a condition', 'Reduce along an axis', 'Broadcasting', 'The silent (n,1) bug'],
    skill: 'Use integer indexing, boolean masks, axis reductions and broadcasting, and predict every result shape.',
    prerequisite: 'Lesson 02.1; NumPy arrays and shapes from Lab 01.',
    paragraphs: [
      'Let `x = np.array([4, 9, 2, 7])`. Integer indexing picks by position: `x[0]` is 4, `x[-1]` is 7, `x[1:3]` is `[9, 2]` (start included, stop excluded). An index array picks several positions at once: `x[[3, 0]]` is `[7, 4]`. This is how a split works: shuffle the row numbers, then take `X[train_idx]` and `X[test_idx]`.',
      'A comparison applied to an array gives a **boolean mask**: `x > 5` is `[False, True, False, True]`. Using the mask as an index keeps the `True` positions: `x[x > 5]` is `[9, 7]`. Combine conditions with `&` (and), `|` (or) and `~` (not), each wrapped in parentheses: `x[(x > 3) & (x < 9)]` is `[4, 7]`. `np.isnan(x)` produces the mask of missing values, which you will use constantly.',
      'For a 2D array `X` of shape `(n, p)` — n rows (observations) and p columns (features) — `X.mean(axis=0)` averages **down** the rows and returns one value per column, shape `(p,)`. `X.mean(axis=1)` averages **across** each row, shape `(n,)`. Read `axis=k` as "the axis that disappears".',
      '**Broadcasting** lets arrays of different shapes combine. Align the shapes from the right; each pair of sizes must be equal or one of them must be 1, and a 1 is stretched to match. `X` of shape `(100, 3)` minus `means` of shape `(3,)` works: `(3,)` behaves like `(1, 3)` and is subtracted from every row. That one line centers every column without a loop.',
      'Now the trap. Predictions of shape `(5, 1)` minus targets of shape `(5,)`: aligned from the right, `(5, 1)` and `(1, 5)` both stretch, giving a `(5, 5)` table of every prediction minus every target. `np.mean(errors ** 2)` still returns one plausible-looking number, and it is wrong. Guard against it with `assert pred.shape == y.shape` or flatten with `pred.ravel()` before subtracting.',
    ],
    formula: 'X (n, p) − X.mean(axis=0) (p,) → (n, p)        (5, 1) − (5,) → (5, 5)  ⚠',
    experiment: 'In the broadcasting explorer, enter `100, 3` and `3`, then `5, 1` and `5`, then `4, 3` and `4`. Predict each result shape (or error) before reading it.',
    question: 'An array of shape `(4, 1)` is added to an array of shape `(3,)`. How many numbers does the result contain?',
    answer: 12,
    misconceptions: [{ answer: 7, feedback: 'Broadcasting does not add the sizes. (4, 1) and (3,) stretch into a (4, 3) grid.' }],
    explanation: 'Aligned from the right: `(4, 1)` and `(1, 3)`. Each 1 stretches, giving shape `(4, 3)` — 12 entries.',
    reflection: 'Where in your own code could a column vector meet a flat array? Write the assertion that would catch it.',
  },
  {
    id: 'l02-pandas',
    title: '02.3 · Tables with pandas',
    sections: ['Why a table library', 'Columns have types', 'Select with loc and iloc', 'Group, then aggregate', 'Read before you trust'],
    skill: 'Load a CSV into a DataFrame, check column types, select rows and columns, and compute grouped summaries.',
    prerequisite: 'Lesson 02.2; boolean masks.',
    paragraphs: [
      'NumPy arrays hold one type of number in a grid. Real data mixes types: a build ID, a branch name, a size in MB, a timestamp. A pandas **DataFrame** is a table of named columns, each a typed array, sharing one row index. `df = pd.read_csv("builds.csv")` loads one; `df.head()`, `df.shape` and `df.dtypes` are the first three things to run.',
      '`df.dtypes` often reveals a problem before any modeling. If one row of `duration_s` says `"unknown"`, the whole column is read as text (dtype `object`, shown as `str` in pandas 3) and `df["duration_s"].mean()` fails. (pandas already treats common markers such as empty cells, `"NA"` and `"n/a"` as missing — but not your logger’s own words.) Tell the reader what missing looks like — `pd.read_csv(path, na_values=["unknown", "-1"])` — or convert explicitly with `pd.to_numeric(col, errors="coerce")`, which turns unparseable entries into `NaN` (Not a Number, pandas\' missing marker).',
      '`df["size_mb"]` selects one column (a Series). `df[["size_mb", "files"]]` selects several (a DataFrame). `df.loc[mask, "size_mb"]` selects rows by a boolean mask or labels and a column by name; `df.iloc[0:5, 1]` selects by integer position. Prefer `.loc` for anything that assigns values; chained indexing such as `df[mask]["x"] = 0` may modify a temporary copy and leave `df` unchanged.',
      '`df.groupby("branch")["duration_s"].mean()` splits rows by branch, averages each group, and returns one value per branch. Suppose branch `main` has durations 40 and 60 and branch `dev` has 10, 20 and 30. The grouped means are 50 and 20: dev builds are much faster. The overall mean, 160 / 5 = 32, is not the average of the two group means (35), because the groups have different sizes. Grouped summaries answer "does this depend on that?" before you model anything.',
      'Procedure for any new table: `shape` (did every row load?), `dtypes` (are numbers numeric?), `isna().sum()` (where are gaps?), `describe()` (do min and max make physical sense?), `duplicated().sum()` (was anything ingested twice?). Write what you found into your notes before changing anything.',
    ],
    formula: 'df.groupby("branch")["duration_s"].mean()     df.loc[df["size_mb"] > 50, "files"]',
    experiment: 'Open the raw log preview. Which problems would `df.dtypes`, `df.isna().sum()`, `df.describe()` and `df.duplicated().sum()` each reveal? Match each problem label to the check that finds it.',
    question: 'Branch `main` has durations 40 and 60; branch `dev` has 20, 20 and 50. What is the grouped mean for `dev`?',
    answer: 30,
    misconceptions: [{ answer: 38, feedback: 'That is the overall mean of all five builds. Group first: only dev’s three durations.' }],
    explanation: '(20 + 20 + 50) / 3 = 30. The main mean is 50. The overall mean, 190 / 5 = 38, is not the average of the two group means (40) because the groups have different sizes.',
    reflection: 'Which grouping column in your own data might change the target the most? How would you check before modeling?',
  },
  {
    id: 'l02-missing',
    title: '02.4 · Missing values are information',
    sections: ['Why is it missing?', 'Drop, or fill?', 'Mean versus median', 'Learn the fill value from training rows', 'Keep a missing indicator'],
    skill: 'Choose and justify a missing-value strategy, fit it on training data only, and preserve the missingness signal.',
    prerequisite: 'Lesson 02.3; mean and median.',
    paragraphs: [
      'A size can be missing because the logger crashed at random, because a specific old tool never recorded it, or because very large builds timed out before logging. These differ. Randomly missing values mostly cost you data. Values missing for a reason related to the target — large builds going unrecorded — bias every estimate made from the rows that remain. Ask why before you choose how.',
      '**Dropping** rows is simple and honest when few are affected, but it discards the other columns of those rows and gives a deployed model no answer for a future input with the same gap. **Imputing** replaces each gap with a value estimated from the data. A missing **target** is different: you cannot train on an unknown answer, so rows without a target are dropped from training.',
      'The median is the middle value after sorting; the mean is the arithmetic average. For sizes `[2, 4, 9, 100]`, the mean is 28.75 but the median is (4 + 9) / 2 = 6.5. One huge value drags the mean far from most observations, so the median is the safer default fill for skewed measurements. `np.nanmean` and `np.nanmedian` ignore `NaN` when computing.',
      'The fill value is a learned parameter, exactly like a model weight. Compute it from training rows only, then apply that same number to validation, test and future data. Computing it from all rows lets validation values influence preprocessing — a form of **leakage** that makes validation look slightly better than deployment will be.',
      'Filling erases the fact that a value was missing, and missingness itself can predict the target. Add a **missing indicator** column: 1 where the value was filled, 0 otherwise. The model can then learn "unknown size behaves differently" instead of treating every filled value as a genuine median-sized build.',
    ],
    formula: 'fill = np.nanmedian(x_train)     x_filled = np.where(np.isnan(x), fill, x)     missing = np.isnan(x).astype(float)',
    experiment: 'Switch "Learn fill value from" between training rows and all rows. Watch the fill value in the log and the validation MSE. Then compare median, mean and drop. Explain each change in the notebook.',
    question: 'Training sizes are `[2, NaN, 9, 4, 100]`. What value does median imputation fill in?',
    answer: 6.5,
    misconceptions: [{ answer: 28.75, feedback: 'That is the mean, pulled up by the 100. Median imputation uses the middle value of the sorted, non-missing sizes.' }, { answer: 9, feedback: 'With four values, the median is the average of the middle two: (4 + 9) / 2.' }],
    explanation: 'Ignoring NaN leaves `[2, 4, 9, 100]`. The middle two sorted values are 4 and 9, so the median is 6.5. The mean would be 28.75, pulled up by 100.',
    reflection: 'For one column in your data, list the plausible reasons it could be missing. Which reason would make dropping those rows misleading?',
  },
  {
    id: 'l02-look',
    title: '02.5 · Look at the data before modeling',
    sections: ['Sentinels pretend to be numbers', 'Units change silently', 'Duplicates inflate evidence', 'Plot the relationship', 'Document every rule'],
    skill: 'Detect sentinel values, unit errors and duplicates with summaries and plots, and record each repair as an explicit rule.',
    prerequisite: 'Lessons 02.3–02.4.',
    paragraphs: [
      'A timeout written as `duration_s = -1` is a **sentinel**: a special code stored in a numeric column. `-1` is a valid float, so nothing crashes; the model simply learns that some builds take negative time. `describe()` exposes it: a minimum of -1 for a duration is physically impossible. Convert sentinels to missing, then treat them as missing.',
      'If an old script logged size in kilobytes, a 40 MB build appears as 40960. One such row can dominate a squared-error fit, because its error is squared too. A histogram or a scatter plot shows a detached cluster far to the right. Only repair a unit error when you can state the rule ("values above 1000 came from the KB script") and confirm it — otherwise flag it and ask.',
      'An exact duplicate row usually means the same log was ingested twice. It counts one build as two independent observations, and if the copies land on both sides of a split, the model is validated on a row it was trained on. `df.drop_duplicates()` removes exact copies. Near-duplicates — the same build rerun — are a grouping problem, handled with grouped splits in a later lab.',
      'Plot target against the main input before any fitting. You should see roughly the relationship you expect, a plausible spread, and no impossible points. If the cloud is curved, a straight line will underfit; if it fans out, errors grow with size; if it has two bands, a missing categorical variable is at work.',
      'Write each repair as a rule in code and in prose: *what* was changed, *how many* rows were affected, and *why* it is justified. The playground\'s cleaning log is that record. A reviewer — or you in six months — should be able to disagree with a rule, change one line and rerun everything.',
    ],
    formula: 'df["duration_s"] = df["duration_s"].replace(-1, np.nan)     df = df.drop_duplicates()',
    experiment: 'Turn off "Repair KB → MB" and look at the plot and the slope. Then turn off "Drop -1 sentinel targets". Predict what each does to the fitted line before toggling.',
    question: 'Durations are `[30, -1, 50, -1, 40]`, with -1 meaning "timed out". After treating the sentinel as missing, what is the mean duration of the valid rows?',
    answer: 40,
    misconceptions: [{ answer: 23.6, feedback: 'That average includes the two −1 sentinels as if they were durations. Treat them as missing first.' }],
    explanation: 'The valid values are 30, 50 and 40, whose mean is 40. Averaging the raw column gives 23.6, an impossible-looking result caused by two fake negative times.',
    reflection: 'Which column in your data could contain a sentinel, and what value would it use? Write the rule you would apply.',
  },
  {
    id: 'l02-seeds',
    title: '02.6 · Seeds, determinism and tests',
    sections: ['Pseudorandom is repeatable', 'Seed every source of randomness', 'Test invariants, not just outputs', 'Record the environment', 'Demonstrate reproducibility'],
    skill: 'Make random steps repeatable, write tests for pipeline invariants, and record what a run depended on.',
    prerequisite: 'Lessons 02.1–02.5.',
    paragraphs: [
      'Computers generate **pseudorandom** numbers from a formula applied to an internal state. The starting state is the **seed**. `rng = np.random.default_rng(42)` creates a generator; the same seed always yields the same sequence, so `rng.permutation(10)` gives the same shuffle every run. Randomness in ML — splits, initial weights, bootstrap samples — should be random *across* seeds and identical *for* a seed.',
      'Create one generator per experiment from the configured seed and pass it (or the seed) to every function that needs randomness. Avoid the legacy global `np.random.seed(...)`: any library call that also draws from the global state changes your sequence without warning. Frameworks with GPU kernels can remain nondeterministic even when seeded; later labs note where.',
      'A test states something that must be true of every correct run. For a split: every row appears exactly once, the two parts do not overlap, the sizes match the fraction, and the same seed gives the same split. For imputation: no NaN remains, the input array was not modified, and the fill value depends only on training rows. `assert` statements checking these **invariants** catch whole families of bugs that a single expected output would miss.',
      'Record what the result depended on: the data file (or its hash), the configuration dictionary, the code version (a git commit), and library versions (`np.__version__`, `pd.__version__`). A fingerprint of data plus configuration, like the one in the playground, gives each run a short ID you can cite in notes.',
      'You have completed this lab when you can: rerun your pipeline from a fresh process and get the same numbers; explain every cleaning rule and how many rows it touched; and show a test that fails when a rule is broken. The Python challenge asks you to build exactly those functions.',
    ],
    formula: 'rng = np.random.default_rng(seed)     idx = rng.permutation(n)     train, test = idx[:k], idx[k:]',
    experiment: 'Record the fingerprint, change the seed, reproduce, then set the seed back and reproduce again. Does the original fingerprint return? What would break this if the pipeline used the current time?',
    question: 'A split puts 25% of 80 rows in validation using `k = int(n * 0.75)` training rows. How many validation rows are there?',
    answer: 20,
    misconceptions: [{ answer: 60, feedback: 'That is the number of training rows. Validation gets the rest: 80 − 60.' }],
    explanation: '`int(80 * 0.75)` = 60 training rows, so 80 − 60 = 20 validation rows. A test should assert 60 + 20 = 80 and that no row appears in both parts.',
    reflection: 'Write three invariants your own pipeline should satisfy. Which one would have caught a bug you have already met?',
  },
]

export const sources = [
  { title: 'NumPy · Broadcasting', url: 'https://numpy.org/doc/stable/user/basics.broadcasting.html' },
  { title: 'NumPy · Random Generator (seeded, recommended API)', url: 'https://numpy.org/doc/stable/reference/random/generator.html' },
  { title: 'pandas · Working with missing data', url: 'https://pandas.pydata.org/docs/user_guide/missing_data.html' },
  { title: 'scikit-learn · Imputation of missing values', url: 'https://scikit-learn.org/stable/modules/impute.html' },
  { title: 'The Turing Way · Guide for reproducible research', url: 'https://book.the-turing-way.org/reproducible-research/reproducible-research' },
]

// Runnable cells and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
