// Lesson order for Lab 19: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l19-order': [
    { p: 0 }, { p: 1 },
    { figure: 'Components', caption: 'Untick components to see what each one contributes to two weeks of usage.' },
    { cell: 0 },
    { p: 2 },
    { figure: 'ShiftCorrelate', caption: 'The series against a copy of itself shifted by k hours. Try k = 1, 12 and 24.' },
    { predict: { prompt: 'The series `[2, 4, 2, 4]` has mean 3. What is its lag-1 autocorrelation r₁?', answer: -0.75, tolerance: 0.001, explain: 'Deviations are −1, 1, −1, 1. Neighbour products: (1)(−1) + (−1)(1) + (1)(−1) = −3. Divide by Σ deviation² = 4: r₁ = −0.75. A series that alternates is negatively correlated with its previous value.', misconceptions: [{ answer: -3, feedback: 'That is the numerator. Divide by Σ(y_t − ȳ)² = 4.' }] } },
    { cell: 1 },
    { p: 3 },
    { figure: 'AcfPlot', caption: 'The autocorrelation function up to one week. Lags 24 and 168 are orange.' },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l19-baselines': [
    { p: 0 },
    { figure: 'OriginHorizon', caption: 'Move the origin and the horizon. Shaded values are not known yet when the forecast is made.' },
    { p: 1 }, { p: 2 },
    { predict: { prompt: 'Hourly data with a daily cycle. A seasonal-naive forecast is made at t = 100 for horizon **h = 30**. Which index does it use? (It must be known at t = 100.)', answer: 82, explain: 'One day before the target, 130 − 24 = 106, is after the origin. Go back two days: 130 − 48 = 82. In general t + h − 24·⌈h/24⌉.', misconceptions: [{ answer: 106, feedback: '106 is after the origin t = 100, so it is not known yet. Go back another day.' }] } },
    { cell: 0 },
    { figure: 'BaselineForecasts', caption: 'Both baselines on the last three days, at three horizons.' },
    { p: 3 },
    { figure: 'BaselineHorizons', caption: 'Mean absolute error of each baseline at horizons 1 to 24 hours.' },
    { cell: 1 },
    { p: 4 },
    { predict: { prompt: 'A model’s MAE is 3.6; the seasonal-naive MAE on the same period is 4.8. What is the scaled error (model ÷ seasonal naive)?', answer: 0.75, tolerance: 0.001, explain: '3.6 / 4.8 = 0.75: the model’s errors are 25% smaller than the baseline’s. 1.0 would mean no better than the baseline.' } },
    { math: true },
  ],
  'l19-lags': [
    { p: 0 },
    { figure: 'SeriesToRows', caption: 'One origin and horizon become one row of the training table. Every feature’s index is at or before the origin.' },
    { p: 1 },
    { predict: { prompt: 'Origin t = 500, horizon h = 6. Which index does the “same hour last week” feature use (t + h − 168)?', answer: 338, explain: '500 + 6 − 168 = 338: the target hour, one week earlier, well before the origin.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'RollingMean', caption: 'A trailing mean over w hours. Compare w = 3 with w = 24.' },
    { p: 3 }, { p: 4 },
    { figure: 'HorizonCurve', caption: 'Walk-forward error of the better baseline and of the lag regression, by horizon.' },
    { cell: 1 },
    { math: true },
  ],
  'l19-walkforward': [
    { p: 0 },
    { figure: 'WalkForwardStepper', caption: 'Step through the daily refits. Blue shading: the origins whose targets are already known.' },
    { p: 1 },
    { figure: 'RefitSchedule', caption: 'Refit every hour, every day or every week, and compare the errors.' },
    { cell: 0 },
    { p: 2 }, { p: 3 },
    { predict: { prompt: 'Origin t = 750, horizon h = 6. What is the latest training-row origin j whose target j + h is known?', answer: 744, explain: 'j + 6 ≤ 750, so j ≤ 744. A row with origin 745 has its target at 751, which has not happened yet.', misconceptions: [{ answer: 750, feedback: 'The row at origin 750 has its target at 756, in the future. The target, not the features, decides.' }] } },
    { cell: 1 },
    { p: 4 },
    { figure: 'DelayEffect', caption: 'A 1-hour persistence forecast when the newest value arrives d hours late.' },
    { cell: 2 },
    { math: true },
  ],
  'l19-leakage': [
    { p: 0 },
    { figure: 'HorizonCurve', props: { leakOption: true }, caption: 'Tick the leaky feature and watch the error by horizon.' },
    { cell: 0 },
    { p: 1 }, { p: 2 },
    { figure: 'CenteredWindow', caption: 'A trailing window against a centred one, around the origin t.' },
    { predict: { prompt: 'A centred 7-hour moving average at origin t. How many of its values come from after t?', answer: 3, explain: 'Centred on t, it covers t − 3 … t + 3: three values from the future.' } },
    { p: 3 }, { p: 4 },
    { math: true },
    { ladder: 'forecast' },
  ],
}
