export const lessons = [
  {
    id: 'l19-order',
    title: '19.1 · When order matters',
    sections: ['Rows are not exchangeable', 'Trend, seasonality, noise', 'Autocorrelation', 'Reading an ACF', 'Put it into practice'],
    skill: 'Describe a time series by trend, seasonality and autocorrelation, and compute an autocorrelation.',
    prerequisite: 'Labs 01–18; correlation (Lab 05); temporal splits (Lab 06).',
    paragraphs: [
      'Hourly CPU usage of a service is not a bag of independent rows. The value at 14:00 is close to the value at 13:00, similar to 14:00 yesterday, and part of a slowly rising trend. Shuffle the rows and most of that information is destroyed.',
      'Many series decompose into a **trend** (slow change: growing traffic), **seasonality** (repeating patterns: daily and weekly cycles), and **noise** (the rest, which often has its own short memory). The playground\'s series has all three plus occasional spikes.',
      '**Autocorrelation** at lag k is the correlation between the series and itself shifted by k steps: `r_k = Σ(y_t − ȳ)(y_{t−k} − ȳ) / Σ(y_t − ȳ)²`. It measures how much the past k steps ago tells you about now.',
      'In the usage series, r₁ is about 0.9 (usage changes slowly), r₁₂ is low (the opposite side of the day), and r₂₄ and r₁₆₈ are high again (same hour yesterday, same hour last week). Peaks in the autocorrelation function (ACF) reveal seasonal periods and suggest which lags to use as features.',
      'Procedure: plot the series over its whole range and over a single week; compute the ACF; identify trend and seasonal periods; note outliers and structural breaks (a deployment that changed baseline usage). Only then design features and baselines.',
    ],
    formula: 'r_k = Σ_t (y_t − ȳ)(y_{t−k} − ȳ) / Σ_t (y_t − ȳ)²',
    experiment: 'Read the autocorrelation bars. Which two lags beyond 1 hour are strongest? Raise the noise level and describe how the ACF changes.',
    question: 'For the series [1, 2, 3, 2, 1] with mean 1.8, what is the numerator of r₁, Σ(y_t − ȳ)(y_{t−1} − ȳ) over t = 2…5? (Three decimals.)',
    answer: 0.16, tolerance: 0.0006,
    explanation: 'Deviations from 1.8 are −0.8, 0.2, 1.2, 0.2, −0.8. Products of neighbours: (0.2)(−0.8) + (1.2)(0.2) + (0.2)(1.2) + (−0.8)(0.2) = −0.16 + 0.24 + 0.24 − 0.16 = 0.16. Dividing by Σ(deviation²) = 2.8 gives r₁ ≈ 0.057.',
    reflection: 'Which seasonal periods would you expect in a time series from your work? What event could break the pattern?',
  },
  {
    id: 'l19-baselines',
    title: '19.2 · Forecasting baselines',
    sections: ['Horizons', 'Persistence', 'Seasonal naive', 'Hard to beat', 'Metrics for forecasts'],
    skill: 'Define a forecast horizon and build persistence and seasonal-naive baselines.',
    prerequisite: 'Lesson 19.1; baselines (Lab 06).',
    paragraphs: [
      'A forecast is made at an **origin** time t for a **horizon** h steps ahead: predict y_{t+h} using only data up to t. Capacity planning might need h = 24 hours; autoscaling, h = 1. Performance depends strongly on h, so always state it.',
      '**Persistence** predicts that the future equals the latest value: ŷ_{t+h} = y_t. For slowly changing series and short horizons it is remarkably good.',
      '**Seasonal naive** predicts the value one season ago at the same phase: for hourly data with a daily cycle, ŷ_{t+h} = y_{t+h−24} (for h ≤ 24). It captures the shape of the day but ignores today\'s level.',
      'These baselines are cheap and often surprisingly hard to beat. The playground\'s horizon curve shows persistence winning at h = 1 and losing badly at h = 6, while seasonal naive is flat across horizons. Any proposed model must beat the **better** of the two at each horizon.',
      'Use scale-dependent errors like MAE when one series is involved (errors in CPU percentage points). For many series with different scales, divide by the error of the seasonal naive forecast (the **MASE** idea) so that 1.0 means "no better than the baseline".',
    ],
    formula: 'persistence: ŷ_{t+h} = y_t     seasonal naive: ŷ_{t+h} = y_{t+h−s}     (s = 24 for a daily cycle, h ≤ s)',
    experiment: 'Set h = 1, 6 and 24. For each, record which baseline is better and by how much.',
    question: 'Hourly data with a daily cycle. A seasonal-naive forecast is made at t = 100 for horizon h = 5. Which time index\'s value does it use? (t + h − 24)',
    answer: 81,
    explanation: '100 + 5 − 24 = 81: the value at the same hour of day as the target, one day earlier.',
    reflection: 'What horizon matters for a forecast you might build? Which baseline would be hard to beat there?',
  },
  {
    id: 'l19-lags',
    title: '19.3 · Lag and rolling features',
    sections: ['Turn a series into a table', 'Lag features', 'Rolling statistics', 'Calendar features', 'Direct multi-step forecasting'],
    skill: 'Build a supervised dataset from a series with lag, rolling and calendar features for a chosen horizon.',
    prerequisite: 'Lessons 19.1–19.2; multiple regression (Lab 03).',
    paragraphs: [
      'Any regression model can forecast if we turn the series into rows. For origin t and horizon h, one row has features computed from y up to t and the target y_{t+h}. Sliding t across history produces a training table.',
      '**Lag features** are past values: y_t, y_{t−1}, y_{t−2}. The ACF suggests more: the value at the target\'s hour yesterday (y_{t+h−24}) and last week (y_{t+h−168}). Each must be known at time t — which is why the daily lag is taken relative to the target but at least one full day back.',
      '**Rolling features** summarize a window ending at t: the mean of the last 24 hours captures the current level while smoothing noise; a rolling standard deviation captures volatility. **Calendar features** — hour of day, day of week, holidays — let the model learn seasonal shapes directly.',
      'The playground uses **direct** forecasting: a separate model for each horizon h, with features aligned to that horizon. The alternative, **recursive** forecasting, predicts one step, feeds the prediction back as a lag and repeats — simpler to maintain, but errors compound.',
      'With these features, the playground\'s ridge regression beats both baselines at medium horizons: it combines the current level (from recent lags and the rolling mean) with the daily shape (from the seasonal lags).',
    ],
    formula: 'row(t) = [y_t, y_{t−1}, y_{t−2}, y_{t+h−24}, y_{t+h−168}, mean(y_{t−23..t})] → target y_{t+h}',
    experiment: 'Compare the three forecasts on the last-week plot at h = 6. Where does each one fail?',
    question: 'You forecast 6 hours ahead from origin t = 500. Is y at index 503 allowed as a feature?',
    choices: [
      { text: 'Yes — it is before the target at 506', why: 'Being before the target is not enough; it must be known when the forecast is made, at t = 500.' },
      { text: 'No — it is after the forecast origin', why: 'Only values at indices ≤ 500 exist when you make the forecast.' },
      { text: 'Yes, if it is lagged by one step', why: 'Lagging 503 by one gives 502, still after the origin.' },
    ],
    answer: 1,
    explanation: 'No: 503 > 500 is after the origin. Only values at indices ≤ 500 are known when the forecast is made.',
    reflection: 'List the features you would compute for a forecast in your domain. For each, write the latest time index it uses.',
  },
  {
    id: 'l19-walkforward',
    title: '19.4 · Walk-forward evaluation',
    sections: ['Evaluate like you deploy', 'Expanding windows', 'Refitting', 'Horizon-by-horizon results', 'Gaps and delays'],
    skill: 'Evaluate forecasts with walk-forward validation and report error by horizon.',
    prerequisite: 'Lessons 19.1–19.3; forward chaining (Lab 06).',
    paragraphs: [
      'In deployment you forecast from each new origin using everything seen so far. **Walk-forward evaluation** replays that: for each origin t in an evaluation period, train only on rows whose targets are at or before t, forecast y_{t+h}, then move t forward.',
      'Retraining at every origin is expensive; the playground refits once per day (every 24 origins) with an expanding window of all earlier data. Report the refit schedule — it is part of the method.',
      'Report error per horizon, not one number: short horizons are easier, and a model may beat the baselines at 6 hours but not at 1. The playground\'s horizon curve is the summary a capacity planner needs.',
      'Mind the training rows\' targets: a row with origin j and target j + h is only usable at origin t if j + h ≤ t. Using rows whose targets lie after t is leakage, even if their features look old.',
      'If actual values arrive late (usage is only aggregated the next morning), the latest value available at time t is older than y_t. Shift the features accordingly — evaluation must reproduce the information delay of real operation.',
    ],
    formula: 'for origin t in evaluation period: fit on {rows j : j + h ≤ t}; forecast y_{t+h}; score',
    experiment: 'Compare the walk-forward MAE of the regression at h = 1, 6 and 24. Does its advantage over the best baseline grow or shrink with the horizon?',
    question: 'Origin t = 600, horizon h = 24. What is the latest training-row origin j whose target (j + h) is allowed?',
    answer: 576,
    explanation: 'j + 24 ≤ 600, so j ≤ 576.',
    reflection: 'Describe how data actually arrives in a system you know. What delay would your evaluation need to simulate?',
  },
  {
    id: 'l19-leakage',
    title: '19.5 · Temporal leakage and honest reporting',
    sections: ['Features from the future', 'Warning signs', 'Where leaks hide', 'Beyond the basics', 'Demonstrate understanding'],
    skill: 'Detect temporal leakage, recognize its symptoms, and report forecasts honestly.',
    prerequisite: 'Lessons 19.1–19.4; leakage (Lab 06).',
    paragraphs: [
      'Turn on the leaky feature: a smoothed usage value around the target hour, of the kind a reporting job computes the next day. Error collapses — and stops growing with the horizon. The model is not forecasting; it is reading an answer that will not exist at prediction time.',
      'Symptoms: accuracy far better than strong baselines; error that does not increase with horizon; a single feature dominating importance; performance that collapses in production. Any one of them should trigger a leakage audit.',
      'Common hiding places: centered moving averages; features computed on the full series (a global normalization, a trend fitted to all data); joins with tables updated after the fact; target-derived features such as "daily total"; and random train/test splits, which interleave past and future (Lab 06).',
      'Real forecasting adds prediction intervals (usage will be between 40% and 65% with 90% probability), hierarchical series (per service and per cluster), external regressors (planned releases), and specialized models (exponential smoothing, ARIMA, gradient-boosted trees on lag features, sequence models in Lab 25). The evaluation discipline stays the same.',
      'You have completed this lab when you can: read an ACF; build persistence and seasonal-naive baselines; construct lag, rolling and calendar features that exist at prediction time; run a walk-forward evaluation; report error by horizon; and recognize temporal leakage. The Python challenge builds this pipeline.',
    ],
    formula: 'every feature for origin t must be computable from data available at time t',
    experiment: 'With the leak on, compare the horizon curve at h = 1 and h = 24. Turn it off. Write down the two symptoms that gave the leak away.',
    question: 'A 24-hour-ahead forecast has MAE 1.5, while the seasonal-naive baseline has 7.3 and a 1-hour-ahead forecast of the same model has 1.4. How many of the listed leakage symptoms (far better than baselines; no growth with horizon) are present?',
    answer: 2,
    explanation: 'Both: it beats the baseline by a factor of about 5, and its error barely grows from 1 to 24 hours. Audit the features before believing it.',
    reflection: 'Which of your data sources is updated after the fact? How could it leak into a forecasting feature?',
  },
]

export const sources = [
  { title: 'Hyndman & Athanasopoulos · Forecasting: Principles and Practice (3rd ed.)', url: 'https://otexts.com/fpp3/' },
  { title: 'scikit-learn · TimeSeriesSplit', url: 'https://scikit-learn.org/stable/modules/cross_validation.html#time-series-split' },
  { title: 'Hyndman & Koehler (2006) · Another look at measures of forecast accuracy (MASE)', url: 'https://doi.org/10.1016/j.ijforecast.2006.03.001' },
]
