// Lesson order for Lab 14: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l14-sequential': [
    { p: 0 }, { p: 1 },
    { predict: { prompt: 'The ensemble predicts 12 for a point whose target is 9. What residual does the next tree try to fit?', answer: -3, explain: 'r = y − F(x) = 9 − 12 = −3: the next tree should pull this region down.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'StageStepper', caption: 'Step through the stages: the ensemble (top) and the residuals it still misses, with the next stump (bottom).' },
    { cell: 1 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l14-gradient': [
    { p: 0 }, { p: 1 },
    { predict: { prompt: 'Squared loss ½(y − F)², with y = 2 and F = 5. What is the negative gradient −∂L/∂F?', answer: -3, explain: '−∂L/∂F = y − F = 2 − 5 = −3: the residual.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'GradientArrows', caption: 'Negative gradients at the training points, and the stump that generalizes them.' },
    { cell: 1 },
    { p: 3 },
    { figure: 'LossGradients', caption: 'The negative gradient each loss asks the next tree to fit.' },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l14-shrinkage': [
    { p: 0 },
    { predict: { prompt: 'With ν = 0.05, how much does a tree predicting a correction of −8 change the ensemble’s prediction?', answer: -0.4, tolerance: 0.001, explain: '0.05 × (−8) = −0.4.' } },
    { p: 1 }, { cell: 0 }, { cell: 1 }, { p: 2 }, { p: 3 }, { cell: 2 }, { p: 4 },
    { figure: 'ShrinkageCurves', caption: 'Training and validation error by stage. Compare ν = 1 with ν = 0.03, then raise the depth.' },
    { math: true },
  ],
  'l14-early': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'ShrinkageCurves', props: { patience: 20 }, caption: 'Early stopping: halt after this many stages without improvement, keep the best stage seen.' },
    { predict: { prompt: 'Validation MSE after stages 100, 200, 300, 400 is 0.40, 0.35, 0.36, 0.38. Which stage does early stopping keep?', answer: 200, explain: 'The lowest validation error, 0.35, occurs at stage 200.' } },
    { cell: 0 },
    { p: 3 }, { cell: 1 }, { p: 4 },
    { math: true },
    { ladder: 'boost' },
  ],
  'l14-practice': [
    { p: 0 }, { p: 1 },
    { figure: 'HistogramBins', caption: 'Exact thresholds versus histogram bin boundaries for one feature.' },
    { cell: 0 },
    { p: 2 }, { cell: 1 }, { p: 3 }, { p: 4 },
    { math: true },
  ],
}
