import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l14-sequential',
    title: '14.1 · Learn from the mistakes so far',
    sections: ['A different way to combine models', 'Residuals', 'Add a correction', 'Weak learners', 'Put it into practice'],
    skill: 'Describe boosting as sequentially fitting residuals with weak learners.',
    prerequisite: 'Lab 12 (regression trees), Lab 13 (ensembles), MSE and residuals (Lab 01).',
    paragraphs: [
      'Random forests train many strong, independent trees and average them to cut variance. **Boosting** does the opposite: it trains many **weak** models one after another, each one focused on what the ensemble so far still gets wrong. It mainly reduces bias.',
      'Start with the simplest prediction: the training mean. For each point, the **residual** `r = y − F(x)` is what that prediction misses. A point with y = 7 predicted as 5 has residual 2. The residuals are the remaining signal (plus noise).',
      'Fit a small regression tree to the residuals — not to y. Its prediction h(x) estimates the correction each region needs. Update the ensemble: `F(x) ← F(x) + ν·h(x)`. Recompute residuals and repeat. After M stages, `F(x) = mean(y) + ν Σ h_m(x)`.',
      'Each tree is a **weak learner**: often a stump (depth 1, one split) or depth 2–4. A single stump barely helps, but hundreds of them, each correcting the last, can represent complicated functions. Depth also controls interactions: a stump uses one feature at a time; depth 2 can capture two-feature interactions.',
      'In the playground, step through stages 0, 1 and 2: the residual plot shows the points the ensemble misses, the black step function is the next tree fitted to them, and the top plot shows the ensemble improving by a fraction of that correction.',
    ],
    formula: 'F₀ = mean(y);  r_i = y_i − F_{m−1}(x_i);  h_m = tree fit to r;  F_m = F_{m−1} + ν h_m',
    experiment: 'At ν = 1 and depth 1, compare stages 1, 2, 3 and 10. Describe what each new stump fixes.',
    question: 'The ensemble predicts 5 for a point whose target is 7. What residual will the next tree try to fit for that point?',
    answer: 2,
    explanation: 'r = y − F(x) = 7 − 5 = 2. The next tree tries to predict +2 in that point\'s region.',
    reflection: 'Explain in your own words how boosting differs from averaging independent trees.',
  },
  {
    id: 'l14-gradient',
    title: '14.2 · Why it is called gradient boosting',
    sections: ['The loss as a function of predictions', 'The negative gradient', 'Residuals are the gradient for squared error', 'Other losses', 'A step in function space'],
    skill: 'Connect residual fitting to gradient descent on the loss and generalize to other losses.',
    prerequisite: 'Lesson 14.1; gradient descent (Labs 01, 03, 08).',
    paragraphs: [
      'Think of the n training predictions F(x₁), …, F(x_n) as the parameters. The loss `L = Σ ½(yᵢ − F(xᵢ))²` depends on them, and gradient descent would move each prediction a little downhill.',
      'The derivative of ½(y − F)² with respect to F is −(y − F). The **negative gradient** is `y − F` — exactly the residual. Fitting a tree to residuals therefore approximates a gradient-descent step on the predictions, and ν plays the role of the learning rate.',
      'Why a tree instead of moving each prediction directly? Directly adjusting training predictions teaches nothing about new points. A tree turns the gradient into a **function** of x that generalizes: points in the same region get the same correction.',
      'For other losses, replace the residual with the negative gradient of that loss. For absolute error it is `sign(y − F)`, robust to outliers. For binary classification with log loss (Lab 08), F is a log-odds score and the negative gradient is `y − σ(F)` — the same "label minus probability" as logistic regression.',
      'This is why libraries such as XGBoost, LightGBM and scikit-learn\'s HistGradientBoosting can optimize many losses with one algorithm: compute the gradient, fit a tree to it, take a small step.',
    ],
    formula: '−∂/∂F [½(y − F)²] = y − F (the residual)     log loss: −∂ℓ/∂F = y − σ(F)',
    experiment: 'Look at stage 1\'s residual plot: those orange points are the negative gradient of the squared loss at stage 0. Where is it largest?',
    question: 'For squared loss ½(y − F)², y = 3 and F = 1. What is the negative gradient −∂L/∂F?',
    answer: 2,
    explanation: '−∂/∂F [½(3 − F)²] = (3 − F) = 2 — the residual.',
    reflection: 'Which loss would you boost for a target with occasional huge outliers? Why?',
  },
  {
    id: 'l14-shrinkage',
    title: '14.3 · Shrinkage, depth and the number of stages',
    sections: ['Take small steps', 'Rate versus stages', 'Tree depth', 'Subsampling', 'Three knobs that interact'],
    skill: 'Tune learning rate, tree depth and number of stages together.',
    prerequisite: 'Lessons 14.1–14.2.',
    paragraphs: [
      'With ν = 1, each tree fully corrects its residuals; the ensemble quickly starts fitting noise. With a small ν such as 0.1, each tree contributes only a tenth of its correction, and later trees get a chance to improve on it. Empirically, smaller steps with more stages generalize better — the same reason small learning rates are safer in gradient descent.',
      'Rate and stages trade off: halving ν roughly doubles the stages needed. A typical recipe is to pick a small ν (0.05–0.1) that you can afford and let early stopping choose the number of stages.',
      'Tree depth sets how complex each correction can be: depth 1 learns additive effects of single features; deeper trees learn interactions but each stage can overfit more. Depth 3–6 is common for tabular data.',
      '**Stochastic gradient boosting** fits each tree on a random subsample of rows (e.g. 50–80%). Like bagging, this adds diversity and reduces variance, and it speeds up training.',
      'In the playground: at ν = 1, validation error bottoms out early and then rises; at ν = 0.03 it falls slowly and reaches a lower minimum. Raise the depth and every setting overfits sooner.',
    ],
    formula: 'F_M = F₀ + ν Σ_{m=1..M} h_m     smaller ν ⇒ larger best M, usually lower validation error',
    experiment: 'For ν = 1, 0.3 and 0.03, record the best stage and the best validation MSE. Then repeat at depth 3.',
    question: 'With ν = 0.1, how much does a tree predicting a correction of +5 change the ensemble\'s prediction?',
    answer: 0.5,
    explanation: '0.1 × 5 = 0.5. The remaining 4.5 is left for later trees to address.',
    reflection: 'If training time were limited, which of the three knobs would you tune first, and why?',
  },
  {
    id: 'l14-early',
    title: '14.4 · Overfitting and early stopping',
    sections: ['Training error always falls', 'Validation error turns', 'Early stopping', 'Honest selection', 'Boosting versus forests'],
    skill: 'Detect boosting overfitting and choose the number of stages with validation data.',
    prerequisite: 'Lessons 14.1–14.3; validation (Lab 06).',
    paragraphs: [
      'Every stage reduces training loss — each tree is fitted to decrease it — so training error keeps falling toward zero. Unlike adding trees to a random forest, adding stages to boosting **can** overfit: late trees fit noise in the residuals.',
      'Validation error typically falls, flattens and rises. The stage with the lowest validation error is the best model of this sequence. The playground marks it with a dashed line.',
      '**Early stopping** monitors validation error during training and stops when it has not improved for a set number of stages ("patience"), then keeps the best stage. It is cheap and nearly universal in boosting libraries.',
      'The validation set used for early stopping has now been used to choose a hyperparameter, so its score is optimistic (Lab 06). Report performance on a separate test set, or use cross-validation for the whole procedure.',
      'Forests: deep trees, parallel, reduce variance, hard to overfit by adding trees, few knobs. Boosting: shallow trees, sequential, reduce bias, needs early stopping and tuning, often the most accurate model for tabular data. Both beat a single tree by a wide margin.',
    ],
    formula: 'M* = argmin_M validation_error(F_M)     stop when no improvement for `patience` stages',
    experiment: 'Set noise σ = 0.8 and ν = 1. Where is the best stage? Drag the stage slider to 400 and compare validation MSE with the best.',
    question: 'Validation MSE after stages 50, 100, 150 and 200 is 0.31, 0.27, 0.28, 0.30. Which stage does early stopping keep?',
    answer: 100,
    explanation: 'Stage 100 has the lowest validation MSE (0.27); later stages overfit.',
    reflection: 'How would you report the performance of a boosted model whose number of stages was chosen on validation data?',
  },
  {
    id: 'l14-practice',
    title: '14.5 · Gradient boosting in practice',
    sections: ['Library implementations', 'Histogram binning', 'Categorical and missing data', 'Interpretation', 'Demonstrate understanding'],
    skill: 'Use gradient-boosting libraries responsibly and explain what they add to the basic algorithm.',
    prerequisite: 'Lessons 14.1–14.4.',
    paragraphs: [
      'Production libraries (XGBoost, LightGBM, CatBoost, scikit-learn\'s `HistGradientBoostingRegressor`) implement the algorithm you built, plus: second-order (Newton) steps, regularization of leaf values, row and column subsampling, and native early stopping.',
      'Instead of trying every threshold, they bin each feature into ~256 histogram buckets once and scan bucket boundaries. This makes each split search nearly independent of n and is why they scale to millions of rows.',
      'Missing values can be routed to whichever branch reduces loss more, learned during training. Categorical features can be handled natively by some libraries; others need encoding. Apply exactly the same preprocessing at prediction time.',
      'Interpretation tools include permutation importance, partial dependence plots (average prediction as one feature varies) and SHAP values. Treat them as descriptions of the model, not of causes in the world (Lab 05).',
      'You have completed this lab when you can: explain residual fitting as gradient descent; implement boosting with regression stumps; tune ν, depth and stages; choose the stage by validation; and compare boosting with forests. The Python challenge builds a boosted regressor from scratch.',
    ],
    formula: 'library defaults: ν ≈ 0.1, depth 3–8, early stopping on validation, subsampling ≈ 0.8',
    experiment: 'Compare the best validation MSE at depth 1 and depth 3 for this one-feature problem. Why does depth matter less when there is only one feature?',
    question: 'A histogram-based booster bins a feature into 256 buckets. At most how many candidate thresholds does it scan for that feature at one node?',
    answer: 255,
    explanation: 'Boundaries between 256 buckets: 255 candidates, regardless of how many rows there are.',
    reflection: 'For a tabular problem you know, would you start with a random forest or gradient boosting? What would make you switch?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 8.2.3: boosting', url: 'https://www.statlearning.com/' },
  { title: 'Friedman (2001) · Greedy function approximation: a gradient boosting machine', url: 'https://doi.org/10.1214/aos/1013203451' },
  { title: 'scikit-learn · Gradient boosting (HistGradientBoosting)', url: 'https://scikit-learn.org/stable/modules/ensemble.html#gradient-boosting' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
