export const lessons = [
  {
    id: 'l42-functions',
    title: '42.1 · From weights to functions',
    sections: ['Uncertainty about functions', 'Integrating out the weights', 'The definition', 'Kernels are covariances', 'Put it into practice'],
    skill: 'Explain a Gaussian process as a distribution over functions and derive a kernel from a weight-space model.',
    prerequisite: 'Lab 41 (Bayesian linear regression), multivariate Gaussians (Labs 18, 40).',
    paragraphs: [
      'Bayesian linear regression (Lab 41) put a prior on weights and got uncertainty about functions as a side effect. A **Gaussian process** (GP) skips the weights and puts the prior directly on the function.',
      'Take f(x) = φ(x)ᵀw with w ~ N(0, α⁻¹I). Then f(x) is Gaussian with mean 0, and the covariance of two function values is Cov[f(x), f(x′)] = φ(x)ᵀφ(x′)/α. Only inner products of features appear — the weights have been integrated out.',
      'A GP is a collection of random variables f(x), one per input, such that **any finite set of them is jointly Gaussian**. It is fully described by a mean function m(x) (usually 0) and a **covariance function** or **kernel** k(x, x′) = Cov[f(x), f(x′)].',
      'The kernel encodes your beliefs about functions: how smooth they are, how quickly they vary, whether they repeat. Any kernel that always produces a positive semidefinite covariance matrix is valid — including kernels that correspond to infinitely many features, like the RBF kernel.',
      'Procedure: pick a kernel that matches what you believe about the function; draw samples from the prior and ask whether they look like plausible functions; only then look at data.',
    ],
    formula: 'f ~ GP(m, k):  (f(x₁), …, f(xₙ)) ~ N(m, K),  Kᵢⱼ = k(xᵢ, xⱼ)     weight space: k(x, x′) = φ(x)ᵀφ(x′)/α',
    derivation: {
      title: 'Derive the kernel of Bayesian linear regression',
      intro: 'One feature φ(x) = x and one weight w ~ N(0, 1/α), so f(x) = w·x.',
      steps: [
        { prompt: 'Cov[f(x), f(x′)] = E[w·x · w·x′]. Write it in terms of x, x′ (type xp) and α.', answer: 'x*xp/α', show: '`x·x′/α`', vars: { x: [-2, 2], xp: [-2, 2], α: [0.5, 4] } },
        { prompt: 'With α = 2, what is the prior variance of f(3)?', number: 4.5, show: '`9/2 = 4.5`' },
        { prompt: 'Correlation of f(1) and f(−1)? (It does not depend on α.)', number: -1, show: '`−1`', why: 'Every sampled function is a line through the origin: f(−1) is always −f(1).' },
      ],
      result: 'A kernel is exactly the covariance of function values; a model with features gives a kernel as their inner product.',
    },
    experiment: 'In the prior view, choose the linear kernel and draw functions, then switch to RBF. Which assumptions about f does each kernel make?',
    question: 'f(x) = w·x with w ~ N(0, 1/α) and α = 4. What is Cov[f(2), f(3)]?',
    answer: 1.5,
    explanation: '2 × 3 / 4 = 1.5.',
    reflection: 'Describe a function in your work that you would like to learn. Is it smooth, rough, periodic, trending? Which kernel matches that belief?',
  },
  {
    id: 'l42-kernels',
    title: '42.2 · Choosing and combining kernels',
    sections: ['The RBF kernel', 'Length scale and signal scale', 'Rougher and periodic kernels', 'Building kernels', 'Valid kernels'],
    skill: 'Choose, parameterize and combine kernels to express assumptions about a function.',
    prerequisite: 'Lesson 42.1.',
    paragraphs: [
      'The **squared exponential** or RBF kernel k(x, x′) = σf² exp(−(x − x′)²/(2ℓ²)) says nearby inputs have strongly correlated outputs, with correlation fading smoothly with distance. Its samples are infinitely differentiable.',
      'The **length scale** ℓ sets how far you must move before the function changes appreciably: at distance ℓ the correlation is e^(−1/2) ≈ 0.61; at 3ℓ it is about 0.011. The **signal scale** σf sets the typical size of the function’s values.',
      '**Matérn** kernels (here ν = 3/2) produce rougher functions — often more realistic for physical measurements. A **periodic** kernel makes f(x) and f(x + period) perfectly correlated. A **linear** kernel gives straight lines, as in Lesson 42.1.',
      'Kernels combine: the **sum** k₁ + k₂ models a function that is the sum of two independent parts (trend plus wiggles); the **product** k₁·k₂ models interactions (a periodic pattern whose shape drifts slowly). Much of GP modelling is composing kernels that tell the story of the data.',
      'A function k is a valid kernel if every matrix Kᵢⱼ = k(xᵢ, xⱼ) is positive semidefinite (Mercer’s condition). Sums, products and positive scalings of valid kernels are valid. Invalid “similarities” can give negative variances and crash the Cholesky factorization.',
    ],
    formula: 'RBF: σf² exp(−(x − x′)²/2ℓ²)     Matérn 3/2: σf²(1 + √3r/ℓ) exp(−√3r/ℓ)     sums and products of kernels are kernels',
    derivation: {
      title: 'Read correlations off the RBF kernel',
      steps: [
        { prompt: 'Write the RBF correlation k(x, x′)/σf² as a function of the distance d and ℓ.', answer: 'exp(-d^2/(2ℓ^2))', show: '`exp(−d²/(2ℓ²))`', vars: { d: [0, 2], ℓ: [0.1, 1] }, hint: 'Type ℓ as ell.' },
        { prompt: 'Correlation at distance d = ℓ? (Four decimals.)', number: Math.exp(-0.5), tolerance: 1e-4, show: '`e^(−1/2) ≈ 0.6065`' },
        { prompt: 'At distance d = 2ℓ?', number: Math.exp(-2), tolerance: 1e-4, show: '`e^(−2) ≈ 0.1353`' },
      ],
      result: 'Only d/ℓ matters: the length scale is the unit of “near”.',
    },
    experiment: 'In the prior view, compare RBF and Matérn at the same length scale, then try the sum kernel. Describe each kind of function in one sentence.',
    question: 'RBF kernel with σf = 2 and ℓ = 0.5. What is k(0, 0)?',
    answer: 4,
    explanation: 'k(x, x) = σf² = 4: the prior variance of f at any single point.',
    reflection: 'Which kernel sum would describe “daily cycles on top of a slow trend”?',
  },
  {
    id: 'l42-regression',
    title: '42.3 · Regression by conditioning',
    sections: ['A joint Gaussian', 'The posterior mean', 'The posterior variance', 'Noise', 'Cost'],
    skill: 'Derive and compute the GP posterior mean and variance from the joint Gaussian.',
    prerequisite: 'Lessons 42.1–42.2; conditional Gaussians.',
    paragraphs: [
      'Observations y = f(X) + noise with noise variance σn², and an unknown f* = f(x*). Under the GP they are jointly Gaussian: y has covariance K + σn²I, f* has variance k(x*, x*), and their covariance is the vector k* of k(x*, xᵢ).',
      'Conditioning a joint Gaussian on some of its variables gives another Gaussian. The **posterior mean** is μ* = k*ᵀ(K + σn²I)⁻¹y: a weighted combination of the observations, with weights set by the kernel.',
      'The **posterior variance** is σ*² = k(x*, x*) − k*ᵀ(K + σn²I)⁻¹k*: the prior variance minus what the observations explain. Near data it is small; far away it returns to the prior variance.',
      'With σn → 0 the mean interpolates the observations exactly; a larger σn lets it pass between them. Predicting a new noisy observation y* adds σn² to the variance.',
      'Computing (K + σn²I)⁻¹ costs O(n³) time and O(n²) memory — fine for a few thousand points, hopeless for millions. Use a Cholesky factorization rather than an inverse, and for large n use sparse approximations with m ≪ n inducing points (O(nm²)).',
    ],
    formula: 'μ* = k*ᵀ(K + σn²I)⁻¹y     σ*² = k(x*, x*) − k*ᵀ(K + σn²I)⁻¹k*',
    derivation: {
      title: 'GP regression with one observation',
      intro: 'RBF kernel with σf = 1; one observation y1 at x1; noise variance s2; a test point whose kernel value with x1 is k (so 0 ≤ k ≤ 1).',
      steps: [
        { prompt: 'The posterior mean is k·(1 + s2)⁻¹·y1. Write it.', answer: 'k*y1/(1+s2)', show: '`k·y1 / (1 + s2)`', vars: { k: [0, 1], y1: [-2, 2], s2: [0.01, 1] } },
        { prompt: 'Write the posterior variance.', answer: '1 - k^2/(1+s2)', show: '`1 − k²/(1 + s2)`', vars: { k: [0, 1], s2: [0.01, 1] } },
        { prompt: 'At the observation itself (k = 1) with s2 = 0.01, what is the posterior variance? (Four decimals.)', number: 1 - 1 / 1.01, tolerance: 1e-4, show: '`1 − 1/1.01 ≈ 0.0099`', why: 'Almost the noise variance: we know f there to within the noise.' },
        { prompt: 'Far away (k = 0)?', number: 1, show: '`1`', why: 'The prior variance: the observation tells us nothing about distant f.' },
      ],
      result: 'The observation shrinks the variance in proportion to k²: exactly as far as the kernel says the point is relevant.',
    },
    experiment: 'In the posterior view, add observations one at a time and watch the sd in the gap. Then change the noise from 0.01 to 0.4. What happens to the mean at the observations?',
    question: 'One observation y = 2 with σn² = 1 and kernel value k = 0.5 between it and x* (σf = 1). What is the posterior mean at x*?',
    answer: 0.5,
    explanation: '0.5 × 2 / (1 + 1) = 0.5.',
    reflection: 'You have 200,000 observations. What would you do instead of an exact GP?',
  },
  {
    id: 'l42-hyper',
    title: '42.4 · Hyperparameters from the marginal likelihood',
    sections: ['The evidence for a kernel', 'Fit versus complexity', 'Optimizing it', 'Too short, too long', 'Cross-validation still matters'],
    skill: 'Choose kernel hyperparameters and kernels with the log marginal likelihood and interpret its terms.',
    prerequisite: 'Lessons 42.1–42.3; model evidence (Lab 41).',
    paragraphs: [
      'The observations are Gaussian with covariance Kθ + σn²I, so the probability of the data given the hyperparameters θ is available in closed form. Its log is the **log marginal likelihood**: log p(y | θ) = −½ yᵀ(K + σn²I)⁻¹y − ½ log|K + σn²I| − (n/2) log 2π.',
      'The first term rewards **fit**; the second penalizes **complexity**: flexible kernels make |K| large because they could explain many different datasets. It is the evidence of Lab 41, with the function integrated out instead of the weights.',
      'Practitioners maximize it with gradient methods (scikit-learn restarts its optimizer from several points, since the surface can have local optima). The playground scans a grid of length scales so you can see the whole curve.',
      'For the observations here, ℓ = 0.2 scores best; ℓ = 0.03 produces a mean that sags to zero between points, and ℓ = 0.5 cannot follow the wiggles. The same score rejects the periodic kernel with the wrong period by a wide margin.',
      'With few observations, the marginal likelihood can be flat or misleading, and a mis-specified kernel can still be optimized confidently. Check predictions with held-out data or cross-validation, and look at posterior samples: if they look nothing like plausible functions, the kernel is wrong.',
    ],
    formula: 'log p(y | θ) = −½ yᵀKy⁻¹y − ½ log|Ky| − (n/2) log 2π,   Ky = Kθ + σn²I',
    derivation: {
      title: 'The marginal likelihood of one observation',
      intro: 'One observation y with prior variance σf² = 1 and noise variance s2, so y ~ N(0, 1 + s2).',
      steps: [
        { prompt: 'Write log p(y) in terms of y and s2.', answer: '-y^2/(2*(1+s2)) - 0.5*log(1+s2) - 0.5*log(2*pi)', show: '`−y²/(2(1 + s2)) − ½ log(1 + s2) − ½ log 2π`', vars: { y: [-2, 2], s2: [0.01, 2] } },
        { prompt: 'Differentiate with respect to s2.', answer: 'y^2/(2*(1+s2)^2) - 1/(2*(1+s2))', show: '`y²/(2(1 + s2)²) − 1/(2(1 + s2))`', vars: { y: [-2, 2], s2: [0.01, 2] } },
        { prompt: 'Set it to zero: with y = 2, which noise variance s2 maximizes the marginal likelihood?', number: 3, show: '`1 + s2 = y² ⇒ s2 = 3`', why: 'The total variance is matched to the observed y²: fit and complexity balanced.' },
      ],
      result: 'Maximizing the evidence matches the model’s predicted spread to the data’s actual spread — no more, no less.',
    },
    experiment: 'In the hyperparameter view, compare the curve for noise 0.01 and 0.2. Does the best length scale move? Which kernel has the highest marginal likelihood?',
    question: 'Two kernels score log marginal likelihoods of −1.6 and −3.3. What is the Bayes factor in favour of the first? (One decimal.)',
    answer: 5.5, tolerance: 0.1,
    explanation: 'exp(−1.6 − (−3.3)) = e^1.7 ≈ 5.5.',
    reflection: 'When would you distrust a hyperparameter chosen by maximizing the marginal likelihood?',
  },
  {
    id: 'l42-uses',
    title: '42.5 · Where GPs shine — and where they do not',
    sections: ['Bayesian optimization', 'Active learning and emulators', 'Classification needs approximations', 'Scaling and dimensionality', 'Demonstrate understanding'],
    skill: 'Recognize problems suited to Gaussian processes and their limitations.',
    prerequisite: 'Lessons 42.1–42.4.',
    paragraphs: [
      'GPs excel when observations are **expensive** and uncertainty guides the next step. **Bayesian optimization** tunes hyperparameters or experiments by fitting a GP to the results so far and choosing the next point where an acquisition function — expected improvement, or an upper confidence bound μ + κσ — is highest, balancing exploitation (high μ) and exploration (high σ).',
      '**Active learning** measures where the posterior variance is largest. **Emulators** replace slow simulations (climate, engineering) with a GP trained on a few runs, complete with error bars.',
      'For classification, the likelihood is not Gaussian, so the posterior is no longer exact: Laplace approximations, expectation propagation or variational inference (Lab 44) are needed.',
      'Exact GPs scale as O(n³). Inducing-point approximations reach hundreds of thousands of points. In high dimensions a single length scale is too crude: use one length scale per input (**automatic relevance determination**) — inputs with long learned length scales barely matter.',
      'You have completed this lab when you can: explain a GP as a distribution over functions; derive a kernel from a weight-space model; choose and combine kernels; derive and compute the posterior mean and variance; choose hyperparameters and kernels by marginal likelihood while checking them; and name where GPs fit and where they do not. The Python challenge implements exact GP regression and checks it against scikit-learn.',
    ],
    formula: 'UCB acquisition: a(x) = μ(x) + κ·σ(x)     ARD: k(x, x′) = σf² exp(−½ Σⱼ (xⱼ − x′ⱼ)²/ℓⱼ²)',
    derivation: {
      title: 'Upper-confidence-bound acquisition',
      steps: [
        { prompt: 'Candidate A: μ = 1.0, σ = 0.1. Candidate B: μ = 0.8, σ = 0.3. With κ = 2, what is the UCB of A?', number: 1.2, show: '`1.0 + 2 × 0.1 = 1.2`' },
        { prompt: 'And of B?', number: 1.4, show: '`0.8 + 2 × 0.3 = 1.4`', why: 'B is chosen: its predicted value is lower, but it is uncertain enough that it might be better.' },
        { prompt: 'Below which κ would A be chosen instead? (Solve 1.0 + 0.1κ = 0.8 + 0.3κ.)', number: 1, show: '`κ = 1`' },
      ],
      result: 'κ is the exploration dial: small κ trusts the mean, large κ chases uncertainty.',
    },
    experiment: 'In the posterior view with 8 observations, where would an upper-confidence-bound rule measure next? Add observations and check whether the gap is filled first.',
    question: 'An exact GP takes 1 second for n = 1,000 points. Roughly how long for n = 10,000, given O(n³) cost? (Seconds.)',
    answer: 1000,
    explanation: '(10,000/1,000)³ = 1,000 — about 17 minutes, and 100 times the memory.',
    reflection: 'Name an expensive experiment or tuning process in your work where Bayesian optimization could save runs.',
  },
]

export const sources = [
  { title: 'Rasmussen & Williams · Gaussian Processes for Machine Learning (free book)', url: 'https://gaussianprocess.org/gpml/' },
  { title: 'Görtler, Kehlbeck & Deussen · A visual exploration of Gaussian processes (Distill)', url: 'https://distill.pub/2019/visual-exploration-gaussian-processes/' },
  { title: 'Duvenaud · The kernel cookbook', url: 'https://www.cs.toronto.edu/~duvenaud/cookbook/' },
  { title: 'scikit-learn · Gaussian processes', url: 'https://scikit-learn.org/stable/modules/gaussian_process.html' },
]
