export const lessons = [
  {
    id: 'l47-hoeffding',
    title: '47.1 · The generalization question',
    sections: ['Training error is an estimate', 'Assumptions', 'Hoeffding’s inequality', 'How much data for one hypothesis?', 'Put it into practice'],
    skill: 'State the generalization question precisely and bound the gap for a single hypothesis.',
    prerequisite: 'Core labs 01–33, especially evaluation (Lab 06) and overfitting (Lab 07); probability (Lab 04).',
    paragraphs: [
      'A model’s **true risk** R(h) is its expected error on the distribution it will meet; its **empirical risk** R̂(h) is its average error on the n training examples. Learning theory asks when a small R̂ guarantees a small R.',
      'The standard assumption: training and future examples are drawn **independently from the same distribution**. Every guarantee in this lab depends on it; leakage, drift and selection effects (Labs 06, 30, 45) break it.',
      'For one hypothesis fixed in advance, each training example is an independent coin flip “error or not”. **Hoeffding’s inequality** bounds how far the average of n such flips strays from its mean: P(|R̂(h) − R(h)| > ε) ≤ 2·exp(−2nε²).',
      'Setting the right side to δ and solving gives ε = √(ln(2/δ) / (2n)): with probability at least 1 − δ, the training error is within ε of the truth. With n = 100 and δ = 0.05, ε ≈ 0.136. Four times the data halves ε.',
      'This is exactly why a held-out test set works: the model was fixed before looking at it, so Hoeffding applies. The trouble starts when the data were used to choose the hypothesis — which is what training does.',
    ],
    formula: 'P(|R̂(h) − R(h)| > ε) ≤ 2 exp(−2nε²)     ε = √(ln(2/δ) / 2n)',
    derivation: {
      title: 'Solve Hoeffding for ε and for n',
      steps: [
        { prompt: 'Set 2·exp(−2nε²) = δ and solve for ε. Write ε in terms of n and δ.', answer: 'sqrt(log(2/δ)/(2*n))', show: '`√(ln(2/δ) / (2n))`', vars: { n: [10, 1000], δ: [0.01, 0.2] }, hint: 'Type δ as delta.' },
        { prompt: 'With n = 100 and δ = 0.05, ε = ? (Three decimals.)', number: Math.sqrt(Math.log(40) / 200), tolerance: 1e-3, show: '`≈ 0.136`' },
        { prompt: 'Solve instead for n: how many examples for ε = 0.05 and δ = 0.05? (Round up.)', number: Math.ceil(Math.log(40) / (2 * 0.0025)), show: '`ln 40 / (2 × 0.0025) ≈ 738`' },
      ],
      result: 'Halving ε costs four times the data: the square-root law again.',
    },
    experiment: 'In the bounds view, set |H| = 1 and move n from 25 to 800. How does the bound shrink, and how does the actual worst gap compare?',
    question: 'A test set has 2,500 examples. With probability 95%, how far can the test error be from the true error at most, by Hoeffding? (Three decimals.)',
    answer: 0.0272, tolerance: 0.001,
    explanation: '√(ln 40 / 5000) ≈ 0.0272 — about 2.7 percentage points.',
    reflection: 'Which of your model evaluations quietly violate the “fixed before looking at the data” condition?',
  },
  {
    id: 'l47-finite',
    title: '47.2 · Finite classes and the union bound',
    sections: ['Training chooses the hypothesis', 'Uniform convergence', 'The union bound', 'What ERM guarantees', 'Where the bound is loose'],
    skill: 'Derive the generalization bound for a finite hypothesis class and the ERM guarantee.',
    prerequisite: 'Lesson 47.1.',
    paragraphs: [
      '**Empirical risk minimization** (ERM) returns the hypothesis ĥ with the lowest training error. ĥ depends on the data, so the single-hypothesis bound does not apply to it: of many hypotheses, one may look good by luck.',
      'The fix is **uniform convergence**: if every hypothesis’s training error is within ε of its true error simultaneously, then so is ĥ’s.',
      'By the **union bound**, the chance that at least one of |H| hypotheses is off by more than ε is at most |H| times the single chance: 2|H|·exp(−2nε²). So with probability 1 − δ, all gaps are below ε = √((ln|H| + ln(2/δ)) / (2n)). The class size enters only through its logarithm.',
      'Consequence for ERM: R(ĥ) ≤ R̂(ĥ) + ε ≤ R̂(h*) + ε ≤ R(h*) + 2ε, where h* is the best hypothesis in the class. The learned model is at most 2ε worse than the best possible in H.',
      'The bound is worst-case. In the playground (n = 100, 50 thresholds) it promises 0.195 while the actual 95th-percentile worst gap is about 0.14; with 1,000 thresholds the bound grows but the actual gap barely moves, because nearly identical hypotheses fail together. Counting hypotheses over-counts.',
    ],
    formula: 'with probability ≥ 1 − δ: ∀h ∈ H, |R̂(h) − R(h)| ≤ √((ln|H| + ln(2/δ)) / 2n)     R(ĥ) ≤ R(h*) + 2ε',
    derivation: {
      title: 'Sample complexity of a finite class',
      steps: [
        { prompt: 'Solve ε = √((ln|H| + ln(2/δ)) / 2n) for n. Write it using H for |H|.', answer: '(log(H) + log(2/δ))/(2*ε^2)', show: '`(ln|H| + ln(2/δ)) / (2ε²)`', vars: { H: [2, 1000], δ: [0.01, 0.2], ε: [0.01, 0.2] }, hint: 'Type δ as delta and ε as epsilon.' },
        { prompt: 'How many examples for |H| = 1,000, ε = 0.05, δ = 0.05? (Round up.)', number: Math.ceil((Math.log(1000) + Math.log(40)) / 0.005), show: '`(ln 1000 + ln 40)/0.005 ≈ 2,120`' },
        { prompt: 'Multiply the class size by 1,000 (|H| = 10⁶). How many examples now? (Round up.)', number: Math.ceil((Math.log(1e6) + Math.log(40)) / 0.005), show: '`≈ 3,501`', why: 'A thousand times more hypotheses cost only about 65% more data — the logarithm at work.' },
      ],
      result: 'Model selection over many candidates is affordable, but not free: every extra comparison uses up some of the data’s evidence.',
    },
    experiment: 'In the bounds view, keep n = 100 and compare |H| = 10, 50 and 1,000. Which moves more: the union bound or the actual 95% gap? Why?',
    question: 'Choosing among 20 candidate models with a validation set of 1,000 examples, what ε does the union bound give with δ = 0.05? (Three decimals.)',
    answer: 0.0578, tolerance: 0.001,
    explanation: 'ln 20 ≈ 2.996 and ln 40 ≈ 3.689, so ε = √(6.685 / 2000) ≈ 0.058 — the best of 20 models may look up to about 6 points better than it truly is.',
    reflection: 'How many models did you compare on your last validation set? How much should that temper the winner’s score?',
  },
  {
    id: 'l47-vc',
    title: '47.3 · VC dimension',
    sections: ['Infinite classes', 'Shattering', 'Half-planes have VC dimension d + 1', 'The VC bound', 'Counting behaviours, not parameters'],
    skill: 'Determine the VC dimension of simple classes and interpret the VC generalization bound.',
    prerequisite: 'Lessons 47.1–47.2; linear classifiers (Labs 08, 15).',
    paragraphs: [
      'Linear classifiers form an infinite class, so ln|H| is useless. But on n given points, they can only produce finitely many different labellings. Capacity should count **distinct behaviours on data**, not hypotheses.',
      'A class **shatters** a set of points if it can produce every one of the 2ⁿ labellings. The **VC dimension** is the size of the largest set it can shatter.',
      'Half-planes in 2D shatter three points in general position (all 8 labellings) but no set of four (the square fails on XOR, a point inside a triangle cannot be separated): VC dimension 3. In d dimensions, half-planes have VC dimension d + 1. Intervals on a line have VC dimension 2.',
      'The VC theorem replaces ln|H| by about d_VC·ln(n): with probability 1 − δ, R(h) ≤ R̂(h) + O(√((d_VC·ln(n/d_VC) + ln(1/δ)) / n)) for all h. The number of examples needed grows roughly linearly with the VC dimension.',
      'VC dimension counts behaviours, not parameters: a one-parameter classifier sign(sin(θx)) has infinite VC dimension, while many parameters can have modest VC dimension. For linear models, though, the count of weights is a good guide.',
    ],
    formula: 'd_VC = largest n with 2ⁿ labellings realizable     R(h) ≤ R̂(h) + O(√((d_VC log(n/d_VC) + log(1/δ)) / n))',
    derivation: {
      title: 'Counting labellings',
      steps: [
        { prompt: 'How many labellings of 3 points are there?', number: 8, show: '`2³ = 8`' },
        { prompt: 'How many labellings of a square’s 4 corners can a half-plane realize?', number: 14, show: '`16 − 2 = 14` (both XOR labellings fail)' },
        { prompt: 'VC dimension of half-planes in 5 dimensions?', number: 6, show: '`d + 1 = 6`' },
      ],
      result: 'Capacity is about how many ways the class can label data, and for linear classifiers that is d + 1.',
    },
    experiment: 'In the shattering view, check all four point sets. Why do the collinear points fail even though half-planes have VC dimension 3?',
    question: 'Intervals on the real line (label 1 inside [a, b], 0 outside). What is their VC dimension?',
    answer: 2,
    explanation: 'Two points can be labelled every way; three points cannot produce 1, 0, 1 (an interval containing the outer two contains the middle one).',
    reflection: 'Which model in your toolbox has far more parameters than its effective capacity suggests?',
  },
  {
    id: 'l47-modern',
    title: '47.4 · What the bounds miss: double descent',
    sections: ['Loose, worst-case, but directionally right', 'Deep networks break the story', 'The interpolation threshold', 'Minimum-norm solutions', 'Other kinds of bounds'],
    skill: 'Explain double descent and why parameter counts alone do not predict generalization.',
    prerequisite: 'Lessons 47.1–47.3; ridge regression (Lab 07), neural networks (Labs 21–22).',
    paragraphs: [
      'Classical bounds are loose and worst-case, but they predict the U-shaped curve of Lab 07: more capacity, more overfitting. Modern networks have far more parameters than examples, fit random labels perfectly, yet generalize well on real data. Counting capacity alone cannot explain that.',
      'The playground’s random-features regression shows the resolution. With p < n features, test error falls then rises as usual. At p = n the model can just barely interpolate every training point, noise included, and needs huge weights: test error explodes (about 35 here, against about 0.8 at p = 20).',
      'Past the threshold there are infinitely many interpolating solutions, and least squares picks the one with the **smallest norm**. As p grows, that solution becomes smoother and test error falls again — to about 0.59 at p = 400, better than any smaller model. That is **double descent**.',
      'What controls generalization, then, is not raw size but the **effective complexity of the solution found**: its norm, its margin, how gradient descent’s implicit bias selects among interpolators. A small ridge penalty removes the spike entirely.',
      'Other theories target this: margin and norm-based bounds (the SVM bound of Lab 15), PAC-Bayes bounds, algorithmic stability, and compression arguments. None is a complete theory of deep learning yet — an open research area.',
    ],
    formula: 'min-norm fit: w = Φᵀ(ΦΦᵀ)⁻¹y when p > n;  ridge: w = (ΦᵀΦ + λI)⁻¹Φᵀy',
    derivation: {
      title: 'Why the norm explodes at the threshold',
      intro: 'One feature, one training point: minimize nothing but fit exactly, w·φ = y.',
      steps: [
        { prompt: 'Write the interpolating weight w in terms of φ and y.', answer: 'y/φ', show: '`w = y/φ`', vars: { y: [-2, 2], φ: [0.05, 2] }, hint: 'Type φ as phi.' },
        { prompt: 'With y = 1 (all noise) and a tiny feature value φ = 0.01, what is w?', number: 100, show: '`100`', why: 'Fitting noise through a nearly degenerate feature needs a huge weight — which then wrecks predictions elsewhere.' },
        { prompt: 'With ridge λ, the weight is y·φ/(φ² + λ). Evaluate for y = 1, φ = 0.01, λ = 0.1. (Four decimals.)', number: 0.01 / (0.0001 + 0.1), tolerance: 1e-4, show: '`≈ 0.0999`' },
      ],
      result: 'At the interpolation threshold the design matrix is nearly singular; ridge (or more features) removes the near-singularity.',
    },
    experiment: 'In the double-descent view, compare training and test error around p = 40, then add the ridge penalty. Which part of the curve changes most?',
    question: 'In the playground, the best test error with fewer than 40 features is about 0.78 and the test error with 400 features is about 0.59. By what fraction is the large model better? (Two decimals.)',
    answer: 0.24, tolerance: 0.02,
    explanation: '(0.78 − 0.59)/0.78 ≈ 0.24: the heavily overparameterized model beats the best “classical” size by about a quarter.',
    reflection: 'Your model fits the training data perfectly. What else would you check before concluding it overfits?',
  },
  {
    id: 'l47-practice',
    title: '47.5 · Approximation, estimation and practical lessons',
    sections: ['Two sources of error', 'More data or a bigger class?', 'Validation as a bound', 'No free lunch', 'Demonstrate understanding'],
    skill: 'Decompose error into approximation and estimation parts and use theory to guide practical decisions.',
    prerequisite: 'Lessons 47.1–47.4.',
    paragraphs: [
      'Excess error splits into **approximation error** — how far the best hypothesis in H is from the best possible predictor — and **estimation error** — how far ERM’s choice is from the best in H, which the bounds control. Bigger classes shrink the first and grow the second.',
      'Theory gives direction: if training error is high, enlarge the class or improve features (approximation); if the gap between training and validation error is large, get more data, regularize or simplify (estimation). This is Lab 07’s diagnosis, now with its reason.',
      'Your validation set is a finite class problem: choosing among k configurations with m validation examples leaves an optimism of about √(ln k / m). A thousand configurations on 500 validation examples can make the winner look several points better than it is — use a final untouched test set (Lab 06).',
      'The **no-free-lunch theorem**: averaged over all possible problems, every learner performs the same. Learning works only because real problems have structure that our models’ assumptions (smoothness, linearity, locality, invariance) happen to match.',
      'You have completed this lab when you can: state the i.i.d. assumption and Hoeffding’s bound; derive the finite-class bound and the ERM guarantee; compute VC dimensions of simple classes; explain double descent and the role of norms; and turn the approximation–estimation split into practical decisions. The Python challenge computes bounds, checks shattering and reproduces double descent.',
    ],
    formula: 'R(ĥ) − R* = [R(h*) − R*] (approximation) + [R(ĥ) − R(h*)] (estimation ≤ 2ε)',
    derivation: {
      title: 'Optimism of choosing the best of many',
      steps: [
        { prompt: 'Approximate optimism √(ln k / m) for k = 1,000 configurations and m = 500 validation examples. (Three decimals.)', number: Math.sqrt(Math.log(1000) / 500), tolerance: 1e-3, show: '`√(6.908/500) ≈ 0.118`' },
        { prompt: 'Same with m = 5,000?', number: Math.sqrt(Math.log(1000) / 5000), tolerance: 1e-3, show: '`≈ 0.037`' },
      ],
      result: 'Heavy tuning needs a large validation set — or a separate test set to report honestly.',
    },
    experiment: 'In the bounds view, look at ERM’s average excess error as n grows. How does it compare with the bound 2ε?',
    question: 'A model has training error 2%, validation error 15%, and the best achievable error is about 12%. Is the main problem approximation or estimation?',
    choices: [
      { text: 'Approximation: the model class is too limited', why: 'Validation error is only 3 points above the best achievable; the class is not the main problem.' },
      { text: 'Estimation: the model fits its sample too closely', why: 'The 13-point train–validation gap dominates. More data or regularization, not a bigger model.' },
      { text: 'Neither — this is irreducible noise', why: 'Noise sets the 12% floor; the extra 3 points and the gap are not noise.' },
    ],
    answer: 1,
    explanation: 'The large train–validation gap (13 points) dominates; validation error is only 3 points above the best achievable. More data or regularization, not a bigger model.',
    reflection: 'Which of your current projects is limited by approximation error, and which by estimation error?',
  },
]

export const sources = [
  { title: 'Shalev-Shwartz & Ben-David · Understanding Machine Learning: From Theory to Algorithms (free book)', url: 'https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/' },
  { title: 'Belkin et al. (2019) · Reconciling modern machine-learning practice and the bias–variance trade-off', url: 'https://arxiv.org/abs/1812.11118' },
  { title: 'Zhang et al. (2017) · Understanding deep learning requires rethinking generalization', url: 'https://arxiv.org/abs/1611.03530' },
  { title: 'Stanford CS229 lecture notes · Learning theory', url: 'https://cs229.stanford.edu/main_notes.pdf' },
]
