// Lesson order for Lab 05: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l05-sample': [
    { p: 0 }, { p: 1 },
    { figure: 'OneStudy', caption: 'One study: n builds drawn from a skewed population whose true mean is known here (dashed).' },
    { cell: 0 },
    { p: 2 },
    { figure: 'SamplingDistribution', caption: 'The estimate from 1,000 repeated studies. Compare the sample mean with the sample median.' },
    { cell: 1 },
    { p: 3 },
    { predict: { prompt: 'A population has standard deviation 20. What is the standard error of the mean of a sample of 100?', answer: 2, explain: 'σ/√n = 20/10 = 2.' } },
    { p: 4 },
  ],
  'l05-clt': [
    { p: 0 }, { p: 1 },
    { figure: 'CltHistogram', caption: 'Means of n skewed durations. Slide n from 1 upward and compare with the normal curve.' },
    { cell: 0 },
    { p: 2 },
    { predict: { prompt: 'A sample of 36 builds has s = 12 s. What is the half-width of the approximate 95% interval, 1.96·s/√n?', answer: 3.92, tolerance: 0.005, explain: 's/√n = 12/6 = 2, and 1.96 × 2 = 3.92 s.' } },
    { cell: 1 },
    { p: 3 },
    { figure: 'IntervalWidth', caption: 'Interval half-width for n = 20, 80, 320 and 1,280.' },
    { predict: { prompt: 'You have 50 observations. How many do you need to halve the standard error?', answer: 200, explain: 'The standard error falls like 1/√n, so halving it needs 4× the data: 200.' } },
    { p: 4 },
  ],
  'l05-bootstrap': [
    { p: 0 }, { p: 1 },
    { figure: 'OneResample', caption: 'One bootstrap resample of 20 builds: how many times each observation was drawn.' },
    { predict: { prompt: 'n = 3. What is the probability that one specific observation is missing from a bootstrap resample of size 3? (Three decimals.)', answer: 0.296, tolerance: 0.001, explain: 'Each draw misses it with probability 2/3, so (2/3)³ ≈ 0.296. For large n this approaches 1/e ≈ 0.368.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'BootstrapInterval', caption: 'The bootstrap distribution of the statistic and its 95% percentile interval.' },
    { p: 3 }, { p: 4 },
    { cell: 1 },
  ],
  'l05-interval': [
    { p: 0 }, { p: 1 },
    { figure: 'CoverageStrips', caption: '100 independent studies, each with its own 95% interval. Red intervals miss the true mean.' },
    { predict: { prompt: 'You compute 200 independent 90% intervals with a well-calibrated method. About how many miss the true value?', answer: 20, explain: '10% of 200 = 20. Which ones miss is unknown; how many is predictable.' } },
    { cell: 0 },
    { p: 2 }, { p: 3 }, { p: 4 },
  ],
  'l05-likelihood': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'LikelihoodCurve', caption: 'The log-likelihood of p for k successes in n trials, relative to its peak.' },
    { predict: { prompt: '3 successes in 12 trials. What is the maximum-likelihood estimate of p?', answer: 0.25, tolerance: 0.001, explain: 'p̂ = k/n = 3/12 = 0.25.' } },
    { cell: 0 },
    { p: 3 },
    { figure: 'NormalNoiseLoss', caption: 'Under normal noise, the log-likelihood is minus the squared error divided by 2σ².' },
    { cell: 1 },
    { p: 4 },
  ],
  'l05-causation': [
    { p: 0 },
    { figure: 'PearsonByHand', caption: 'Pearson’s r from its deviations. Move the third y value.' },
    { predict: { prompt: 'x = `[1, 2, 3]` and y = `[3, 2, 1]`. What is Pearson’s r?', answer: -1, explain: 'y falls exactly linearly as x rises: r = −1.' } },
    { cell: 0 },
    { p: 1 },
    { figure: 'ConfounderScatter', caption: 'Project size (colour) drives both tests and bugs. Set a negative true effect and compare the pooled slope with the within-size slopes.' },
    { cell: 1 },
    { p: 2 }, { p: 3 }, { p: 4 },
  ],
}
