import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l05-sample',
    title: '05.1 · Samples, populations and estimators',
    sections: ['The number you want is hidden', 'Parameter, estimator, estimate', 'Every sample tells a different story', 'Bias and variance of an estimator', 'Put it into practice'],
    skill: 'Distinguish a population parameter from a sample estimate and describe an estimator by its bias and spread.',
    prerequisite: 'Lab 04 (expectation, variance, standard error of a mean).',
    paragraphs: [
      'You want the average duration of **all** builds your team will ever run. You have measured 20. The average of those 20 is 31.4 s. Is the real average 31.4 s? Almost certainly not exactly — a different 20 builds would give a different number. Statistics is the discipline of saying how far off you might be.',
      'The **population** is everything you want to describe (all builds, past and future). A **parameter** is a fixed number describing it, such as the population mean μ. A **sample** is the data you actually have. An **estimator** is a rule for turning a sample into a guess, like "average the sample"; the **estimate** is the number that rule produced on your particular sample.',
      'Because the sample is random, the estimate is a random variable too, with its own distribution — the **sampling distribution**. The playground draws it by repeating the study 1,000 times from a known synthetic population. Real studies cannot do that; they must infer this distribution from one sample.',
      'An estimator is **unbiased** if its sampling distribution is centered on the parameter: on average over many studies, it is right. Its **variance** says how much individual studies scatter. The sample mean is unbiased for μ, with standard error `σ/√n`. The sample median of skewed data is centered on the population *median*, not the mean — a different parameter, a common source of confusion.',
      'Procedure: state the parameter in words ("mean seconds per build on our CI machines this quarter"); state how the sample was collected and whether it represents that population; choose an estimator; report the estimate **with** a measure of its uncertainty. A single number without uncertainty invites overconfidence.',
    ],
    formula: 'parameter μ (fixed, unknown)   →   estimator x̄ = (1/n) Σ xᵢ (random)   →   estimate 31.4 (one number)',
    experiment: 'In "Sampling & bootstrap", change only the seed several times at n = 20. Watch your one sample and its mean jump. Then switch to median: is the sampling distribution centered on the true mean line?',
    question: 'A population has mean 30 and standard deviation 12. What is the standard error of the mean of a sample of 36?',
    answer: 2,
    misconceptions: [{ answer: 12, feedback: 'That is the population standard deviation. The standard error of the mean divides it by √n = 6.' }, { answer: 0.333, tolerance: 0.001, feedback: 'That divides by n = 36. The standard error divides by √n = 6.' }],
    explanation: 'σ/√n = 12/√36 = 12/6 = 2 seconds. Most sample means of size 36 land within about ±4 s of 30.',
    reflection: 'For a number you recently reported from data, what was the population, and how was your sample collected? Could it be unrepresentative?',
  },
  {
    id: 'l05-clt',
    title: '05.2 · Sampling distributions and the standard error',
    sections: ['Averages are better behaved than data', 'The central limit theorem', 'Estimating the standard error', 'Why n matters so much', 'When the shortcut fails'],
    skill: 'Explain why sample means are approximately normal and compute a standard error from data.',
    prerequisite: 'Lesson 05.1.',
    paragraphs: [
      'Individual build times are skewed: most take 25–35 s, a few take 80 s. Yet the playground\'s histogram of **sample means** is nearly symmetric and bell-shaped, even though every sample came from the skewed population. Averaging cancels much of the individual irregularity.',
      'The **central limit theorem** makes this precise: for independent observations with finite variance, the distribution of the sample mean approaches a normal distribution with mean μ and standard deviation σ/√n as n grows. How large n must be depends on the skew; for mildly skewed data 20–30 often suffices, for heavy tails far more.',
      'σ is unknown, so estimate it from the sample with the standard deviation using `n − 1` in the denominator (`np.std(x, ddof=1)`); dividing by n − 1 corrects the slight underestimate caused by measuring spread around the sample\'s own mean. The estimated standard error is `s/√n`. An approximate 95% interval for μ is `x̄ ± 1.96·s/√n`.',
      'Halving the standard error needs four times the data. Going from 20 to 80 builds narrows the interval by half; going from 80 to 320 halves it again. This is why "just collect more" gets expensive, and why deciding how precise you need to be should come before collecting.',
      'The normal shortcut assumes independent observations and a large enough n. It breaks with strongly skewed data at small n, with measurements that influence each other (builds on a shared, overloaded runner), and for statistics other than the mean. The bootstrap, next, handles many of these cases with the same idea — resampling — you used for simulation in Lab 04.',
    ],
    formula: 'x̄ ≈ Normal(μ, σ²/n)     SE ≈ s/√n with s = √(Σ(xᵢ − x̄)²/(n − 1))     95% ≈ x̄ ± 1.96·SE',
    experiment: 'Compare the sampling distribution at n = 5, 20 and 200. At n = 5, is it still skewed? By roughly what factor does its spread shrink from 20 to 200?',
    question: 'A sample of 25 builds has standard deviation s = 10 s. What is the estimated standard error of the mean?',
    answer: 2,
    misconceptions: [{ answer: 10, feedback: 'That is s, the spread of individual builds. The standard error of the mean is s/√n.' }, { answer: 0.4, feedback: 'That divides by n. The standard error divides by √n = 5.' }],
    explanation: 's/√n = 10/5 = 2 s. An approximate 95% interval is the sample mean ± 3.92 s.',
    reflection: 'How precise does one of your estimates need to be for its decision? Use σ/√n to estimate how many observations that requires.',
  },
  {
    id: 'l05-bootstrap',
    title: '05.3 · The bootstrap: resample what you have',
    sections: ['Pretend the sample is the population', 'Resample with replacement', 'Read off an interval', 'Any statistic', 'What the bootstrap assumes'],
    skill: 'Compute a bootstrap standard error and percentile interval for any statistic and state its assumptions.',
    prerequisite: 'Lessons 05.1–05.2; seeded simulation from Lab 04.',
    paragraphs: [
      'The sampling distribution needs many samples from the population. The **bootstrap** substitutes the one sample you have for the population: if the sample is representative, drawing from it mimics drawing from the world. Your 20 builds become a small model of all builds.',
      'Draw n values **with replacement** from your n observations — some appear twice, some not at all — and compute the statistic. Repeat B times (1,000 is typical). The spread of those B values estimates the standard error. In NumPy: `idx = rng.integers(0, n, size=(B, n)); boots = x[idx].mean(axis=1)`.',
      'The **percentile interval** takes the 2.5th and 97.5th percentiles of the bootstrap values as a 95% interval: `np.percentile(boots, [2.5, 97.5])`. It needs no normal assumption and follows skewness in the data: here the upper side is longer, like the data.',
      'The same procedure works for a median, a correlation, a model\'s validation error or the difference between two models\' errors — anything you can compute from a sample. For validation scores this matters: a model that beats another by 0.3 MSE may be no better once you see the interval (Lab 06).',
      'Assumptions: observations are independent and the sample represents the population. Resample the **unit that was sampled independently** — whole users, whole days, whole projects — not individual rows inside them. The bootstrap cannot invent information: with n = 5 it only knows 5 values, and it under-covers badly on small skewed samples, as the coverage experiment shows.',
    ],
    formula: 'for b = 1…B: x*⁽ᵇ⁾ = n draws from x with replacement; θ*⁽ᵇ⁾ = stat(x*⁽ᵇ⁾)     SE ≈ std(θ*)     CI = percentiles of θ*',
    experiment: 'Compare "True spread of estimate" with "Bootstrap estimate of it" at n = 5, 20 and 200, across three seeds. When is the bootstrap trustworthy?',
    question: 'A sample has n = 2 distinct values. What is the probability that one specific value is absent from a bootstrap resample of size 2?',
    answer: 0.25,
    misconceptions: [{ answer: 0.5, feedback: 'The chance that one specific value is missed on a single draw is 1/2; it must be missed on both independent draws: (1/2)².' }],
    explanation: 'Each draw misses it with probability 1/2; two independent draws: (1/2)² = 0.25. For large n, (1 − 1/n)ⁿ approaches e⁻¹ ≈ 0.368: about 37% of rows are left out of each resample.',
    reflection: 'In your data, what is the unit that was sampled independently? What would go wrong if you bootstrapped rows inside those units?',
  },
  {
    id: 'l05-interval',
    title: '05.4 · What an interval does — and does not — mean',
    sections: ['The truth is fixed', 'Coverage is a property of the procedure', 'Common misreadings', 'When nominal ≠ actual', 'Report uncertainty honestly'],
    skill: 'Interpret a confidence interval correctly and check a procedure\'s coverage by simulation.',
    prerequisite: 'Lessons 05.2–05.3.',
    paragraphs: [
      'The population mean is a fixed number. Your interval, say 28.1–35.6 s, was computed from a random sample, so the **interval** is what is random. Before you collected data, the procedure had a 95% chance of producing an interval containing μ. After, this particular interval either contains μ or it does not.',
      '"95% confidence" is a statement about **coverage**: if many independent studies each computed an interval the same way, about 95% of those intervals would contain the true value. The playground simulates exactly that: 100 studies, 100 intervals, each colored by whether it captured the truth.',
      'An interval is **not** a range containing 95% of the data (that is much wider), not the range of plausible *future* sample means, and not a guarantee about this one interval. A 95% interval that excludes zero improvement does not prove a large improvement; the effect could be just outside zero.',
      'Every method\'s real coverage depends on its assumptions. Small or skewed samples make the percentile bootstrap too narrow — observed coverage below nominal. Dependent observations can make any naive interval badly overconfident. Simulating coverage on synthetic data resembling yours is the direct check.',
      'Report an estimate as "31.4 s (95% bootstrap interval 28.1–35.6 s, n = 20 builds from May)". State the method and sample size so a reader can judge it. When comparing models, report the interval of the **difference**, not two overlapping intervals.',
    ],
    formula: 'P(procedure produces an interval containing μ) ≈ level     (a statement before the data are seen)',
    experiment: 'Run coverage at 95% for n = 5, 20 and 200. Record the observed coverage for each. Then set 80% and check that about 20 intervals miss.',
    question: 'You compute 100 independent 95% intervals with a well-calibrated procedure. About how many do you expect to miss the true value?',
    answer: 5,
    misconceptions: [{ answer: 95, feedback: 'That is how many intervals should contain the true value. The question asks how many miss it.' }],
    explanation: 'Coverage 95% means about 5% miss: 5 of 100. The number varies from run to run — roughly 1 to 9 is ordinary.',
    reflection: 'Rewrite a claim you have seen ("the new version is faster") as an estimate with an interval. What sample and method would you need?',
  },
  {
    id: 'l05-likelihood',
    title: '05.5 · Likelihood: which parameter explains the data?',
    sections: ['Flip the question', 'The likelihood function', 'Maximum likelihood', 'Why squared error', 'Log-likelihood and sharper evidence'],
    skill: 'Write a likelihood, find its maximum, and connect maximum likelihood to the losses used in ML.',
    prerequisite: 'Lessons 05.1–05.4; derivatives from Lab 01; probability from Lab 04.',
    paragraphs: [
      'Seven of ten deployments succeeded. Probability asks: if the success rate is p = 0.5, how likely is 7 of 10? **Likelihood** flips it: given that 7 of 10 happened, how well does each candidate p explain it? Plot that across all p and you see which values the data favor.',
      'For independent yes/no trials, the probability of a particular sequence with k successes is `pᵏ(1 − p)ⁿ⁻ᵏ`. As a function of p, with the data fixed, that is the **likelihood** L(p). Its logarithm is easier to handle: `log L(p) = k log p + (n − k) log(1 − p)`. Products become sums, and tiny numbers stay representable.',
      'The **maximum-likelihood estimate** is the p where the log-likelihood peaks. Set the derivative to zero: `k/p − (n − k)/(1 − p) = 0`, which gives `p̂ = k/n = 0.7`. The intuitive answer is also the maximum-likelihood one — and the same recipe works where intuition runs out.',
      'Assume regression targets are the model\'s prediction plus normal noise with fixed σ. The log-likelihood of the data is then a constant minus `Σ(yᵢ − ŷᵢ)²/(2σ²)`. Maximizing it is exactly **minimizing squared error**. MSE is not arbitrary: it is what maximum likelihood gives under normal noise. For yes/no targets, the same recipe gives cross-entropy — Lab 08\'s loss.',
      'With more data at the same ratio, the log-likelihood curve becomes narrower: 70 of 100 rules out p = 0.5 far more decisively than 7 of 10. Differences in log-likelihood measure how much more one parameter explains the data than another.',
    ],
    formula: 'log L(p) = k log p + (n − k) log(1 − p)     d/dp = 0 ⇒ p̂ = k/n     normal noise ⇒ maximize log L ⇔ minimize Σ(y − ŷ)²',
    experiment: 'Set 7 of 10 and read log L at 0.5 relative to the peak. Now set 70 of 100. How far below the peak is p = 0.5 now? Explain the difference.',
    question: 'In 10 independent trials there were 7 successes. What is the maximum-likelihood estimate of p?',
    answer: 0.7,
    misconceptions: [{ answer: 7, feedback: 'The estimate of a probability must lie between 0 and 1: k/n.' }],
    explanation: 'Setting the derivative of 7 log p + 3 log(1 − p) to zero gives 7/p = 3/(1 − p), so p = 0.7.',
    reflection: 'Explain in your own words why assuming normal noise leads to squared-error loss. What noise assumption would lead to absolute error instead?',
  },
  {
    id: 'l05-causation',
    title: '05.6 · Correlation is not causation',
    sections: ['Measure association', 'A hidden common cause', 'Stratify and compare', 'Prediction versus intervention', 'Demonstrate understanding'],
    skill: 'Compute correlation, recognize confounding, and separate predictive associations from causal claims.',
    prerequisite: 'Lessons 05.1–05.5; least-squares slopes from Lab 01.',
    paragraphs: [
      '**Pearson correlation** r measures linear association: `r = Σ(x − x̄)(y − ȳ) / √(Σ(x − x̄)² Σ(y − ȳ)²)`, between −1 and +1. For x = [1, 2, 3] and y = [1, 3, 2]: deviations are [−1, 0, 1] and [−1, 1, 0]; the cross-product sum is 1, each squared sum is 2, so r = 1/2 = 0.5. r = 0 means no *linear* association, not independence.',
      'In the playground, projects that write more tests also report more bugs: r is strongly positive. Yet tests have no effect on bugs in that simulation. **Project size** causes both. A variable that influences both the input and the outcome is a **confounder**, and it creates association without causation.',
      'Compare like with like: fit the relationship **within** each size group. The within-group slopes are near the true effect you set with the slider, while the pooled slope is badly biased. If the true effect is negative — tests prevent bugs — the pooled slope can still come out positive, reversing the conclusion (**Simpson\'s paradox**).',
      'A predictive model only needs associations that persist: if large projects will keep writing more tests, "many tests" legitimately predicts "many bugs". A decision that **changes** an input — "should we write fewer tests?" — needs the causal effect, which pure observation can mislead about. Randomized experiments break the confounding by assigning the input independently of everything else (optional specialization, Lab 36).',
      'You have completed this lab when you can: explain the difference between a parameter and an estimate; compute and bootstrap a standard error; interpret an interval by its coverage; derive a maximum-likelihood estimate; and identify a plausible confounder before trusting a correlation. The Python challenge checks the computational half.',
    ],
    formula: 'r = Σ(x−x̄)(y−ȳ) / √(Σ(x−x̄)² · Σ(y−ȳ)²)     confounder Z → X and Z → Y ⇒ X, Y correlated without X → Y',
    experiment: 'Set the true effect to 0, then −0.3. Compare the pooled slope with the within-group slopes each time. Write down which one a decision about writing tests should use.',
    question: 'For x = [1, 2, 3] and y = [1, 3, 2], what is Pearson\'s r?',
    answer: 0.5,
    explanation: 'Deviations [−1, 0, 1] and [−1, 1, 0]: cross products sum to 1; squared deviations sum to 2 and 2; r = 1/√4 = 0.5.',
    reflection: 'Name a correlation in your domain that people treat as causal. What confounder could explain it, and how could you test that?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 5.2: the bootstrap', url: 'https://www.statlearning.com/' },
  { title: 'Efron & Tibshirani · An Introduction to the Bootstrap', url: 'https://doi.org/10.1201/9780429246593' },
  { title: 'Seeing Theory · frequentist inference and confidence intervals', url: 'https://seeing-theory.brown.edu/frequentist-inference/index.html' },
  { title: 'NumPy · numpy.percentile', url: 'https://numpy.org/doc/stable/reference/generated/numpy.percentile.html' },
]

// Runnable cells and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
