import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l29-modes',
    title: '29.1 · Batch or online prediction?',
    sections: ['Where predictions are used', 'Batch prediction', 'Online prediction', 'Streaming and edge', 'Put it into practice'],
    skill: 'Choose between batch and online serving from the decision the prediction supports.',
    prerequisite: 'Labs 01–28; data contracts and lineage (Lab 28).',
    paragraphs: [
      'A model creates value only when its predictions reach a decision. Start from that decision: when is the prediction needed, how fresh must its inputs be, how many are needed, and what happens if it is late or missing?',
      '**Batch prediction** scores many records on a schedule — nightly risk scores, weekly capacity forecasts — and stores the results for later lookup. It is simple, cheap and easy to monitor, and latency hardly matters. Its limit: inputs are only as fresh as the last run.',
      '**Online prediction** scores a request when it arrives — an estimated build time shown the moment a job is queued. It uses the freshest inputs but must meet a latency budget under real traffic, stay available, and validate every request.',
      'Other options: **streaming** (score events as they flow through a message queue) and **edge** (run the model on the device, for privacy or offline use). Each changes the constraints on size, latency and update frequency.',
      'Prefer batch when it is good enough; move to online only when freshness justifies the operational cost. Many systems combine them: precompute what can be precomputed, and compute only the last-minute part online.',
    ],
    formula: 'choose by: needed freshness · volume · latency budget · cost of a late or missing prediction',
    experiment: 'For each playground view, name one real system that would face that problem. Which of your own predictions could be served in batch?',
    question: 'A batch job scores 2.4 million records in 40 minutes. How many records per second is that?',
    answer: 1000,
    explanation: '2,400,000 / (40 × 60) = 2,400,000 / 2,400 = 1,000 records per second, with no latency pressure on any single one.',
    reflection: 'For a model you would like to deploy, write the decision it supports, when it is needed, and whether batch serving would suffice.',
  },
  {
    id: 'l29-artifact',
    title: '29.2 · The model artifact and preprocessing parity',
    sections: ['What must be saved', 'Training–serving skew', 'One implementation, two paths', 'The parity test', 'Serialization formats'],
    skill: 'Package a model with its preprocessing and prove serving matches training.',
    prerequisite: 'Lesson 29.1; standardization (Labs 02–03), feature engineering (Lab 16).',
    paragraphs: [
      'A model is not just weights. The artifact must include every learned piece of preprocessing — standardization means and deviations, imputation values, vocabularies, category orders — plus the feature definitions, the version and the expected input schema.',
      '**Training–serving skew** happens when serving computes features differently from training: a rewritten transformation (log10 instead of ln), statistics recomputed from the live batch, categories in a different order. The playground\'s three buggy servers all load the correct weights and produce plausible, wrong predictions.',
      'The robust fix is structural: one feature implementation, imported by both the training pipeline and the server. When that is impossible (different languages), generate both from one specification and test them against each other.',
      'A **parity test** replays a set of real requests through the offline pipeline and the serving path and requires the outputs to match within a tight tolerance. Run it in continuous integration and before every release. It would have caught every bug in the playground.',
      'Serialize artifacts in explicit formats (JSON for small linear models, framework-native or ONNX for networks) together with a manifest: model version, data version, code version, feature list and the parity test results.',
    ],
    formula: 'artifact = { weights, preprocessing stats, feature spec, schema, versions }     parity: max|served − offline| ≤ ε',
    experiment: 'Select each buggy server. For each, write how large the error is and how a user might notice — or fail to notice — it.',
    question: 'A feature uses log10(x) instead of ln(x). By what factor is the feature too small? (ln 10, two decimals.)',
    answer: 2.3026, tolerance: 0.006,
    explanation: 'log10(x) = ln(x)/ln(10) ≈ ln(x)/2.303: every value is about 2.3 times too small.',
    reflection: 'List every learned preprocessing step in a model you know. Where is each one stored today?',
  },
  {
    id: 'l29-api',
    title: '29.3 · The prediction API contract',
    sections: ['Requests are untrusted', 'Validate, then predict', 'Useful responses', 'Versioning the API', 'Fallbacks'],
    skill: 'Design and validate an online prediction contract with clear errors and versioned responses.',
    prerequisite: 'Lessons 29.1–29.2; data contracts (Lab 28).',
    paragraphs: [
      'Every request is input from another system and must be validated against the contract before scoring: required fields, types, ranges, categories. A model given `"size_mb": "40"` or an unknown language should not guess.',
      'Return clear errors with an appropriate status: 400 for malformed JSON, 422 for a well-formed request that breaks the contract, with the list of violations. Callers can fix what they can see.',
      'A successful response names the model version and echoes the request id, so every prediction can be traced to the run that produced it (Lab 28) and to the log line that recorded it (Lab 30). Consider returning uncertainty (an interval) when the decision needs it.',
      'Version the API itself (`/v1/…`): adding an optional field is backwards-compatible; renaming or removing one is not. Changing the model behind a stable API is allowed, but must be deliberate and monitored (Lab 32).',
      'Decide the fallback when the model cannot answer — invalid input, timeout, outage: a documented default (e.g. the historical median), a simpler rule, or "no estimate". Never let the fallback be an unhandled exception.',
    ],
    formula: '400 malformed · 422 contract violation · 200 {model_version, prediction, request_id}',
    experiment: 'In "Request/response contract", break the request in three different ways and read each response. Then design the fallback you would return on a 422.',
    question: 'A request is missing 2 required fields and has 1 field of the wrong type. How many violations should the 422 response list?',
    answer: 3,
    explanation: 'Report every violation (2 + 1 = 3) at once, so the caller can fix them in one round trip.',
    reflection: 'Write the request and response JSON for a prediction service you might build, including errors and version fields.',
  },
  {
    id: 'l29-latency',
    title: '29.4 · Latency, throughput and batching',
    sections: ['Latency budgets', 'Queues dominate', 'Utilization', 'Micro-batching', 'Resource limits'],
    skill: 'Reason about latency percentiles, utilization and batching for an online model service.',
    prerequisite: 'Lessons 29.1–29.3; compute budgets (Lab 27).',
    paragraphs: [
      'State latency goals as percentiles: "p95 under 50 ms" means 95% of requests finish within 50 ms. Averages hide the slow tail that users notice.',
      'Total latency = waiting in the queue + processing. When requests arrive at random, waiting time grows sharply as **utilization** (the fraction of time the server is busy) approaches 100%. In the playground, a server that takes 10 ms per request can handle 100 requests per second — and at exactly that rate its latency explodes.',
      'Capacity = requests handled per second. With a per-call overhead o and a per-item cost c, one-at-a-time serving handles 1000/(o + c) requests per second; batches of B handle 1000·B/(o + c·B). With o = 8 ms, c = 2 ms: 100 per second alone, about 333 per second in batches of 8 (8,000/24).',
      '**Micro-batching** waits a few milliseconds to collect requests, trading a little latency at low traffic for much higher capacity at high traffic. Accelerators (GPUs) benefit most, because their per-call overhead is large and per-item cost small.',
      'Set resource limits deliberately: memory for the model and batch, CPU or GPU per replica, timeouts on every call, and a maximum queue length that rejects early rather than letting every request time out. Scale by adding replicas before utilization gets high.',
    ],
    formula: 'capacity(B) = 1000·B / (overhead + per_item·B) req/s     keep utilization well below 100%',
    experiment: 'At 100 requests/s, compare max batch 1 and 8. Then find the traffic level at which p95 exceeds 100 ms for each.',
    question: 'Per-call overhead 8 ms and per-item cost 2 ms. What is the capacity in requests per second with batches of 8?',
    answer: 333.3, tolerance: 0.5,
    explanation: '1000 × 8 / (8 + 2 × 8) = 8000 / 24 ≈ 333 requests per second — versus 100 one at a time.',
    reflection: 'What latency percentile and budget would matter for your users? What traffic peak should the service survive?',
  },
  {
    id: 'l29-test',
    title: '29.5 · Testing the full prediction path',
    sections: ['Test the path, not just the model', 'Contract tests', 'Parity and golden tests', 'Load tests', 'Demonstrate understanding'],
    skill: 'Build a test suite that covers the whole serving path.',
    prerequisite: 'Lessons 29.1–29.4.',
    paragraphs: [
      'Offline metrics test the model. Production needs tests of the whole path: request parsing, validation, feature computation, model call, response formatting, fallbacks and logging.',
      '**Contract tests** send valid and invalid requests and check status codes and error messages. Include edge cases: minimum and maximum values, every category, missing optional fields.',
      '**Parity tests** compare served and offline predictions on logged requests. **Golden tests** store a small set of requests with their expected predictions for a given model version; a change fails the build unless the model version changed deliberately.',
      '**Load tests** replay realistic traffic at and above the expected peak and check latency percentiles, error rates and memory. They find the capacity limits that the queueing view illustrates before users do.',
      'You have completed this lab when you can: choose batch or online serving; package a model with its preprocessing; prove parity; design an API contract with errors and versions; reason about latency and capacity; and test the entire path. The Python challenge builds a serializable predictor with parity and contract tests.',
    ],
    formula: 'serving tests = contract + parity + golden + load (+ fallback)',
    experiment: 'Write, in the notebook, five test cases for the playground API — two valid, three invalid — with the response each should produce.',
    question: 'A golden test set holds 25 requests for each of 4 languages-by-runner combinations. How many golden requests are there?',
    answer: 100,
    explanation: '25 × 4 = 100 requests, each with a stored expected prediction for the current model version.',
    reflection: 'Which of these test types is missing from a system you know? What failure would it have caught?',
  },
]

export const sources = [
  { title: 'Google · Rules of ML: training–serving skew', url: 'https://developers.google.com/machine-learning/guides/rules-of-ml#training-serving_skew' },
  { title: 'Sculley et al. (2015) · Hidden technical debt in machine learning systems', url: 'https://papers.nips.cc/paper/2015/hash/86df7dcfd896fcaf2674f757a2463eba-Abstract.html' },
  { title: 'Chip Huyen · Designing Machine Learning Systems, ch. 7 (deployment and prediction service)', url: 'https://huyenchip.com/books/' },
  { title: 'Dean & Barroso (2013) · The tail at scale', url: 'https://doi.org/10.1145/2408776.2408794' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
