// Lesson order for Lab 12: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l12-questions': [
    { p: 0 }, { cell: 0 }, { p: 1 }, { p: 2 }, { p: 3 },
    { figure: 'TreePath', caption: 'Leaves are rectangles. Move the point and read the questions on its path.' },
    { predict: { prompt: 'A binary tree of depth 4 can have at most how many leaves?', answer: 16, explain: '2⁴ = 16: each level can double the number of nodes.' } },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l12-impurity': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'ImpurityCurves', caption: 'Gini impurity and entropy as the class mix changes.' },
    { predict: { prompt: 'A node holds labels [0, 1, 1, 1]. What is its Gini impurity 2p(1 − p)? (Three decimals.)', answer: 0.375, tolerance: 0.001, explain: 'p = 0.75, so 2 × 0.75 × 0.25 = 0.375.' } },
    { cell: 0 },
    { p: 3 }, { p: 4 },
    { figure: 'SplitGain', caption: 'Choose how ten points (five of each class) are split, and see the gain.' },
    { cell: 1 },
    { math: true },
  ],
  'l12-greedy': [
    { p: 0 }, { p: 1 },
    { figure: 'ThresholdScan', caption: 'Every candidate threshold on one feature, scored by weighted Gini; the orange dot is the best.' },
    { predict: { prompt: 'A node’s points have 9 distinct values of one feature. How many candidate thresholds are there?', answer: 8, explain: 'One midpoint between each pair of consecutive distinct values: 9 − 1 = 8.' } },
    { cell: 0 },
    { p: 2 }, { p: 3 }, { cell: 1 }, { cell: 2 }, { p: 4 },
    { figure: 'XorGreedy', caption: 'XOR data: no first question helps on its own.' },
    { cell: 3 },
    { math: true },
  ],
  'l12-overfit': [
    { p: 0 }, { p: 1 },
    { figure: 'DepthCurve', caption: 'Training (blue) and validation (orange) accuracy against depth; the regions for the chosen depth.' },
    { cell: 0 },
    { p: 2 }, { p: 3 }, { cell: 1 }, { p: 4 },
    { figure: 'RootInstability', caption: 'The same data, nudged very slightly. Watch the root question.' },
    { cell: 2 },
    { math: true },
  ],
  'l12-regression': [
    { p: 0 }, { p: 1 }, { cell: 0 }, { p: 2 },
    { figure: 'RegressionSteps', caption: 'A regression tree on data between x = 0 and x = 6.' },
    { cell: 1 },
    { predict: { prompt: 'A regression leaf holds targets 3, 5, 5 and 11. What does it predict?', answer: 6, explain: 'The mean: (3 + 5 + 5 + 11)/4 = 6.' } },
    { p: 3 }, { p: 4 },
    { figure: 'ImportanceCompare', caption: 'Two informative features and a random ID, scored two ways.' },
    { cell: 2 },
    { math: true },
  ],
  'l12-practice': [
    { p: 0 }, { p: 1 },
    { figure: 'DiagonalStaircase', caption: 'A diagonal boundary, approximated with axis-aligned cuts.' },
    { cell: 0 },
    { p: 2 }, { p: 3 }, { cell: 1 }, { p: 4 },
    { math: true },
  ],
}
