export const lessons = [
  {
    id: 'l12-questions',
    title: '12.1 · A model made of questions',
    sections: ['Twenty questions', 'Nodes, branches and leaves', 'Axis-aligned regions', 'Prediction is a path', 'Put it into practice'],
    skill: 'Read a decision tree, follow a prediction path, and describe the regions it creates.',
    prerequisite: 'Labs 01–11; classification and validation (Labs 06–09).',
    paragraphs: [
      'An experienced engineer triages a failed build with a few questions: "Did the tests time out? If yes, is the runner shared? If no, did the dependency cache miss?" Each answer narrows the possibilities. A **decision tree** learns such a sequence of questions from data.',
      'Each **internal node** asks one yes/no question about one feature: "is x₁ ≤ 0.42?" Its two **branches** lead to further questions. A **leaf** stores a prediction: for classification, the fraction of training points of each class that reached it; for regression, their mean target.',
      'Because every question compares a single feature with a threshold, the tree cuts the feature space with lines parallel to the axes. The leaves form rectangles (boxes in more dimensions), each with a constant prediction. The playground shades those rectangles.',
      'To predict, start at the root, answer each question for the new point, and follow the branches to a leaf. The path is a complete, human-readable explanation: "x₁ = 0.20 ≤ 0.42 → left; x₂ = 0.10 > −0.35 → right; leaf: 91% class 1". Click the plot to see the path highlighted in the diagram.',
      'Trees need no feature scaling (a threshold works in any unit), handle mixed feature types, and capture interactions naturally ("large AND shared runner"). Their weaknesses — instability and overfitting — are what the rest of this lab and the next two address.',
    ],
    formula: 'predict(x): at each node, go left if x[feature] ≤ threshold, else right; return the leaf value',
    experiment: 'Set depth 2 on "Two moons". Click three different points and read each path. How many distinct predictions can a depth-2 tree make at most?',
    question: 'How many leaves can a binary decision tree of depth 3 have at most?',
    answer: 8,
    explanation: 'Each level can double the number of nodes: 2³ = 8 leaves at depth 3.',
    reflection: 'Write the decision tree an expert in your domain uses informally. Which features does it ask about first?',
  },
  {
    id: 'l12-impurity',
    title: '12.2 · Measuring impurity',
    sections: ['A good split separates the classes', 'Gini impurity', 'Entropy', 'Weighted impurity of a split', 'Information gain'],
    skill: 'Compute Gini impurity, entropy and the information gain of a candidate split.',
    prerequisite: 'Lesson 12.1; probability (Lab 04).',
    paragraphs: [
      'A split is useful if the two groups it creates are each more "one-class" than the group before. We need a number that is 0 for a pure group and largest for an even mix: an **impurity** measure.',
      '**Gini impurity** for two classes with class-1 share p is `2p(1 − p)` — the probability that two randomly drawn members of the node have different labels. A pure node (p = 0 or 1) scores 0; a 50/50 node scores 0.5. For labels [0, 0, 1, 1], p = 0.5 and Gini = 0.5.',
      '**Entropy** is `−p log₂ p − (1 − p) log₂(1 − p)`: the average number of bits needed to encode a label drawn from the node. Pure → 0 bits; 50/50 → 1 bit. Gini and entropy almost always choose the same splits; Gini is slightly cheaper to compute.',
      'A split sends nₗ points left and nᵣ right. Its quality is the **size-weighted** impurity of the children: `(nₗ·I(left) + nᵣ·I(right))/n`. Weighting stops a split that isolates one point into a tiny pure leaf from looking better than it is.',
      '**Information gain** is the parent\'s impurity minus that weighted child impurity. Parent [0, 0, 1, 1] has Gini 0.5; splitting it into [0, 0] and [1, 1] gives children with Gini 0, so the gain is 0.5 — the maximum possible here.',
    ],
    formula: 'Gini = 2p(1 − p)     H = −p log₂p − (1−p) log₂(1−p)     gain = I(parent) − (nₗIₗ + nᵣIᵣ)/n',
    experiment: 'In "How the root split was chosen", find the dashed parent impurity and the lowest point of the curve. Compute the gain from those two numbers and compare with the caption.',
    question: 'A node holds labels [0, 0, 1, 1]. What is its Gini impurity 2p(1 − p)?',
    answer: 0.5,
    explanation: 'p = 0.5, so 2 × 0.5 × 0.5 = 0.5 — the maximum for two classes.',
    reflection: 'Explain in your own words why the children\'s impurities must be weighted by their sizes.',
  },
  {
    id: 'l12-greedy',
    title: '12.3 · Growing a tree greedily',
    sections: ['Scan every threshold', 'Pick the best split', 'Recurse', 'Stopping rules', 'Greedy is not optimal'],
    skill: 'Implement the recursive greedy tree-growing algorithm and explain the limits of greediness.',
    prerequisite: 'Lessons 12.1–12.2; recursion in Python.',
    paragraphs: [
      'For one feature, sort the points by that feature. Only thresholds between consecutive distinct values can change which points go left, so try the midpoints: with n points there are at most n − 1 candidates. Keep running sums while sweeping, and each candidate\'s weighted impurity takes constant time.',
      'Repeat for every feature and choose the (feature, threshold) with the largest gain. That is one node. The playground\'s scan panel plots the weighted impurity for every threshold on the chosen feature; the orange dot is the best.',
      'Split the data by the chosen question and apply the same procedure to each side — **recursion**. Each call receives fewer points and returns a subtree; the root call returns the whole tree.',
      'Stop splitting a node when: it is pure; it reached the maximum depth; it has too few points to create two children of the minimum leaf size; or the best gain is below a threshold. Without stopping rules the tree grows until every leaf is pure — typically one training point per leaf.',
      'Choosing the best split now, without looking ahead, is **greedy**. On XOR data, no single first question separates the classes, so every root split has near-zero gain and the greedy choice is essentially random; only the second level reveals the structure. Finding the truly optimal tree is computationally intractable in general, so greedy growth is the practical compromise.',
    ],
    formula: 'grow(node): if stop: leaf; else (j, t) = argmax gain; grow(left: x_j ≤ t); grow(right: x_j > t)',
    experiment: 'Select "XOR quadrants". Scan x1 and x2 at the root: how large is the best gain? Then compare validation accuracy at depth 1, 2 and 4.',
    question: 'A feature has 6 distinct sorted values among the node\'s points. How many candidate thresholds are there?',
    answer: 5,
    explanation: 'One midpoint between each consecutive pair of distinct values: 6 − 1 = 5.',
    reflection: 'Describe a problem in your domain where the first question that looks best might not lead to the best overall sequence of questions.',
  },
  {
    id: 'l12-overfit',
    title: '12.4 · Overfitting and pruning',
    sections: ['Pure leaves memorize', 'The depth curve', 'Pre-pruning', 'Post-pruning', 'Instability'],
    skill: 'Diagnose an overfit tree and control complexity with depth, leaf size and pruning.',
    prerequisite: 'Lessons 12.1–12.3; bias and variance (Lab 07).',
    paragraphs: [
      'Grow a tree without limits and it keeps splitting until each leaf holds one training point (or identical ones): training accuracy 100%. Near the class boundary, leaves shrink to single noisy points, carving small islands of the wrong class into the regions. Validation accuracy drops.',
      'The accuracy-versus-depth plot shows the familiar pattern from Lab 07: training accuracy rises steadily with depth; validation accuracy rises, peaks and declines. Depth is the complexity knob, and the best depth depends on how much data and noise you have.',
      '**Pre-pruning** stops growth early: a maximum depth, a minimum number of samples per leaf (a leaf with 20 points averages away noise), or a minimum gain. They are cheap and effective; choose them by cross-validation.',
      '**Post-pruning** grows a large tree and then removes branches that do not help. **Cost-complexity pruning** minimizes `error + α·(number of leaves)`: each α gives a nested sequence of smaller trees, and cross-validation picks α. It can keep a split whose immediate gain was small if deeper splits below it pay off — something pre-pruning would miss.',
      'Trees are **unstable**: move a few training points and the root split can change, changing the whole tree below it. Change the seed in the playground and compare the diagrams. This high variance is exactly what averaging many trees (Lab 13) removes.',
    ],
    formula: 'cost-complexity: minimize Σ_leaves error + α · |leaves|',
    experiment: 'At depth 14 with minimum leaf 1, compare training and validation accuracy. Now keep depth 14 and raise the minimum leaf size to 10. What happened to the islands in the plot?',
    question: 'A training set has 128 points with distinct feature values. At most how many leaves can an unpruned tree need to make every leaf pure?',
    answer: 128,
    explanation: 'In the worst case every point needs its own leaf: 128 leaves, i.e. perfect memorization.',
    reflection: 'Which stopping rule would you choose for a tree in your domain, and how would you tune it without touching the test set?',
  },
  {
    id: 'l12-regression',
    title: '12.5 · Regression trees and feature importance',
    sections: ['Predict a number', 'Variance as impurity', 'Step functions', 'Feature importance', 'Handle it with care'],
    skill: 'Build regression trees with squared-error impurity and interpret impurity-based feature importance critically.',
    prerequisite: 'Lessons 12.1–12.4; MSE (Lab 01).',
    paragraphs: [
      'For a numeric target such as build duration, a leaf predicts the mean of its training targets. The natural impurity is the **variance** — the mean squared error around that mean. A split is good if it creates two groups whose targets are each tightly clustered.',
      'Minimizing size-weighted variance is exactly minimizing the training MSE of a piecewise-constant prediction. The same scan-and-recurse algorithm applies; only the impurity function changes. Lab 14 builds boosting on exactly these regression trees.',
      'A regression tree predicts a **step function**: constant within each region, jumping at thresholds. It cannot extrapolate — beyond the largest training value it predicts the last leaf\'s mean forever. For trends that continue beyond the data, linear models behave better.',
      'Summing each feature\'s impurity reductions across all nodes that split on it, weighted by the number of points reaching those nodes, gives an impurity-based **feature importance**. It is cheap and often informative.',
      'But it is biased toward features with many possible thresholds (continuous or high-cardinality features), is computed on training data (so it rewards overfit splits), and splits credit arbitrarily between correlated features. Prefer **permutation importance** on validation data: shuffle one feature and measure how much the validation score drops.',
    ],
    formula: 'impurity(node) = mean((y − ȳ_node)²)     leaf prediction = ȳ_leaf',
    experiment: 'Set minimum leaf size to 1 and increase depth step by step. Watch how many rectangles appear in regions with only a few points. Relate that to variance.',
    question: 'A regression leaf contains training targets 4, 6 and 11. What does it predict?',
    answer: 7,
    explanation: 'The mean: (4 + 6 + 11)/3 = 7. Its impurity is the variance around 7: (9 + 1 + 16)/3 ≈ 8.67.',
    reflection: 'If a tree said one of your features was the most important, what check would you run before believing it?',
  },
  {
    id: 'l12-practice',
    title: '12.6 · Trees in practice',
    sections: ['Strengths', 'Weaknesses', 'Categorical and missing values', 'When to use one tree', 'Demonstrate understanding'],
    skill: 'Decide when a single tree is appropriate and explain its behaviour to a stakeholder.',
    prerequisite: 'Lessons 12.1–12.5.',
    paragraphs: [
      'Strengths: interpretable paths; no scaling; handles non-linear effects and interactions; fast to train and predict; works with numeric and categorical data. A depth-3 tree printed on one page can be reviewed by someone who has never seen a model before.',
      'Weaknesses: high variance (unstable structure), axis-aligned boundaries (a diagonal boundary needs a staircase of many splits), no extrapolation, and greedy growth that can miss good multi-step structure. On most tabular problems a single tree is beaten by ensembles of trees.',
      'Categorical features can be split by grouping categories; many libraries require them to be encoded numerically first. Missing values can be sent down a learned default branch, imputed (Lab 02), or given an indicator. Whatever you choose, apply it identically at prediction time.',
      'Use a single tree when explanation matters more than the last few points of accuracy, as a quick baseline, or as a tool to discover interactions worth engineering into features for another model. Constrain its depth so that the explanation stays readable.',
      'You have completed this lab when you can: compute Gini, entropy and gain by hand; implement greedy tree growth; trace a prediction path; diagnose and control overfitting; and explain the weaknesses that motivate forests and boosting. The Python challenge builds a tree from scratch.',
    ],
    formula: 'single tree: low bias (if deep), high variance → averaging many trees (Lab 13)',
    experiment: 'On "Two blobs", compare the tree\'s staircase boundary at depth 6 with the straight boundary logistic regression found in Lab 08. Which is simpler? Which generalizes better?',
    question: 'A depth-2 tree splits the root on x₁ ≤ 3, then the left child on x₂ ≤ 1. A point has x₁ = 2, x₂ = 5. How many questions are asked before it reaches a leaf?',
    answer: 2,
    explanation: 'Root: 2 ≤ 3 → left. Left child: 5 > 1 → right, which is a leaf. Two questions.',
    reflection: 'Would a stakeholder in your domain accept a slightly less accurate model if its every prediction came with a readable path? When would they not?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 8.1: decision trees', url: 'https://www.statlearning.com/' },
  { title: 'scikit-learn · Decision trees (and cost-complexity pruning)', url: 'https://scikit-learn.org/stable/modules/tree.html' },
  { title: 'scikit-learn · Permutation feature importance', url: 'https://scikit-learn.org/stable/modules/permutation_importance.html' },
  { title: 'Breiman, Friedman, Olshen & Stone · Classification and Regression Trees (1984)', url: 'https://doi.org/10.1201/9781315139470' },
]
