const R = { x: [-3, 3], m1: [-2, 2], m2: [-2, 2], p: [0.1, 0.9] }

export const lessons = [
  {
    id: 'l43-mixtures',
    title: '43.1 · Latent variables and mixtures',
    sections: ['Data from several sources', 'The generative story', 'A log of a sum', 'Responsibilities', 'Put it into practice'],
    skill: 'Write a Gaussian mixture as a latent-variable model and compute posterior responsibilities.',
    prerequisite: 'Labs 40–41 (Gaussians, Bayes’ rule, maximum likelihood); clustering (Lab 17).',
    paragraphs: [
      'Build times on a CI server come from several kinds of jobs; sensor readings come from several operating modes. Nobody labels which source produced each point. A **mixture model** says the data came from K sources and learns them without labels.',
      'The generative story: pick a component z with probability πₖ, then draw x from that component’s Gaussian N(μₖ, Σₖ). The unobserved z is a **latent variable**. Summing over it gives the density p(x) = Σₖ πₖ N(x | μₖ, Σₖ) — flexible enough to approximate almost any shape with enough components.',
      'Maximum likelihood wants to maximize Σᵢ log Σₖ πₖ N(xᵢ | μₖ, Σₖ). The **log of a sum** does not split into separate pieces, so there is no closed form like GDA (Lab 40). But if we knew each zᵢ, it would be exactly GDA — a count and an average per class.',
      'Given parameters, Bayes’ rule tells us how likely each component is to have produced a point: the **responsibility** rᵢₖ = πₖ N(xᵢ | μₖ, Σₖ) / Σⱼ πⱼ N(xᵢ | μⱼ, Σⱼ). It is a soft label: a point halfway between two clusters gets about 0.5 from each.',
      'Procedure: choose K and the covariance type (full, diagonal, shared); fit the mixture (next lesson); inspect responsibilities, not just hard labels; and check the fit with held-out likelihood or BIC (Lesson 43.5).',
    ],
    formula: 'p(x) = Σₖ πₖ N(x | μₖ, Σₖ)     rᵢₖ = πₖ N(xᵢ | μₖ, Σₖ) / Σⱼ πⱼ N(xᵢ | μⱼ, Σⱼ)',
    derivation: {
      title: 'Responsibilities for two one-dimensional components',
      intro: 'Unit variances, means m1 and m2, and weight p on component 1. N(x | m, 1) ∝ exp(−(x − m)²/2).',
      steps: [
        { prompt: 'Write the responsibility of component 1 for a point x.', answer: 'p*exp(-(x-m1)^2/2)/(p*exp(-(x-m1)^2/2) + (1-p)*exp(-(x-m2)^2/2))', show: '`p·e^(−(x−m1)²/2) / (p·e^(−(x−m1)²/2) + (1−p)·e^(−(x−m2)²/2))`', vars: R },
        { prompt: 'Rewrite it as a sigmoid: r = σ(log-odds). Write the log-odds.', answer: 'log(p/(1-p)) - (x-m1)^2/2 + (x-m2)^2/2', show: '`log(p/(1−p)) − (x − m1)²/2 + (x − m2)²/2`', vars: R, hint: 'Divide numerator and denominator by the numerator, as in Lab 40.' },
        { prompt: 'With m1 = 0, m2 = 2 and p = 0.5, evaluate the responsibility of component 1 for x = 1.', number: 0.5, show: '`0.5`', why: 'Halfway between equally weighted components: a perfectly soft assignment.' },
        { prompt: 'Same model, x = 0. (Four decimals.)', number: 1 / (1 + Math.exp(-2)), tolerance: 1e-4, show: '`σ(2) ≈ 0.8808`' },
      ],
      result: 'A responsibility is the GDA posterior from Lab 40 — with parameters that we are still learning.',
    },
    experiment: 'In “EM step by step”, choose the three-cluster data, K = 3, and iteration 0. Which points have faint colours? Step through the iterations and watch them become confident.',
    question: 'Two components with weights 0.3 and 0.7. At a point x, N(x | μ₁, Σ₁) = 0.2 and N(x | μ₂, Σ₂) = 0.05. What is the responsibility of component 1? (Three decimals.)',
    answer: 0.632, tolerance: 0.001,
    explanation: '0.3 × 0.2 = 0.06 and 0.7 × 0.05 = 0.035; 0.06 / 0.095 ≈ 0.632.',
    reflection: 'Name data in your work that plausibly comes from several unlabeled sources. What would each component mean?',
  },
  {
    id: 'l43-em',
    title: '43.2 · The EM algorithm',
    sections: ['Guess the labels softly', 'Fit as if they were known', 'The update formulas', 'Repeat until stable', 'Initialization'],
    skill: 'Carry out E- and M-steps for a Gaussian mixture by hand and in code.',
    prerequisite: 'Lesson 43.1; GDA maximum likelihood (Lab 40).',
    paragraphs: [
      'EM breaks the circular problem — parameters need labels, labels need parameters — by alternating. **E-step**: with the current parameters, compute every responsibility rᵢₖ.',
      '**M-step**: fit each component as in GDA, but with each point counted fractionally by its responsibility. Nₖ = Σᵢ rᵢₖ is the effective number of points in component k.',
      'The updates: πₖ = Nₖ / n; μₖ = Σᵢ rᵢₖ xᵢ / Nₖ (a weighted mean); Σₖ = Σᵢ rᵢₖ (xᵢ − μₖ)(xᵢ − μₖ)ᵀ / Nₖ (a weighted covariance, using the new mean).',
      'Repeat until the log-likelihood stops changing (say by less than 10⁻⁶ relative). Each iteration costs O(nKd²) — cheap — though convergence can be slow when components overlap.',
      'EM needs a starting point. Common choices: K random data points as means, or the result of k-means (scikit-learn’s default). Different starts can end in different solutions, so run several and keep the one with the highest likelihood.',
    ],
    formula: 'Nₖ = Σᵢ rᵢₖ     πₖ = Nₖ/n     μₖ = Σᵢ rᵢₖxᵢ / Nₖ     Σₖ = Σᵢ rᵢₖ(xᵢ − μₖ)(xᵢ − μₖ)ᵀ / Nₖ',
    derivation: {
      title: 'Derive the M-step for a component mean',
      intro: 'One dimension, unit variance. The expected complete-data log-likelihood for component k contains −½ Σᵢ rᵢₖ (xᵢ − μ)². Three points a, b, c with responsibilities ra, rb, rc.',
      steps: [
        { prompt: 'Differentiate −½[ra(a − μ)² + rb(b − μ)² + rc(c − μ)²] with respect to μ.', answer: 'ra*(a-μ) + rb*(b-μ) + rc*(c-μ)', show: '`ra(a − μ) + rb(b − μ) + rc(c − μ)`', vars: { a: [-3, 3], b: [-3, 3], c: [-3, 3], ra: [0, 1], rb: [0, 1], rc: [0, 1], μ: [-2, 2] } },
        { prompt: 'Set it to zero and solve for μ.', answer: '(ra*a + rb*b + rc*c)/(ra + rb + rc)', show: '`(ra·a + rb·b + rc·c)/(ra + rb + rc)` — a weighted mean', vars: { a: [-3, 3], b: [-3, 3], c: [-3, 3], ra: [0.1, 1], rb: [0.1, 1], rc: [0.1, 1] } },
        { prompt: 'Points 0, 2 and 10 with responsibilities 1, 1 and 0.2. What is the new mean? (Four decimals.)', number: (0 + 2 + 2) / 2.2, tolerance: 1e-4, show: '`4/2.2 ≈ 1.8182`', why: 'The far point barely counts because this component barely claims it.' },
      ],
      result: 'Every M-step formula is the GDA formula with each point weighted by its responsibility.',
    },
    experiment: 'In “EM step by step”, drag the iteration slider slowly from 0 to 10 on the three-cluster data. What changes most between iterations 0 and 1?',
    question: 'A component has responsibilities 0.5, 1 and 0.5 for points 2, 4 and 8. What is its updated mean?',
    answer: 4.5,
    explanation: '(0.5 × 2 + 1 × 4 + 0.5 × 8) / (0.5 + 1 + 0.5) = 9 / 2 = 4.5.',
    reflection: 'Why would initializing EM from k-means usually speed it up?',
  },
  {
    id: 'l43-why',
    title: '43.3 · Why EM works: the lower bound',
    sections: ['Jensen’s inequality', 'The evidence lower bound', 'E-step closes the gap', 'M-step raises the bound', 'Local optima'],
    skill: 'Prove that EM never decreases the likelihood using the evidence lower bound.',
    prerequisite: 'Lessons 43.1–43.2; KL divergence (Lab 46 revisits it); expectations (Lab 04).',
    paragraphs: [
      'The logarithm is concave, so the log of an average is at least the average of the logs: log E[Y] ≥ E[log Y] (**Jensen’s inequality**). Equality holds only when Y is constant.',
      'For any distribution q(z) over the latent label, write log p(x) = log Σ_z q(z) · p(x, z)/q(z) ≥ Σ_z q(z) log [p(x, z)/q(z)]. The right-hand side is the **evidence lower bound** (ELBO). Exactly: log p(x) = ELBO(q, θ) + KL(q ‖ p(z | x, θ)), and the KL divergence is never negative.',
      'The **E-step** sets q(z) = p(z | x, θ) — the responsibilities. The KL term becomes 0 and the bound touches log p(x).',
      'The **M-step** maximizes the ELBO over θ with q fixed; since the bound touched the log-likelihood before and the log-likelihood is always above the bound, the log-likelihood cannot go down. Hence the monotone curves in the playground.',
      'Monotone does not mean global: EM climbs to a **local** maximum or saddle. On the parallel clusters, most starting points settle on the wrong split with log-likelihood about −1044, while one start finds −893. Restarts, sensible initialization and model checks are part of the algorithm. The same ELBO drives variational inference (Lab 44) and VAEs (Lab 53).',
    ],
    formula: 'log p(x | θ) = ELBO(q, θ) + KL(q(z) ‖ p(z | x, θ)) ≥ ELBO(q, θ)',
    derivation: {
      title: 'Jensen’s inequality and the size of the gap',
      steps: [
        { prompt: 'Two equally likely values 1 and 4. Compute log of their average. (Four decimals.)', number: Math.log(2.5), tolerance: 1e-4, show: '`log 2.5 ≈ 0.9163`' },
        { prompt: 'Now the average of their logs. (Four decimals.)', number: Math.log(4) / 2, tolerance: 1e-4, show: '`(0 + log 4)/2 ≈ 0.6931`', why: 'Smaller, as Jensen promises; the gap is what the E-step closes.' },
        { prompt: 'Write the KL divergence between q = (q, 1 − q) and p = (p, 1 − p) for a binary latent variable.', answer: 'q*log(q/p) + (1-q)*log((1-q)/(1-p))', show: '`q log(q/p) + (1 − q) log((1 − q)/(1 − p))`', vars: { q: [0.05, 0.95], p: [0.05, 0.95] } },
        { prompt: 'Evaluate it for q = p = 0.3.', number: 0, show: '`0`', why: 'When q equals the true posterior, the bound is tight — exactly what the E-step does.' },
      ],
      result: 'The E-step makes the bound touch the log-likelihood; the M-step pushes the bound up; the log-likelihood follows.',
    },
    experiment: 'Choose the parallel clusters with K = 2 and compare the five starting points in the log-likelihood plot. Which starts end on the higher peak, and what do their clusters look like?',
    question: 'At the current parameters, log p(x) = −100 and the KL term between q and the true posterior is 3. What is the ELBO?',
    answer: -103,
    explanation: 'ELBO = log p(x) − KL = −100 − 3 = −103. After the E-step, KL = 0 and the ELBO equals −100.',
    reflection: 'Explain in two sentences to a classmate why EM cannot make the fit worse, but can still get stuck.',
  },
  {
    id: 'l43-kmeans',
    title: '43.4 · k-means, soft assignments and failure modes',
    sections: ['k-means is hard EM', 'When soft clustering wins', 'Collapse', 'Label switching', 'Covariance choices'],
    skill: 'Relate k-means to EM and diagnose the failure modes of mixture fitting.',
    prerequisite: 'Lessons 43.1–43.3; k-means (Lab 17).',
    paragraphs: [
      'Fix every covariance to σ²I and equal weights, then let σ → 0. Responsibilities become 0 or 1 — each point goes wholly to the nearest mean — and the M-step becomes the average of the assigned points. That is **k-means**: EM with hard assignments and round, equal clusters.',
      'Those hidden assumptions show. On two long parallel clusters, k-means cuts across them (about 53% agreement with the truth, even from its best start); a full-covariance mixture recovers them (over 99% from its best start). With a big diffuse cluster beside a small tight one, k-means steals points for the small cluster (77% versus 98%).',
      'Maximum likelihood for mixtures has a flaw: a component can sit on a single point and shrink its variance toward zero, pushing the likelihood to infinity. This **collapse** is a degenerate optimum, not a good model. Fixes: a variance floor (scikit-learn’s reg_covar), a prior on covariances (MAP-EM), or discarding tiny components. Strictly, a floor means the M-step no longer maximizes the likelihood exactly, so the log-likelihood can dip by a tiny amount; EM is then climbing a slightly regularized objective.',
      'The components have no fixed names: swapping labels 1 and 2 gives the same likelihood (**label switching**). Compare solutions by matching components, as the playground does when scoring agreement.',
      'Covariance options trade flexibility for parameters: full (most flexible), diagonal (axis-aligned), tied (shared, like LDA) or spherical (like k-means). With little data or many dimensions, simpler covariances generalize better.',
    ],
    formula: 'σ → 0:  rᵢₖ → 1[k = argminⱼ ‖xᵢ − μⱼ‖]  ⇒  EM → k-means',
    experiment: 'In “Mixture versus k-means”, compare all three datasets. Then in “EM step by step”, turn off the variance floor, choose K = 6 on the three-cluster data and look for a component that shrinks onto a point.',
    question: 'A component with mean exactly at one data point and variance σ² in one dimension. Its density at that point is 1/√(2πσ²). What is that density when σ = 0.001? (Nearest whole number.)',
    answer: 399, tolerance: 1,
    explanation: '1/(√(2π) × 0.001) ≈ 398.9 — and it grows without limit as σ → 0. That is the collapse.',
    reflection: 'You ran EM and got a component with weight 0.3% and a tiny covariance. What would you do?',
  },
  {
    id: 'l43-choose',
    title: '43.5 · Choosing K and using mixtures well',
    sections: ['Likelihood always rises with K', 'BIC', 'Held-out likelihood', 'Beyond clustering', 'Demonstrate understanding'],
    skill: 'Choose the number of components and apply mixtures for density estimation and clustering.',
    prerequisite: 'Lessons 43.1–43.4; model evidence (Lab 41).',
    paragraphs: [
      'More components can only fit the training data better, so the maximum log-likelihood keeps rising with K. It cannot choose K on its own.',
      'The **Bayesian information criterion** BIC = −2 log L + p log n penalizes each of the p parameters; lower is better. It approximates −2 × the log evidence for large n. A full-covariance mixture in d dimensions has p = (K − 1) + Kd + Kd(d + 1)/2 parameters. In the playground, BIC finds the true K in all three datasets.',
      'With enough data, the most direct check is **held-out log-likelihood**: fit on training data and score the validation set; choose the K that predicts unseen data best. AIC penalizes less than BIC and tends to pick larger K.',
      'Mixtures do more than clustering: they are flexible **density estimators** (anomaly scores are low densities, Lab 17), class-conditional models for generative classifiers (Lab 40), and building blocks of HMMs (Lab 45). EM itself applies to any model with missing or latent data.',
      'You have completed this lab when you can: write a mixture as a latent-variable model; compute responsibilities; derive and run the E- and M-steps; prove monotonicity with the ELBO; relate k-means to EM; recognize local optima, collapse and label switching; and choose K with BIC or held-out likelihood. The Python challenge implements EM and checks it against scikit-learn.',
    ],
    formula: 'BIC = −2 log L + p log n,   p = (K − 1) + Kd + Kd(d + 1)/2',
    derivation: {
      title: 'Count parameters and compute BIC',
      steps: [
        { prompt: 'Full-covariance mixture, K = 3, d = 2. How many parameters?', number: 17, show: '`2 + 6 + 9 = 17`' },
        { prompt: 'Write p as a function of K for d = 2.', answer: '6*K - 1', show: '`6K − 1`', vars: { K: [1, 8] } },
        { prompt: 'With log-likelihood −900 and n = 300 points, what is BIC for K = 3? (One decimal.)', number: 1800 + 17 * Math.log(300), tolerance: 0.1, show: '`1800 + 17 log 300 ≈ 1897.0`' },
      ],
      result: 'Each extra component in 2D must improve the log-likelihood by about 3 log n ≈ 17 to be worth it.',
    },
    experiment: 'In “How many components?”, compare the log-likelihood and BIC for each dataset. How much does the log-likelihood gain from K = 3 to K = 4 on the three-cluster data, compared with the BIC penalty?',
    question: 'A full-covariance mixture in d = 3 dimensions with K = 2 components. How many parameters does it have?',
    answer: 19,
    explanation: '(2 − 1) + 2 × 3 + 2 × 6 = 1 + 6 + 12 = 19.',
    reflection: 'Would you choose K by BIC, held-out likelihood or usefulness to a decision in your work? Why?',
  },
]

export const sources = [
  { title: 'Dempster, Laird & Rubin (1977) · Maximum likelihood from incomplete data via the EM algorithm', url: 'https://doi.org/10.1111/j.2517-6161.1977.tb01600.x' },
  { title: 'Bishop · Pattern Recognition and Machine Learning, ch. 9 (free PDF)', url: 'https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/' },
  { title: 'Stanford CS229 lecture notes · The EM algorithm', url: 'https://cs229.stanford.edu/main_notes.pdf' },
  { title: 'scikit-learn · Gaussian mixture models', url: 'https://scikit-learn.org/stable/modules/mixture.html' },
]
