// Lesson order for Lab 04: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l04-frequency': [
    { p: 0 },
    { figure: 'DicePairs', caption: 'All 36 equally likely outcomes of two dice. Pick a sum and count its pairs.' },
    { predict: { prompt: 'How many of the 36 pairs of two dice sum to 10?', answer: 3, explain: '(4,6), (5,5) and (6,4): P = 3/36 = 1/12.' } },
    { p: 1 },
    { figure: 'DiceSimulation', caption: 'Simulated shares (bars) against the exact probabilities (dots). Raise the number of rolls; change the seed.' },
    { cell: 0 },
    { p: 2 },
    { figure: 'StandardErrorLadder', caption: 'How the typical simulation error falls as the number of trials grows.' },
    { predict: { prompt: 'A simulation estimates p = 0.5 from 10,000 trials. What is its standard error √(p(1−p)/n)?', answer: 0.005, tolerance: 0.0001, explain: '√(0.25/10,000) = 0.5/100 = 0.005.' } },
    { cell: 1 },
    { p: 3 }, { cell: 2 },
    { p: 4 },
  ],
  'l04-distributions': [
    { p: 0 }, { p: 1 },
    { figure: 'PmfBars', caption: 'The probability mass function: one bar per possible value.' },
    { cell: 0 },
    { p: 2 },
    { figure: 'NormalArea', caption: 'For a continuous variable, probability is area under the density.' },
    { predict: { prompt: 'For a normal distribution, roughly what fraction of values lie **more** than 2σ from the mean? (Give a decimal.)', answer: 0.05, tolerance: 0.006, explain: 'About 95% lie within 2σ, so about 5% (0.046 exactly) lie outside.' } },
    { cell: 1 },
    { p: 3 },
    { figure: 'DieCdf', caption: 'The CDF of one die: a staircase that rises by 1/6 at each face.' },
    { cell: 2 },
    { p: 4 },
  ],
  'l04-expectation': [
    { p: 0 },
    { figure: 'LoadedDie', caption: 'Each bar is one face’s contribution x·P(X = x); their total is the expectation. Load the die toward 6.' },
    { figure: 'RunningMean', caption: 'The running average of two-dice sums settles toward the expectation, 7.' },
    { cell: 0 },
    { p: 1 },
    { predict: { prompt: 'X is one die. What is E[2X + 1]?', answer: 8, explain: 'Linearity: 2 × 3.5 + 1 = 8. No table of outcomes needed.' } },
    { p: 2 },
    { figure: 'SquaredDistances', caption: 'Variance, face by face.' },
    { p: 3 },
    { cell: 1 },
    { p: 4 },
    { figure: 'AverageSpread', caption: 'Simulated averages of n dice. The spread shrinks like σ/√n; the centre does not move.' },
    { cell: 2 },
  ],
  'l04-conditional': [
    { p: 0 },
    { figure: 'ConditionGrid', caption: '1,000 machines. Conditioning means keeping only one group, then counting inside it.' },
    { cell: 0 },
    { p: 1 }, { p: 2 },
    { predict: { prompt: 'Using the same 1,000 machines, what is P(alarm | healthy)? (49 of the 980 healthy machines alarmed.)', answer: 0.05, tolerance: 0.001, explain: '49/980 = 0.05: the false-alarm rate. It divides by healthy machines, not by alarms.' } },
    { cell: 1 },
    { p: 3 },
    { figure: 'IndependenceCheck', caption: 'Does knowing one thing change the probability of the other?' },
    { cell: 2 },
    { p: 4 },
  ],
  'l04-bayes': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { p: 2 },
    { figure: 'BayesPopulation', caption: 'Expected counts among 1,000 machines. The posterior is true alarms divided by all alarms.' },
    { predict: { prompt: 'Prior 10%, sensitivity 0.9, false-alarm rate 0.05. What is P(fault | alarm)? (Three decimals.)', answer: 0.667, tolerance: 0.001, explain: '0.09 / (0.09 + 0.045) = 0.667. A ten-times higher prior turns 15% into 67%.' } },
    { p: 3 },
    { cell: 1 }, { cell: 2 },
    { p: 4 },
    { figure: 'InspectDecision', caption: 'Compare the expected loss of ignoring an alarm with the cost of checking it.' },
    { ladder: 'bayes' },
  ],
  'l04-verify': [
    { p: 0 }, { p: 1 },
    { figure: 'SimVersusExact', caption: 'A simulated P(fault | alarm) against the exact formula. The error bar depends on the number of alarms, not machines.' },
    { cell: 0 },
    { p: 2 },
    { figure: 'PlantedBug', caption: 'Plausible mistakes, measured in standard errors from the exact answer.' },
    { cell: 1 },
    { p: 3 },
    { predict: { prompt: 'A simulated proportion is 0.2 from 400 relevant trials. What is its standard error?', answer: 0.02, tolerance: 0.0001, explain: '√(0.2 × 0.8 / 400) = √0.0004 = 0.02.' } },
    { cell: 2 },
    { p: 4 },
  ],
}
