export const lessons = [
  {
    id: 'l04-frequency',
    title: '04.1 · Probability as long-run frequency',
    sections: ['Count what happens', 'Estimate by simulation', 'How close is close?', 'Seeds make simulation checkable', 'Put it into practice'],
    skill: 'Estimate a probability by simulation and explain why the estimate improves with more trials.',
    prerequisite: 'Labs 01–03. Fractions, loops and a seeded random generator (Lab 02).',
    paragraphs: [
      'Roll two dice 36,000 times and count how often the sum is 7. You will see roughly 6,000. Of the 36 equally likely (first, second) pairs, six give 7 — (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) — so the **probability** is 6/36 = 1/6. A probability is the fraction of times an event happens in a long run of identical, independent repetitions.',
      'When counting outcomes by hand is hard, let the computer repeat the experiment: generate random outcomes, count the event, divide by the number of trials. This is **Monte Carlo simulation**. `rng = np.random.default_rng(1); a = rng.integers(1, 7, size=100_000); b = rng.integers(1, 7, size=100_000); np.mean(a + b == 7)` gives about 0.1667. The comparison `a + b == 7` builds a boolean array; its mean is the fraction of True values.',
      'An estimate from n trials has a typical error of about `√(p(1−p)/n)`, the **standard error**. With p = 1/6: 100 trials give an error near 0.037; 10,000 trials, near 0.0037. Error shrinks like 1/√n, so **each extra decimal place costs 100 times more trials**. Simulations are cheap, but not free, and a precise-looking number from a small simulation is not precise.',
      'Seeding the generator makes a simulation exactly repeatable: a reviewer running your code sees your numbers. Changing the seed shows how much the answer moves by chance alone — a free, honest error bar. Run a few seeds before believing a difference in the third decimal.',
      'Procedure: write one trial as a function; run it many times with a seeded generator; compute the fraction (or average) of interest; report it with its standard error; and, whenever an exact answer is available, compare. The playground\'s dice experiment does all of this.',
    ],
    formula: 'P(A) ≈ (number of trials where A happened) / n     standard error ≈ √(p(1 − p)/n)',
    experiment: 'Choose the dice experiment. Set 10 rolls, then 100, 1,000 and 100,000. Record the sample mean each time and try two seeds at 10 rolls. How big is the seed-to-seed difference at each size?',
    question: 'What is the exact probability that two fair dice sum to 7? Give a decimal to three places.',
    answer: 0.1667, tolerance: 0.0006,
    explanation: 'Six of the 36 equally likely pairs sum to 7, so 6/36 = 1/6 ≈ 0.167.',
    reflection: 'Describe one quantity in your work that you could estimate by simulating many repetitions. What would one trial be?',
  },
  {
    id: 'l04-distributions',
    title: '04.2 · Random variables and distributions',
    sections: ['A number produced by chance', 'Discrete distributions', 'Continuous measurements', 'The cumulative view', 'Why models need distributions'],
    skill: 'Describe discrete and continuous random variables with probability mass, density and cumulative functions.',
    prerequisite: 'Lesson 04.1.',
    paragraphs: [
      'A **random variable** is a number whose value is determined by a chance process: the sum of two dice, the time a build takes, the reading of a noisy sensor. Its **distribution** says which values are possible and how likely each is. Everything in machine learning that talks about uncertainty — noise, errors, predicted probabilities — is a statement about distributions.',
      'A **discrete** random variable takes separate values, and its **probability mass function** gives each value\'s probability: for the dice sum, `P(S = 7) = 6/36` and `P(S = 2) = 1/36`. The probabilities of all possible values add to 1. The playground histogram is a simulated estimate of this function; the dots are the exact values.',
      'A **continuous** variable, like a sensor voltage, can take any value in a range, so the probability of one exact value is 0. A **probability density** describes it instead: probability is the **area** under the density between two values. The normal (Gaussian) density, a symmetric bell centered at its mean μ with spread σ, describes many measurement errors; about 68% of its area lies within one σ of μ and about 95% within two.',
      'The **cumulative distribution function**, `F(x) = P(X ≤ x)`, works for both kinds. For one fair die, `F(2) = P(X ≤ 2) = 2/6`. `P(a < X ≤ b) = F(b) − F(a)`. Sorting a sample and plotting the fraction at or below each value gives the empirical version, a robust way to compare two samples by eye.',
      'A regression model predicts a value, but the data scatter around it; that scatter is a distribution. Later labs assume specific distributions — Bernoulli for yes/no outcomes in logistic regression, normal noise for least squares — and the choice of loss follows directly from that assumption.',
    ],
    formula: 'Σₓ P(X = x) = 1     P(a < X ≤ b) = F(b) − F(a) = ∫ₐᵇ f(x) dx',
    experiment: 'At 100 rolls, find a sum whose simulated frequency is far from its exact dot. Predict whether it will still be far at 100,000 rolls, then check.',
    question: 'For one fair six-sided die, what is P(X ≤ 2)? Give a decimal to three places.',
    answer: 0.3333, tolerance: 0.0006,
    explanation: 'Outcomes 1 and 2 are 2 of 6 equally likely outcomes: 2/6 ≈ 0.333. This is F(2), the cumulative distribution at 2.',
    reflection: 'Pick one measured quantity in your project. Is it discrete or continuous? Sketch what you expect its distribution to look like and why.',
  },
  {
    id: 'l04-expectation',
    title: '04.3 · Expectation and variance',
    sections: ['A weighted average of outcomes', 'Linearity', 'Spread: variance and standard deviation', 'Independent sums', 'The average of many'],
    skill: 'Compute expectation and variance from a distribution and use their rules for sums and averages.',
    prerequisite: 'Lesson 04.2.',
    paragraphs: [
      'The **expectation** (expected value, mean) of a random variable weights each value by its probability: `E[X] = Σ x·P(X = x)`. One die: (1 + 2 + 3 + 4 + 5 + 6)/6 = 3.5. No single roll equals 3.5; it is the long-run average — the value the running mean in the playground settles toward.',
      'Expectation is **linear**: `E[aX + b] = a·E[X] + b` and `E[X + Y] = E[X] + E[Y]`, always, whether or not X and Y are related. Two dice: 3.5 + 3.5 = 7, with no need to list 36 pairs. Mean squared error is itself an expectation — the average squared error over the data distribution.',
      '**Variance** measures spread: `Var[X] = E[(X − E[X])²]`, the expected squared distance from the mean. One die: the squared distances from 3.5 are 6.25, 2.25, 0.25, 0.25, 2.25, 6.25, averaging 17.5/6 ≈ 2.917. The **standard deviation** `σ = √Var` is back in the original units: about 1.71 for a die.',
      'If X and Y are **independent** (knowing one says nothing about the other), variances add: `Var[X + Y] = Var[X] + Var[Y]`. Two dice: 2 × 2.917 = 5.833, the value shown in the playground. For dependent variables an extra covariance term appears — the same kind of relationship that made correlated features unstable in Lab 03.',
      'Average n independent copies of X. The mean of the average is still E[X], but its variance is `Var[X]/n`, so its standard deviation is `σ/√n` — the **standard error**. This single fact explains why simulations, validation scores and A/B tests all get more precise with more data, and exactly how slowly.',
    ],
    formula: 'E[X] = Σ x p(x)     Var[X] = E[(X − μ)²]     Var[mean of n] = σ²/n',
    experiment: 'At 10,000 rolls, compare the sample variance with 35/6. Then predict the typical distance between the running mean and 7 after 100 rolls, using σ/√n with σ² = 35/6. Check against three seeds.',
    question: 'What is the variance of one fair six-sided die? Give three decimal places.',
    answer: 2.9167, tolerance: 0.0006,
    explanation: 'Squared deviations from 3.5 are 6.25, 2.25, 0.25, 0.25, 2.25 and 6.25; their average is 17.5/6 = 35/12 ≈ 2.917.',
    reflection: 'Explain in your own words why averaging more observations reduces uncertainty, and why it does so like 1/√n rather than 1/n.',
  },
  {
    id: 'l04-conditional',
    title: '04.4 · Conditional probability and independence',
    sections: ['Restrict the population', 'The definition', 'Order matters', 'Independence', 'Where this appears in ML'],
    skill: 'Compute conditional probabilities from counts and test independence.',
    prerequisite: 'Lessons 04.1–04.3.',
    paragraphs: [
      'Of 1,000 machines, 20 are faulty; 18 of the faulty and 49 of the healthy ones raised an alarm. Among the **alarms only**, 18 of 67 were real faults. Conditioning means restricting attention to the cases where something is known to have happened, then counting within that group.',
      'In symbols, the probability of A **given** B is `P(A | B) = P(A and B) / P(B)`: the share of B-cases in which A also happened. With the numbers above, `P(fault | alarm) = (18/1000) / (67/1000) = 18/67 ≈ 0.269`.',
      'Conditioning is not symmetric. `P(alarm | fault) = 18/20 = 0.9` — the detector catches 90% of faults — while `P(fault | alarm) ≈ 0.27`. They share a numerator but divide by different groups: faulty machines in one case, alarming machines in the other. Reading one as the other is one of the most common and costly reasoning errors in medicine, security and monitoring.',
      'A and B are **independent** if knowing B does not change the probability of A: `P(A | B) = P(A)`, equivalently `P(A and B) = P(A)·P(B)`. Two separate dice are independent. Alarms and faults are not — that dependence is exactly what makes the alarm useful. Independence is an assumption you must justify; many models (Naive Bayes, Lab 11) assume it knowingly.',
      'A classifier\'s predicted probability is a conditional probability: P(class | features). Evaluation metrics are conditional too: recall is P(predicted positive | actually positive), precision is P(actually positive | predicted positive). Lab 09 builds on exactly this distinction.',
    ],
    formula: 'P(A | B) = P(A ∩ B) / P(B)     independent ⇔ P(A ∩ B) = P(A) P(B)',
    experiment: 'In the alarm experiment, raise the base rate from 0.1% to 30% while keeping sensitivity and false alarms fixed. Which conditional probability changes, and which does not? Why?',
    question: 'Of 200 builds, 50 used a cache; 10 of those failed. What is P(failed | used cache)?',
    answer: 0.2,
    explanation: 'Restrict to the 50 cached builds: 10 / 50 = 0.2. The overall failure rate is irrelevant to this conditional probability.',
    reflection: 'Find a pair of conditional probabilities in your field that people often swap. Write both in words and say which one a decision actually needs.',
  },
  {
    id: 'l04-bayes',
    title: '04.5 · Bayes’ rule: updating on evidence',
    sections: ['Reverse a conditional', 'Derive the rule', 'Prior, likelihood, posterior', 'Rare events', 'Decisions need costs too'],
    skill: 'Derive Bayes’ rule, compute a posterior from a prior and test characteristics, and explain the base-rate effect.',
    prerequisite: 'Lesson 04.4.',
    paragraphs: [
      'A vendor tells you their detector has 90% sensitivity and a 5% false-alarm rate. What you actually need at 3 a.m. is the reverse: given this alarm, how likely is a real fault? **Bayes’ rule** converts one conditional into the other.',
      'Write the joint probability two ways: `P(F and A) = P(A | F)·P(F) = P(F | A)·P(A)`. Divide by P(A): `P(F | A) = P(A | F)·P(F) / P(A)`. The denominator counts all alarms, real and false: `P(A) = P(A | F)P(F) + P(A | not F)P(not F)`.',
      'The **prior** P(F) is the fault rate before seeing the alarm. The **likelihood** P(A | F) says how expected the evidence is if the hypothesis is true. The **posterior** P(F | A) is the updated belief after the evidence. With a 1% prior, 90% sensitivity and 5% false alarms: 0.009 / (0.009 + 0.0495) ≈ 0.154. Ninety percent sensitivity, and still most alarms are false.',
      'When the prior is tiny, even a small false-alarm rate applied to the huge healthy population outnumbers the true alarms. Improving the posterior requires either a lower false-alarm rate or a higher prior — for example, only alerting on machines already flagged by a second signal. The playground\'s population grid makes the counts visible.',
      'A posterior is not a decision. If a missed fault costs $10,000 and an inspection $200, inspecting at 15% posterior is worth it: expected loss from ignoring, 0.154 × 10,000 ≈ $1,540, exceeds the inspection cost. Lab 09 formalizes choosing thresholds from costs.',
    ],
    formula: 'P(F | A) = P(A | F) P(F) / [P(A | F) P(F) + P(A | ¬F) P(¬F)]',
    experiment: 'Set base rate 1%, sensitivity 90%, false alarms 5%. Predict the posterior before reading it. Then find the false-alarm rate needed to make P(fault | alarm) exceed 50%.',
    question: 'Prior 1%, sensitivity 0.9, false-alarm rate 0.05. What is P(fault | alarm)? Three decimal places.',
    answer: 0.1538, tolerance: 0.0006,
    explanation: 'Numerator 0.9 × 0.01 = 0.009. Denominator 0.009 + 0.05 × 0.99 = 0.0585. 0.009 / 0.0585 ≈ 0.154.',
    reflection: 'For an alert or test you rely on, estimate its prior, sensitivity and false-alarm rate. Roughly what fraction of its alarms are real?',
  },
  {
    id: 'l04-verify',
    title: '04.6 · Check every formula by simulation',
    sections: ['Two independent routes', 'Error bars on a simulation', 'When they disagree', 'Simulate your assumptions', 'Demonstrate understanding'],
    skill: 'Verify a probability calculation by simulation with an appropriate error bar, and diagnose disagreements.',
    prerequisite: 'Lessons 04.1–04.5.',
    paragraphs: [
      'A formula can be derived wrong; a simulation can be coded wrong. They rarely fail in the same way. Computing a result by both routes and comparing them is one of the most reliable checks available, the same idea as comparing an analytic gradient with finite differences in Lab 01.',
      'A simulated fraction p̂ from n relevant cases has standard error `√(p̂(1 − p̂)/n)`. Note which n: when estimating P(fault | alarm), only the alarms count, not all machines simulated. With 1% faults you may need 100,000 machines to get a thousand alarms. If exact and simulated values differ by more than about three standard errors, suspect a bug.',
      'Typical causes of disagreement: conditioning on the wrong group (dividing by faults instead of alarms), reusing one random draw for two things that should be independent, an off-by-one in `integers(1, 7)` (the upper bound is excluded), or a formula that silently assumed independence. Fix the cause; never tune one side until it matches.',
      'Simulation also tests assumptions you cannot solve exactly. What if sensitivity drops for small faults, or alarms cluster in time? Write the more realistic process, simulate it, and see whether the simple formula still gives a usable answer. This is how engineers check models against messier reality.',
      'You have completed this lab when you can: compute expectations and conditional probabilities from a table; apply Bayes’ rule and explain the base-rate effect; and confirm each result by a seeded simulation with an honest error bar. The Python challenge asks for exactly that.',
    ],
    formula: '|p̂ − p_exact| ≲ 2–3 × √(p̂(1 − p̂)/n_relevant)',
    experiment: 'Run the alarm simulation with 100 machines at a 1% base rate, then 100,000. At the small size, how many alarms were there, and how wide is the error bar? Is the disagreement with the exact value surprising?',
    question: 'A simulated proportion is 0.5 from 100 relevant trials. What is its standard error?',
    answer: 0.05,
    explanation: '√(0.5 × 0.5 / 100) = √0.0025 = 0.05. A difference of 0.03 from the exact value would be unremarkable; 0.2 would signal a bug.',
    reflection: 'Which calculation in your work could you check with a quick simulation? Write the one-trial function in plain words.',
  },
]

export const sources = [
  { title: 'Seeing Theory · a visual introduction to probability', url: 'https://seeing-theory.brown.edu/' },
  { title: 'Introduction to Probability (Blitzstein & Hwang) · free online book', url: 'https://projects.iq.harvard.edu/stat110/home' },
  { title: 'NumPy · Random Generator', url: 'https://numpy.org/doc/stable/reference/random/generator.html' },
  { title: 'Gigerenzer & Hoffrage (1995) · natural frequencies improve Bayesian reasoning', url: 'https://doi.org/10.1037/0033-295X.102.4.684' },
]
