import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l32-triggers',
    title: '32.1 · When to retrain',
    sections: ['Models age', 'Scheduled retraining', 'Triggered retraining', 'What retraining cannot fix', 'Put it into practice'],
    skill: 'Choose retraining triggers and recognize problems that retraining will not solve.',
    prerequisite: 'Labs 01–31; monitoring and drift (Lab 30), versioning (Lab 28).',
    paragraphs: [
      'The world keeps changing after deployment: new build caches, new languages, new traffic patterns. A model trained on last year\'s data slowly becomes last year\'s model. Retraining on recent data is routine maintenance, not an emergency.',
      '**Scheduled** retraining (weekly, monthly) is simple and predictable. Choose the cadence from how fast performance decays: measure how much worse a model gets per week of age on held-out recent data.',
      '**Triggered** retraining starts when monitoring shows confirmed performance loss (Lab 30), when enough new labeled data accumulates, or when the product changes. Input drift alone is a reason to evaluate a retrained candidate, not to deploy one blindly.',
      'Retraining cannot fix a pipeline bug (it would learn the bug), a broken label, or a change the features cannot express. In the playground, retraining on recent data improves overall error but leaves some slices worse: the new cache interacts with size in a way the old features cannot represent. That needs a feature change and a design review.',
      'Every retraining run goes through the same pipeline as the first model: data contract, versioned data, recorded configuration, evaluation, and the release gates of the next lesson. Automate it so that routine retraining is boring.',
    ],
    formula: 'retrain when: schedule elapsed · confirmed error increase · enough new labels · product change',
    experiment: 'Compare the production and retrained models\' MAE on the recent holdout. Then read the slice results. Is retraining alone enough?',
    question: 'Production MAE on recent data is 14.31 s and a retrained candidate scores 9.62 s. By what percentage did error fall? (Nearest whole percent.)',
    answer: 33, tolerance: 0.5,
    explanation: '1 − 9.62/14.31 ≈ 0.328, about 33% lower error overall — yet two slices got worse, which the overall number hides.',
    reflection: 'How quickly does a model in your domain go stale? How would you measure it?',
  },
  {
    id: 'l32-gates',
    title: '32.2 · Promotion gates',
    sections: ['Automate the release decision', 'Better, where it matters', 'No silent contract change', 'Parity, latency, sanity', 'Gates encode decisions'],
    skill: 'Define promotion gates that a candidate model must pass before release.',
    prerequisite: 'Lesson 32.1; parity and latency (Lab 29), subgroups (Lab 31).',
    paragraphs: [
      'A candidate model reaches users only after passing **promotion gates**: automated checks that compare it with the production model on the same recent holdout. Gates turn "looks good to me" into reproducible, reviewable criteria.',
      '**Improvement**: better than production by a meaningful margin on recent data. **Slices**: no important slice worse by more than a tolerance — an overall gain can hide a regression for some users (Lab 31). In the playground the honest retrain fails exactly this gate.',
      '**Prediction contract**: same output meaning and unit. Replaying a golden set through both models and checking the median ratio of predictions catches a model that suddenly outputs minutes. Changing the contract is a breaking change that needs a new major version and coordination with every consumer.',
      '**Parity**: serving computes the same predictions as the offline pipeline (Lab 29). **Latency**: p95 within budget on production hardware. **Sanity**: results better than the process noise allows usually mean leakage (Lab 06) — the leaky candidate in the playground scores 2.5 s against a noise floor of about 5 s.',
      'Thresholds are product decisions: how much improvement justifies a release, which slices matter, what latency users tolerate. Write them down, review them, and change them deliberately — never quietly to let a favourite candidate through.',
    ],
    formula: 'promote ⇔ improvement ∧ no slice regression ∧ same contract ∧ parity ∧ latency ∧ sanity',
    experiment: 'Try each candidate with the default gates. Then raise the latency budget to 35 ms. Which candidate now passes, and who should approve that change?',
    question: 'A candidate\'s median prediction is 0.0167 times production\'s on the golden set. By what factor are its outputs smaller? (Nearest whole number.)',
    answer: 60, tolerance: 0.5,
    explanation: '1/0.0167 ≈ 60: exactly the seconds-to-minutes factor. The candidate outputs minutes — a contract change, whatever its accuracy.',
    reflection: 'Write the gates you would require before updating a model you know. Which one would be hardest to agree on?',
  },
  {
    id: 'l32-staged',
    title: '32.3 · Staged rollout and automatic rollback',
    sections: ['Offline is not online', 'Shadow deployment', 'Canary releases', 'Rollback rules', 'Keep the old model warm'],
    skill: 'Roll out a model gradually with canary traffic and an automatic rollback rule.',
    prerequisite: 'Lessons 32.1–32.2; alerts and persistence (Lab 30).',
    paragraphs: [
      'Offline evaluation cannot capture everything: real traffic, integration bugs, user behaviour. Expose a new model gradually so that problems affect few users and are caught quickly.',
      '**Shadow deployment** runs the candidate on live traffic without using its predictions: compare its outputs and latency with production at zero risk. It cannot measure effects that depend on acting on the predictions.',
      'A **canary** release sends a small share of real traffic (1%, then 5%, 25%, 50%, 100%) to the candidate and compares it with the rest (control). Exposure grows only while the canary stays healthy.',
      'An automatic **rollback rule** returns all traffic to production when the canary is worse than control by more than a tolerance for N consecutive periods. Small canaries measure noisily: the playground\'s honest retrain is about 25% better than control on most days, yet on day 3, with only 15 canary jobs at 5% traffic, it looks 9% worse. A single-day rule with a 5% tolerance would roll back a good model; persistence prevents such needless rollbacks, and the tolerance is set from normal day-to-day variation.',
      'Rollback must be instant and boring: keep the previous model loaded or deployable, with its exact preprocessing and version (Lab 28). A rollback path that has never been exercised is a hope, not a plan.',
    ],
    formula: 'rollback if canary_MAE > control_MAE × (1 + tol) for N consecutive days',
    experiment: 'Force a canary for the log10 and minutes candidates. On which day does each roll back, and what share of traffic was exposed?',
    question: 'A canary schedule exposes 1%, 5%, 5%, 25% of traffic on days 1–4. The rollback fires at the end of day 3. What is the largest share of traffic that ever used the bad model?',
    answer: 5,
    explanation: 'Days 1–3 used 1%, 5% and 5%: at most 5% of traffic ever saw it. Day 4\'s 25% never happens.',
    reflection: 'How would you run a canary for a batch-prediction model? What is the equivalent of "traffic share"?',
  },
  {
    id: 'l32-ci',
    title: '32.4 · Continuous integration and release artifacts',
    sections: ['CI for ML', 'What a release contains', 'Semantic versioning for models', 'Approvals', 'Auditability'],
    skill: 'Assemble a release artifact and version model updates by their impact on consumers.',
    prerequisite: 'Lessons 32.1–32.3; tests (Lab 30), model cards (Lab 31).',
    paragraphs: [
      'Continuous integration for ML runs, on every change: unit tests, data-contract tests, training on a small fixture dataset, model tests, parity tests and the promotion gates. A red build blocks the release exactly like a failing unit test.',
      'A **release artifact** bundles the model file, its preprocessing, the input and output schema, the data and code versions, the evaluation report with gate results, the model card (Lab 31), and the rollback target. Everything a reviewer or an on-call engineer needs is in one place.',
      '**Semantic versioning** communicates impact: a new **major** version changes the contract (output unit, required fields); a **minor** version changes the model within the same contract (retraining, new features); a **patch** fixes packaging without changing predictions. The minutes model is a major change even if its accuracy were perfect.',
      'Require human approval where the stakes demand it: a gate threshold relaxed, a contract change, a subgroup regression accepted. Record who approved what and why.',
      'Together these make every production prediction traceable: request → model version → release artifact → training run → data version and code (Labs 28–29). That traceability is what audits, incident reviews and future you depend on.',
    ],
    formula: 'MAJOR: contract change · MINOR: same contract, different model · PATCH: same predictions',
    experiment: 'For each candidate, read the suggested version. Do you agree with each bump? What would you write in the release note?',
    question: 'The current model is 1.4.0. A retrained model keeps the same contract. What version should it get? (Answer with the minor number.)',
    answer: 5,
    explanation: '1.5.0: a new model under the same contract is a minor bump. A contract change would make it 2.0.0.',
    reflection: 'What would a release artifact for your model contain? Which item is missing today?',
  },
  {
    id: 'l32-loops',
    title: '32.5 · Feedback loops and safe iteration',
    sections: ['Models change their own data', 'Degenerate loops', 'Breaking the loop', 'A delivery checklist', 'Demonstrate understanding'],
    skill: 'Recognize feedback loops created by deployed models and design safeguards.',
    prerequisite: 'Lessons 32.1–32.4; causal reasoning (Lab 05).',
    paragraphs: [
      'Once a model acts, it shapes the data used to retrain it. If predicted-long builds are routed to dedicated runners, future data contains fewer long builds on shared runners — the model\'s own decisions change what it later learns.',
      'Loops can degrade silently: a recommender shows only what it already ranks highly, so it never learns about anything else; a fraud model blocks transactions, so the blocked cases never receive labels; an alerting model is retrained on the incidents it caught and forgets the kind it missed.',
      'Break loops deliberately: keep a small randomized holdout that the model does not influence (an A/B control), log what the model saw and decided, collect labels for a sample of rejected or unacted cases, and reason about which data the decision policy excluded (Lab 36 develops the causal view).',
      'A delivery checklist for every model update: trigger and data window recorded; contract-validated, versioned data; gates passed (or exceptions approved); model card updated; canary plan with rollback rule; monitoring dashboards and alerts updated; feedback-loop risk reviewed.',
      'You have completed this lab when you can: choose retraining triggers; define and justify promotion gates; roll out with canaries and automatic rollback; version and package releases; and identify and mitigate feedback loops. The Python challenge implements the gates, the canary rule and version bumping.',
    ],
    formula: 'holdout control group + decision logging + labels for unacted cases ⇒ data the model did not shape',
    experiment: 'Imagine the routing model has run for a year. Describe in the notebook how the training data would differ from the original data, and one safeguard you would add.',
    question: 'A 5% randomized holdout is kept from 20,000 daily decisions. How many decisions per day are made without the model\'s influence?',
    answer: 1000,
    explanation: '5% of 20,000 = 1,000 decisions per day — an unbiased stream for evaluation and retraining.',
    reflection: 'Where could a model in your work influence its own future training data? How would you detect it?',
  },
]

export const sources = [
  { title: 'Google Cloud · MLOps: continuous delivery and automation pipelines in machine learning', url: 'https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning' },
  { title: 'Breck et al. (2017) · The ML test score', url: 'https://research.google/pubs/pub46555/' },
  { title: 'Semantic Versioning 2.0.0', url: 'https://semver.org/' },
  { title: 'Sculley et al. (2015) · Hidden technical debt in machine learning systems (feedback loops)', url: 'https://papers.nips.cc/paper/2015/hash/86df7dcfd896fcaf2674f757a2463eba-Abstract.html' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
