export const lessons = [
  {
    id: 'l44-mc',
    title: '44.1 · Why approximate, and Monte Carlo',
    sections: ['The intractable normalizer', 'Expectations are what we need', 'Monte Carlo estimates', 'Error shrinks like 1/√S', 'Put it into practice'],
    skill: 'Explain why most posteriors need approximation and estimate expectations by Monte Carlo with a known error.',
    prerequisite: 'Labs 41–43 (posteriors, evidence, ELBO); expectation and variance (Lab 04).',
    paragraphs: [
      'Conjugate models (Lab 41) and Gaussian processes (Lab 42) have exact posteriors. Most models do not. Bayesian logistic regression, hierarchical models and neural networks all give posteriors p(θ | D) = p(D | θ)p(θ)/p(D) where the normalizer p(D) = ∫ p(D | θ)p(θ) dθ is an integral over many dimensions with no formula.',
      'We rarely need the density itself: we need **expectations** — the posterior mean, the probability that an effect is positive, the posterior predictive. Each is ∫ f(θ) p(θ | D) dθ for some f.',
      'If we can draw samples θ₁, …, θ_S from p, the **Monte Carlo** estimate is the average (1/S) Σ f(θₛ). It is unbiased, and it works in any number of dimensions.',
      'Its standard error is σ_f / √S, where σ_f is the standard deviation of f(θ): four times as many samples halve the error, whatever the dimension. That is why sampling beats grids beyond a few dimensions — a grid with 100 points per axis needs 100¹⁰ points in 10 dimensions.',
      'The catch: drawing independent samples from a posterior known only up to its normalizer is itself hard. The rest of this lab covers the two answers — reweight samples from something easy (importance sampling), or build a random walk that visits θ in proportion to p (MCMC) — and a third route that optimizes an approximation instead (variational inference).',
    ],
    formula: 'E_p[f] ≈ (1/S) Σₛ f(θₛ),  θₛ ~ p     standard error = σ_f / √S',
    derivation: {
      title: 'The Monte Carlo error',
      steps: [
        { prompt: 'The variance of an average of S independent draws with variance v. Write it in terms of v and S.', answer: 'v/S', show: '`v/S`', vars: { v: [0.1, 5], S: [1, 1000] } },
        { prompt: 'With σ_f = 2 and S = 400 samples, what is the standard error?', number: 0.1, show: '`2/√400 = 0.1`' },
        { prompt: 'How many samples to reach a standard error of 0.01?', number: 40000, show: '`(2/0.01)² = 40,000`', why: 'Ten times more precision costs a hundred times more samples.' },
      ],
      result: 'The 1/√S rate does not depend on dimension — but it assumes independent samples. Correlated samples count for less (Lesson 44.4).',
    },
    experiment: 'In the importance-sampling view, press “Draw 1,000 new samples” several times with a wide proposal. How much does the estimated mean move between draws?',
    question: 'A Monte Carlo estimate uses 2,500 independent samples of f with standard deviation 5. What is its standard error?',
    answer: 0.1,
    explanation: '5 / √2500 = 5 / 50 = 0.1.',
    reflection: 'Which quantity in a model you use would you most like a posterior for, and what expectation would you compute from it?',
  },
  {
    id: 'l44-importance',
    title: '44.2 · Importance sampling',
    sections: ['Sample from something easy', 'Weights', 'Self-normalization', 'Effective sample size', 'When it silently fails'],
    skill: 'Estimate posterior expectations with importance sampling and judge its reliability.',
    prerequisite: 'Lesson 44.1.',
    paragraphs: [
      'If sampling from p is hard, sample from an easy **proposal** q instead and correct: E_p[f] = ∫ f(θ) (p(θ)/q(θ)) q(θ) dθ = E_q[f · w] with **weights** w = p/q. Samples where q under-represents p get large weights.',
      'We usually know p only up to its normalizer. **Self-normalized** importance sampling divides by the sum of the weights: estimate = Σ wₛ f(θₛ) / Σ wₛ. It is slightly biased but consistent, and needs only the unnormalized p.',
      'If a few samples carry nearly all the weight, the estimate rests on those few. The **effective sample size** ESS = (Σ w)² / Σ w² measures it: equal weights give ESS = S; one dominant weight gives ESS ≈ 1.',
      'The dangerous failure is silent. A proposal centred on one mode of a two-mode posterior never proposes the other, so every weight looks ordinary: the playground reports an ESS above 600 of 1,000 while estimating the mean at −1.9 instead of −0.4. Weights only correct regions q actually visits.',
      'Rule: the proposal must have heavier tails than the target and cover every region where p has mass. In high dimensions, weights almost always degenerate, which is why MCMC dominates there; importance sampling remains central in sequential Monte Carlo and in off-policy evaluation (Lab 35).',
    ],
    formula: 'E_p[f] ≈ Σ wₛ f(θₛ) / Σ wₛ,  wₛ = p̃(θₛ)/q(θₛ),  θₛ ~ q     ESS = (Σ w)² / Σ w²',
    derivation: {
      title: 'Weights and effective sample size',
      steps: [
        { prompt: 'Write the importance weight for target density p and proposal density q.', answer: 'p/q', show: '`p/q`', vars: { p: [0.01, 2], q: [0.01, 2] } },
        { prompt: 'Four samples with weights 1, 1, 1, 1. What is the ESS?', number: 4, show: '`16/4 = 4`' },
        { prompt: 'Four samples with weights 10, 1, 1, 1? (Two decimals.)', number: 169 / 103, tolerance: 0.01, show: '`13²/103 ≈ 1.64`', why: 'One heavy sample dominates: four draws are worth fewer than two.' },
      ],
      result: 'ESS measures how evenly the weights are spread — not whether the proposal missed a region entirely.',
    },
    experiment: 'In the importance-sampling view, set the proposal to mean −2 and sd 0.6. Compare the ESS with the error of the estimated mean. Then try mean 0 and sd 0.5.',
    question: 'Three samples have self-normalized weights 0.5, 0.3 and 0.2 and values f = 2, 4 and 10. What is the importance-sampling estimate of E[f]?',
    answer: 4.2,
    explanation: '0.5 × 2 + 0.3 × 4 + 0.2 × 10 = 1 + 1.2 + 2 = 4.2.',
    reflection: 'Where else have you seen reweighting to correct for sampling from the “wrong” distribution? (Hint: Labs 35–36.)',
  },
  {
    id: 'l44-mcmc',
    title: '44.3 · Markov chain Monte Carlo',
    sections: ['A random walk that visits θ in proportion to p', 'Metropolis–Hastings', 'Why it works: detailed balance', 'Only ratios needed', 'The step size'],
    skill: 'Implement random-walk Metropolis–Hastings and explain why it samples the target.',
    prerequisite: 'Lessons 44.1–44.2; Markov chains (Lab 37’s states and transitions).',
    paragraphs: [
      'MCMC builds a Markov chain whose long-run distribution is the posterior. After a warm-up, the chain’s states are (correlated) samples from p, and averages over them estimate expectations.',
      '**Random-walk Metropolis**: from θ, propose θ′ = θ + step·z with z ~ N(0, I). Accept with probability min(1, p(θ′)/p(θ)); otherwise stay at θ (and count θ again). Uphill moves are always taken; downhill moves sometimes, in proportion to how much lower p is.',
      'Why it works: the acceptance rule makes p(θ)·T(θ → θ′) = p(θ′)·T(θ′ → θ) for every pair — **detailed balance**. The flow of probability between any two states balances, so p is the stationary distribution. (For asymmetric proposals, Metropolis–Hastings multiplies the ratio by q(θ | θ′)/q(θ′ | θ).)',
      'The acceptance probability uses only the ratio p(θ′)/p(θ), so the unknown normalizer p(D) cancels. That is the whole reason MCMC is practical for posteriors.',
      'The step size is a trade-off: tiny steps are nearly always accepted but move slowly; huge steps are nearly always rejected. In the playground’s correlated target, step 0.1 accepts 86% and yields about 16 effective samples out of 4,500, while step 1.5 accepts 14% and yields about 180. Rules of thumb aim for acceptance around 20–50%, adapted during warm-up.',
    ],
    formula: 'accept θ′ with probability min(1, p̃(θ′)/p̃(θ))     detailed balance: p(θ)T(θ→θ′) = p(θ′)T(θ′→θ)',
    derivation: {
      title: 'Metropolis acceptance and detailed balance',
      steps: [
        { prompt: 'The current state has unnormalized density 0.8, the proposal 0.2. What is the acceptance probability?', number: 0.25, show: '`min(1, 0.2/0.8) = 0.25`' },
        { prompt: 'Reverse move: from 0.2 to 0.8?', number: 1, show: '`1`' },
        { prompt: 'Check detailed balance for a symmetric proposal: write p(a)·min(1, p(b)/p(a)) when p(b) < p(a), in terms of pa and pb.', answer: 'pb', show: '`p(b)` — which equals p(b)·min(1, p(a)/p(b)) = p(b)·1', vars: { pa: [1, 2], pb: [0.1, 0.9] } },
      ],
      result: 'Both directions carry flow p(b)·q: balanced. The normalizer never appears.',
    },
    experiment: 'In the MCMC view on the correlated Gaussian, try step sizes 0.1, 0.5, 1.5 and 4. Record the acceptance rate and the effective sample size for each. Which step would you choose?',
    question: 'The current log-density is −3.0 and the proposal’s is −4.2. What is the acceptance probability? (Three decimals.)',
    answer: 0.301, tolerance: 0.001,
    explanation: 'exp(−4.2 − (−3.0)) = e^(−1.2) ≈ 0.301. Work with log-densities to avoid underflow.',
    reflection: 'Explain to a classmate why MCMC does not need the normalizing constant of the posterior.',
  },
  {
    id: 'l44-diagnostics',
    title: '44.4 · Gibbs sampling and convergence diagnostics',
    sections: ['Gibbs: one coordinate at a time', 'Autocorrelation and effective sample size', 'Burn-in and trace plots', 'R̂: do the chains agree?', 'Better samplers'],
    skill: 'Run Gibbs sampling and diagnose MCMC with autocorrelation, ESS, trace plots and R̂.',
    prerequisite: 'Lesson 44.3; conditional Gaussians (Lab 42).',
    paragraphs: [
      '**Gibbs sampling** updates one coordinate at a time by drawing it from its full conditional distribution given all the others. Every move is accepted. For a standard bivariate normal with correlation ρ, θ₁ | θ₂ ~ N(ρθ₂, 1 − ρ²). With ρ = 0.95 each move is tiny relative to the long diagonal, so the chain crawls.',
      'Consecutive MCMC samples are correlated. The **effective sample size** n / (1 + 2 Σₖ ρₖ), with ρₖ the autocorrelation at lag k, says how many independent samples the chain is worth. Monte Carlo error uses the ESS, not n.',
      'Discard an initial **burn-in** while the chain travels from its start to the typical region. Plot **traces**: good chains look like overlapping fuzzy caterpillars; trends or long flat runs signal trouble.',
      'A single chain can look perfect while stuck. Run several chains from dispersed starts and compare them: **R̂** is the ratio of the between-chain-plus-within-chain variance estimate to the within-chain variance. It approaches 1 when chains agree; values above about 1.01 mean “keep sampling or fix the sampler”. In the two-mode target with small steps, each chain reports a healthy ESS but R̂ is above 3.',
      'Modern samplers use gradients: **Hamiltonian Monte Carlo** and its adaptive variant NUTS (used by Stan and PyMC) make long, directed moves and handle correlated posteriors far better than random walks. Multimodal posteriors remain hard for every sampler.',
    ],
    formula: 'ESS = n / (1 + 2 Σₖ ρₖ)     R̂ = √( ((n−1)/n·W + B/n) / W )',
    derivation: {
      title: 'Gibbs conditional for a bivariate normal',
      intro: 'Standard bivariate normal with correlation ρ.',
      steps: [
        { prompt: 'The conditional mean of θ₁ given θ₂. Write it in terms of ρ and t2 (for θ₂).', answer: 'ρ*t2', show: '`ρ·θ₂`', vars: { ρ: [-0.9, 0.9], t2: [-3, 3] }, hint: 'Type ρ as rho.' },
        { prompt: 'Its conditional variance.', answer: '1 - ρ^2', show: '`1 − ρ²`', vars: { ρ: [-0.9, 0.9] } },
        { prompt: 'With ρ = 0.95, what is the conditional standard deviation? (Four decimals.)', number: Math.sqrt(1 - 0.95 ** 2), tolerance: 1e-4, show: '`√(1 − 0.9025) ≈ 0.3122`', why: 'Each Gibbs move is about a third of the marginal spread: slow exploration along the diagonal.' },
      ],
      result: 'Strong correlation makes the conditionals narrow, so coordinate-wise sampling crawls — reparameterize or use gradient-based samplers.',
    },
    experiment: 'In the MCMC view, compare Gibbs with Metropolis (step 1.5) on the correlated Gaussian. Then choose the two-mode target with step 0.5: look at the trace plot and R̂.',
    question: 'A chain of 5,000 draws has autocorrelations summing to Σₖ ρₖ = 12. What is its effective sample size? (Nearest whole number.)',
    answer: 200, tolerance: 1,
    explanation: '5000 / (1 + 24) = 200 — the chain is worth 200 independent draws.',
    reflection: 'What would you report alongside an MCMC estimate so a reader could trust it?',
  },
  {
    id: 'l44-vi',
    title: '44.5 · Variational inference',
    sections: ['Turn inference into optimization', 'Maximize the ELBO', 'Mode-seeking and shrinking variance', 'Forward versus reverse KL', 'Demonstrate understanding'],
    skill: 'Explain variational inference, its objective and its characteristic biases, and choose between VI and MCMC.',
    prerequisite: 'Lessons 44.1–44.4; the ELBO (Lab 43).',
    paragraphs: [
      '**Variational inference** (VI) picks a simple family of distributions q_λ — for example independent Gaussians — and finds the member closest to the posterior by optimization: minimize KL(q_λ ‖ p(θ | D)).',
      'That KL contains the unknown log p(D), but log p(D) = ELBO(λ) + KL(q ‖ p), so minimizing the KL is maximizing the **ELBO** = E_q[log p(D, θ)] − E_q[log q(θ)] — the same bound as EM (Lab 43), now optimized over a distribution family. With the reparameterization θ = μ + σε, gradients of the ELBO can be estimated by sampling, which scales VI to huge models (and powers VAEs, Lab 53).',
      'KL(q ‖ p) is large when q puts mass where p has little, but cheap when q ignores part of p. So VI is **mode-seeking**: facing two modes, the best Gaussian sits on one (here mean −2.0, sd 0.60) and ignores the other. A **mean-field** q cannot represent correlation and **underestimates variances**: for a Gaussian posterior with correlation ρ, each factor’s variance is 1 − ρ² instead of 1.',
      'Minimizing the other direction, KL(p ‖ q), gives **moment matching**: q takes the true mean and variance (−0.4 and sd 2.08 here), covering both modes but putting mass between them. Expectation propagation follows this direction.',
      'Choose: MCMC is asymptotically exact but slow and hard to diagnose at scale; VI is fast, deterministic to monitor and scalable, but biased in known ways. You have completed this lab when you can: estimate expectations by Monte Carlo with an error bar; use and judge importance sampling; implement and tune Metropolis–Hastings and Gibbs; diagnose chains with traces, ESS and R̂; and explain VI’s objective and biases. The Python challenge implements the samplers and diagnostics.',
    ],
    formula: 'log p(D) = ELBO(q) + KL(q ‖ p(θ | D))     mean-field Gaussian: Var_q(θᵢ) = 1/Λᵢᵢ',
    derivation: {
      title: 'Mean-field variance for a correlated Gaussian',
      intro: 'Posterior: standard bivariate normal with correlation ρ. Its precision matrix Λ has diagonal entries 1/(1 − ρ²). Mean-field VI gives each factor variance 1/Λᵢᵢ.',
      steps: [
        { prompt: 'Write the mean-field variance of θ₁ in terms of ρ.', answer: '1 - ρ^2', show: '`1 − ρ²`', vars: { ρ: [-0.95, 0.95] } },
        { prompt: 'With ρ = 0.9, what fraction of the true standard deviation does mean-field VI report? (Three decimals.)', number: Math.sqrt(0.19), tolerance: 1e-3, show: '`√0.19 ≈ 0.436`' },
      ],
      result: 'Strong posterior correlation makes mean-field VI badly overconfident — check with a few MCMC runs when uncertainty matters.',
    },
    experiment: 'In the variational view, move ρ from 0 to 0.99 and compare the ellipses. Then read the two one-dimensional fits: which would you report if the question were “what is P(θ > 0)?”',
    question: 'A posterior has two equal, well-separated modes at −3 and +3, each with standard deviation 0.5. Mean-field VI with a single Gaussian returns mean ≈ −3. Approximately what posterior probability of θ > 0 does it imply?',
    answer: 0,
    explanation: 'The Gaussian at −3 with sd 0.5 puts essentially no mass above 0, yet the true probability is 0.5. Mode-seeking can make a confident, wrong statement.',
    reflection: 'For a model you care about, which matters more: speed of inference, or honest uncertainty? What would you use?',
  },
]

export const sources = [
  { title: 'MacKay · Information Theory, Inference, and Learning Algorithms, ch. 29–33 (free book)', url: 'https://www.inference.org.uk/itila/book.html' },
  { title: 'Blei, Kucukelbir & McAuliffe (2017) · Variational inference: a review for statisticians', url: 'https://arxiv.org/abs/1601.00670' },
  { title: 'Vehtari et al. (2021) · Rank-normalization, folding, and localization: an improved R̂', url: 'https://arxiv.org/abs/1903.08008' },
  { title: 'Betancourt (2017) · A conceptual introduction to Hamiltonian Monte Carlo', url: 'https://arxiv.org/abs/1701.02434' },
]
