// The curated series and their lessons, in teaching order. Plain data, so the
// checker (scripts/check_notebook_series.mjs) can read it outside Vite.
//
// A lesson's text lives in `./<series dir>/<slug>.md`; until that file exists
// the lesson shows as "coming soon". Its id is `<prefix>-<slug>` and is a
// progress key: once a lesson ships, never rename its slug. Reordering lessons
// here is safe. Curriculum and lesson standard: docs/notebook-series-curriculum.md.

const series = (id, dir, prefix, title, blurb, lessons) => ({
  id,
  dir,
  title,
  blurb,
  lessons: lessons.map(([slug, lessonTitle], i) => ({
    id: `${prefix}-${slug}`,
    slug,
    number: i + 1,
    title: lessonTitle,
  })),
})

export const SERIES_MANIFEST = [
  series('python', 'python', 'py', 'Python from Zero',
    'No experience needed. Start here before Machine Learning or Algorithms.', [
      ['running-code', 'Running code'],
      ['numbers-and-variables', 'Numbers and variables'],
      ['strings', 'Strings'],
      ['decisions', 'Decisions'],
      ['lists', 'Lists'],
      ['for-loops', 'for loops'],
      ['while-loops', 'while loops'],
      ['functions', 'Functions'],
      ['functions-in-depth', 'Functions in depth'],
      ['dictionaries', 'Dictionaries'],
      ['tuples-and-sets', 'Tuples and sets'],
      ['names-and-references', 'Names and references'],
      ['comprehensions', 'Comprehensions'],
      ['errors-and-exceptions', 'Errors and exceptions'],
      ['debugging', 'Debugging'],
      ['modules', 'Modules and the standard library'],
      ['files-and-text', 'Files and text data'],
      ['classes-and-objects', 'Classes and objects'],
      ['special-methods', 'Special methods'],
      ['inheritance', 'Inheritance'],
      ['iterators-and-generators', 'Iterators and generators'],
      ['functions-as-values', 'Functions as values'],
      ['type-hints-and-dataclasses', 'Type hints and dataclasses'],
      ['testing-your-code', 'Testing your own code'],
    ]),

  series('ml', 'ml', 'ml', 'Machine Learning',
    'From NumPy to Q-learning, every core algorithm written from scratch first.', [
      ['numpy-arrays', 'NumPy arrays'],
      ['indexing-and-broadcasting', 'Indexing, shapes and broadcasting'],
      ['plotting', 'Plotting with matplotlib'],
      ['vectors', 'Vectors'],
      ['matrices-as-transformations', 'Matrices as transformations'],
      ['linear-systems', 'Solving linear systems'],
      ['eigenvectors-and-svd', 'Eigenvectors and SVD'],
      ['rates-of-change', 'Rates of change'],
      ['gradients-and-chain-rule', 'Gradients and the chain rule'],
      ['probability-by-simulation', 'Probability by simulation'],
      ['distributions', 'Distributions'],
      ['expectation-and-variance', 'Expectation and variance'],
      ['estimation-and-uncertainty', 'Estimation and uncertainty'],
      ['pandas-dataframes', 'pandas: DataFrames'],
      ['pandas-reshaping', 'pandas: reshaping and joining'],
      ['exploring-a-dataset', 'Exploring a dataset'],
      ['what-learning-is', 'What learning is'],
      ['least-squares', 'Linear regression by least squares'],
      ['loss-functions', 'Loss functions'],
      ['gradient-descent', 'Gradient descent'],
      ['multiple-regression', 'Multiple regression, vectorised'],
      ['overfitting', 'Overfitting and the bias–variance trade-off'],
      ['regularisation', 'Regularisation'],
      ['cross-validation', 'Validation and cross-validation'],
      ['perceptron', 'The perceptron'],
      ['perceptron-limits', 'What a perceptron cannot learn'],
      ['logistic-regression', 'Logistic regression'],
      ['classification-metrics', 'Classification metrics'],
      ['softmax-regression', 'Softmax regression'],
      ['knn', 'k-nearest neighbours'],
      ['naive-bayes', 'Naive Bayes'],
      ['decision-trees', 'Decision trees'],
      ['random-forests', 'Bagging and random forests'],
      ['boosting', 'Boosting'],
      ['svm', 'Support vector machines'],
      ['sklearn-workflow', 'The scikit-learn workflow'],
      ['feature-engineering', 'Feature engineering'],
      ['leakage-and-imbalance', 'Data leakage and imbalanced data'],
      ['hyperparameter-search', 'Hyperparameter search'],
      ['k-means', 'k-means'],
      ['hierarchical-and-dbscan', 'Hierarchical clustering and DBSCAN'],
      ['gaussian-mixtures', 'Gaussian mixtures and EM'],
      ['pca', 'PCA'],
      ['visualising-high-dimensions', 'Visualising high-dimensional data'],
      ['anomaly-detection', 'Anomaly detection'],
      ['neural-networks', 'From perceptron to neural network'],
      ['activation-functions', 'Activation functions'],
      ['backprop-by-hand', 'Backpropagation by hand'],
      ['autograd-engine', 'An automatic differentiation engine'],
      ['training-a-network', 'Training a network'],
      ['optimisers', 'Optimisers'],
      ['regularising-networks', 'Regularising networks'],
      ['convolution', 'Convolution'],
      ['cnns', 'Convolutional networks'],
      ['rnns', 'Recurrent networks'],
      ['lstm-and-gru', 'LSTM and GRU'],
      ['embeddings', 'Embeddings'],
      ['attention', 'Attention'],
      ['transformer-block', 'The transformer block'],
      ['autoencoders', 'Autoencoders'],
      ['generative-models', 'Generative models'],
      ['bayesian-inference', 'Bayesian inference'],
      ['time-series', 'Time series'],
      ['rl-problem', 'The reinforcement learning problem'],
      ['bandits', 'Multi-armed bandits'],
      ['mdps', 'Markov decision processes'],
      ['rl-dynamic-programming', 'Dynamic programming'],
      ['monte-carlo-rl', 'Monte Carlo methods'],
      ['td-and-sarsa', 'Temporal-difference learning and SARSA'],
      ['q-learning', 'Q-learning'],
      ['deep-q-learning', 'Deep Q-learning'],
      ['policy-gradients', 'Policy gradients'],
      ['interpreting-models', 'Interpreting models and checking them'],
      ['capstone', 'Capstone: from data to a defensible model'],
    ]),

  series('rl', 'rl', 'rl', 'Reinforcement Learning: the Q-Maze and CartPole',
    'Two classic problems in depth: Q-learning on a maze and on CartPole, then the same agents with a neural network instead of a table (deep Q-learning).', [
      ['q-maze-diy', 'Q-maze, typed by hand: from numpy to Q-learning, planning and a neural network'],
      ['q-maze', 'Q-learning on a maze'],
      ['cartpole', 'CartPole and Q-learning'],
      ['deep-q-maze', 'Deep Q-learning on the maze'],
      ['deep-q-cartpole', 'Deep Q-learning on CartPole'],
    ]),

  series('dsa', 'dsa', 'dsa', 'Algorithms & Design Patterns',
    'Data structures, algorithms and object design, taught together.', [
      ['what-an-algorithm-is', 'What an algorithm is'],
      ['big-o', 'Big-O'],
      ['cost-of-python-operations', 'The cost of Python operations'],
      ['amortised-analysis', 'Amortised analysis'],
      ['dynamic-arrays', 'Dynamic arrays'],
      ['linked-lists', 'Linked lists'],
      ['stacks', 'Stacks'],
      ['queues-and-deques', 'Queues and deques'],
      ['hash-tables', 'Hash tables'],
      ['sets-and-dict-patterns', 'Sets and dictionary patterns'],
      ['recursion', 'Recursion'],
      ['recurrences', 'Recurrences'],
      ['invariants', 'Invariants and correctness'],
      ['binary-search', 'Binary search'],
      ['elementary-sorts', 'Elementary sorts'],
      ['merge-sort', 'Merge sort'],
      ['quicksort', 'Quicksort and quickselect'],
      ['non-comparison-sorts', 'Sorting without comparisons'],
      ['binary-trees', 'Binary trees'],
      ['binary-search-trees', 'Binary search trees'],
      ['balanced-trees', 'Balanced trees'],
      ['heaps', 'Heaps and priority queues'],
      ['tries', 'Tries'],
      ['segment-and-fenwick-trees', 'Segment trees and Fenwick trees'],
      ['graph-representations', 'Graph representations'],
      ['bfs', 'Breadth-first search'],
      ['dfs', 'Depth-first search'],
      ['topological-sort', 'Topological sort'],
      ['dijkstra', "Dijkstra's algorithm"],
      ['bellman-ford-floyd-warshall', 'Bellman-Ford and Floyd-Warshall'],
      ['union-find', 'Union-Find'],
      ['minimum-spanning-trees', 'Minimum spanning trees'],
      ['a-star', 'A* search'],
      ['two-pointers', 'Two pointers'],
      ['sliding-window', 'Sliding window'],
      ['prefix-sums', 'Prefix sums'],
      ['monotonic-stacks', 'Monotonic stacks and queues'],
      ['divide-and-conquer', 'Divide and conquer'],
      ['greedy', 'Greedy algorithms'],
      ['dp-memoisation', 'Dynamic programming: memoisation'],
      ['dp-tabulation', 'Dynamic programming: tabulation'],
      ['dp-two-dimensions', 'Dynamic programming in two dimensions'],
      ['dp-state-design', 'Designing DP states'],
      ['backtracking', 'Backtracking'],
      ['bit-manipulation', 'Bit manipulation'],
      ['string-algorithms', 'String algorithms'],
      ['randomised-algorithms', 'Randomised algorithms'],
      ['why-design-matters', 'Why design matters'],
      ['single-responsibility', 'Single responsibility'],
      ['encapsulation-and-interfaces', 'Encapsulation and interfaces'],
      ['composition-over-inheritance', 'Composition over inheritance'],
      ['polymorphism', 'Polymorphism and duck typing'],
      ['solid', 'SOLID'],
      ['dependency-injection', 'Dependency inversion and injection'],
      ['refactoring', 'Refactoring'],
      ['strategy', 'Strategy'],
      ['factory-method', 'Factory method and simple factory'],
      ['abstract-factory', 'Abstract factory'],
      ['builder', 'Builder'],
      ['singleton', 'Singleton, and why to avoid it'],
      ['prototype', 'Prototype'],
      ['adapter', 'Adapter'],
      ['decorator', 'Decorator'],
      ['facade', 'Facade'],
      ['composite', 'Composite'],
      ['proxy', 'Proxy'],
      ['bridge', 'Bridge'],
      ['flyweight', 'Flyweight'],
      ['observer', 'Observer'],
      ['command', 'Command'],
      ['state', 'State'],
      ['template-method', 'Template method'],
      ['iterator', 'Iterator'],
      ['chain-of-responsibility', 'Chain of responsibility'],
      ['visitor', 'Visitor'],
      ['mediator', 'Mediator'],
      ['memento', 'Memento'],
      ['interpreter', 'Interpreter'],
      ['patterns-vs-simpler-python', 'Patterns vs simpler Python'],
      ['testing-algorithms', 'Testing algorithms'],
      ['profiling', 'Profiling and optimisation'],
      ['project-lru-cache', 'Project: LRU cache'],
      ['project-text-editor', 'Project: text editor with undo'],
      ['project-expression-evaluator', 'Project: expression evaluator'],
      ['project-job-scheduler', 'Project: job scheduler'],
      ['capstone-route-planner', 'Capstone: route planner'],
    ]),

  series('math', 'math', 'math', 'Mathematics Through Computation',
    'One mathematics curriculum, from quantities to advanced topics, learned through applications and computation.', [
      ['numbers-exact-and-approximate', 'Numbers, exact and approximate'],
      ['quantities-and-units', 'Quantities and units'],
      ['ratios-rates-and-scaling', 'Ratios, rates and scaling'],
      ['powers-and-orders-of-magnitude', 'Powers and orders of magnitude'],
      ['formulas-as-functions', 'Formulas as functions'],
      ['plotting-a-relationship', 'Plotting a relationship'],
      ['arrays', 'Arrays: computing on many values'],
      ['coordinates-and-distance', 'Coordinates and distance'],
      ['lines-and-slope', 'Lines, slope and calibration'],
      ['motion-in-one-dimension', 'Motion in one dimension'],
      ['average-rate-of-change', 'Average rate of change'],
      ['angles-and-rotation', 'Angles, radians and rotation'],
      ['sine-and-cosine-from-rotation', 'Sine and cosine from rotation'],
      ['vectors', 'Vectors: size and direction'],
      ['components-and-resultants', 'Components and resultants'],
      ['projectile-motion', 'Projectile motion'],
      ['two-equations-two-unknowns', 'Two equations, two unknowns'],
      ['matrices-as-systems', 'Matrices: a system in one object'],
      ['matrices-that-move-points', 'Matrices that move points'],
      ['the-derivative-appears', 'Instantaneous rate: the derivative appears'],
      ['newtons-second-law', "Newton's second law, simulated"],
      ['accumulation', 'Accumulation: from rate back to total'],
      ['work-and-energy', 'Work and energy'],
      ['exponential-change', 'Exponential growth and decay'],
      ['logarithms', 'Logarithms and log scales'],
      ['probability-by-simulation', 'Probability by simulation'],
      ['random-variables', 'Random variables and distributions'],
      ['statistics-from-measurements', 'Statistics from measurements'],
      ['fitting-a-line', 'Fitting a line to data'],
      ['finding-the-best', 'Finding the best: optimisation'],
      ['walking-downhill', 'Walking downhill: gradient descent'],
      ['functions-of-two-variables', 'Functions of two variables'],
      ['partial-derivatives-and-the-gradient', 'Partial derivatives and the gradient'],
      ['the-jacobian', 'The Jacobian: how outputs follow inputs'],
      ['eigenvectors-through-vibration', 'Eigenvectors through vibration'],
      ['laws-as-rates', 'Differential equations: laws as rates'],
      ['the-spring-mass-system', 'The spring–mass system'],
      ['waves-amplitude-frequency-phase', 'Waves: amplitude, frequency and phase'],
      ['building-signals-from-sines', 'Building signals from sines'],
      ['seeing-frequencies', 'Seeing frequencies: the spectrum'],
      ['sampling-and-aliasing', 'Sampling and aliasing'],
      ['graphs-and-networks', 'Graphs and networks'],
      ['shortest-paths', 'Shortest paths'],
      ['counting-possibilities', 'Counting possibilities'],
      ['bayes-theorem', "Updating beliefs: Bayes' theorem"],
      ['directions-of-most-variation', 'Directions of most variation: PCA'],
      ['compressing-with-the-svd', 'Compressing with the SVD'],
      ['the-chain-rule-and-learning', 'The chain rule and learning'],
      ['solving-equations-numerically', 'Solving equations numerically'],
      ['when-numbers-betray-you', 'When numbers betray you'],
      ['robot-arm-kinematics', 'Robot arm kinematics'],
      ['heat-flow-on-a-bar', 'Heat flow on a bar'],
      ['a-vibrating-string', 'A vibrating string'],
      ['first-tour-capstone', 'Capstone: simulate a machine'],
      ['fractions-and-exact-arithmetic', 'Fractions and exact arithmetic'],
      ['relative-change-and-error', 'Percentages, relative change and relative error'],
      ['dimensional-analysis', 'Dimensional analysis'],
      ['floating-point', 'How computers store numbers'],
      ['error-propagation', 'Propagating measurement error'],
      ['rearranging-formulas', 'Rearranging formulas, with SymPy'],
      ['inequalities-and-tolerances', 'Inequalities and tolerances'],
      ['absolute-value', 'Absolute value and error bands'],
      ['domain-and-range', 'Functions: domain, range and mapping'],
      ['composition-and-inverses', 'Composition and inverse functions'],
      ['transforming-graphs', 'Shifting, stretching and reflecting graphs'],
      ['quadratics', 'Quadratics in depth'],
      ['polynomials', 'Polynomials: roots, factors and multiplicity'],
      ['rational-functions', 'Rational functions, poles and asymptotes'],
      ['piecewise-functions', 'Piecewise functions'],
      ['power-laws', 'Power laws and log–log plots'],
      ['sequences', 'Sequences, arithmetic and geometric'],
      ['recurrences', 'Recurrences and iteration'],
      ['parametric-curves', 'Parametric curves'],
      ['polar-curves', 'Polar curves'],
      ['nonlinear-systems', 'Systems of nonlinear equations'],
      ['triangles-and-similarity', 'Triangles and similarity'],
      ['right-triangle-trigonometry', 'Right-triangle trigonometry'],
      ['inverse-trig-and-atan2', 'Inverse trigonometry and atan2'],
      ['trig-identities', 'Trigonometric identities, by computation'],
      ['laws-of-sines-and-cosines', 'The laws of sines and cosines'],
      ['circles-arcs-and-tangents', 'Circles, arcs and tangents'],
      ['areas-of-polygons', 'Areas of polygons'],
      ['volumes-and-mass-properties', 'Volumes and mass properties'],
      ['conic-sections', 'Conic sections'],
      ['the-dot-product', 'The dot product'],
      ['projections-and-closest-points', 'Projections and closest points'],
      ['the-cross-product', 'The cross product'],
      ['lines-and-planes-in-3d', 'Lines and planes in 3D'],
      ['coordinate-frames', 'Coordinate frames'],
      ['complex-numbers', 'Complex numbers'],
      ['the-complex-plane', 'The complex plane and polar form'],
      ['eulers-formula', "Euler's formula"],
      ['roots-of-unity', 'Roots of complex numbers'],
      ['phasors-and-ac-circuits', 'Phasors and AC circuits'],
      ['affine-transformations', 'Affine transformations and homogeneous coordinates'],
      ['rotations-in-3d', 'Rotations in 3D'],
      ['camera-projection', 'Camera projection and perspective'],
      ['linear-combinations-and-span', 'Linear combinations and span'],
      ['independence-basis-dimension', 'Independence, basis and dimension'],
      ['matrix-multiplication', 'Matrix multiplication in depth'],
      ['gaussian-elimination', 'Gaussian elimination from scratch'],
      ['pivoting-and-lu', 'Pivoting and LU decomposition'],
      ['rank-and-solution-sets', 'Rank and solution sets'],
      ['null-space-and-column-space', 'Null space and column space'],
      ['determinants', 'Determinants: area, volume and orientation'],
      ['inverse-matrices', 'Inverse matrices, and why to avoid them'],
      ['change-of-basis', 'Change of basis'],
      ['eigenvalues', 'Eigenvalues and the characteristic polynomial'],
      ['diagonalisation', 'Diagonalisation and matrix powers'],
      ['orthogonality', 'Orthogonality and Gram–Schmidt'],
      ['least-squares', 'Least squares: projection onto a subspace'],
      ['qr-decomposition', 'QR decomposition'],
      ['the-svd', 'The singular value decomposition'],
      ['principal-components', 'Principal component analysis'],
      ['positive-definite-matrices', 'Positive-definite matrices and quadratic forms'],
      ['condition-numbers', 'Condition numbers'],
      ['iterative-solvers', 'Iterative solvers'],
      ['limits', 'Limits'],
      ['continuity', 'Continuity'],
      ['derivative-rules', 'The derivative and its basic rules'],
      ['product-and-quotient-rules', 'The product and quotient rules'],
      ['the-chain-rule', 'The chain rule'],
      ['exponential-log-and-trig-derivatives', 'Derivatives of exponential, logarithmic and trigonometric functions'],
      ['implicit-differentiation', 'Implicit differentiation'],
      ['related-rates', 'Related rates'],
      ['higher-derivatives', 'Higher derivatives, jerk and curvature'],
      ['linear-approximation', 'Linear approximation and differentials'],
      ['optimisation-with-derivatives', 'Optimisation with derivatives'],
      ['newtons-method', "Newton's method and its convergence"],
      ['riemann-sums', 'Riemann sums'],
      ['the-definite-integral', 'The definite integral'],
      ['fundamental-theorem', 'The fundamental theorem of calculus'],
      ['substitution', 'Integration by substitution'],
      ['integration-by-parts', 'Integration by parts'],
      ['partial-fractions', 'Partial fractions'],
      ['numerical-integration', 'Numerical integration: trapezoid and Simpson'],
      ['work-and-fluid-force', 'Work and fluid force'],
      ['centre-of-mass', 'Centre of mass and moments'],
      ['average-value-and-rms', 'Average value and RMS'],
      ['improper-integrals', 'Improper integrals'],
      ['convergence-of-sequences', 'Convergence of sequences'],
      ['infinite-series', 'Infinite series'],
      ['power-series', 'Power series'],
      ['taylor-series', 'Taylor series'],
      ['taylor-error', 'Taylor error bounds and small-angle approximations'],
      ['slope-fields', 'Slope fields'],
      ['eulers-method', "Euler's method and its error"],
      ['separable-equations', 'Separable equations'],
      ['linear-first-order', 'Linear first-order equations'],
      ['logistic-growth', 'Logistic growth'],
      ['second-order-linear', 'Second-order linear equations'],
      ['damping', 'Damping'],
      ['forced-oscillation', 'Forced oscillation and resonance'],
      ['runge-kutta', 'Runge–Kutta and solve_ivp'],
      ['energy-and-integrators', 'Energy drift and symplectic integrators'],
      ['the-pendulum', 'The pendulum, beyond small angles'],
      ['drag', 'Drag and terminal velocity'],
      ['coupled-oscillators', 'Coupled oscillators'],
      ['phase-space', 'Phase space'],
      ['equilibria-and-stability', 'Equilibria and stability'],
      ['predator-prey', 'Predator–prey systems'],
      ['epidemic-models', 'Epidemic models'],
      ['reaction-kinetics', 'Chemical reaction kinetics'],
      ['orbits', 'Orbits'],
      ['rigid-body-rotation', 'Rigid-body rotation'],
      ['sample-spaces-and-events', 'Sample spaces and events'],
      ['probability-rules', 'The rules of probability'],
      ['conditional-probability', 'Conditional probability'],
      ['independence', 'Independence'],
      ['counting-and-probability', 'Counting and probability'],
      ['discrete-distributions', 'Discrete distributions'],
      ['expectation', 'Expectation'],
      ['variance', 'Variance and standard deviation'],
      ['continuous-distributions', 'Continuous distributions and densities'],
      ['the-normal-distribution', 'The normal distribution'],
      ['exponential-and-poisson-processes', 'Exponential waiting times and Poisson processes'],
      ['joint-distributions', 'Joint distributions and covariance'],
      ['law-of-large-numbers', 'The law of large numbers'],
      ['central-limit-theorem', 'The central limit theorem'],
      ['monte-carlo', 'Monte Carlo methods'],
      ['data-tables', 'Data tables with pandas'],
      ['descriptive-statistics', 'Descriptive statistics'],
      ['visualising-data', 'Visualising distributions'],
      ['sampling-distributions', 'Sampling distributions and standard error'],
      ['confidence-intervals', 'Confidence intervals'],
      ['hypothesis-tests', 'Hypothesis tests'],
      ['effect-size-and-power', 'Effect size and power'],
      ['correlation', 'Correlation'],
      ['regression-in-depth', 'Linear regression in depth'],
      ['residuals', 'Residual analysis'],
      ['multiple-regression', 'Multiple and polynomial regression'],
      ['anova', 'ANOVA and experimental design'],
      ['design-of-experiments', 'Designing experiments'],
      ['bootstrap', 'The bootstrap'],
      ['bayesian-statistics', 'Bayesian statistics'],
      ['maximum-likelihood', 'Maximum likelihood'],
      ['surfaces-and-contours', 'Surfaces and contour plots'],
      ['partial-derivatives', 'Partial derivatives in depth'],
      ['directional-derivatives', 'Directional derivatives and tangent planes'],
      ['multivariable-chain-rule', 'The multivariable chain rule and computational graphs'],
      ['jacobians', 'Jacobians in depth'],
      ['hessians', 'Hessians and curvature'],
      ['unconstrained-optimisation', 'Unconstrained optimisation'],
      ['gradient-descent', 'Gradient descent in depth'],
      ['momentum-and-adaptive-steps', 'Momentum and adaptive steps'],
      ['newton-optimisation', "Newton's method for optimisation"],
      ['convexity', 'Convex functions and convex sets'],
      ['lagrange-multipliers', 'Constrained optimisation and Lagrange multipliers'],
      ['linear-programming', 'Linear programming'],
      ['integer-programming', 'Integer programming'],
      ['multi-objective-optimisation', 'Multi-objective optimisation'],
      ['double-integrals', 'Double integrals'],
      ['change-of-variables', 'Polar, cylindrical and spherical coordinates'],
      ['triple-integrals', 'Triple integrals'],
      ['vector-fields', 'Vector fields'],
      ['gradient-fields-and-potentials', 'Gradient fields and potentials'],
      ['divergence-and-curl', 'Divergence and curl'],
      ['line-integrals', 'Line integrals and work'],
      ['surface-integrals-and-flux', 'Surface integrals and flux'],
      ['greens-theorem', "Green's theorem"],
      ['divergence-and-stokes-theorems', 'The divergence and Stokes theorems'],
      ['rounding-and-cancellation', 'Rounding error and cancellation'],
      ['conditioning-and-stability', 'Conditioning and stability'],
      ['root-finding', 'Root finding: bisection, secant and Newton compared'],
      ['interpolation', 'Polynomial interpolation'],
      ['splines', 'Splines'],
      ['numerical-differentiation', 'Numerical differentiation and its errors'],
      ['quadrature', 'Gaussian and adaptive quadrature'],
      ['stiff-equations', 'Stiff equations and implicit methods'],
      ['finite-differences', 'Finite differences for boundary problems'],
      ['sparse-matrices', 'Sparse matrices'],
      ['fixed-point-iteration', 'Fixed-point iteration and convergence'],
      ['periodic-signals', 'Periodic signals'],
      ['fourier-series', 'Fourier series'],
      ['the-fourier-transform', 'The Fourier transform'],
      ['the-dft', 'The discrete Fourier transform'],
      ['the-fft', 'The fast Fourier transform'],
      ['nyquist-and-reconstruction', 'Sampling theory and reconstruction'],
      ['windowing-and-leakage', 'Windowing and spectral leakage'],
      ['convolution', 'Convolution'],
      ['filters', 'Digital filters'],
      ['correlation-of-signals', 'Cross-correlation and autocorrelation'],
      ['noise-and-power-spectra', 'Noise and power spectral density'],
      ['spindle-vibration-analysis', 'Analysing spindle vibration'],
      ['feedback', 'Feedback and control'],
      ['transfer-functions', 'Transfer functions, poles and zeros'],
      ['step-and-frequency-response', 'Step response and Bode plots'],
      ['pid-control', 'PID control'],
      ['state-space', 'State-space models'],
      ['controllability-and-observability', 'Controllability and observability'],
      ['kalman-filter', 'The Kalman filter'],
      ['logic-and-propositions', 'Logic and propositions'],
      ['boolean-algebra', 'Truth tables and Boolean algebra'],
      ['sets', 'Sets and set operations'],
      ['relations', 'Relations and equivalence classes'],
      ['functions-as-mappings', 'Functions as mappings'],
      ['quantifiers', 'Quantifiers and specifications'],
      ['proof-techniques', 'Proof techniques'],
      ['induction', 'Mathematical induction'],
      ['pigeonhole-and-inclusion-exclusion', 'Pigeonhole and inclusion–exclusion'],
      ['binomial-coefficients', "Binomial coefficients and Pascal's triangle"],
      ['generating-functions', 'Generating functions'],
      ['graph-theory', 'Graph theory: degrees, paths and trees'],
      ['network-flow', 'Network flow and matching'],
      ['divisibility-and-gcd', 'Divisibility, primes and the Euclidean algorithm'],
      ['modular-arithmetic', 'Modular arithmetic'],
      ['modular-inverses-and-crt', 'Modular inverses and the Chinese remainder theorem'],
      ['rsa', 'Fast exponentiation, Fermat and RSA'],
      ['entropy', 'Entropy and information'],
      ['coding-and-compression', 'Coding, compression and error correction'],
      ['automata', 'Automata and regular languages'],
      ['computability-and-complexity', 'Computability and complexity'],
      ['markov-chains', 'Markov chains'],
      ['random-walks-and-brownian-motion', 'Random walks and Brownian motion'],
      ['stochastic-differential-equations', 'Stochastic differential equations'],
      ['game-theory', 'Strategic games and Nash equilibrium'],
      ['mixed-strategies-and-zero-sum', 'Mixed strategies and zero-sum games'],
      ['repeated-and-evolutionary-games', 'Repeated and evolutionary games'],
      ['bifurcations', 'Bifurcations'],
      ['chaos', 'Chaos: the logistic map and the Lorenz system'],
      ['heat-equation', 'The heat equation'],
      ['wave-equation', 'The wave equation'],
      ['laplace-equation', "Laplace's equation"],
      ['separation-of-variables', 'Separation of variables and Fourier solutions'],
      ['pde-stability', 'Stability of numerical PDE schemes'],
      ['advection-and-diffusion', 'Advection and diffusion'],
      ['complex-functions', 'Complex functions and conformal maps'],
      ['analytic-functions', 'Complex differentiability and the Cauchy–Riemann equations'],
      ['contour-integrals', 'Contour integrals and residues'],
      ['groups-and-symmetry', 'Groups and symmetry'],
      ['rings-and-fields', 'Rings, fields and finite fields'],
      ['real-numbers-and-completeness', 'The real numbers and completeness'],
      ['rigorous-limits', 'Rigorous limits: epsilon and N, epsilon and delta'],
      ['mean-value-and-taylor-theorems', 'The mean value and Taylor theorems'],
      ['uniform-convergence', 'Uniform convergence'],
      ['metric-spaces', 'Metric spaces'],
      ['tensors', 'Tensors and Einstein summation'],
      ['curves-curvature-torsion', 'Curves: curvature and torsion'],
      ['surfaces-and-geodesics', 'Surfaces, normals and geodesics'],
      ['computational-geometry', 'Computational geometry'],
      ['bezier-and-b-splines', 'Bézier curves and B-splines'],
      ['fractals', 'Fractals and dimension'],
      ['capstone-physics-engine', 'Capstone: a physics engine'],
      ['capstone-vibrating-machine', 'Capstone: modelling a vibrating machine'],
      ['capstone-sensor-signal', 'Capstone: analysing a sensor signal'],
      ['capstone-robot-arm', 'Capstone: solving a robot arm'],
      ['capstone-cad-kernel', 'Capstone: a small CAD geometry kernel'],
      ['capstone-fitting-a-model', 'Capstone: fitting a physical model to data'],
      ['capstone-heat-treatment', 'Capstone: simulating heat treatment'],
      ['capstone-investigation', 'Capstone: an engineering investigation'],
    ]),
]
