// Lesson order for Lab 08: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l08-why': [
    { p: 0 },
    { figure: 'LineVsSigmoid', caption: 'Twelve yes/no labels. Orange: a least-squares line. Purple: logistic regression.' },
    { cell: 0 },
    { p: 1 }, { p: 2 },
    { predict: { prompt: 'w = 2, b = −1 and x = 0.5. What probability does σ(w·x + b) give?', answer: 0.5, tolerance: 0.001, explain: 'z = 2 × 0.5 − 1 = 0, and σ(0) = 0.5.' } },
    { cell: 1 },
    { p: 3 }, { p: 4 },
  ],
  'l08-sigmoid': [
    { p: 0 },
    { figure: 'SigmoidExplorer', caption: 'Move the score and read its probability, odds and log-odds.' },
    { p: 1 },
    { predict: { prompt: 'A model predicts p = 0.75. What are the odds p/(1 − p)?', answer: 3, tolerance: 0.001, explain: '0.75/0.25 = 3: three to one.' } },
    { p: 2 },
    { cell: 0 },
    { p: 3 },
    { figure: 'OddsMultiplier', caption: 'One more unit of a feature: the same odds multiplier, different probability changes.' },
    { cell: 1 },
    { p: 4 },
    { figure: 'StableSigmoid', caption: 'Very large scores break the naive formula.' },
    { cell: 2 },
  ],
  'l08-loss': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'LossCurves', caption: 'The loss for one example as its predicted probability moves.' },
    { predict: { prompt: 'A negative example (y = 0) gets p = 0.9. What is its loss −log(1 − p)? (Natural log, three decimals.)', answer: 2.303, tolerance: 0.001, explain: '−log(0.1) = 2.303: confidently wrong costs a lot.' } },
    { cell: 0 },
    { p: 3 },
    { figure: 'SquaredVersusCrossEntropy', caption: 'Two losses through the same sigmoid, for a positive example.' },
    { p: 4 },
    { cell: 1 },
  ],
  'l08-gradient': [
    { p: 0 }, { p: 1 },
    { figure: 'PerExampleGradient', caption: 'One example’s gradient: its error times its input.' },
    { predict: { prompt: 'One example with x = −1, y = 0 and current p = 0.4. What is ∂ℓ/∂w = (p − y)·x?', answer: -0.4, tolerance: 0.001, explain: '(0.4 − 0) × (−1) = −0.4.' } },
    { p: 2 }, { p: 3 },
    { cell: 0 },
    { p: 4 },
    { figure: 'TrainingLoop', caption: 'Batch gradient descent from zeros on overlapping blobs.' },
    { cell: 1 },
    { ladder: 'logistic' },
  ],
  'l08-boundary': [
    { p: 0 }, { p: 1 },
    { figure: 'BoundaryLine', caption: 'The line where w·x + b = 0, with the predicted probability shaded.' },
    { predict: { prompt: 'w = (2, 1) and b = −6. Where does the boundary cross the x₁ axis (x₂ = 0)?', answer: 3, tolerance: 0.001, explain: '2x₁ − 6 = 0 gives x₁ = 3.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'RingFeatures', caption: 'A ring around a centre: linear features against squared features.' },
    { cell: 1 },
    { p: 3 },
    { figure: 'SeparableGrowth', caption: 'Weight size on perfectly separable data, with and without an L2 penalty.' },
    { cell: 2 },
    { p: 4 },
  ],
  'l08-decision': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'CostThreshold', caption: 'Average cost per case as the threshold moves, for calibrated probabilities.' },
    { predict: { prompt: 'A false positive costs 3 and a false negative costs 1. What threshold minimizes expected cost?', answer: 0.75, tolerance: 0.001, explain: 'C_FP/(C_FP + C_FN) = 3/4: act only when quite sure, because acting wrongly is expensive.' } },
    { cell: 0 }, { cell: 1 },
    { p: 3 }, { p: 4 },
  ],
}
