import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l08-why',
    title: '08.1 · From numbers to yes-or-no',
    sections: ['A yes/no target', 'Why not a straight line?', 'Score, then squash', 'Model the probability', 'Put it into practice'],
    skill: 'Frame a binary classification problem as predicting a probability from a linear score.',
    prerequisite: 'Labs 01–07; linear models (Lab 03), likelihood (Lab 05).',
    paragraphs: [
      'Will this build fail? Is this transaction fraud? Did this sensor reading come from a faulty machine? The target y is 1 (yes) or 0 (no). You could fit ordinary least squares to 0/1 targets, but its predictions run below 0 and above 1, and a single far-away point drags the line and moves every decision.',
      'What we actually want is **P(y = 1 | x)**: a number between 0 and 1 that rises smoothly as the evidence for "yes" grows. Most applications need that probability — to rank cases, to set alert thresholds, to combine with costs — not just a hard label.',
      'Keep the linear part you already know: compute a **score** `z = w·x + b`, any real number, where larger means more evidence for class 1. Then pass it through a function that squashes (−∞, +∞) into (0, 1). The model is `p = σ(w·x + b)`. That is **logistic regression**: despite the name, a classification model.',
      'Each prediction is a probability; each training label is an outcome drawn with that probability. So the model makes a precise, testable claim: among cases where it says 0.8, about 80% should be positives. Lab 09 checks that claim (calibration); this lab builds the model and trains it.',
      'Procedure: choose the positive class explicitly (y = 1 means "fails", not "passes"); build features available before the outcome; fit the probability model; evaluate probabilities with log loss; only then choose a decision rule.',
    ],
    formula: 'z = w·x + b ∈ (−∞, ∞)     p = σ(z) ∈ (0, 1)     p ≈ P(y = 1 | x)',
    experiment: 'Before training, the playground predicts p = 0.5 everywhere (all weights zero). Press "Step once" three times on "Overlapping blobs" and describe how the shading changes.',
    question: 'The score is z = 0. What probability does σ(z) = 1 / (1 + e^(−z)) give?',
    answer: 0.5,
    explanation: 'e⁰ = 1, so σ(0) = 1/2. A score of zero is maximal uncertainty; the decision boundary at threshold 0.5 is exactly where z = 0.',
    reflection: 'Name a yes/no prediction in your work. Which class is "positive", and would a probability be more useful than a label? Why?',
  },
  {
    id: 'l08-sigmoid',
    title: '08.2 · The sigmoid and log-odds',
    sections: ['The shape of σ', 'Odds', 'Log-odds are linear', 'Reading a weight', 'Computing σ safely'],
    skill: 'Interpret logistic-regression weights through odds and log-odds, and compute the sigmoid stably.',
    prerequisite: 'Lesson 08.1.',
    paragraphs: [
      'The **sigmoid** `σ(z) = 1 / (1 + e^(−z))` is an S-shaped curve: σ(0) = 0.5, σ(2) ≈ 0.88, σ(−2) ≈ 0.12, and it approaches 1 and 0 at the extremes. It is symmetric: σ(−z) = 1 − σ(z). Its slope is largest at z = 0 and equals σ(z)(1 − σ(z)), a fact the gradient will use.',
      'The **odds** of an event are `p / (1 − p)`: the ratio of "yes" to "no". p = 0.8 gives odds 4 ("four to one"); p = 0.5 gives odds 1. Odds range from 0 to ∞.',
      'Invert the sigmoid: if p = σ(z), then `z = log(p / (1 − p))`, the **log-odds** or **logit**. So logistic regression says the log-odds are a linear function of the features: `log(p/(1−p)) = w·x + b`. It is linear regression on a scale where probabilities are unbounded.',
      'A weight therefore has a precise meaning: increasing feature j by one unit adds `w_j` to the log-odds, i.e. multiplies the odds by `e^(w_j)`, holding the other features fixed. w = 0.7 means odds × 2.0 per unit. The change in **probability** depends on where you start: largest near p = 0.5, tiny near 0 or 1.',
      'Computing `1 / (1 + np.exp(-z))` overflows for very negative z (e^1000 is infinite). Use the stable form: for z ≥ 0 compute `1 / (1 + e^(−z))`, for z < 0 compute `e^z / (1 + e^z)`. Both only exponentiate non-positive numbers. `scipy.special.expit` does exactly this.',
    ],
    formula: 'σ(z) = 1/(1 + e^(−z))     odds = p/(1−p)     logit(p) = log(p/(1−p)) = w·x + b',
    experiment: 'Open "Inside the model". For a point with score z ≈ 2, check that p ≈ 0.88. Find a point with a negative score and confirm p < 0.5.',
    question: 'A model predicts p = 0.8. What are the odds p / (1 − p)?',
    answer: 4,
    misconceptions: [{ answer: 0.8, feedback: 'That is the probability itself. Odds divide it by the probability of “no”: 0.8 / 0.2.' }, { answer: 0.25, feedback: 'That is (1 − p)/p, the odds against. Odds for are p/(1 − p).' }],
    explanation: '0.8 / 0.2 = 4: four positive outcomes for each negative one. The log-odds are ln 4 ≈ 1.386.',
    reflection: 'Explain why a weight changes the probability a lot for some cases and barely at all for others.',
  },
  {
    id: 'l08-loss',
    title: '08.3 · From likelihood to cross-entropy',
    sections: ['The probability of the labels', 'Take the log', 'Binary cross-entropy', 'Why not squared error?', 'Computing it stably'],
    skill: 'Derive binary cross-entropy from the Bernoulli likelihood and compute it without numerical failure.',
    prerequisite: 'Lessons 08.1–08.2; maximum likelihood from Lab 05.',
    paragraphs: [
      'If the model predicts pᵢ for example i, the probability it assigns to the observed label is pᵢ when yᵢ = 1 and 1 − pᵢ when yᵢ = 0 — compactly, `pᵢ^yᵢ (1 − pᵢ)^(1−yᵢ)`. For independent examples, the likelihood of all labels is the product. Maximum likelihood (Lab 05) chooses w and b to make the observed labels as probable as possible.',
      'Products of many probabilities underflow and are awkward to differentiate. Take the logarithm (sums instead of products), negate it (so we minimize), and average: `J = −(1/n) Σ [yᵢ log pᵢ + (1 − yᵢ) log(1 − pᵢ)]`. This is **binary cross-entropy**, also called **log loss**.',
      'Each term is `−log(probability given to the truth)`. Confident and right (p = 0.99 for a positive) costs 0.01. Unsure (0.5) costs log 2 ≈ 0.693. Confident and wrong (p = 0.01 for a positive) costs 4.6. Being confidently wrong is punished severely, which is what makes the probabilities meaningful.',
      'Squared error on probabilities, `(p − y)²`, combined with the sigmoid, gives a non-convex loss with flat regions where the gradient vanishes even though the prediction is badly wrong. Cross-entropy with a sigmoid is **convex** in w and b, and convexity buys one precise guarantee: **there are no bad local minima** — any point where the gradient is zero is a global minimum. It does **not** promise three other things. (1) *A minimum exists:* on perfectly separable data the loss keeps falling as the weights grow, so there is no finite minimizer (Lesson 08.5). (2) *It is unique:* with duplicated or collinear features, many weight vectors tie (Lesson 03.5). (3) *Gradient descent reaches it:* a learning rate that is too large still diverges. Regularization (Lab 07) fixes the first two; a suitable learning rate fixes the third.',
      'Compute the loss from the score z, not from p: `log(1 + e^z) − y·z`, evaluated as `max(z, 0) + log1p(e^(−|z|)) − y·z`. This never takes log of 0 and never overflows. If you must use probabilities, clip them to [ε, 1 − ε].',
    ],
    formula: 'J(w, b) = −mean[y log p + (1 − y) log(1 − p)] = mean[log(1 + e^z) − y z]',
    experiment: 'Watch the per-point loss column while training. Which points still have loss above 1 after 200 steps? Where are they in the plot?',
    question: 'A positive example (y = 1) gets p = 0.5. What is its cross-entropy loss −log(p)? (Natural log, three decimals.)',
    answer: 0.6931, tolerance: 0.0006,
    misconceptions: [{ answer: 0.5, tolerance: 0.01, feedback: 'That is 1 − p. The loss is −log(p): natural logarithm of 0.5, negated.' }],
    explanation: '−ln(0.5) = ln 2 ≈ 0.693. This is also the average loss of the all-zero model on any data.',
    reflection: 'Why should a model that says "99% sure" and is wrong be penalized far more than one that says "60% sure" and is wrong? Where would that matter in your work?',
  },
  {
    id: 'l08-gradient',
    title: '08.4 · The gradient: error times input, again',
    sections: ['Chain rule through the sigmoid', 'A familiar result', 'In matrix form', 'Check it numerically', 'Training loop'],
    skill: 'Derive the logistic-regression gradient and verify it with finite differences.',
    prerequisite: 'Lessons 08.1–08.3; chain rule (Lab 01) and matrix gradients (Lab 03).',
    paragraphs: [
      'For one example, the loss is `ℓ = log(1 + e^z) − y z` with `z = w·x + b`. Differentiate with respect to z: `dℓ/dz = e^z/(1 + e^z) − y = σ(z) − y = p − y`. The awkward sigmoid derivative and the logarithm cancel exactly — this is the payoff of choosing cross-entropy.',
      'Chain rule: `dz/dw_j = x_j` and `dz/db = 1`. So `∂ℓ/∂w_j = (p − y)·x_j` and `∂ℓ/∂b = p − y`. Compare least squares, where the per-example gradient was 2(ŷ − y)x: the same shape, **prediction error times input**, with the probability as the prediction.',
      'Averaged over the data: `∇_w J = (1/n) Xᵀ(p − y)` and `∂J/∂b = mean(p − y)`, where p = σ(Xw + b) is the vector of predicted probabilities. With an L2 penalty λ‖w‖², add 2λw. Shapes: `(p − y)` is `(n,)`, Xᵀ is `(features, n)`, so the gradient has one entry per weight.',
      'Check it: perturb each weight by ±ε, recompute the loss, and compare the slope with your formula. The playground\'s "Check gradients" does this for every parameter, including the quadratic features, at the current point of training.',
      'Training is Lab 01\'s loop unchanged: start at zero, compute p, compute the gradient, subtract α times it, repeat. Log loss on training and validation data, plotted over steps, tells you whether it is still learning and whether it is starting to overfit.',
    ],
    formula: '∂ℓ/∂z = p − y     ∇_w J = (1/n) Xᵀ(σ(Xw + b) − y) + 2λw     ∂J/∂b = mean(p − y)',
    experiment: 'Press "Check gradients" at step 0, after 200 steps, and with quadratic features and λ = 0.01. Does the match survive every setting?',
    question: 'One example with x = 2, y = 1 and current prediction p = 0.7. What is ∂ℓ/∂w = (p − y)·x?',
    answer: -0.6,
    misconceptions: [{ answer: -0.3, feedback: 'That is p − y alone. Multiply by the input x = 2.' }, { answer: 0.6, feedback: 'Right size, wrong sign: p − y = 0.7 − 1 is negative.' }],
    explanation: '(0.7 − 1) × 2 = −0.6. Negative: increasing w raises p toward the correct label 1, lowering the loss.',
    reflection: 'Explain, without formulas, why a misclassified point far from the boundary contributes a large gradient while a confidently correct one contributes almost none.',
  },
  {
    id: 'l08-boundary',
    title: '08.5 · Decision boundaries and feature maps',
    sections: ['Where p = 0.5', 'A line in two dimensions', 'Curved boundaries from new features', 'Separable data and exploding weights', 'Regularize'],
    skill: 'Compute and draw a logistic-regression decision boundary, and use feature maps and regularization appropriately.',
    prerequisite: 'Lessons 08.1–08.4; polynomial features and ridge from Lab 07.',
    paragraphs: [
      'At threshold 0.5 the model predicts class 1 exactly when p ≥ 0.5, i.e. when z = w·x + b ≥ 0. The **decision boundary** is the set of points where `w·x + b = 0`. With two features that is a straight line; with more, a flat **hyperplane**. The weight vector w points across it, toward class 1.',
      'For w = (1, 2), b = −4: the boundary is `x₁ + 2x₂ = 4`. It crosses the x₂ axis at x₂ = 2 and the x₁ axis at x₁ = 4. Points with x₁ + 2x₂ > 4 are predicted positive. Scaling w and b by 10 keeps the same line but makes the probabilities change more steeply across it.',
      'A ring of one class around the other cannot be separated by any line. Add features `x₁², x₂², x₁x₂`: the boundary `w·φ(x) + b = 0` is now a conic — an ellipse fits the ring. The model is still linear in its weights, so training is unchanged; only the **feature map** φ changed, as with polynomial regression in Lab 07.',
      'If the classes are perfectly separable, the likelihood keeps improving as the weights grow: scaling w up makes every correct probability closer to 1. Unregularized gradient descent never stops — ‖w‖ grows forever and predicted probabilities become overconfident. The playground shows this on "Two blobs".',
      'An L2 penalty λ‖w‖² stops the growth, giving finite weights and more honest probabilities. As in Lab 07: standardize features first, do not penalize the intercept, and choose λ by cross-validation.',
    ],
    formula: 'boundary: w·x + b = 0     with feature map φ: w·φ(x) + b = 0',
    experiment: 'On "Circle inside ring", train with linear features and record validation accuracy. Switch to quadratic features and train again. Then try "Two blobs" at λ = 0 versus λ = 0.01, watching ‖w‖.',
    question: 'For w = (1, 2) and b = −4, where does the decision boundary cross the x₂ axis (x₁ = 0)?',
    answer: 2,
    misconceptions: [{ answer: 4, feedback: 'That is where it crosses the x₁ axis. On the x₂ axis, x₁ = 0: 2x₂ − 4 = 0.' }],
    explanation: 'With x₁ = 0: 2x₂ − 4 = 0, so x₂ = 2.',
    reflection: 'Would a straight boundary be adequate for a classifier in your domain? What feature could make a curved boundary unnecessary?',
  },
  {
    id: 'l08-decision',
    title: '08.6 · A probability is not yet a decision',
    sections: ['The threshold is a choice', 'Costs decide it', 'Derive the cost-optimal threshold', 'Probabilities must be trustworthy', 'Demonstrate understanding'],
    skill: 'Choose a decision threshold from error costs and explain why it depends on calibrated probabilities.',
    prerequisite: 'Lessons 08.1–08.5; expected values (Lab 04).',
    paragraphs: [
      'The model outputs p = 0.3 that a build will fail. Should you block the release? The model cannot answer that. Converting a probability into an action requires knowing what each kind of mistake costs, which is a fact about your situation, not about the data.',
      'A **false positive** acts when the answer was "no" (blocking a good build). A **false negative** fails to act when the answer was "yes" (shipping a bad build). Accuracy counts them as equally bad. They rarely are: a missed outage may cost 50× an unnecessary review.',
      'Act when the expected cost of acting is lower than the expected cost of not acting. Acting on a case with probability p costs `(1 − p)·C_FP`; not acting costs `p·C_FN`. Act when `p·C_FN > (1 − p)·C_FP`, i.e. when `p > C_FP / (C_FP + C_FN)`. With C_FP = 1 and C_FN = 4, the threshold is 0.2, not 0.5.',
      'This rule is only as good as the probabilities. If the model says 0.3 when the true frequency is 0.1, a cost-derived threshold will act far too often. Regularization, feature choice and class imbalance all affect how trustworthy (**calibrated**) the probabilities are. Lab 09 measures and fixes calibration, and chooses thresholds with validation data.',
      'You have completed this lab when you can: derive cross-entropy from likelihood; derive and check its gradient; train logistic regression from scratch; draw its boundary; explain what regularization does on separable data; and turn a probability into a decision using costs. The Python challenge builds the full model.',
    ],
    formula: 'act if p > C_FP / (C_FP + C_FN)',
    experiment: 'Train on "Overlapping blobs", then move the threshold from 0.5 to 0.2 and to 0.8. Record how the validation confusion table changes. Which threshold would you choose if missing a class-1 case cost four times a false alarm?',
    question: 'A false positive costs 1 and a false negative costs 4. What probability threshold minimizes expected cost?',
    answer: 0.2,
    misconceptions: [{ answer: 0.8, feedback: 'You swapped the costs. The threshold is C_FP / (C_FP + C_FN) = 1 / 5.' }, { answer: 0.5, feedback: 'That threshold treats both mistakes as equally costly. Here a false negative costs four times more.' }],
    explanation: 't = C_FP/(C_FP + C_FN) = 1/5 = 0.2. Act on anything with at least a 20% chance of being positive.',
    reflection: 'Estimate the costs of false positives and false negatives for a classifier you might build. What threshold do they imply?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 4.3: logistic regression', url: 'https://www.statlearning.com/' },
  { title: 'Dive into Deep Learning · 4.1 softmax regression and cross-entropy', url: 'https://d2l.ai/chapter_linear-classification/softmax-regression.html' },
  { title: 'scikit-learn · LogisticRegression', url: 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression' },
  { title: 'SciPy · scipy.special.expit (stable sigmoid)', url: 'https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.expit.html' },
]

// Runnable cells and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
