// @vitest-environment jsdom
import React from 'react'
import { render, fireEvent, cleanup, within } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import LessonExperience from './LessonExperience'
import { lessons, sequenceByIds } from './registry'
import { defineLesson, validateSequence } from './schema'
import { choose } from './runtime'
import pascal, { selections } from './lessons/pascal'

afterEach(() => { cleanup(); vi.restoreAllMocks() })
function mount(id) {
  const lesson = lessons.find(item => item.id === id)
  const view = render(<LessonExperience lesson={lesson} />)
  const root = view.container.querySelector('section')
  return { ...view, root, query: selector => root.querySelector(selector), explanation: () => root.querySelector('.wm-explanation').textContent }
}
const input = (node, value) => fireEvent.input(node, { target: { value: String(value) } })

describe('standalone lesson contract', () => {
  it.each(lessons.map(lesson => [lesson.id, lesson.title]))('%s mounts independently: %s', id => {
    const { root, query } = mount(id)
    expect(root.querySelectorAll('.wm-panel')).toHaveLength(4)
    for (const key of ['observation','why','tryNext']) expect(query(`[data-state="${key}"]`).textContent.length).toBeGreaterThan(20)
    const ids = [...root.querySelectorAll('[id]')].map(node => node.id)
    expect(new Set(ids).size).toBe(ids.length)
    expect(root.querySelector('.wm-panel:nth-child(2)').textContent.trim().length).toBeGreaterThan(0)
  })
  it('accepts a contributor file and rejects malformed or repeated entries', () => {
    const custom = {...lessons[0], id:'new-contributor-lesson', order:42}
    expect(defineLesson(custom).schemaVersion).toBe(1)
    expect(() => defineLesson({...custom, panels:{scene:'<svg/>'}})).toThrow('panel markup')
    expect(() => defineLesson({...custom, mount:null})).toThrow('mount')
    expect(() => validateSequence([custom,custom])).toThrow('Duplicate')
    expect(sequenceByIds(['l14','l1']).map(x=>x.id)).toEqual(['l14','l1'])
    expect(() => sequenceByIds(['missing'])).toThrow('Unknown')
  })
  it('does not share state between two instances of the same lesson', () => {
    const lesson = lessons[0]
    const { container } = render(<><LessonExperience lesson={lesson}/><LessonExperience lesson={lesson}/></>)
    const [a,b] = container.querySelectorAll('section')
    fireEvent.click(a.querySelector('#ad'))
    expect(a.querySelector('#num').textContent).toBe('1')
    expect(b.querySelector('#num').textContent).toBe('0')
  })
})

describe('explanations follow the situation', () => {
  it('starts loose, keeps grouping optional, and returns to loose rocks without changing the collection', () => {
    const {query,explanation} = mount('l1')
    expect(query('#group-controls').hidden).toBe(true)
    expect(query('#record').hidden).toBe(true)
    for(let i=0;i<7;i++)fireEvent.click(query('#ad'))
    expect(query('#rocks').querySelectorAll('rect')).toHaveLength(0)
    expect(explanation()).toContain('keeping your place')
    fireEvent.click(query('#make-groups'))
    expect(query('#rocks').querySelectorAll('rect')).toHaveLength(0)
    fireEvent.change(query('#group-size'),{target:{value:'2'}})
    expect(explanation()).toContain('odd')
    fireEvent.click(query('#ad'));expect(explanation()).toContain('even')
    fireEvent.click(query('#ungroup'))
    expect(query('#num').textContent).toBe('8')
    expect(query('#rocks').querySelectorAll('rect')).toHaveLength(0)
  })
  it('times completed counting attempts and ignores repeat touches', () => {
    const {query} = mount('l1')
    for(let i=0;i<3;i++)fireEvent.click(query('#ad'))
    fireEvent.click(query('#count-start'))
    fireEvent.click(query('#rocks [aria-label="Count rock 1"]'))
    fireEvent.click(query('#rocks [aria-label="Count rock 1"]'))
    expect(query('#count-results').textContent).toBe('')
    fireEvent.keyDown(query('#rocks [aria-label="Count rock 2"]'),{key:'Enter'})
    fireEvent.click(query('#rocks [aria-label="Count rock 3"]'))
    expect(query('#count-results').textContent).toContain('Loose rocks:')
    fireEvent.click(query('#make-groups'))
    fireEvent.change(query('#group-size'),{target:{value:'2'}})
    fireEvent.click(query('#count-start'))
    fireEvent.click(query('#rocks [aria-label="Count group 1"]'))
    fireEvent.click(query('#rocks [aria-label="Count leftover rocks"]'))
    expect(query('#count-results').textContent).toContain('Groups of 2:')
    expect(query('#count-results').textContent).toContain('Loose rocks:')
  })
  it('explains equality, separation, and containment for the selected rules', () => {
    const {query,explanation} = mount('l2')
    fireEvent.change(query('#ra'),{target:{value:'even'}})
    fireEvent.change(query('#rb'),{target:{value:'divisible by 2'}})
    expect(explanation()).toContain('Different wording')
    fireEvent.change(query('#rb'),{target:{value:'odd'}})
    expect(explanation()).toContain('share no members')
    fireEvent.change(query('#rb'),{target:{value:'a multiple of 6'}})
    expect(explanation()).toContain('Belonging to the smaller collection')
  })
  it('treats debt as an obligation and explains cancellation', () => {
    const {query,explanation} = mount('l5')
    for(let i=0;i<4;i++) fireEvent.click(query('#ab'))
    expect(explanation()).toContain('Ana now owes Ben 1')
    expect(explanation()).toContain('obligation, not a coin')
    fireEvent.click(query('#ba')); expect(explanation()).toContain('nothing owed')
  })
  it('identifies arrangement properties and the pieces of a split square', () => {
    const a = mount('l9'); input(a.query('#pn'),13)
    expect(a.query('#row-choice').hidden).toBe(true)
    fireEvent.click(a.query('#try-rows'));input(a.query('#row-width'),4)
    expect(a.explanation()).toContain('last row has gaps')
    expect(a.explanation()).toContain('13 is prime')
    a.unmount()
    const b = mount('l11'); fireEvent.click(b.query('[data-a=layers]')); input(b.query('#an'),6)
    expect(b.explanation()).toContain('border contains 11')
    fireEvent.click(b.query('[data-a="split"]')); input(b.query('#as'),3)
    expect(b.explanation()).toContain('each contain 9 tiles')
    expect(b.explanation()).toContain('combined area stays the same')
  })
  it('responds to a newcomer and to connecting an actual pair', () => {
    const {query,explanation} = mount('l3')
    fireEvent.click(query('#hadd')); expect(explanation()).toContain('now 6 people and 15 possible pairs')
    let people=query('#hs').querySelectorAll('[role=button]')
    fireEvent.click(people[0]); people=query('#hs').querySelectorAll('[role=button]'); fireEvent.click(people[1])
    expect(explanation()).toContain('You connected a pair')
    fireEvent.click(query('#hall')); expect(explanation()).toContain('counts every line at both ends')
  })
  it('distinguishes outcomes from samples and responds to the latest flip', () => {
    vi.spyOn(Math,'random').mockReturnValue(0)
    const {query,explanation} = mount('l10')
    fireEvent.click(query('#cf1'))
    expect(explanation()).toContain('latest has 0 heads')
    expect(explanation()).toContain('observed counts')
    fireEvent.click(query('[data-reveal=cc]'))
    expect(explanation()).toContain('columns are not equally likely')
    input(query('#cs'),4)
    expect(explanation()).toContain('16 possible stories')
  })
  it('explains a pending peg-ball and exact route counts without promising a sample result', () => {
    vi.spyOn(window,'requestAnimationFrame').mockReturnValue(99)
    const {query,explanation} = mount('l7')
    fireEvent.click(query('#g1'))
    expect(explanation()).toContain('1 ball is travelling')
    fireEvent.click(query('#gt'))
    expect(explanation()).toContain('two parent counts')
  })
  it('explains carries and only allows meaningful reversal moves', () => {
    const a=mount('l8');fireEvent.click(a.query('#show-values'));fireEvent.click(a.query('#b1'));fireEvent.click(a.query('#b1'))
    expect(a.explanation()).toContain('carried their value')
    a.unmount()
    const b=mount('l12')
    expect(b.query('#au2').disabled).toBe(false)
    fireEvent.click(b.query('#au2'));expect(b.explanation()).toContain('one arm a dot short')
    fireEvent.click(b.query('#au1'));expect(b.explanation()).toContain('second copy of the shared corner')
    fireEvent.click(b.query('#au2'));expect(b.explanation()).toContain('Rejoin two arms')
  })
  it('updates the explanation at each clock mark and when the pieces are folded', () => {
    let callback
    vi.spyOn(performance,'now').mockReturnValue(0)
    vi.spyOn(window,'requestAnimationFrame').mockImplementation(fn=>{callback=fn;return 1})
    const {query,explanation}=mount('l4')
    fireEvent.change(query('#pg'),{target:{value:'16'}});fireEvent.click(query('#drop'))
    callback(1800);expect(explanation()).toContain('After 2 ticks')
    callback(3600);expect(explanation()).toContain('most recent tick contributed 7')
    fireEvent.click(query('#fold'));expect(explanation()).toContain('none were added or removed')
  })
  it('explains wave turning points, signs, finite gaps, and the limiting idea', () => {
    const a=mount('l13');fireEvent.click(a.query('#trace-height'));input(a.query('#ta'),90)
    expect(a.explanation()).toContain('top of the circle')
    input(a.query('#ta'),270);expect(a.explanation()).toContain('bottom of the circle')
    a.unmount()
    const b=mount('l14');input(b.query('#ct'),2);input(b.query('#ch'),4)
    expect(b.explanation()).toContain('average speed over that gap: 4.01')
    expect(b.explanation()).toContain('approximation, not the limit itself')
  })
})

describe('Pascal entries mean actual choices', () => {
  it('shows the single empty and complete selections at the two edges', () => {
    const {root,query,explanation}=mount('l6')
    fireEvent.click(query('[data-reveal=pattern-view]'))
    fireEvent.click(within(root).getByRole('button',{name:'The edges'}))
    expect(explanation()).toContain('one way to leave every object out')
    expect(query('#choice-examples').textContent).toContain('Empty selection')
    fireEvent.click(query('#choose-all'))
    expect(explanation()).toContain('one way to include every object')
    expect(query('#choice-examples').textContent).toContain('A · B · C · D')
    fireEvent.click(query('#choice-add'))
    expect(query('#choice-count').textContent).toContain('1 different selection')
    expect(query('#choice-examples').textContent).toContain('E')
  })
  it('shows the two disjoint parent groups and updates from direct object selection', () => {
    const {root,query,explanation}=mount('l6')
    fireEvent.click(query('[data-reveal=pattern-view]'))
    const entry=within(root).getByRole('button',{name:'Row 4, position 2: 6'})
    entry.focus();fireEvent.keyDown(entry,{key:'Enter'})
    expect(explanation()).toContain('3 selections leave it out; 3 include it')
    expect(query('#choice-examples').children).toHaveLength(6)
    expect(document.activeElement.getAttribute('data-r')).toBe('4')
    fireEvent.click(query('[data-object="2"]'))
    expect(query('#choice-heading').textContent).toContain('choose 3')
    expect(explanation()).toContain('counts 4 ways')
  })
  it('explains diagonals, doubling, and odd-count parity for the current state', () => {
    const {query,explanation}=mount('l6')
    fireEvent.click(query('[data-reveal=pattern-view]'))
    fireEvent.click(query('[data-p="d1"]'));expect(explanation()).toContain('new single-object selection')
    fireEvent.click(query('[data-p="d2"]'));expect(explanation()).toContain('same growth as handshakes')
    fireEvent.click(query('[data-p="sum"]'));expect(explanation()).toContain('16 possibilities')
    fireEvent.click(query('[data-p="odd"]'));expect(explanation()).toContain('one odd parent and one even parent')
    input(query('#prow'),16)
    expect(query('#choice-examples').children.length).toBeLessThanOrEqual(12)
  })
  it('enumeration agrees with the exact binomial count, including empty and full selections', () => {
    for(let n=0;n<=8;n++)for(let k=0;k<=n;k++){
      const actual=selections(n,k,300)
      expect(actual).toHaveLength(choose(n,k))
      expect(new Set(actual.map(x=>x.join(','))).size).toBe(actual.length)
      for(const picked of actual)expect(picked).toHaveLength(k)
    }
    expect(selections(15,7)).toHaveLength(12)
    expect(pascal.id).toBe('l6')
  })
})


it('regroups the same collection, counts by groups, and distinguishes remainder from group count', () => {
 const {query,explanation} = mount('l1')
 fireEvent.click(query('#make-groups'))
 fireEvent.change(query('#group-size'),{target:{value:'5'}})
 for(let i=0;i<5;i++)fireEvent.click(query('#add-group'))
 fireEvent.click(query('#ad'))
 expect(query('#num').textContent).toBe('26')
 expect(query('#group-summary').textContent).toContain('5 complete groups of 5 · 1 left over')
 expect(query('#skip-count').textContent).toContain('5 → 10 → 15 → 20 → 25')
 expect(explanation()).toContain('26 mod 5 = 1')
 fireEvent.change(query('#group-size'),{target:{value:'3'}})
 expect(query('#num').textContent).toBe('26')
 expect(query('#group-summary').textContent).toContain('8 complete groups of 3 · 2 left over')
 fireEvent.change(query('#group-size'),{target:{value:'2'}})
 expect(query('#group-summary').textContent).toContain('13 complete groups of 2 · 0 left over')
 fireEvent.change(query('#group-size'),{target:{value:'10'}})
 expect(query('#group-summary').textContent).toContain('2 complete groups of 10 · 6 left over')
})
