export const lessons = [
  {
    id: 'l52-overfit',
    title: '52.1 · How big networks overfit',
    sections: ['More parameters than examples', 'Memorizing noise', 'Watch the validation curve', 'Early stopping', 'Put it into practice'],
    skill: 'Diagnose overfitting in neural networks from training and validation curves and apply early stopping.',
    prerequisite: 'Neural networks, backpropagation and optimizers (Labs 20–23); overfitting (Lab 07); double descent (Lab 47).',
    paragraphs: [
      'The playground’s network has 2,594 parameters and sees 80 training points, 8 of them mislabelled. It has more than enough capacity to fit every point exactly — including the mislabelled ones.',
      'That is what happens without regularization: training accuracy reaches 100%, the decision regions grow little islands around the mislabelled points, and validation accuracy stops at about 85%. The network learned the noise.',
      'The validation loss tells the story first. It falls while the network learns the real spiral, reaches its minimum (here around epoch 90), then climbs as memorization takes over — even while training loss keeps falling.',
      '**Early stopping** keeps the parameters from the epoch with the lowest validation loss. It is free, always worth doing, and acts like a regularizer: the network simply has not had time to reach complex solutions. Use a separate validation set (not the test set, Lab 06) and some patience before stopping.',
      'Procedure: always plot training and validation loss per epoch; if they diverge, add regularization or data; keep the best checkpoint; and report the test result of that checkpoint only once.',
    ],
    formula: 'stop at argmin_epoch  L_validation(epoch)',
    derivation: {
      title: 'Counting parameters',
      steps: [
        { prompt: 'A dense layer from 48 inputs to 48 outputs has how many parameters (weights plus biases)?', number: 48 * 48 + 48, show: '`48 × 48 + 48 = 2,352`' },
        { prompt: 'Write the parameter count of a dense layer with n inputs and m outputs.', answer: 'n*m + m', show: '`n·m + m`', vars: { n: [1, 100], m: [1, 100] } },
        { prompt: 'Parameters per training example for 2,594 parameters and 80 examples? (One decimal.)', number: 2594 / 80, tolerance: 0.05, show: '`≈ 32.4`' },
      ],
      result: 'With over 30 parameters per example, the network can fit almost anything — regularization decides what it actually fits.',
    },
    experiment: 'With all regularization off, find the epoch where validation loss is lowest, then look at the decision regions. Where are the islands?',
    question: 'A network’s validation loss is 0.40, 0.33, 0.35, 0.52 at epochs 50, 90, 150 and 400. Which epoch would early stopping keep?',
    answer: 90,
    explanation: 'The epoch with the lowest validation loss: 90.',
    reflection: 'What would you log during training so that early stopping is possible after the fact?',
  },
  {
    id: 'l52-dropout',
    title: '52.2 · Dropout and weight decay',
    sections: ['Dropout', 'Inverted dropout', 'An ensemble in one network', 'Weight decay', 'L2 versus decoupled decay'],
    skill: 'Explain how dropout and weight decay regularize and use them correctly.',
    prerequisite: 'Lesson 52.1; ridge regression (Lab 07); ensembles (Lab 13); Adam (Lab 22).',
    paragraphs: [
      '**Dropout** sets each hidden unit to zero with probability p on every training step. No unit can rely on a particular other unit being present, so the network cannot build fragile, memorizing co-adaptations.',
      'To keep expected activations the same, kept units are scaled by 1/(1 − p) during training (**inverted dropout**); at evaluation nothing is dropped and nothing is scaled. Forgetting to switch to evaluation mode is a classic bug (model.eval() in PyTorch, Lab 23).',
      'Each step trains a different thinned sub-network, all sharing weights; prediction with the full network approximates averaging that huge ensemble (Lab 13). In the playground, dropout 0.3 lifts validation accuracy from about 85% to about 93%.',
      '**Weight decay** shrinks every weight toward zero a little each step, favouring small weights and smoother functions — the neural-network version of ridge regression (Lab 07) and a Gaussian prior (Lab 41).',
      'With Adam, adding λ‖w‖² to the loss (L2 regularization) is not the same as shrinking weights directly, because Adam rescales gradients per parameter. **Decoupled** weight decay (AdamW) applies w ← w − lr·λ·w separately and is the modern default. Biases and normalization parameters are usually not decayed.',
    ],
    formula: 'dropout: h ← h·m/(1 − p), m ~ Bernoulli(1 − p)     AdamW: w ← w − lr·(Adam step + λw)',
    derivation: {
      title: 'Why dropout rescales',
      steps: [
        { prompt: 'A unit with activation a is kept with probability 1 − p and scaled by 1/(1 − p). Write its expected value.', answer: 'a', show: '`(1 − p)·a/(1 − p) = a`', vars: { a: [-2, 2], p: [0, 0.9] } },
        { prompt: 'With p = 0.5, what does a kept activation of 3 become during training?', number: 6, show: '`3/(1 − 0.5) = 6`' },
      ],
      result: 'Rescaling during training means evaluation needs no change — just stop dropping.',
    },
    experiment: 'Compare dropout 0.3 alone, weight decay 1 alone, and both together. Which changes the decision regions most?',
    question: 'With AdamW, learning rate 0.01 and weight decay 0.5, by what fraction does decoupled decay shrink a weight in one step (ignoring the gradient)?',
    answer: 0.005, tolerance: 1e-9,
    explanation: 'lr × λ = 0.01 × 0.5 = 0.005: each step multiplies the weight by 0.995.',
    reflection: 'Why should you not apply weight decay to batch-norm scale parameters?',
  },
  {
    id: 'l52-augment',
    title: '52.3 · Data augmentation',
    sections: ['More data, for free', 'Encode what should not matter', 'Input noise as a regularizer', 'Augmentations that lie', 'Combining regularizers'],
    skill: 'Design label-preserving augmentations and combine regularizers sensibly.',
    prerequisite: 'Lessons 52.1–52.2; convolution and augmentation (Lab 24).',
    paragraphs: [
      'Often the best regularizer is more data. **Augmentation** creates new training examples by transforming existing ones in ways that do not change the label.',
      'Each augmentation encodes an invariance you believe in: a cat photo flipped left–right is still a cat; a sentence with a synonym is still positive; a sensor reading with tiny noise is still the same state. The model learns to ignore exactly those variations.',
      'Adding small Gaussian noise to inputs — **input jitter** — turns each point into a small cloud and discourages boundaries that bend sharply around individual points. For small noise it is equivalent to a smoothness penalty. In the playground, jitter 0.15 reaches about 93% validation accuracy.',
      'Augmentations must preserve labels. Rotating a “6” by 180° makes a “9”; flipping medical images can move the heart to the wrong side; cropping can remove the object. A lying augmentation adds label noise instead of removing overfitting.',
      'Regularizers stack but interact: dropout, decay, augmentation and early stopping together reached the best validation accuracy here, but each extra one needs tuning. Add one at a time, and compare on the same validation set with the same seeds (Lab 27).',
    ],
    formula: 'augmented example: (T(x), y) with T label-preserving     jitter: x + ε, ε ~ N(0, σ²I)',
    derivation: {
      title: 'How many examples does augmentation add?',
      steps: [
        { prompt: 'Each of 80 examples is jittered freshly every epoch for 400 epochs. How many distinct noisy inputs does the network see?', number: 32000, show: '`80 × 400 = 32,000`' },
        { prompt: 'With 4 flips × 3 crops per image, how many variants of each image?', number: 12, show: '`12`' },
      ],
      result: 'Augmented examples are correlated with the originals — they help, but less than truly new data.',
    },
    experiment: 'Set jitter to 0.25. Does it still help, or does it blur the spiral too much? Where is the sweet spot?',
    question: 'A digit classifier is augmented with random rotations up to 180°. Which pair of digits will it most likely confuse? Answer with the sum of the two digits.',
    answer: 15,
    explanation: 'A 6 rotated by 180° looks like a 9: 6 + 9 = 15. That augmentation is not label-preserving.',
    reflection: 'Which transformations of your data truly leave the label unchanged?',
  },
  {
    id: 'l52-norm',
    title: '52.4 · Normalization layers',
    sections: ['Keeping activations in range', 'Batch normalization', 'Train versus evaluation mode', 'Layer normalization', 'Why they help'],
    skill: 'Explain batch and layer normalization, including their training and evaluation behaviour.',
    prerequisite: 'Lessons 52.1–52.3; standardization (Lab 03); initialization (Lab 21).',
    paragraphs: [
      'As weights change during training, the distribution of each layer’s inputs shifts, and in deep networks activations can drift into saturated or exploding ranges.',
      '**Batch normalization** standardizes each feature using the mean and variance over the current mini-batch, then applies a learned scale γ and shift β: y = γ·(x − μ_B)/σ_B + β. The layer can still represent any scale, but the optimization landscape becomes much smoother.',
      'At evaluation there may be only one example, so batch norm uses running averages of the training statistics instead. Mismatches between the two modes — tiny batches, shifted data, forgetting eval mode — are a common source of bugs. Batch statistics also couple examples in a batch, which complicates small-batch and sequence models.',
      '**Layer normalization** standardizes across the features of each example separately, so it behaves the same in training and evaluation and does not depend on batch size. Transformers use it (Lab 26).',
      'In the playground at depth 16, adding batch norm to a plain tanh network cuts the training loss after 100 steps from about 0.26 to about 0.03. Why exactly normalization helps is still debated — smoother loss surfaces and better-conditioned gradients are the leading explanations.',
    ],
    formula: 'BN: y = γ (x − μ_batch)/√(σ²_batch + ε) + β     LN: statistics over features of one example',
    derivation: {
      title: 'Normalize one feature over a batch',
      intro: 'A feature takes values 1, 3 and 5 in a batch of three; γ = 2, β = 0.5 (ignore ε).',
      steps: [
        { prompt: 'Batch mean?', number: 3, show: '`3`' },
        { prompt: 'Batch standard deviation (divide by 3)? (Four decimals.)', number: Math.sqrt(8 / 3), tolerance: 1e-4, show: '`√(8/3) ≈ 1.6330`' },
        { prompt: 'Output for the value 5? (Four decimals.)', number: 2 * 2 / Math.sqrt(8 / 3) + 0.5, tolerance: 1e-4, show: '`2 × 1.2247 + 0.5 ≈ 2.9495`' },
      ],
      result: 'After normalization the scale is whatever γ says — learned, not inherited from earlier layers.',
    },
    experiment: 'In the depth view at depth 16, compare the gradient-norm bars for the plain tanh network and the batch-norm network. Then train all five.',
    question: 'A model with batch norm performs well in training but poorly when you predict one example at a time. What is the most likely mistake?',
    choices: [
      { text: 'The learning rate is too high', why: 'That would hurt training too.' },
      { text: 'The model is still in training mode', why: 'Batch norm then normalizes each lone example by its own statistics. Evaluation mode uses the running averages.' },
      { text: 'Too little dropout', why: 'The symptom is specific to batch size one, which points at batch statistics.' },
    ],
    answer: 1,
    explanation: 'In training mode, batch norm normalizes a single example by its own statistics (a batch of one), which destroys the signal. Switch to evaluation mode to use the running averages.',
    reflection: 'For a model you serve one request at a time, which normalization would you choose?',
  },
  {
    id: 'l52-residual',
    title: '52.5 · Residual connections and very deep networks',
    sections: ['The degradation problem', 'y = x + f(x)', 'Gradients through the identity', 'Transformers are residual networks', 'Demonstrate understanding'],
    skill: 'Explain why residual connections make very deep networks trainable.',
    prerequisite: 'Lessons 52.1–52.4; backpropagation (Lab 20).',
    paragraphs: [
      'Deeper networks can represent more, yet before 2015 simply stacking layers often made training error **worse** — not overfitting, but optimization failure. Gradients passing back through many layers shrink or explode (Lab 22), and the network cannot even learn the identity function easily.',
      'A **residual block** computes y = x + f(x): the layers learn only a correction f to the identity. If a block is not useful, f can stay near zero and the signal passes through unchanged.',
      'Backpropagation through y = x + f(x) gives ∂L/∂x = ∂L/∂y + ∂L/∂y·f′(x): the first term carries the gradient straight back to early layers, whatever f does. In the playground at depth 16, the residual tanh network drives training loss to about 0.01 in 100 steps while the plain one is still near 0.26.',
      'Every transformer block (Lab 26) wraps attention and the feed-forward layer in residual connections with layer normalization. Modern very deep networks — ResNets with hundreds of layers, language models with dozens of blocks — are only trainable because of this.',
      'You have completed this lab when you can: read overfitting from training and validation curves and use early stopping; explain and correctly use dropout and (decoupled) weight decay; design label-preserving augmentations; explain batch and layer normalization and their modes; and explain why residual connections make depth trainable. The Python challenge implements dropout, batch normalization and a residual block with their gradients.',
    ],
    formula: 'y = x + f(x)     ∂L/∂x = ∂L/∂y · (I + ∂f/∂x)',
    derivation: {
      title: 'Gradients through a chain of blocks',
      intro: 'Scalar blocks. Plain: each multiplies the gradient by 0.5. Residual: each multiplies it by 1 + 0.5·s, with small s = −0.1 (so the factor is 0.95).',
      steps: [
        { prompt: 'Plain network, 16 blocks: what fraction of the gradient reaches the first block? (Scientific notation fine, six decimals.)', number: 0.5 ** 16, tolerance: 1e-7, show: '`0.5¹⁶ ≈ 0.0000153`' },
        { prompt: 'Residual network, 16 blocks with factor 0.95 each? (Four decimals.)', number: 0.95 ** 16, tolerance: 1e-4, show: '`0.95¹⁶ ≈ 0.4401`' },
      ],
      result: 'The identity path keeps the product of factors near 1 instead of shrinking it exponentially.',
    },
    experiment: 'In the depth view, go from depth 2 to 16 and train all five architectures at each depth. At which depth does the plain network start to fall behind?',
    question: 'In a residual block y = x + f(x), if the best thing a block can do is nothing, what should f output?',
    answer: 0,
    explanation: 'f(x) = 0 makes the block the identity — easy to learn by keeping f’s weights small.',
    reflection: 'Explain to a classmate why adding more layers can make a plain network’s training error worse.',
  },
]

export const sources = [
  { title: 'Srivastava et al. (2014) · Dropout: a simple way to prevent neural networks from overfitting', url: 'https://jmlr.org/papers/v15/srivastava14a.html' },
  { title: 'Ioffe & Szegedy (2015) · Batch normalization', url: 'https://arxiv.org/abs/1502.03167' },
  { title: 'He et al. (2016) · Deep residual learning for image recognition', url: 'https://arxiv.org/abs/1512.03385' },
  { title: 'Loshchilov & Hutter (2019) · Decoupled weight decay regularization (AdamW)', url: 'https://arxiv.org/abs/1711.05101' },
]
