// Lesson order for Lab 09: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l09-confusion': [
    { p: 0 },
    { figure: 'ConfusionAtThreshold', caption: '1,000 simulated services, 10% with incidents. Move the threshold and watch the four counts.' },
    { cell: 0 },
    { p: 1 },
    { cell: 1 },
    { p: 2 },
    { predict: { prompt: 'A system catches 45 incidents and misses 15. What is its recall, TP/(TP + FN)?', answer: 0.75, tolerance: 0.001, explain: '45/(45 + 15) = 0.75.' } },
    { cell: 2 },
    { cell: 3 },
    { p: 3 },
    { figure: 'ScoreStrips', caption: 'Scores of incidents (orange) and healthy services (blue). The threshold splits both.' },
    { cell: 4 },
    { p: 4 },
    { math: true },
  ],
  'l09-precision': [
    { p: 0 }, { p: 1 },
    { predict: { prompt: 'An alert system raises 100 alerts: 40 real, 60 false. What is its precision?', answer: 0.4, tolerance: 0.001, explain: '40/(40 + 60) = 0.4: most pages are false alarms.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'PrecisionRecallSlider', caption: 'Precision, recall and F1 as the threshold moves.' },
    { cell: 1 },
    { p: 3 },
    { figure: 'F1VersusMean', caption: 'F1 against the ordinary average of precision and recall.' },
    { predict: { prompt: 'Precision 0.5 and recall 1. What is F1? (Three decimals.)', answer: 0.667, tolerance: 0.001, explain: '2 × 0.5 × 1 / 1.5 = 0.667 — below the plain average 0.75.' } },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l09-roc': [
    { p: 0 },
    { figure: 'RocBuilder', caption: 'Ten cases sorted by score. Lower the threshold one case at a time.' },
    { p: 1 }, { p: 2 },
    { cell: 0 },
    { figure: 'AucPairs', caption: 'AUC as the share of positive–negative pairs ranked correctly.' },
    { predict: { prompt: 'Positives score 0.7 and 0.6; negatives score 0.8 and 0.1. What is the AUC?', answer: 0.5, tolerance: 0.001, explain: 'Pairs: 0.7 vs 0.8 ✗, 0.7 vs 0.1 ✓, 0.6 vs 0.8 ✗, 0.6 vs 0.1 ✓ — 2 of 4.' } },
    { cell: 1 },
    { p: 3 },
    { figure: 'RankingOnly', caption: 'AUC measures ranking only.' },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l09-imbalance': [
    { p: 0 },
    { figure: 'PrevalencePrecision', caption: 'The same detector at different prevalences: true and false alerts per 1,000 cases.' },
    { predict: { prompt: 'TPR 0.9, FPR 0.05, prevalence 10%. What is the precision? (Three decimals.)', answer: 0.667, tolerance: 0.001, explain: '0.09/(0.09 + 0.045) = 0.667.' } },
    { cell: 0 },
    { p: 1 }, { p: 2 }, { p: 3 },
    { cell: 1 },
    { figure: 'RocVersusPr', caption: 'ROC (left) and precision–recall (right) for one model as incidents become rare.' },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l09-cost': [
    { p: 0 },
    { predict: { prompt: '1,000 cases: 30 false alarms (cost 1 each) and 2 misses (cost 10 each). What is the expected cost per case?', answer: 0.05, tolerance: 0.0001, explain: '(30 × 1 + 2 × 10)/1000 = 50/1000 = 0.05.' } },
    { cell: 0 },
    { p: 1 },
    { figure: 'CostCurveFig', caption: 'Expected cost per case against the threshold, with the calibrated-probability rule dashed.' },
    { cell: 1 },
    { p: 2 },
    { cell: 2 },
    { p: 3 }, { p: 4 },
    { figure: 'PrecisionAtK', caption: 'A fixed investigation budget: alert on the top k scores.' },
    { math: true },
  ],
  'l09-calibration': [
    { p: 0 }, { p: 1 },
    { figure: 'ReliabilityDiagram', caption: 'Predicted probability against observed frequency, bin by bin. Distort the model and watch the curve leave the diagonal.' },
    { p: 2 },
    { predict: { prompt: 'Predictions 0.6 and 0.1 for outcomes 1 and 0. What is the Brier score?', answer: 0.085, tolerance: 0.0001, explain: '((0.4)² + (0.1)²)/2 = (0.16 + 0.01)/2 = 0.085.' } },
    { cell: 0 },
    { cell: 1 },
    { p: 3 },
    { figure: 'PlattFix', caption: 'An overconfident model before and after Platt scaling.' },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
}
