export const lessons = [
  {
    id: 'l09-confusion',
    title: '09.1 · The confusion matrix',
    sections: ['Four kinds of outcome', 'Accuracy hides the split', 'Rates within each class', 'One matrix per threshold', 'Put it into practice'],
    skill: 'Build a confusion matrix at a threshold and compute accuracy, true-positive rate and false-positive rate from it.',
    prerequisite: 'Lab 08 (probabilities and thresholds); conditional probability (Lab 04).',
    paragraphs: [
      'An alert system watches 1,000 services; 100 have real incidents today. At threshold 0.5 it raises 90 alerts: 70 on real incidents, 20 false alarms. It misses 30 incidents and stays quiet on 880 healthy services. Those four counts — **true positives** (70), **false positives** (20), **false negatives** (30), **true negatives** (880) — are the **confusion matrix**.',
      '**Accuracy** is the fraction correct: (70 + 880)/1000 = 0.95. It sounds excellent, but "never alert" would score 0.90 while catching nothing. When classes are unbalanced, accuracy is dominated by the large class and says little about the one you care about.',
      'Compute rates within each true class instead. The **true-positive rate** (recall, sensitivity) is TP/(TP + FN) = 70/100 = 0.7: the fraction of real incidents caught. The **false-positive rate** is FP/(FP + TN) = 20/900 ≈ 0.022: the fraction of healthy services that raised an alarm. Each is a conditional probability: P(alert | incident) and P(alert | healthy).',
      'Every threshold gives a different matrix from the same scores. Lower the threshold and TP and FP rise together; raise it and both fall. There is no "the" confusion matrix of a model — only the matrix of a model **at a threshold**.',
      'Procedure: always report the four counts with the threshold used and the class prevalence; then compute whichever rates the decision needs. Counts let a reader recompute any metric; a single percentage does not.',
    ],
    formula: 'accuracy = (TP + TN)/n     TPR = TP/(TP + FN)     FPR = FP/(FP + TN)',
    experiment: 'In "Threshold, confusion & cost", set prevalence to 1% and slide the threshold to 0.99. Accuracy is high — why? How many incidents were caught?',
    question: 'TP = 70, FP = 20, FN = 30, TN = 880. What is the accuracy? (Decimal.)',
    answer: 0.95,
    explanation: '(70 + 880)/1000 = 0.95. The trivial "never alert" rule scores 0.90 on the same data.',
    reflection: 'For a classifier you care about, which of the four cells is most expensive? Which metric would you watch first?',
  },
  {
    id: 'l09-precision',
    title: '09.2 · Precision, recall and F1',
    sections: ['Two questions about alerts', 'Precision', 'The trade-off', 'F1 and when not to use it', 'Report both'],
    skill: 'Compute precision, recall and F1 and explain which one a given decision depends on.',
    prerequisite: 'Lesson 09.1.',
    paragraphs: [
      'An on-call engineer asks: "When the system alerts, how often is it real?" A manager asks: "Of all real incidents, how many did the system catch?" These are different questions with different denominators, and they often move in opposite directions.',
      '**Precision** = TP/(TP + FP): among alerts, the fraction that are real — here 70/90 ≈ 0.78. **Recall** = TP/(TP + FN): among real incidents, the fraction alerted — 0.70. Precision is about the cost of acting on alerts (wasted pages, alert fatigue); recall is about the cost of missing cases.',
      'Lowering the threshold catches more incidents (recall ↑) but admits more false alarms (precision usually ↓). Raising it does the reverse. No threshold maximizes both unless the model separates the classes perfectly. Choosing one is choosing a point on that trade-off.',
      '**F1** is the harmonic mean `2PR/(P + R)`: high only when both are high. It is a convenient single number when both errors matter about equally, but it ignores true negatives and silently assumes a particular trade-off. When real costs are known, optimize expected cost (Lesson 09.5) instead.',
      'Report precision and recall together, with the threshold and prevalence. "95% precision" at 5% recall and "95% precision" at 80% recall describe very different systems.',
    ],
    formula: 'precision = TP/(TP + FP)     recall = TP/(TP + FN)     F1 = 2PR/(P + R)',
    experiment: 'Slide the threshold from 0.1 to 0.9 at 10% prevalence. Write down precision and recall at 0.2, 0.5 and 0.8. Which threshold would you give an on-call engineer who is paged for every alert?',
    question: 'An alert system has TP = 30 and FP = 10. What is its precision? (Decimal.)',
    answer: 0.75,
    explanation: '30/(30 + 10) = 0.75: three of every four alerts are real.',
    reflection: 'In your domain, is it worse to raise a false alarm or to miss a case? Which of precision or recall should drive your threshold?',
  },
  {
    id: 'l09-roc',
    title: '09.3 · ROC curves and AUC',
    sections: ['Sweep every threshold', 'The ROC curve', 'AUC as a ranking probability', 'What AUC ignores', 'Using ROC well'],
    skill: 'Construct an ROC curve, compute AUC, and interpret AUC as a ranking probability.',
    prerequisite: 'Lessons 09.1–09.2.',
    paragraphs: [
      'Instead of one threshold, sort all cases by score and lower the threshold one case at a time. Each step adds one case to the "alert" side: a positive moves the true-positive rate up; a negative moves the false-positive rate right. Plotting TPR against FPR over all thresholds gives the **ROC curve** (receiver operating characteristic).',
      'The curve starts at (0, 0) — alert on nothing — and ends at (1, 1) — alert on everything. A useless model that ranks randomly follows the diagonal. A perfect model goes straight up to (0, 1) and then across. Better models bow toward the top-left corner.',
      'The **area under the curve** (AUC) has a clean meaning: the probability that a randomly chosen positive gets a higher score than a randomly chosen negative. With positives scored 0.9 and 0.4 and negatives 0.6 and 0.2, three of the four positive–negative pairs are ranked correctly: AUC = 0.75. The area is computed by the trapezoid rule over the curve\'s points.',
      'AUC measures **ranking** only. Multiply every score by 0.1 and AUC is unchanged — but every probability is now wrong. AUC also averages over thresholds you would never use, and because TPR and FPR are each computed within one class, it hardly reacts to prevalence. For rare events it can look excellent while precision is terrible.',
      'Use ROC to compare how well models separate classes; then choose an operating point on the curve using costs, and check calibration separately.',
    ],
    formula: 'ROC: (FPR(t), TPR(t)) for all t     AUC = P(score⁺ > score⁻)',
    experiment: 'In the curves view, lower separation d′ toward 0.2 and watch the ROC curve approach the diagonal. Then set d′ = 2 and change prevalence from 50% to 0.5%: how much does AUC move?',
    question: 'Positives have scores 0.9 and 0.4; negatives have 0.6 and 0.2. What is the AUC?',
    answer: 0.75,
    explanation: 'Pairs (positive, negative): (0.9, 0.6) ✓, (0.9, 0.2) ✓, (0.4, 0.6) ✗, (0.4, 0.2) ✓. Three of four correct: 0.75.',
    reflection: 'Why can two models with the same AUC be very different for your use case? Describe a threshold region where one could be better.',
  },
  {
    id: 'l09-imbalance',
    title: '09.4 · Imbalance and precision–recall curves',
    sections: ['Rare positives change everything', 'The same model, different precision', 'The precision–recall curve', 'Average precision', 'Resampling is not a fix for evaluation'],
    skill: 'Explain how prevalence affects precision, and evaluate rare-event classifiers with precision–recall curves.',
    prerequisite: 'Lessons 09.1–09.3; Bayes’ rule (Lab 04).',
    paragraphs: [
      'Keep a model\'s TPR at 0.9 and FPR at 0.05 and change only how common incidents are. At 50% prevalence, precision is 0.9·0.5/(0.9·0.5 + 0.05·0.5) ≈ 0.95. At 1% prevalence it falls to 0.009/(0.009 + 0.0495) ≈ 0.15. This is exactly Bayes\' rule from Lab 04: precision is P(incident | alert), and it depends on the prior.',
      'A classifier is not "85% precise" in general; it is 85% precise **at a prevalence**. A model validated on a balanced sample will disappoint in production if real incidents are rare. Evaluate on data with the real-world class mix, or reweight to it.',
      'The **precision–recall curve** plots precision against recall across thresholds. A random model sits at a horizontal line at the prevalence — 1% for rare incidents — so the achievable area depends strongly on the class mix, making weak models on rare events visible.',
      '**Average precision** summarizes the PR curve as a sum over thresholds of (increase in recall) × (precision). Compare it with the prevalence baseline. The playground shows ROC AUC staying high while average precision collapses as incidents become rare.',
      'Oversampling the rare class or weighting it more can help a model **learn**; it does not change what evaluation should report. Evaluate on untouched data with the real prevalence, and if you trained with reweighting, recalibrate probabilities afterwards (Lesson 09.6).',
    ],
    formula: 'precision = TPR·π / (TPR·π + FPR·(1 − π))     PR baseline = π',
    experiment: 'In the curves view, set d′ = 2 and sweep prevalence from 50% to 0.5%. Record ROC AUC and average precision at each end.',
    question: 'TPR = 0.9, FPR = 0.05, prevalence π = 1%. What is the precision? (Three decimals.)',
    answer: 0.1538, tolerance: 0.0006,
    explanation: '0.009/(0.009 + 0.0495) = 0.009/0.0585 ≈ 0.154. Five of six alerts are false, despite a 5% false-positive rate.',
    reflection: 'What is the real prevalence of the event you want to predict? Is your evaluation data representative of it?',
  },
  {
    id: 'l09-cost',
    title: '09.5 · Choosing a threshold from costs',
    sections: ['Put a price on each error', 'Expected cost per case', 'Theory and practice', 'Choose on validation, report on test', 'Beyond two costs'],
    skill: 'Choose a threshold that minimizes expected cost on validation data and justify it.',
    prerequisite: 'Lessons 09.1–09.4; the cost-based threshold from Lab 08.',
    paragraphs: [
      'Suppose each false alarm costs 1 unit of engineer time and each missed incident costs 10. For any threshold, the **expected cost per case** is `(FP·C_FP + FN·C_FN)/n`. At the threshold from Lesson 09.1: (20·1 + 30·10)/1000 = 0.32. Lower thresholds trade misses for false alarms; the best one minimizes this total.',
      'Plot expected cost against threshold (the playground does) and pick the minimum. With calibrated probabilities, theory predicts it: act when `p > C_FP/(C_FP + C_FN)` — here 1/11 ≈ 0.09. When the empirical minimum and the theoretical line disagree, the probabilities are miscalibrated.',
      'The empirical minimum depends on the data used to find it. Choose the threshold on validation data (or cross-validation), freeze it, and report cost, precision and recall at that frozen threshold on the test set. Choosing the threshold on test data is the winner\'s curse from Lab 06 in a new form.',
      'Real costs are rarely exact. Show the cost curve for a range of plausible cost ratios; if the best threshold is stable across them, the decision is robust. If it moves a lot, make the uncertainty explicit to whoever owns the decision.',
      'Some settings have capacity limits instead of costs — the team can investigate 50 alerts a day. Then the threshold is set by rank: alert on the top 50 scores, and report precision at that volume ("precision@k").',
    ],
    formula: 'cost(t) = [FP(t)·C_FP + FN(t)·C_FN] / n     calibrated optimum: t* = C_FP/(C_FP + C_FN)',
    experiment: 'Set costs 1 and 10. Compare the empirical minimum with the dashed theory line. Then distort calibration in the Calibration view (distortion 2.5) and return: what happened to the agreement?',
    question: 'At some threshold there are 20 false positives and 5 false negatives. A false positive costs 1 and a false negative costs 10. What is the total cost?',
    answer: 70,
    explanation: '20 × 1 + 5 × 10 = 70. Divide by the number of cases to get the expected cost per case.',
    reflection: 'Estimate C_FP and C_FN for a decision in your work. Compute the implied threshold. How sensitive is it to a factor-of-two error in either cost?',
  },
  {
    id: 'l09-calibration',
    title: '09.6 · Calibration: can you trust the probability?',
    sections: ['A testable promise', 'The reliability diagram', 'Scores that summarize calibration', 'Recalibration', 'Demonstrate understanding'],
    skill: 'Measure calibration with a reliability diagram and Brier score, and recalibrate with Platt scaling on held-out data.',
    prerequisite: 'Lessons 09.1–09.5; logistic regression (Lab 08).',
    paragraphs: [
      'A calibrated model keeps its word: among all cases it scores near 0.8, about 80% are positive. Without calibration, cost-based thresholds, risk estimates and "70% chance of failure" messages are all wrong — even if the model ranks cases perfectly.',
      'Bin predictions by probability (0–0.1, 0.1–0.2, …). For each bin, plot the mean predicted probability against the observed fraction of positives. A calibrated model lies on the diagonal. Points below the diagonal at high probabilities mean **overconfidence** (says 0.9, happens 0.7); above it, **underconfidence**.',
      'The **Brier score** is the mean squared error of probabilities: `mean((p − y)²)`. For predictions 0.8 and 0.3 on outcomes 1 and 0: ((0.2)² + (0.3)²)/2 = 0.065. It rewards both sharpness and calibration. **Expected calibration error** (ECE) is the average gap between predicted and observed in each bin, weighted by bin size.',
      'Models trained with heavy regularization, class reweighting, or on shifted data are often miscalibrated. **Platt scaling** fits a one-feature logistic regression on held-out data: `p′ = σ(a·logit(p) + b)`. **Isotonic regression** fits any increasing mapping instead. Both preserve the ranking — AUC is unchanged — and fix the probabilities. Fit them on data the model did not train on.',
      'You have completed this lab when you can: compute the confusion matrix and every metric from it; explain why accuracy and ROC AUC can mislead on rare events; choose a threshold from costs on validation data; and diagnose and fix calibration. The Python challenge implements these tools from scratch.',
    ],
    formula: 'Brier = mean((p − y)²)     ECE = Σ_bins (n_b/n)·|mean p_b − mean y_b|     p′ = σ(a·logit p + b)',
    experiment: 'In the Calibration view, set distortion 2.5: note ECE, Brier and AUC. Turn on Platt scaling: which numbers change, and which stay the same? Why?',
    question: 'Predictions 0.8 and 0.3; outcomes 1 and 0. What is the Brier score?',
    answer: 0.065,
    explanation: '((1 − 0.8)² + (0 − 0.3)²)/2 = (0.04 + 0.09)/2 = 0.065.',
    reflection: 'Where would miscalibrated probabilities cause harm in your work even if the model ranked cases correctly?',
  },
]

export const sources = [
  { title: 'scikit-learn · Metrics and scoring: classification metrics', url: 'https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics' },
  { title: 'scikit-learn · Probability calibration', url: 'https://scikit-learn.org/stable/modules/calibration.html' },
  { title: 'Saito & Rehmsmeier (2015) · The precision–recall plot is more informative than ROC on imbalanced data', url: 'https://doi.org/10.1371/journal.pone.0118432' },
  { title: 'Fawcett (2006) · An introduction to ROC analysis', url: 'https://doi.org/10.1016/j.patrec.2005.10.010' },
]
