// Lesson order for Lab 20: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l20-graph': [
    { p: 0 }, { p: 1 },
    { figure: 'ForwardGraph', caption: 'The graph of L = (a·b + c)². Move a, b and c; every node recomputes from its inputs.' },
    { p: 2 },
    { cell: 0 },
    { predict: { prompt: 'With a = 1, b = 5 and c = −2, what is L = (a·b + c)²?', answer: 9, explain: 'd = a·b = 5, e = d + c = 3, L = e² = 9.', misconceptions: [{ answer: 49, feedback: 'That is (a·b − c)². The sum node adds c = −2: 5 + (−2) = 3.' }] } },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l20-local': [
    { p: 0 }, { p: 1 },
    { figure: 'BackwardSteps', caption: 'Backpropagation one node at a time on L = (a·b + c)² with a = 2, b = −3, c = 10.' },
    { predict: { prompt: 'Same graph and values. What is ∂L/∂b?', answer: 16, explain: 'The product passes b the upstream gradient times the other input: ∂L/∂d × a = 8 × 2 = 16.', misconceptions: [{ answer: -24, feedback: 'That is ∂L/∂a, which uses b. For b, multiply by the other input, a = 2.' }, { answer: 8, feedback: 'That is the gradient arriving at d. Multiply it by d’s local derivative with respect to b, which is a.' }] } },
    { p: 2 }, { p: 3 },
    { cell: 0 }, { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l20-accumulate': [
    { p: 0 },
    { figure: 'BackwardSteps', props: { preset: 'shared' }, caption: 'f = x·y + x with x = 3, y = 4: watch x collect two contributions.' },
    { p: 1 },
    { cell: 0 },
    { predict: { prompt: 'f = x·x with x = 3: the product node uses x for both of its inputs. What is df/dx?', answer: 6, explain: 'The product passes each input the other input’s value: 3 through one slot and 3 through the other. They add: 6, which is 2x.', misconceptions: [{ answer: 3, feedback: 'That is one slot’s contribution. x fills both inputs of the product, so it receives two contributions of 3.' }, { answer: 9, feedback: 'That is f itself, x·x. The derivative is the sum of the two contributions.' }] } },
    { p: 2 }, { p: 3 },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l20-neuron': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { figure: 'Saturation', caption: 'tanh (solid) and its slope 1 − y² (dashed). Move z out past ±2 and watch the slope collapse.' },
    { p: 2 },
    { cell: 1 },
    { predict: { prompt: 'A tanh neuron has z = 2. What share of the upstream gradient passes back to z, 1 − tanh(2)²? (Three decimals.)', answer: 0.071, tolerance: 0.001, explain: 'tanh(2) = 0.964, and 1 − 0.964² = 0.071: about 7% of the gradient gets through.' } },
    { p: 3 },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l20-check': [
    { p: 0 }, { p: 1 },
    { figure: 'EpsilonSweep', caption: 'The finite-difference error for tanh’s slope at 0.5, over step sizes from 0.1 down to 10⁻¹³.' },
    { cell: 0 },
    { p: 2 }, { p: 3 },
    { cell: 1 },
    { predict: { prompt: 'In the engine, L = e * e with e = 4. What gradient does e receive?', answer: 8, explain: 'e fills both inputs of the product, so it gets two contributions of 4 (the other input’s value), and += adds them: 8 = 2e. With = instead of += it would get 4.', misconceptions: [{ answer: 4, feedback: 'That is one contribution. The product uses e twice, and the engine adds both: 4 + 4.' }] } },
    { p: 4 },
    { math: true },
    { ladder: 'backprop' },
  ],
}
