import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l20-graph',
    title: '20.1 · Computations are graphs',
    sections: ['Break a formula into steps', 'Nodes and edges', 'The forward pass', 'Why a graph', 'Put it into practice'],
    skill: 'Draw the computation graph of an expression and evaluate it with a forward pass.',
    prerequisite: 'Labs 01–19; the chain rule (Lab 01) and gradients (Labs 03, 08).',
    paragraphs: [
      'Every model so far had a hand-derived gradient: least squares, logistic regression, the SVM. A neural network has millions of parameters combined through many layers; deriving each gradient by hand is impossible. We need a mechanical procedure that works for any composition of simple operations.',
      'Write L = (a·b + c)² as a sequence of elementary steps: d = a·b, e = d + c, L = e². Each step is a **node**; arrows connect each node to the nodes that use its value. The result is a **computation graph**: a directed acyclic graph from inputs to the output.',
      'The **forward pass** evaluates nodes in order, each from its inputs. With a = 2, b = −3, c = 10: d = −6, e = 4, L = 16. Every intermediate value is stored, because the backward pass will need it.',
      'Graphs make structure explicit: which values depend on which, and where a value is reused. Frameworks like PyTorch record exactly such a graph as your Python code runs, then traverse it backwards to compute gradients.',
      'Procedure: split the expression into operations whose derivatives you know (+, ×, powers, tanh, exp); draw a node for each; evaluate forward; label every node with its value. The playground draws the graph for four expressions.',
    ],
    formula: 'L = (a·b + c)²:  d = a·b → e = d + c → L = e²',
    experiment: 'Choose "L = (a·b + c)²" and change a, b and c. Predict each node\'s value before reading it.',
    question: 'With a = 2, b = −3 and c = 10, what is L = (a·b + c)²?',
    answer: 16,
    explanation: 'a·b = −6, plus 10 gives 4, squared gives 16.',
    reflection: 'Draw the computation graph of a model from an earlier lab (for example logistic regression for one example). What are its nodes?',
  },
  {
    id: 'l20-local',
    title: '20.2 · Local derivatives and the chain rule',
    sections: ['Each node knows one derivative', 'Chain rule along a path', 'Backward from the output', 'Worked example', 'Why backwards?'],
    skill: 'Compute gradients through a graph by multiplying local derivatives in reverse order.',
    prerequisite: 'Lesson 20.1.',
    paragraphs: [
      'Each operation knows its **local derivative**: for e = d + c, ∂e/∂d = 1 and ∂e/∂c = 1; for d = a·b, ∂d/∂a = b and ∂d/∂b = a; for L = e², dL/de = 2e. Nothing more is needed.',
      'The chain rule says a derivative along a path is the product of the local derivatives on it: `∂L/∂a = ∂L/∂e · ∂e/∂d · ∂d/∂a`. With the values above: 2e = 8, ∂e/∂d = 1, ∂d/∂a = b = −3, so ∂L/∂a = −24.',
      'Work **backwards**: start with ∂L/∂L = 1 at the output. Each node receives the gradient of the output with respect to itself (its "upstream" gradient), multiplies by its local derivatives, and passes the products to its inputs. When a node has been processed, its inputs have their shares.',
      'Worked through: L has grad 1; e gets 2e·1 = 8; d and c each get 8 (addition passes gradients through unchanged); a gets 8·b = −24 and b gets 8·a = 16. One sweep produced every gradient.',
      'Going backwards from one output reaches all inputs in a single pass, costing about as much as the forward pass. Going forwards would need one pass per input. With one loss and millions of parameters, reverse mode — **backpropagation** — is the only practical choice.',
    ],
    formula: '∂L/∂a = ∂L/∂e · ∂e/∂d · ∂d/∂a     node rule: grad(input) += grad(node) × local derivative',
    experiment: 'Step through the backward pass one node at a time on "L = (a·b + c)²". Before each click, predict the gradient that will appear.',
    question: 'With a = 2, b = −3, c = 10, what is ∂L/∂a for L = (a·b + c)²?',
    answer: -24,
    explanation: '∂L/∂a = 2(ab + c) · b = 2 × 4 × (−3) = −24.',
    reflection: 'Explain why computing all gradients backwards costs about one forward pass, while forwards would cost one pass per input.',
  },
  {
    id: 'l20-accumulate',
    title: '20.3 · Shared inputs and gradient accumulation',
    sections: ['A value used twice', 'Contributions add', 'Why += and not =', 'Topological order', 'Weight sharing'],
    skill: 'Handle branching in graphs by accumulating gradient contributions in topological order.',
    prerequisite: 'Lessons 20.1–20.2; partial derivatives (Lab 01).',
    paragraphs: [
      'In f = x·y + x, the input x flows into two nodes. A small change in x changes f through both paths: through the product (rate y) and directly through the sum (rate 1). The total derivative is the **sum** over paths: ∂f/∂x = y + 1. With x = 3, y = 4 it is 5.',
      'So each backward step must **add** to its inputs\' gradients: `x.grad += …`. Writing `x.grad = …` would let the second contribution overwrite the first, silently giving 1 or 4 instead of 5 — a bug that produces plausible-looking wrong gradients.',
      'A node\'s gradient is only complete after every node that uses it has passed back its share. Processing nodes in **reverse topological order** (outputs before the nodes they depend on) guarantees that. The engine builds this order with a depth-first search.',
      'Gradients must also start from zero before each backward pass; otherwise contributions from the previous pass accumulate. This is why frameworks have an explicit `zero_grad()` (Lab 23).',
      'Shared inputs are everywhere in networks: the same weight is applied to many examples in a batch, and in convolutional and recurrent networks (Labs 24–25) the same weights are reused at many positions. Their gradients are the sum of the contributions from every use.',
    ],
    formula: 'if x feeds nodes u and v:  ∂f/∂x = ∂f/∂u · ∂u/∂x + ∂f/∂v · ∂v/∂x',
    experiment: 'Select "f = x·y + x". Step through the backward pass and watch x\'s gradient receive two contributions. Check it against the finite difference.',
    question: 'For f = x·y + x with x = 3 and y = 4, what is ∂f/∂x?',
    answer: 5,
    explanation: 'Product path: y = 4. Sum path: 1. Total 4 + 1 = 5.',
    reflection: 'Where in a model you know is a parameter used more than once? What would go wrong if its gradient contributions were not added?',
  },
  {
    id: 'l20-neuron',
    title: '20.4 · Backprop through a neuron',
    sections: ['A neuron is a small graph', 'Nonlinear nodes', 'Saturation', 'A training step', 'From scalars to tensors'],
    skill: 'Backpropagate through a tanh neuron, recognize vanishing gradients, and perform one gradient step.',
    prerequisite: 'Lessons 20.1–20.3; logistic regression (Lab 08).',
    paragraphs: [
      'A neuron computes z = w₁x₁ + w₂x₂ + b and outputs y = tanh(z). Its graph has two products, two sums and a tanh. The derivative of tanh is `1 − tanh(z)² = 1 − y²`, which the node can compute from its own output.',
      'In the playground\'s default neuron, z = 0.88 and y = tanh(0.88) ≈ 0.706, so 1 − y² ≈ 0.50: about half of the upstream gradient passes back to z. Then each weight receives that gradient times its input, exactly the "error times input" pattern from Labs 01 and 08.',
      'If z is large in magnitude, tanh is flat: y ≈ ±1 and 1 − y² ≈ 0. Almost no gradient reaches the weights — the neuron is **saturated** and learns very slowly. Stacking many saturating layers multiplies these small factors together: the **vanishing gradient** problem that shaped modern activation choices (ReLU, Lab 21).',
      'A training step uses the gradients to update every parameter: `w ← w − α·∂L/∂w`. Build the loss graph, run forward, run backward, update, zero the gradients, repeat. The Python challenge trains a neuron exactly this way with your own engine.',
      'Real networks apply the same rules to whole arrays at once — matrix multiplications instead of scalar products — so one node might handle a million multiplications. The logic of local derivatives, reverse order and accumulation is unchanged.',
    ],
    formula: 'y = tanh(w·x + b)     ∂y/∂z = 1 − y²     ∂L/∂wᵢ = ∂L/∂y · (1 − y²) · xᵢ',
    experiment: 'In the neuron, run the backward pass. Then set b = 10 and run it again. What happened to the weight gradients, and why?',
    question: 'A tanh neuron outputs y = 0.8. What is its local derivative 1 − y²?',
    answer: 0.36,
    explanation: '1 − 0.64 = 0.36: only 36% of the upstream gradient passes through.',
    reflection: 'Explain in your own words why saturated neurons learn slowly, and why that gets worse with depth.',
  },
  {
    id: 'l20-check',
    title: '20.5 · Checking gradients and building an engine',
    sections: ['Finite differences as ground truth', 'Relative error', 'Kinks and precision', 'The engine you will build', 'Demonstrate understanding'],
    skill: 'Verify backpropagation with finite differences and build a scalar autodiff engine.',
    prerequisite: 'Lessons 20.1–20.4; gradient checking (Lab 01).',
    paragraphs: [
      'The finite difference `(f(x + ε) − f(x − ε)) / 2ε` approximates each partial derivative by rerunning the forward pass. It is slow — two passes per input — but independent of your backward code, so it catches bugs. The playground table compares both for every input.',
      'Compare with a relative error, `|a − n| / max(1, |a|, |n|)`, and expect agreement to around 10⁻⁶ with ε ≈ 10⁻⁵ in double precision. Much larger disagreement means a wrong local derivative, a missing accumulation, or a sign error.',
      'Finite differences mislead near kinks such as ReLU at 0 or the hinge at margin 1, where the function is not differentiable; check at points away from them. Too small an ε loses precision to rounding; too large an ε measures curvature.',
      'The Python challenge asks you to build a `Value` class: each operation creates a new node storing its inputs and a small function that pushes gradients back; `backward()` sorts the graph topologically and calls those functions in reverse. It is about 50 lines — and it is, in essence, what PyTorch\'s autograd does.',
      'You have completed this lab when you can: draw a computation graph; compute gradients by hand with local derivatives in reverse; explain accumulation for shared inputs; recognize saturation; and implement and verify a working autodiff engine.',
    ],
    formula: 'numeric ∂f/∂x ≈ (f(x+ε) − f(x−ε)) / 2ε     relative error = |a − n| / max(1, |a|, |n|)',
    experiment: 'For each preset, confirm the table shows matches. Then think of a bug (replace += with =) and predict which preset would reveal it.',
    question: 'The analytic gradient is 2.0000 and the finite difference is 2.0002. What is the relative error |a − n| / max(1, |a|, |n|)? (Scientific notation accepted as a decimal.)',
    answer: 0.0001, tolerance: 0.000001,
    explanation: '0.0002 / 2.0002 ≈ 0.0001 — too large for a correct implementation at ε = 10⁻⁵; investigate.',
    reflection: 'How would you convince a teammate that a new layer\'s backward pass is correct?',
  },
]

export const sources = [
  { title: 'Karpathy · micrograd (a tiny scalar autograd engine)', url: 'https://github.com/karpathy/micrograd' },
  { title: 'Dive into Deep Learning · 5.3 forward propagation, backward propagation and computational graphs', url: 'https://d2l.ai/chapter_multilayer-perceptrons/backprop.html' },
  { title: 'Baydin et al. (2018) · Automatic differentiation in machine learning: a survey', url: 'https://jmlr.org/papers/v18/17-468.html' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
