export const lessons = [
  {
    id: 'l38-read',
    title: '38.1 · Reading a paper for testable claims',
    sections: ['What exactly is claimed?', 'Setup details that matter', 'Reproduce, replicate, generalize', 'Plan within a budget', 'Put it into practice'],
    skill: 'Extract testable claims and the setup needed to check them from a paper, and plan a replication within a compute budget.',
    prerequisite: 'Core labs 01–33; statistics (Lab 05), evaluation (Lab 06), the capstones (Labs 16, 27, 33).',
    paragraphs: [
      'Read a paper as a list of **claims**, each with the evidence offered. "Our method reaches 93.4%" is a claim about a number; "the gain comes from JitterMix" is a claim about a cause; "robust to label noise" is a claim about conditions that may never have been tested. Write each one down separately — they can succeed or fail independently.',
      'Record the setup each claim depends on: data and splits, preprocessing, model and hyperparameters, training length, number of runs and seeds, the metric, and how the baseline was tuned. Missing details are the most common reason a replication fails; note every guess you make as a **deviation**.',
      'Three levels: **reproduce** — same code, same data, same seed, same number (it checks the pipeline); **replicate** — the effect holds on fresh seeds or fresh data from the same setting; **generalize** — it holds in new settings. Papers often show only the first.',
      'Compute is finite. Estimate the cost of each experiment in training runs (or GPU hours) and rank them by how much they could change your conclusions. Checking seed variation is cheap and decisive; a full hyperparameter search for every variant usually is not.',
      'Procedure: list the claims; for each, the experiment that would test it and its cost; run the cheapest decisive experiments first; stop when the budget is spent and report untested claims as untested.',
    ],
    formula: 'claim → required evidence → experiment → cost; spend the budget where it can change the conclusion',
    experiment: 'Read the paper card in the playground. Before running anything, decide which experiments you would buy with 100 runs, and why.',
    question: 'Five experiments cost 2, 20, 40, 32 and 20 training runs. The budget is 100. How many runs over budget would running all of them be?',
    answer: 14,
    explanation: '2 + 20 + 40 + 32 + 20 = 114, which is 14 over. At least one experiment must be skipped — pick the one whose result would change your conclusions least.',
    reflection: 'Pick a result you rely on at work (a benchmark, a vendor claim, a paper). Write its claims as separate testable sentences.',
  },
  {
    id: 'l38-seeds',
    title: '38.2 · Seeds, variance and paired comparisons',
    sections: ['One run is an anecdote', 'Paired seeds', 'Intervals for the difference', 'Cherry-picking and the winner\'s curse', 'Report distributions'],
    skill: 'Quantify seed-to-seed variation and compare two methods with a paired interval.',
    prerequisite: 'Lesson 38.1; confidence intervals and bootstrap (Lab 05), the winner\'s curse (Lab 36).',
    paragraphs: [
      'With 40 training points, which 40 you draw changes test accuracy by several points. A single run cannot tell a real gain from a lucky draw. Report results over several seeds, with the mean and spread.',
      '**Pair** the comparison: give both methods the same seed, hence the same training data, and analyse the per-seed differences. Pairing removes the variation that affects both methods alike, so the interval for the difference is much narrower than comparing two separate averages.',
      'With 10 paired differences, a 95% interval is mean ± 2.262 × sd/√10 (the t value for 9 degrees of freedom), or a bootstrap interval (Lab 05). If the interval excludes 0, the direction is supported; compare the interval with the claimed size separately.',
      'The paper\'s seed 9 happens to be the most favourable of the first twenty. Whether chosen deliberately or by luck, a reported single run tends to be an optimistic one — the same selection effect as the winner\'s curse (Lab 36). Fresh seeds put the gain at about a third of the claim.',
      'Report the distribution, not only the best number: mean, standard deviation or interval, and the number of seeds. When you publish results yourself, fix the seeds in advance and report all of them.',
    ],
    formula: 'dᵢ = accᴬ(seed i) − accᴮ(seed i)     d̄ ± t₀.₉₇₅,ₙ₋₁ · s_d / √n',
    experiment: 'Run the exact reproduction, then the 10-seed comparison. Where does the paper\'s claimed gain fall relative to the interval?',
    question: 'Ten paired differences have mean 0.034 and standard deviation 0.015. What is the upper end of the 95% interval, mean + 2.262 × sd/√10? (Three decimals.)',
    answer: 0.0447, tolerance: 0.001,
    explanation: '2.262 × 0.015 / 3.162 = 0.0107, so the interval is about [0.023, 0.045] — the claimed 0.086 lies far outside it.',
    reflection: 'How many seeds does your team usually run before believing a result? What spread would change that practice?',
  },
  {
    id: 'l38-ablation',
    title: '38.3 · Ablations and fair baselines',
    sections: ['Which part does the work?', 'One component at a time', 'The under-tuned baseline', 'Equal effort', 'Surprises are findings'],
    skill: 'Attribute a gain to its causes with ablations and an equally tuned baseline.',
    prerequisite: 'Lessons 38.1–38.2; regularization and tuning (Labs 07, 16).',
    paragraphs: [
      'A method usually bundles several changes. An **ablation** removes one component at a time, keeping everything else fixed, and measures the drop on the same seeds. A large, clear drop means the component matters; an interval around 0 means it made no detectable difference.',
      'In the playground, removing JitterMix — the paper\'s claimed contribution — changes nothing, while removing the cubic features costs about 3.6 points. Removing weight decay even **improves** accuracy slightly: the paper\'s chosen λ was not well tuned.',
      'The baseline in the paper was plain logistic regression. Give the baseline the same standard ingredients (cubic features) and tune its λ on separate seeds with the same effort, and it matches or beats the full method. Many published gains shrink or vanish against a fairly tuned baseline.',
      'Equal effort means the same tuning budget, the same data preprocessing and the same number of runs for every method compared. Tune on seeds or folds that are not used for the final comparison, or the comparison is biased (Lab 06).',
      'An ablation that contradicts the paper is a result, not a failure. Report it plainly: which component carries the gain, which does not, and the exact settings used.',
    ],
    formula: 'effect of component c = score(full) − score(full without c), paired over the same seeds',
    experiment: 'Run the ablation and the stronger baseline. Which component would you keep if you were building this for real?',
    question: 'Full method 88.8%; without cubic features 85.3%. How many accuracy points do the cubic features contribute? (One decimal.)',
    answer: 3.5, tolerance: 0.05,
    explanation: '88.8 − 85.3 = 3.5 points on these seeds — essentially the whole gain over the baseline, with none left for JitterMix.',
    reflection: 'Think of a system you built with several improvements added at once. Which one would you ablate first, and what would you expect?',
  },
  {
    id: 'l38-report',
    title: '38.4 · Reporting a replication — and choosing deeper work',
    sections: ['Verdicts per claim', 'Deviations', 'Untested is not replicated', 'Where to go deeper', 'Demonstrate understanding'],
    skill: 'Write a replication report with per-claim verdicts and deviations, and choose further advanced study deliberately.',
    prerequisite: 'Lessons 38.1–38.3.',
    paragraphs: [
      'Give each claim a verdict with its evidence: **replicated** (the effect holds and the claimed size is inside your interval), **partially replicated** (real in direction, different in size or conditions), **not supported** (your interval includes no effect, or the evidence points elsewhere), or **not tested**. Here: the accuracy and the gain are partially replicated; the attribution to JitterMix and the robustness claim are not supported.',
      'List every **deviation**: settings you had to guess, different library versions, a smaller budget. Readers need them to judge whether a failure to replicate is about the method or your setup.',
      'A claim you could not afford to test is "not tested" — never quietly "replicated". Robustness claims in particular deserve their own experiment: with 20% flipped labels, the method\'s accuracy swings by about ten points across seeds.',
      'The same skills carry into deeper topics: generative models (variational autoencoders, diffusion models, large language models), probabilistic modelling, graph neural networks, and more. Choose one because a project needs it; start by replicating one well-documented result within a stated budget before building on it.',
      'You have completed this specialization — and the curriculum — when you can: extract testable claims and setup from a paper; distinguish reproduction, replication and generalization; compare methods over paired seeds with intervals; attribute gains with ablations and fairly tuned baselines; spend a compute budget deliberately; and write a report that separates replicated findings, deviations and unsupported conclusions. The Python challenge builds a reusable replication harness.',
    ],
    formula: 'verdict = f(interval for the effect, claimed size); report claims, evidence, deviations, budget',
    experiment: 'Write your verdicts and evidence for all four claims, then compare with the evidence-based verdicts and download the report.',
    question: 'A claimed gain of 5 points; your 10-seed interval for the gain is [2.1, 4.0]. Using the rule "replicated if the claim is inside the interval; partially if the interval is above 0 but excludes the claim", what is the verdict? (1 = replicated, 2 = partially replicated, 3 = not supported)',
    answer: 2,
    explanation: 'The interval is above 0, so the gain is real, but it excludes 5: partially replicated — the effect is smaller than claimed.',
    reflection: 'Which advanced topic will your next project need? Name one well-documented result in it that you could replicate first.',
  },
]

export const sources = [
  { title: 'Pineau et al. (2021) · Improving reproducibility in machine learning research (NeurIPS program report)', url: 'https://jmlr.org/papers/v22/20-303.html' },
  { title: 'Bouthillier et al. (2021) · Accounting for variance in machine learning benchmarks', url: 'https://arxiv.org/abs/2103.03098' },
  { title: 'Lipton & Steinhardt (2018) · Troubling trends in machine learning scholarship', url: 'https://arxiv.org/abs/1807.03341' },
  { title: 'Papers with Code · ML reproducibility challenge', url: 'https://paperswithcode.com/rc2022' },
]
