export const lessons = [
  {
    id: 'l59-importance',
    title: '59.1 · Which features does the model use?',
    sections: ['Explaining a model versus explaining the world', 'The model to explain', 'Permutation importance', 'Measure on held-out data', 'Gain importance and its bias', 'Correlated features', 'Put it into practice'],
    skill: 'Compute permutation importance correctly and recognize when importance scores mislead.',
    prerequisite: 'Gradient boosting (Lab 14), random forests (Lab 13), held-out evaluation (Lab 06), correlation (Lab 05).',
    paragraphs: [
      'An **interpretability method** answers a question about a trained model: which inputs it relies on, how its prediction moves as an input changes, or why it gave one particular answer. Every method in this lab explains **the model**, not the world. If the model learned something wrong, a faithful explanation faithfully reports the wrong thing.',
      'The playground’s model is a boosted-tree regression (Lab 14) that predicts how many minutes a CI build takes from six features: change size, lines changed, files touched, whether the cache was hit, the hour of day, and a random build id. Two features are traps. **Lines changed** is nearly a copy of change size but plays no part in the true process. **Build id** is pure noise.',
      '**Permutation importance** (Breiman 2001) asks how much worse the model gets when it can no longer use a feature. Shuffle that feature’s column, which breaks its link to the target but keeps its distribution, then measure the rise in error: importance_j = error(shuffled j) − error(original). Repeat the shuffle a few times and average, because a single shuffle is random. The method only needs predictions, so it works for any model.',
      'Measure it on **held-out data**. On training data, a model that memorized noise loses accuracy when the noise is shuffled, so the noise looks important. In the playground, build id has a small but real importance on the training builds and essentially none on the test builds.',
      '**Gain (impurity) importance** adds up how much each feature’s splits reduced the training error across all trees. It is free to compute but biased: a feature with many distinct values offers many candidate splits, and some of them fit noise. Here, build id gets about as much gain credit as hour of day, which has a real 4-minute effect.',
      'Correlated features share credit unpredictably. The model split mostly on change size and rarely on lines changed, so shuffling size raises the test error by about 134, while lines changed looks useless. Yet refitting without size raises the test error only from about 7.4 to 9.7, because lines changed and files touched carry almost the same information. Shuffling also creates impossible rows, such as a 90 MB change with 2,000 lines, and the model is then scored on inputs it never saw. **Drop-column importance** (refit without the feature) answers the different question “does the outcome need this feature?”, at the cost of one refit per feature.',
      'Procedure: compute permutation importance on held-out data with several repeats and report the spread. Check correlations before reading the ranking, and group or drop near-duplicates. Never read importance as causal effect.',
    ],
    formula: 'I_j = (1/K) Σₖ [ L(f, X_test with column j shuffled, k-th time) − L(f, X_test) ]',
    derivation: {
      title: 'Permutation importance of a linear effect',
      steps: [
        { prompt: 'The model is f = β·x + (terms without x). A row’s x is replaced by a shuffled value u. Write the change in the prediction, f(u) − f(x).', answer: 'β*(u-x)', show: '`β(u − x)`', vars: { β: [-3, 3], u: [-5, 5], x: [-5, 5] } },
        { prompt: 'u and x are independent draws with the same variance s². Write E[(u − x)²] in terms of s.', answer: '2*s^2', show: '`2s²` — E[u²] + E[x²] − 2E[u]E[x] = 2(s² + m²) − 2m² = 2s²', vars: { s: [0.1, 5] } },
        { prompt: 'If the model was exact before shuffling, the squared error after shuffling is the squared prediction change. Write the expected rise in squared error in terms of β and s.', answer: '2*β^2*s^2', show: '`2β²s²`', vars: { β: [-3, 3], s: [0.1, 5] } },
        { prompt: 'A feature has β = 0.5 minutes per unit and standard deviation 4 units. What is its permutation importance, in squared minutes?', number: 8, tolerance: 1e-6, show: '`2 × 0.25 × 16 = 8`' },
        { prompt: 'The same effect is measured in a unit that doubles every value, so s = 8 and β = 0.25. What is its permutation importance now?', number: 8, tolerance: 1e-6, show: '`2 × 0.0625 × 64 = 8` — importance does not depend on the unit, unlike a raw coefficient', why: 'Permutation importance is measured in the target’s units, so rescaling a feature cannot change it.' },
      ],
      result: 'For a linear effect, permutation importance is 2β²Var(x): large when the effect is strong and the feature varies a lot, whatever unit the feature uses.',
    },
    experiment: 'Switch the evaluation between test and training builds and compare build id. Then choose “Refit without change size” and see which features take over its importance, and how much the test error actually rises.',
    question: 'A model’s test MSE is 7.4. With change size shuffled, it is 141.8. What is the permutation importance of change size?',
    answer: 134.4,
    tolerance: 0.05,
    explanation: '141.8 − 7.4 = 134.4 squared minutes.',
    reflection: 'Which two features in a dataset you know are near-duplicates, and how would that change how you read an importance ranking?',
  },
  {
    id: 'l59-pdp',
    title: '59.2 · Partial dependence and ICE curves',
    sections: ['One feature at a time', 'Partial dependence', 'Individual conditional expectation', 'Centred curves reveal interactions', 'Extrapolation', 'Put it into practice'],
    skill: 'Draw partial dependence and ICE curves and read interactions and extrapolation from them.',
    prerequisite: 'Lesson 59.1; expectation (Lab 04).',
    paragraphs: [
      'Importance says how much a feature matters. **Partial dependence** (Friedman 2001) shows how the prediction changes as that feature changes. Fix feature j at a value v in every row, keep each row’s other features, and average the predictions: PD_j(v) = (1/n) Σᵢ f(v, x_{i,−j}). Repeat for a grid of values v and draw the curve.',
      'An **ICE curve** (individual conditional expectation, Goldstein et al. 2015) is one row’s term of that average: f(v, x_{i,−j}) as v varies. The partial dependence is the average of the ICE curves. The individual curves show whether every row responds the same way.',
      'If the model is additive in feature j, f = g(x_j) + h(everything else), all ICE curves are shifted copies of g and run parallel. **Centred ICE** subtracts each curve’s value at the left end, so parallel curves collapse onto one line and any fan-out is visible. In the playground, change size fans out into two bundles: builds with a cache miss rise about twice as steeply as builds with a cache hit. That is the interaction built into the true process, and the single average line hides it.',
      'Setting one feature to v while keeping the others assumes the features can vary independently. Change size and lines changed move together, so a 100 MB change with its original 2,000 lines is a build that never occurs. The model is being queried where it has no data, and the curve there reports its extrapolation. The red dots mark such points. **Accumulated local effects** (ALE, Apley & Zhu 2020) avoid this by averaging only local changes within narrow bins of real data.',
      'Partial dependence answers “what does the model predict as v changes, other things held as they are in the data?” It does not say what would happen if you changed v in reality. That is a causal question, and confounding (Lab 36) can make the two very different.',
      'Procedure: plot ICE and PDP together, centre the ICE curves to look for interactions, mark or trim regions without data, and compare with ALE when features are correlated.',
    ],
    formula: 'PD_j(v) = (1/n) Σᵢ f(v, x_{i,−j})     ICE_i(v) = f(v, x_{i,−j})     c-ICE_i(v) = ICE_i(v) − ICE_i(v_min)',
    derivation: {
      title: 'Why ICE curves fan out',
      steps: [
        { prompt: 'The model is f(v, w) = c·v + d·w, with no interaction. Write the centred ICE curve for a row with other feature w, relative to the left end ℓ: f(v, w) − f(ℓ, w).', answer: 'c*(v-ℓ)', show: '`c(v − ℓ)` — w cancels, so every row gives the same centred curve', vars: { c: [-3, 3], d: [-3, 3], v: [0, 10], ℓ: [0, 10], w: [-5, 5] } },
        { prompt: 'Now f(v, w) = a·v·w. Write the slope of one row’s ICE curve with respect to v.', answer: 'a*w', show: '`a·w` — each row has its own slope', vars: { a: [-3, 3], w: [-5, 5], v: [0, 10] } },
        { prompt: 'Write the slope of the partial dependence curve when the other feature’s average is m.', answer: 'a*m', show: '`a·m` — the average of the rows’ slopes', vars: { a: [-3, 3], m: [-5, 5] } },
        { prompt: 'With a = 0.15, w = 1 for a cache miss and w = 0 for a hit, and 40% of builds missing the cache, what is the partial dependence slope?', number: 0.06, tolerance: 1e-6, show: '`0.15 × 0.4 = 0.06` minutes per MB — yet no build has that slope: misses have 0.15 and hits have 0', why: 'The average of two different slopes describes neither group.' },
      ],
      result: 'Centred ICE curves coincide exactly when the feature enters additively. Fanning out is the signature of an interaction, and the partial dependence reports only its average.',
    },
    experiment: 'Pick change size and turn on centring: how many distinct bundles of curves do you see, and what separates them? Then look at the share of red points, and compare with hour of day.',
    question: 'At v = 10, three ICE curves give 20, 26 and 29 minutes. What is the partial dependence at v = 10?',
    answer: 25,
    explanation: '(20 + 26 + 29) / 3 = 25.',
    reflection: 'Name two features in a problem you know that could never vary independently. What would their partial dependence plots show?',
  },
  {
    id: 'l59-shapley',
    title: '59.3 · Shapley values',
    sections: ['Sharing a prediction fairly', 'Coalitions and the value function', 'The Shapley formula', 'The axioms', 'What “missing” means', 'SHAP in practice'],
    skill: 'Compute exact Shapley values for a prediction and state what the value function assumes.',
    prerequisite: 'Lessons 59.1–59.2; expectation (Lab 04); combinatorics (counting subsets).',
    paragraphs: [
      'A **local explanation** splits one prediction into contributions, one per feature. Shapley values, from cooperative game theory (Shapley 1953), do this with a guarantee of fairness. Treat the features as players who cooperate to produce the prediction, and share the payout, f(x) minus the average prediction, among them.',
      'This needs a **value function** v(S): what the model predicts when only the features in set S are known. The playground uses the interventional definition. Take the features in S from x, take the rest from each of 50 background builds, and average the predictions. v(∅) is then the average prediction, and v(all features) is f(x).',
      'Feature j’s Shapley value averages its **marginal contribution** v(S ∪ {j}) − v(S) over every coalition S of the other features. Each coalition is weighted by |S|!(d − |S| − 1)!/d!, which is the chance that exactly the features in S come before j when the features are added in a random order. With d = 6 features there are 2⁶ = 64 coalitions, so the playground computes the values exactly.',
      'The Shapley value is the only attribution that satisfies four axioms. **Efficiency**: the values add up to f(x) − v(∅). **Symmetry**: two features that contribute equally to every coalition get equal values. **Dummy**: a feature that never changes the value gets zero. **Additivity**: the values for a sum of two models are the sums of their values. Efficiency is why the playground’s waterfall always ends exactly at the prediction.',
      '“Missing” has to be defined, and the definition matters. Interventional values replace features independently, so they can create impossible rows (Lesson 59.2). Conditional values replace them with values consistent with the features that are known, which is more realistic but harder to estimate, and they spread credit onto correlated features the model never used. Change the background set and the values change too: an explanation is always relative to a reference population.',
      '**SHAP** (Lundberg & Lee 2017) is the family of practical estimators. KernelSHAP samples coalitions and fits a weighted regression. TreeSHAP computes values exactly and fast for tree ensembles. Plotting many local explanations gives global views: a dependence plot of feature j’s value against its Shapley value shows interactions as vertical spread. In the playground, a cache hit is credited with saving more time on larger changes.',
    ],
    formula: 'φ_j = Σ_{S ⊆ F∖{j}} |S|!(d − |S| − 1)!/d! · [v(S ∪ {j}) − v(S)]     Σ_j φ_j = f(x) − v(∅)',
    derivation: {
      title: 'Shapley values for two features with an interaction',
      steps: [
        { prompt: 'f(a, b) = p·a + q·b + r·a·b, with a single background point (0, 0), so a missing feature is set to 0. Write v({1}): only a is known.', answer: 'p*a', show: '`v({1}) = f(a, 0) = p·a`', vars: { p: [-3, 3], q: [-3, 3], r: [-3, 3], a: [-4, 4], b: [-4, 4] } },
        { prompt: 'Write feature 1’s marginal contribution when it joins feature 2: v({1, 2}) − v({2}).', answer: 'p*a+r*a*b', show: '`p·a + r·a·b`', vars: { p: [-3, 3], r: [-3, 3], a: [-4, 4], b: [-4, 4] } },
        { prompt: 'With two features, each ordering has probability ½. Write φ₁, the average of feature 1’s two marginal contributions.', answer: 'p*a+r*a*b/2', show: '`φ₁ = p·a + r·a·b/2` — the interaction is split equally', vars: { p: [-3, 3], r: [-3, 3], a: [-4, 4], b: [-4, 4] }, hint: 'Its contribution joining first is v({1}) − v(∅) = p·a.' },
        { prompt: 'By symmetry φ₂ = q·b + r·a·b/2. Write φ₁ + φ₂.', answer: 'p*a+q*b+r*a*b', show: '`p·a + q·b + r·a·b = f(a, b) − f(0, 0)` — efficiency', vars: { p: [-3, 3], q: [-3, 3], r: [-3, 3], a: [-4, 4], b: [-4, 4] } },
        { prompt: 'With d = 6 features, what weight does the formula give one particular coalition of size 2? (Five decimals.)', number: 1 / 60, tolerance: 1e-5, show: '`2!·3!/6! = 12/720 = 1/60 ≈ 0.01667`', why: 'There are C(5, 2) = 10 such coalitions and 6 possible coalition sizes: (1/6)·(1/10) = 1/60.' },
      ],
      result: 'Shapley values split interaction effects equally between the features involved, and always add up to the prediction minus the baseline.',
    },
    experiment: 'Step through several test builds and check that base plus the sum of the values always equals the prediction. Turn on the dependence plot: why does a cache hit’s value get more negative as change size grows?',
    question: 'The average prediction is 24.3 minutes and a build’s Shapley values are 8.0, 0.1, 2.7, −5.7, −0.8 and 0.2. What does the model predict for this build?',
    answer: 28.8,
    tolerance: 0.05,
    explanation: 'By efficiency, 24.3 + (8.0 + 0.1 + 2.7 − 5.7 − 0.8 + 0.2) = 24.3 + 4.5 = 28.8.',
    reflection: 'Which background population would make sense for explaining a loan decision to an applicant, and why does the choice change the explanation?',
  },
  {
    id: 'l59-lime',
    title: '59.4 · Local surrogate models',
    sections: ['Approximate the model near one point', 'Sampling and weighting', 'Weighted least squares', 'Fidelity and stability', 'Global surrogates', 'Put it into practice'],
    skill: 'Fit a local surrogate and judge whether its explanation is faithful and stable.',
    prerequisite: 'Lesson 59.3; least squares (Lab 03), kernels (Lab 49).',
    paragraphs: [
      'A **surrogate** is a simple model trained to imitate a complex one. **LIME** (Ribeiro et al. 2016) fits it locally. Sample points near x, ask the black-box model for its prediction at each, weight each sample by its closeness to x, and fit a weighted linear regression. The regression’s coefficients are the explanation: how the prediction changes per unit of each feature, near x.',
      'The playground perturbs each numeric feature by a Gaussian with one training standard deviation and flips the cache feature half the time. The kernel weight is w = exp(−d²/σ²), where d is the standardized distance and σ is the **kernel width**. Coefficients are reported per standard deviation of each feature, so they can be compared.',
      'The fit minimizes Σᵢ wᵢ(yᵢ − β₀ − βᵀzᵢ)², a weighted least-squares problem with the closed form β = (ZᵀWZ)⁻¹ZᵀWy (the normal equations of Lab 03, with weights). Close samples count fully; far samples barely count.',
      'Two numbers check the explanation. **Local fidelity**, a weighted R², says how well the line imitates the model near x; a low value means the linear story is wrong at this scale. **Effective sample size**, (Σw)²/Σw², says how many samples the fit really rests on. A narrow kernel describes a small neighbourhood but rests on few samples, so repeated runs disagree. A wide kernel is stable but averages over a region where the model bends. The width is a choice, and it changes the explanation.',
      'A tree ensemble is piecewise constant, so infinitely close to x its slope is zero. A local linear explanation is always a statement about some chosen scale. Shapley values (Lesson 59.3) answer a different question, the fair share of the prediction relative to a background set, so the two methods need not agree.',
      'A **global surrogate**, such as a shallow tree trained on the black box’s predictions over the whole dataset, gives a readable summary. Report its fidelity, because a readable summary of 60% of the behaviour can mislead. Procedure: fix and report the kernel width, check fidelity and effective sample size, rerun with other seeds, and treat disagreement as uncertainty in the explanation.',
    ],
    formula: 'β̂ = argmin_β Σᵢ wᵢ (f(zᵢ) − β₀ − βᵀ(zᵢ − x))²     wᵢ = exp(−‖zᵢ − x‖²/σ²)     n_eff = (Σwᵢ)²/Σwᵢ²',
    derivation: {
      title: 'Kernel weights and the effective sample size',
      steps: [
        { prompt: 'What weight does a sample exactly at x get?', number: 1, tolerance: 1e-9, show: '`exp(0) = 1`' },
        { prompt: 'What weight does a sample at distance d = σ get? (Four decimals.)', number: Math.exp(-1), tolerance: 1e-4, show: '`e⁻¹ ≈ 0.3679`' },
        { prompt: 'Two samples with weights w1 and w2 have values y1 and y2. Write the weighted mean of y, the intercept of a weighted fit with no slope.', answer: '(w1*y1+w2*y2)/(w1+w2)', show: '`(w₁y₁ + w₂y₂)/(w₁ + w₂)`', vars: { w1: [0.1, 1], w2: [0.1, 1], y1: [-5, 5], y2: [-5, 5] } },
        { prompt: 'n samples all have the same weight c. Write the effective sample size (Σw)²/Σw².', answer: 'n', show: '`(nc)²/(nc²) = n`', vars: { n: [1, 100], c: [0.1, 1] } },
        { prompt: 'Four samples have weights 1, 1, 0.5 and 0.5. What is the effective sample size?', number: 3.6, tolerance: 1e-6, show: '`3²/2.5 = 3.6`', why: 'Unequal weights make the fit rest on fewer samples than were drawn.' },
      ],
      result: 'Shrinking the kernel width makes the explanation more local but lowers the effective sample size, so its coefficients get noisier.',
    },
    experiment: 'Set the kernel width to 0.2 and compare the three runs, then set it to 2. Watch the effective sample size and the spread of the change-size coefficient. Then set the samples to 50.',
    question: 'Five samples have weights 1, 0.25, 0.25, 0.25 and 0.25. What is their effective sample size?',
    answer: 3.2,
    tolerance: 0.01,
    explanation: 'Σw = 2 and Σw² = 1 + 4 × 0.0625 = 1.25, so n_eff = 4/1.25 = 3.2.',
    reflection: 'If two explanation runs of the same prediction disagree, what should you tell the person asking for the explanation?',
  },
  {
    id: 'l59-counterfactual',
    title: '59.5 · Counterfactual explanations and the limits of interpretation',
    sections: ['What would have to change?', 'Distance, sparsity and plausibility', 'Actionability', 'Recourse is not causation', 'Choosing a method', 'Inherently interpretable models'],
    skill: 'Find a counterfactual explanation under constraints, and choose the right interpretability tool for a question.',
    prerequisite: 'Lessons 59.1–59.4; causal inference (Lab 36); responsible decisions (Lab 31).',
    paragraphs: [
      'A **counterfactual explanation** (Wachter et al. 2017) answers “what is the smallest change to this input that would have produced the outcome I wanted?” For example: “if the change had been under 19 MB, the build was predicted to finish within the time limit.” It needs no model internals, only predictions, and it answers the question people usually ask.',
      'Formally: minimize a distance d(x, x′) subject to f(x′) ≤ target. The distance defines “smallest”. The playground adds numeric changes measured in standard deviations, plus 1 for each yes/no feature flipped. An L1 distance favours **sparse** changes to few features, which are easier to act on. Weigh the distance differently and the answer changes.',
      'Constraints matter as much as the objective. **Actionability**: only suggest changes the person can make. Hour of day may be under your control; a random build id or someone’s age is not. **Plausibility**: the counterfactual should be a realistic input. Lowering change size while keeping about 53,000 lines changed describes a build that never happens, and the model’s prediction there is extrapolation. The playground reports the distance to the nearest real build as a plausibility check.',
      'A counterfactual explanation tells you what **the model** would predict, not what **the world** would do. If the model learned that large changes are slow partly because they touch slow test suites, shrinking the change without avoiding those suites may not help. Turning a counterfactual into advice (**recourse**) needs causal knowledge (Lab 36). Different people may need very different amounts of change to get the same outcome, which is a fairness question (Lab 31).',
      'Match the method to the question. For what the model relies on overall, use permutation importance on held-out data. For how a prediction moves with a feature, use ICE and PDP, or ALE when features are correlated. For why this case got this prediction, use Shapley values, with a background set you state. For what would change the prediction, use a counterfactual under actionability constraints. For how the world works, no method in this lab answers that; you need causal inference.',
      'When a decision must be explained, consider an **inherently interpretable model** such as a sparse linear model, a shallow tree, or an additive model with one shape function per feature. Rudin (2019) argues that for high-stakes decisions these often match black boxes in accuracy on tabular data, and their explanations are exact rather than approximate.',
    ],
    formula: 'x* = argmin_{x′} d(x, x′)  subject to  f(x′) ≤ t,  x′ actionable and plausible     d(x, x′) = Σ_j |x_j − x′_j| / s_j',
    derivation: {
      title: 'The cheapest change for a linear model',
      steps: [
        { prompt: 'The prediction rises by w minutes per unit of one feature. Write the change in that feature that lowers the prediction by δ minutes.', answer: '-δ/w', show: '`−δ/w`', vars: { δ: [0.5, 20], w: [0.1, 3] } },
        { prompt: 'The feature’s standard deviation is σ. Write the cost of that change in standard deviations (a positive number).', answer: 'δ/(w*σ)', show: '`δ/(wσ)`', vars: { δ: [0.5, 20], w: [0.1, 3], σ: [0.5, 40] } },
        { prompt: 'Change size costs 0.35 minutes per MB for a build that misses the cache, and its standard deviation is 30 MB. What does a 12-minute cut cost through size alone, in standard deviations? (Two decimals.)', number: 12 / (0.35 * 30), tolerance: 0.005, show: '`12/(0.35 × 30) ≈ 1.14`' },
        { prompt: 'Turning the cache on saves 6 + 0.15 × 55.7 minutes for this build and costs 1. Does it reach the 12-minute cut? Enter the saving in minutes. (One decimal.)', number: 6 + 0.15 * 55.7, tolerance: 0.05, show: '`≈ 14.4` minutes, which is more than 12 at a cost of 1 < 1.14 — flipping the cache wins', why: 'The cheapest counterfactual depends on the distance weights: price a flip at 2 and the size route wins.' },
      ],
      result: 'In a linear model, a feature’s cost per minute saved is 1/(wσ), so the cheapest counterfactual moves the features with the largest effect per standard deviation.',
    },
    experiment: 'For build 33 with a 12-minute cut, compare the three feature sets. Then raise the cut to 16 and allow hour of day. Which answer would you give the engineer who owns the build, and which would you refuse to give?',
    question: 'A linear model predicts 0.4 extra minutes per MB of change. By how many MB must a change shrink to cut 10 minutes from the prediction?',
    answer: 25,
    explanation: '10 / 0.4 = 25 MB.',
    reflection: 'Write the counterfactual explanation you would give for a decision in a domain you know, and name one constraint on it that is not in the data.',
  },
]

export const sources = [
  { title: 'Molnar · Interpretable Machine Learning (free book): permutation importance, PDP, ICE, ALE, LIME, Shapley, counterfactuals', url: 'https://christophm.github.io/interpretable-ml-book/' },
  { title: 'Breiman (2001) · Random forests (permutation importance)', url: 'https://doi.org/10.1023/A:1010933404324' },
  { title: 'Goldstein et al. (2015) · Peeking inside the black box: individual conditional expectation plots', url: 'https://arxiv.org/abs/1309.6392' },
  { title: 'Lundberg & Lee (2017) · A unified approach to interpreting model predictions (SHAP)', url: 'https://arxiv.org/abs/1705.07874' },
  { title: 'Ribeiro, Singh & Guestrin (2016) · “Why should I trust you?” Explaining the predictions of any classifier (LIME)', url: 'https://arxiv.org/abs/1602.04938' },
  { title: 'Wachter, Mittelstadt & Russell (2017) · Counterfactual explanations without opening the black box', url: 'https://arxiv.org/abs/1711.00399' },
  { title: 'Rudin (2019) · Stop explaining black box machine learning models for high stakes decisions', url: 'https://arxiv.org/abs/1811.10154' },
  { title: 'Strobl et al. (2007) · Bias in random forest variable importance measures', url: 'https://doi.org/10.1186/1471-2105-8-25' },
]
