export const lessons = [
  {
    id: 'l55-chain',
    title: '55.1 · What a language model is',
    sections: ['Probabilities of text', 'The chain rule', 'Next-token prediction', 'Perplexity', 'Put it into practice'],
    skill: 'Define a language model, factor it with the chain rule and evaluate it by perplexity.',
    prerequisite: 'Information theory (Lab 46), sequence models and attention (Labs 25–26), retrieval (Lab 34).',
    paragraphs: [
      'A **language model** assigns a probability to every sequence of tokens: p(x₁, x₂, …, x_T). That one number lets it score sentences, complete text, and — sampled token by token — generate it.',
      'The **chain rule** of probability factors any such distribution exactly: p(x₁, …, x_T) = Πₜ p(xₜ | x₁, …, xₜ₋₁). So a language model only has to answer one question, over and over: given the text so far, what comes next?',
      'Training minimizes the cross-entropy of the next token on real text (Lab 46): the average −log₂ p(true next token | context). For characters this is **bits per character**; for word pieces, bits (or nats) per token.',
      '**Perplexity** = 2^(bits per token) is the effective number of equally likely choices the model faces at each step. Uniform guessing over the playground’s 28 characters gives perplexity 28 (4.81 bits); the best n-gram here reaches about 6.6.',
      'Always measure on held-out text the model never trained on — training perplexity rewards memorization (Lab 06). Compare only models with the same tokenization: bits per character and bits per token are different units.',
    ],
    formula: 'p(x₁…x_T) = Πₜ p(xₜ | x<ₜ)     bits/token = −(1/T) Σₜ log₂ p(xₜ | x<ₜ)     perplexity = 2^(bits/token)',
    derivation: {
      title: 'Perplexity from probabilities',
      steps: [
        { prompt: 'A model assigns probabilities 0.5, 0.25 and 0.125 to the three actual next characters. Average bits per character?', number: 2, show: '`(1 + 2 + 3)/3 = 2`' },
        { prompt: 'Its perplexity?', number: 4, show: '`2² = 4`' },
        { prompt: 'Write the bits for one token given its probability p.', answer: '-log2(p)', show: '`−log₂ p`', vars: { p: [0.01, 1] } },
      ],
      result: 'Perplexity 4 means the model is as uncertain as if choosing uniformly among 4 characters at each step.',
    },
    experiment: 'In the n-gram view, set n = 1 (letter frequencies only), then n = 4. How does the held-out perplexity change, compared with uniform guessing?',
    question: 'A character model reaches 2 bits per character on held-out text. What is its perplexity?',
    answer: 4,
    explanation: '2² = 4 effective choices per character.',
    reflection: 'Which everyday tool you use is secretly a language model scoring or completing text?',
  },
  {
    id: 'l55-tokens',
    title: '55.2 · Tokenization',
    sections: ['Characters, words or pieces?', 'Byte-pair encoding', 'Consequences of tokenization', 'Tokens and cost', 'Pitfalls'],
    skill: 'Explain and apply byte-pair encoding and reason about tokenization effects.',
    prerequisite: 'Lesson 55.1; text features (Lab 11).',
    paragraphs: [
      'Characters give a tiny vocabulary but long sequences; whole words give short sequences but a huge vocabulary with endless unknown words. Modern models use **subword** tokens in between.',
      '**Byte-pair encoding** (BPE) starts from characters (or bytes) and repeatedly merges the most frequent adjacent pair into a new token, recording each merge. Frequent words become single tokens; rare ones are spelled with smaller pieces, so any string can be encoded.',
      'In the playground, 200 merges shrink the held-out text from 350 characters to roughly 210 tokens: about 1.7 characters per token. Real tokenizers learn 30,000–200,000 merges over bytes and average around four characters of English per token.',
      'Tokenization shapes behaviour: models see “ strawberry” as a few opaque pieces, which is why counting letters or doing digit arithmetic is harder than it looks; languages under-represented in the tokenizer’s training data need more tokens per word, costing more and fitting less into the context window.',
      'Costs, context limits and rate limits are counted in tokens. Measure your texts with the tokenizer your model actually uses.',
    ],
    formula: 'BPE: repeat { find most frequent adjacent pair (a, b) → new token ab }',
    derivation: {
      title: 'One BPE merge by hand',
      intro: 'Words: “low” ×5, “lower” ×2, “newest” ×6, “widest” ×3. Count adjacent pairs across all occurrences.',
      steps: [
        { prompt: 'How many times does the pair (e, s) occur?', number: 9, show: '`6 + 3 = 9` (in newest and widest)' },
        { prompt: 'And (l, o)?', number: 7, show: '`5 + 2 = 7`' },
        { prompt: 'After merging (e, s) into “es”, how many tokens does “newest” have?', number: 5, show: '`n e w es t` → 5' },
      ],
      result: 'Each merge adds one vocabulary entry and shortens every text containing that pair.',
    },
    experiment: 'In the tokenization view, move the merges from 0 to 200. Which words become single tokens first? When do the gains flatten?',
    question: 'A 1,200-character text becomes 300 tokens. How many characters per token?',
    answer: 4,
    explanation: '1,200 / 300 = 4 characters per token — typical of English with a large BPE vocabulary.',
    reflection: 'How might tokenization affect a model’s handling of product codes, names or another language you use?',
  },
  {
    id: 'l55-ngram',
    title: '55.3 · n-gram models and smoothing',
    sections: ['Counting contexts', 'The zero-probability problem', 'Add-k smoothing', 'Interpolation and backoff', 'The limits of counting'],
    skill: 'Build and smooth n-gram language models and read their bias–variance trade-off.',
    prerequisite: 'Lessons 55.1–55.2; naive Bayes smoothing (Lab 11); overfitting (Lab 07).',
    paragraphs: [
      'An **n-gram** model assumes the next token depends only on the previous n − 1: p(xₜ | x<ₜ) ≈ p(xₜ | xₜ₋ₙ₊₁…xₜ₋₁), estimated by counting how often each continuation followed each context in the training text.',
      'Unsmoothed counts give probability 0 to anything unseen. One unseen character in the held-out text makes its probability — and the product — zero: infinite perplexity, as the playground’s first column shows.',
      '**Add-k smoothing** adds k to every count (Laplace, Lab 11). It removes zeros but spreads mass over all continuations of every context, including absurd ones; with longer contexts most are unseen, so the model overfits: training bits fall, held-out bits rise.',
      '**Interpolation** mixes orders: p = λₙpₙ + λₙ₋₁pₙ₋₁ + … + λ₁p₁, so an unseen long context falls back on shorter ones. In the playground the interpolated 5-gram is the best model, at about 2.71 held-out bits per character. Kneser–Ney smoothing refines this and was the state of the art before neural models.',
      'Counting cannot generalize between similar contexts (“the build” and “the builds” share nothing), and the number of possible contexts explodes with n. Neural models (next lesson) learn representations that share statistical strength across contexts.',
    ],
    formula: 'p(c | ctx) = (count(ctx, c) + k) / (count(ctx) + kV)     interpolation: Σₒ λₒ pₒ(c | last o−1 chars)',
    derivation: {
      title: 'Add-k smoothing',
      steps: [
        { prompt: 'Context “th” occurred 20 times, followed by “e” 18 times. Vocabulary 28, k = 0.1. Smoothed p(e | th)? (Four decimals.)', number: 18.1 / 22.8, tolerance: 1e-4, show: '`18.1/22.8 ≈ 0.7939`' },
        { prompt: 'Smoothed probability of a continuation never seen after “th”? (Four decimals.)', number: 0.1 / 22.8, tolerance: 1e-4, show: '`0.1/22.8 ≈ 0.0044`' },
        { prompt: 'Write the add-k probability for count c, context count N, vocabulary V.', answer: '(c + k)/(N + k*V)', show: '`(c + k)/(N + kV)`', vars: { c: [0, 10], N: [10, 50], k: [0.01, 1], V: [10, 50] } },
      ],
      result: 'Smoothing trades a little probability on the seen for a little on the unseen — a prior, as in Lab 41.',
    },
    experiment: 'In the n-gram view, compare training and held-out bits as n rises from 1 to 6 for each smoothing method. Where does add-k start to overfit?',
    question: 'A trigram model gives probability 0 to one character in a 1,000-character test text. What is its test perplexity?',
    choices: [
      { text: 'About 1', why: 'Perplexity 1 means perfect prediction.' },
      { text: 'Slightly higher than without that character', why: 'One zero makes the whole product zero; the effect is not small.' },
      { text: 'Infinite', why: '−log₂ 0 = ∞, so the average is infinite. Smoothing exists to prevent this.' },
    ],
    answer: 2,
    explanation: 'One zero makes the product zero: −log₂ 0 = ∞, so perplexity is infinite. Smoothing exists to prevent this.',
    reflection: 'Where else have you seen a single zero probability break a whole computation?',
  },
  {
    id: 'l55-neural',
    title: '55.4 · Neural language models and sampling',
    sections: ['Embeddings share strength', 'From MLPs to transformers', 'Greedy decoding is dull', 'Temperature, top-k, top-p', 'Memorization'],
    skill: 'Explain neural language models and control generation with sampling parameters.',
    prerequisite: 'Lessons 55.1–55.3; embeddings and attention (Labs 25–26).',
    paragraphs: [
      'A neural language model maps the context to a vector and the vector to a softmax over the vocabulary. Similar contexts get similar vectors, so what is learned about one transfers to others — the key advantage over counting. The playground’s model sees the previous few characters through one hidden layer; transformers (Lab 26) attend over thousands of previous tokens.',
      'On a 2,000-character corpus, the small neural model overfits quickly with a long context, and a well-smoothed n-gram remains competitive. Neural models pull ahead with more data and capacity — the story of language modelling since about 2013.',
      'To generate, sample one token at a time from p(· | context) and append it. Always taking the most likely token (greedy decoding) produces repetitive loops.',
      '**Temperature** T rescales probabilities as p^(1/T): T < 1 sharpens toward the most likely tokens (safer, blander, more copying), T > 1 flattens (more varied, more errors). **Top-k** keeps only the k most likely tokens; **top-p** (nucleus) keeps the smallest set whose probability sums to p. In the playground, low temperature reproduces long verbatim stretches of the training text; high temperature produces gibberish.',
      'Language models **memorize**: rare or repeated training sequences can be reproduced word for word, which matters for privacy, licensing and evaluation leakage (a benchmark in the training data is not a test).',
    ],
    formula: 'p_T(c) ∝ p(c)^(1/T)     top-k: keep the k largest     top-p: keep the smallest set with Σp ≥ p',
    derivation: {
      title: 'Temperature by hand',
      intro: 'Two candidate characters with probabilities 0.8 and 0.2.',
      steps: [
        { prompt: 'At temperature 0.5 (square the probabilities, renormalize), probability of the first? (Four decimals.)', number: 0.64 / 0.68, tolerance: 1e-4, show: '`0.64/0.68 ≈ 0.9412`' },
        { prompt: 'At temperature 2 (square roots, renormalize)? (Four decimals.)', number: Math.sqrt(0.8) / (Math.sqrt(0.8) + Math.sqrt(0.2)), tolerance: 1e-4, show: '`≈ 0.6667`' },
        { prompt: 'Write the tempered probability of the first as a function of T.', answer: '0.8^(1/T)/(0.8^(1/T) + 0.2^(1/T))', show: '`0.8^(1/T) / (0.8^(1/T) + 0.2^(1/T))`', vars: { T: [0.3, 3] } },
      ],
      result: 'T → 0 approaches greedy decoding; T → ∞ approaches uniform sampling.',
    },
    experiment: 'In the neural view, sample at temperature 0.3, 1 and 1.8. Compare with the n-gram samples and note the longest copied stretch in each.',
    question: 'Top-k with k = 1 is equivalent to which decoding rule?',
    choices: [
      { text: 'Greedy decoding', why: 'Keeping only the most likely token means always choosing it.' },
      { text: 'Uniform sampling', why: 'That keeps every token with equal probability.' },
      { text: 'Temperature 1 sampling', why: 'That samples from the full distribution.' },
    ],
    answer: 0,
    explanation: 'Keeping only the single most likely token means always choosing it: greedy decoding.',
    reflection: 'For a customer-facing assistant, would you choose a low or a high temperature? What would you lose?',
  },
  {
    id: 'l55-assistants',
    title: '55.5 · From language models to assistants',
    sections: ['Pretraining', 'Fine-tuning and LoRA', 'Instruction tuning', 'Preference optimization', 'Demonstrate understanding'],
    skill: 'Describe how pretrained language models are adapted into assistants and evaluated.',
    prerequisite: 'Lessons 55.1–55.4; retrieval (Lab 34); reinforcement learning (Labs 37, 58).',
    paragraphs: [
      '**Pretraining** is next-token prediction on enormous text corpora: the same objective as the playground, with transformers, trillions of tokens and billions of parameters. Performance improves smoothly and predictably with data, parameters and compute (**scaling laws**).',
      '**Fine-tuning** continues training on a smaller, targeted dataset. Updating every weight is expensive; **LoRA** freezes the pretrained weights W and learns a low-rank update W + BA with A of shape r × d and B of shape d × r (r small), cutting trainable parameters by orders of magnitude.',
      '**Instruction tuning** fine-tunes on examples of requests and good responses, so the model follows instructions rather than merely continuing text.',
      '**Preference optimization** aligns outputs with human judgements: RLHF trains a reward model on comparisons and optimizes the policy against it with RL (Labs 37, 58) — and inherits reward hacking risks; **DPO** skips the reward model and directly raises the probability of preferred responses relative to rejected ones, anchored to a reference model.',
      'Evaluate assistants on held-out, uncontaminated tasks, check calibration and refusal behaviour, guard against prompt injection when retrieving documents (Lab 34), and remember they generate plausible text, not verified facts. You have completed this lab when you can: define language models, perplexity and tokenization; build and smooth n-gram models; explain neural LMs and sampling controls; and describe pretraining, LoRA, instruction tuning and preference optimization. The Python challenge implements BPE, n-gram scoring, sampling filters, LoRA and the DPO loss.',
    ],
    formula: 'LoRA: W′ = W + (α/r)·BA     DPO: −log σ(β[(log π(y_w) − log π_ref(y_w)) − (log π(y_l) − log π_ref(y_l))])',
    derivation: {
      title: 'How much does LoRA save?',
      steps: [
        { prompt: 'A 4096 × 4096 weight matrix has how many parameters? (Nearest thousand is fine; exact expected.)', number: 4096 * 4096, show: '`16,777,216`' },
        { prompt: 'LoRA with rank r = 8 trains A (8 × 4096) and B (4096 × 8). How many parameters?', number: 2 * 8 * 4096, show: '`65,536`' },
        { prompt: 'Write the LoRA parameter count for a d × d matrix with rank r.', answer: '2*r*d', show: '`2rd`', vars: { r: [1, 64], d: [64, 4096] } },
      ],
      result: '65,536 instead of 16.8 million: 0.4% of the parameters, and the base model stays untouched.',
    },
    experiment: 'Consider the playground’s low-temperature samples: fluent but copied. What would instruction tuning or preference optimization need to change for this to become a useful assistant?',
    question: 'In DPO, the policy raises log π(preferred) by 0.4 and lowers log π(rejected) by 0.2 relative to the reference, with β = 1. What is the margin inside the sigmoid?',
    answer: 0.6, tolerance: 1e-9,
    explanation: 'β[(0.4) − (−0.2)] = 0.6; the loss −log σ(0.6) ≈ 0.44 falls as the margin grows.',
    reflection: 'If you fine-tuned a model for your domain, what data would you use, and how would you check it did not get worse elsewhere?',
  },
]

export const sources = [
  { title: 'Jurafsky & Martin · Speech and Language Processing, ch. 3 (n-grams) and ch. 10 (LLMs) (free draft)', url: 'https://web.stanford.edu/~jurafsky/slp3/' },
  { title: 'Sennrich, Haddow & Birch (2016) · Neural machine translation of rare words with subword units (BPE)', url: 'https://arxiv.org/abs/1508.07909' },
  { title: 'Hu et al. (2021) · LoRA: low-rank adaptation of large language models', url: 'https://arxiv.org/abs/2106.09685' },
  { title: 'Rafailov et al. (2023) · Direct preference optimization', url: 'https://arxiv.org/abs/2305.18290' },
]
