import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l23-tensors',
    title: '23.1 · Tensors and autograd',
    sections: ['Why a framework', 'Tensors are arrays with extras', 'requires_grad and the recorded graph', 'backward() fills .grad', 'Put it into practice'],
    skill: 'Map NumPy arrays and your autodiff engine onto PyTorch tensors and autograd.',
    prerequisite: 'Labs 20–22: backpropagation, NumPy networks and optimizers.',
    paragraphs: [
      'You have built everything a small network needs: arrays, a forward pass, backpropagation and optimizers. A framework such as **PyTorch** packages the same mathematics so you can build large models quickly, run them on GPUs, and rely on well-tested gradient code.',
      'A **tensor** is an n-dimensional array, like a NumPy array: the same shapes, indexing and broadcasting rules (Lab 02). It also records its data type and **device** (CPU or GPU). `torch.tensor(x)` and `t.numpy()` convert between the two worlds when both are on the CPU.',
      'Create a tensor with `requires_grad=True` and PyTorch records every operation on it — exactly the graph from Lab 20, built automatically as your Python runs. Model parameters are tensors with this flag set.',
      '`loss.backward()` traverses that graph in reverse topological order, applies each operation\'s local derivative and **accumulates** into each leaf tensor\'s `.grad` attribute — the `grad +=` rule from Lab 20. For y = x² at x = 3, `y.backward()` leaves `x.grad == 6`.',
      'Nothing here is magic: autograd is a well-engineered version of the engine you wrote. Knowing that lets you predict its behaviour — including why gradients pile up when you forget to clear them.',
    ],
    formula: 'x = torch.tensor(3.0, requires_grad=True); y = x**2; y.backward(); x.grad → 6',
    experiment: 'Read the NumPy ↔ PyTorch table in the playground. For each row, say which lab you implemented the NumPy side in.',
    question: 'x = 3 with requires_grad=True, y = x² + 2x. After y.backward(), what is x.grad?',
    answer: 8,
    explanation: 'dy/dx = 2x + 2 = 8 at x = 3.',
    reflection: 'Which parts of your Lab 21 network would you keep writing by hand in production, and which would you hand to a framework? Why?',
  },
  {
    id: 'l23-modules',
    title: '23.2 · Modules, parameters and optimizers',
    sections: ['nn.Module', 'Parameters are registered', 'Composing layers', 'Optimizers own state', 'Counting parameters'],
    skill: 'Define a model as an nn.Module, count its parameters, and connect it to an optimizer.',
    prerequisite: 'Lesson 23.1; dense layers (Lab 21).',
    paragraphs: [
      'An `nn.Module` bundles parameters with a `forward` method. `nn.Linear(5, 1)` owns a weight of shape (1, 5) and a bias of shape (1,) — six parameters — and computes `x @ W.T + b`. Your own modules subclass `nn.Module`, create layers in `__init__`, and combine them in `forward`.',
      'Assigning a layer or `nn.Parameter` as an attribute **registers** it: `model.parameters()` then yields every trainable tensor, recursively through sub-modules. This is how an optimizer finds what to update and how `state_dict()` knows what to save.',
      '`nn.Sequential(nn.Linear(2, 8), nn.ReLU(), nn.Linear(8, 2))` is the Lab 21 network in one line: 2·8 + 8 + 8·2 + 2 = 42 parameters, the same count you computed by hand.',
      'An optimizer, e.g. `torch.optim.SGD(model.parameters(), lr=0.02, momentum=0.9)` or `torch.optim.AdamW(...)`, keeps references to those tensors and its own **state** — momentum buffers, Adam\'s m and v and step counts (Lab 22). `opt.step()` reads each `.grad` and updates the tensor in place.',
      'Because the optimizer and the model share tensor objects, replacing a parameter with a new tensor after creating the optimizer silently disconnects it — a classic bug. Create the model first, then the optimizer, and update parameters only through `step()` or in-place operations.',
    ],
    formula: 'nn.Linear(d_in, d_out): d_in·d_out + d_out parameters     sum(p.numel() for p in model.parameters())',
    experiment: 'In the loop code, identify where the model, optimizer, and each of their states live. Which line touches every parameter\'s .grad?',
    question: 'How many parameters does nn.Linear(5, 1) have?',
    answer: 6,
    explanation: 'A 1 × 5 weight matrix (5 values) plus 1 bias: 6.',
    reflection: 'Write the nn.Module you would use for the Lab 21 spiral network. How many parameters does it have?',
  },
  {
    id: 'l23-loop',
    title: '23.3 · The training loop, line by line',
    sections: ['Five lines, five jobs', 'zero_grad: gradients accumulate', 'train() and eval()', 'no_grad for evaluation', 'Data loaders'],
    skill: 'Write a correct PyTorch training loop and explain the consequence of omitting each line.',
    prerequisite: 'Lessons 23.1–23.2; mini-batches (Lab 22).',
    paragraphs: [
      'The canonical loop: `model.train()`; for each batch, `opt.zero_grad()`, `loss = loss_fn(model(x), y)`, `loss.backward()`, `opt.step()`. Each line has one job, and the playground lets you delete them one at a time.',
      'Because autograd **accumulates** into `.grad`, forgetting `zero_grad()` makes each step use the sum of all gradients so far. The effective step size grows every iteration and training diverges. (Accumulation is deliberate: it lets you sum gradients over several small batches before one step.)',
      'Some layers behave differently in training and evaluation. **Dropout** zeroes random activations during training (a regularizer) but must be off when evaluating; **batch normalization** switches from batch statistics to running averages. `model.eval()` flips them; forgetting it makes validation noisy and pessimistic — 3.5 instead of 0.86 in the playground.',
      '`with torch.no_grad():` stops autograd from recording during evaluation. Forgetting it gives correct numbers but keeps graphs alive, wasting memory — the playground\'s retained-node counter — and can crash long runs.',
      'A `Dataset` returns single examples; a `DataLoader` shuffles, batches and loads them in parallel workers. Shuffle training data every epoch; do not shuffle evaluation data if you need predictions in order.',
    ],
    formula: 'model.train(); for x, y in loader: opt.zero_grad(); loss = loss_fn(model(x), y); loss.backward(); opt.step()',
    experiment: 'Remove each checkbox line in turn. For each, write the symptom you see and how you would notice it in a real project.',
    question: 'You forget opt.zero_grad(). The gradient happens to equal g at every step. What gradient does the optimizer use at step 3?',
    answer: 3,
    explanation: 'g + g + g = 3g (as a multiple of g): the accumulated sum. At step 100 it would be 100g.',
    reflection: 'Which of the four mistakes in the playground would be hardest to spot in your own project, and what would catch it?',
  },
  {
    id: 'l23-verify',
    title: '23.4 · Verifying a framework model against your own',
    sections: ['Trust, but verify', 'Match the forward pass', 'Match the gradients', 'Match a training step', 'Numerical tolerance'],
    skill: 'Check a framework implementation against an independent NumPy implementation.',
    prerequisite: 'Lessons 23.1–23.3; gradient checking (Lab 20).',
    paragraphs: [
      'Porting a model to a framework — or trusting a model someone else wrote — should come with evidence that it computes what you think. Compare it against an implementation you understand completely.',
      'Copy identical weights into both: `torch.tensor(W1_numpy)`, remembering that `nn.Linear` stores its weight as (out, in), the transpose of the (in, out) convention used in Lab 21. Feed the same inputs. The outputs should agree to about 10⁻⁶ in float32.',
      'Run `loss.backward()` and compare each parameter\'s `.grad` with your NumPy backward pass. Differences usually come from a transposed weight, a loss averaged versus summed, or a different softmax/cross-entropy convention (PyTorch\'s `cross_entropy` takes raw logits and applies log-softmax itself).',
      'Apply one optimizer step in both and compare again. Then train both for a few hundred steps: identical settings should give nearly identical loss curves.',
      'Float32 (the framework default) has about 7 significant digits, float64 (NumPy\'s default) about 16. When comparing across them use a relative tolerance like `rtol=1e-5` together with an absolute one scaled to the outputs (entries near zero have large relative errors), or set `torch.set_default_dtype(torch.float64)` for exact checks. The downloadable script does all of this.',
    ],
    formula: 'nn.Linear weight = W_numpyᵀ     compare outputs, .grad and one step with rtol ≈ 1e-5 (float32)',
    experiment: 'Download the PyTorch verification script from the "Implement in Python" tab. Before running it, predict which comparison is most likely to fail if you forget the transpose.',
    question: 'A NumPy layer uses W with shape (8, 2) for inputs of width 8 and outputs of width 2. What shape must the matching nn.Linear weight have? Answer with the number of rows.',
    answer: 2,
    explanation: 'nn.Linear stores (out_features, in_features) = (2, 8): 2 rows. Copy Wᵀ.',
    reflection: 'How would you convince a reviewer that a model you ported to PyTorch is correct?',
  },
  {
    id: 'l23-checkpoints',
    title: '23.5 · Devices, checkpoints and reproducibility',
    sections: ['Moving to the GPU', 'What a checkpoint contains', 'Resuming exactly', 'Determinism', 'Demonstrate understanding'],
    skill: 'Save and resume training faithfully and control the sources of nondeterminism.',
    prerequisite: 'Lessons 23.1–23.4; reproducibility (Lab 02).',
    paragraphs: [
      '`device = "cuda" if torch.cuda.is_available() else "cpu"`; `model.to(device)` moves parameters; every batch needs `x.to(device)`. Mixing devices raises an error; the fix is always to move tensors, never to change the math.',
      '`model.state_dict()` maps parameter names to tensors. A **checkpoint** should contain the model state, the optimizer state (`opt.state_dict()`: momentum buffers, Adam moments, step counts), the scheduler state, the epoch and step number, and the random generator states.',
      'Resuming without optimizer state is a quiet bug: the weights continue, but momentum or Adam statistics restart from zero, so training takes a different path. The playground measures that drift. Save and reload everything, then verify by comparing a resumed run against an uninterrupted one.',
      'Seed Python, NumPy and PyTorch (`torch.manual_seed`), and record library versions. Some GPU operations are nondeterministic by default; `torch.use_deterministic_algorithms(True)` trades speed for repeatability. Report results over several seeds anyway (Lab 27).',
      'You have completed this lab when you can: map NumPy operations to tensors and autograd; build models from modules; write a correct training loop and explain every line; verify a framework model against your own; and checkpoint and resume training faithfully. The in-browser challenge builds these conventions in NumPy; the downloadable script does the same in real PyTorch.',
    ],
    formula: "ckpt = {'model': model.state_dict(), 'opt': opt.state_dict(), 'sched': sched.state_dict(), 'step': step}",
    experiment: 'Untick "save optimizer state" and read the parameter drift. Then explain in the notebook why the losses look almost the same even though the runs differ.',
    question: 'A model has 42 parameters and uses Adam, which stores two running averages per parameter. How many optimizer-state numbers does the checkpoint need (ignoring the step counter)?',
    answer: 84,
    explanation: 'Adam keeps m and v for each parameter: 2 × 42 = 84 values, as many as the model itself twice over.',
    reflection: 'Write the checklist you would use before starting a multi-day training run so it can be resumed exactly.',
  },
]

export const sources = [
  { title: 'PyTorch · Learn the basics (tensors, autograd, modules, optimization loop)', url: 'https://pytorch.org/tutorials/beginner/basics/intro.html' },
  { title: 'PyTorch · Saving and loading a general checkpoint', url: 'https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_a_general_checkpoint.html' },
  { title: 'PyTorch · Reproducibility', url: 'https://pytorch.org/docs/stable/notes/randomness.html' },
  { title: 'Dive into Deep Learning · Chapter 6: builders’ guide', url: 'https://d2l.ai/chapter_builders-guide/index.html' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
