const G = { x: [-3, 3], m1: [-2, 2], m0: [-2, 2] }

export const lessons = [
  {
    id: 'l40-generative',
    title: '40.1 · Generative versus discriminative',
    sections: ['Two ways to classify', 'Bayes’ rule does the classifying', 'The posterior is a sigmoid', 'What a generative model buys you', 'Put it into practice'],
    skill: 'Classify with a generative model through Bayes’ rule and derive its log-odds.',
    prerequisite: 'Core labs 01–33, especially Bayes’ rule (Lab 04), logistic regression (Lab 08) and naive Bayes (Lab 11); Lab 39.',
    paragraphs: [
      'Logistic regression models p(y | x) directly: it only cares where the boundary is. That is a **discriminative** model. A **generative** model instead describes how each class produces its inputs, p(x | y), together with how common each class is, p(y). It could generate new examples of each class.',
      'To classify, a generative model uses Bayes’ rule: p(y = 1 | x) = p(x | 1)·p(1) / [p(x | 1)·p(1) + p(x | 0)·p(0)]. The class whose model explains x better — weighted by how common the class is — wins.',
      'Divide numerator and denominator by the numerator: p(y = 1 | x) = σ(log-odds), with log-odds = log p(x | 1) − log p(x | 0) + log(φ / (1 − φ)), where φ = p(y = 1). Every generative classifier with two classes ends in a sigmoid; the class-conditional models decide what goes inside.',
      'Modelling x is extra work, but it buys things: you can generate examples to check the model’s realism, handle a missing feature by simply leaving its term out, add unlabeled data, and — when the model is right — learn from fewer examples. The cost: if p(x | y) is wrong, the classifier inherits the error.',
      'Procedure: choose a distribution for each class’s inputs, fit it and the class proportions, then classify with the posterior. Always compare against a discriminative model on the same split, because you can rarely be sure p(x | y) is right.',
    ],
    formula: 'p(y=1 | x) = σ( log p(x|1) − log p(x|0) + log(φ/(1−φ)) )',
    derivation: {
      title: 'Derive the posterior for two one-dimensional Gaussians',
      intro: 'Class 1 inputs follow N(m1, 1) and class 0 inputs N(m0, 1). Constants that are the same for both classes cancel.',
      steps: [
        { prompt: 'log p(x | 1) up to a constant is −(x − m1)²/2. Write log p(x | 1) − log p(x | 0).', answer: '-(x-m1)^2/2 + (x-m0)^2/2', show: '`−(x − m1)²/2 + (x − m0)²/2`', vars: G },
        { prompt: 'Expand it: the x² terms cancel. Write the result as (something)·x + (something).', answer: '(m1-m0)*x - (m1^2-m0^2)/2', show: '`(m1 − m0)·x − (m1² − m0²)/2` — linear in x', vars: G, hint: 'Expand both squares; −x²/2 and +x²/2 cancel.' },
        { prompt: 'With m1 = 2, m0 = 0 and equal class proportions, what is p(y = 1 | x = 1)?', number: 0.5, show: '`0.5`', why: 'x = 1 is exactly halfway between the means: log-odds 2·1 − 2 = 0.' },
        { prompt: 'Same model, x = 2. Evaluate p(y = 1 | x = 2). (Four decimals.)', number: 1 / (1 + Math.exp(-2)), tolerance: 1e-4, show: '`σ(2) ≈ 0.8808`' },
      ],
      result: 'Two Gaussians with equal variance produce exactly a logistic-regression posterior. The generative model implies the discriminative form — not the other way round.',
    },
    experiment: 'In “Decision boundaries”, choose the shared-covariance world and compare the LDA and logistic boundaries at 10, 40 and 400 examples. When are they closest?',
    question: 'p(x | class 1) = 0.3, p(x | class 0) = 0.1, and class 1 makes up 25% of the data. What is p(class 1 | x)?',
    answer: 0.5,
    explanation: '0.3 × 0.25 = 0.075 and 0.1 × 0.75 = 0.075. The better likelihood of class 1 is exactly cancelled by its rarity: 0.075 / 0.15 = 0.5.',
    reflection: 'Name a problem where you would want to generate examples of each class, not just classify them.',
  },
  {
    id: 'l40-fit',
    title: '40.2 · Fitting GDA by maximum likelihood',
    sections: ['The joint likelihood splits apart', 'Class proportions', 'Class means', 'The pooled covariance', 'No optimizer needed'],
    skill: 'Derive and compute the maximum-likelihood estimates of Gaussian discriminant analysis.',
    prerequisite: 'Lesson 40.1; maximum likelihood (Lab 05), covariance (Lab 18).',
    paragraphs: [
      '**Gaussian discriminant analysis** (GDA) assumes y ~ Bernoulli(φ) and x | y = k ~ N(μₖ, Σ). The log-likelihood of the data is Σᵢ [log p(xᵢ | yᵢ) + log p(yᵢ)]. It splits into a part about φ and a part about each class’s Gaussian, so each parameter can be estimated separately.',
      'The class proportion: with m examples of class 1 among n, maximizing m·log φ + (n − m)·log(1 − φ) gives **φ = m / n**.',
      'Each class mean: maximizing −½ Σ (xᵢ − μₖ)ᵀΣ⁻¹(xᵢ − μₖ) over the examples of class k gives **μₖ = the average of that class’s examples**.',
      'The shared covariance is the **pooled within-class covariance**: Σ = (1/n) Σᵢ (xᵢ − μ_yᵢ)(xᵢ − μ_yᵢ)ᵀ — each example measured from its own class mean. Using the overall mean would mix the gap between classes into the noise.',
      'All estimates are averages: no gradient descent, no learning rate, one pass over the data. Compare logistic regression, which needs an iterative optimizer (Lab 39). With few examples per class, covariances can be singular; adding a small multiple of the identity (shrinkage) keeps them invertible.',
    ],
    formula: 'φ = m/n     μₖ = mean of class k     Σ = (1/n) Σᵢ (xᵢ − μ_yᵢ)(xᵢ − μ_yᵢ)ᵀ',
    derivation: {
      title: 'Derive the maximum-likelihood estimates',
      steps: [
        { prompt: 'The log-likelihood for φ is m·log φ + (n − m)·log(1 − φ). Write its derivative with respect to φ.', answer: 'm/φ - (n-m)/(1-φ)', show: '`m/φ − (n − m)/(1 − φ)`', vars: { m: [1, 20], n: [25, 60], φ: [0.1, 0.9] } },
        { prompt: 'Set it to zero. With m = 30 of n = 120 examples in class 1, what is φ?', number: 0.25, show: '`φ = m/n = 0.25`' },
        { prompt: 'For a one-dimensional class mean with unit variance, the log-likelihood is −½[(a − μ)² + (b − μ)² + (c − μ)²]. Write its derivative with respect to μ.', answer: '(a-μ) + (b-μ) + (c-μ)', show: '`(a − μ) + (b − μ) + (c − μ)`', vars: { a: [-3, 3], b: [-3, 3], c: [-3, 3], μ: [-2, 2] } },
        { prompt: 'Setting it to zero gives the sample mean. For class values 2, 4 and 9, what is μ?', number: 5, show: '`5`' },
      ],
      result: 'Every GDA parameter is a count or an average — which is why GDA fits instantly, even on huge datasets.',
    },
    experiment: 'In “Decision boundaries”, turn on the ellipses and slide the number of examples from 10 to 400. How do the fitted ellipses change, and how does the LDA boundary move?',
    question: 'One feature. Class 0 has values 1 and 3; class 1 has values 6 and 10. What is the pooled within-class variance (divide by n = 4)?',
    answer: 2.5,
    explanation: 'Class means 2 and 8. Squared deviations: 1, 1 (class 0) and 4, 4 (class 1). (1 + 1 + 4 + 4)/4 = 2.5. The overall variance would be far larger because it includes the gap between the classes.',
    reflection: 'Why must each point be measured from its own class mean when estimating the shared covariance?',
  },
  {
    id: 'l40-boundaries',
    title: '40.3 · LDA and QDA boundaries',
    sections: ['Shared covariance: the quadratic terms cancel', 'The linear discriminant', 'Separate covariances: curved boundaries', 'Counting parameters', 'Shrinkage'],
    skill: 'Derive why LDA’s boundary is linear and QDA’s quadratic, and count their parameters.',
    prerequisite: 'Lessons 40.1–40.2; matrices (Lab 03).',
    paragraphs: [
      'For a d-dimensional Gaussian, log p(x | k) = −½(x − μₖ)ᵀΣₖ⁻¹(x − μₖ) − ½ log|Σₖ| + const. Subtract the two classes. If both use the **same** Σ, the terms −½xᵀΣ⁻¹x cancel, and what is left is linear in x.',
      'The result is **linear discriminant analysis** (LDA): log-odds = θᵀx + θ₀ with **θ = Σ⁻¹(μ₁ − μ₀)** and θ₀ = −½(μ₁ᵀΣ⁻¹μ₁ − μ₀ᵀΣ⁻¹μ₀) + log(φ/(1 − φ)). The posterior is a sigmoid of a linear function — the same form as logistic regression, but with θ computed from means and a covariance instead of optimized.',
      'With a separate Σₖ per class — **quadratic discriminant analysis** (QDA) — the term −½xᵀ(Σ₁⁻¹ − Σ₀⁻¹)x survives: the boundary is a conic (ellipse, parabola or hyperbola). In the playground’s “different covariances” world, QDA draws a closed curve around the tight class, which no linear model can.',
      'Flexibility costs parameters. For d features and two classes: LDA estimates 2d means, d(d + 1)/2 covariance entries and a prior; QDA twice as many covariance entries; logistic regression only d + 1 weights. With d = 20: 251 for LDA, 461 for QDA, 21 for logistic regression.',
      'When examples barely outnumber features, estimated covariances are noisy or singular. **Shrinkage** — Σ̂ = (1 − α)·Σ̂ + α·(diagonal) — trades a little bias for much lower variance (regularized discriminant analysis, Ledoit–Wolf). Taken to the limit, it gives naive Bayes (Lesson 40.5).',
    ],
    formula: 'LDA: θ = Σ⁻¹(μ₁ − μ₀),  θ₀ = −½(μ₁ᵀΣ⁻¹μ₁ − μ₀ᵀΣ⁻¹μ₀) + log(φ/(1−φ))     QDA: + −½xᵀ(Σ₁⁻¹ − Σ₀⁻¹)x',
    derivation: {
      title: 'Compute an LDA boundary by hand',
      intro: 'Two features, shared covariance Σ = I (identity), μ₁ = (2, 1), μ₀ = (0, 0), equal class proportions.',
      steps: [
        { prompt: 'θ = Σ⁻¹(μ₁ − μ₀). What is its first component θ₁?', number: 2, show: '`2`' },
        { prompt: 'θ₀ = −½(μ₁ᵀμ₁ − μ₀ᵀμ₀) + log(1). What is θ₀?', number: -2.5, show: '`−½(4 + 1) = −2.5`' },
        { prompt: 'Write the log-odds as a function of x1 and x2.', answer: '2*x1 + x2 - 2.5', show: '`2·x1 + x2 − 2.5`', vars: { x1: [-3, 3], x2: [-3, 3] } },
        { prompt: 'On the boundary the log-odds is 0. Write x2 as a function of x1 along the boundary.', answer: '2.5 - 2*x1', show: '`x2 = 2.5 − 2·x1`', vars: { x1: [-3, 3] }, why: 'A straight line through the midpoint (1, 0.5), perpendicular to μ₁ − μ₀ = (2, 1) because Σ = I.' },
      ],
      result: 'With identity covariance, LDA’s boundary is the perpendicular bisector of the two means; a non-identity Σ tilts it by Σ⁻¹.',
    },
    experiment: 'Choose “different covariances”. Compare LDA and QDA error at 10 and at 400 examples. Why does QDA lose at 10 but win at 400?',
    question: 'QDA with 3 features and two classes: 2 mean vectors, 2 covariance matrices (each symmetric, 6 distinct entries) and 1 prior. How many parameters in total?',
    answer: 19,
    explanation: '2 × 3 + 2 × 6 + 1 = 19. LDA would need 2 × 3 + 6 + 1 = 13; logistic regression 4.',
    reflection: 'Your dataset has 50 features and 80 examples. Which of LDA, QDA and logistic regression would you try first, and why?',
  },
  {
    id: 'l40-tradeoff',
    title: '40.4 · Which wins, and when?',
    sections: ['Faster learning from assumptions', 'Lower final error from fewer assumptions', 'Reading the learning curves', 'Robustness to outliers', 'Fisher’s discriminant'],
    skill: 'Predict from the assumptions and the sample size whether a generative or discriminative classifier will do better.',
    prerequisite: 'Lessons 40.1–40.3; learning curves (Lab 07).',
    paragraphs: [
      'Ng and Jordan (2002) compared naive Bayes with logistic regression. When the generative assumptions hold, naive Bayes reaches its best error with a number of examples that grows only **logarithmically** in the number of features; logistic regression needs a number that grows linearly. Assumptions are information: they replace data.',
      'But logistic regression assumes only that the log-odds is linear, which is true whenever GDA is true and in many other cases too. When p(x | y) is misspecified, the generative model converges to the wrong boundary, while logistic regression keeps approaching the best linear one: lower asymptotic error.',
      'The learning curves show both effects. With 20 features and 40 examples: naive Bayes 8.9% error, logistic regression 12.4%, full LDA 15.8% (it must estimate 210 covariance entries). By 400 examples they converge near the 5.9% Bayes error. In the far-subgroup world, LDA levels off near 20% while logistic regression keeps improving to about 16%.',
      'The far subgroup is an outlier problem: those points are correctly classified and far from the boundary, so they barely affect logistic regression, yet they shift LDA’s class mean and inflate its covariance. Generative fits use every point to describe the class, not just the points that matter for the boundary.',
      'LDA also gives supervised dimensionality reduction. **Fisher’s linear discriminant** finds the direction w maximizing the between-class separation relative to the within-class spread, (wᵀ(μ₁ − μ₀))² / (wᵀΣw). The answer is w ∝ Σ⁻¹(μ₁ − μ₀) — the same θ. With K classes it gives up to K − 1 directions for plotting and preprocessing.',
    ],
    formula: 'Fisher: maximize (wᵀ(μ₁ − μ₀))² / wᵀΣw  ⇒  w ∝ Σ⁻¹(μ₁ − μ₀)',
    experiment: 'In “Learning curves”, compare the 2-feature and 20-feature settings. In which one does the choice of model matter more at 40 examples?',
    question: 'At 40 examples with 20 features, naive Bayes has 8.9% error and logistic regression 12.4%. How many percentage points lower is naive Bayes?',
    answer: 3.5, tolerance: 0.01,
    explanation: '12.4 − 8.9 = 3.5 points — a large gain from assumptions that happen to be true here. With enough data, the gap disappears.',
    reflection: 'Which assumptions about your own data are reliable enough to “replace data” in this way?',
  },
  {
    id: 'l40-nb',
    title: '40.5 · Naive Bayes, missing values and generation',
    sections: ['Naive Bayes is diagonal GDA', 'Missing features for free', 'Sampling as a diagnostic', 'Beyond Gaussians', 'Demonstrate understanding'],
    skill: 'Relate naive Bayes to GDA and use a generative model to handle missing features and check its realism.',
    prerequisite: 'Lessons 40.1–40.4; naive Bayes for text (Lab 11).',
    paragraphs: [
      '**Gaussian naive Bayes** is GDA with a diagonal covariance: features are assumed independent given the class. Each feature then adds its own term to the log-odds, and only means and variances are estimated. Lab 11’s multinomial naive Bayes is the same idea with word counts instead of Gaussians.',
      'Because the log-odds is a sum of per-feature terms, a **missing feature** is handled by leaving its term out — exactly marginalizing it under the model. A discriminative model has no such principled option; it needs imputation (Lab 02).',
      'A generative model can **sample**: draw a class, then x from its Gaussian. If the samples look nothing like real data (wrong spread, missing clusters, impossible values), the model’s p(x | y) is wrong, and so may be its posterior. It is a cheap check that discriminative models cannot offer.',
      'Nothing forces Gaussians: class-conditional mixtures of Gaussians (Lab 43), kernel density estimates, or deep generative models (Labs 53–54) all plug into the same Bayes-rule classifier.',
      'You have completed this lab when you can: classify with Bayes’ rule from class-conditional models; derive and compute the GDA maximum-likelihood estimates; prove LDA’s boundary is linear and QDA’s quadratic; predict from assumptions and sample size which model wins; and use a generative model for missing features and realism checks. The Python challenge implements GDA, the LDA linear form and Gaussian naive Bayes with missing values.',
    ],
    formula: 'naive Bayes log-odds = log(φ/(1−φ)) + Σⱼ [log p(xⱼ | 1) − log p(xⱼ | 0)]',
    derivation: {
      title: 'One feature’s contribution in Gaussian naive Bayes',
      intro: 'A feature with class means m1 and m0 and shared variance v.',
      steps: [
        { prompt: 'log N(x; m1, v) − log N(x; m0, v) (the normalizing constants cancel). Write it in terms of x, m1, m0 and v.', answer: '((x-m0)^2 - (x-m1)^2)/(2*v)', show: '`((x − m0)² − (x − m1)²) / (2v)`', vars: { x: [-3, 3], m1: [-2, 2], m0: [-2, 2], v: [0.5, 3] } },
        { prompt: 'Simplify to linear form in x.', answer: '(m1-m0)*x/v - (m1^2-m0^2)/(2*v)', show: '`(m1 − m0)x/v − (m1² − m0²)/(2v)`', vars: { x: [-3, 3], m1: [-2, 2], m0: [-2, 2], v: [0.5, 3] } },
        { prompt: 'Evaluate it for x = 1, m1 = 2, m0 = 0, v = 4.', number: 0, show: '`0`', why: 'x = 1 is halfway between the means, so this feature is neutral.' },
      ],
      result: 'Each feature votes with a straight-line term; a larger variance v makes its vote quieter.',
    },
    experiment: 'In “Learning curves”, choose 20 features and trace naive Bayes against full LDA. Where does LDA misbehave, and why is the diagonal assumption harmless here?',
    question: 'Naive Bayes with three features: log-odds contributions 0.4, −1.1 and 0.9, and prior log-odds 0. Feature 2 is missing. What is the log-odds?',
    answer: 1.3, tolerance: 1e-6,
    explanation: 'Leave out the missing feature’s term: 0.4 + 0.9 = 1.3. With it, the log-odds would have been 0.2.',
    reflection: 'Where in your data are features often missing? How are they handled today?',
  },
]

export const sources = [
  { title: 'Ng & Jordan (2002) · On discriminative vs. generative classifiers: logistic regression and naive Bayes', url: 'https://papers.nips.cc/paper/2020-on-discriminative-vs-generative-classifiers-a-comparison-of-logistic-regression-and-naive-bayes' },
  { title: 'Stanford CS229 lecture notes · Generative learning algorithms', url: 'https://cs229.stanford.edu/main_notes.pdf' },
  { title: 'Hastie, Tibshirani & Friedman · The Elements of Statistical Learning, §4.3 (free book)', url: 'https://hastie.su.domains/ElemStatLearn/' },
  { title: 'scikit-learn · Linear and quadratic discriminant analysis (shrinkage)', url: 'https://scikit-learn.org/stable/modules/lda_qda.html' },
]
