// Lesson order for Lab 22: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l22-sgd': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { figure: 'BatchSpread', caption: 'How much a mini-batch gradient varies from batch to batch, against the batch size.' },
    { predict: { prompt: 'A single-example gradient varies with spread 8. Roughly what spread does a batch of 16 have?', answer: 2, tolerance: 0.01, explain: 'The spread falls like 1/√B: 8/√16 = 8/4 = 2.', misconceptions: [{ answer: 0.5, feedback: 'That divides by 16. The spread falls with the square root of the batch size.' }] } },
    { p: 2 }, { p: 3 },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l22-momentum': [
    { p: 0 },
    { p: 1 },
    { cell: 0 },
    { predict: { prompt: 'Momentum with β = 0.9 starts at v = 0, and the gradient is 1 on both of the first two steps. What is v after step 2?', answer: 1.9, tolerance: 0.001, explain: 'Step 1: v = 0.9 × 0 + 1 = 1. Step 2: v = 0.9 × 1 + 1 = 1.9.', misconceptions: [{ answer: 2, feedback: 'The old velocity is multiplied by β = 0.9 before the new gradient is added.' }] } },
    { p: 2 },
    { figure: 'ValleyPaths', caption: 'Gradient descent (grey) and momentum (blue) on the elongated valley, 150 steps each.' },
    { cell: 1 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l22-adam': [
    { p: 0 }, { p: 1 }, { p: 2 }, { p: 3 },
    { cell: 0 },
    { figure: 'AdamScale', caption: 'The first update of gradient descent and of Adam, as the gradient’s size changes by a factor of a million.' },
    { predict: { prompt: 'Adam with α = 0.01 and bias correction sees a first gradient of g = 100. How large is its first step?', answer: 0.01, tolerance: 0.0001, explain: 'After correction m̂ = 100 and v̂ = 100², so the step is α × 100/100 = α = 0.01. Plain gradient descent would step α × 100 = 1.', misconceptions: [{ answer: 1, feedback: 'That is gradient descent’s step, α·g. Adam divides by √v̂ = |g|.' }] } },
    { p: 4 },
    { cell: 1 },
    { math: true },
  ],
  'l22-schedules': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'ScheduleCurves', caption: 'Four learning-rate schedules over 1,000 steps.' },
    { cell: 0 },
    { p: 3 },
    { cell: 1 },
    { predict: { prompt: 'A gradient (6, 8) is clipped to length c = 5. What is its first component after clipping?', answer: 3, tolerance: 0.001, explain: 'Its length is 10, so it is scaled by 5/10: (3, 4). The direction is unchanged.', misconceptions: [{ answer: 5, feedback: 'Clipping rescales the whole vector to length 5; it does not cap each component at 5.' }] } },
    { p: 4 },
    { math: true },
  ],
  'l22-diagnose': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { p: 2 }, { p: 3 },
    { cell: 1 },
    { predict: { prompt: 'In the cell above, run B’s training loss rises from 1.81 to 13.5 million. Is that a bug (1), an optimization problem (2), or a generalization problem (3)?', answer: 1, explain: 'A training loss that rises steadily from the first step is a bug until proven otherwise: here the update adds the gradient instead of subtracting it. Run A (jumping loss) is an optimization problem; run C (training error to 7e−7, validation lowest near step 500 then rising) is a generalization problem.', misconceptions: [{ answer: 2, feedback: 'An optimizer with too large a rate makes the loss jump around; here it climbs steadily from the first step, the signature of a wrong sign.' }, { answer: 3, feedback: 'Generalization problems need a low training loss first. Here the training loss itself explodes.' }] } },
    { p: 4 },
    { math: true },
    { ladder: 'optim' },
  ],
}
