import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l22-sgd',
    title: '22.1 · Stochastic and mini-batch gradients',
    sections: ['Full-batch gradients are expensive', 'An unbiased estimate', 'Noise as a feature and a bug', 'Epochs and batch size', 'Put it into practice'],
    skill: 'Explain stochastic and mini-batch gradient descent and choose a batch size.',
    prerequisite: 'Labs 01–21; gradient descent (Labs 01, 03), neural networks (Lab 21).',
    paragraphs: [
      'Every training step so far computed the gradient over the whole training set. With 10 million examples, one step means 10 million forward and backward passes — and you need thousands of steps.',
      'The full gradient is an average over examples, so the average over a random subset — a **mini-batch** of B examples — is an **unbiased** estimate of it: correct on average, noisy in any single step. Its noise shrinks like 1/√B (Lab 05). B = 1 is **stochastic gradient descent** (SGD); B = n is full-batch descent.',
      'Mini-batch noise makes each step less precise, but many cheap steps usually beat few precise ones. The noise also helps escape flat regions and sharp minima. Near the optimum, though, noise keeps parameters jittering around it — a **noise floor** that only a smaller learning rate removes.',
      'An **epoch** is one pass over the training data. With n = 256 and B = 8, one epoch is 32 updates. Shuffle the data every epoch so batches differ. Typical batch sizes are 32–512, chosen so a batch fills the GPU\'s parallel hardware; the learning rate often needs adjusting when B changes.',
      'In the playground\'s mini-batch view, batch 1 falls fastest per epoch but stays noisy; the full batch is smooth and slow. A decaying learning-rate schedule gets the best of both.',
    ],
    formula: 'g_B = (1/B) Σ_{i∈B} ∇ℓᵢ(w)     E[g_B] = ∇L(w)     noise ∝ 1/√B',
    experiment: 'In "Mini-batches & schedules", compare batch 1, 8 and 256 with a constant rate, then switch to cosine decay. Which curve reaches the lowest final loss?',
    question: 'A training set has 256 examples and the batch size is 8. How many parameter updates happen in one epoch?',
    answer: 32,
    explanation: '256 / 8 = 32 updates per epoch; full-batch descent makes only 1.',
    reflection: 'If your dataset had 50 million rows, what batch size and number of epochs would you try first? Why?',
  },
  {
    id: 'l22-momentum',
    title: '22.2 · Momentum',
    sections: ['Zig-zag in a valley', 'A running velocity', 'Why it helps', 'Choosing β', 'State you must save'],
    skill: 'Explain momentum as an exponentially weighted velocity and predict its effect on ill-conditioned problems.',
    prerequisite: 'Lesson 22.1; condition numbers (Lab 03).',
    paragraphs: [
      'In an elongated valley (large condition number κ, Lab 03), the gradient points mostly across the valley. Gradient descent bounces between the walls while creeping along the floor; a learning rate large enough to move along the floor makes it overshoot the walls.',
      '**Momentum** keeps a velocity: `v ← βv + g`, then `w ← w − αv`. The velocity is an exponentially weighted sum of past gradients: recent ones count most, older ones decay by β per step.',
      'Across the valley, gradients alternate in sign and largely cancel in v; along the floor they point the same way every step and accumulate. With β = 0.9 a consistent gradient builds up to about 1/(1 − β) = 10 times its size. The result: damped oscillation and faster progress, visible in the playground\'s valley.',
      'β = 0.9 is the usual default; 0.99 gives more smoothing but more overshoot. Too much momentum can orbit the minimum before settling — watch the Rosenbrock path.',
      'The velocity is **optimizer state**: part of what training depends on, besides the weights. Resuming training from a checkpoint without it changes the dynamics (Lab 23).',
    ],
    formula: 'v ← βv + g     w ← w − αv     steady velocity for constant g: g/(1 − β)',
    experiment: 'On the elongated valley, compare gradient descent and momentum at α = 0.035, then raise κ to 100. Which one copes?',
    question: 'With β = 0.9 and a constant gradient g = 1, what velocity does momentum approach?',
    answer: 10,
    explanation: 'v = βv + 1 converges to 1/(1 − 0.9) = 10.',
    reflection: 'Explain momentum using a physical analogy, then say where the analogy breaks down.',
  },
  {
    id: 'l22-adam',
    title: '22.3 · Adaptive steps: RMSProp and Adam',
    sections: ['One learning rate is not enough', 'Scale by recent gradient size', 'Adam combines both', 'Bias correction', 'Defaults and caveats'],
    skill: 'Explain RMSProp and Adam, including Adam’s bias correction, and apply their defaults.',
    prerequisite: 'Lessons 22.1–22.2.',
    paragraphs: [
      'Parameters differ wildly in gradient scale: embedding rows seen rarely, biases with huge gradients, weights in steep and flat directions. A single learning rate is too big for some and too small for others.',
      '**RMSProp** keeps a running average of squared gradients per parameter, `r ← ρr + (1 − ρ)g²`, and divides each step by its square root: `w ← w − α g/(√r + ε)`. Parameters with large gradients take smaller steps; parameters with small gradients take larger ones.',
      '**Adam** combines momentum\'s running mean m with RMSProp\'s running square v: `m ← β₁m + (1 − β₁)g`, `v ← β₂v + (1 − β₂)g²`, step `α·m̂/(√v̂ + ε)`. Defaults β₁ = 0.9, β₂ = 0.999, ε = 10⁻⁸ work across a surprising range of problems.',
      'm and v start at 0, so early averages are biased toward zero. **Bias correction** divides by `1 − βᵗ`: m̂ = m/(1 − β₁ᵗ). At t = 1, m = 0.1·g and m̂ = g exactly; without the correction, the first steps would be ten times too small (and the v correction matters even more).',
      'Adam usually converges quickly with little tuning, which makes it the common default for neural networks. Well-tuned SGD with momentum sometimes generalizes slightly better. With L2 regularization, use **AdamW**, which applies weight decay directly rather than through the adaptive gradient.',
    ],
    formula: 'm ← β₁m + (1−β₁)g   v ← β₂v + (1−β₂)g²   m̂ = m/(1−β₁ᵗ)   v̂ = v/(1−β₂ᵗ)   w ← w − α m̂/(√v̂ + ε)',
    experiment: 'On "Flat plateau then steep bowl", compare gradient descent with Adam at the same α. Why does Adam cross the plateau so much faster?',
    question: 'With β₁ = 0.9 and a first gradient g = 2, m = 0.1 × 2 = 0.2 after one step. What is the bias-corrected m̂ = m / (1 − 0.9¹)?',
    answer: 2,
    explanation: '0.2 / 0.1 = 2: exactly the first gradient, as intended.',
    reflection: 'Why is per-parameter scaling useful for networks where some parameters receive gradients rarely?',
  },
  {
    id: 'l22-schedules',
    title: '22.4 · Learning-rate schedules and gradient scale',
    sections: ['Big steps early, small steps late', 'Common schedules', 'Warm-up', 'Exploding gradients and clipping', 'Initialization revisited'],
    skill: 'Choose a learning-rate schedule and protect training against exploding gradients.',
    prerequisite: 'Lessons 22.1–22.3; initialization (Lab 21).',
    paragraphs: [
      'A large learning rate makes fast progress but, with noisy mini-batch gradients, keeps bouncing around the minimum. A small one settles precisely but is slow. **Schedules** change the rate during training to get both.',
      '**Step decay** divides the rate by 10 at fixed epochs. **Cosine decay** lowers it smoothly to near zero: `α_t = α₀ · ½(1 + cos(π t/T))`. At the halfway point t = T/2, the cosine term is 0, so α_t = α₀/2.',
      '**Warm-up** increases the rate linearly over the first few hundred steps. Early gradients (with random weights and Adam\'s fresh statistics) can be large and unrepresentative; warm-up keeps them from wrecking the initialization. It is standard for transformers (Lab 26).',
      'If a gradient\'s norm suddenly becomes huge — a rare batch, a steep cliff in the loss — a single update can throw the weights somewhere useless. **Gradient clipping** rescales the gradient when its norm exceeds a threshold: `g ← g · min(1, c/‖g‖)`. It is essential for recurrent networks (Lab 25).',
      'Gradient scale also depends on initialization and depth: too-small weights shrink signals layer by layer (vanishing), too-large ones grow them (exploding). He/Xavier initialization, normalization layers and residual connections keep gradients in a healthy range.',
    ],
    formula: 'cosine: α_t = α₀·½(1 + cos(πt/T))     clipping: g ← g·min(1, c/‖g‖)',
    experiment: 'In the mini-batch view with batch 1 and rate 0.1, compare constant, step and cosine schedules. How does each end?',
    question: 'Cosine decay with α₀ = 0.1: what is the learning rate halfway through training (t = T/2)?',
    answer: 0.05,
    explanation: 'cos(π/2) = 0, so α = 0.1 × ½ × (1 + 0) = 0.05.',
    reflection: 'You see occasional spikes in your training loss. Which of the tools in this lesson would you try first, and why?',
  },
  {
    id: 'l22-diagnose',
    title: '22.5 · Diagnosing training failures',
    sections: ['Three kinds of failure', 'Bugs', 'Optimization problems', 'Generalization problems', 'Demonstrate understanding'],
    skill: 'Distinguish numerical bugs from optimization failures and generalization failures using loss curves and targeted checks.',
    prerequisite: 'Lessons 22.1–22.4; gradient checking (Lab 20); overfitting (Lab 07).',
    paragraphs: [
      'When a network disappoints, the cause is usually one of three kinds. Treating the wrong one wastes days: no optimizer fixes a sign error, and no bug fix cures a too-small dataset.',
      '**Bugs**: training loss rises from the start, is NaN, or cannot even overfit a handful of examples. Checks: gradient-check each layer (Lab 20); overfit 10 examples to near-zero loss; confirm labels line up with inputs; inspect the initial loss (≈ log k for k balanced classes).',
      '**Optimization problems**: the code is right but training does not reduce the loss well. Symptoms: divergence or wild oscillation (rate too high), a nearly flat curve (rate too low, saturated units, vanishing gradients), long plateaus. Fixes: tune the rate first, then optimizer, initialization, normalization, architecture.',
      '**Generalization problems**: training loss is low but validation loss is high or rising. Fixes: more or better data, augmentation, regularization, early stopping, a smaller model — not the optimizer. Evaluate honestly (Lab 06) before concluding anything.',
      'You have completed this lab when you can: explain mini-batch noise; derive momentum\'s velocity; implement Adam with bias correction; choose schedules and clipping; and, given a loss curve, classify the failure and name the next check. The playground\'s diagnosis gallery practises exactly that; the Python challenge implements the optimizers.',
    ],
    formula: 'rising train loss → bug · flat/unstable train loss → optimization · train ↓ val ↑ → generalization',
    experiment: 'In "Diagnose a training failure", classify all six cases before revealing each. Write your reasoning in the notebook.',
    question: 'Training loss falls to 0.001 while validation loss rises from 0.4 to 1.3. Is this a bug (1), an optimization problem (2), or a generalization problem (3)?',
    answer: 3,
    explanation: 'The optimizer is doing its job — training loss is tiny. The model does not generalize: overfitting.',
    reflection: 'Write your personal checklist for the first 30 minutes of debugging a network that "doesn\'t learn".',
  },
]

export const sources = [
  { title: 'Dive into Deep Learning · Chapter 12: optimization algorithms', url: 'https://d2l.ai/chapter_optimization/index.html' },
  { title: 'Kingma & Ba (2015) · Adam: a method for stochastic optimization', url: 'https://arxiv.org/abs/1412.6980' },
  { title: 'Loshchilov & Hutter (2019) · Decoupled weight decay regularization (AdamW)', url: 'https://arxiv.org/abs/1711.05101' },
  { title: 'Karpathy · A recipe for training neural networks', url: 'https://karpathy.github.io/2019/04/25/recipe/' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
