export const GAMES = [
  {
    key: 'circuit-clash',
    label: 'Circuit Clash',
    emoji: '🏎️',
    color: 'emerald',
    desc: 'A third-person kart combat racer: mountain circuit, garage upgrades, weapons and Q-learning rivals. Play the software engineering course reference.',
    path: '/game/circuit-clash',
    tags: ['3D', 'Racing', 'Software Engineering', 'Q-learning'],
    cover: { grad: 'from-emerald-800 via-teal-900 to-slate-900', mark: 'CC', sub: 'Play first. Build it yourself.' },
  },
  {
    key: 'rubiks-cube',
    label: "Rubik's Cube",
    emoji: '🎲',
    color: 'emerald',
    desc: "Group theory, permutations & non-commutativity through the world's most famous puzzle.",
    path: '/game/rubiks-cube',
    tags: ['Group Theory', 'Linear Algebra', 'Math', 'Puzzle'],
    cover: { grad: 'from-emerald-700 via-green-800 to-teal-900', mark: '3×3', sub: 'Group Theory' },
  },
  {
    key: 'matrix-game',
    label: 'Linear Algebra Arcade',
    emoji: 'λ',
    color: 'cyan',
    desc: 'Seven interactive lessons — vectors, transforms, determinants & eigenvectors.',
    path: '/game/matrix-game',
    tags: ['Linear Algebra', 'Interactive', 'Math', 'Vectors', 'Matrices'],
    cover: { grad: 'from-cyan-700 via-sky-800 to-blue-900', mark: '[Ax]', sub: '7 Interactive Lessons' },
  },
  {
    key: 'stem-tetris',
    label: 'STEM Tetris',
    emoji: '🟦',
    color: 'fuchsia',
    desc: 'Classic Tetris with six STEM lenses: matrix ops, 2×2 transforms, probability distributions.',
    path: '/game/stem-tetris',
    tags: ['Math', 'CS', 'Arcade', 'Probability', 'Matrices'],
    cover: { grad: 'from-fuchsia-700 via-purple-800 to-violet-900', mark: '████', sub: '6 STEM Lenses' },
  },
  {
    key: 'card-quest',
    label: 'Card Quest',
    emoji: '🎲',
    color: 'violet',
    desc: 'Master counting, probability, permutations, statistics & linear algebra through cards and dice.',
    path: '/game/card-quest',
    tags: ['Probability', 'Combinatorics', 'Statistics'],
    cover: { grad: 'from-violet-700 via-purple-800 to-indigo-900', mark: '⚄ C(n,r)', sub: 'Math Through Play' },
  },
  {
    key: 'card-academy',
    label: 'STEM Card Academy',
    emoji: '🃏',
    color: 'indigo',
    desc: 'Five card games teaching probability, statistics & neuroscience through play.',
    path: '/game/card-academy',
    tags: ['Probability', 'Statistics'],
    cover: { grad: 'from-indigo-700 via-violet-800 to-purple-900', mark: '♠ ♥', sub: 'Probability & Stats' },
  },
  {
    key: 'asteroids-la',
    label: 'Vector Asteroids',
    emoji: '🌀',
    color: 'violet',
    desc: 'Blast rocks through 10 waves — velocity, dot products, matrix transforms via gameplay.',
    path: '/game/asteroids-la',
    tags: ['Linear Algebra', 'Arcade', 'Physics', 'Vectors', 'Space'],
    cover: { grad: 'from-violet-700 via-indigo-800 to-blue-900', mark: 'v→', sub: '10 Waves' },
  },
  {
    key: 'vector-command',
    label: 'Vector Command 3D',
    emoji: '🚀',
    color: 'cyan',
    desc: 'Full 3D mission campaign: use RREF, Cross Products, and Integrals to intercept targets.',
    path: '/game/vector-command',
    tags: ['Linear Algebra', '3D', 'Calculus', 'Physics', 'Space', 'Geometry'],
    cover: { grad: 'from-cyan-700 via-blue-800 to-indigo-900', mark: 'R³', sub: '3D Missions' },
  },
  {
    key: 'arkanoid',
    label: 'Arkanoid Learn',
    emoji: '🎮',
    color: 'rose',
    desc: 'Break bricks by answering math questions. Miss one and the wall fights back.',
    path: '/game/arkanoid',
    tags: ['Arcade', 'Math'],
    cover: { grad: 'from-rose-700 via-pink-800 to-red-900', mark: '▬▬▬', sub: 'Math Breakout' },
  },
  {
    key: 'stem-quest',
    label: 'STEM Quest',
    emoji: '🗺️',
    color: 'amber',
    desc: 'An interactive adventure map packed with multi-subject STEM challenges.',
    path: '/game/stem-quest',
    tags: ['Adventure', 'Multi-subject'],
    cover: { grad: 'from-amber-600 via-orange-700 to-red-800', mark: '◈◈◈', sub: 'STEM Adventure' },
  },
  {
    key: 'open-craft',
    label: 'OpenCraft',
    emoji: '⛏️',
    color: 'teal',
    desc: 'Build and explore in a physics-based voxel sandbox.',
    path: '/game/open-craft',
    tags: ['Sandbox', 'Physics', '3D', 'Voxel', 'Simulation'],
    cover: { grad: 'from-teal-700 via-cyan-800 to-blue-900', mark: '⬛⬛', sub: 'Physics Sandbox' },
  },
  {
    key: 'reality-runner',
    label: 'Reality Runner',
    emoji: '🏃',
    color: 'sky',
    desc: 'Run through physics simulations and dodge equations in real time.',
    path: '/game/reality-runner',
    tags: ['Runner', 'Physics'],
    cover: { grad: 'from-sky-600 via-blue-700 to-indigo-800', mark: '▶▶▶', sub: 'Physics Runner' },
  },
  {
    key: 'basketball',
    label: 'Basketball Lab',
    emoji: '🏀',
    color: 'orange',
    desc: 'Apply trajectory and calculus to perfect your arc and sink every shot.',
    event: 'basketball',
    tags: ['Physics', 'Calculus'],
    cover: { grad: 'from-orange-600 via-red-700 to-rose-800', mark: '⌒', sub: 'Trajectory · Calculus' },
  },
  {
    key: 'pool',
    label: 'Physics Pool',
    emoji: '🎱',
    color: 'purple',
    desc: 'Explore collision physics and bank angles on the felt.',
    event: 'pool',
    tags: ['Physics', 'Geometry'],
    cover: { grad: 'from-purple-700 via-violet-800 to-indigo-900', mark: '⊙●', sub: 'Collision Physics' },
  },
  {
    key: 'golf',
    label: 'Mini Golf',
    emoji: '⛳',
    color: 'green',
    desc: 'Apply geometry and projectile motion to sink every putt.',
    event: 'golf',
    tags: ['Geometry', 'Physics'],
    cover: { grad: 'from-green-600 via-emerald-700 to-teal-800', mark: '⌒⛳', sub: 'Geometry · Projectile' },
  },
  {
    key: 'football',
    label: 'Football Calculus',
    emoji: '🏈',
    color: 'amber',
    desc: 'Use integration and optimization to analyse routes and trajectories.',
    event: 'football',
    tags: ['Calculus', 'Sports'],
    cover: { grad: 'from-amber-600 via-yellow-700 to-orange-800', mark: '∫ dt', sub: 'Integration & Routes' },
  },
]
