// Lesson order for Lab 10: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l10-idea': [
    { p: 0 }, { cell: 0 }, { p: 1 },
    { figure: 'QueryNeighbours', caption: 'Move the query (circle); lines connect it to its k nearest training points.' },
    { cell: 1 },
    { p: 2 },
    { predict: { prompt: 'k = 7 and the neighbours’ labels are 1, 0, 0, 1, 1, 1, 0. What is the class-1 share? (Three decimals.)', answer: 0.571, tolerance: 0.001, explain: '4 of 7 = 0.571, so class 1 wins the vote.' } },
    { p: 3 }, { cell: 2 }, { p: 4 },
    { math: true },
  ],
  'l10-distance': [
    { p: 0 },
    { figure: 'DistanceShapes', caption: 'All points at the same distance from a: a circle for Euclidean, a diamond for Manhattan.' },
    { predict: { prompt: 'What is the Manhattan distance between (0, 0) and (3, −2)?', answer: 5, explain: '|3| + |−2| = 5. The Euclidean distance would be √13 ≈ 3.61.' } },
    { cell: 0 },
    { p: 1 },
    { figure: 'UnitsStripes', caption: '7-NN decision regions when one feature is recorded in much larger units.' },
    { cell: 1 },
    { p: 2 }, { cell: 2 }, { p: 3 }, { p: 4 },
    { math: true },
    { ladder: 'knn' },
  ],
  'l10-k': [
    { p: 0 }, { cell: 0 }, { p: 1 }, { p: 2 },
    { figure: 'ChooseK', caption: 'Decision regions and the train/validation accuracy curve as k grows.' },
    { cell: 1 },
    { p: 3 }, { cell: 2 }, { cell: 3 }, { p: 4 },
    { math: true },
  ],
  'l10-curse': [
    { p: 0 }, { p: 1 },
    { figure: 'DistanceConcentration', caption: 'How much farther is the farthest point than the nearest, as dimension grows?' },
    { cell: 0 },
    { p: 2 },
    { figure: 'NeighbourhoodSide', caption: 'Side length of a cube-shaped neighbourhood holding a fixed share of uniform data.' },
    { predict: { prompt: 'In 3 dimensions, a cube holding 12.5% of uniform data has side 0.125^(1/3). What is it?', answer: 0.5, tolerance: 0.001, explain: '0.5³ = 0.125, so the side is 0.5 — half of every feature’s range.' } },
    { cell: 1 },
    { p: 3 },
    { figure: 'IrrelevantFeatures', caption: 'Two useful features, plus a growing number of pure-noise features.' },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l10-practice': [
    { p: 0 },
    { figure: 'NeighbourTable', caption: 'The seven training rows behind one prediction.' },
    { cell: 0 },
    { p: 1 },
    { figure: 'NearDuplicateLeak', caption: 'Repeated recordings of the same items, split two ways.' },
    { cell: 1 },
    { p: 2 },
    { figure: 'PredictionCost', caption: 'The work one brute-force prediction does.' },
    { predict: { prompt: 'Brute-force k-NN stores 50,000 rows with 8 features. How many feature differences does one prediction compute?', answer: 400000, explain: '50,000 × 8 = 400,000 — for every single query.' } },
    { p: 3 }, { cell: 2 }, { p: 4 },
    { math: true },
  ],
}
