import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l10-idea',
    title: '10.1 · Predict from similar examples',
    sections: ['No formula, just memory', 'The algorithm', 'Classification and regression', 'The cost moves to prediction time', 'Put it into practice'],
    skill: 'Describe and apply the k-nearest-neighbour rule for classification and regression.',
    prerequisite: 'Labs 01–09; distance between points; validation and metrics (Labs 06, 09).',
    paragraphs: [
      'How long will a new 42 MB build take? Find the five past builds most like it and average their times. That is the entire idea of **k-nearest neighbours** (k-NN): no weights, no training loop — predict from the most similar stored examples.',
      'To predict for a query x: compute its distance to every training example; take the k closest; for classification return the majority label (or the fraction of class 1 as a probability); for regression return the mean of their targets. The playground draws lines from the query to its k neighbours and counts their votes.',
      'The same rule works for any target type because it only averages or votes over neighbours. With k = 5 and neighbours labeled 1, 1, 0, 1, 0, the class-1 share is 0.6, so the prediction is class 1 with an estimated probability of 0.6.',
      'Every model so far did its expensive work once, during training, then predicted cheaply. k-NN is a **lazy learner**: training just stores the data, and each prediction scans all n stored rows. Prediction cost grows with the dataset, and the whole dataset must be shipped with the model. Tree and graph indexes (k-d trees, approximate nearest-neighbour search) reduce the scan in practice.',
      'Procedure: choose features whose distances mean "similar for this purpose"; scale them; choose k by validation; inspect the neighbours behind a few predictions — being able to point to the examples a prediction came from is k-NN\'s great strength for explaining and debugging.',
    ],
    formula: 'ŷ(x) = mean{ yᵢ : i ∈ N_k(x) }     N_k(x) = the k training points closest to x',
    experiment: 'Click several places near the class boundary on "Two moons". Before each click, predict how many of the 5 neighbours will be class 1.',
    question: 'The 5 nearest neighbours of a query have labels 1, 1, 0, 1, 0. What fraction of the votes are class 1?',
    answer: 0.6,
    explanation: 'Three of five votes: 0.6. The majority rule predicts class 1; 0.6 is a (rough) probability estimate.',
    reflection: 'For your own data, which past examples would you consider "similar" to a new case? Which features define that similarity?',
  },
  {
    id: 'l10-distance',
    title: '10.2 · What does "near" mean?',
    sections: ['Euclidean distance', 'Manhattan distance', 'Units dominate distance', 'Standardize first', 'Choosing features is choosing similarity'],
    skill: 'Compute Euclidean and Manhattan distances and explain why feature scaling determines which neighbours are chosen.',
    prerequisite: 'Lesson 10.1; standardization from Labs 02 and 03.',
    paragraphs: [
      'The **Euclidean distance** between (1, 2) and (4, 6) is the straight-line length `√((4−1)² + (6−2)²) = √(9 + 16) = 5`. In general, `√Σ(aⱼ − bⱼ)²`. The **Manhattan distance** adds absolute differences instead — `|3| + |4| = 7` — like walking city blocks. They produce differently shaped neighbourhoods: circles versus diamonds.',
      'Distances add up contributions from every feature. If one feature is recorded in centimetres and another in metres, the centimetre feature\'s differences are 100 times larger and dominate the sum. The playground\'s "units of x2" control shows the effect: at × 1000, neighbours are chosen almost purely by x2, and the decision regions become horizontal stripes.',
      'Standardize each feature with the training mean and standard deviation, so that one standard deviation counts the same in every direction. As in Lab 02, compute these statistics on training data only and apply them unchanged to queries.',
      'Standardization is a default, not a truth. If one feature genuinely matters more for similarity, you can weight it; if a feature is irrelevant, it adds noise to every distance and should be removed. Choosing and scaling features **is** choosing what similarity means.',
      'Categorical features need their own treatment (for example one-hot encoding, where two different categories are distance √2 apart), and mixed data may need a custom distance. Whatever you choose, inspect a few neighbour sets and ask whether they look similar to a domain expert.',
    ],
    formula: 'd₂(a, b) = √Σⱼ (aⱼ − bⱼ)²     d₁(a, b) = Σⱼ |aⱼ − bⱼ|',
    experiment: 'Set x2 units to × 1000 with standardization off and note validation accuracy. Turn standardization on. Then compare Euclidean and Manhattan on "XOR quadrants".',
    question: 'What is the Euclidean distance between (1, 2) and (4, 6)?',
    answer: 5,
    explanation: '√(3² + 4²) = √25 = 5. The Manhattan distance would be 3 + 4 = 7.',
    reflection: 'List your features with their units. Which one would dominate a raw Euclidean distance? What does that imply for k-NN or clustering on your data?',
  },
  {
    id: 'l10-k',
    title: '10.3 · Choosing k: bias and variance again',
    sections: ['k = 1 memorizes', 'Large k smooths', 'The validation curve', 'Ties and weighting', 'Local versus global'],
    skill: 'Choose k by validation and explain its bias–variance effect.',
    prerequisite: 'Lessons 10.1–10.2; bias and variance (Lab 07).',
    paragraphs: [
      'With k = 1, each training point is its own nearest neighbour, so training accuracy is 100% — and says nothing about generalization. The decision regions trace every noisy point, like a high-degree polynomial.',
      'As k grows, each prediction averages over a larger neighbourhood: the boundary smooths out and random noise averages away (lower variance), but real structure smaller than the neighbourhood is blurred (higher bias). At k = n every query gets the same prediction — the majority class.',
      'Plot training and validation accuracy against k (the "Choosing k" view). Training accuracy falls from 100%; validation accuracy usually rises, peaks, then falls. Pick k near the peak — preferably the largest k within noise of the best, for stability.',
      'With two classes, an odd k avoids tied votes. **Distance weighting** (each vote weighted by 1/distance) lets close neighbours count more and makes the choice of k less critical. Both are small refinements; the bias–variance behaviour stays the same.',
      'k-NN is a **local** method: it makes no assumption about a global shape like a line or a parabola. That is powerful when the true boundary is complicated and data are plentiful, and weak when data are sparse — which, as the next lesson shows, is almost always the case in many dimensions.',
    ],
    formula: 'small k → low bias, high variance     large k → high bias, low variance',
    experiment: 'In "Choosing k", compare "Two moons" and "Overlapping blobs". Where is the best k for each, and why does the noisier dataset prefer larger k?',
    question: 'Two-class k-NN with k = 4 gets votes 2 for class 0 and 2 for class 1. What is the class-1 vote share?',
    answer: 0.5,
    explanation: '2/4 = 0.5 — a tie. An odd k (3 or 5) avoids ties for two classes; otherwise a tie-breaking rule is needed.',
    reflection: 'How would you explain the choice of k to a colleague using the words bias and variance?',
  },
  {
    id: 'l10-curse',
    title: '10.4 · The curse of dimensionality',
    sections: ['Space grows faster than data', 'Distances concentrate', 'Neighbourhoods stop being local', 'Irrelevant features hurt', 'What to do'],
    skill: 'Explain why distance-based methods degrade with many features, and what to do about it.',
    prerequisite: 'Lessons 10.1–10.3.',
    paragraphs: [
      'To cover a line segment with points spaced 0.1 apart takes 10 points; a square, 100; a 10-dimensional cube, 10¹⁰. Data do not grow with dimension, so in many dimensions the training set is spread impossibly thin.',
      'Worse, distances **concentrate**: with many random features, the nearest and the farthest points from a query are almost the same distance away. The playground measures it: with 400 uniform points, the farthest/nearest ratio is huge in 2 dimensions and barely above 1 in 300. When everything is about equally far, "nearest" carries little information.',
      'To capture even 10% of uniformly spread data in d dimensions, a cube-shaped neighbourhood needs side length `0.1^(1/d)`: 0.1 in 1D, about 0.32 in 2D, about 0.79 in 10D. The "local" neighbourhood spans most of the range of every feature.',
      'Each irrelevant feature adds a random amount to every distance, drowning the relevant differences. A k-NN model with 3 useful features and 50 noise features can be far worse than one with only the 3.',
      'Remedies: select or engineer few, relevant features; reduce dimension with PCA (Lab 18) or learned embeddings (Lab 25); or use models that learn which features matter, like trees and linear models. Real data often lie near a lower-dimensional structure, which is why k-NN still works surprisingly often.',
    ],
    formula: 'side of a cube holding fraction f of uniform data in d dims: f^(1/d)',
    experiment: 'In the curse view, read the ratio at d = 1, 10, 100 and 300. Change the seed: is the trend stable?',
    question: 'In 2 dimensions, a square neighbourhood holding 25% of uniform data has side length 0.25^(1/2). What is it?',
    answer: 0.5,
    explanation: '√0.25 = 0.5: half the range of each feature. In 20 dimensions, the side would be 0.25^(1/20) ≈ 0.93.',
    reflection: 'How many features does your data have? Which could you remove or combine before using a distance-based method?',
  },
  {
    id: 'l10-practice',
    title: '10.5 · k-NN in practice: inspect, compare, decide',
    sections: ['Explain a prediction by its neighbours', 'Leakage through near-duplicates', 'Runtime and memory', 'Compare against simpler models', 'Demonstrate understanding'],
    skill: 'Use k-NN responsibly: explain predictions, avoid duplicate leakage, account for cost, and compare with baselines.',
    prerequisite: 'Lessons 10.1–10.4; group splits (Lab 06).',
    paragraphs: [
      'For any prediction, list its k neighbours with their labels and distances. Surprising neighbours reveal bad features, mislabeled examples or scaling mistakes faster than any metric. This transparency is k-NN\'s main practical advantage.',
      'k-NN is especially vulnerable to near-duplicates across a split: a reading from the same machine, or the same document with a changed timestamp, becomes the nearest neighbour of its twin. Validation accuracy soars and deployment disappoints. Use group splits (Lab 06) whenever repeated measurements exist.',
      'Prediction scans all n training rows for each query: O(n·d) work per prediction. For 10 million rows and thousands of queries per second, that is too slow without an index. Memory holds the full training set. Measure latency before committing to k-NN in a service.',
      'Always compare with a simple model on the same validation folds: majority class, logistic regression, a small tree. If k-NN only wins through suspiciously close neighbours, suspect leakage; if it loses, prefer the simpler model.',
      'You have completed this lab when you can: compute distances; explain how scaling changes neighbours; choose k from a validation curve; explain why many features break distance; and justify k-NN — or reject it — against a baseline. The Python challenge implements k-NN with vectorized distances.',
    ],
    formula: 'prediction cost ∝ n · d per query (brute force)',
    experiment: 'Pick a validation point near the boundary (click near it). Are its neighbours plausible? Then compare k-NN\'s validation accuracy with logistic regression\'s from Lab 08 on the same dataset.',
    question: 'A brute-force k-NN model stores 10,000 training rows with 20 features. How many feature differences must it compute to predict one query?',
    answer: 200000,
    explanation: '10,000 rows × 20 features = 200,000 differences (then squares, sums and a partial sort). Training cost was zero; prediction pays all of it.',
    reflection: 'Would k-NN be acceptable for your latency and memory budget? What would you compare it against?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapters 2.2.3 and 4 (k-nearest neighbours)', url: 'https://www.statlearning.com/' },
  { title: 'scikit-learn · Nearest neighbors', url: 'https://scikit-learn.org/stable/modules/neighbors.html' },
  { title: 'Beyer et al. (1999) · When is “nearest neighbor” meaningful?', url: 'https://doi.org/10.1007/3-540-49257-7_15' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
