export const lessons = [
  {
    id: 'l11-bow',
    title: '11.1 · Turning text into counts',
    sections: ['Models need numbers', 'Tokens', 'The vocabulary', 'Bag of words', 'Learn the vocabulary from training data only'],
    skill: 'Tokenize text, build a training-only vocabulary and represent documents as word-count vectors.',
    prerequisite: 'Labs 01–10; arrays (Lab 02) and leakage (Lab 06).',
    paragraphs: [
      'An on-call bot should flag messages like "database timeout on primary" as incidents and let "deployed version 2.3 to staging" pass. A model cannot read; it needs numbers. The simplest useful representation counts which words appear.',
      '**Tokenization** splits text into units. Here: lowercase, then take runs of letters and digits: "Disk FULL on agent-7!" → `disk, full, on, agent, 7`. Real systems handle punctuation, numbers, stemming and sub-words differently; each choice changes what the model can see.',
      'The **vocabulary** is the list of distinct tokens in the training messages, each given a column index. A token never seen in training has no column; at prediction time it is simply ignored. Building the vocabulary from all data (including validation) is a mild form of leakage: the model\'s feature space would depend on held-out text.',
      'A document becomes a vector of length V: entry j counts how often vocabulary word j occurs. Word order is discarded — "error, no timeout" and "timeout, no error" look identical — which is why it is called a **bag of words**. Most entries are zero; such **sparse** vectors are stored efficiently by recording only non-zero positions.',
      'Procedure: define the tokenizer; fit the vocabulary on training text; transform training and validation text with that fixed vocabulary; inspect a few vectors; decide how to handle unseen words and very rare ones (often dropped because they add noise and memory).',
    ],
    formula: 'document → tokens → counts x ∈ ℕ^V (x_j = occurrences of vocabulary word j)',
    experiment: 'Type a message containing a word the model has never seen (e.g. "kubernetes"). Where does it appear in the explanation table, and what does it contribute?',
    question: 'A document "error error timeout" is represented over the vocabulary [disk, error, timeout]. What is the count in the "error" position?',
    answer: 2,
    explanation: 'The vector is [0, 2, 1]: no "disk", two "error", one "timeout".',
    reflection: 'What text in your work could be classified? What information would a bag of words lose that matters for it?',
  },
  {
    id: 'l11-bayes',
    title: '11.2 · Bayes’ rule for classification',
    sections: ['Turn the question around', 'Prior and likelihood', 'The naive assumption', 'What the model stores', 'Why it can still work'],
    skill: 'Write the Naive Bayes classifier from Bayes’ rule and state its independence assumption precisely.',
    prerequisite: 'Lesson 11.1; Bayes’ rule and independence (Lab 04).',
    paragraphs: [
      'We want P(incident | words). Bayes\' rule (Lab 04) turns it around: `P(class | words) ∝ P(words | class)·P(class)`. The right side needs two things that are easy to estimate from counts: how common each class is, and what messages of each class tend to say.',
      'The **prior** P(class) is the fraction of training messages in that class. The **likelihood** P(words | class) is the probability of seeing this message if it came from that class. Estimating it for every possible message is hopeless — there are too many — so we need a simplifying assumption.',
      'Naive Bayes assumes words are **conditionally independent given the class**: once you know a message is an incident, seeing "database" tells you nothing more about whether "timeout" appears. Then `P(w₁, …, w_m | c) = Π P(wᵢ | c)` and we only need one probability per word per class.',
      'So the model stores, for each class, the prior and a table of word probabilities. Training is counting; prediction multiplies (in practice, adds logs). It trains in one pass over the data and handles tens of thousands of features effortlessly.',
      'The assumption is almost always false — "database" and "timeout" co-occur — yet Naive Bayes often classifies well, because a decision only needs the right class to score highest, not accurate probabilities. The probabilities themselves are usually overconfident (Lesson 11.5).',
    ],
    formula: 'P(c | w₁…w_m) ∝ P(c) · Π_i P(w_i | c)     (conditional independence)',
    experiment: 'Look at "Most indicative words". For the top incident words, can you think of pairs that almost always appear together? That is the independence assumption failing.',
    question: 'The training set has 30 incident and 30 routine messages. What is the prior P(incident)?',
    answer: 0.5,
    explanation: '30/60 = 0.5. With a 10% incident rate in training, the prior would be 0.1 and would pull every prediction toward routine.',
    reflection: 'State the independence assumption for your own text data in one sentence. Give an example of two words that clearly violate it.',
  },
  {
    id: 'l11-smoothing',
    title: '11.3 · Counting and smoothing',
    sections: ['Estimate by counting', 'The zero-count problem', 'Laplace smoothing', 'Choosing α', 'Unseen words'],
    skill: 'Estimate word probabilities from counts with additive smoothing and explain the effect of α.',
    prerequisite: 'Lessons 11.1–11.2; maximum likelihood (Lab 05).',
    paragraphs: [
      'The maximum-likelihood estimate of P(word | class) is the word\'s count in that class divided by the total number of tokens in that class. If incident messages contain 200 tokens and "timeout" appears 8 times, P(timeout | incident) = 8/200 = 0.04.',
      'If "backup" never appears in incident messages, its estimate is 0 — and because the likelihood multiplies word probabilities, a single "backup" would make P(incident | message) exactly zero, no matter how many incident words surround it. One unlucky gap in a small training set overrules all other evidence.',
      '**Additive (Laplace) smoothing** adds α to every count: `P(w | c) = (count(w, c) + α) / (total(c) + α·V)`. The α·V in the denominator keeps the probabilities summing to 1 over the vocabulary. With count 0, total 200, α = 1 and V = 100: 1/300 ≈ 0.0033 — small but not zero.',
      'α is a hyperparameter: α → 0 trusts counts completely (extreme weights for rare words); large α pulls every word toward uniform (weak evidence everywhere). α = 1 is the classic default; choose by validation like any other hyperparameter. The playground slider shows rare words\' bars shrink as α grows.',
      'Words outside the training vocabulary have no counts at all. The usual choice is to ignore them, which is what the playground does. Smoothing only fixes zero counts for words that are in the vocabulary.',
    ],
    formula: 'P(w | c) = (count(w, c) + α) / (Σ_w′ count(w′, c) + α·V)',
    experiment: 'Set α = 0.01 and type a message with one word seen only in incidents. Watch its bar. Raise α to 5 and compare validation accuracy.',
    question: 'A word appears 0 times in 200 incident tokens; α = 1, V = 100. What is the smoothed P(word | incident)? (Four decimals.)',
    answer: 0.0033, tolerance: 0.0001,
    explanation: '(0 + 1)/(200 + 1 × 100) = 1/300 ≈ 0.0033.',
    reflection: 'Why is a zero probability so much more dangerous than a small one when evidence is multiplied?',
  },
  {
    id: 'l11-logs',
    title: '11.4 · Work in log space',
    sections: ['Products underflow', 'Sums of logs', 'Read the prediction as log-odds', 'Tracing one prediction', 'Normalizing safely'],
    skill: 'Compute Naive Bayes predictions as sums of log probabilities and trace a prediction word by word.',
    prerequisite: 'Lessons 11.1–11.3; log-odds (Lab 08).',
    paragraphs: [
      'A 300-word document multiplies 300 probabilities of about 0.001: the product is around 10⁻⁹⁰⁰, far below the smallest positive float (about 10⁻³⁰⁸). It rounds to exactly 0 for both classes, and the comparison is lost. This is **underflow**.',
      'Take logs: `log P(c) + Σ log P(wᵢ | c)`. The product became a sum of moderate negative numbers (around −7 each), which never underflows. Comparing classes by their log scores gives the same decision as comparing the products.',
      'For two classes, subtract the two log scores: the **log-odds** of incident versus routine is `[log P(1) − log P(0)] + Σ [log P(wᵢ | 1) − log P(wᵢ | 0)]`. It is a prior term plus one **log-likelihood ratio** per word: positive words push toward incident, negative toward routine. The playground\'s bars are exactly these terms, and the probability is σ(log-odds), as in logistic regression.',
      'Tracing "database timeout error": if the prior term is 0 and the three words contribute +1.2, +0.9 and +1.5, the log-odds are 3.6 and P(incident) = σ(3.6) ≈ 0.97. You can see precisely which words drove the decision — a transparency few models offer.',
      'For more than two classes, turn log scores into probabilities with the **log-sum-exp** trick: subtract the largest score before exponentiating, `p_c = exp(s_c − m) / Σ exp(s_k − m)`. The same trick reappears in softmax (Lab 21) and attention (Lab 26).',
    ],
    formula: 'log-odds = log P(1)/P(0) + Σ_i log P(w_i|1)/P(w_i|0)     P(1 | words) = σ(log-odds)',
    experiment: 'For the default example, add up the bars (including the prior) yourself and compare with "Total log-odds". Then compute σ of it by hand.',
    question: 'Prior log-odds 0, word contributions +1.2, +0.9 and +1.5. What are the total log-odds?',
    answer: 3.6, tolerance: 0.0001,
    explanation: '0 + 1.2 + 0.9 + 1.5 = 3.6, so P(incident) = σ(3.6) ≈ 0.973.',
    reflection: 'Why is it valuable, operationally, that each word\'s contribution can be read off separately?',
  },
  {
    id: 'l11-limits',
    title: '11.5 · Where the naive assumption fails',
    sections: ['Repeated evidence', 'Correlated words', 'Overconfident probabilities', 'Ranking still works', 'When to use something else'],
    skill: 'Identify how conditional dependence distorts Naive Bayes probabilities and decide when that matters.',
    prerequisite: 'Lessons 11.1–11.4; calibration (Lab 09).',
    paragraphs: [
      'Type "error error error error error". Each copy adds the full weight of "error" again, as if five independent witnesses had testified. Real repeated words are not independent evidence — once someone writes "error" in a message, writing it again says little new — but the model cannot know that.',
      'The same happens with correlated words: "database", "replica" and "writes" often appear together, so the model counts overlapping evidence several times. Stop words and boilerplate ("on", "for") contribute small but systematic distortions too.',
      'The result is **overconfidence**: probabilities pushed toward 0 and 1 far more than the evidence justifies. If you use Naive Bayes probabilities for thresholds or costs (Lab 09), recalibrate them on held-out data first.',
      'Because every class is distorted in a similar way, the **ranking** of classes is often still right, so accuracy can be good even when probabilities are poor. That is why Naive Bayes is a strong, fast baseline for text — spam filtering was built on it.',
      'Use it as a baseline; switch when correlations or word order matter. Logistic regression on the same counts (Lab 08) learns weights jointly, so correlated words share credit instead of double-counting. Sequence models (Lab 25) and transformers (Lab 26) use order.',
    ],
    formula: 'repeating word w k times adds k · log P(w|1)/P(w|0) to the log-odds',
    experiment: 'Compare "error" once with "error error error error error". How much did the probability change? Would five repeats convince a human five times as much?',
    question: 'The word "error" contributes +1.5 to the log-odds each time it appears. What do four copies contribute in total?',
    answer: 6,
    explanation: '4 × 1.5 = 6. Together with a zero prior that gives P ≈ σ(6) ≈ 0.998 — extreme confidence from one repeated word.',
    reflection: 'Would duplicated or templated text in your data mislead a Naive Bayes model? How would you detect it?',
  },
  {
    id: 'l11-evaluate',
    title: '11.6 · Evaluate a text classifier honestly',
    sections: ['Split before anything else', 'Near-duplicate messages', 'Baselines and metrics', 'Inspect errors', 'Demonstrate understanding'],
    skill: 'Evaluate a text classifier without leakage and analyze its errors by reading them.',
    prerequisite: 'Lessons 11.1–11.5; evaluation (Lab 06) and metrics (Lab 09).',
    paragraphs: [
      'Split first; then build the vocabulary, the counts and any preprocessing from training messages only. Everything learned from text — vocabulary, stop-word lists, rare-word thresholds, TF-IDF weights — belongs inside the pipeline that is fit on each training fold.',
      'Text collections are full of near-duplicates: automated alerts, templated tickets, the same message from several regions. If copies land on both sides of a split, validation measures memorization. Group by template or source (Lab 06) before splitting, or deduplicate.',
      'Compare with the majority-class baseline and report precision and recall for the class that matters (Lab 09). A classifier that flags 90% of incidents at 50% precision may be excellent or useless depending on what a false page costs.',
      'Read the misclassified validation messages, with their per-word contributions. Errors cluster: a word that means different things in different teams, a new service name, a template the model has never seen. Each cluster suggests a concrete fix — more data, a new feature, a label correction.',
      'You have completed this lab when you can: build a training-only vocabulary; derive and fit Naive Bayes with smoothing; compute a prediction in log space and explain it word by word; name how the independence assumption fails; and evaluate the classifier without leakage. The Python challenge implements the full pipeline.',
    ],
    formula: 'fit(tokenizer, vocabulary, counts) on train → transform(validation) → evaluate',
    experiment: 'Change the split seed several times and record validation accuracy. How much does it vary with so few messages? What does that say about reporting one number?',
    question: 'A validation set has 16 messages; the classifier gets 13 right. What is its accuracy? (Four decimals.)',
    answer: 0.8125, tolerance: 0.0001,
    explanation: '13/16 = 0.8125. With 16 messages, one more error moves accuracy by 6 points — report it with that uncertainty in mind.',
    reflection: 'Describe the error analysis you would run on your first text classifier. What would you read, and what would you count?',
  },
]

export const sources = [
  { title: 'Jurafsky & Martin · Speech and Language Processing, Chapter 4: Naive Bayes and sentiment', url: 'https://web.stanford.edu/~jurafsky/slp3/' },
  { title: 'scikit-learn · Naive Bayes (MultinomialNB)', url: 'https://scikit-learn.org/stable/modules/naive_bayes.html' },
  { title: 'scikit-learn · Text feature extraction (bag of words)', url: 'https://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction' },
]
