// Lesson order for Lab 07: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l07-poly': [
    { p: 0 },
    { figure: 'PolyFit', caption: 'Twenty noisy points from a curved truth (dashed). Raise the degree.' },
    { p: 1 },
    { predict: { prompt: 'A polynomial of degree 5 in one input, with an intercept, has how many weights?', answer: 6, explain: 'b, w₁ … w₅: one per power from x⁰ to x⁵.' } },
    { p: 2 },
    { cell: 0 },
    { p: 3 },
    { figure: 'PowerScale', caption: 'How big each power column gets when x is not rescaled.' },
    { cell: 1 },
    { p: 4 },
  ],
  'l07-fit': [
    { p: 0 },
    { figure: 'PolyFit', props: { degree: 15 }, caption: 'Degree 15 on 20 points: the curve chases the noise.' },
    { p: 1 },
    { figure: 'ValidationU', caption: 'Training error (blue) and validation error (orange) as the degree grows.' },
    { cell: 0 },
    { p: 2 },
    { predict: { prompt: 'The noise has standard deviation 0.25. What is the lowest validation MSE any model can achieve on average?', answer: 0.0625, tolerance: 0.0001, explain: 'The noise floor is σ² = 0.25² = 0.0625: no function of x can predict the noise.' } },
    { p: 3 }, { p: 4 },
  ],
  'l07-bias-variance': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'ManyFits', caption: 'The same model fitted to 40 different training sets.' },
    { p: 3 },
    { figure: 'BiasVarianceBars', caption: 'The three parts of the expected error, degree by degree.' },
    { predict: { prompt: 'bias² = 0.5, variance = 0.2, noise variance = 0.1. What is the expected squared error?', answer: 0.8, tolerance: 0.0001, explain: '0.5 + 0.2 + 0.1 = 0.8.' } },
    { cell: 0 },
    { p: 4 },
  ],
  'l07-ridge': [
    { p: 0 },
    { figure: 'RidgeShrink', caption: 'Degree 15, with a penalty on the size of the weights. Raise λ.' },
    { p: 1 },
    { figure: 'OneFeatureRidge', caption: 'The one-feature ridge formula: least squares, shrunk.' },
    { predict: { prompt: 'Σxy = 6, Σx² = 2, n = 4, λ = 0.25. What is the ridge weight Σxy/(Σx² + nλ)?', answer: 2, explain: '6/(2 + 4 × 0.25) = 6/3 = 2. Least squares would give 6/2 = 3.' } },
    { cell: 0 },
    { p: 2 },
    { cell: 1 },
    { p: 3 }, { p: 4 },
  ],
  'l07-lasso': [
    { p: 0 }, { p: 1 },
    { figure: 'SoftThresholdPlot', caption: 'The lasso update (purple) versus proportional shrinkage (orange).' },
    { predict: { prompt: 'What is S(−2.5, 1) = sign(−2.5)·max(|−2.5| − 1, 0)?', answer: -1.5, tolerance: 0.001, explain: 'max(2.5 − 1, 0) = 1.5, with the sign of −2.5: −1.5.' } },
    { cell: 0 },
    { p: 2 },
    { figure: 'RidgeShrink', props: { penalty: 'l1' }, caption: 'Degree 10 with the lasso penalty. Raise λ and count the grey (exactly zero) weights.' },
    { cell: 1 },
    { p: 3 }, { p: 4 },
    { ladder: 'shrink' },
  ],
  'l07-learning': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'LearningCurveFig', caption: 'Training (blue) and validation (orange) error as the training set grows. Compare a line with degree 12.' },
    { cell: 0 },
    { p: 3 }, { p: 4 },
  ],
}
