import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l07-poly',
    title: '07.1 · Curves from linear models',
    sections: ['A straight line is not enough', 'Polynomial features', 'Still linear in the weights', 'Scale the features', 'Put it into practice'],
    skill: 'Build polynomial features and fit curved relationships with the least-squares machinery you already have.',
    prerequisite: 'Labs 01–06; the design matrix and least squares from Lab 03.',
    paragraphs: [
      'Build time grows slowly for small projects, faster for medium ones and levels off for huge ones that hit a cache. A straight line leaves a curved pattern in the residuals no matter how long it trains. The model family, not the optimizer, is the limitation.',
      'Create new columns from the old one: x, x², x³, …, x^d. The model `ŷ = b + w₁x + w₂x² + … + w_d x^d` is a **polynomial of degree d**. Degree 1 is a line, degree 2 a parabola; higher degrees can bend more times. `np.column_stack([x ** k for k in range(1, d + 1)])` builds the features.',
      'The prediction is still a weighted sum of columns — **linear in the weights** — so everything from Lab 03 applies unchanged: the design matrix, the gradient `(2/n)Xᵀ(Xw − y)`, the least-squares solver. "Linear model" describes how parameters enter, not the shape of the curve.',
      'Powers of x have very different scales: if x reaches 10, x¹⁰ reaches ten billion, and the loss surface becomes a canyon with an enormous condition number (Lab 03). Rescale x to about [−1, 1] first. The playground goes further and uses **Legendre polynomials**, an equivalent set of degree-≤ d curves that stay well-conditioned, so the math — not rounding error — is what you see.',
      'Procedure: plot the residuals of a simple model; if they show a systematic curve, add polynomial terms of increasing degree; rescale inputs; fit; compare **validation** errors, not training errors (next lesson explains why). Feature engineering like this is often worth more than a more complicated algorithm.',
    ],
    formula: 'Φ(x) = [x, x², …, x^d]     ŷ = b + Φ(x)·w     (linear in w, curved in x)',
    experiment: 'In "Fit one model" with λ = 0, set degree 1, 3, 9 and 15 at n = 20. Describe the fitted curve at each degree before reading the metrics.',
    question: 'A polynomial model of degree 3 in one input variable, with an intercept, has how many weights (including the intercept)?',
    answer: 4,
    misconceptions: [{ answer: 3, feedback: 'Count the intercept too: b, w₁, w₂, w₃.' }],
    explanation: 'The intercept plus x, x² and x³: four weights. A model of degree d has d + 1.',
    reflection: 'Where might a relationship in your data bend? What would a curved residual pattern look like there?',
  },
  {
    id: 'l07-fit',
    title: '07.2 · Underfitting and overfitting',
    sections: ['Training error can only fall', 'Validation error has a U-shape', 'Fitting the noise', 'Diagnosing from the two numbers', 'Choose complexity on validation'],
    skill: 'Recognize underfitting and overfitting from training and validation error and choose complexity accordingly.',
    prerequisite: 'Lesson 07.1; validation from Lab 06.',
    paragraphs: [
      'Each higher degree contains every lower-degree curve as a special case (set the extra weights to zero). So the best training error can only stay the same or fall as the degree grows. With 20 points, a degree-19 polynomial can pass through every one of them: training error zero.',
      'On new data the story differs. Validation error falls while added flexibility captures real structure, reaches a minimum, and rises once the model starts bending toward individual points. The validation curve in the playground shows this U-shape; its bottom is the complexity that generalizes best **for this amount of data**.',
      'Noise is the part of y that no function of x can predict — here, random measurement error with variance σ². A model flexible enough to hit every training point is fitting that noise. The noise differs on new data, so those wiggles become pure error. Validation error can never go below the noise floor σ²; a training error far below it is a warning sign.',
      '**Underfitting**: training and validation errors are both high and close together — the model cannot express the pattern. **Overfitting**: training error is low but validation error much higher — the model has memorized the sample. **Good fit**: validation error near its minimum, with a modest gap.',
      'Use validation or cross-validation (Lab 06) to choose the degree, and keep the test set out of it. With small datasets the validation curve is itself noisy; prefer the simplest model whose validation error is within one standard error of the minimum (the **one-standard-error rule**).',
    ],
    formula: 'training error ↓ monotonically with complexity     validation error ↓ then ↑     both ≥ σ² on average',
    experiment: 'Open the validation curve at n = 20, then n = 100 and n = 200. Where is the minimum each time? Explain why more data allows more complexity.',
    question: 'Validation MSEs for degrees 1–5 are 0.21, 0.09, 0.07, 0.08, 0.12. Which degree has the lowest validation error?',
    answer: 3,
    explanation: 'Degree 3 has the minimum, 0.07. If 0.08 were within one standard error of 0.07, the one-standard-error rule might still prefer degree 3 as the simplest near-best; here it already is.',
    reflection: 'Describe a model you have seen that looked great on training data and disappointed later. Was it under- or overfitting, and what would the curves have shown?',
  },
  {
    id: 'l07-bias-variance',
    title: '07.3 · Bias and variance',
    sections: ['Imagine many training sets', 'Bias', 'Variance', 'The decomposition', 'Two knobs: complexity and data'],
    skill: 'Explain expected prediction error as bias² + variance + noise, and estimate each by simulation.',
    prerequisite: 'Lessons 07.1–07.2; expectation and variance from Lab 04.',
    paragraphs: [
      'Your training set is one sample of many you could have collected. Fit the same model to 40 different samples and you get 40 different curves. The playground draws them. How those curves relate to the truth explains every result in this lab.',
      '**Bias** is how far the **average** curve is from the true function: `bias(x) = E[ŷ(x)] − f(x)`, the expectation taken over training sets. A line fitted to a sine wave misses in the same way every time — high bias. It is error built into the model family.',
      '**Variance** is how much the curves spread around their own average: `Var[ŷ(x)]`. A degree-15 polynomial on 20 points is on average close to the truth but wildly different each time — high variance. It is error caused by sensitivity to the particular sample.',
      'For squared error, the expected error on a new point splits exactly into three parts: **E[(y − ŷ)²] = bias² + variance + σ²**. The noise σ² is irreducible. Bias falls and variance rises as flexibility grows; their sum is the U-shaped validation curve. The playground computes all three terms from its 40 fits and shows they add up.',
      'More data reduces variance (each fit sees more of the same truth) but leaves bias unchanged. Constraining the model — lower degree, or regularization (next lesson) — reduces variance at the cost of bias. Most model-selection decisions are choices about where to sit on this trade-off.',
    ],
    formula: 'E[(y − ŷ(x))²] = (E[ŷ(x)] − f(x))² + Var[ŷ(x)] + σ²',
    experiment: 'In "Validation curve & bias–variance", compare degree 1, 5 and 15 at n = 20. Record bias² and variance for each. Then set degree 15 and increase n to 200. Which term changed?',
    question: 'At some input, bias² = 4, variance = 1 and noise variance = 0.25. What is the expected squared error there?',
    answer: 5.25,
    misconceptions: [{ answer: 5, feedback: 'Add the noise variance as well: bias² + variance + σ².' }],
    explanation: '4 + 1 + 0.25 = 5.25. Here bias dominates: a more flexible model would likely help.',
    reflection: 'In your own words, why does more data reduce variance but not bias?',
  },
  {
    id: 'l07-ridge',
    title: '07.4 · Ridge regression (L2 regularization)',
    sections: ['Penalize large weights', 'The ridge solution', 'Why it reduces variance', 'Do not penalize the intercept', 'Choosing λ'],
    skill: 'Derive and apply ridge regression, and choose its strength λ by validation.',
    prerequisite: 'Lessons 07.1–07.3; the normal equations from Lab 03.',
    paragraphs: [
      'Overfitted polynomials have huge weights that nearly cancel each other: +300x⁸ − 280x⁹ + … That is what lets them snake through every point. Instead of lowering the degree, keep it and **discourage large weights**.',
      'Minimize `J(w) = mean((y − Xw)²) + λ Σⱼ wⱼ²`. λ ≥ 0 sets how much weight size costs. The gradient gains a term 2λw, and setting it to zero gives `(XᵀX/n + λI) w = Xᵀy/n`. For one feature with no intercept: `w = Σxy / (Σx² + nλ)`: the same estimate as least squares, shrunk toward zero.',
      'Adding λI also makes the matrix invertible even when features are collinear or outnumber the rows (Lab 03\'s rank problems disappear). Each fit is pulled toward small weights, so fits on different samples differ less — lower variance, slightly more bias. In the playground, a small λ at degree 15 turns wild curves into smooth ones.',
      'Penalize only the feature weights. The intercept just sets the average level; shrinking it toward 0 would bias every prediction for no benefit. Center the features and target (or exclude the intercept from the penalty). Also **standardize** features: the penalty treats all weights alike, so a feature in larger units would be penalized unfairly — the same training-only scaling from Lab 02.',
      'λ = 0 is ordinary least squares; λ → ∞ predicts the mean everywhere. Choose λ by cross-validation over a logarithmic grid (1e−6, 1e−5, …, 1) — never on the test set. The playground\'s slider is that grid.',
    ],
    formula: 'J(w) = mean((y − Xw)²) + λ‖w‖²     (XᵀX/n + λI) w = Xᵀy/n',
    experiment: 'At degree 15, n = 20, λ = 0, note the validation MSE and the weight bars. Step λ up through the grid. At which λ is validation MSE lowest? What happens to the weights?',
    question: 'One feature, no intercept: Σxy = 10, Σx² = 4, n = 2, λ = 0.5. What is the ridge weight Σxy / (Σx² + nλ)?',
    answer: 2,
    misconceptions: [{ answer: 2.5, feedback: 'That is least squares (λ = 0). Ridge adds nλ = 2 × 0.5 = 1 to the denominator.' }],
    explanation: '10 / (4 + 2 × 0.5) = 10 / 5 = 2. Least squares (λ = 0) would give 2.5: ridge shrinks it toward zero.',
    reflection: 'Why must features be standardized before ridge? Give an example from your data where units would distort the penalty.',
  },
  {
    id: 'l07-lasso',
    title: '07.5 · Lasso (L1) and sparsity',
    sections: ['A penalty with corners', 'Soft thresholding', 'Exact zeros select features', 'Correlated features', 'Ridge, lasso or both?'],
    skill: 'Explain why the L1 penalty produces exact zeros and implement its coordinate update.',
    prerequisite: 'Lesson 07.4.',
    paragraphs: [
      'Replace the squared penalty with absolute values: `J(w) = mean((y − Xw)²) + λ Σ|wⱼ|`. This is the **lasso**. It looks like a small change; its effect is qualitatively different: many weights become **exactly** zero, not merely small.',
      'Optimize one weight at a time with the others fixed (coordinate descent). For standardized features, the best new value is the least-squares value z, **soft-thresholded**: `S(z, t) = sign(z)·max(|z| − t, 0)` with t proportional to λ. If |z| is below the threshold, the weight is set to zero; otherwise it is moved toward zero by t. `S(3, 1) = 2`, `S(0.4, 1) = 0`.',
      'Why zeros? The absolute value has a corner at 0: its slope jumps from −1 to +1. Unless a feature improves the fit by more than λ per unit of weight, staying at the corner is optimal. The squared penalty is flat at zero, so ridge never has a reason to land exactly there. Zeros mean the lasso **selects features**, giving a simpler, more interpretable model.',
      'With two strongly correlated features, the lasso tends to keep one and drop the other, somewhat arbitrarily — different samples may keep different ones. Ridge instead spreads weight across both. **Elastic net** combines both penalties to get sparsity with ridge\'s stability.',
      'Use ridge when many features each contribute a little; lasso when you expect few features to matter or need a compact model; elastic net when features are correlated and you want selection. In every case, standardize, fit inside cross-validation, and treat the selected set as unstable unless it survives resampling.',
    ],
    formula: 'J(w) = mean((y − Xw)²) + λ‖w‖₁     wⱼ ← S(zⱼ, t) = sign(zⱼ)·max(|zⱼ| − t, 0)',
    experiment: 'Switch to lasso at degree 12. Raise λ step by step and count nonzero weights. Compare with ridge at the same λ values.',
    question: 'Soft thresholding: what is S(3, 1) = sign(3)·max(|3| − 1, 0)?',
    answer: 2,
    misconceptions: [{ answer: 3, feedback: 'Soft thresholding shrinks by the threshold: |3| − 1.' }],
    explanation: '|3| − 1 = 2 > 0, so the result is +2. Any |z| ≤ 1 would give exactly 0.',
    reflection: 'Would you rather have a model that uses all 40 of your features a little, or 5 of them strongly? What would each choice cost?',
  },
  {
    id: 'l07-learning',
    title: '07.6 · Learning curves: more data or a better model?',
    sections: ['Vary the training size', 'The high-variance shape', 'The high-bias shape', 'Decide what to do next', 'Demonstrate understanding'],
    skill: 'Read learning curves to decide between collecting data, regularizing, or changing the model.',
    prerequisite: 'Lessons 07.1–07.5.',
    paragraphs: [
      'Collecting data is expensive. Before asking for more, check whether more would help. A **learning curve** plots training and validation error against training-set size for a fixed model, averaging several random draws at each size to smooth the noise.',
      'A flexible model has near-zero training error at small n and high validation error — a large gap. As n grows, training error rises (harder to memorize) and validation error falls (less variance). If the curves are still converging at your current n, **more data will help**. So will regularization, sooner and cheaper.',
      'A too-simple model shows both curves converging quickly to the same, high level well above the noise floor. More data changes nothing; the model cannot represent the pattern. **Add features or flexibility.** Seeing this shape saves the cost of a data-collection campaign that could never have worked.',
      'Decision guide: large gap → more data, regularization, fewer features; small gap and high error → more flexible model, better features; small gap and error near noise floor → you are near the limit of what the inputs can predict — improve the inputs themselves (measure something new) or accept the error.',
      'You have completed this lab when you can: build polynomial features; read a validation curve; decompose error into bias, variance and noise; derive ridge and explain lasso\'s zeros; and use a learning curve to justify the next step — all while keeping the test set untouched. The Python challenge builds these tools.',
    ],
    formula: 'gap = validation error − training error     large gap → variance     both high, small gap → bias',
    experiment: 'Learning curve view: compare degree 1, degree 5 and degree 12 at λ = 0, then degree 12 with λ = 0.01. For each, say whether more data would help.',
    question: 'At n = 200 a model has training MSE 0.30 and validation MSE 0.31, while the noise variance is 0.06. What mainly limits it?',
    choices: [
      { text: 'Bias: it is too simple for the pattern', why: 'Both errors sit far above the 0.06 noise floor and close to each other.' },
      { text: 'Variance: it is fitting noise', why: 'Variance shows as a large train–validation gap; here the gap is only 0.01.' },
      { text: 'Noise: nothing can do better', why: 'The noise floor is 0.06, far below 0.30, so a better model exists.' },
    ],
    answer: 0,
    explanation: 'The gap is tiny (0.01), so variance is small; both errors sit far above the 0.06 noise floor. That is bias: a more flexible model or better features are needed, not more data.',
    reflection: 'Sketch the learning curve you expect for your current model. What would you do next if it showed a large gap? A small gap?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapters 2.2 (bias–variance) and 6.2 (ridge and lasso)', url: 'https://www.statlearning.com/' },
  { title: 'scikit-learn · Ridge, Lasso and Elastic-Net', url: 'https://scikit-learn.org/stable/modules/linear_model.html' },
  { title: 'scikit-learn · Validation curves and learning curves', url: 'https://scikit-learn.org/stable/modules/learning_curve.html' },
  { title: 'The Elements of Statistical Learning · Chapter 3.4 (shrinkage methods)', url: 'https://hastie.su.domains/ElemStatLearn/' },
]

// Runnable cells and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
