export const lessons = [
  {
    id: 'l48-convexity',
    title: '48.1 · Convex sets and functions',
    sections: ['Why convexity matters', 'Convex sets', 'Convex functions', 'Tests you can use', 'Which ML losses are convex'],
    skill: 'Recognize convex problems and prove convexity of common ML losses.',
    prerequisite: 'Gradients and Hessians (Labs 03, 22, 39); Labs 47 and earlier.',
    paragraphs: [
      'For a **convex** problem every local minimum is a global minimum, and many algorithms come with guarantees on speed and accuracy. Knowing whether your problem is convex tells you whether “it converged” means “it found the answer”.',
      'A set is convex if the straight segment between any two of its points stays inside it: half-planes, balls and intersections of convex sets are convex; a ring is not.',
      'A function is convex if the chord between any two points on its graph lies above the graph: f(tx + (1 − t)y) ≤ t·f(x) + (1 − t)·f(y). Equivalently (if differentiable), it lies above all its tangent lines; (if twice differentiable) its Hessian is positive semidefinite everywhere.',
      'Useful rules: sums and positive multiples of convex functions are convex; a convex function of a linear function is convex; the maximum of convex functions is convex. Norms are convex.',
      'Squared loss, logistic (log) loss, hinge loss, and their L1/L2-regularized versions are convex in the weights — so linear regression, logistic regression, lasso and SVMs have single, findable optima. Neural-network losses are not convex in the weights; there, guarantees give way to good initialization, optimizers and luck (Lab 22).',
    ],
    formula: 'f(tx + (1−t)y) ≤ t f(x) + (1−t) f(y)   ⇔   ∇²f ⪰ 0 (twice differentiable)',
    derivation: {
      title: 'Prove the logistic loss is convex',
      intro: 'For one example with score z = wᵀx and label y ∈ {0, 1}, the loss is ℓ(z) = log(1 + e^z) − y·z.',
      steps: [
        { prompt: 'ℓ′(z) = ?', answer: 'exp(z)/(1+exp(z)) - y', show: '`σ(z) − y`', vars: { z: [-4, 4], y: [0, 1] } },
        { prompt: 'ℓ″(z) = ?', answer: 'σ(z)*(1-σ(z))', show: '`σ(z)(1 − σ(z))`', vars: { z: [-4, 4] } },
        { prompt: 'What is the smallest value ℓ″ can take? (It approaches this far from 0.)', number: 0, show: '`0` — never negative, so ℓ is convex in z', why: 'A convex function of the linear score wᵀx is convex in w.' },
      ],
      result: 'The Hessian in w is σ(1 − σ)·xxᵀ ⪰ 0: logistic regression has no bad local minima.',
    },
    experiment: 'In the KKT view, notice that the contours of ‖x − a‖² are circles and the feasible region is a half-plane. Why does that guarantee exactly one constrained minimum?',
    question: 'Is f(x) = max(0, 1 − x) (the hinge loss) convex? (1 = yes, 0 = no)',
    answer: 1,
    explanation: 'Yes: it is the maximum of two linear (hence convex) functions, 0 and 1 − x.',
    reflection: 'Name a model you use whose training problem is not convex. What do you do about local minima?',
  },
  {
    id: 'l48-kkt',
    title: '48.2 · Lagrange multipliers and KKT conditions',
    sections: ['Equality constraints', 'Inequality constraints', 'The KKT conditions', 'Complementary slackness', 'Shadow prices'],
    skill: 'Solve constrained problems with Lagrange multipliers and interpret the KKT conditions.',
    prerequisite: 'Lesson 48.1.',
    paragraphs: [
      'Minimize f(x) subject to g(x) = 0. At the optimum you cannot move along the constraint and decrease f, so ∇f must be perpendicular to the constraint: **∇f = −λ∇g** for some multiplier λ. The **Lagrangian** L(x, λ) = f(x) + λg(x) packages this: set its gradient to zero.',
      'With an inequality g(x) ≤ 0, two things can happen. If the unconstrained minimum is feasible, the constraint does nothing (λ = 0). Otherwise the optimum sits on the boundary, pushed against it, with λ > 0.',
      'The **Karush–Kuhn–Tucker** (KKT) conditions: stationarity ∇f + λ∇g = 0; primal feasibility g(x) ≤ 0; dual feasibility λ ≥ 0; **complementary slackness** λ·g(x) = 0. For convex problems (with a mild condition), they are necessary and sufficient for optimality.',
      'Complementary slackness says each constraint is either tight or has zero multiplier. In SVMs (Lesson 48.4) it is what makes most training points irrelevant.',
      'λ is the **shadow price**: how fast the optimal value changes as the constraint is relaxed, df*/db = −λ. In the playground, raising b by 0.1 lowers f* by about 0.1·λ. In economics it is the value of one more unit of a scarce resource.',
    ],
    formula: 'L(x, λ) = f(x) + λ g(x)     KKT: ∇f + λ∇g = 0,  g ≤ 0,  λ ≥ 0,  λg = 0',
    derivation: {
      title: 'Solve the playground problem by hand',
      intro: 'Minimize (x₁ − 2)² + (x₂ − 1)² subject to x₁ + x₂ = 1.',
      steps: [
        { prompt: 'Stationarity in x₁: 2(x₁ − 2) + λ = 0. Write x₁ in terms of λ.', answer: '2 - λ/2', show: '`x₁ = 2 − λ/2`', vars: { λ: [-3, 3] }, hint: 'Type λ as lambda.' },
        { prompt: 'Similarly x₂ = 1 − λ/2. Substitute into x₁ + x₂ = 1 and solve for λ.', number: 2, show: '`3 − λ = 1 ⇒ λ = 2`' },
        { prompt: 'What is x₁?', number: 1, show: '`x* = (1, 0)`' },
        { prompt: 'Optimal value f*?', number: 2, show: '`1 + 1 = 2`' },
      ],
      result: 'Matches the playground at a = (2, 1), b = 1: x* = (1, 0), λ = 2.',
    },
    experiment: 'In the KKT view, move a inside the feasible region and back out. Watch λ and the “active” label. Then check the shadow-price prediction at several values of b.',
    question: 'At an optimum the multiplier of a constraint x₁ + x₂ ≤ b is λ = 3. If b increases by 0.01, approximately how does f* change?',
    answer: -0.03, tolerance: 1e-6,
    explanation: 'df*/db = −λ, so f* changes by about −3 × 0.01 = −0.03.',
    reflection: 'Which constraint in a real system you know has the largest shadow price?',
  },
  {
    id: 'l48-duality',
    title: '48.3 · Duality',
    sections: ['The dual function', 'Weak duality', 'Strong duality', 'Certificates and gaps', 'Why ML cares'],
    skill: 'Derive a Lagrangian dual and use the duality gap as a certificate of optimality.',
    prerequisite: 'Lesson 48.2.',
    paragraphs: [
      'Minimize the Lagrangian over x for a fixed λ ≥ 0: the **dual function** d(λ) = minₓ L(x, λ). It is always concave, even when the original problem is not convex.',
      '**Weak duality**: for any feasible x and any λ ≥ 0, d(λ) ≤ f(x). Every dual value is a lower bound on the primal optimum.',
      'Maximizing d(λ) is the **dual problem**. For convex problems with a strictly feasible point (Slater’s condition), **strong duality** holds: the best dual value equals the primal optimum.',
      'The **duality gap** f(x) − d(λ) is a certificate: if it is 10⁻⁶, x is within 10⁻⁶ of optimal, whatever algorithm produced it. The playground’s SVM reports primal and dual objectives whose gap closes to the solver’s tolerance.',
      'Sometimes the dual is easier: fewer variables, simpler constraints, or structure (like inner products) the primal hides. The SVM is the classic example.',
    ],
    formula: 'd(λ) = minₓ L(x, λ)     d(λ) ≤ f(x) for feasible x, λ ≥ 0     strong duality: max d = min f',
    derivation: {
      title: 'Dual of a one-dimensional problem',
      intro: 'Minimize x² subject to x ≥ 1, i.e. 1 − x ≤ 0. L(x, λ) = x² + λ(1 − x).',
      steps: [
        { prompt: 'Minimize L over x: x = λ/2. Write d(λ) = L(λ/2, λ).', answer: 'λ - λ^2/4', show: '`λ − λ²/4`', vars: { λ: [0, 4] } },
        { prompt: 'Maximize d(λ): which λ?', number: 2, show: '`λ = 2`' },
        { prompt: 'Dual optimum d(2)?', number: 1, show: '`1` — equal to the primal optimum 1² = 1: strong duality' },
      ],
      result: 'The dual touches the primal at the solution; every other λ gives a smaller lower bound.',
    },
    experiment: 'In the SVM view, compare the primal and dual objectives for each C. Which is always larger?',
    question: 'A solver reports primal objective 13.3501 and dual objective 13.3498. At most how far is the current solution from optimal in objective value?',
    answer: 0.0003, tolerance: 1e-7,
    explanation: 'The optimum lies between them, so the gap 0.0003 bounds the suboptimality.',
    reflection: 'Where else would a certificate like the duality gap be valuable in your work?',
  },
  {
    id: 'l48-svm',
    title: '48.4 · The SVM dual and SMO',
    sections: ['Primal soft-margin SVM', 'Deriving the dual', 'Support vectors from KKT', 'The kernel trick appears', 'SMO'],
    skill: 'Derive the SVM dual, identify support vectors from the KKT conditions, and explain SMO.',
    prerequisite: 'Lessons 48.1–48.3; SVMs (Lab 15).',
    paragraphs: [
      'The soft-margin SVM (Lab 15) minimizes ½‖w‖² + C Σ ξᵢ subject to yᵢ(wᵀxᵢ + b) ≥ 1 − ξᵢ and ξᵢ ≥ 0. Attach multipliers αᵢ to the margin constraints.',
      'Setting the Lagrangian’s derivatives to zero gives **w = Σ αᵢ yᵢ xᵢ** and Σ αᵢ yᵢ = 0, with 0 ≤ αᵢ ≤ C. Substituting back yields the **dual**: maximize Σ αᵢ − ½ Σᵢ Σⱼ αᵢ αⱼ yᵢ yⱼ xᵢᵀxⱼ.',
      'Complementary slackness sorts the points: αᵢ = 0 for points beyond the margin (they do not matter); 0 < αᵢ < C for points exactly on the margin; αᵢ = C for points inside the margin or misclassified. The classifier depends only on the **support vectors** (αᵢ > 0).',
      'The data appear only through inner products xᵢᵀxⱼ. Replace them by a kernel k(xᵢ, xⱼ) and the same algorithm learns in a feature space it never computes — the **kernel trick**, justified here by duality (and in Lab 49 by the representer theorem).',
      '**SMO** (sequential minimal optimization) solves the dual by repeatedly picking two multipliers and optimizing them analytically while keeping Σ αᵢyᵢ = 0 — two is the fewest that can move. It powered libsvm and scikit-learn’s SVC.',
    ],
    formula: 'dual: max Σαᵢ − ½ΣᵢΣⱼ αᵢαⱼyᵢyⱼ k(xᵢ, xⱼ)  s.t. 0 ≤ αᵢ ≤ C, Σαᵢyᵢ = 0     f(x) = Σ αᵢyᵢ k(xᵢ, x) + b',
    derivation: {
      title: 'Stationarity gives w',
      intro: 'The Lagrangian contains ½‖w‖² − Σ αᵢ[yᵢ(wᵀxᵢ + b) − 1 + ξᵢ]. One-dimensional inputs, two examples.',
      steps: [
        { prompt: 'Differentiate ½w² − a1·y1·w·x1 − a2·y2·w·x2 with respect to w.', answer: 'w - a1*y1*x1 - a2*y2*x2', show: '`w − a1·y1·x1 − a2·y2·x2`', vars: { w: [-2, 2], a1: [0, 2], a2: [0, 2], y1: [-1, 1], y2: [-1, 1], x1: [-2, 2], x2: [-2, 2] } },
        { prompt: 'Set it to zero. With α = (0.5, 0.5), y = (+1, −1), x = (2, −1): what is w?', number: 1.5, show: '`0.5·2 + 0.5·(−1)(−1) = 1.5`' },
        { prompt: 'Check the constraint Σ αᵢyᵢ for these values.', number: 0, show: '`0.5 − 0.5 = 0` ✓' },
      ],
      result: 'The weight vector is a weighted sum of training examples — only those with αᵢ > 0 contribute.',
    },
    experiment: 'In the SVM view, move C from 0.01 to 50. Count support vectors and those at the bound α = C. Then switch to the RBF kernel with overlap 1.0.',
    question: 'An SVM has 400 training points; 360 lie strictly outside the margin on the correct side. At most how many training points does the decision function depend on?',
    answer: 40,
    explanation: 'Points beyond the margin have αᵢ = 0 by complementary slackness, so only the remaining 40 can be support vectors.',
    reflection: 'Why does the number of support vectors affect how fast a kernel SVM predicts?',
  },
  {
    id: 'l48-prox',
    title: '48.5 · Proximal methods and the optimizer toolbox',
    sections: ['Non-smooth objectives', 'The proximal operator', 'ISTA and FISTA', 'Choosing an optimizer', 'Demonstrate understanding'],
    skill: 'Apply proximal gradient methods to non-smooth problems and choose appropriate optimizers.',
    prerequisite: 'Lessons 48.1–48.4; lasso (Lab 07), Newton’s method (Lab 39).',
    paragraphs: [
      'The lasso objective (1/2n)‖y − Xw‖² + λ‖w‖₁ is convex but not differentiable at wⱼ = 0 — exactly where we want many coefficients to land. Subgradient descent works but needs shrinking steps, converges slowly and never lands exactly on zero.',
      'The **proximal operator** of a function h finds the point minimizing h(u) + (1/2t)‖u − v‖²: a step toward low h that stays close to v. For h = λ|u| it is **soft-thresholding**: shrink v toward zero by tλ, and set it exactly to zero if |v| ≤ tλ.',
      '**Proximal gradient** (ISTA) alternates a gradient step on the smooth part with the proximal step on the non-smooth part. With step 1/L (L the Lipschitz constant of the smooth gradient) it converges like gradient descent on a smooth problem; **FISTA** adds momentum. In the playground, both reach machine precision within about 100 iterations and produce exact zeros; subgradient descent is still visibly off after 200.',
      'The toolbox: closed forms (least squares), Newton and IRLS for small smooth problems (Lab 39), L-BFGS for medium smooth problems, coordinate descent (scikit-learn’s Lasso), proximal methods for structured non-smooth penalties, interior-point methods for general constrained convex problems, stochastic gradient methods for huge data (Lab 22).',
      'You have completed this lab when you can: test convexity; solve constrained problems with Lagrange multipliers and KKT conditions and read shadow prices; derive a dual and use the duality gap; derive the SVM dual and explain support vectors and the kernel trick; and apply proximal gradient methods. The Python challenge implements soft-thresholding and ISTA and verifies the SVM dual against scikit-learn.',
    ],
    formula: 'prox_{tλ|·|}(v) = sign(v)·max(|v| − tλ, 0)     ISTA: w ← prox(w − t∇f(w))',
    derivation: {
      title: 'Derive soft-thresholding',
      intro: 'Minimize λ|u| + (u − v)²/2 over u (step t = 1).',
      steps: [
        { prompt: 'For u > 0 the derivative is λ + (u − v). Setting it to zero, u = ?', answer: 'v - λ', show: '`u = v − λ` (valid when v > λ)', vars: { v: [1, 3], λ: [0.1, 0.9] } },
        { prompt: 'Evaluate the proximal step for v = 0.3 and λ = 0.5.', number: 0, show: '`0` — |v| ≤ λ, so the minimum is exactly at zero' },
        { prompt: 'And for v = −2, λ = 0.5?', number: -1.5, show: '`−1.5`' },
      ],
      result: 'Small values are set exactly to zero, large ones shrink by λ: sparsity by construction.',
    },
    experiment: 'In the lasso view, move λ from 0.01 to 1. How does the number of exact zeros change, and which coefficients survive?',
    question: 'Soft-threshold v = 1.2 with threshold tλ = 0.4.',
    answer: 0.8, tolerance: 1e-9,
    explanation: 'sign(1.2)·max(1.2 − 0.4, 0) = 0.8.',
    reflection: 'For a model you train, which optimizer would you pick from the toolbox, and why?',
  },
]

export const sources = [
  { title: 'Boyd & Vandenberghe · Convex Optimization (free book)', url: 'https://web.stanford.edu/~boyd/cvxbook/' },
  { title: 'Platt (1998) · Sequential minimal optimization: a fast algorithm for training support vector machines', url: 'https://www.microsoft.com/en-us/research/publication/sequential-minimal-optimization-a-fast-algorithm-for-training-support-vector-machines/' },
  { title: 'Beck & Teboulle (2009) · A fast iterative shrinkage-thresholding algorithm (FISTA)', url: 'https://doi.org/10.1137/080716542' },
  { title: 'Stanford CS229 lecture notes · Support vector machines and duality', url: 'https://cs229.stanford.edu/main_notes.pdf' },
]
