import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l26-lookup',
    title: '26.1 · Attention as a soft lookup',
    sections: ['A dictionary you can differentiate', 'Queries, keys and values', 'Scores and softmax', 'The weighted average', 'Put it into practice'],
    skill: 'Compute an attention output from a query, keys and values, and explain the role of each.',
    prerequisite: 'Labs 01–25; dot products (Lab 01), softmax (Lab 21), sequences (Lab 25).',
    paragraphs: [
      'A Python dictionary looks up a value by an exact key. **Attention** does a soft version: a **query** is compared with every **key**, and the answer is a weighted average of the **values**, with more weight on keys that match the query better.',
      'Each position in a sequence produces all three vectors by multiplying its representation with learned matrices: `q = x W_Q`, `k = x W_K`, `v = x W_V`. The query says what this position is looking for; a key advertises what a position contains; a value is what it hands over if chosen.',
      'Similarity is the dot product q·k. Softmax over all keys turns the scores into weights that are positive and sum to 1. With scores (2, 0, 0): weights ≈ (0.787, 0.107, 0.107).',
      'The output is `Σ wᵢ vᵢ`. If those three values are 10, 20 and 30, the output is 0.787·10 + 0.107·20 + 0.107·30 ≈ 13.2 — mostly the first value, a little of the others. Every step is differentiable, so W_Q, W_K and W_V are learned by backpropagation: the network learns what to ask for and what to offer.',
      'In the playground\'s lookup view, the query is a direction and the keys are services. Raising the sharpness β moves attention from a plain average (β = 0) to a near-exact lookup of the closest key.',
    ],
    formula: 'weights = softmax(q·k₁, …, q·k_T)     output = Σᵢ weightsᵢ · vᵢ',
    experiment: 'Point the query between "db" and "cache". Predict the output latency at β = 0, 4 and 30 before reading it.',
    question: 'Weights are 0.5, 0.3 and 0.2 on values 10, 20 and 40. What is the attention output?',
    answer: 19,
    explanation: '0.5·10 + 0.3·20 + 0.2·40 = 5 + 6 + 8 = 19.',
    reflection: 'Describe a lookup in your own work that would benefit from being "soft" — returning a blend of close matches rather than one exact hit.',
  },
  {
    id: 'l26-scaled',
    title: '26.2 · Scaled dot-product self-attention',
    sections: ['Every token attends to every token', 'Matrix form', 'Why divide by √d', 'Cost', 'What attention buys'],
    skill: 'Compute self-attention in matrix form, explain the √d scaling, and state its cost.',
    prerequisite: 'Lesson 26.1; matrix products (Lab 03); saturation (Labs 20–22).',
    paragraphs: [
      'In **self-attention**, queries, keys and values all come from the same sequence. For T tokens with width d: Q, K, V have shape (T, d); `S = QKᵀ` has shape (T, T) — the score of every token against every other; softmax is applied to each row; the output `softmax(S)V` has shape (T, d), one updated vector per token.',
      'If the entries of q and k are roughly independent with unit variance, q·k is a sum of d products, so its typical size grows like √d. For d = 64 that is about 8; softmax of scores that large is nearly one-hot, and its gradient nearly vanishes for every other position. Dividing by √d keeps scores near unit scale: `Attention(Q, K, V) = softmax(QKᵀ/√d)V`.',
      'The playground shows it: without the division, raising d drives the weight entropy toward zero. With it, the weights stay spread out enough to learn.',
      'The score matrix has T² entries. Doubling the sequence length quadruples attention\'s memory and compute; 2,048 tokens with 8 heads means about 33 million scores per layer per sequence. Much engineering (efficient kernels, sparse or linear attention) targets this cost.',
      'In exchange, any token can draw information from any other in one step. An RNN (Lab 25) must pass it through every intermediate state, where gradients vanish; attention gives a direct path regardless of distance, and all positions are computed in parallel.',
    ],
    formula: 'Attention(Q, K, V) = softmax(QKᵀ / √d) V     Q, K, V: (T, d) → scores (T, T) → output (T, d)',
    experiment: 'In self-attention, set d = 256. Toggle "Divide by √d" and compare the mean row entropy with the uniform value.',
    question: 'With d = 64, by what factor does scaled attention divide the raw dot products?',
    answer: 8,
    explanation: '√64 = 8.',
    reflection: 'Explain to a colleague why a sequence twice as long costs four times as much in an attention layer.',
  },
  {
    id: 'l26-masks',
    title: '26.3 · Masks and positional information',
    sections: ['Causal masks', 'Padding masks', 'Attention ignores order', 'Positional encodings', 'Checking both'],
    skill: 'Apply causal and padding masks, and add positional information to make attention order-aware.',
    prerequisite: 'Lessons 26.1–26.2; padding and masking (Lab 25).',
    paragraphs: [
      'A model trained to predict the next token must not see it. A **causal mask** sets every score for a later position to −∞ before the softmax: `S[i, j] = −∞ for j > i`. Those weights become exactly 0, so position i only attends to positions 0…i. In a 4-token causal mask, 6 of the 16 scores are masked.',
      'A **padding mask** does the same for `<pad>` positions (Lab 25), so padded tokens never receive attention — the result does not depend on how much padding a batch needed.',
      'Self-attention itself treats the input as a **set**: permute the tokens and the output rows are permuted the same way, with no other change (permutation equivariance). "Deploy caused error" and "error caused deploy" would look alike. The playground\'s swap button shows this.',
      '**Positional encodings** inject order: add to each token\'s embedding a vector that depends on its position — fixed sinusoids of different frequencies (as in the original transformer), learned position embeddings, or relative schemes such as rotary embeddings that modify q and k directly.',
      'Check both properties in code: perturb a future token and confirm earlier outputs are unchanged (causality); permute tokens with and without positional encodings and confirm equivariance disappears only when positions are added.',
    ],
    formula: 'causal: S_ij = −∞ for j > i     PE(pos, 2i) = sin(pos/10000^{2i/d}),  PE(pos, 2i+1) = cos(…)',
    experiment: 'Turn on the causal mask and describe the pattern of zeros. Then compare the swap test with and without positional encodings.',
    question: 'How many entries of a 4 × 4 causal attention mask are masked (set to −∞)?',
    answer: 6,
    explanation: 'Entries strictly above the diagonal: 3 + 2 + 1 = 6.',
    reflection: 'Where in your data does order carry meaning? How would you give a model that information?',
  },
  {
    id: 'l26-heads',
    title: '26.4 · Multi-head attention and the transformer block',
    sections: ['Several attention patterns at once', 'Splitting into heads', 'The block', 'Residuals and normalization', 'Parameter count'],
    skill: 'Trace shapes through multi-head attention and a full transformer block.',
    prerequisite: 'Lessons 26.1–26.3; residuals and normalization (Labs 22, 24).',
    paragraphs: [
      'One attention pattern per layer is limiting: a token may need to find its subject, the previous error, and the matching bracket at the same time. **Multi-head attention** runs h attentions in parallel, each on its own projected subspace of width d/h, then concatenates the results and mixes them with an output matrix W_O.',
      'Shapes: X (T, d) → Q, K, V (T, d) → reshape to (h, T, d/h) → scores (h, T, T) → outputs (h, T, d/h) → concatenate to (T, d) → W_O → (T, d). With d = 256 and h = 8, each head works in 32 dimensions. The total cost is about the same as one full-width head.',
      'A **transformer block**: `x = x + MHA(LayerNorm(x))`, then `x = x + MLP(LayerNorm(x))`. LayerNorm standardizes each token\'s vector (mean 0, variance 1, then a learned scale and shift). The MLP expands to about 4d, applies a nonlinearity (GELU) and projects back, independently for each token.',
      'The **residual** additions give gradients a direct route through many blocks (the lesson from Labs 22 and 24), and normalization keeps activations in a stable range. Deep transformers — dozens of blocks — train reliably because of them.',
      'Per block: attention 4d² + 4d parameters, MLP 8d² + 5d, LayerNorms 4d: about 12d². At d = 768, that is about 7 million per block; 12 blocks give roughly 85 million, before embeddings.',
    ],
    formula: 'x ← x + MHA(LN(x));  x ← x + MLP(LN(x))     params/block ≈ 12d²',
    experiment: 'In the block view, set d = 768 and 12 heads. Read the total parameters per block and the attention-matrix size at T = 1,024.',
    question: 'A model with width d = 512 uses 8 heads. What is the width of each head?',
    answer: 64,
    explanation: '512 / 8 = 64 dimensions per head.',
    reflection: 'Sketch (in words) the full data path from input token ids to next-token probabilities in a one-block transformer.',
  },
  {
    id: 'l26-interpret',
    title: '26.5 · What attention weights do and do not tell you',
    sections: ['Tempting pictures', 'Where information flowed', 'Not an explanation', 'Better tools', 'Demonstrate understanding'],
    skill: 'Interpret attention weights cautiously and choose appropriate analysis tools.',
    prerequisite: 'Lessons 26.1–26.4; correlation versus causation (Lab 05).',
    paragraphs: [
      'Attention heatmaps are appealing: "the model looked at *deploy* when it saw *error*". They show, for one head in one layer, how much each position\'s value vector contributed to another position\'s output.',
      'That is not the same as why the model predicted what it did. Values are further transformed by later layers and residual paths; many heads and layers contribute; and different attention patterns can produce the same prediction. Studies have found that attention weights can be substantially changed without changing outputs.',
      'Treat weights as a description of information flow in one component, a hypothesis generator. Test hypotheses with interventions: remove or replace a token and measure the change in the prediction; ablate a head; compare with gradient-based attributions. Only changes in outputs establish influence (Lab 05\'s lesson about causation, applied inside a model).',
      'Practical failures to check in attention models: missing masks (look for weight on padding or future tokens), attention collapsing onto one position (often a first or separator token), and saturation at large widths without scaling.',
      'You have completed this lab when you can: compute attention by hand; explain the √d scaling and the T² cost; apply causal and padding masks; explain why positional information is necessary; trace shapes through multi-head attention and a transformer block; and interpret attention weights with appropriate caution. The Python challenge implements multi-head attention with masks.',
    ],
    formula: 'influence of token j ≈ change in output when j is removed or replaced — not attention weight alone',
    experiment: 'In self-attention, change only the seed. Do the attention patterns change substantially? What does that suggest about reading meaning into a single heatmap?',
    question: 'A head puts weight 0.7 on token A. Removing token A changes the prediction by 0.001. Is A important for this prediction?',
    choices: [
      { text: 'Yes — 0.7 is the largest attention weight', why: 'An attention weight says where information was read from, not whether the prediction depends on it.' },
      { text: 'No — removing it barely changes the prediction', why: 'The intervention is the evidence; the heatmap is a hypothesis.' },
      { text: 'Impossible to say without more heads', why: 'The removal experiment answers the question for this prediction directly.' },
    ],
    answer: 1,
    explanation: 'High attention weight but negligible effect when removed: the intervention shows A is not important for this prediction, despite the heatmap.',
    reflection: 'How would you test a claim like "the model uses the deploy event to predict incidents"?',
  },
]

export const sources = [
  { title: 'Vaswani et al. (2017) · Attention is all you need', url: 'https://arxiv.org/abs/1706.03762' },
  { title: 'Dive into Deep Learning · Chapter 11: attention mechanisms and transformers', url: 'https://d2l.ai/chapter_attention-mechanisms-and-transformers/index.html' },
  { title: 'Karpathy · nanoGPT (a small, readable transformer)', url: 'https://github.com/karpathy/nanoGPT' },
  { title: 'Jain & Wallace (2019) · Attention is not explanation', url: 'https://arxiv.org/abs/1902.10186' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
