export const lessons = [
  {
    id: 'l46-entropy',
    title: '46.1 · Surprise and entropy',
    sections: ['Information is surprise', 'Entropy: expected surprise', 'Bits and nats', 'Maximum and minimum', 'Put it into practice'],
    skill: 'Compute the information content of outcomes and the entropy of a distribution.',
    prerequisite: 'Probability (Lab 04), logarithms; Labs 39–45 use these quantities throughout.',
    paragraphs: [
      'Learning that a build passed tells you little if builds almost always pass; learning it timed out tells you a lot. Shannon measured the **information** in an outcome of probability p as its surprise, −log p: rare events carry more information, certain ones none, and information from independent events adds.',
      'The **entropy** H(p) = −Σ p(x) log p(x) is the average surprise of a source — how uncertain you are before seeing the outcome.',
      'With log base 2 the unit is the **bit**; with the natural log it is the **nat** (1 nat ≈ 1.443 bits). Machine-learning libraries use nats; information theory usually uses bits.',
      'Entropy is 0 when one outcome is certain and largest — log K — when all K outcomes are equally likely. A fair coin has 1 bit; the playground’s default CI log (½, ¼, ⅛, ⅛) has 1.75 bits, less than the 2 bits of four equal outcomes because it is partly predictable.',
      'Procedure: for any categorical variable — a label, a token, a decision-tree split — compute its entropy to see how much uncertainty there is to remove. Decision trees (Lab 12) choose splits that remove the most.',
    ],
    formula: 'I(x) = −log₂ p(x)     H(p) = −Σₓ p(x) log₂ p(x)     0 ≤ H ≤ log₂ K',
    derivation: {
      title: 'Entropy of a biased coin',
      steps: [
        { prompt: 'Write the binary entropy H(p) in bits (use log2( ) for base-2 logarithms).', answer: '-(p*log(p) + (1-p)*log(1-p))/log(2)', show: '`−p log₂ p − (1 − p) log₂(1 − p)`', vars: { p: [0.05, 0.95] } },
        { prompt: 'Differentiate with respect to p (in bits).', answer: 'log((1-p)/p)/log(2)', show: '`log₂((1 − p)/p)`', vars: { p: [0.05, 0.95] } },
        { prompt: 'Where is the maximum? (Set the derivative to zero.)', number: 0.5, show: '`p = 0.5`' },
        { prompt: 'Entropy of (½, ¼, ¼) in bits?', number: 1.5, show: '`½·1 + ¼·2 + ¼·2 = 1.5`' },
      ],
      result: 'Uncertainty is largest when outcomes are equally likely and shrinks as one outcome dominates.',
    },
    experiment: 'In the coding view, make “build passed” overwhelmingly likely. What happens to the entropy, and to the length of its codeword?',
    question: 'A die with 8 equally likely faces. What is its entropy in bits?',
    answer: 3,
    explanation: 'log₂ 8 = 3 bits: exactly three yes/no questions identify the face.',
    reflection: 'Which variable in your work has the highest entropy? What would it take to reduce it?',
  },
  {
    id: 'l46-coding',
    title: '46.2 · Entropy is the limit of compression',
    sections: ['Codes for outcomes', 'Short codes for common outcomes', 'Huffman coding', 'The source coding theorem', 'Prediction is compression'],
    skill: 'Build a Huffman code and relate average code length to entropy.',
    prerequisite: 'Lesson 46.1.',
    paragraphs: [
      'To transmit a stream of outcomes we assign each a binary codeword. A **prefix code** (no codeword is the start of another) can be decoded without separators.',
      'Common outcomes should get short codewords. The ideal length for an outcome of probability p is −log₂ p bits: 1 bit for p = ½, 3 bits for p = ⅛.',
      '**Huffman coding** repeatedly merges the two least likely outcomes into a node, building a tree whose leaves are the outcomes; codeword length is the depth. It is the optimal prefix code for a known distribution.',
      '**Shannon’s source coding theorem**: no lossless code averages fewer than H(p) bits per outcome, and codes exist within one bit of it (and arbitrarily close when coding long blocks). For (½, ¼, ⅛, ⅛) Huffman achieves exactly 1.75 bits; for (0.4, 0.3, 0.2, 0.1) it needs 1.9 against an entropy of 1.846.',
      'So a model that predicts well compresses well, and vice versa — arithmetic coding turns any probabilistic predictor into a compressor using −log₂ p bits per symbol. Language-model training is literally learning to compress text.',
    ],
    formula: 'H(p) ≤ average length of the best prefix code < H(p) + 1     ideal length ℓ(x) = −log₂ p(x)',
    derivation: {
      title: 'Average code length',
      steps: [
        { prompt: 'Probabilities (0.4, 0.3, 0.2, 0.1) with Huffman lengths (1, 2, 3, 3). Average length?', number: 1.9, show: '`0.4 + 0.6 + 0.6 + 0.3 = 1.9`' },
        { prompt: 'Its entropy in bits? (Three decimals.)', number: -(0.4 * Math.log2(0.4) + 0.3 * Math.log2(0.3) + 0.2 * Math.log2(0.2) + 0.1 * Math.log2(0.1)), tolerance: 1e-3, show: '`≈ 1.846`' },
        { prompt: 'The ideal (non-integer) length for an outcome with probability 0.3? (Three decimals.)', number: -Math.log2(0.3), tolerance: 1e-3, show: '`−log₂ 0.3 ≈ 1.737`', why: 'Codeword lengths must be whole numbers, which is why Huffman loses a little.' },
      ],
      result: 'The gap between 1.9 and 1.846 comes only from rounding lengths to whole bits.',
    },
    experiment: 'In the coding view, set the probabilities to (½, ¼, ⅛, ⅛) and compare Huffman with the entropy. Then make them less “dyadic”. When does the gap appear?',
    question: 'A source has entropy 2.3 bits per symbol. What is the minimum average number of bits needed to compress 1,000 symbols losslessly (in the long run)?',
    answer: 2300,
    explanation: '1,000 × 2.3 = 2,300 bits. No lossless compressor can do better on average.',
    reflection: 'Why does a compressed file look random? What would a pattern in it mean?',
  },
  {
    id: 'l46-kl',
    title: '46.3 · Cross-entropy and KL divergence',
    sections: ['Coding with the wrong model', 'Cross-entropy', 'KL divergence', 'Asymmetry', 'Why log-loss'],
    skill: 'Compute cross-entropy and KL divergence and connect them to log-loss and maximum likelihood.',
    prerequisite: 'Lessons 46.1–46.2; logistic regression (Lab 08).',
    paragraphs: [
      'If the data follow p but we design the code for q, each outcome costs −log₂ q(x), so the average is the **cross-entropy** H(p, q) = −Σ p(x) log₂ q(x).',
      'The extra cost over the best possible is the **Kullback–Leibler divergence** KL(p ‖ q) = H(p, q) − H(p) = Σ p(x) log(p(x)/q(x)). It is always ≥ 0 (Gibbs’ inequality, from Jensen) and 0 only when q = p.',
      'KL is not a distance: KL(p ‖ q) ≠ KL(q ‖ p) in general, and the difference matters. KL(p ‖ q) is huge if q assigns tiny probability to something p makes common (mass-covering); KL(q ‖ p) is huge if q puts mass where p has none (mode-seeking) — the variational-inference bias of Lab 44.',
      'A classifier trained with **log-loss** minimizes the average −log q(y | x) on the data: the cross-entropy between the data’s labels and the model. Since H(p) does not depend on the model, minimizing cross-entropy is minimizing KL(p_data ‖ q_model), which is the same as **maximum likelihood**.',
      'This is why a confident wrong prediction is so costly: q = 0.01 for the true class costs −log₂ 0.01 ≈ 6.6 bits, while 0.5 costs 1 bit. Log-loss rewards honest probabilities, which is also what calibration measures (Lab 09).',
    ],
    formula: 'H(p, q) = −Σ p log q     KL(p ‖ q) = Σ p log(p/q) = H(p, q) − H(p) ≥ 0',
    derivation: {
      title: 'KL between two coins',
      steps: [
        { prompt: 'Write KL(p ‖ q) in bits for coins with P(heads) = p and q.', answer: '(p*log(p/q) + (1-p)*log((1-p)/(1-q)))/log(2)', show: '`p log₂(p/q) + (1 − p) log₂((1 − p)/(1 − q))`', vars: { p: [0.05, 0.95], q: [0.05, 0.95] } },
        { prompt: 'KL(0.5 ‖ 0.9) in bits? (Three decimals.)', number: 0.5 * Math.log2(0.5 / 0.9) + 0.5 * Math.log2(0.5 / 0.1), tolerance: 1e-3, show: '`≈ 0.737`' },
        { prompt: 'KL(0.9 ‖ 0.5)? (Three decimals.)', number: 0.9 * Math.log2(0.9 / 0.5) + 0.1 * Math.log2(0.1 / 0.5), tolerance: 1e-3, show: '`≈ 0.531`', why: 'Different: KL is asymmetric.' },
      ],
      result: 'Believing a fair coin is biased costs more than believing a biased coin is fair — the direction matters.',
    },
    experiment: 'In the coding view, set q so it gives “timeout” almost no probability while p gives it 12%. Watch KL(p ‖ q) and KL(q ‖ p). Which explodes?',
    question: 'A model gives the true class probability 0.25. What is the log-loss for that example in bits?',
    answer: 2,
    explanation: '−log₂ 0.25 = 2 bits (≈ 1.386 nats, as libraries report it).',
    reflection: 'Explain to a classmate why minimizing cross-entropy and maximizing likelihood are the same thing.',
  },
  {
    id: 'l46-mi',
    title: '46.4 · Mutual information',
    sections: ['How much does X tell you about Y?', 'Two equivalent definitions', 'Beyond correlation', 'Estimating it is hard', 'Uses in ML'],
    skill: 'Compute mutual information from a joint table, interpret it, and estimate it carefully from samples.',
    prerequisite: 'Lessons 46.1–46.3; decision trees (Lab 12).',
    paragraphs: [
      '**Mutual information** I(X; Y) = H(Y) − H(Y | X) is the reduction in uncertainty about Y from learning X. It is symmetric, never negative, and zero exactly when X and Y are independent.',
      'Equivalently, I(X; Y) = KL(p(x, y) ‖ p(x)p(y)): how far the joint distribution is from what independence would predict. The information gain of a decision-tree split (Lab 12) is the mutual information between the split and the label.',
      'Correlation only measures straight-line dependence. For y = x² + noise, the correlation is about 0 yet y depends strongly on x; the mutual information shows it clearly. For feature screening, MI catches relationships correlation misses.',
      'From samples, MI must be estimated, and simple binned estimates are **biased upward**: with finite data, random fluctuations look like dependence, and more bins make it worse. Compare with a shuffled baseline (break the pairing, recompute) or use nearest-neighbour estimators (scikit-learn’s mutual_info_regression).',
      'MI appears across ML: feature selection, the information bottleneck, contrastive learning (InfoNCE is a lower bound on MI, Lab 56), and active learning (choose the query whose answer is most informative about the model).',
    ],
    formula: 'I(X; Y) = H(Y) − H(Y | X) = Σ p(x, y) log [p(x, y) / (p(x)p(y))]',
    derivation: {
      title: 'Mutual information from a table',
      intro: 'A feature X and label Y, each yes/no. P(X=1, Y=1) = 0.4, P(X=1, Y=0) = 0.1, P(X=0, Y=1) = 0.1, P(X=0, Y=0) = 0.4.',
      steps: [
        { prompt: 'H(Y) in bits?', number: 1, show: '`1` (Y is a fair coin)' },
        { prompt: 'H(Y | X) in bits? (Three decimals.)', number: -(0.8 * Math.log2(0.8) + 0.2 * Math.log2(0.2)), tolerance: 1e-3, show: '`H(0.8) ≈ 0.722`' },
        { prompt: 'I(X; Y) in bits? (Three decimals.)', number: 1 + (0.8 * Math.log2(0.8) + 0.2 * Math.log2(0.2)), tolerance: 1e-3, show: '`1 − 0.722 ≈ 0.278`' },
      ],
      result: 'Knowing X removes about 28% of the uncertainty about Y.',
    },
    experiment: 'In the MI view, compare the four relationships with 8 bins, then raise the bins to 20. What happens to the shuffled baseline, and what does that tell you about the estimator?',
    question: 'H(Y) = 0.9 bits and H(Y | X) = 0.6 bits. What is I(X; Y)?',
    answer: 0.3, tolerance: 1e-9,
    explanation: '0.9 − 0.6 = 0.3 bits.',
    reflection: 'Name a feature in your data that might be strongly but nonlinearly related to the target. How would you check?',
  },
  {
    id: 'l46-ml',
    title: '46.5 · Information theory across machine learning',
    sections: ['Perplexity', 'Label smoothing and confidence', 'Rate and distortion', 'Minimum description length', 'Demonstrate understanding'],
    skill: 'Use information-theoretic quantities to evaluate and reason about models.',
    prerequisite: 'Lessons 46.1–46.4.',
    paragraphs: [
      'Language models report **perplexity** = 2^(cross-entropy in bits per token): the effective number of equally likely choices the model faces at each step. On the playground text, perplexity falls from 27 (uniform) to about 16.6 (letter frequencies) to about 7.8 (previous letter) — measured on the training text itself, so optimistic.',
      'Cross-entropy training pushes probabilities toward 0 and 1 on training data, encouraging overconfidence. **Label smoothing** trains against a slightly softened target (e.g. 0.9 on the true class, the rest spread evenly), limiting how far log-loss can pull the logits.',
      'Compressing data lossily trades **rate** (bits) against **distortion** (error). The VAE objective (Lab 53) is exactly a rate term (a KL divergence) plus a distortion term (reconstruction error), and so is the ELBO of Labs 43–44.',
      '**Minimum description length** chooses the model that minimizes the bits needed to describe the model plus the data given the model — Occam’s razor in bits, closely related to BIC and the evidence (Labs 41, 43).',
      'You have completed this lab when you can: compute information, entropy, cross-entropy, KL and mutual information; relate entropy to optimal codes; explain why log-loss and maximum likelihood minimize KL; estimate mutual information honestly; and read perplexity. The Python challenge implements these quantities and checks them against known values and scikit-learn.',
    ],
    formula: 'perplexity = 2^(H(p, q) in bits)     MDL: minimize L(model) + L(data | model)',
    derivation: {
      title: 'Perplexity',
      steps: [
        { prompt: 'Write perplexity as a function of the cross-entropy h in bits.', answer: '2^h', show: '`2^h`', vars: { h: [0, 6] } },
        { prompt: 'A model has cross-entropy 3 bits per token. Perplexity?', number: 8, show: '`2³ = 8`' },
        { prompt: 'Another reports 2.0 nats per token. Its perplexity? (Two decimals.)', number: Math.exp(2), tolerance: 0.01, show: '`e² ≈ 7.39`', why: 'With nats, perplexity is e^H.' },
      ],
      result: 'Always check the unit before comparing perplexities.',
    },
    experiment: 'In the text view, compare perplexities. Why would the bigram model score worse on a different passage?',
    question: 'A language model’s perplexity drops from 32 to 16. By how many bits per token did its cross-entropy fall?',
    answer: 1,
    explanation: 'log₂ 32 − log₂ 16 = 5 − 4 = 1 bit per token.',
    reflection: 'Which evaluation metric in your work is secretly a cross-entropy? Which one should be?',
  },
]

export const sources = [
  { title: 'Cover & Thomas · Elements of Information Theory (2nd ed.)', url: 'https://doi.org/10.1002/047174882X' },
  { title: 'MacKay · Information Theory, Inference, and Learning Algorithms (free book)', url: 'https://www.inference.org.uk/itila/book.html' },
  { title: 'Shannon (1948) · A mathematical theory of communication', url: 'https://doi.org/10.1002/j.1538-7305.1948.tb01338.x' },
  { title: 'Olah · Visual information theory', url: 'https://colah.github.io/posts/2015-09-Visual-Information/' },
]
