// Lesson order for Lab 21: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l21-layers': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { cell: 0 },
    { predict: { prompt: 'A batch of 32 examples goes through a dense layer with W of shape (2, 8). How many numbers does Z = XW + b hold?', answer: 256, explain: 'Z has one row per example and one column per unit: (32, 8), so 32 × 8 = 256 numbers.', misconceptions: [{ answer: 16, feedback: 'That is the number of weights in W, 2 × 8. Z has one row per example.' }, { answer: 64, feedback: 'That would be (32, 2), the input’s shape. Z has one column per unit: 8.' }] } },
    { p: 3 },
    { figure: 'LayerShapes', caption: 'Choose the widths: every array’s shape and the parameter count follow.' },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l21-activations': [
    { p: 0 },
    { cell: 0 },
    { p: 1 },
    { figure: 'ActivationSlopes', caption: 'Each activation and its slope. Increase the depth and watch the best-case factor.' },
    { p: 2 },
    { cell: 1 },
    { predict: { prompt: 'A gradient passes back through 3 tanh layers whose local slopes are each 0.5. By what factor is it multiplied?', answer: 0.125, tolerance: 0.0005, explain: 'Backprop multiplies the local slopes: 0.5 × 0.5 × 0.5 = 0.125.', misconceptions: [{ answer: 1.5, feedback: 'Slopes multiply along the path; they do not add.' }] } },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l21-softmax': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { p: 2 },
    { figure: 'SoftmaxBars', caption: 'Move the three scores and choose the true class: probabilities (top) and the gradient p − one-hot (bottom).' },
    { p: 3 },
    { predict: { prompt: 'Two classes with equal scores, so p = (0.5, 0.5), and the true class is 0. What is ∂L/∂z₀?', answer: -0.5, tolerance: 0.0005, explain: 'p₀ − 1 = 0.5 − 1 = −0.5; and ∂L/∂z₁ = +0.5. Raising the true class’s score lowers the loss.', misconceptions: [{ answer: 0.5, feedback: 'That is ∂L/∂z₁, the wrong class. For the true class subtract 1: 0.5 − 1.' }] } },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l21-backprop': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { cell: 0 },
    { predict: { prompt: 'A_prev has shape (32, 8) and Δ has shape (32, 3). How many numbers are in ∂L/∂W = A_prevᵀΔ?', answer: 24, explain: 'A_prevᵀ is (8, 32) and Δ is (32, 3), so the product is (8, 3): 24 numbers, one per weight. The batch dimension is summed away.', misconceptions: [{ answer: 96, feedback: 'That is (32, 3), Δ’s size. The product sums over the 32 examples.' }, { answer: 256, feedback: 'That is A_prev’s size. ∂L/∂W has W’s shape, (8, 3).' }] } },
    { p: 3 },
    { cell: 1 },
    { figure: 'InitSpread', caption: 'The spread of the activations through ten ReLU layers, for three initial weight scales.' },
    { cell: 2 },
    { p: 4 },
    { math: true },
  ],
  'l21-train': [
    { p: 0 },
    { cell: 0 },
    { p: 1 },
    { cell: 1 },
    { p: 2 },
    { predict: { prompt: 'A binary classifier predicts p = 0.5 for the true class on every example. What is its cross-entropy loss, −log 0.5? (Three decimals.)', answer: 0.693, tolerance: 0.0006, explain: 'ln 2 ≈ 0.693: the loss of a coin flip. A loss stuck exactly here usually means the network is not using its inputs at all — symmetric or dead units.' } },
    { p: 3 }, { p: 4 },
    { math: true },
    { ladder: 'mlp' },
  ],
}
