export const lessons = [
  {
    id: 'l21-layers',
    title: '21.1 · From one neuron to layers',
    sections: ['A single neuron draws a line', 'Stacking neurons', 'A dense layer as a matrix product', 'Shapes through the network', 'Put it into practice'],
    skill: 'Write a dense layer as a matrix product and track array shapes through a multilayer network.',
    prerequisite: 'Labs 01–20; logistic regression (Lab 08), matrix products (Lab 03), backpropagation (Lab 20).',
    paragraphs: [
      'A logistic-regression unit computes σ(w·x + b): one linear score, one soft boundary line. On XOR no single line works (Lab 08 needed hand-made quadratic features). Neural networks learn the features instead.',
      'Put several units side by side, each with its own weights: a **layer**. Each unit\'s output is a new feature — a soft half-plane in the input space. Feed those features into another layer, and it can combine half-planes into bands, corners and islands.',
      'For a batch X of shape `(n, d)`, a dense layer with m units computes `Z = X W + b`, with W of shape `(d, m)` and b of shape `(m,)` broadcast over rows (Lab 02). Then an **activation** φ is applied elementwise: `A = φ(Z)`, shape `(n, m)`.',
      'A network 2 → 8 → 2 has W₁ `(2, 8)`, b₁ `(8,)`, W₂ `(8, 2)`, b₂ `(2,)`: 16 + 8 + 16 + 2 = 42 parameters. Every intermediate has one row per example. Writing these shapes down before coding prevents most bugs, exactly as in Lab 03.',
      'Procedure: choose layer widths; initialize weights (Lesson 21.4); run the forward pass layer by layer, storing Z and A for the backward pass; compute the loss; backpropagate; update; repeat.',
    ],
    formula: 'Z⁽ˡ⁾ = A⁽ˡ⁻¹⁾W⁽ˡ⁾ + b⁽ˡ⁾     A⁽ˡ⁾ = φ(Z⁽ˡ⁾)     shapes: (n, d_{l−1}) · (d_{l−1}, d_l) → (n, d_l)',
    experiment: 'On XOR, set 1 hidden unit and train. Then 2, 4 and 8. How many units does XOR need, and what do their activation maps look like?',
    question: 'How many parameters (weights and biases) does a 2 → 8 → 2 network have?',
    answer: 42,
    explanation: 'Layer 1: 2 × 8 + 8 = 24. Layer 2: 8 × 2 + 2 = 18. Total 42.',
    reflection: 'For an input with 20 features and 3 classes, write the shapes of every weight matrix and activation in a 20 → 64 → 64 → 3 network.',
  },
  {
    id: 'l21-activations',
    title: '21.2 · Why nonlinear activations',
    sections: ['Linear layers collapse', 'Common activations', 'Derivatives matter', 'Saturation and dead units', 'Choosing one'],
    skill: 'Explain why activations must be nonlinear and compare tanh, sigmoid and ReLU by their gradients.',
    prerequisite: 'Lesson 21.1; saturation (Lab 20).',
    paragraphs: [
      'Without an activation, two layers compute `(X W₁) W₂ = X (W₁W₂)` — a single linear map. Any number of linear layers collapses into one; the network would still draw one straight boundary. The nonlinearity between layers is what gives depth its power.',
      '**sigmoid** σ(z) squashes to (0, 1); **tanh** squashes to (−1, 1) and is zero-centred; **ReLU** `max(0, z)` passes positive values unchanged and zeroes negatives. All three let networks approximate essentially any continuous function given enough units.',
      'Their derivatives drive learning: sigmoid\'s is at most 0.25, tanh\'s at most 1, ReLU\'s is exactly 1 for positive inputs. Backprop multiplies these factors layer by layer (Lab 20), so in deep networks sigmoid and tanh shrink gradients geometrically — ReLU largely avoids that.',
      'Saturated sigmoid/tanh units (large |z|) have near-zero derivatives and stop learning. ReLU units whose inputs are negative for every example output 0 with zero gradient — **dead units** — often caused by a too-large learning rate. Variants like leaky ReLU keep a small slope for negatives.',
      'Default: ReLU (or a smooth relative such as GELU) in hidden layers; the output activation follows the task — softmax for classes, identity for regression. Try tanh and ReLU in the playground and compare the hidden-unit maps: soft ramps versus sharp creases.',
    ],
    formula: 'σ′(z) = σ(1−σ) ≤ 0.25     tanh′(z) = 1 − tanh² ≤ 1     ReLU′(z) = 1 if z > 0 else 0',
    experiment: 'Train the circles dataset with sigmoid, tanh and ReLU (same width and rate). Count steps to reach 95% training accuracy for each.',
    question: 'What is the maximum value of the sigmoid\'s derivative σ(z)(1 − σ(z))?',
    answer: 0.25,
    explanation: 'It peaks at z = 0 where σ = 0.5: 0.5 × 0.5 = 0.25. Through 10 sigmoid layers the gradient can shrink by 0.25¹⁰ ≈ 10⁻⁶.',
    reflection: 'Explain to a colleague, without equations, why a network of only linear layers is no more powerful than one linear layer.',
  },
  {
    id: 'l21-softmax',
    title: '21.3 · Softmax and cross-entropy',
    sections: ['More than two classes', 'Softmax', 'Stable computation', 'Cross-entropy', 'The gradient is simple again'],
    skill: 'Compute softmax probabilities stably and derive the softmax–cross-entropy gradient.',
    prerequisite: 'Lessons 21.1–21.2; logistic regression and log loss (Lab 08); log-sum-exp (Lab 11).',
    paragraphs: [
      'The final layer produces one score (logit) per class. **Softmax** turns scores into probabilities: `pₖ = e^{zₖ} / Σⱼ e^{zⱼ}`. All pₖ are positive and sum to 1; larger scores get more probability. With two classes it reduces to the sigmoid of the score difference.',
      'e^{1000} overflows. Subtracting the largest score first changes nothing mathematically — the factor e^{−max} cancels — and keeps every exponent ≤ 0: `softmax(z) = softmax(z − max(z))`. This is the log-sum-exp trick from Lab 11.',
      '**Cross-entropy** for one example with true class y is `−log p_y`, the multi-class version of Lab 08\'s log loss, derived the same way from likelihood. For scores (2, 1, 0) and true class 0: p₀ = e²/(e² + e + 1) ≈ 0.665, loss ≈ 0.408.',
      'Softmax and cross-entropy combine into a remarkably simple gradient with respect to the scores: `∂L/∂zₖ = pₖ − 1[k = y]`. Predicted probability minus the one-hot truth — the same "prediction minus target" shape as linear and logistic regression.',
      'Averaged over n examples, the output layer\'s error signal is `(P − Y)/n`; everything upstream follows from Lab 20\'s chain rule. The playground\'s three-arm spiral uses three softmax outputs.',
    ],
    formula: 'pₖ = e^{zₖ − m} / Σⱼ e^{zⱼ − m} (m = max z)     L = −log p_y     ∂L/∂zₖ = pₖ − 1[k = y]',
    experiment: 'On the three-arm spiral, watch the loss start near log 3 ≈ 1.10 (uniform guessing) and fall. Why is that the starting value?',
    question: 'Scores (2, 1, 0) and true class 0 give p₀ ≈ 0.665. What is ∂L/∂z₀ = p₀ − 1? (Three decimals.)',
    answer: -0.335, tolerance: 0.001,
    explanation: '0.665 − 1 = −0.335: increasing the correct class\'s score lowers the loss. The other classes get +p₁ ≈ 0.245 and +p₂ ≈ 0.090.',
    reflection: 'Why does it matter that the softmax–cross-entropy gradient never saturates the way a sigmoid with squared error would?',
  },
  {
    id: 'l21-backprop',
    title: '21.4 · Backpropagation in matrix form, and initialization',
    sections: ['Layer by layer', 'The weight gradient', 'Passing the error back', 'Symmetry and scale', 'Check every layer'],
    skill: 'Implement a vectorized backward pass for dense layers and initialize weights correctly.',
    prerequisite: 'Lessons 21.1–21.3; backpropagation (Lab 20).',
    paragraphs: [
      'Let Δ⁽ˡ⁾ = ∂L/∂Z⁽ˡ⁾, shape `(n, d_l)`. At the output, Δ = (P − Y)/n. Everything else follows from Z = A_prev W + b.',
      'Weight gradient: `∂L/∂W = A_prevᵀ Δ`, shape `(d_{l−1}, d_l)` — each weight\'s gradient sums input-times-error over the batch, the same Xᵀ(error) pattern as Lab 03. Bias gradient: the column sums of Δ.',
      'Error for the layer below: `∂L/∂A_prev = Δ Wᵀ`, then multiply elementwise by the activation derivative: `Δ_prev = (Δ Wᵀ) ⊙ φ′(Z_prev)`. Repeat down to the first layer. Two matrix products per layer; the backward pass costs about twice the forward pass.',
      'Initialization matters. All-zero weights give every hidden unit identical outputs and identical gradients: they stay identical forever (**symmetry**). Random weights break symmetry, but their scale must keep activations and gradients from shrinking or exploding across layers: **He** initialization N(0, 2/fan_in) for ReLU, **Xavier/Glorot** N(0, 1/fan_in) for tanh.',
      'Verify with finite differences on a few weights per layer (the playground\'s "Check gradients"). A correct implementation agrees to about 10⁻⁷ relative error. Then train, and watch both training and validation loss.',
    ],
    formula: '∂L/∂W⁽ˡ⁾ = A⁽ˡ⁻¹⁾ᵀ Δ⁽ˡ⁾     ∂L/∂b⁽ˡ⁾ = Σ_rows Δ⁽ˡ⁾     Δ⁽ˡ⁻¹⁾ = (Δ⁽ˡ⁾ W⁽ˡ⁾ᵀ) ⊙ φ′(Z⁽ˡ⁻¹⁾)',
    experiment: 'Initialize with all zeros and train XOR for 500 steps. Look at the hidden-unit maps. Then switch to He initialization.',
    question: 'He initialization draws weights from N(0, 2/fan_in). For a layer with 50 inputs, what is the standard deviation? (Two decimals.)',
    answer: 0.2, tolerance: 0.001,
    explanation: '√(2/50) = √0.04 = 0.2.',
    reflection: 'Why does zero initialization work for logistic regression (Lab 08) but fail for a hidden layer?',
  },
  {
    id: 'l21-train',
    title: '21.5 · Training and diagnosing a network',
    sections: ['The loop', 'Capacity', 'Overfitting again', 'Common failures', 'Demonstrate understanding'],
    skill: 'Train a small network, choose its capacity, and diagnose common training failures.',
    prerequisite: 'Lessons 21.1–21.4; overfitting (Lab 07).',
    paragraphs: [
      'The training loop is Lab 01\'s with more layers: forward, loss, backward, update, repeat — here with the full training set each step. Plot training and validation loss as you go.',
      'Width and depth set **capacity**. Too little and even the training loss stays high (a 1-unit XOR network); plenty and the training loss approaches zero. With 180 training points, a 32 × 32 network can memorize noise; validation loss is the honest judge, as always (Lab 07).',
      'Failures and their signatures: loss stuck at log(k) → symmetry or dead units; loss exploding to NaN → learning rate too high; training loss falling while validation loss rises → overfitting; very slow progress → saturation or too small a rate. Each has a standard fix, most of which Lab 22 examines.',
      'Networks are rarely the best tool for small tabular datasets — the ensembles of Labs 13–14 usually win there. Their strength is learning features from raw, high-dimensional inputs like images, audio and text, where hand-engineering features is hopeless (Labs 24–26).',
      'You have completed this lab when you can: track shapes through dense layers; explain why nonlinearity is needed; compute stable softmax and cross-entropy; implement and gradient-check a matrix backward pass; initialize correctly; and diagnose a training run. The Python challenge builds a two-layer network in NumPy.',
    ],
    formula: 'loop: P = forward(X); L = CE(P, Y); grads = backward(); params −= α·grads',
    experiment: 'On the spiral, use width 32 and 3 layers, then width 4 and 1 layer. Compare training and validation accuracy for each. Which one is capacity-limited?',
    question: 'A 3-class network starts with uniform predictions. What is its initial cross-entropy −log(1/3)? (Three decimals.)',
    answer: 1.0986, tolerance: 0.0006,
    explanation: 'ln 3 ≈ 1.099. A starting loss far above this means the initial predictions are confidently wrong — often a sign of too-large initial weights.',
    reflection: 'Your network\'s loss is stuck at 0.693 on a binary task. List three possible causes and how you would check each.',
  },
]

export const sources = [
  { title: 'Dive into Deep Learning · Chapter 5: multilayer perceptrons', url: 'https://d2l.ai/chapter_multilayer-perceptrons/index.html' },
  { title: 'Glorot & Bengio (2010) · Understanding the difficulty of training deep feedforward networks', url: 'https://proceedings.mlr.press/v9/glorot10a.html' },
  { title: 'He et al. (2015) · Delving deep into rectifiers (He initialization)', url: 'https://arxiv.org/abs/1502.01852' },
  { title: 'CS231n · Neural networks part 1–3 notes', url: 'https://cs231n.github.io/neural-networks-1/' },
]
