const AB = { a: [-1.5, 1.5], b: [-1, 1], x: [-2, 2], y: [0, 5] }

export const lessons = [
  {
    id: 'l39-expfam',
    title: '39.1 · The exponential family',
    sections: ['Three distributions, one shape', 'Bernoulli in disguise', 'Gaussian and Poisson', 'The log-partition knows the moments', 'Put it into practice'],
    skill: 'Write Bernoulli, Gaussian and Poisson distributions in exponential-family form and read off their mean and variance.',
    prerequisite: 'Core labs 01–33, especially likelihood (Lab 05), logistic regression (Lab 08) and derivatives (Lab 01).',
    paragraphs: [
      'Linear regression, logistic regression and count regression look like separate inventions. They are one idea. Each assumes the target comes from a distribution in the **exponential family**: p(y; η) = b(y) · exp(η·y − a(η)). Here η is the **natural parameter**, a(η) is the **log-partition function** that makes the probabilities sum to 1, and b(y) does not depend on η.',
      'Take a Bernoulli variable with P(y = 1) = φ. Its probability is φ^y (1 − φ)^(1 − y). Take logs: y·log φ + (1 − y)·log(1 − φ) = y·log(φ/(1 − φ)) + log(1 − φ). Matching the form gives η = log(φ/(1 − φ)) — the log-odds from Lab 08 — and a(η) = log(1 + e^η). Inverting, φ = 1/(1 + e^(−η)): the sigmoid appears on its own; nobody chose it.',
      'A Gaussian with variance 1: log p = −(y − μ)²/2 + const = y·μ − μ²/2 + (terms in y only). So η = μ and a(η) = η²/2. A Poisson count with mean λ: log p = y·log λ − λ − log y!, so η = log λ and a(η) = e^η.',
      'The log-partition function carries the moments: **a′(η) = E[y]** and **a″(η) = Var(y)**. Check: Bernoulli a′(η) = σ(η) = φ and a″ = φ(1 − φ); Poisson a′ = a″ = e^η = λ. Because a″ is a variance, it is never negative — so the negative log-likelihood a(η) − yη is **convex** in η. That is why these models have a single minimum.',
      'Procedure: write log p(y), collect the terms that multiply y (that coefficient is η), and put the rest that depends on the parameter into −a(η). Then differentiate a to get the mean and variance. The derivation below walks the Bernoulli case.',
    ],
    formula: 'p(y; η) = b(y) exp(ηy − a(η))     a′(η) = E[y]     a″(η) = Var(y) ≥ 0',
    derivation: {
      title: 'Put the Bernoulli distribution in exponential-family form',
      intro: 'Use φ for P(y = 1) and η for the natural parameter.',
      steps: [
        { prompt: 'The coefficient of y in log p(y) = y·log(φ/(1 − φ)) + log(1 − φ) is the natural parameter. Write η in terms of φ.', answer: 'log(φ/(1-φ))', show: '`η = log(φ / (1 − φ))` — the log-odds', vars: { φ: [0.05, 0.95] } },
        { prompt: 'Invert it: write φ in terms of η.', answer: '1/(1+exp(-η))', show: '`φ = 1 / (1 + e^(−η)) = σ(η)`', vars: { η: [-4, 4] }, hint: 'Solve e^η = φ/(1 − φ) for φ.' },
        { prompt: 'The remaining term is log(1 − φ) = −a(η). Write a(η) in terms of η.', answer: 'log(1+exp(η))', show: '`a(η) = log(1 + e^η)`', vars: { η: [-4, 4] }, hint: 'Substitute φ = σ(η): 1 − σ(η) = 1/(1 + e^η).' },
        { prompt: 'Differentiate: a′(η) = ?', answer: 'exp(η)/(1+exp(η))', show: '`a′(η) = σ(η)` — the mean φ', vars: { η: [-4, 4] } },
        { prompt: 'Differentiate again: a″(η) = ?', answer: 'σ(η)*(1-σ(η))', show: '`a″(η) = σ(η)(1 − σ(η))` — the Bernoulli variance', vars: { η: [-4, 4] }, hint: 'The derivative of σ(η) is σ(η)(1 − σ(η)).' },
        { prompt: 'Evaluate the variance a″(η) at η = 0.', number: 0.25, tolerance: 1e-6, show: '`0.25`', why: 'σ(0) = 0.5, and 0.5 × 0.5 = 0.25: a fair coin is the most uncertain Bernoulli.' },
      ],
      result: 'The sigmoid, the log-loss and its convexity all follow from writing the Bernoulli likelihood in one standard form.',
    },
    experiment: 'In the Newton view, switch between the three models. The loss has the same form a(η) − yη each time — only a(η) changes. How does the fitted mean curve differ between them?',
    question: 'A Poisson model has natural parameter η = 1.2. What is the expected count a′(η) = e^η? (Three decimals.)',
    answer: 3.3201, tolerance: 0.001,
    explanation: 'For the Poisson, a(η) = e^η, so the mean is e^1.2 ≈ 3.320 — and the variance is the same number.',
    reflection: 'For a target in your own work, which exponential-family distribution fits it: continuous, yes/no, or a count?',
  },
  {
    id: 'l39-glm',
    title: '39.2 · Generalized linear models and count data',
    sections: ['Three assumptions', 'Why not linear regression for counts?', 'One gradient for every GLM', 'Reading a log-link coefficient', 'When the variance does not match'],
    skill: 'Build a GLM from three assumptions, derive its gradient and Hessian, and interpret a Poisson regression.',
    prerequisite: 'Lesson 39.1; matrix gradients (Lab 03).',
    paragraphs: [
      'A **generalized linear model** makes three assumptions: (1) given x, y follows an exponential-family distribution with natural parameter η; (2) η is linear in the inputs, η = θᵀx; (3) the prediction is the mean, h(x) = E[y | x] = a′(θᵀx). The function a′ that maps η to the mean is the **canonical response function**; its inverse is the **link**.',
      'Counts — failed builds per day, support tickets per hour — are non-negative integers whose spread grows with their size. Linear regression can predict −2 tickets and assumes constant noise. Poisson regression uses μ = exp(θᵀx): predictions are always positive, and the variance equals the mean.',
      'For one observation the negative log-likelihood is ℓ = a(θᵀx) − y·θᵀx (plus a constant). Its gradient is **(a′(θᵀx) − y)·x = (μ − y)·x** — prediction minus target, times the input. Linear regression (μ = η), logistic regression (μ = σ(η)) and Poisson regression (μ = e^η) all share this gradient. The Hessian is a″(θᵀx)·xxᵀ = Var(y)·xxᵀ, positive semidefinite, so the loss is convex.',
      'With a log link, coefficients act multiplicatively: increasing x by 1 multiplies the expected count by e^θ₁. In the playground’s count data, θ₁ ≈ 0.24, so each unit of x multiplies the expected count by about 1.28.',
      'Real counts are often **overdispersed**: their variance exceeds their mean (for example because of unmeasured differences between days). The Poisson fit then understates uncertainty. Check by comparing the average squared residual with the average prediction; if it is much larger, use a negative binomial or quasi-Poisson model.',
    ],
    formula: 'η = θᵀx     μ = a′(η)     ∇ℓ = (μ − y)x     ∇²ℓ = Var(y)·xxᵀ',
    derivation: {
      title: 'Derive the gradient and curvature of Poisson regression',
      intro: 'One observation (x, y) with η = a + b·x, where a is the intercept θ₀ and b the slope θ₁. The loss is ℓ = e^η − y·η.',
      steps: [
        { prompt: 'Write the loss ℓ in terms of a, b, x and y.', answer: 'exp(a+b*x) - y*(a+b*x)', show: '`ℓ = e^(a + bx) − y(a + bx)`', vars: AB },
        { prompt: '∂ℓ/∂b = ?', answer: '(exp(a+b*x) - y)*x', show: '`(e^(a + bx) − y)·x = (μ − y)·x`', vars: AB, hint: 'Chain rule: ∂η/∂b = x.' },
        { prompt: '∂ℓ/∂a = ?', answer: 'exp(a+b*x) - y', show: '`μ − y`', vars: AB },
        { prompt: 'Second derivative ∂²ℓ/∂b² = ?', answer: 'exp(a+b*x)*x^2', show: '`e^(a + bx)·x² = Var(y)·x²`', vars: AB },
        { prompt: 'At a = 0, b = 0.5, x = 2, y = 1: evaluate ∂ℓ/∂b.', number: 2 * (Math.E - 1), tolerance: 1e-3, show: '`2(e − 1) ≈ 3.437`', why: 'μ = e¹ ≈ 2.718 exceeds y = 1, so the gradient is positive: decrease b.' },
      ],
      result: 'Prediction minus target, times the input — the same gradient as linear and logistic regression. Only the mean function changes.',
    },
    experiment: 'Choose the Poisson model and watch the fitted mean curve bend upward. Why can this curve never predict a negative count?',
    question: 'A Poisson regression has slope θ₁ = 0.25. By what factor does the expected count multiply when x increases by 1? (Three decimals.)',
    answer: 1.284, tolerance: 0.001,
    explanation: 'e^0.25 ≈ 1.284: each extra unit of x raises the expected count by about 28%, whatever the starting level.',
    reflection: 'Name a count you care about. What would overdispersion mean for it in plain words?',
  },
  {
    id: 'l39-softmax',
    title: '39.3 · Softmax regression for many classes',
    sections: ['One score per class', 'Softmax', 'The gradient', 'Stability and redundancy', 'Two classes again'],
    skill: 'Derive the softmax cross-entropy gradient and implement multiclass regression stably.',
    prerequisite: 'Lessons 39.1–39.2; cross-entropy (Lab 08).',
    paragraphs: [
      'With K classes, give each class k its own weight vector wₖ and score zₖ = wₖᵀx. Scores can be any real numbers; we need K probabilities that are positive and sum to 1.',
      'The **softmax** does it: pₖ = exp(zₖ) / Σⱼ exp(zⱼ). It is the multinomial distribution written in exponential-family form, just as the sigmoid came from the Bernoulli. The prediction is the class with the highest probability, and the boundaries between classes are straight lines where two scores tie.',
      'The loss for an observation of class y is the cross-entropy −log p_y = −z_y + log Σⱼ exp(zⱼ). Its derivative with respect to score zₖ is **pₖ − 1[k = y]**: push the true class’s probability up and every other class’s down, each in proportion to its current probability. With respect to wₖ, multiply by x.',
      'Exponentials overflow: exp(1000) is infinite in floating point. Subtract the largest score from all scores first — softmax is unchanged by adding the same constant to every score. That same fact means one weight vector is redundant; regularization or fixing one class to zero removes the ambiguity.',
      'With K = 2, p₁ = 1/(1 + exp(−(z₁ − z₀))) — the sigmoid of the difference of two scores. Logistic regression is softmax regression with two classes.',
    ],
    formula: 'pₖ = exp(zₖ) / Σⱼ exp(zⱼ)     ∂(−log p_y)/∂zₖ = pₖ − 1[k = y]',
    derivation: {
      title: 'Differentiate the softmax cross-entropy',
      intro: 'Three classes with scores z1, z2, z3; the true class is class 1. The loss is L = −z1 + log(exp(z1) + exp(z2) + exp(z3)).',
      steps: [
        { prompt: '∂L/∂z1 = ?', answer: 'exp(z1)/(exp(z1)+exp(z2)+exp(z3)) - 1', show: '`p₁ − 1`', vars: { z1: [-2, 2], z2: [-2, 2], z3: [-2, 2] }, hint: 'Differentiate −z1 (gives −1) and log Σ exp (gives exp(z1)/Σ exp).' },
        { prompt: '∂L/∂z2 = ?', answer: 'exp(z2)/(exp(z1)+exp(z2)+exp(z3))', show: '`p₂`', vars: { z1: [-2, 2], z2: [-2, 2], z3: [-2, 2] } },
        { prompt: 'Check the stability trick: write p₁ after subtracting a constant c from every score. (Use c as a variable.)', answer: 'exp(z1-c)/(exp(z1-c)+exp(z2-c)+exp(z3-c))', show: '`exp(z1 − c) / Σ exp(zⱼ − c)` — the same value as before', vars: { z1: [-2, 2], z2: [-2, 2], z3: [-2, 2], c: [-3, 3] }, why: 'e^(−c) cancels from numerator and denominator.' },
        { prompt: 'With scores (z1, z2, z3) = (2, 1, 0) and true class 1, evaluate ∂L/∂z1.', number: Math.exp(2) / (Math.exp(2) + Math.E + 1) - 1, tolerance: 1e-3, show: '`p₁ − 1 ≈ −0.335`' },
      ],
      result: 'Sum the three derivatives: (p₁ − 1) + p₂ + p₃ = 0. The gradient only moves probability between classes; it cannot change the total.',
    },
    experiment: 'In the softmax view, move the gradient-descent step from 0 to 200 and place the probe point on a boundary between two regions. What are the two largest probabilities there?',
    question: 'Scores are (2, 1, 0). What probability does softmax give the first class? (Three decimals.)',
    answer: 0.6652, tolerance: 0.001,
    explanation: 'e² / (e² + e + 1) = 7.389 / 11.107 ≈ 0.665.',
    reflection: 'When your classes are not mutually exclusive (a ticket can be both “billing” and “urgent”), why is softmax the wrong output layer?',
  },
  {
    id: 'l39-newton',
    title: '39.4 · Newton’s method and IRLS',
    sections: ['Minimize the local quadratic', 'Quadratic convergence', 'Iteratively reweighted least squares', 'Invariant to rescaling', 'When not to use Newton'],
    skill: 'Apply Newton’s method to GLMs, recognise quadratic convergence, and choose between Newton, quasi-Newton and gradient methods.',
    prerequisite: 'Lessons 39.1–39.3; eigenvalues and conditioning (Lab 03), optimization (Lab 22).',
    paragraphs: [
      'Gradient descent uses only the slope. Newton’s method also uses the curvature: it fits the quadratic that matches the function’s value, slope and curvature at θ, and jumps to that quadratic’s minimum. In one dimension, θ ← θ − f′(θ)/f″(θ); in many, **θ ← θ − H⁻¹∇f**, where H is the Hessian.',
      'Near the optimum, Newton’s error roughly **squares** each step: 10⁻³, then 10⁻⁶, then 10⁻¹². In the playground the logistic loss gap falls 4 × 10⁻⁷ → 2 × 10⁻¹² in a single step. Gradient descent’s error shrinks by a constant factor per step, which can be painfully close to 1 when the problem is ill-conditioned.',
      'For a GLM, H = (1/n) Xᵀ S X with S = diag(Var(yᵢ)). Each Newton step solves a weighted least-squares problem whose weights are the current variances — hence **iteratively reweighted least squares** (IRLS), the classic algorithm in statistics packages. For the Gaussian, the loss is exactly quadratic and Newton finishes in one step: it is the normal equations.',
      'Rescale x and gradient descent changes completely (the contours stretch), but Newton’s iterates simply rescale with it: it is **affine invariant**. That is why standardizing inputs matters a lot for gradient methods and not at all for Newton.',
      'Costs: each step forms a d × d Hessian (n·d² work) and solves it (d³). For thousands of features, quasi-Newton methods such as **L-BFGS** approximate H⁻¹ from recent gradients — the default solver of scikit-learn’s LogisticRegression. Far from the optimum, a pure Newton step can overshoot; damping (halving the step until the loss drops) fixes it. On perfectly separable classification data there is no finite optimum at all: regularize.',
    ],
    formula: 'θ ← θ − H⁻¹∇f     GLM: ∇f = Xᵀ(μ − y)/n,  H = XᵀSX/n,  S = diag(a″(η))',
    derivation: {
      title: 'Run Newton’s method by hand',
      intro: 'Minimize f(θ) = e^θ − 2θ (a Poisson model with only an intercept and one observation y = 2). The minimum is at θ = log 2 ≈ 0.693.',
      steps: [
        { prompt: 'f′(θ) = ?', answer: 'exp(θ) - 2', show: '`e^θ − 2`', vars: { θ: [-1, 2] } },
        { prompt: 'f″(θ) = ?', answer: 'exp(θ)', show: '`e^θ`', vars: { θ: [-1, 2] } },
        { prompt: 'Write the Newton update θ_new as a function of θ.', answer: 'θ - (exp(θ)-2)/exp(θ)', show: '`θ − (e^θ − 2)/e^θ = θ − 1 + 2e^(−θ)`', vars: { θ: [-1, 2] } },
        { prompt: 'Start at θ = 0. What is θ after one step?', number: 1, tolerance: 1e-6, show: '`1`' },
        { prompt: 'And after the second step? (Three decimals.)', number: 1 - (Math.E - 2) / Math.E, tolerance: 1e-3, show: '`1 − (e − 2)/e ≈ 0.736`', why: 'Errors: 0.693 → 0.307 → 0.043 → next about 0.001 — squaring each time.' },
      ],
      result: 'Each error is roughly the square of the previous one (times a constant): the digits of accuracy double every step.',
    },
    experiment: 'In the Newton view with raw x, compare the two convergence curves. Then standardize x. Which method changes, and which does not?',
    question: 'With quadratic convergence, an error of 10⁻³ becomes about 10⁻⁶ after one step. About what is it after the next step? Answer with the exponent (e.g. −9).',
    answer: -12,
    explanation: 'Squaring 10⁻⁶ gives 10⁻¹²: the number of correct digits doubles each step.',
    reflection: 'You have 5 million features. Why is Newton’s method impractical, and what would you use instead?',
  },
  {
    id: 'l39-lwr',
    title: '39.5 · Locally weighted regression',
    sections: ['Keep the data, fit per query', 'The weights', 'Choosing the bandwidth', 'Parametric versus non-parametric', 'Demonstrate understanding'],
    skill: 'Implement locally weighted regression and choose its bandwidth by leave-one-out error.',
    prerequisite: 'Lessons 39.1–39.4; weighted least squares, k-NN (Lab 10), cross-validation (Lab 06).',
    paragraphs: [
      'A straight line cannot follow a wave. Instead of choosing a more flexible global model, **locally weighted regression** fits a new straight line for every query point, using mostly the nearby data. The model is the dataset itself.',
      'For query x, each training point gets weight wᵢ = exp(−(xᵢ − x)² / (2τ²)). A point at distance τ gets weight e^(−0.5) ≈ 0.61; at 2τ, e^(−2) ≈ 0.14; at 3τ, about 0.011. Fit weighted least squares — minimize Σ wᵢ (yᵢ − θᵀxᵢ)² — and predict θᵀx.',
      'The **bandwidth** τ sets the bias–variance trade-off (Lab 07). Small τ uses few points and follows noise; large τ approaches one global line. Training error always prefers the smallest τ, so choose it with leave-one-out or cross-validation error, as the playground does.',
      'Linear regression is **parametric**: after training, θ summarizes the data and the data can be discarded. LWR is **non-parametric**: its complexity grows with the data, every prediction touches every training point, and memory holds the whole dataset. k-NN (Lab 10) and Gaussian processes (Lab 42) share these properties.',
      'You have completed this lab when you can: write a distribution in exponential-family form and read off its mean and variance; build a GLM from its three assumptions; derive the shared (μ − y)x gradient and the Hessian; implement softmax regression stably; apply Newton’s method/IRLS and explain its speed and cost; and choose a bandwidth for locally weighted regression honestly. The Python challenge implements all four.',
    ],
    formula: 'wᵢ(x) = exp(−(xᵢ − x)² / 2τ²)     θ(x) = argmin Σ wᵢ(x)(yᵢ − θᵀxᵢ)²',
    derivation: {
      title: 'Compute locally weighted regression weights',
      steps: [
        { prompt: 'Write the weight of training point xi for query x with bandwidth τ.', answer: 'exp(-(xi-x)^2/(2τ^2))', show: '`exp(−(xᵢ − x)² / (2τ²))`', vars: { xi: [0, 10], x: [0, 10], τ: [0.5, 3] } },
        { prompt: 'Weight of a point 2 units from the query when τ = 1? (Four decimals.)', number: Math.exp(-2), tolerance: 1e-4, show: '`e^(−2) ≈ 0.1353`' },
        { prompt: 'Same point, τ = 2?', number: Math.exp(-0.5), tolerance: 1e-4, show: '`e^(−0.5) ≈ 0.6065`', why: 'Doubling τ makes the same distance count as “half as far”.' },
      ],
      result: 'Only distance divided by τ matters: the bandwidth is the unit in which “near” is measured.',
    },
    experiment: 'In the locally weighted view, drag the query point across the plot at τ = 0.8, then try τ = 0.2 and τ = ∞. Which τ does leave-one-out error choose, and does the curve look reasonable there?',
    question: 'With τ = 1, what weight does a point 3 units from the query receive? (Three decimals.)',
    answer: 0.0111, tolerance: 0.001,
    explanation: 'exp(−9/2) = e^(−4.5) ≈ 0.011 — practically ignored.',
    reflection: 'When would you accept the prediction cost of a non-parametric model in your work, and when not?',
  },
]

export const sources = [
  { title: 'Stanford CS229 lecture notes · Generalized linear models, Newton’s method, locally weighted regression', url: 'https://cs229.stanford.edu/main_notes.pdf' },
  { title: 'McCullagh & Nelder · Generalized Linear Models (2nd ed.)', url: 'https://doi.org/10.1201/9780203753736' },
  { title: 'Boyd & Vandenberghe · Convex Optimization, §9.5 Newton’s method (free book)', url: 'https://web.stanford.edu/~boyd/cvxbook/' },
  { title: 'scikit-learn · Generalized linear models (Poisson, Tweedie) and solvers', url: 'https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-models' },
]
