export const lessons = [
  {
    id: 'l54-gan',
    title: '54.1 · Generative adversarial networks',
    sections: ['Generating without a likelihood', 'A two-player game', 'The optimal discriminator', 'What the generator minimizes', 'Put it into practice'],
    skill: 'Explain the GAN game, its optimal discriminator and the divergence it minimizes.',
    prerequisite: 'Autoencoders and VAEs (Lab 53), logistic regression (Lab 08), KL divergence (Lab 46).',
    paragraphs: [
      'VAEs (Lab 53) optimize a likelihood bound and tend to produce blurry samples. **Generative adversarial networks** (GANs) drop likelihoods altogether: a **generator** G turns noise z into samples, and a **discriminator** D, a classifier, learns to tell real data from generated.',
      'They play a game. D maximizes E_data[log D(x)] + E_z[log(1 − D(G(z)))] — ordinary logistic-regression log-likelihood with real = 1, fake = 0. G minimizes the same quantity: it wins by making D wrong.',
      'For a fixed generator with density p_g, the best discriminator is **D*(x) = p_data(x) / (p_data(x) + p_g(x))**: the probability that a point at x came from the data. Where generated points are too dense, D* says “fake”; where they are missing, “real”.',
      'Plugging D* back in, the generator minimizes 2·JS(p_data ‖ p_g) − log 4, where JS is the Jensen–Shannon divergence. At the equilibrium p_g = p_data and D = ½ everywhere.',
      'Procedure: alternate a discriminator step and a generator step; watch both losses (neither should win outright); inspect samples regularly with fixed noise; and measure diversity, not only sharpness.',
    ],
    formula: 'min_G max_D  E_x[log D(x)] + E_z[log(1 − D(G(z)))]     D*(x) = p_data(x) / (p_data(x) + p_g(x))',
    derivation: {
      title: 'Derive the optimal discriminator',
      intro: 'At a single point x, with data density a = p_data(x) and generator density b = p_g(x), D chooses a value d in (0, 1) to maximize a·log d + b·log(1 − d).',
      steps: [
        { prompt: 'Differentiate a·log d + b·log(1 − d) with respect to d.', answer: 'a/d - b/(1-d)', show: '`a/d − b/(1 − d)`', vars: { a: [0.1, 2], b: [0.1, 2], d: [0.05, 0.95] } },
        { prompt: 'Set it to zero and solve for d.', answer: 'a/(a+b)', show: '`d* = a/(a + b)`', vars: { a: [0.1, 2], b: [0.1, 2] } },
        { prompt: 'If the generator matches the data exactly (a = b), what is D*?', number: 0.5, show: '`½` — the discriminator cannot do better than guessing' },
      ],
      result: 'The discriminator estimates a density ratio; the generator learns by following its gradient.',
    },
    experiment: 'In the GAN view with balanced training, watch the snapshots. At which step do the eight clusters first appear?',
    question: 'At some x, real data are 3 times as dense as generated samples. What does the optimal discriminator output there?',
    answer: 0.75,
    explanation: 'D* = 3/(3 + 1) = 0.75.',
    reflection: 'Why might a generator that never sees the data directly still learn to produce it?',
  },
  {
    id: 'l54-gantrain',
    title: '54.2 · Training GANs: saturation, balance and mode collapse',
    sections: ['Saturating gradients', 'The non-saturating trick', 'Keeping the players balanced', 'Mode collapse', 'Stabilizers'],
    skill: 'Diagnose GAN training failures and apply standard remedies.',
    prerequisite: 'Lesson 54.1; optimization (Lab 22).',
    paragraphs: [
      'Early in training, generated samples are obviously fake, D(G(z)) ≈ 0, and log(1 − D) is flat there: the generator’s gradient vanishes. The **non-saturating** loss instead maximizes log D(G(z)) — same fixed point, strong gradients when the generator is losing. It is the standard choice.',
      'The two networks must stay balanced. If the discriminator becomes perfect, its gradients carry little information; if the generator is updated much faster, it exploits the discriminator’s current blind spot.',
      'That exploitation is **mode collapse**: the generator maps most noise to one convincing region. In the playground, five generator steps per discriminator step at a higher learning rate put nearly all samples on one of the eight clusters, while balanced training covers all eight. When the discriminator adapts, a collapsed generator often hops to another mode instead of spreading out.',
      'Stabilizers: Wasserstein GANs with gradient penalties (a smoother distance than JS), spectral normalization of the discriminator, two-time-scale learning rates, minibatch discrimination, and careful architectures. GAN training remains finicky; diffusion models (next lessons) sidestep the game entirely.',
      'Always evaluate diversity: count modes or classes produced, compare feature statistics (FID), and look for near-copies of training examples.',
    ],
    formula: 'saturating: min log(1 − D(G(z)))     non-saturating: max log D(G(z))',
    derivation: {
      title: 'Why the original generator loss saturates',
      intro: 'Let D(G(z)) = σ(ℓ) with discriminator logit ℓ.',
      steps: [
        { prompt: 'Derivative of log(1 − σ(ℓ)) with respect to ℓ.', answer: '-σ(ℓ)', show: '`−σ(ℓ)`', vars: { ℓ: [-6, 6] }, hint: 'Type ℓ as ell.' },
        { prompt: 'Derivative of −log σ(ℓ) (the non-saturating loss) with respect to ℓ.', answer: 'σ(ℓ) - 1', show: '`σ(ℓ) − 1`', vars: { ℓ: [-6, 6] } },
        { prompt: 'When the discriminator is confident a sample is fake, ℓ = −6. Magnitude of the saturating gradient? (Four decimals.)', number: 1 / (1 + Math.exp(6)), tolerance: 1e-4, show: '`σ(−6) ≈ 0.0025`' },
        { prompt: 'And of the non-saturating gradient? (Four decimals.)', number: 1 - 1 / (1 + Math.exp(6)), tolerance: 1e-4, show: '`1 − σ(−6) ≈ 0.9975`', why: 'About 400 times stronger exactly when the generator most needs to learn.' },
      ],
      result: 'Same equilibrium, very different gradients early in training.',
    },
    experiment: 'Switch the GAN view to the generator-heavy schedule and compare the per-mode bar chart with balanced training. Try all three seeds.',
    question: 'A GAN produces 1,000 samples: 970 near one mode and the rest spread over the other seven. Is that mode collapse?',
    choices: [
      { text: 'Yes', why: '97% of samples sit on one of eight modes. Diversity is what failed, even if every sample looks good.' },
      { text: 'No — every mode gets some samples', why: 'Partial collapse is still collapse; the distribution is badly wrong.' },
      { text: 'No — the samples look sharp', why: 'Sample quality and diversity are separate properties.' },
    ],
    answer: 0,
    explanation: 'Yes: 97% of samples on one of eight modes. The samples may look perfect individually; diversity is what failed.',
    reflection: 'How would you detect mode collapse in a generator of product descriptions or images?',
  },
  {
    id: 'l54-diffusion',
    title: '54.3 · Diffusion models: the forward process',
    sections: ['Destroy structure slowly', 'A noise schedule', 'Jumping to any step', 'Why noise helps', 'What must be learned'],
    skill: 'Describe the forward diffusion process and compute its closed-form marginals.',
    prerequisite: 'Lessons 54.1–54.2; Gaussians (Lab 04); VAEs (Lab 53).',
    paragraphs: [
      'A **diffusion model** defines a fixed forward process that adds a little Gaussian noise at each of T steps: x_t = √(1 − β_t)·x_{t−1} + √β_t·ε, with a small, increasing variance schedule β_t. After enough steps nothing but standard Gaussian noise remains.',
      'Composing Gaussian steps gives a closed form for any step: with α_t = 1 − β_t and ᾱ_t = α₁α₂…α_t, **x_t = √ᾱ_t·x₀ + √(1 − ᾱ_t)·ε**. Training can jump straight to a random t without simulating the chain.',
      'In the playground (T = 40), the signal factor √ᾱ_t falls from 1 to about 0.06: the ring of clusters blurs, merges and dissolves into a round Gaussian cloud.',
      'Why this helps: denoising a tiny amount of noise is an easy, local regression problem, and there is always a training signal everywhere in space, because noisy versions of the data cover all of it. No adversary, no collapse.',
      'The generative model is the reverse process: start from noise and remove it step by step. Each reverse step is Gaussian with a mean that depends on the unknown noise — which is exactly what a network will learn to predict.',
    ],
    formula: 'q(x_t | x₀) = N(√ᾱ_t x₀, (1 − ᾱ_t) I)     x_t = √ᾱ_t x₀ + √(1 − ᾱ_t) ε',
    derivation: {
      title: 'Two noising steps in one',
      intro: 'Start from x₀; apply x₁ = √α₁ x₀ + √(1 − α₁) ε₁, then x₂ = √α₂ x₁ + √(1 − α₂) ε₂ with independent standard noises.',
      steps: [
        { prompt: 'Coefficient of x₀ in x₂ (write with a1, a2).', answer: 'sqrt(a1*a2)', show: '`√(α₁α₂) = √ᾱ₂`', vars: { a1: [0.5, 1], a2: [0.5, 1] } },
        { prompt: 'Total noise variance in x₂: α₂(1 − α₁) + (1 − α₂). Simplify.', answer: '1 - a1*a2', show: '`1 − α₁α₂ = 1 − ᾱ₂`', vars: { a1: [0.5, 1], a2: [0.5, 1] } },
        { prompt: 'With ᾱ_t = 0.36, what is the signal factor √ᾱ_t?', number: 0.6, show: '`0.6`' },
      ],
      result: 'Gaussian noise composes into Gaussian noise, so any step of the forward process is one line of code.',
    },
    experiment: 'In the diffusion view, read the signal factor under each forward frame. At which step does the ring stop being visible?',
    question: 'ᾱ_t = 0.04. What fraction of x_t’s variance (for unit-variance data) comes from noise?',
    answer: 0.96, tolerance: 1e-9,
    explanation: 'Signal variance ᾱ_t = 0.04, noise variance 1 − ᾱ_t = 0.96.',
    reflection: 'Why is it easier to learn “remove a little noise” than “produce data from scratch”?',
  },
  {
    id: 'l54-reverse',
    title: '54.4 · Learning to denoise and sampling',
    sections: ['Predict the noise', 'A simple regression loss', 'Ancestral sampling', 'Coverage and speed', 'Score matching'],
    skill: 'Train a noise-prediction network and generate samples by reversing the diffusion.',
    prerequisite: 'Lesson 54.3; regression losses (Lab 01).',
    paragraphs: [
      'Train a network ε_θ(x_t, t) to predict the noise ε that produced x_t from x₀: sample x₀, t and ε, form x_t in closed form, and minimize ‖ε − ε_θ(x_t, t)‖². That is the whole DDPM training loss — mean squared error. The time t enters as extra input features (here sines and cosines of t).',
      'To sample, start from x_T ~ N(0, I) and step backwards: x_{t−1} = (x_t − β_t/√(1 − ᾱ_t)·ε_θ(x_t, t)) / √α_t + √β_t·z, with fresh noise z except at the last step.',
      'In the playground the learned reverse process turns a round Gaussian cloud into the ring, covering all eight clusters: the regression objective rewards getting every region right, so there is no incentive to drop modes.',
      'The cost is speed: 40 network evaluations per sample here, often hundreds or thousands in image models. Faster samplers (DDIM, distillation, consistency models) cut this to a few steps; latent diffusion runs the process in a VAE’s compressed space (Lab 53).',
      'Predicting the noise is equivalent to estimating the **score** ∇ₓ log p_t(x) — the direction toward higher data density at noise level t. That view (score-based models, stochastic differential equations) unifies diffusion with Langevin sampling.',
    ],
    formula: 'loss = E_{x₀,t,ε} ‖ε − ε_θ(√ᾱ_t x₀ + √(1−ᾱ_t) ε, t)‖²     score ≈ −ε_θ(x_t, t)/√(1 − ᾱ_t)',
    derivation: {
      title: 'Recover x₀ from a noise prediction',
      steps: [
        { prompt: 'From x_t = √ᾱ x₀ + √(1 − ᾱ) ε, solve for x₀ (use xt, e, ab for ᾱ).', answer: '(xt - sqrt(1-ab)*e)/sqrt(ab)', show: '`(x_t − √(1 − ᾱ)·ε)/√ᾱ`', vars: { xt: [-3, 3], e: [-2, 2], ab: [0.05, 0.95] } },
        { prompt: 'With x_t = 1.0, predicted ε = 0.5 and ᾱ = 0.64, the estimated x₀?', number: (1 - 0.6 * 0.5) / 0.8, tolerance: 1e-6, show: '`(1 − 0.3)/0.8 = 0.875`' },
      ],
      result: 'A good noise predictor is a denoiser: each reverse step nudges the sample toward its best guess of clean data.',
    },
    experiment: 'In the diffusion view, compare the reverse frames with the forward frames in reverse order. When do the eight clusters appear?',
    question: 'A diffusion sampler uses 40 steps; each step is one network call taking 2 ms. How long does one sample take in milliseconds?',
    answer: 80,
    explanation: '40 × 2 = 80 ms — a GAN would need one call (2 ms). That is the speed–stability trade-off.',
    reflection: 'For what applications is diffusion’s slower sampling acceptable, and for which is it not?',
  },
  {
    id: 'l54-compare',
    title: '54.5 · Choosing and evaluating generative models',
    sections: ['Four families', 'Evaluating samples', 'Memorization and privacy', 'Conditioning', 'Demonstrate understanding'],
    skill: 'Compare generative model families and evaluate their samples responsibly.',
    prerequisite: 'Lessons 54.1–54.4; Lab 53.',
    paragraphs: [
      'Four families: **VAEs** (fast sampling, a useful encoder, blurrier samples), **GANs** (fast, sharp samples, unstable training, mode collapse), **diffusion models** (stable training, excellent coverage and quality, slower sampling), and **autoregressive models** (exact likelihoods, sequential generation — language models, Lab 55). Normalizing flows add exact likelihoods with invertible networks.',
      'Evaluate both quality and diversity. Sample-based metrics compare generated and real distributions in a feature space (FID; precision and recall for generative models); likelihood-based models also report bits per dimension. Always look at many samples, including the worst.',
      'Generators can **memorize** training examples and reproduce them — a privacy and copyright risk. Search generated samples for near-duplicates of the training set and prefer data you have rights to use (Lab 31).',
      'Most practical generators are **conditional**: generate given a class, a text prompt or another image. Classifier-free guidance steers diffusion models toward the condition by combining conditional and unconditional noise predictions.',
      'You have completed this lab when you can: derive the GAN game’s optimal discriminator; diagnose saturation and mode collapse; derive the diffusion forward process and its closed form; explain the noise-prediction loss and ancestral sampling; and choose and evaluate a generative model family for a task. The Python challenge implements the diffusion equations and the GAN losses with checks against theory.',
    ],
    formula: 'VAE: bound on likelihood · GAN: adversarial · diffusion: denoising regression · autoregressive: exact likelihood',
    derivation: {
      title: 'Bits per dimension',
      steps: [
        { prompt: 'A model assigns an image of 784 pixels a log-likelihood of −543.4 nats. Bits per dimension = −log p / (784 · ln 2). (Three decimals.)', number: 543.4 / (784 * Math.LN2), tolerance: 1e-3, show: '`≈ 1.000`' },
      ],
      result: 'Bits per dimension compare likelihood models across image sizes — lower is better.',
    },
    experiment: 'Compare the GAN (balanced) and diffusion views on the per-mode bars and the share of samples landing on a mode. Which is more diverse, and which more precise?',
    question: 'A generator’s samples score perfectly on a sharpness metric, but 60% of them are near-copies of training images. Is it a good model to deploy?',
    choices: [
      { text: 'Yes — the quality metric is perfect', why: 'A quality metric alone missed the memorization.' },
      { text: 'No — it is memorizing its training data', why: 'Near-copies create privacy and copyright risks and show it has not learned the distribution.' },
      { text: 'Yes, if the training images are public', why: 'Public does not mean licensed for copying, and memorization is still a modelling failure.' },
    ],
    answer: 1,
    explanation: 'No: it is memorizing — a quality metric alone missed it, and it creates privacy and copyright risks.',
    reflection: 'Which generative family would you choose for a project you can imagine, and how would you evaluate it before release?',
  },
]

export const sources = [
  { title: 'Goodfellow et al. (2014) · Generative adversarial nets', url: 'https://arxiv.org/abs/1406.2661' },
  { title: 'Ho, Jain & Abbeel (2020) · Denoising diffusion probabilistic models', url: 'https://arxiv.org/abs/2006.11239' },
  { title: 'Arjovsky, Chintala & Bottou (2017) · Wasserstein GAN', url: 'https://arxiv.org/abs/1701.07875' },
  { title: 'Song et al. (2021) · Score-based generative modeling through stochastic differential equations', url: 'https://arxiv.org/abs/2011.13456' },
]
