export const lessons = [
  {
    id: 'l18-projection',
    title: '18.1 · Projection onto a direction',
    sections: ['Too many numbers per row', 'Unit vectors and dot products', 'Projecting a point', 'The residual', 'Put it into practice'],
    skill: 'Project points onto a unit direction and compute the residual that projection discards.',
    prerequisite: 'Labs 01–17; dot products and matrices (Lab 03), variance (Lab 04).',
    paragraphs: [
      'A build record might have 40 correlated measurements; an image has thousands of pixels. Many of those numbers move together. If a few combinations carry most of the variation, we can describe each row with far fewer numbers — for plotting, compression, faster models or noise removal.',
      'A **unit vector** u has length 1: ‖u‖ = √(u·u) = 1. The direction at 45° is u = (1/√2, 1/√2). For any point x, the dot product `u·x` is its coordinate along that direction — how far along u the point lies.',
      'The **projection** of x onto the line through the origin in direction u is `(u·x)·u`: the closest point on that line to x. For x = (3, 4) and u = (1, 0): u·x = 3 and the projection is (3, 0).',
      'The **residual** `x − (u·x)u` is perpendicular to u and is exactly what the projection throws away. By Pythagoras, `‖x‖² = (u·x)² + ‖residual‖²`: squared length splits into a kept part and a lost part. For (3, 4) onto the x-axis: 25 = 9 + 16.',
      'For data, measure everything relative to the mean (next lesson explains why): project x − x̄. Keeping one coordinate per point, `z = u·(x − x̄)`, turns 2 numbers into 1; with d dimensions and k directions it turns d numbers into k.',
    ],
    formula: 'z = u·(x − x̄)     x̂ = x̄ + z u     ‖x − x̄‖² = z² + ‖x − x̂‖²',
    experiment: 'In "Search for the best direction", set θ = 0, then 90. For each, compare "variance kept" and "variance lost". Do they always add to the same total?',
    question: 'Project x = (3, 4) onto the unit direction u = (0.6, 0.8). What is the coordinate u·x?',
    answer: 5,
    explanation: '0.6 × 3 + 0.8 × 4 = 1.8 + 3.2 = 5. The point lies exactly along u, so nothing is lost: the residual is zero.',
    reflection: 'Name a set of measurements in your work that probably move together. What single "direction" might summarize them?',
  },
  {
    id: 'l18-maxvar',
    title: '18.2 · The direction of maximum variance',
    sections: ['A good summary keeps spread', 'Variance of a projection', 'The covariance matrix', 'The best direction is an eigenvector', 'Two optimal views'],
    skill: 'Derive that the first principal component is the top eigenvector of the covariance matrix.',
    prerequisite: 'Lesson 18.1; eigenvectors as curvature directions (Lab 03).',
    paragraphs: [
      'A one-number summary is useful if it keeps rows distinguishable — if the projected values are spread out. So choose the unit direction u that **maximizes the variance** of z = u·(x − x̄).',
      'The variance of the projections is `mean(z²) = uᵀ Σ u`, where Σ is the **covariance matrix**: `Σ = (1/n) Σᵢ (xᵢ − x̄)(xᵢ − x̄)ᵀ`. Its diagonal holds each feature\'s variance; the off-diagonals hold covariances, which are large when features move together.',
      'Maximizing uᵀΣu subject to ‖u‖ = 1 gives, with a Lagrange multiplier, `Σu = λu`: u must be an **eigenvector** of Σ, and the variance achieved equals its **eigenvalue** λ. The best direction is the eigenvector with the largest eigenvalue — the **first principal component** (PC1).',
      'The playground\'s variance-versus-direction curve peaks exactly at PC1, and the peak height is λ₁. The second component is the best direction perpendicular to the first, with eigenvalue λ₂, and so on. Because Σ is symmetric, its eigenvectors are mutually perpendicular.',
      'Since kept + lost = total variance for every direction (Lesson 18.1), maximizing the kept variance is the same as minimizing the squared distances to the line. PCA is simultaneously the most spread-preserving projection and the best-fitting low-dimensional approximation.',
    ],
    formula: 'Σ = (1/n) Σ (xᵢ − x̄)(xᵢ − x̄)ᵀ     Var(u·x) = uᵀΣu     max ⇒ Σu = λu, variance = λ',
    experiment: 'Change the orientation and elongation. Before looking, predict where the peak of the variance curve will be. Check against the "PC1 direction" metric.',
    question: 'A covariance matrix is diag(9, 4). What is the variance along the first principal component?',
    answer: 9,
    explanation: 'A diagonal covariance has its eigenvectors along the axes; the largest eigenvalue, 9, is the variance along PC1 (the first axis).',
    reflection: 'Explain in your own words why the direction of maximum variance is also the line that fits the points best.',
  },
  {
    id: 'l18-centering',
    title: '18.3 · Centering and scaling',
    sections: ['Variance is measured around the mean', 'What goes wrong without centering', 'Scaling changes the answer', 'Fit on training data', 'Correlation or covariance?'],
    skill: 'Explain why PCA requires centering, when to standardize, and how to avoid leakage.',
    prerequisite: 'Lessons 18.1–18.2; standardization (Labs 02–03).',
    paragraphs: [
      'Variance and covariance are defined around the mean. If you skip centering, the "spread" you maximize is measured around the origin instead, and PC1 is pulled toward the direction of the mean itself. The playground\'s uncentered PC1 points from the origin to the cloud, not along its shape.',
      'For a cloud centered at (3, 2), almost all "variance around the origin" is just the offset. The components describe where the data are, not how they vary, and the reconstruction error rises. Subtracting the mean first removes this.',
      'PCA maximizes variance, so features with large numeric ranges dominate. Size in bytes would swamp duration in seconds. When features have different units, **standardize** them (divide by their standard deviation) — equivalent to PCA on the correlation matrix. When all features share a unit and scale (pixel intensities), plain centering is usually right.',
      'The mean, the scale and the components are all learned from data. Fit them on training data only and apply the same transform to validation and test data (Labs 02 and 06). A PCA fitted on all data before splitting leaks the test set\'s structure into the features.',
      'A quick check: after centering, every column of the transformed training data has mean zero, and the variances of the components equal the eigenvalues in decreasing order.',
    ],
    formula: 'PCA on centered data: X − x̄     on standardized data: (X − x̄)/s  (correlation PCA)',
    experiment: 'In "Principal axes in 2D", toggle "Center the data first" off and on. Record PC1\'s explained share and the reconstruction error each time.',
    question: 'Three training values of a feature are 2, 4 and 9. What value is subtracted from each when centering?',
    answer: 5,
    explanation: 'The training mean, (2 + 4 + 9)/3 = 5. The same 5 is subtracted from validation and test values too.',
    reflection: 'Which features in your data have very different units? Would you use covariance PCA or correlation PCA, and why?',
  },
  {
    id: 'l18-svd',
    title: '18.4 · Explained variance, SVD and choosing k',
    sections: ['Variance adds up', 'The scree plot', 'SVD computes PCA', 'Reconstruction error', 'Choosing k'],
    skill: 'Compute explained variance ratios, relate PCA to the SVD, and choose the number of components.',
    prerequisite: 'Lessons 18.1–18.3.',
    paragraphs: [
      'The eigenvalues of Σ sum to the total variance (the trace of Σ). The share explained by component j is `λⱼ / Σλ`. With eigenvalues 6, 3 and 1, PC1 explains 60% and the first two explain 90%.',
      'Plotting these shares (or their running total) against the component number is a **scree plot**. The digit images show a typical shape: a few components explain a lot, then a long tail of small ones that mostly represent noise.',
      'In practice PCA is computed with the **singular value decomposition** of the centered data matrix: `X_c = U S Vᵀ`. The rows of Vᵀ are the principal directions, and the eigenvalues are `sᵢ²/n`. The SVD avoids forming XᵀX, which squares the condition number (Lab 03), and is what `np.linalg.svd` and scikit-learn use.',
      'Keeping k components and reconstructing gives a mean squared error equal to the sum of the dropped eigenvalues. In the 2D view with k = 1 the error equals λ₂ exactly. So explained variance directly tells you how much information the compression loses.',
      'Choose k by purpose: 2–3 for visualization; enough to reach a variance target (say 90–95%) for compression; or by cross-validating a downstream model that uses the components as features. Never choose k on the test set.',
    ],
    formula: 'share_j = λⱼ / Σₖ λₖ     X_c = U S Vᵀ, λᵢ = sᵢ²/n     error(k) = Σ_{j>k} λⱼ',
    experiment: 'In the digit view, find the smallest k that explains 80% of the variance. Look at the reconstructions at that k. Are the digits recognizable?',
    question: 'Eigenvalues are 6, 3 and 1. What fraction of the variance do the first two components explain? (Decimal.)',
    answer: 0.9,
    explanation: '(6 + 3)/(6 + 3 + 1) = 9/10 = 0.9.',
    reflection: 'How would you choose k if the components fed a classifier? What would you measure?',
  },
  {
    id: 'l18-use',
    title: '18.5 · Using and misusing PCA',
    sections: ['Compression and denoising', 'Features for other models', 'Interpreting components', 'Limitations', 'Demonstrate understanding'],
    skill: 'Apply PCA for compression, visualization and features, and state its limitations.',
    prerequisite: 'Lessons 18.1–18.4; curse of dimensionality (Lab 10).',
    paragraphs: [
      'Reconstructing from the top components keeps the dominant structure and drops the small, noisy directions, so PCA can **denoise**: compare the reconstructed digits with the noisy originals at moderate k.',
      'Using a handful of components as features can help distance-based methods (Lab 10) and speed up training. But the directions of greatest variance are not necessarily the most predictive: a tiny-variance direction can carry the signal that separates classes. Validate any PCA-based pipeline on the downstream task.',
      'Components are weighted mixtures of all original features, with arbitrary sign. The eigen-digit images show them as patterns of positive and negative pixel weights. Interpretation is possible sometimes ("overall size", "left versus right stroke"), but it is a description of the data\'s variation, not a discovered cause.',
      'PCA is linear: curved structure (a spiral, a manifold) cannot be captured by flat projections. It is sensitive to outliers, which contribute large squared distances. It depends on scaling choices. Non-linear alternatives (kernel PCA, t-SNE and UMAP for visualization, autoencoders) exist, each with its own caveats.',
      'You have completed this lab when you can: project points onto directions; derive PC1 as the top eigenvector of the covariance matrix; explain why centering is required; compute explained variance and reconstruction error; relate PCA to the SVD; and use it — or decline to — for a given purpose. The Python challenge implements PCA with the SVD.',
    ],
    formula: 'x ≈ x̄ + Σ_{j≤k} zⱼ vⱼ     (mean plus a weighted sum of component patterns)',
    experiment: 'Compare reconstructions at k = 3, 10 and 30. At which k do the reconstructions look cleaner than the noisy originals? Past which k do they reproduce the noise?',
    question: 'Each image has 64 pixels and you keep 8 components. By what factor did the numbers per image shrink?',
    answer: 8,
    explanation: '64/8 = 8 times fewer numbers per image (plus the shared mean and 8 component vectors, stored once).',
    reflection: 'Name one task where you would use PCA and one where you would avoid it. Why?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 12.2: principal components analysis', url: 'https://www.statlearning.com/' },
  { title: 'Mathematics for Machine Learning · Chapter 10: dimensionality reduction with PCA', url: 'https://mml-book.github.io/' },
  { title: 'Shlens · A tutorial on principal component analysis', url: 'https://arxiv.org/abs/1404.1100' },
  { title: 'scikit-learn · PCA', url: 'https://scikit-learn.org/stable/modules/decomposition.html#pca' },
]
