import { notebooks } from './notebooks.js'

// Lessons 03.1–03.3 work on one four-row table of builds (also in the playground and the
// notebooks). The loss bowl appears only in 03.4; eigenvalues wait for the optional 03.8.
export const lessons = [
  {
    id: 'l03-design',
    title: '03.1 · Rows are observations, columns are features',
    sections: ['One input is not enough', 'A table of builds', 'Read one row with the weights', 'The column of ones', 'Read every shape', 'Put it into practice'],
    skill: 'Organize data as a design matrix, compute one row’s prediction by hand, and state the shape of every array in a multi-feature model.',
    prerequisite: 'Lab 01 (weights, dot products, one-feature regression) and Lab 02 (arrays and indexing).',
    paragraphs: [
      'Here are four builds: **A** is 1 GB with 100 files and took 6.2 minutes; **B** is 2 GB with 400 files, 12.1 minutes; **C** is 3 GB with 200 files, 12.8 minutes; **D** is 4 GB with 300 files, 17.1 minutes. Compare B and C: C is a whole GB larger but took only 0.7 minutes longer, because B had twice as many files. A model that sees only size cannot explain that — it has to treat the difference as noise. Give each prediction both inputs.',
      'Write the builds as a table: one **row** per build, one **column** per measurement. With size in GB and files in hundreds, the rows are `[1, 1]`, `[2, 4]`, `[3, 2]` and `[4, 3]`. This table of inputs is the **design matrix** X, shape `(4, 2)`: 4 observations, 2 features. `X[2, 0]` is build C’s size, 3 — row index first, column index second, both counting from 0. The times form a separate vector `y = [6.2, 12.1, 12.8, 17.1]`, shape `(4,)`. The target never goes inside X: it is what we predict.',
      'A model with two features is `ŷ = b + w₁·size + w₂·files`. Guess b = 1, w₁ = 2 minutes per GB and w₂ = 2 minutes per hundred files. For build C: **1 + 2×3 + 2×2 = 11 minutes**. Its measured time is 12.8, so the error ŷ − y is −1.8. Notice that each weight belongs to a **column**: w₁ multiplies the size of every build. Raise w₂ by 1 and every prediction rises by that build’s file count — B by 4, A by only 1.',
      'The intercept b is added to every row, so write it as a weight on a column that is always 1. X becomes `[[1, 1, 1], [1, 2, 4], [1, 3, 2], [1, 4, 3]]`, shape `(4, 3)`, and `w = [b, w₁, w₂] = [1, 2, 2]`. Row C’s prediction is `1×1 + 3×2 + 2×2 = 11` — the same number, now one dot product of a row with w. `np.column_stack([np.ones(n), X])` builds this matrix. From here on one formula covers every weight, the intercept included.',
      'Before computing anything, write the shape next to every array. In general: X `(n, p+1)`, w `(p+1,)`, predictions `(n,)`, errors `(n,)`. For our table: `(4, 3)`, `(3,)`, `(4,)`, `(4,)`. If a result has a shape you did not predict, stop — the computation is wrong even if it runs. Most multi-feature bugs are a transposed matrix, a missing ones column, or a `(n, 1)` column meeting a `(n,)` vector (Lab 01, lesson 00a).',
      'Procedure: decide what one row represents (one build, one customer, one day); list the features available **before** the target is known; build X and y; print `X.shape`, `y.shape` and the first rows; compute one row’s prediction by hand and compare it with `X[i] @ w`.',
    ],
    blocks: [
      { p: 0 },
      { p: 1 },
      { figure: 'DesignTable', caption: 'Click any number to read its index. Row index first, column index second, both from 0.' },
      { cell: 0 },
      { p: 2 },
      { figure: 'RowContributions', caption: 'One prediction is a sum of contributions: the intercept, plus each weight times its feature. Change the build or a weight and watch which bar moves.' },
      { predict: { prompt: 'Same weights (b = 1, w₁ = 2, w₂ = 2). Predict build **B**: 2 GB and 400 files (4 hundreds).', answer: 13, explain: '1 + 2×2 + 2×4 = 13 minutes. Its measured time is 12.1, so the error is +0.9: too high this time.', misconceptions: [{ answer: 12.1, feedback: 'That is B’s measured time, y. Predict with the weights instead.' }, { answer: 805, feedback: 'The files column is in hundreds: 400 files is 4.' }] } },
      { cell: 1 },
      { cell: 2 },
      { p: 3 },
      { predict: { prompt: 'With the ones column, build A’s row is `[1, 1, 1]` and w = `[1, 2, 2]`. What is the dot product?', answer: 5, explain: '1×1 + 1×2 + 1×2 = 5: the intercept is now just the weight on the column of ones.' } },
      { p: 4 },
      { cell: 3 },
      { p: 5 },
      { math: true },
    ],
    formulaTex: '$$\\hat y_i = 1\\cdot b + x_{i1}\\,w_1 + x_{i2}\\,w_2 = x_i \\cdot w$$ $$X:(n,\\,p+1),\\;\\; w:(p+1,),\\;\\; \\hat y:(n,)$$',
    formula: 'ŷᵢ = 1·b + xᵢ₁·w₁ + xᵢ₂·w₂ = row i · w     X (n, p+1), first column = 1     w (p+1,)',
    mathCode: {
      rows: [
        ['$X$', 'X = np.column_stack([np.ones(4), size, files])', 'The design matrix: one row per build; columns are ones, size, files.'],
        ['$x_i$ (row $i$)', 'X[i]', 'Every feature of observation i.'],
        ['$x_{\\cdot j}$ (column $j$)', 'X[:, j]', 'Feature j across all observations.'],
        ['$w = (b, w_1, w_2)$', 'w = np.array([1., 2., 2.])', 'One weight per column; the first is the intercept.'],
        ['$\\hat y_i = x_i \\cdot w$', 'X[i] @ w', 'One prediction: a row dotted with w.'],
        ['$y$', 'y = np.array([6.2, 12.1, 12.8, 17.1])', 'The targets, kept out of X.'],
      ],
    },
    notebook: notebooks['l03-design'],
    experiment: 'Click build C in the table and check its multiply-and-add against the lesson. Then predict: if you raise w₂ by 1, which build’s prediction rises most, and by how much? Move the slider and check. Finally switch on the column of ones and confirm that no prediction changes.',
    question: 'Build D is 4 GB with 300 files, so its row is `[1, 4, 3]`. With w = [b, w₁, w₂] = [1, 2, 2], what is its prediction in minutes?',
    answer: 15,
    misconceptions: [
      { answer: 14, feedback: 'You left out the intercept. The first column is always 1, so b = 1 is added to every prediction.' },
      { answer: 17.1, feedback: 'That is D’s measured time, the target y. The question asks for the model’s prediction.' },
      { answer: 607, feedback: 'You used 300 files instead of 3 hundreds. The column is in hundreds of files, and the weight is per hundred.' },
    ],
    explanation: 'Row D is `[1, 4, 3]`. Dot it with w: 1×1 + 4×2 + 3×2 = 15 minutes. The measured time is 17.1, so the error ŷ − y is −2.1: this guess predicts too little.',
    reflection: 'For your own project, what is one row? List three features that exist before the target is measured.',
  },
  {
    id: 'l03-matmul',
    title: '03.2 · Matrix multiplication is many dot products',
    sections: ['One row, one dot product', 'All rows at once', 'The shape rule', '`*` is not `@`', 'Transpose: columns become rows', 'Why vectorize'],
    skill: 'Compute a matrix–vector product by hand, predict its shape, and read `Xᵀv` as one dot product per feature column.',
    prerequisite: 'Lesson 03.1; the dot product from Lab 01.',
    paragraphs: [
      'You computed build C’s prediction as one dot product: row `[1, 3, 2]` with `w = [1, 2, 2]` gives 11. Now do every row with the **same** w. A: 1 + 2 + 2 = **5**. B: 1 + 4 + 8 = **13**. C: **11**. D: 1 + 8 + 6 = **15**. Written in row order, the answers form the vector `[5, 13, 11, 15]`. That vector is `X @ w`.',
      'In general `(X @ w)[i]` is the dot product of row i of X with w: `Σⱼ X[i, j]·w[j]`. **Matrix multiplication** of A `(a, b)` by B `(b, c)` gives C `(a, c)`, where `C[i, k]` is the dot product of row i of A with column k of B. A vector w acts as a single column, so `(n, p) @ (p,)` gives `(n,)`. Nothing new happens inside — it is the multiply-and-add you already know, repeated.',
      'The **shape rule**: the inner dimensions must match, and they disappear. `(4, 3) @ (3,)` → `(4,)`. `(3, 4) @ (4,)` → `(3,)`. `(4, 3) @ (4,)` is an error: each row has 3 entries but the vector has 4, so there is no way to pair them. To check, write the two shapes side by side and cross out the matching inner pair; what is left is the result.',
      '`X * w` multiplies matching entries **without adding**. With X `(4, 3)` and w `(3,)`, broadcasting multiplies each row entry by entry, giving shape `(4, 3)`: row C becomes `[1, 6, 4]`. Summing each row, `(X * w).sum(axis=1)`, recovers `X @ w`. If you meant `@` and typed `*`, NumPy often raises no error — you just get the wrong shape.',
      'The **transpose** Xᵀ swaps rows and columns: `(4, 3)` becomes `(3, 4)`, and `Xᵀ[j, i] = X[i, j]`. Row j of Xᵀ is column j of X: one feature across all builds. So `Xᵀ @ v`, for a vector v with one entry per build, takes each feature column’s dot product with v. With `v = [1, 1, 1, 1]` it gives `[4, 10, 10]`: the column sums. In the next lesson v will be the vector of errors, and `Xᵀ @ e` will be the gradient.',
      'A Python loop over rows computes the same values, but `X @ w` runs in optimized compiled code, often hundreds of times faster, and states the intent in one expression. Write the loop once to convince yourself, check that it matches, then use `@`.',
    ],
    blocks: [
      { p: 0 },
      { figure: 'MatVecStepper', caption: 'Press **Next row** and say each product before it appears. Then switch to `X * w` to see what happens without the sums.' },
      { cell: 1 },
      { p: 1 },
      { predict: { prompt: 'With w = `[0, 1, 1]` (no intercept, one minute per GB and per hundred files), what is `(X @ w)[1]`, build B’s entry?', answer: 6, explain: 'Row B is `[1, 2, 4]`: 1×0 + 2×1 + 4×1 = 6.' } },
      { p: 2 },
      { figure: 'ShapeRule', caption: 'Pick the shapes. The inner pair must match, and it disappears.' },
      { cell: 2 },
      { p: 3 },
      { cell: 3 },
      { p: 4 },
      { predict: { prompt: 'What is the **third** entry of `Xᵀ @ [1, 1, 1, 1]`?', answer: 10, explain: 'Row 2 of Xᵀ is the files column `[1, 4, 2, 3]`; its sum is 10. The whole result is `[4, 10, 10]`: the column sums.', misconceptions: [{ answer: 4, feedback: 'That is the first entry, the ones column. Count from 0: entry 2 is the files column.' }] } },
      { figure: 'TransposeDot', caption: 'Each row of Xᵀ is one column of X. Edit v and choose a column to see its dot product.' },
      { cell: 4 },
      { p: 5 },
      { math: true },
      { ladder: 'prediction' },
    ],
    formulaTex: '$$(Xw)_i = \\sum_j X_{ij}\\,w_j$$ $$(AB)_{ik} = \\sum_j A_{ij}B_{jk}$$ $$(a\\times b)\\,(b\\times c) \\to (a\\times c)$$ $$(X^\\top v)_j = \\sum_i X_{ij}\\,v_i$$',
    formula: '(X @ w)[i] = Σⱼ X[i, j]·w[j]     (a, b) @ (b, c) → (a, c)     (Xᵀ v)[j] = Σᵢ X[i, j]·v[i]',
    mathCode: {
      rows: [
        ['$(Xw)_i$', 'X[i] @ w', 'Row i dotted with w: one prediction.'],
        ['$Xw$', 'X @ w', 'Every row at once: shape (n,).'],
        ['$\\sum_j X_{ij} w_j$', '(X * w).sum(axis=1)', 'The same numbers: elementwise product, then row sums.'],
        ['$X^\\top$', 'X.T', 'Rows and columns swapped: shape (p+1, n).'],
        ['$X^\\top v$', 'X.T @ v', 'One dot product per feature column.'],
      ],
    },
    notebook: notebooks['l03-matmul'],
    experiment: 'Press **Next row** to multiply one row at a time; say each product aloud before it appears. After all four rows, switch to `*` and explain the `(4, 3)` result. Then switch to the Xᵀ view and predict `Xᵀ @ [1, 1, 1, 1]` before revealing it.',
    question: 'With X = `[[1, 1, 1], [1, 2, 4], [1, 3, 2], [1, 4, 3]]` and v = `[1, 0, 0, 1]`, what is the **second** entry of `Xᵀ @ v`?',
    answer: 5,
    misconceptions: [
      { answer: 2, feedback: 'That is the first entry: the ones column dotted with v. The second entry uses the second column, the sizes [1, 2, 3, 4].' },
      { answer: 4, feedback: 'That is the third entry, from the files column [1, 4, 2, 3]. Count the columns from the ones column.' },
    ],
    explanation: 'Entry j of `Xᵀ @ v` is column j of X dotted with v. The second column is the sizes `[1, 2, 3, 4]`: 1×1 + 2×0 + 3×0 + 4×1 = 5. The full result is `[2, 5, 4]`, one number per column.',
    reflection: 'Explain in words why the inner dimensions must match. What would a mismatch mean about your data?',
  },
  {
    id: 'l03-gradient',
    title: '03.3 · The gradient in matrix form',
    sections: ['Start from the errors', 'One weight, one column', 'Every weight at once: Xᵀe', 'Check it with a nudge', 'Take a step', 'The general formula'],
    skill: 'Compute the least-squares gradient `(2/n) Xᵀ(Xw − y)` by hand for a small table, check it numerically, and take a gradient-descent step on every weight at once.',
    prerequisite: 'Lessons 03.1–03.2; the one-feature gradient and chain rule from Lab 01.',
    paragraphs: [
      'With `w = [1, 2, 2]` the predictions are `[5, 13, 11, 15]` and the measured times are `[6.2, 12.1, 12.8, 17.1]`. The errors `e = ŷ − y` are **[−1.2, 0.9, −1.8, −2.1]** and the MSE is (1.44 + 0.81 + 3.24 + 4.41)/4 = **2.475**. Three errors are negative: the model mostly predicts too little, so some weights should grow. Which ones, and by how much? That is what the gradient says.',
      'In Lab 01, with one feature, `∂J/∂w = 2·mean(e·x)`. Nothing in that derivation depended on having one feature: when w_j changes by a small amount, prediction i changes by `x_ij` times that amount, so **∂J/∂w_j = (2/n)·Σᵢ eᵢ·x_ij**. For the size weight w₁: e × size = [−1.2, 1.8, −5.4, −8.4], which sums to −13.2; times 2/4 gives **−6.6**. Negative means that increasing w₁ lowers the loss.',
      'Repeat for every column: each gradient entry is one feature column dotted with e, times 2/n. That is exactly `Xᵀ @ e` from the last lesson: **∇J = (2/n) Xᵀ e**. For our table, `Xᵀe = [Σe, Σe·size, Σe·files] = [−4.2, −13.2, −7.5]`, so ∇J = **[−2.1, −6.6, −3.75]**, shape `(3,)`: one entry per weight. The intercept’s entry is `2·mean(e)`, as in Lab 01, because its column is all ones.',
      'Check any entry by nudging its weight. Raise w₁ from 2 to 2.01: every prediction rises by 0.01 × that build’s size, and the MSE falls from 2.475 to 2.40975, a change of **−0.06525**. The gradient predicted −6.6 × 0.01 = **−0.066**. Close — and closer still with a smaller nudge or the centered difference `[J(w + ε) − J(w − ε)]/(2ε)` from Lab 01. A clear mismatch almost always means a missing transpose, a wrong sign or a lost factor of 2.',
      'Update every weight at once, using the gradient computed at the old w: `w ← w − α∇J`. With α = 0.02: `[1, 2, 2] − 0.02 × [−2.1, −6.6, −3.75] = [1.042, 2.132, 2.075]`, and the MSE drops from 2.475 to about **1.59**. Repeat and it keeps falling toward the least-squares fit, about `[2.16, 2.93, 1.03]` with MSE 0.017. But α = 0.07 makes the MSE explode within a few dozen steps: the step overshoots. Lesson 03.7 shows where that limit comes from.',
      'Shapes: e is `(n,)`, Xᵀ is `(p+1, n)`, their product `(p+1,)`. If you ever get a gradient of shape `(n,)`, you multiplied by X instead of Xᵀ. Nothing in the algorithm depends on p: the same five lines fit two features or two thousand.',
    ],
    blocks: [
      { p: 0 },
      { figure: 'ErrorBars', caption: 'Move the weights and watch the errors and the MSE. Can you get the MSE below 1 by hand?' },
      { p: 1 },
      { predict: { prompt: 'Do the same for the files weight w₂. The files column is `[1, 4, 2, 3]` and e = `[−1.2, 0.9, −1.8, −2.1]`. What is ∂J/∂w₂?', answer: -3.75, tolerance: 0.005, explain: 'e × files = [−1.2, 3.6, −3.6, −6.3], which sums to −7.5; times 2/4 gives −3.75.', misconceptions: [{ answer: -7.5, feedback: 'That is the sum Σ eᵢ·filesᵢ. Multiply by 2/n = 2/4.' }] } },
      { figure: 'GradientColumns', caption: 'Pick a weight: its gradient entry is its column dotted with the errors, times 2/n.' },
      { p: 2 },
      { cell: 2 },
      { p: 3 },
      { figure: 'NudgeCheck', caption: 'Shrink ε and compare the one-sided and centered differences with the gradient’s prediction.' },
      { cell: 3 },
      { p: 4 },
      { figure: 'DescentSteps', caption: 'Take steps at α = 0.02, then reset and try 0.05 and 0.07. The stable limit for this table is about 0.066.' },
      { cell: 4 },
      { p: 5 },
      { math: true },
      { ladder: 'gradient' },
    ],
    formulaTex: '$$\\frac{\\partial J}{\\partial w_j} = \\frac{2}{n}\\sum_i e_i\\,x_{ij}$$ $$\\nabla J(w) = \\frac{2}{n}\\,X^\\top (Xw - y)$$ $$w \\leftarrow w - \\alpha\\,\\nabla J(w)$$',
    formula: '∂J/∂w_j = (2/n) Σᵢ eᵢ·xᵢⱼ     ∇J(w) = (2/n) Xᵀ (Xw − y)     w ← w − α ∇J(w)',
    mathCode: {
      rows: [
        ['$e = Xw - y$', 'e = X @ w - y', 'Errors, shape (n,).'],
        ['$\\frac{2}{n}\\sum_i e_i x_{ij}$', '2 * np.mean(e * X[:, j])', 'One gradient entry: column j dotted with e, times 2/n.'],
        ['$\\nabla J = \\frac{2}{n} X^\\top e$', 'grad = 2 / n * X.T @ e', 'Every entry at once: shape (p+1,).'],
        ['$\\frac{J(w + \\varepsilon u_j) - J(w - \\varepsilon u_j)}{2\\varepsilon}$', '(mse(w + eps * u) - mse(w - eps * u)) / (2 * eps)', 'Numerical check of entry j; u is 1 in position j and 0 elsewhere.'],
        ['$w \\leftarrow w - \\alpha \\nabla J$', 'w = w - alpha * grad', 'One simultaneous update of every weight.'],
      ],
    },
    notebook: notebooks['l03-gradient'],
    experiment: 'The playground builds `Xᵀe` column by column. Before pressing **Nudge w₁ by 0.01**, use the gradient to predict the change in MSE. Then take five steps at α = 0.02 and watch every weight move at once. Finally reset and try α = 0.07: what happens to the loss, and why?',
    question: 'X = `[[1, 2], [1, 4]]`, y = `[3, 5]`, w = `[0, 1]`. Compute the **second** entry of ∇J = (2/n) Xᵀ(Xw − y).',
    answer: -6,
    misconceptions: [
      { answer: -2, feedback: 'That is the first entry, from the ones column [1, 1]. The second entry uses the column [2, 4].' },
      { answer: -1, feedback: 'That is an error, not a gradient entry. Dot the column [2, 4] with the error vector e = [−1, −1], then multiply by 2/n.' },
    ],
    explanation: 'Xw = [2, 4], so e = Xw − y = [−1, −1]. The second column is [2, 4]: its dot product with e is −2 − 4 = −6. With n = 2 the factor 2/n is 1, so the entry is −6. The full gradient is [−2, −6]: both negative, so increasing either weight lowers the loss.',
    reflection: 'Why does the intercept’s gradient entry reduce to twice the mean error? Explain using the column of ones.',
  },
  {
    id: 'l03-bowl',
    title: '03.4 · Weight space: the loss is a bowl',
    sections: ['Every model is a point', 'A height above every point', 'Contours', 'Gradient descent as a path', 'What the picture leaves out', 'Put it into practice'],
    skill: 'Read a loss-contour plot in weight space and predict the path gradient descent takes across it.',
    prerequisite: 'Lesson 03.3: the gradient and one gradient-descent step.',
    paragraphs: [
      'Until now each choice of weights gave a table of predictions and one MSE. Turn this around and treat the weights themselves as coordinates. With two features, the pair (w₁, w₂) is a point on a plane, and **every point on the plane is a whole model**. The playground handles the intercept separately: it subtracts each feature’s training mean first, and then the best intercept is simply the mean of y whatever w₁ and w₂ are.',
      'Above every point, imagine the training MSE of that model drawn as a height. For linear regression with squared error, this surface is a **bowl**: the MSE is a quadratic function of the weights, curving upward in every direction as long as no feature is redundant (Lesson 03.6 shows what happens when one is). The bottom of the bowl is the least-squares solution, marked ✕.',
      'A **contour** joins points with the same MSE, like height lines on a hiking map. For this bowl the contours are ellipses around ✕. Where they crowd together the bowl is steep; where they spread apart it is nearly flat.',
      'The gradient at a point is perpendicular to the contour through it and points uphill, toward larger MSE. Gradient descent steps the opposite way, so its path cuts across contours toward the centre. The dashed path in the playground is exactly the update from Lesson 03.3, `w ← w − α∇J`, drawn step by step from (0, 0). When the ellipses are long and thin, “perpendicular to the contour” does not point at ✕, and the path bends or zig-zags.',
      'The picture has limits. With p features the bowl lives in p dimensions and cannot be drawn: this plane shows two weights only. The algebra — `∇J = (2/n) Xᵀe` — does not care how many there are. Use the picture to build intuition, then trust the shapes and the numbers.',
      'Procedure: before running, mark where you expect the minimum and predict whether 40 steps at α = 0.1 reach it. Run, then compare the path with your prediction. Change one setting at a time.',
    ],
    blocks: [
      { p: 0 }, { p: 1 },
      { figure: 'WeightSpace', props: { show: ['rate', 'corr'] }, caption: 'Each point of the plane is a model (w₁, w₂); grey ellipses join models with equal MSE; ✕ is the bottom. The dashed path is 40 gradient steps from (0, 0).' },
      { p: 2 }, { p: 3 },
      { cell: 0 }, { cell: 1 },
      { p: 4 }, { p: 5 },
      { math: true },
    ],
    formula: 'J(w₁, w₂) = training MSE of the model (w₁, w₂)     contour: J(w) = c     −∇J is perpendicular to the contour, pointing downhill',
    notebook: notebooks['l03-bowl'],
    experiment: 'Choose α = 0.1 and 40 steps. Predict where the path ends, then look. Next try α = 0.01 with 400 steps, then α = 0.6. Describe each path in words — direct, slow, or zig-zag — and say which contour spacing explains it.',
    question: 'On a contour plot of the loss bowl, which way does one gradient-descent step go from the current point?',
    choices: [
      { text: 'Perpendicular to the contour through the point, downhill', why: 'The gradient is perpendicular to the contour and points uphill; the step goes the opposite way.' },
      { text: 'Straight toward the minimum ✕', why: 'Only when the contours are circles. On long, thin ellipses the downhill direction points across the valley, not at ✕ — which is why paths bend.' },
      { text: 'Along the contour, keeping the loss constant', why: 'Moving along a contour leaves the loss unchanged, to first order. Gradient descent moves across contours.' },
    ],
    answer: 0,
    explanation: 'Each step moves by −α∇J, and ∇J is perpendicular to the contour. The path heads straight for ✕ only when the contours are circles; Lesson 03.7 shows how feature units stretch them.',
    reflection: 'Describe, in your own words, what one point on the weight-space plot represents. Why can we still reason about the bowl when there are 50 features?',
  },
  {
    id: 'l03-projection',
    title: '03.5 · Least squares is a projection',
    sections: ['Set the gradient to zero', 'The residual is perpendicular', 'The geometry', 'Solve it properly', 'Gradient descent or a solver?'],
    skill: 'Derive the normal equations, interpret the fit as an orthogonal projection, and solve with a numerically stable routine.',
    prerequisite: 'Lessons 03.3–03.4: the gradient in matrix form and the loss bowl.',
    paragraphs: [
      'At the bottom of the bowl the gradient is zero: `(2/n) Xᵀ(Xw − y) = 0`. Rearranged: **XᵀX w = Xᵀy**. These are the **normal equations**: p + 1 linear equations in p + 1 unknowns. When XᵀX is invertible they have exactly one solution, the least-squares weights. For the four builds of Lesson 03.1 that solution is about `[2.16, 2.93, 1.03]`.',
      'Read the zero-gradient condition directly: `Xᵀe = 0` means every column of X has zero dot product with the residual vector e. Two vectors with zero dot product are **orthogonal** (perpendicular). The column of ones gives `Σ eᵢ = 0`: at the optimum, residuals average to zero. Each feature column gives `Σ eᵢ x_ij = 0`: residuals are uncorrelated with every feature. Any remaining pattern must be something the features cannot express. The playground shows these sums shrinking to zero as gradient descent converges.',
      'Think of y as a point in n-dimensional space, one coordinate per observation. Every possible prediction `Xw` lies in the **column space** of X: all combinations of its columns. Least squares picks the point in that space closest to y, and the closest point is the perpendicular foot — an orthogonal **projection**. Adding a feature enlarges the space; the projection can only get closer, so training error never increases when you add a column.',
      'Do not compute `np.linalg.inv(X.T @ X) @ X.T @ y`. Forming XᵀX squares the condition number (Lesson 03.8), amplifying rounding error, and fails outright when XᵀX is singular. Use `np.linalg.lstsq(X, y, rcond=None)`, which solves the problem through a stable factorization of X itself and returns a sensible answer even when the solution is not unique.',
      'Why keep gradient descent at all? A direct solver is exact and fast for thousands of features. Gradient descent scales to problems too large to factor, works when data arrives in batches, and — crucially — generalizes to models with no closed form. Neural networks are trained by exactly the loop you wrote in Lesson 03.3.',
    ],
    blocks: [
      { p: 0 },
      { predict: { prompt: 'A model has an intercept and 2 features. How many equations are in its normal equations XᵀXw = Xᵀy?', answer: 3, explain: 'One per weight: p + 1 = 3. XᵀX is 3 × 3.' } },
      { cell: 0 }, { cell: 1 },
      { p: 1 },
      { figure: 'OrthogonalResiduals', caption: 'Each column’s dot product with the residuals, as gradient descent runs on the four builds.' },
      { p: 2 },
      { figure: 'ProjectionPicture', caption: 'With two observations, y is a point in the plane. Every possible prediction lies on the grey line; the best one is the perpendicular foot.' },
      { cell: 2 },
      { p: 3 }, { p: 4 },
      { math: true },
    ],
    formulaTex: '$$X^\\top X\\,w^* = X^\\top y \\iff X^\\top (y - Xw^*) = 0$$ $$\\hat y = Xw^* = \\operatorname{proj}_{\\operatorname{col}(X)}\\, y$$',
    formula: 'XᵀX w* = Xᵀy     ⇔     Xᵀ(y − Xw*) = 0     ŷ = Xw* is the projection of y onto col(X)',
    mathCode: {
      rows: [
        ['$X^\\top X\\,w = X^\\top y$', 'np.linalg.lstsq(X, y, rcond=None)[0]', 'Solve the normal equations stably, without forming the inverse.'],
        ['$e = Xw^* - y$', 'e = X @ w_star - y', 'Residuals at the solution.'],
        ['$X^\\top e = 0$', 'X.T @ e', 'One zero per column: the residual is orthogonal to each.'],
        ['$\\sum_i e_i = 0$', 'e.sum()', 'The ones column’s condition: residuals average to zero.'],
      ],
    },
    notebook: notebooks['l03-projection'],
    experiment: 'Watch the orthogonality readouts (Σe, Σe·x₁, Σe·x₂) after 10, 40 and 400 steps: how close to zero do they get? Compare the least-squares and gradient-descent rows of the table. How many steps until they agree to three decimals?',
    question: 'A fit has residuals e = [1, −2, 1] on inputs x = [−1, 0, 1] with an intercept. What is Σ eᵢ·xᵢ?',
    answer: 0,
    explanation: '1×(−1) + (−2)×0 + 1×1 = 0, and Σ eᵢ = 0 too. Both orthogonality conditions hold, so this is the least-squares fit for that data.',
    reflection: 'Explain why adding a useless random feature can still lower training error. What does that imply about judging models by training error?',
  },
  {
    id: 'l03-rank',
    title: '03.6 · Rank, collinearity and constant columns',
    sections: ['When the answer is not unique', 'Rank', 'Nearly collinear features', 'Constant columns', 'Interpreting weights honestly'],
    skill: 'Recognize rank deficiency and collinearity, and explain their effect on weights versus predictions.',
    prerequisite: 'Lesson 03.5; the normal equations.',
    paragraphs: [
      'Suppose one column records size in MB and another the same size in KB: `x₂ = 1024·x₁`. Then `w₁ = 2, w₂ = 0` and `w₁ = 0, w₂ = 2/1024` give identical predictions for every row — and so do infinitely many combinations in between. The data cannot say how to divide the credit. XᵀX is singular and the normal equations have no unique solution: the bowl has become a valley with a flat floor.',
      'The **rank** of X is the number of linearly independent columns: columns that cannot be written as combinations of the others. With p + 1 columns and rank p + 1, the least-squares weights are unique. With lower rank, the loss has a flat valley of equally good solutions. `np.linalg.matrix_rank(X)` computes it; `lstsq` returns the solution of smallest length in that case.',
      'Exact duplicates are rare; **near** collinearity is common. When x₂ ≈ x₁ plus a little noise, the solution is unique but fragile: small changes in the data swing weight between the two features while their sum stays stable. Predictions remain good, but individual weights — and any story told about them — become unreliable. The playground’s resampled refits make this visible as a long, thin cloud.',
      'A column that never changes is collinear with the intercept column of ones: `constant = c·1`. Its weight and the intercept cannot be separated. Drop constant columns (or those constant within the training data) before fitting. The same happens with one-hot encoded categories when every category column is kept alongside an intercept.',
      'Procedure: check `matrix_rank` and the pairwise correlations of features; drop duplicates and constants; if two meaningful features are strongly correlated, report their combined effect or regularize (Lab 07) rather than interpreting each weight alone. A weight describes the association **holding the other features fixed**, which may be a situation your data rarely contains.',
    ],
    blocks: [
      { p: 0 },
      { figure: 'RankCheck', caption: 'Four design matrices. Which columns can be written using the others?' },
      { p: 1 },
      { cell: 0 },
      { p: 2 },
      { figure: 'WeightSpace', props: { corr: 0.95, show: ['corr'], cloud: true }, caption: 'Near-collinear features: the bowl stretches into a valley, and refits on resampled data (orange) scatter along it.' },
      { cell: 1 },
      { p: 3 },
      { predict: { prompt: 'What is the rank of a matrix with columns `[1, 1, 1]`, `[2, 2, 2]` and `[1, 2, 3]`?', answer: 2, explain: '[2, 2, 2] = 2 × [1, 1, 1], so only two columns are independent.' } },
      { p: 4 },
      { math: true },
    ],
    formula: 'rank(X) < p + 1  ⇒  XᵀX singular  ⇒  infinitely many w with minimal loss',
    mathCode: {
      rows: [
        ['$\\operatorname{rank}(X)$', 'np.linalg.matrix_rank(X)', 'Number of independent columns.'],
        ['$\\operatorname{corr}(x_1, x_2)$', 'np.corrcoef(X[:, 1], X[:, 2])[0, 1]', 'How nearly two features duplicate each other.'],
        ['minimum-length $w$', 'np.linalg.lstsq(X, y, rcond=None)[0]', 'The solution lstsq returns when many tie.'],
      ],
    },
    notebook: notebooks['l03-rank'],
    experiment: 'Drag correlation from 0 to 0.99, then to exactly 1. Watch the refit cloud and the least-squares row. At 0.99, are predictions still good? Record what you observe about weights versus predictions.',
    question: 'What is the rank of a matrix whose columns are [1, 1, 1], [1, 2, 3] and [2, 4, 6]?',
    answer: 2,
    misconceptions: [{ answer: 3, feedback: 'Three columns, but not three independent ones: compare the third column with the second.' }],
    explanation: 'The third column is twice the second, so it adds no new direction. The first two are independent, giving rank 2.',
    reflection: 'Name two features in your data that are likely correlated. Would you trust a claim about either weight alone?',
  },
  {
    id: 'l03-scaling',
    title: '03.7 · Units, step sizes and standardization',
    sections: ['Change the units, change the path', 'Where the step-size limit comes from', 'Two features, two very different limits', 'Standardize with training statistics', 'Convert back and report'],
    skill: 'Derive the stable learning rate for one feature, explain why mismatched units slow gradient descent, and standardize without leakage.',
    prerequisite: 'Lessons 03.3–03.4: gradient descent and the loss bowl.',
    paragraphs: [
      'Record x₂ in KB instead of MB and every value becomes 1,000 times larger. The weight giving the same predictions becomes 1,000 times smaller (2 per MB is 0.002 per KB). The best model has not changed — only its units. Gradient descent notices, though: `∂J/∂w₂ = (2/n) Σ eᵢ·xᵢ₂` is now 1,000 times larger, while the distance w₂ needs to travel is 1,000 times smaller.',
      'Take one feature and no intercept, with the target exactly `y = w*·x`. The error of row i is `(w − w*)·xᵢ`, so the gradient is `2·mean(x²)·(w − w*)`, and one step gives `w − w* ← (1 − 2α·mean(x²))·(w − w*)`. Each step **multiplies the distance to the best weight by (1 − 2α·mean(x²))**. It shrinks only if that factor lies between −1 and 1, which means **α < 1/mean(x²)**. With mean(x²) = 4: α = 0.1 gives factor 0.2 (fast), α = 0.25 gives −1 (bounces forever), α = 0.3 gives −1.4 (diverges).',
      'With two features the same logic applies to each, and **one** α must satisfy the strictest limit. If x₁ is around 1 and x₂ is around 1,000, the x₂ direction needs α below roughly 10⁻⁶. At that rate the x₁ direction shrinks by a factor of about (1 − 2×10⁻⁶) per step: after 400 steps w₁ has barely moved. Choose **largest stable rate** in the playground to see exactly this — the rate is computed from the data, so the path cannot diverge, and yet it crawls. Picking any fixed rate from the list instead (even 0.0001) diverges.',
      '**Standardization** subtracts each column’s training mean and divides by its training standard deviation, so every feature has mean 0 and spread 1. Now every direction has a similar limit, one α suits them all, and the contours become close to circles. Correlated features still stretch the bowl diagonally (Lesson 03.6); scaling cannot remove that. As in Lab 02, the means and deviations are learned from training rows only and reused unchanged on validation and new data.',
      'Weights learned on standardized features are “per standard deviation”. Convert them back: `w_original = w_std / s`, and `b_original = b − Σ w_original·m` using the training means m. Report weights in original units, with the preprocessing that produced them, so someone else can apply the model to a raw input.',
    ],
    blocks: [
      { p: 0 },
      { figure: 'WeightSpace', props: { scale: 1000, show: ['scale', 'std', 'stable'], steps: 400, rate: 0.1 }, caption: 'x₂ in KB: tick “largest stable rate” and watch the path crawl; then standardize.' },
      { p: 1 },
      { figure: 'StepFactor', caption: 'The distance to the best weight after each step, for one feature.' },
      { predict: { prompt: 'One feature with mean(x²) = 4 and α = 0.2. What is the step factor 1 − 2α·mean(x²)?', answer: -0.6, tolerance: 0.001, explain: '1 − 2 × 0.2 × 4 = −0.6: each step overshoots the best weight, but by less each time, so it still converges.' } },
      { cell: 0 },
      { p: 2 },
      { cell: 1 },
      { p: 3 },
      { cell: 2 },
      { p: 4 },
      { math: true },
    ],
    formulaTex: '$$w_{k+1} - w^* = \\big(1 - 2\\alpha\\,\\overline{x^2}\\big)(w_k - w^*)$$ $$\\text{stable iff } 0 < \\alpha < \\frac{1}{\\overline{x^2}}$$ $$z = \\frac{x - m_{\\text{train}}}{s_{\\text{train}}}$$',
    formula: 'one feature: distance × (1 − 2α·mean(x²)) per step  ⇒  stable iff α < 1/mean(x²)     z = (x − m_train)/s_train',
    mathCode: {
      rows: [
        ['$\\overline{x^2}$', 'np.mean(x ** 2)', 'The curvature of the one-feature loss, halved.'],
        ['$1/\\overline{x^2}$', '1 / np.mean(x ** 2)', 'The largest stable learning rate for that feature.'],
        ['$m_{\\text{train}},\\, s_{\\text{train}}$', 'm, s = X_train.mean(axis=0), X_train.std(axis=0)', 'Learned from training rows only.'],
        ['$z$', '(X_new - m) / s', 'Applied unchanged to any other rows.'],
        ['$w_{\\text{original}}$', 'w_std / s', 'Weights back in original units.'],
      ],
    },
    notebook: notebooks['l03-scaling'],
    experiment: 'Set x2 units to × 1000 with standardization off. Choose **largest stable rate** and run 400 steps: how far has w1 moved toward its least-squares value? Now switch standardization on, keep the same rate choice, and compare the path and the final MSE. Finally, with × 1000 and no standardization, pick α = 0.0001 and explain the warning.',
    question: 'One feature, no intercept, mean(x²) = 4. Gradient descent converges for every learning rate α below what value?',
    answer: 0.25,
    misconceptions: [
      { answer: 4, feedback: 'That is mean(x²) itself. The limit is its reciprocal: α < 1/mean(x²).' },
      { answer: 0.5, feedback: 'The factor per step is 1 − 2α·mean(x²), and it must stay above −1: 2α·4 < 2 gives α < 0.25. You may have dropped the 2 from differentiating the square.' },
    ],
    explanation: 'Each step multiplies the distance to the best weight by 1 − 2α·4 = 1 − 8α. That factor lies in (−1, 1) exactly when 0 < α < 0.25. At α = 0.25 it equals −1 and the weight bounces forever.',
    reflection: 'Which of your features have very different ranges? Write the exact code you would use to standardize them without leakage.',
  },
  {
    id: 'l03-conditioning',
    title: '03.8 · Second pass: curvature, eigenvalues and the condition number',
    sections: ['From one curvature to many', 'Eigenvectors: directions A only stretches', 'The stable learning rate, exactly', 'The condition number', 'What standardization can and cannot fix'],
    skill: 'Compute the eigenvalues of a 2×2 curvature matrix, derive the stable learning rate 1/λmax, and explain what κ says about the speed of gradient descent.',
    prerequisite: 'Lesson 03.7. **Optional on a first pass** — Labs 04–08 do not depend on it. Come back before Lab 18 (PCA) or Lab 22 (optimizers), which build on eigenvalues.',
    paragraphs: [
      'In Lesson 03.7 one feature had one curvature, mean(x²), and one stability limit. With several centered features the curvature becomes a matrix: `J(w) = J* + (w − w*)ᵀ A (w − w*)` with **A = XᵀX/n**. Its diagonal holds each feature’s mean(x²); its off-diagonal entries hold mean(x_j·x_k), which is where correlation enters. A small example: mean(x₁²) = 1, mean(x₂²) = 1 and mean(x₁x₂) = 0.9 give `A = [[1, 0.9], [0.9, 1]]`.',
      'An **eigenvector** v of A is a direction that A only stretches, without turning: `Av = λv`, where the number λ is its **eigenvalue**. Check two directions for our A. For v = (1, 1): Av = (1.9, 1.9) = 1.9·v, so λ = 1.9. For v = (1, −1): Av = (0.1, −0.1) = 0.1·v, so λ = 0.1. Along each eigenvector the bowl behaves like a one-feature problem with curvature λ. The contours are ellipses whose axes lie along the eigenvectors, with lengths proportional to `1/√λ`: long along (1, −1), short along (1, 1).',
      'Gradient descent treats each eigen-direction separately: the distance to w* along direction k is multiplied by `(1 − 2αλ_k)` every step — the one-feature factor from Lesson 03.7 with mean(x²) replaced by λ_k. Every factor must lie between −1 and 1, so **α < 1/λmax**: the playground’s “stable α below” readout. Here that is 1/1.9 ≈ 0.53. At α = 0.4 the steep direction shrinks by |1 − 0.8×1.9| = 0.52 per step (about 4 steps per factor of 10), but the flat one only by 1 − 0.8×0.1 = 0.92 (about 28 steps per factor of 10).',
      'The **condition number** κ = λmax / λmin summarizes this imbalance: the number of steps gradient descent needs grows roughly in proportion to κ. In the example κ = 19. With x₂ recorded in KB, κ reaches about 10⁶. κ of A is already the square of X’s own condition number, which is why Lesson 03.5 warns against forming XᵀX explicitly.',
      'Standardization sets every diagonal entry of A to 1, removing the imbalance caused by units. It cannot remove correlation: standardized features with correlation ρ have `A = [[1, ρ], [ρ, 1]]`, eigenvalues 1 + ρ and 1 − ρ, and κ = (1 + ρ)/(1 − ρ) — 19 when ρ = 0.9. Remedies for that are different: regularization (Lab 07), combining the correlated features, or optimizers that adapt to the geometry, such as momentum and Adam (Lab 22).',
    ],
    blocks: [
      { p: 0 }, { p: 1 },
      { figure: 'EigenStretch', caption: 'Turn v and watch Av. At two special angles A only stretches v.' },
      { cell: 0 },
      { p: 2 },
      { figure: 'EigenDecay', caption: 'How fast each eigen-direction closes in, for a given α.' },
      { cell: 1 },
      { p: 3 },
      { predict: { prompt: 'Standardized features with correlation ρ = 0.8. What is the condition number (1 + ρ)/(1 − ρ)?', answer: 9, tolerance: 0.001, explain: '1.8 / 0.2 = 9.' } },
      { p: 4 },
      { figure: 'WeightSpace', props: { corr: 0.9, standardize: true, show: ['corr', 'std', 'rate'] }, caption: 'Standardized, yet still correlated: the ellipses stay diagonal and stretched.' },
      { math: true },
      { derivation: true },
    ],
    formulaTex: '$$A = \\tfrac{1}{n}X^\\top X$$ $$Av = \\lambda v$$ $$\\text{stable iff } 0 < \\alpha < \\frac{1}{\\lambda_{\\max}}$$ $$\\kappa = \\frac{\\lambda_{\\max}}{\\lambda_{\\min}}$$',
    formula: 'A = XᵀX/n     Av = λv     stable: 0 < α < 1/λmax     κ = λmax/λmin',
    mathCode: {
      rows: [
        ['$A = \\frac{1}{n}X^\\top X$', 'A = X.T @ X / n', 'The curvature matrix of centered features.'],
        ['$Av = \\lambda v$', 'vals, vecs = np.linalg.eigh(A)', 'Eigenvalues (ascending) and eigenvectors (columns) of a symmetric matrix.'],
        ['$1/\\lambda_{\\max}$', '1 / vals.max()', 'The largest stable learning rate.'],
        ['$\\kappa$', 'vals.max() / vals.min()', 'How stretched the bowl is.'],
      ],
    },
    derivation: {
      title: 'The example matrix A = [[1, 0.9], [0.9, 1]]',
      steps: [
        { prompt: 'Compute A·(1, 1). Its first entry is λ for this direction. What is λ?', number: 1.9, tolerance: 1e-9, show: 'A·(1, 1) = (1 + 0.9, 0.9 + 1) = (1.9, 1.9) = 1.9·(1, 1)' },
        { prompt: 'Compute A·(1, −1). What is its eigenvalue?', number: 0.1, tolerance: 1e-9, show: 'A·(1, −1) = (1 − 0.9, 0.9 − 1) = (0.1, −0.1) = 0.1·(1, −1)' },
        { prompt: 'What is the condition number κ?', number: 19, tolerance: 1e-9, show: 'κ = 1.9 / 0.1 = 19' },
        { prompt: 'Below what learning rate does gradient descent converge? (Three decimals.)', number: 1 / 1.9, tolerance: 0.001, show: 'α < 1/λmax = 1/1.9 ≈ 0.526' },
        { prompt: 'At α = 0.4, what factor multiplies the distance along the flat direction each step?', number: 0.92, tolerance: 1e-9, show: '1 − 2 × 0.4 × 0.1 = 0.92', why: 'The flat direction sets the pace: about 28 steps for every factor of 10.' },
      ],
      result: 'Each eigen-direction is a one-feature problem with curvature λ; the steepest sets the largest safe step, the flattest sets the number of steps.',
    },
    notebook: notebooks['l03-conditioning'],
    experiment: 'Switch standardization on and drag the correlation from 0 to 0.9. Compare the κ readout with (1 + ρ)/(1 − ρ): does the formula predict it? (The sample correlation differs a little from the slider.) Then pick the largest stable rate and count roughly how many steps the path needs to get close to ✕.',
    question: 'XᵀX/n has eigenvalues 4 and 0.01. What is the condition number?',
    answer: 400,
    misconceptions: [{ answer: 0.0025, feedback: 'That is λmin/λmax. κ divides the largest eigenvalue by the smallest.' }],
    explanation: '4 / 0.01 = 400. The stable learning rate is below 1/4 = 0.25, while the flat direction shrinks by only about 2·α·0.01 per step — hundreds of steps for each factor of e.',
    reflection: 'In your own words: why does the steepest direction limit the step size, while the flattest direction limits the speed?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 3.2: multiple linear regression', url: 'https://www.statlearning.com/' },
  { title: 'Mathematics for Machine Learning · Chapters 2–4 (linear algebra, geometry, matrix decompositions)', url: 'https://mml-book.github.io/' },
  { title: 'NumPy · numpy.linalg.lstsq', url: 'https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html' },
  { title: 'scikit-learn · Standardization, or mean removal and variance scaling', url: 'https://scikit-learn.org/stable/modules/preprocessing.html#standardization-or-mean-removal-and-variance-scaling' },
  { title: 'Goh (2017) · Why momentum really works (eigen-directions of gradient descent)', url: 'https://distill.pub/2017/momentum/' },
]
