export const lessons = [
  {
    id: 'l03-design',
    title: '03.1 · Rows are observations, columns are features',
    sections: ['One prediction needs several inputs', 'The design matrix', 'The column of ones', 'Read every shape', 'Put it into practice'],
    skill: 'Organize data as a design matrix and state the meaning and shape of every array in a multi-feature model.',
    prerequisite: 'Lab 01 (one-feature regression, dot products) and Lab 02 (arrays, axes, broadcasting).',
    paragraphs: [
      'A build takes longer when it is larger **and** when it has more files. Size alone leaves a pattern in the errors: two 40 MB builds, one with 10 files and one with 400, take very different times. A model with one input cannot tell them apart. The fix is to give each prediction several inputs, called **features**: `ŷ = w₁·size + w₂·files + b`.',
      'Stack the observations as rows and the features as columns. For n builds and p features this gives the **design matrix** X of shape `(n, p)`: `X[i, j]` is feature j of observation i. Row i is one build; column j is one measurement across all builds. The targets form a vector y of shape `(n,)`, and the weights a vector w of shape `(p,)`, one weight per column.',
      'The intercept b can be folded into the weights. Add a column of ones to X: the design matrix becomes `(n, p + 1)` and w gains one entry. Row i\'s prediction is then `1·b + x_i1·w₁ + … + x_ip·w_p`, so the bias is just the weight on a feature that is always 1. `np.column_stack([np.ones(n), X])` builds it. From here on, one formula covers every weight, the intercept included.',
      'Before any computation, write the shape next to every array: X `(n, p+1)`, w `(p+1,)`, predictions `(n,)`, errors `(n,)`, gradient `(p+1,)`. If a result has a shape you did not predict, stop — the computation is wrong even if it runs. Most multi-feature bugs are a transposed matrix, a missing intercept column, or a `(n, 1)` column meeting a `(n,)` vector.',
      'Procedure: decide what one row represents (one build, one customer, one day); list the features available **before** the target is known; build X and y; print `X.shape`, `y.shape`, and the first rows; verify one row\'s prediction by hand.',
    ],
    formula: 'X ∈ ℝⁿˣ⁽ᵖ⁺¹⁾ (first column = 1)     w ∈ ℝᵖ⁺¹     ŷ = X w ∈ ℝⁿ',
    experiment: 'Read the "Shapes, tracked" panel. Before looking, predict the shape of `Xᵀ @ e` for the playground\'s data. Why does it have one entry per weight rather than one per observation?',
    question: 'A dataset has 50 builds and 3 features. How many numbers does the design matrix contain after adding the intercept column?',
    answer: 200,
    explanation: 'Three features plus one column of ones gives shape `(50, 4)`: 50 × 4 = 200 numbers.',
    reflection: 'For your own project, what is one row? List three features that exist before the target is measured.',
  },
  {
    id: 'l03-matmul',
    title: '03.2 · Matrix multiplication is many dot products',
    sections: ['One row, one dot product', 'All rows at once', 'The shape rule', 'Transpose', 'Why vectorize'],
    skill: 'Compute matrix–vector and matrix–matrix products by hand and predict their shapes.',
    prerequisite: 'Lesson 03.1; the dot product from Lab 01.',
    paragraphs: [
      'Take weights `w = [10, 1]` and one observation `[3, 4]`. The prediction is the dot product: 3×10 + 4×1 = 34. Now take two observations as rows of `X = [[1, 2], [3, 4]]`. Each row gets its own dot product with the same w: the first is 1×10 + 2×1 = 12, the second is 34. The result `[12, 34]` is `X @ w`.',
      'In general, `(X @ w)[i]` is the dot product of row i of X with w. **Matrix multiplication** of A `(a, b)` by B `(b, c)` produces C `(a, c)` where `C[i, k]` is the dot product of row i of A with column k of B. A vector is treated as a single column, so `(n, p) @ (p,)` gives `(n,)`.',
      'The shape rule: the **inner** dimensions must match and disappear; the outer dimensions remain. `(50, 4) @ (4,)` → `(50,)`. `(4, 50) @ (50,)` → `(4,)`. `(50, 4) @ (50,)` is an error, because each row has 4 entries but the vector has 50. `@` is not elementwise `*`: `*` needs broadcast-compatible shapes and multiplies matching entries without summing.',
      'The **transpose** Xᵀ swaps rows and columns: `(n, p)` becomes `(p, n)`, and `Xᵀ[j, i] = X[i, j]`. `Xᵀ @ e` computes, for each feature column j, the dot product of that column with the vector e — one number per feature. That operation appears in every gradient in this course.',
      'A Python loop over rows computes the same values, but `X @ w` runs in optimized compiled code, often hundreds of times faster, and states the intent in one expression. Write the loop once to convince yourself, check it matches, then use the vectorized form.',
    ],
    formula: '(A @ B)[i, k] = Σⱼ A[i, j]·B[j, k]     (a, b) @ (b, c) → (a, c)',
    experiment: 'In the shapes panel, check each line with the shape rule. Then predict what shape `X @ Xᵀ` would have for the playground data, and what one of its entries means.',
    question: 'Compute the second entry of `[[1, 2], [3, 4]] @ [10, 1]`.',
    answer: 34,
    explanation: 'Row 2 is `[3, 4]`: 3×10 + 4×1 = 34. The full result is `[12, 34]`.',
    reflection: 'Explain in words why the inner dimensions must match. What would a mismatch mean about your data?',
  },
  {
    id: 'l03-gradient',
    title: '03.3 · The gradient in matrix form',
    sections: ['Start from one weight', 'Every weight at once', 'Check the shapes', 'The same algorithm', 'Verify numerically'],
    skill: 'Derive the least-squares gradient as `(2/n) Xᵀ(Xw − y)` and implement batch gradient descent for any number of features.',
    prerequisite: 'Lessons 03.1–03.2; the one-feature gradient and chain rule from Lab 01.',
    paragraphs: [
      'With one feature, the derivative of MSE with respect to the weight was `2·mean(e·x)`, where `e = ŷ − y`. Nothing about that derivation used the fact that there was only one feature. For weight j, the error of observation i changes at rate `x_ij` when `w_j` changes, so `∂J/∂w_j = (2/n) Σᵢ eᵢ·x_ij` — the same formula, with feature column j in place of x.',
      'Stack those p + 1 derivatives into a vector. Entry j is the dot product of column j of X with e, divided by n and doubled. That is exactly what `Xᵀ @ e` computes for all columns at once: **∇J = (2/n) Xᵀ (Xw − y)**. The intercept\'s entry comes from the column of ones, giving `2·mean(e)`, as before.',
      'Shapes: `Xw − y` is `(n,)`; Xᵀ is `(p+1, n)`; their product is `(p+1,)` — one partial derivative per weight. If you ever get a gradient of shape `(n,)`, you multiplied by X instead of Xᵀ.',
      'The learning rule is unchanged: compute the whole gradient at the current w, then `w ← w − α∇J`. Because w is a vector, one line updates every weight simultaneously. Nothing in the algorithm depends on p; the same five lines fit two features or two thousand.',
      'Always check a new gradient formula against finite differences, one weight at a time: perturb `w_j` by ±ε, recompute the loss, and compare `[J(w+εe_j) − J(w−εe_j)]/(2ε)` to entry j of your gradient. A mismatch almost always means a missing transpose, a wrong sign, or a forgotten factor of 2.',
    ],
    formula: '∇J(w) = (2/n) Xᵀ (Xw − y)     w ← w − α ∇J(w)',
    experiment: 'Set 40 steps at α = 0.1, then 400 steps. Watch the dashed path. Is each step perpendicular to the contour it starts on? (It should be: the gradient points across contours, uphill.)',
    question: 'X = [[1, 2], [1, 4]], y = [3, 5], w = [0, 1]. Compute the second entry of ∇J = (2/n) Xᵀ(Xw − y).',
    answer: -6,
    explanation: 'Xw = [2, 4], so e = Xw − y = [−1, −1]. Xᵀe takes each column\'s dot product with e: column [1, 1] gives −2, column [2, 4] gives −6. With n = 2, the factor 2/n is 1, so ∇J = [−2, −6] and the second entry is −6. Both entries are negative: increasing either weight would reduce the loss.',
    reflection: 'Why does the intercept\'s gradient entry reduce to twice the mean error? Explain using the column of ones.',
  },
  {
    id: 'l03-projection',
    title: '03.4 · Least squares is a projection',
    sections: ['Set the gradient to zero', 'The residual is perpendicular', 'The geometry', 'Solve it properly', 'Gradient descent or a solver?'],
    skill: 'Derive the normal equations, interpret the fit as an orthogonal projection, and solve with a numerically stable routine.',
    prerequisite: 'Lesson 03.3; the gradient in matrix form.',
    paragraphs: [
      'At the minimum of a convex bowl the gradient is zero: `(2/n) Xᵀ(Xw − y) = 0`. Rearranged: **XᵀX w = Xᵀy**. These are the **normal equations**: p + 1 linear equations in p + 1 unknowns. When XᵀX is invertible they have exactly one solution, the least-squares weights.',
      'Read the zero-gradient condition directly: `Xᵀe = 0` means every column of X has zero dot product with the residual vector e. Two vectors with zero dot product are **orthogonal** (perpendicular). The column of ones gives `Σ eᵢ = 0`: at the optimum, residuals average to zero. Each feature column gives `Σ eᵢ x_ij = 0`: residuals are uncorrelated with every feature. Any remaining pattern must be something the features cannot express.',
      'Think of y as a point in n-dimensional space, one coordinate per observation. Every possible prediction `Xw` lies in the **column space** of X: all combinations of its columns. Least squares picks the point in that space closest to y, and the closest point is the perpendicular foot — an orthogonal **projection**. Adding a feature enlarges the space; the projection can only get closer, so training error never increases when you add a column.',
      'Do not compute `np.linalg.inv(X.T @ X) @ X.T @ y`. Forming XᵀX squares the condition number (defined in Lesson 03.6), amplifying rounding error, and fails outright when XᵀX is singular. Use `np.linalg.lstsq(X, y, rcond=None)`, which solves the problem through a stable factorization of X itself and returns a sensible answer even when the solution is not unique.',
      'Why keep gradient descent at all? A direct solver is exact and fast for thousands of features. Gradient descent scales to problems too large to factor, works when data arrives in batches, and — crucially — generalizes to models with no closed form. Neural networks are trained by exactly the loop you are writing here.',
    ],
    formula: 'XᵀX w* = Xᵀy     ⇔     Xᵀ(y − Xw*) = 0     ŷ = Xw* is the projection of y onto col(X)',
    experiment: 'Compare the least-squares and gradient-descent rows of the table after 40, 100 and 400 steps. How many steps until they agree to three decimals? Does that number change when you standardize?',
    question: 'A fit has residuals e = [1, −2, 1] on inputs x = [−1, 0, 1] with an intercept. What is Σ eᵢ·xᵢ?',
    answer: 0,
    explanation: '1×(−1) + (−2)×0 + 1×1 = 0, and Σ eᵢ = 0 too. Both orthogonality conditions hold, so this is the least-squares fit for that data.',
    reflection: 'Explain why adding a useless random feature can still lower training error. What does that imply about judging models by training error?',
  },
  {
    id: 'l03-rank',
    title: '03.5 · Rank, collinearity and constant columns',
    sections: ['When the answer is not unique', 'Rank', 'Nearly collinear features', 'Constant columns', 'Interpreting weights honestly'],
    skill: 'Recognize rank deficiency and collinearity, and explain their effect on weights versus predictions.',
    prerequisite: 'Lesson 03.4; the normal equations.',
    paragraphs: [
      'Suppose one column records size in MB and another the same size in KB: `x₂ = 1024·x₁`. Then `w₁ = 2, w₂ = 0` and `w₁ = 0, w₂ = 2/1024` give identical predictions for every row — and so do infinitely many combinations in between. The data cannot say how to divide the credit. XᵀX is singular and the normal equations have no unique solution.',
      'The **rank** of X is the number of linearly independent columns: columns that cannot be written as combinations of the others. With p + 1 columns and rank p + 1, the least-squares weights are unique. With lower rank, the loss has a flat valley of equally good solutions. `np.linalg.matrix_rank(X)` computes it; `lstsq` returns the solution of smallest length in that case.',
      'Exact duplicates are rare; **near** collinearity is common. When x₂ ≈ x₁ plus a little noise, the solution is unique but fragile: small changes in the data swing weight between the two features while their sum stays stable. Predictions remain good, but individual weights — and any story told about them — become unreliable. The playground\'s resampled refits make this visible as a long, thin cloud.',
      'A column that never changes is collinear with the intercept column of ones: `constant = c·1`. Its weight and the intercept cannot be separated. Drop constant columns (or those constant within the training data) before fitting. The same happens with one-hot encoded categories when every category column is kept alongside an intercept.',
      'Procedure: check `matrix_rank` and the pairwise correlations of features; drop duplicates and constants; if two meaningful features are strongly correlated, report their combined effect or regularize (Lab 07) rather than interpreting each weight alone. A weight describes the association **holding the other features fixed**, which may be a situation your data rarely contains.',
    ],
    formula: 'rank(X) < p + 1  ⇒  XᵀX singular  ⇒  infinitely many w with minimal loss',
    experiment: 'Drag correlation from 0 to 0.99, then to exactly 1. Watch the refit cloud, κ and the least-squares row. At 0.99, are predictions still good? Record what you observe about weights versus predictions.',
    question: 'What is the rank of a matrix whose columns are [1, 1, 1], [1, 2, 3] and [2, 4, 6]?',
    answer: 2,
    explanation: 'The third column is twice the second, so it adds no new direction. The first two are independent, giving rank 2.',
    reflection: 'Name two features in your data that are likely correlated. Would you trust a claim about either weight alone?',
  },
  {
    id: 'l03-scaling',
    title: '03.6 · Scaling and the shape of the loss',
    sections: ['A long, thin valley', 'Curvature and eigenvalues', 'The condition number', 'Standardize with training statistics', 'Convert back and report'],
    skill: 'Explain how feature scale and correlation shape the loss surface, choose a stable learning rate, and standardize correctly.',
    prerequisite: 'Lessons 03.3–03.5; eigenvectors are introduced here.',
    paragraphs: [
      'Measure x₂ in KB instead of MB and its values become 1024 times larger. The loss now changes about a million times faster when w₂ moves than when w₁ moves. The bowl becomes a narrow canyon. A learning rate small enough not to overshoot across the canyon crawls along its length: after hundreds of steps, w₁ has barely moved.',
      'For centered features, MSE is exactly `L(w) = L* + (w − w*)ᵀ A (w − w*)` with `A = XᵀX/n`. An **eigenvector** v of A is a direction that A only stretches: `Av = λv`. Its **eigenvalue** λ is the curvature of the bowl along that direction. The contours are ellipses whose axes are the eigenvectors, with lengths proportional to `1/√λ`.',
      'The **condition number** κ = λmax / λmin measures how stretched the bowl is. Gradient descent is stable only when `α < 1/λmax` (the Hessian of MSE is 2A), yet progress along the flattest direction is proportional to `α·λmin`. So the number of steps needed grows roughly like κ. A κ of 10⁶ means a million-fold slowdown — and a squared condition number for methods that form XᵀX explicitly.',
      '**Standardization** subtracts each column\'s training mean and divides by its training standard deviation, so every feature has mean 0 and spread 1. For uncorrelated features this makes A close to the identity: circular contours, κ ≈ 1, fast convergence. Correlation still stretches the bowl diagonally; scaling cannot remove that. As in Lab 02, the means and deviations are learned from training rows only and reused unchanged.',
      'Weights learned on standardized features are "per standard deviation". Convert them back: `w_original = w_std / s`, and `b_original = b − Σ w_original·m` using the training means m. Report weights in original units, together with the preprocessing that produced them, so someone else can apply the model to a raw input.',
    ],
    formula: 'A = XᵀX/n     κ = λmax/λmin     stable: 0 < α < 1/λmax     z = (x − m_train)/s_train',
    experiment: 'Choose x2 units × 1000 with standardization off. Note κ and the stable α. Run 400 steps at the largest stable rate. Then standardize, keep everything else, and compare the path and the final MSE.',
    question: 'XᵀX/n has eigenvalues 4 and 0.01. What is the condition number?',
    answer: 400,
    explanation: '4 / 0.01 = 400. The stable learning rate is below 1/4 = 0.25, while the flat direction shrinks its error by only about 2·α·0.01 per step — hundreds of steps for each factor of e.',
    reflection: 'Which of your features have very different ranges? Write the exact code you would use to standardize them without leakage.',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 3.2: multiple linear regression', url: 'https://www.statlearning.com/' },
  { title: 'Mathematics for Machine Learning · Chapters 2–3 (linear algebra, geometry)', url: 'https://mml-book.github.io/' },
  { title: 'NumPy · numpy.linalg.lstsq', url: 'https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html' },
  { title: 'scikit-learn · Standardization, or mean removal and variance scaling', url: 'https://scikit-learn.org/stable/modules/preprocessing.html#standardization-or-mean-removal-and-variance-scaling' },
]
