// Lesson order for Lab 25: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l25-tokens': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { cell: 0 },
    { predict: { prompt: 'A batch of 32 sequences of 20 tokens is embedded with d = 64. How many numbers does the embedded batch hold?', answer: 40960, explain: 'Its shape is (B, T, d) = (32, 20, 64): 32 × 20 × 64 = 40,960.', misconceptions: [{ answer: 1280, feedback: 'That is one sequence, 20 × 64. The batch holds 32 of them.' }] } },
    { p: 3 },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l25-order': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { figure: 'OrderMean', caption: 'Two orders of the same four tokens, with opposite labels, and their mean embedding.' },
    { predict: { prompt: 'E[deploy] = (1, 0) and E[error] = (0, 1). What is the first coordinate of the mean embedding of “deploy, error, error”? (Three decimals.)', answer: 0.333, tolerance: 0.001, explain: '((1, 0) + (0, 1) + (0, 1))/3 = (1/3, 2/3): the first coordinate is 0.333, whatever the order.' } },
    { p: 2 },
    { cell: 1 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l25-rnn': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { predict: { prompt: 'An RNN has embedding size 16 and hidden size 32. How many parameters are in W_x, W_h and b?', answer: 1568, explain: 'W_x: 16 × 32 = 512; W_h: 32 × 32 = 1,024; b: 32. Total 1,568, for any sequence length.', misconceptions: [{ answer: 544, feedback: 'W_h is square: hidden × hidden = 32 × 32.' }] } },
    { p: 2 }, { p: 3 },
    { figure: 'GradThroughTime', caption: 'How big the gradient is after k steps back, when each step multiplies it by the same factor.' },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l25-padding': [
    { p: 0 }, { p: 1 },
    { cell: 0 },
    { figure: 'PadDilution', caption: 'The mean embedding of “deploy, restart, error” as padding is added, with and without a mask.' },
    { predict: { prompt: 'Two real tokens with embeddings (2, 0) and (0, 2) are padded to length 8 with zero vectors. What is the first coordinate of the unmasked mean?', answer: 0.25, tolerance: 0.001, explain: '(2 + 0 + 6 × 0)/8 = 0.25. The masked mean divides by the 2 real tokens: 1.', misconceptions: [{ answer: 1, feedback: 'That is the masked mean. Unmasked, the six zero pads count in the denominator: 2/8.' }] } },
    { p: 2 },
    { cell: 1 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l25-shortcuts': [
    { p: 0 }, { p: 1 },
    { cell: 1 },
    { p: 2 },
    { cell: 0 },
    { predict: { prompt: 'Windows of 20 events are cut from one log, starting every 5 events. How many other windows does a window (away from the ends) share events with?', answer: 6, explain: 'Windows starting 5, 10 or 15 events earlier or later overlap it: 3 before and 3 after. A random split puts most of them on the other side.', misconceptions: [{ answer: 3, feedback: 'Count both directions: 3 earlier windows and 3 later ones.' }, { answer: 4, feedback: 'A window 20 events away no longer overlaps; 5, 10 and 15 do, on both sides.' }] } },
    { p: 3 }, { p: 4 },
    { math: true },
    { ladder: 'rnn' },
  ],
}
