import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l25-tokens',
    title: '25.1 · Tokens and embeddings',
    sections: ['Sequences of symbols', 'One-hot is wasteful', 'An embedding table', 'Learned by backpropagation', 'Put it into practice'],
    skill: 'Represent symbols as learned embedding vectors and track the shapes of embedded sequences.',
    prerequisite: 'Labs 01–24; bag of words (Lab 11), neural networks (Labs 21–23).',
    paragraphs: [
      'Logs, user sessions, text and DNA are sequences of symbols from a **vocabulary**. First map each symbol to an integer id: `deploy → 1`, `error → 2`. The ids are labels, not quantities — "error" is not twice "deploy".',
      'A **one-hot** vector for a vocabulary of V symbols has a single 1 among V entries. It is exact but large (V can be 50,000), and every pair of symbols is equally different from every other: nothing says "timeout" is closer to "error" than to "login".',
      'An **embedding table** E has one row of d numbers per symbol (shape V × d); looking up token t means taking row t. Multiplying a one-hot vector by E gives exactly that row, so an embedding is a linear layer with a cheap implementation. A sequence of length T becomes a (T, d) array; a batch of B sequences, (B, T, d).',
      'The table\'s values are parameters learned by backpropagation like any weights; each row\'s gradient comes only from the positions where that token appears (the accumulation rule, Lab 20). Symbols that play similar roles in the task end up with similar vectors — the playground plots the learned table.',
      'Procedure: build the vocabulary from training data only (Lab 11), reserve ids for padding and unknown symbols, choose d (tens to hundreds), and embed. With 10 symbols and d = 4 the table has 40 parameters.',
    ],
    formula: 'token t → E[t] ∈ ℝᵈ     sequence (T,) → (T, d)     batch (B, T) → (B, T, d)',
    experiment: 'Train the RNN, then look at the embedding plot. Where do "deploy" and "error" sit relative to the filler events? What about "[bot]" with the shortcut on?',
    question: 'A vocabulary of 10,000 tokens is embedded with d = 64. How many parameters does the embedding table have?',
    answer: 640000,
    explanation: '10,000 × 64 = 640,000 — often the largest single layer in a small language model.',
    reflection: 'What would the vocabulary be for a sequence problem in your work? Which tokens would you expect to end up with similar embeddings?',
  },
  {
    id: 'l25-order',
    title: '25.2 · Order and a baseline that ignores it',
    sections: ['Bag of embeddings', 'What averaging destroys', 'Always build this baseline', 'Where order is irrelevant', 'Diagnosing the gap'],
    skill: 'Build a mean-pooled baseline and recognize when order carries the signal.',
    prerequisite: 'Lesson 25.1; baselines (Lab 06).',
    paragraphs: [
      'The simplest sequence model averages the token embeddings and feeds the result to a classifier. It is fast, works for any length, and is a strong baseline for tasks like topic classification.',
      'Averaging is invariant to order: "deploy, error" and "error, deploy" have the same mean. In the playground the label depends on exactly that order, so the pooled model can do no better than exploit token frequencies — it stays close to the base rate: about 60% of test sequences are negative, and it scores about 59%.',
      'Always build this baseline. If it is almost as good as a sequence model, order barely matters for your task and the simpler model may be enough. If a sequence model is far better, you have evidence that order carries the signal.',
      'Many tasks are largely order-insensitive (spam detection, many document classifiers). Others hinge on order: causality in event logs, negation in sentences ("not good"), and anything about time. Decide from the problem, then confirm with the baseline.',
      'A large gap can also mean something unintended: a sequence model may be exploiting position artifacts or sequence length. Inspect what distinguishes the examples it gets right.',
    ],
    formula: 'pooled(x₁…x_T) = (1/T) Σ E[x_t]     (identical for every reordering of the tokens)',
    experiment: 'Train the pooled model and the RNN on the same data. Record both test accuracies and the base rate.',
    question: 'Embeddings are E[deploy] = (1, 0) and E[error] = (0, 1). What is the first coordinate of the mean embedding of "error, deploy"?',
    answer: 0.5,
    explanation: '((0, 1) + (1, 0))/2 = (0.5, 0.5) — exactly the same as for "deploy, error". Order is gone.',
    reflection: 'For a sequence task you know, would a bag-of-embeddings baseline be strong or weak? Why?',
  },
  {
    id: 'l25-rnn',
    title: '25.3 · Recurrent networks',
    sections: ['A state carried through time', 'The recurrence', 'Unrolling', 'Backpropagation through time', 'Vanishing and exploding gradients'],
    skill: 'Compute an RNN forward pass, explain BPTT and recognize its gradient problems.',
    prerequisite: 'Lessons 25.1–25.2; backpropagation (Lab 20), clipping (Lab 22).',
    paragraphs: [
      'A **recurrent neural network** reads a sequence one token at a time and keeps a **hidden state** h, a vector summarizing what it has seen. Each step combines the current input with the previous state: `h_t = tanh(E[x_t] W_x + h_{t−1} W_h + b)`. The final state feeds a classifier.',
      'The same weights W_x, W_h and b are used at every step — weight sharing across time, just as convolutions share weights across space. The RNN can therefore process sequences of any length with a fixed number of parameters.',
      'Unrolling the recurrence over T steps produces a deep computation graph, one layer per time step. Training applies ordinary backpropagation to that graph: **backpropagation through time** (BPTT). Each shared weight\'s gradient is the sum of its contributions at every step.',
      'The gradient that reaches early steps is multiplied by W_h and the tanh derivative once per step. Products of many factors below 1 vanish, so the RNN struggles to connect events far apart; factors above 1 explode — use gradient clipping (Lab 22).',
      '**LSTM** and **GRU** cells add gates that decide what to keep, forget and output, giving gradients a more direct path through time. They remain useful for streaming data; for most modelling of long sequences, attention (Lab 26) has replaced them.',
    ],
    formula: 'h_t = tanh(x_t W_x + h_{t−1} W_h + b)     ŷ = σ(h_T · w + c)     BPTT: sum gradients over t',
    experiment: 'Train the RNN and open the hidden-state heatmap for several examples. Which step changes the state most when a deploy is followed by an error?',
    question: 'An RNN has embedding size 4 and hidden size 8. How many parameters are in W_x, W_h and b together?',
    answer: 104,
    explanation: 'W_x: 4 × 8 = 32; W_h: 8 × 8 = 64; b: 8. Total 104 — the same for a sequence of length 3 or 3,000.',
    reflection: 'Explain in your own words why an RNN struggles to connect two events that are 200 steps apart.',
  },
  {
    id: 'l25-padding',
    title: '25.4 · Padding and masking',
    sections: ['Batches need rectangles', 'Padding', 'Masking', 'What goes wrong without it', 'Masking elsewhere'],
    skill: 'Pad variable-length sequences into batches and apply masks so padding cannot change results.',
    prerequisite: 'Lessons 25.1–25.3.',
    paragraphs: [
      'Efficient training processes a batch as one rectangular array, but sequences differ in length. **Padding** fills shorter sequences with a special `<pad>` token up to a common length, e.g. the longest sequence in the batch.',
      'Pads are not data. A **mask** marks which positions are real (1) and which are padding (0). Every operation that mixes positions must respect it: averages divide by the number of real tokens; an RNN skips padded steps (keeping its state); attention assigns padded positions zero weight (Lab 26); the loss ignores padded targets.',
      'Without masking, results depend on how much padding a sequence happened to receive — which depends on the other sequences in its batch. In the playground, an unmasked RNN trained with padding to 8 is excellent at length 8 and collapses toward chance when test batches are padded to 16: the extra pads overwrite its memory. The masked model is unaffected.',
      'Such bugs are dangerous because they pass tests run with one batch configuration and fail in production when the batching changes. A quick check: predictions for a sequence must not change when you pad it more.',
      'Related tools: bucketing sequences of similar length reduces wasted computation; truncation caps very long sequences (decide which end to keep); and a causal mask stops models from looking at future positions (Lab 26).',
    ],
    formula: 'mask_t = 1 if real token else 0     masked mean = Σ mask_t·e_t / Σ mask_t     RNN: h_t = h_{t−1} if mask_t = 0',
    experiment: 'Train the RNN with masking off. Evaluate with padding 8, 12, 16 and 24. Turn masking on, retrain, and repeat.',
    question: 'A batch has sequences of lengths 3, 5 and 8, all padded to 8. How many padding tokens does the batch contain?',
    answer: 8,
    explanation: '(8 − 3) + (8 − 5) + (8 − 8) = 5 + 3 + 0 = 8 padding tokens.',
    reflection: 'Write a test that would catch a missing mask in a sequence model you might build.',
  },
  {
    id: 'l25-shortcuts',
    title: '25.5 · Shortcut learning and split contamination',
    sections: ['The model learns what works', 'Spurious tokens', 'Contaminated splits', 'Probing for shortcuts', 'Demonstrate understanding'],
    skill: 'Detect shortcut learning and contamination in sequence datasets.',
    prerequisite: 'Lessons 25.1–25.4; leakage (Lab 06).',
    paragraphs: [
      'A model minimizes loss with whatever signal is easiest. If an irrelevant artifact correlates with the label in the training data, the model may learn the artifact instead of the intended rule — **shortcut learning**.',
      'In the playground, turning on the shortcut inserts a "[bot]" token into 90% of positive training examples — like an automated reporter that only posts about real incidents. The pooled model reaches about 95% training accuracy by learning "[bot] → incident" and falls to about 60% on clean test data — no better than always answering "no incident".',
      'Sequence data are prone to **contamination**: the same template message in train and test, overlapping windows cut from one long log, duplicated documents, or future events leaking into past windows. Split by source and time (Lab 06) and deduplicate before splitting.',
      'Probe for shortcuts: evaluate on data where the suspected artifact is removed or randomized; inspect the most influential tokens (the embedding plot is a start); try an adversarial test set built by domain experts. Improvement that vanishes under these probes was never real.',
      'You have completed this lab when you can: embed tokens and track shapes; explain why pooling ignores order and use it as a baseline; compute an RNN forward pass and explain BPTT; pad and mask correctly; and detect shortcut learning and contamination. The Python challenge implements embeddings, masking and an RNN forward pass.',
    ],
    formula: 'test on data without the artifact: a large drop ⇒ the model relied on a shortcut',
    experiment: 'Turn on the shortcut and train the pooled model, then the RNN. Compare training and clean-test accuracy for both. Does the RNN resist the shortcut?',
    question: 'A model scores 95.3% on training data containing an artifact and 59.7% on clean test data, where always predicting the majority class scores 59.7%. By how many percentage points does it beat that baseline on clean data?',
    answer: 0,
    explanation: '59.7 − 59.7 = 0 points: all of its apparent skill came from the shortcut. These are the playground’s own numbers.',
    reflection: 'Name one artifact in your data that could correlate with the label for the wrong reason. How would you test for it?',
  },
]

export const sources = [
  { title: 'Dive into Deep Learning · Chapters 9–10: recurrent neural networks', url: 'https://d2l.ai/chapter_recurrent-neural-networks/index.html' },
  { title: 'Olah · Understanding LSTM networks', url: 'https://colah.github.io/posts/2015-08-Understanding-LSTMs/' },
  { title: 'Geirhos et al. (2020) · Shortcut learning in deep neural networks', url: 'https://arxiv.org/abs/2004.07780' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
