import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l13-variance',
    title: '13.1 · Averaging away variance',
    sections: ['One tree is a noisy estimate', 'The wisdom of many estimates', 'Correlation limits the gain', 'The formula', 'Put it into practice'],
    skill: 'Explain how averaging reduces variance and why correlation between models limits it.',
    prerequisite: 'Lab 12 (decision trees); variance of averages (Lab 04); bias–variance (Lab 07).',
    paragraphs: [
      'A deep decision tree has low bias but high variance: train it on a slightly different sample and its boundary changes a lot (Lab 12). Each tree is like one noisy measurement of the true boundary.',
      'Lab 04 showed that the mean of n independent measurements has variance σ²/n. If we could train many trees on **independent** datasets and average their predictions, the noise would shrink while the (low) bias stayed the same.',
      'Trees trained on the same data are not independent; they make similar mistakes. If every pair of trees has prediction correlation ρ, averaging cannot remove the shared part. At ρ = 1 all trees are identical and averaging does nothing.',
      'The variance of the average of T predictors, each with variance σ² and pairwise correlation ρ, is `ρσ² + (1 − ρ)σ²/T`. As T grows the second term vanishes, leaving ρσ². With ρ = 0.3 and σ² = 1, 10 trees give 0.3 + 0.07 = 0.37; infinitely many give 0.3.',
      'So an ensemble needs two things: many models (large T) and models that disagree (small ρ) while each stays reasonably accurate. Bagging and random forests are recipes for producing exactly such trees.',
    ],
    formula: 'Var(average of T) = ρσ² + (1 − ρ)σ²/T',
    experiment: 'Compare the three small tree plots: how different are they? Then read the mean tree correlation ρ and plug it into the formula for 30 trees.',
    question: 'σ² = 1, ρ = 0.3, T = 10. What is ρσ² + (1 − ρ)σ²/T?',
    answer: 0.37,
    explanation: '0.3 + 0.7/10 = 0.37. With infinitely many trees it would approach 0.3 — the floor set by correlation.',
    reflection: 'In your own words, why can adding more of the same kind of model never remove all the variance?',
  },
  {
    id: 'l13-bagging',
    title: '13.2 · Bagging: bootstrap aggregating',
    sections: ['Fake new datasets', 'Train one tree per sample', 'Aggregate', 'Which models benefit', 'Cost'],
    skill: 'Implement bagging with bootstrap samples and aggregate tree predictions.',
    prerequisite: 'Lesson 13.1; the bootstrap (Lab 05).',
    paragraphs: [
      'We cannot collect 100 independent datasets, but the bootstrap from Lab 05 can imitate them: draw n rows with replacement from the n training rows. Each bootstrap sample repeats some rows and omits others, so each tree sees a somewhat different dataset.',
      'Train one deep tree on each of T bootstrap samples. Deep trees are appropriate here: we want low bias and are about to remove much of the variance by averaging.',
      'To predict, average the trees\' class-1 fractions (or take a majority vote); for regression, average their numbers. This is **bagging** — **b**ootstrap **agg**regat**ing** (Breiman, 1996).',
      'Bagging helps high-variance, low-bias models like deep trees a lot. It does little for stable models such as linear regression, whose fits barely change between bootstrap samples — averaging nearly identical lines gives the same line.',
      'Training costs T times one tree, but the trees are independent, so they train in parallel. Prediction also costs T tree evaluations — usually cheap. The ensemble is less readable than one tree: there is no single path to show.',
    ],
    formula: 'for t = 1…T: D_t = bootstrap(D); h_t = tree(D_t)     ŷ(x) = (1/T) Σ h_t(x)',
    experiment: 'Choose "Both (bagging)". Set trees to 1, then 5, 30 and 100. Watch the boundary smooth out and the validation curve rise and level off.',
    question: 'A bootstrap sample of size n = 4 is drawn with replacement. What is the probability that a particular row is never drawn? (Four decimals.)',
    answer: 0.3164, tolerance: 0.0001,
    explanation: '(1 − 1/4)⁴ = 0.75⁴ ≈ 0.3164. For large n this approaches e⁻¹ ≈ 0.368.',
    reflection: 'Which model in your toolbox is unstable enough that bagging could help? Which is stable enough that it would not?',
  },
  {
    id: 'l13-random',
    title: '13.3 · Random forests: decorrelating the trees',
    sections: ['Bagged trees look alike', 'Random feature subsets', 'How many features', 'The effect on ρ', 'Defaults that work'],
    skill: 'Explain how random feature selection decorrelates trees and choose max_features.',
    prerequisite: 'Lessons 13.1–13.2.',
    paragraphs: [
      'If one feature is very strong, almost every bagged tree splits on it first. The trees then share the same top-level structure and make correlated errors: ρ stays high and averaging helps less than hoped.',
      'A **random forest** adds a second source of randomness: at **each split**, the tree may only choose among a random subset of the features. Sometimes the strong feature is unavailable, so the tree finds another good question. Different trees develop genuinely different structures.',
      'The subset size `max_features` is the key hyperparameter. Common defaults: √p for classification and p/3 for regression, where p is the number of features. Smaller subsets decorrelate more but make each tree weaker; the best value is found by validation.',
      'With only two features, the playground\'s "one random feature" option is the most extreme choice. Compare the reported mean tree correlation with bagging: it drops, and with enough trees the ensemble usually matches or beats the bagged one.',
      'Random forests are one of the most reliable off-the-shelf models for tabular data: few hyperparameters, little sensitivity to them, no feature scaling, and good accuracy. They are a strong baseline before trying anything more complex.',
    ],
    formula: 'at each split: choose best (feature, threshold) among a random subset of m ≤ p features (m ≈ √p)',
    experiment: 'Record ρ and validation accuracy with "Both (bagging)" and with "One random feature" at 100 trees, depth 10. Try two datasets.',
    question: 'A classification dataset has p = 16 features. What is the common default max_features = √p?',
    answer: 4,
    explanation: '√16 = 4 features are considered at each split.',
    reflection: 'If your data had one dominant feature, what would bagged trees look like? How would a random forest differ?',
  },
  {
    id: 'l13-oob',
    title: '13.4 · Out-of-bag evaluation',
    sections: ['Each tree skips a third of the data', 'Predict with the trees that did not see a row', 'An almost-free validation estimate', 'Caveats', 'Use it well'],
    skill: 'Compute and interpret out-of-bag accuracy.',
    prerequisite: 'Lessons 13.1–13.3; cross-validation (Lab 06).',
    paragraphs: [
      'Each bootstrap sample leaves out about 37% of the training rows ((1 − 1/n)ⁿ ≈ e⁻¹). For every tree, those **out-of-bag** (OOB) rows are genuinely unseen data.',
      'For each training row, collect predictions only from the trees that did not train on it — roughly a third of the forest — and average them. Compare with the row\'s label. The fraction correct across all rows is the **OOB accuracy**.',
      'This gives a validation-like estimate without holding out any data or running cross-validation: every row is used for training some trees and evaluating others. The playground plots OOB accuracy next to true validation accuracy; they track each other closely once there are enough trees.',
      'Caveats: with few trees, some rows have no OOB predictions; OOB predictions use only about a third of the trees, so they are slightly pessimistic; and OOB does nothing about group or time leakage — rows from the same machine in different bootstrap samples still leak (Lab 06).',
      'Use OOB accuracy to tune the number of trees and max_features quickly. Still keep an untouched test set for the final report.',
    ],
    formula: 'OOB prediction for row i = average over trees t with i ∉ D_t     OOB accuracy = mean(correct)',
    experiment: 'Compare the OOB and validation curves as trees are added. Where do they differ most? Turn bootstrap off and explain why OOB disappears.',
    question: 'With bootstrap samples of a large dataset, roughly what fraction of trees did NOT see a given row? (Three decimals, e⁻¹.)',
    answer: 0.3679, tolerance: 0.001,
    explanation: 'Each tree omits a given row with probability (1 − 1/n)ⁿ → e⁻¹ ≈ 0.368, so about 37% of trees can evaluate it.',
    reflection: 'When would OOB accuracy be misleading for your data?',
  },
  {
    id: 'l13-limits',
    title: '13.5 · Tuning, importance and limits',
    sections: ['What to tune', 'More trees never overfits — mostly', 'Feature importance again', 'Where forests struggle', 'Demonstrate understanding'],
    skill: 'Tune a random forest sensibly, interpret its importances critically and recognise its limits.',
    prerequisite: 'Lessons 13.1–13.4; feature importance (Lab 12).',
    paragraphs: [
      'Tune, in order of impact: max_features; the minimum leaf size or maximum depth (to control each tree); then the number of trees until the validation curve flattens. Forests are forgiving — defaults are often within a point or two of the best.',
      'Adding trees reduces variance and does not increase overfitting: the curve rises and flattens. Beyond the plateau more trees only cost time and memory. Each tree can still overfit on its own, which is why leaf size matters on noisy data.',
      'Impurity-based importances inherit the biases from Lab 12, averaged over trees. Permutation importance on validation data remains the more trustworthy choice. With correlated features, importance is shared between them in ways that do not reflect causal relevance (Lab 05).',
      'Forests cannot extrapolate beyond the range of the training targets (every leaf predicts an average of seen values), struggle with very sparse high-dimensional data like text, and produce large models. Their probabilities are often under-confident near 0 and 1; calibrate if you need them (Lab 09).',
      'You have completed this lab when you can: explain the variance formula for averages; implement bagging and a random forest; compute OOB accuracy; and justify when a forest is — or is not — the right tool. The Python challenge implements a forest around a provided tree.',
    ],
    formula: 'defaults: many trees (100–500), max_features ≈ √p, deep trees with a minimum leaf size',
    experiment: 'At depth 1 (stumps), does adding trees help much? At depth 14? Explain using bias and variance.',
    question: 'A forest has 200 trees. On average, about how many trees provide an out-of-bag prediction for a given training row? (Nearest whole number, using e⁻¹ ≈ 0.368.)',
    answer: 74, tolerance: 0.6,
    explanation: '200 × 0.368 ≈ 73.6, so about 74 trees.',
    reflection: 'Would a random forest be your baseline for a tabular problem you know? What would make you choose something else?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 8.2: bagging and random forests', url: 'https://www.statlearning.com/' },
  { title: 'Breiman (2001) · Random Forests', url: 'https://doi.org/10.1023/A:1010933404324' },
  { title: 'scikit-learn · Forests of randomized trees', url: 'https://scikit-learn.org/stable/modules/ensemble.html#forests-of-randomized-trees' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
