export const lessons = [
  {
    id: 'l41-update',
    title: '41.1 · Parameters as uncertain quantities',
    sections: ['A different question', 'Prior × likelihood', 'Conjugacy: the Beta–binomial', 'Sequential updating', 'Put it into practice'],
    skill: 'Compute a posterior from a prior and a likelihood, and update a Beta prior with binomial data.',
    prerequisite: 'Core labs 01–33, especially Bayes’ rule (Lab 04) and maximum likelihood (Lab 05); Labs 39–40.',
    paragraphs: [
      'Maximum likelihood asks: which parameter value makes the data most probable? The Bayesian approach asks a different question: given the data, **how plausible is each parameter value?** It treats the unknown parameter θ as uncertain and describes that uncertainty with a probability distribution.',
      'Bayes’ rule for parameters: p(θ | data) = p(data | θ) · p(θ) / p(data). The **prior** p(θ) encodes what you believed before; the **likelihood** p(data | θ) is the same function maximum likelihood uses; the **posterior** p(θ | data) is the result. The denominator p(data) only rescales, so posterior ∝ likelihood × prior.',
      'For a coin with P(heads) = θ, the likelihood of h heads and t tails is θ^h(1 − θ)^t. Choose a **Beta(a, b)** prior, whose density is proportional to θ^(a−1)(1 − θ)^(b−1). Multiply: the posterior is proportional to θ^(a+h−1)(1 − θ)^(b+t−1) — another Beta, **Beta(a + h, b + t)**. A prior that stays in the same family after updating is **conjugate**.',
      'The prior acts like imaginary earlier flips: Beta(a, b) behaves like a − 1 heads and b − 1 tails already seen. Updating one flip at a time or all at once gives the same posterior — today’s posterior is tomorrow’s prior.',
      'Procedure: write the likelihood; choose a prior that honestly states what was known (and check how much it matters); multiply and normalize; report the posterior, not just a single number.',
    ],
    formula: 'p(θ | D) ∝ p(D | θ) p(θ)     Beta(a, b) + (h heads, t tails) → Beta(a + h, b + t)',
    derivation: {
      title: 'Derive the Beta–binomial update',
      intro: 'Prior density ∝ θ^(a−1)(1 − θ)^(b−1); likelihood θ^h(1 − θ)^t.',
      steps: [
        { prompt: 'Multiply them. Write the log of the unnormalized posterior in terms of θ, a, b, h and t.', answer: '(a+h-1)*log(θ) + (b+t-1)*log(1-θ)', show: '`(a + h − 1)·log θ + (b + t − 1)·log(1 − θ)`', vars: { θ: [0.05, 0.95], a: [1, 5], b: [1, 5], h: [0, 10], t: [0, 10] } },
        { prompt: 'This is the log of a Beta(A, B) density up to a constant. With a = 2, b = 2, h = 7 and t = 3, what is A?', number: 9, show: '`A = a + h = 9`' },
        { prompt: 'And B?', number: 5, show: '`B = b + t = 5`' },
        { prompt: 'The mean of Beta(A, B) is A/(A + B). Evaluate it. (Four decimals.)', number: 9 / 14, tolerance: 1e-4, show: '`9/14 ≈ 0.6429`', why: 'Between the prior mean 0.5 and the observed proportion 0.7 — pulled toward 0.5 by the prior.' },
      ],
      result: 'The posterior mean is a weighted average of the prior mean and the data proportion; the weights are the prior’s pseudo-count a + b and the number of flips n.',
    },
    experiment: 'In the Beta–binomial view, choose the strong fairness prior and a true P(heads) of 0.8. How many flips does the posterior need before its mean passes 0.7? Repeat with the uniform prior.',
    question: 'Prior Beta(2, 2); you observe 7 heads and 3 tails. What is the posterior mean? (Four decimals.)',
    answer: 0.6429, tolerance: 0.001,
    explanation: 'Posterior Beta(9, 5), mean 9/14 ≈ 0.643. Maximum likelihood would say 0.7.',
    reflection: 'Describe a quantity in your work where you have real prior knowledge before seeing any data. How strong is it, in “pseudo-observations”?',
  },
  {
    id: 'l41-summaries',
    title: '41.2 · Summaries, intervals and predictions',
    sections: ['Posterior mean and MAP', 'Credible intervals', 'The posterior predictive', 'Zero counts', 'Prior sensitivity'],
    skill: 'Summarize a posterior with its mean, mode and credible interval, and make posterior-predictive probabilities.',
    prerequisite: 'Lesson 41.1; confidence intervals (Lab 05).',
    paragraphs: [
      'A posterior is a whole distribution. Common summaries: the **posterior mean** (minimizes expected squared error), the **posterior mode** or **MAP** estimate (the single most plausible value), and the **median**. For Beta(A, B): mean A/(A + B), mode (A − 1)/(A + B − 2) when A, B > 1.',
      'A **95% credible interval** contains 95% of the posterior probability: given the model and prior, θ lies in it with probability 0.95. This is the statement people often wrongly attach to a frequentist confidence interval (Lab 05), whose 95% refers to the procedure over repeated samples.',
      'Predictions should average over the uncertainty rather than plug in one estimate. The **posterior predictive** P(next flip is heads | data) = ∫ θ · p(θ | data) dθ = A/(A + B) — the posterior mean. For more complex models, plug-in predictions are overconfident because they ignore parameter uncertainty.',
      'With a uniform prior and 5 successes in 5 trials, maximum likelihood says the next trial succeeds with probability 1. The posterior predictive says (5 + 1)/(5 + 2) = 6/7 — **Laplace’s rule of succession**. It is also why Lab 11 added one to every word count: Laplace smoothing is a posterior mean.',
      'Always check **prior sensitivity**: repeat the analysis with a few reasonable priors. If conclusions change, the data are not yet decisive — say so. If they do not, the prior hardly matters and the posterior is driven by data.',
    ],
    formula: 'Beta(A, B): mean A/(A+B), mode (A−1)/(A+B−2)     P(next = 1 | D) = A/(A+B)',
    derivation: {
      title: 'Find the MAP estimate of a Beta posterior',
      steps: [
        { prompt: 'The log density of Beta(A, B) is (A − 1)·log θ + (B − 1)·log(1 − θ) + const. Differentiate with respect to θ.', answer: '(A-1)/θ - (B-1)/(1-θ)', show: '`(A − 1)/θ − (B − 1)/(1 − θ)`', vars: { A: [1.5, 10], B: [1.5, 10], θ: [0.05, 0.95] } },
        { prompt: 'Setting it to zero gives the mode. For A = 9 and B = 5, what is the MAP estimate? (Four decimals.)', number: 8 / 12, tolerance: 1e-4, show: '`8/12 ≈ 0.6667`' },
        { prompt: 'With a uniform prior Beta(1, 1) and h heads in n flips, write the MAP estimate in terms of h and n.', answer: 'h/n', show: '`h/n` — maximum likelihood', vars: { h: [1, 9], n: [10, 20] }, why: 'A flat prior changes nothing about where the peak is.' },
      ],
      result: 'MAP equals maximum likelihood under a flat prior; any other prior shifts the peak toward what the prior favours.',
    },
    experiment: 'Set the flips to 0, then to 3 with the uniform prior. Compare maximum likelihood, the posterior mean and the credible interval. Which one would you trust with 3 flips?',
    question: 'Uniform prior; 5 successes in 5 trials. What is the posterior-predictive probability that the next trial succeeds? (Three decimals.)',
    answer: 0.857, tolerance: 0.001,
    explanation: 'Beta(6, 1): (5 + 1)/(5 + 2) = 6/7 ≈ 0.857 — confident, but not certain.',
    reflection: 'When did a single estimate from very little data mislead you? What would the posterior have said?',
  },
  {
    id: 'l41-map',
    title: '41.3 · Regularization is a prior',
    sections: ['Gaussian prior → ridge', 'Laplace prior → lasso', 'What λ means', 'MAP is not the whole posterior', 'Choosing the prior'],
    skill: 'Show that ridge and lasso are MAP estimates and interpret the regularization strength as a prior.',
    prerequisite: 'Lessons 41.1–41.2; ridge and lasso (Lab 07).',
    paragraphs: [
      'Linear regression with Gaussian noise: y = wᵀx + ε, ε ~ N(0, σ²). Put a Gaussian prior on each weight: w ~ N(0, τ²). The negative log posterior is (1/(2σ²)) Σ (yᵢ − wᵀxᵢ)² + (1/(2τ²)) ‖w‖² + const.',
      'Multiply by 2σ²: minimizing it is minimizing Σ (yᵢ − wᵀxᵢ)² + (σ²/τ²)‖w‖² — **ridge regression** with **λ = σ²/τ²**. In precision form (α = 1/τ², β = 1/σ²), λ = α/β. The ridge solution is the MAP estimate.',
      'A **Laplace** prior, p(w) ∝ exp(−|w|/b), gives the penalty ‖w‖₁/b: the **lasso**. Its sharp peak at zero is why lasso sets weights exactly to zero (Lab 07).',
      'So λ has a meaning: a large λ says “I believe weights are small compared with the noise”. Choosing λ by cross-validation is choosing the prior by predictive performance. The evidence (Lesson 41.5) offers another route without a validation set.',
      'MAP is one point of the posterior. It is not invariant to reparameterization, ignores how wide the posterior is, and can sit in an atypical spot in high dimensions. Bayesian linear regression (next lesson) keeps the whole posterior.',
    ],
    formula: '−log p(w | D) = (1/2σ²) Σ (y − wᵀx)² + (1/2τ²) ‖w‖² + c   ⇒   ridge with λ = σ²/τ² = α/β',
    derivation: {
      title: 'Derive the one-weight MAP estimate',
      intro: 'One weight w, no intercept, data sums Sxy = Σ xᵢyᵢ and Sxx = Σ xᵢ², noise variance s2, prior variance t2.',
      steps: [
        { prompt: 'The negative log posterior is (Syy − 2w·Sxy + w²·Sxx)/(2·s2) + w²/(2·t2). Differentiate with respect to w.', answer: '(-2*Sxy + 2*w*Sxx)/(2*s2) + w/t2', show: '`(w·Sxx − Sxy)/s2 + w/t2`', vars: { w: [-2, 2], Sxy: [-5, 5], Sxx: [1, 10], s2: [0.2, 2], t2: [0.2, 3] } },
        { prompt: 'Solve for the MAP weight.', answer: 'Sxy/(Sxx + s2/t2)', show: '`w = Sxy / (Sxx + s2/t2)` — ridge with λ = s2/t2', vars: { Sxy: [-5, 5], Sxx: [1, 10], s2: [0.2, 2], t2: [0.2, 3] } },
        { prompt: 'With Sxy = 12, Sxx = 10, noise variance 1 and prior variance 0.5: evaluate the MAP weight.', number: 1, show: '`12 / (10 + 2) = 1`', why: 'Least squares would give 1.2; the prior shrinks it.' },
      ],
      result: 'The prior adds s2/t2 to the denominator: the less you trust large weights (small t2), the more you shrink.',
    },
    experiment: 'In the Bayesian regression view with the degree-9 polynomial and 6 points, toggle the maximum-likelihood fit. Then move α from 0.0001 to 10. What happens to the posterior mean?',
    question: 'Noise standard deviation 0.5 and prior standard deviation 2. What ridge λ = σ²/τ² does this prior correspond to?',
    answer: 0.0625, tolerance: 1e-6,
    explanation: 'σ² = 0.25 and τ² = 4, so λ = 0.25/4 = 0.0625.',
    reflection: 'Which regularization strength have you chosen before without thinking about it? What prior belief did it encode?',
  },
  {
    id: 'l41-blr',
    title: '41.4 · Bayesian linear regression',
    sections: ['The full Gaussian posterior', 'Predictive uncertainty', 'Two sources of uncertainty', 'Sampling functions', 'Where this leads'],
    skill: 'Compute the posterior and predictive distribution of Bayesian linear regression and explain its uncertainty.',
    prerequisite: 'Lessons 41.1–41.3; features and matrices (Labs 03, 07).',
    paragraphs: [
      'With features φ(x), prior w ~ N(0, α⁻¹I) and noise precision β, the posterior over weights is Gaussian: **N(m, S)** with S⁻¹ = αI + βΦᵀΦ and m = βSΦᵀy. The mean m is the ridge solution; S describes how uncertain each direction of weight space still is.',
      'For a new input, the predictive distribution is Gaussian with mean mᵀφ(x) and variance **1/β + φ(x)ᵀSφ(x)**. The first term is the irreducible noise; the second is uncertainty about the weights, large where the data say little about φ(x).',
      'In the playground, the band is narrow near observations and wide in gaps and beyond the data. Adding data shrinks the weight uncertainty toward zero, but the band never becomes narrower than the noise. A plug-in prediction (only m) would show the same width everywhere — overconfident exactly where it matters.',
      'Drawing w from N(m, S) and plotting φ(x)ᵀw gives functions that agree where the data constrain them and disagree elsewhere. This picture — a distribution over functions — leads directly to Gaussian processes (Lab 42).',
      'The cost of this exactness: a d × d matrix to invert. With millions of weights (neural networks) the posterior is intractable, and approximations — Laplace, variational inference (Lab 44), ensembles (Lab 60) — take over.',
    ],
    formula: 'S⁻¹ = αI + βΦᵀΦ,   m = βSΦᵀy     p(y* | x*, D) = N(mᵀφ*, 1/β + φ*ᵀSφ*)',
    derivation: {
      title: 'One weight, no intercept',
      intro: 'Features φ(x) = x, prior precision α, noise precision β, data sums Sxx = Σx², Sxy = Σxy.',
      steps: [
        { prompt: 'Posterior precision S⁻¹ = α + β·Sxx. Write the posterior variance S.', answer: '1/(α + β*Sxx)', show: '`1/(α + β·Sxx)`', vars: { α: [0.1, 5], β: [0.5, 10], Sxx: [0.5, 10] } },
        { prompt: 'Write the posterior mean m = β·S·Sxy.', answer: 'β*Sxy/(α + β*Sxx)', show: '`β·Sxy/(α + β·Sxx)`', vars: { α: [0.1, 5], β: [0.5, 10], Sxx: [0.5, 10], Sxy: [-5, 5] } },
        { prompt: 'Write the predictive variance at a new input x.', answer: '1/β + x^2/(α + β*Sxx)', show: '`1/β + x²/(α + β·Sxx)`', vars: { α: [0.1, 5], β: [0.5, 10], Sxx: [0.5, 10], x: [-3, 3] }, why: 'The weight uncertainty grows with x²: far from the origin, a wrong slope matters more.' },
        { prompt: 'With α = 1, β = 4, Sxx = 2: predictive variance at x = 3? (Four decimals.)', number: 0.25 + 9 / 9, tolerance: 1e-4, show: '`0.25 + 9/9 = 1.25`' },
      ],
      result: 'More data (larger Sxx) shrinks only the second term; the noise term 1/β remains.',
    },
    experiment: 'Start with 0 observations and add them one by one. Where does the band shrink first? What happens to the sampled functions beyond the last observation?',
    question: 'The noise standard deviation is 0.25, and at some input the weight uncertainty contributes variance 0.0225. What is the predictive standard deviation there? (Four decimals.)',
    answer: 0.2915, tolerance: 0.001,
    explanation: 'Variances add, standard deviations do not: 0.25² + 0.0225 = 0.0625 + 0.0225 = 0.085, and √0.085 ≈ 0.2915.',
    reflection: 'Where would honest predictive uncertainty change a decision in your work?',
  },
  {
    id: 'l41-evidence',
    title: '41.5 · Model evidence and Occam’s razor',
    sections: ['Probability of the data under a model', 'Why complexity is penalized', 'Bayes factors', 'Empirical Bayes and its limits', 'Demonstrate understanding'],
    skill: 'Compare models by their evidence and explain the automatic complexity penalty.',
    prerequisite: 'Lessons 41.1–41.4; model selection (Labs 06–07).',
    paragraphs: [
      'The denominator we kept ignoring, p(D | model) = ∫ p(D | θ) p(θ) dθ, is the **evidence** or **marginal likelihood**: how probable the data were under the model, averaging over its prior. It is a score for the whole model, not for one parameter value.',
      'A complex model can fit many datasets, so it must spread its prior probability thinly across them; a simple model concentrates probability on few datasets. If the data are among the simple model’s few, it wins. This is **Occam’s razor** made quantitative, with no validation set.',
      'For polynomial regression on the sine data, the log evidence rises until degree 3 and then declines, while training error keeps falling; degree 3 also has the lowest test error. The ratio of evidences for two models is the **Bayes factor**: a factor of 10 or more is conventionally strong evidence.',
      'Choosing hyperparameters such as α and β by maximizing the evidence is **empirical Bayes** (type-II maximum likelihood); Gaussian processes use it to tune kernels (Lab 42). Cautions: the evidence depends heavily on the prior (an absurdly vague prior makes any model look bad), and it assumes one of the models is sensible. Cross-validation remains the robust default for predictive goals.',
      'You have completed this lab when you can: compute and summarize posteriors with conjugate priors; distinguish credible from confidence intervals; use posterior predictives; derive ridge and lasso as MAP estimates; compute the Bayesian linear regression posterior and predictive variance; and compare models by their evidence while stating its limits. The Python challenge implements all of these.',
    ],
    formula: 'p(D | M) = ∫ p(D | θ, M) p(θ | M) dθ     Bayes factor = p(D | M₁) / p(D | M₂)',
    derivation: {
      title: 'Compare “fair coin” with “unknown bias” after 3 heads in 3 flips',
      steps: [
        { prompt: 'Evidence of the fair-coin model: P(HHH | θ = 0.5).', number: 0.125, show: '`0.5³ = 0.125`' },
        { prompt: 'Evidence of the unknown-bias model with a uniform prior: ∫₀¹ θ³ dθ.', number: 0.25, show: '`1/4 = 0.25`' },
        { prompt: 'Bayes factor (unknown bias : fair).', number: 2, show: '`2`', why: 'Mild evidence for bias. Maximum likelihood would say the bias model fits infinitely better (θ = 1 gives probability 1).' },
      ],
      result: 'The flexible model pays for its flexibility: it spreads probability over all θ, so 3 heads is only twice as likely under it.',
    },
    experiment: 'In “Model evidence”, switch between 10, 15 and 30 observations. Does the degree with the highest evidence change? Compare with the degree of lowest test error.',
    question: '10 heads in 10 flips. Evidence under a fair coin is 1/1024; under a uniform prior on the bias it is 1/11. What is the Bayes factor in favour of a biased coin? (One decimal.)',
    answer: 93.1, tolerance: 0.1,
    explanation: '(1/11)/(1/1024) = 1024/11 ≈ 93.1: strong evidence for bias.',
    reflection: 'When would you prefer the evidence to cross-validation for choosing a model, and when not?',
  },
]

export const sources = [
  { title: 'Bishop · Pattern Recognition and Machine Learning, ch. 2–3 (free PDF)', url: 'https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/' },
  { title: 'MacKay · Information Theory, Inference, and Learning Algorithms, ch. 28 Occam’s razor (free book)', url: 'https://www.inference.org.uk/itila/book.html' },
  { title: 'Gelman et al. · Bayesian Data Analysis, 3rd ed. (free PDF)', url: 'http://www.stat.columbia.edu/~gelman/book/' },
  { title: 'Murphy · Probabilistic Machine Learning: An Introduction, ch. 4 and 11 (free PDF)', url: 'https://probml.github.io/pml-book/book1.html' },
]
