// Lesson order for Lab 16: each paragraph followed by what makes it concrete (see LessonFlow).
export const blocks = {
  'l16-frame': [
    { p: 0 }, { p: 1 },
    { figure: 'KnownAtPredictionTime', caption: 'Which candidate features exist at the moment the prediction is needed?' },
    { cell: 0 }, { cell: 2 },
    { p: 2 },
    { figure: 'MaeVersusRmse', caption: 'The same errors summarized two ways.' },
    { predict: { prompt: 'Predictions [100, 90, 60] for actual durations [80, 90, 70]. What is the MAE in seconds?', answer: 10, explain: '(20 + 0 + 10)/3 = 10.' } },
    { cell: 1 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l16-features': [
    { p: 0 },
    { figure: 'PerMbBySharedRunner', caption: 'Cache-miss builds: duration against size, coloured by runner type.' },
    { cell: 0 },
    { p: 1 },
    { predict: { prompt: 'A job of 25 MB runs on a shared runner (shared = 1) with a cache hit (cache = 1). What is its value for size × shared?', answer: 25, explain: '25 × 1 = 25. Its size × (1 − cache) would be 0.' } },
    { p: 2 }, { p: 3 },
    { figure: 'FeatureToggleCV', caption: 'Cross-validated error as engineered features are added.' },
    { cell: 1 },
    { p: 4 },
    { math: true },
  ],
  'l16-compare': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'ModelBoard', caption: 'Five models, one configuration each, on the same five folds.' },
    { cell: 0 }, { cell: 1 },
    { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l16-errors': [
    { p: 0 }, { p: 1 }, { p: 2 },
    { figure: 'SegmentErrors', caption: 'Out-of-fold predictions for every development job, and their errors by segment.' },
    { cell: 0 },
    { predict: { prompt: 'A segment of 5 jobs has out-of-fold absolute errors 2, 4, 6, 8 and 30 s. What is its MAE?', answer: 10, explain: '(2 + 4 + 6 + 8 + 30)/5 = 10 — one bad case doubles the segment’s error.' } },
    { p: 3 }, { p: 4 },
    { math: true },
    { ladder: 'oof' },
  ],
  'l16-test': [
    { p: 0 }, { p: 1 },
    { figure: 'FinalTestOnce', caption: 'The locked test set. Open it once, for the model you already chose.' },
    { cell: 0 },
    { p: 2 }, { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l16-report': [
    { p: 0 }, { p: 1 },
    { figure: 'ReportChecklist', caption: 'What a reproducible report contains.' },
    { cell: 0 },
    { p: 2 }, { p: 3 }, { p: 4 },
    { math: true },
  ],
  'l16-project': [
    { p: 0 },
    { p: 1 },
    { cell: 0 },
    { cell: 1 },
    { bridge: { label: 'Worked answer for “Your features” (open after trying)', title: '', body: [
      'Divide by the parallel factor first, then split the per-test time into its two parts:',
      '`factor = np.where(dev.parallel == 1, 4, 1)` · `dev["tests_eff"] = dev.tests / factor` · `dev["db_tests_eff"] = dev.tests * dev.db_share / factor` · `my_cols = ["tests_eff", "db_tests_eff"]`',
      'That gives CV MAE 2.61 s (±0.09), and `LinearRegression().fit(dev[my_cols], dev.seconds)` learns weights `[0.05 0.4]` and intercept 5.1 — the recipe.',
    ] } },
    { p: 2 },
    { predict: { prompt: 'Your engineered linear model scores 2.61 s. What MAE, to one decimal, does the recipe written as a rule get on the same development suites?', answer: 2.6, tolerance: 0.051, explain: 'About 2.6 s — the same as the model, because the model learned the recipe. With no training, no features to fit and nothing to drift, the rule is the better tool here.' } },
    { cell: 2 },
    { p: 3 },
    { cell: 3 },
    { p: 4 },
    { cell: 4 },
    { p: 5 },
    { cell: 5 },
    { bridge: { label: 'Reference results for stage 3 (open after writing your decision)', title: '', body: [
      'With the locked split above (`random_state=0`) and the same 5 folds: predicting the mean scores a CV MAE of 67.8; linear regression on all ten columns 43.9 (±0.8); ridge regression with its penalty chosen by `RidgeCV` 43.9; a random forest (300 trees) 47.8 (±1.4); gradient boosting with default settings 48.0 (±1.5); linear regression on body-mass index alone 51.5.',
      'So the simplest full model is also the best here: the tree ensembles are worse, not better. A report that picks the forest because it “should” be stronger, or that reports the best of many test-set evaluations, is the mistake this lab is about.',
    ] } },
    { math: true },
  ],
}
