import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l16-frame',
    title: '16.1 · Frame the problem before touching a model',
    sections: ['A decision, not a dataset', 'Target, unit, horizon', 'What is known at prediction time', 'Success criteria', 'Lock the test set'],
    skill: 'Write a precise problem statement with a target, features available at prediction time, a baseline, a metric and a success threshold.',
    prerequisite: 'Labs 01–15, especially evaluation (Lab 06) and metrics (Lab 09).',
    paragraphs: [
      'The CI team wants to show engineers an estimated wait time when a build starts, and to route long builds to dedicated runners. The model exists to support those two decisions; everything else follows from them.',
      'Target: build duration in seconds, measured from start to finish. Unit of prediction: one build job. Prediction time: when the job is queued — so only information available then can be a feature: size, file count, cache status, runner type, language, hour. The number of failed tests, known only afterwards, is future leakage (Lab 06).',
      'Metric: **mean absolute error** (MAE) in seconds, because the display shows seconds and a 60-second miss is twice as bad as a 30-second miss, no more. Baseline: the mean duration of past builds. Success: at least 50% lower MAE than the baseline, with the improvement\'s confidence interval above zero.',
      'Before exploring anything, set aside 20% of the jobs as the **test set** and do not look at them again until the final evaluation. In real projects, prefer a time-based test set — the most recent weeks — because the model will predict future builds (Lab 06).',
      'Write this down as a one-paragraph plan. It is the yardstick for every later choice and the first section of the final report.',
    ],
    formula: 'MAE = mean(|ŷ − y|)     skill = 1 − MAE_model / MAE_baseline',
    experiment: 'Before running anything, write in the notebook: the target, the prediction moment, the features you expect to matter, and the MAE you would consider a success.',
    question: 'Predictions [30, 50, 80] for actual durations [40, 50, 60]. What is the MAE?',
    answer: 10,
    explanation: 'Absolute errors are 10, 0 and 20; their mean is 30/3 = 10 seconds.',
    reflection: 'Write the problem statement for a prediction you would like to make in your own work: decision, target, prediction moment, metric, baseline, success threshold.',
  },
  {
    id: 'l16-features',
    title: '16.2 · Feature engineering from domain knowledge',
    sections: ['Models only see columns', 'Transformations', 'Interactions', 'Categoricals', 'Engineer inside the pipeline'],
    skill: 'Create transformed, interaction and categorical features justified by domain knowledge, without leakage.',
    prerequisite: 'Lesson 16.1; polynomial features (Lab 07), one-hot encoding.',
    paragraphs: [
      'Domain knowledge says: builds on a shared runner are slower **per MB**, not by a fixed amount; a cache hit skips most of the work; shared runners are congested during office hours. A linear model given raw columns cannot express "slower per MB only on shared runners".',
      '**Transformations** reshape a feature: log(size) turns multiplicative effects into additive ones and tames long right tails. **Interactions** multiply features: `size × shared` lets a linear model learn a separate per-MB cost for shared runners; `size × (1 − cache)` lets it learn that cache misses scale with size.',
      '**Categorical** features such as language are encoded as one-hot columns: one indicator per category, dropping one when the model has an intercept (Lab 03\'s collinearity). Trees can split on the codes directly.',
      'In the playground, run the comparison with raw features, then with interactions and busy hours. The linear model improves dramatically — often overtaking the tree ensembles. Trees discover interactions automatically but approximate them with many steps; an explicit, correct feature is worth more than a more complex model.',
      'Every engineered feature must be computable at prediction time and, if it learns anything from data (a target mean per category, a scaler), be fit inside the training folds (Lab 06). Pure formulas of a row\'s own columns, like these interactions, carry no leakage risk.',
    ],
    formula: 'size×shared, size×(1 − cache), shared×busy, log(size), one-hot(language)',
    experiment: 'Record the CV MAE of all five models with raw features, then with every engineered feature. Which model gained the most? Why?',
    question: 'A job has size 40 MB, a shared runner (shared = 1) and a cache miss (cache = 0). What is its value for the feature size × (1 − cache)?',
    answer: 40,
    explanation: '40 × (1 − 0) = 40. With a cache hit it would be 0: the model can learn that cache misses cost time in proportion to size.',
    reflection: 'Name one interaction in your own domain that a domain expert would take for granted but a linear model could not learn from raw columns.',
  },
  {
    id: 'l16-compare',
    title: '16.3 · Compare models systematically',
    sections: ['Same folds for everyone', 'A small, bounded search', 'Read the spread', 'Simplicity as a tie-breaker', 'Keep a log'],
    skill: 'Compare candidate models with identical cross-validation folds and a bounded, pre-declared search.',
    prerequisite: 'Lessons 16.1–16.2; cross-validation (Lab 06), trees and ensembles (Labs 12–14).',
    paragraphs: [
      'Evaluate every candidate — baseline, linear, tree, forest, boosting — on the **same five folds** of the development data. Differences between models then reflect the models, not the luck of different splits.',
      'Declare the search before running it: a handful of models, each with a few sensible settings. An unbounded search over hundreds of configurations finds one that fits the validation folds by chance (Lab 06\'s winner\'s curse). The playground fixes one reasonable configuration per model on purpose.',
      'Report each model\'s mean CV MAE and its fold-to-fold standard deviation. A 0.5-second advantage with fold standard deviations of 3 seconds is not a meaningful difference; prefer comparing models fold by fold (paired) when the gap is small.',
      'When two models are within noise, choose the simpler, faster, more explainable one. A linear model with good features that matches boosting is easier to debug, monitor and explain to the CI team.',
      'Log every configuration you tried, including failures. The final report must say how many comparisons were made — it is part of the evidence.',
    ],
    formula: 'for each model m: CV_MAE(m) = mean_f MAE(m fit on folds ≠ f, evaluated on fold f)',
    experiment: 'With all engineered features, is the best model clearly better than the second best, given the fold standard deviations? Which one would you choose, and why?',
    question: 'Model A has CV MAE 10.4 ± 1.9 and model B 9.5 ± 0.8 (seconds, mean ± sd over folds). What is B\'s advantage in mean MAE?',
    answer: 0.9, tolerance: 0.0001,
    explanation: '10.4 − 9.5 = 0.9 seconds — smaller than A\'s fold standard deviation. Compare fold by fold, and weigh simplicity, before declaring a winner.',
    reflection: 'How would you decide, in advance, how many configurations you are allowed to try on a project?',
  },
  {
    id: 'l16-errors',
    title: '16.4 · Error analysis: where does the model fail?',
    sections: ['Averages hide failures', 'Out-of-fold predictions', 'Slice by segment', 'Turn findings into features or data', 'Know when to stop'],
    skill: 'Use out-of-fold predictions to find systematic errors by segment and act on them.',
    prerequisite: 'Lessons 16.1–16.3.',
    paragraphs: [
      'An overall MAE of 10 seconds can hide 4-second errors on small builds and 40-second errors on the largest ones — exactly the builds whose routing matters most. The average is the start of the analysis, not the end.',
      'Cross-validation gives each development row one **out-of-fold** prediction from a model that never saw it. Collect them all and you can analyse errors on the whole development set without touching the test set.',
      'Slice the errors by meaningful segments: runner type, cache status, language, size bands, time. The playground\'s table and predicted-versus-actual plot show where the chosen model is weakest. Systematic patterns (all of one group above the line) point to missing features; random scatter that grows with size points to noise the features cannot explain.',
      'Each finding suggests an action: a new feature (busy hours for shared runners), more data for a rare segment, a different loss, or a note in the report that the model is unreliable for some cases. Re-run the comparison after each change — still on development data only.',
      'Stop when the remaining errors look like noise, when improvements are within fold-to-fold variation, or when the model already meets the success criterion. Endless tuning spends time and quietly overfits the validation folds.',
    ],
    formula: 'segment MAE = mean(|ŷ_oof − y|) over rows in the segment',
    experiment: 'With raw features and the linear model, which segment has the worst error? Turn on the interaction features and look again.',
    question: 'A segment of 4 jobs has out-of-fold absolute errors 5, 15, 30 and 50 seconds. What is its MAE?',
    answer: 25,
    explanation: '(5 + 15 + 30 + 50)/4 = 25 seconds.',
    reflection: 'Which segment of your own data would you inspect first, and what would a bad result there cost?',
  },
  {
    id: 'l16-test',
    title: '16.5 · The final test and an honest decision',
    sections: ['Freeze everything', 'One evaluation', 'Uncertainty of the improvement', 'Accept, iterate or reject', 'What the number means'],
    skill: 'Evaluate a frozen pipeline once on the test set and make a justified ship/reject decision.',
    prerequisite: 'Lessons 16.1–16.4; bootstrap intervals (Lab 05).',
    paragraphs: [
      'Freeze the whole pipeline — features, model, settings — and write down the choice. Refit it on all development data. Then, and only then, compute its predictions on the test set.',
      'Compare with the baseline on the **same** test rows. Report the improvement with a bootstrap interval of the paired difference: resample test rows, recompute baseline MAE minus model MAE, and take percentiles. The playground does this with 1,000 resamples.',
      'Decide against the criterion written in Lesson 16.1. If the improvement meets it and the interval excludes zero, ship — with monitoring (Lab 30). If not, iterate on development data, knowing the next test result will be optimistic, or reject the model and report why.',
      'Opening the test set a second time after changing the model makes the second number biased: you have used the test set to choose. The playground counts openings and warns you. In real projects, keep a fresh holdout (or collect new data) for a truly final check.',
      'Rejecting a model is a legitimate, valuable outcome. "A mean-duration estimate is within 12 seconds; our best model improves this by only 1 second (CI −2 to 4); we recommend not deploying it" saves the team from maintaining a useless system.',
    ],
    formula: 'Δ = MAE_baseline − MAE_model on test; 95% CI from bootstrap of paired row differences',
    experiment: 'Choose your model, open the test set once, and write your decision in the notebook field. Then open it again with a different model and read the warning.',
    question: 'On the test set, baseline MAE is 49.2 s and the model MAE is 10.4 s. What is the improvement in seconds?',
    answer: 38.8, tolerance: 0.0001,
    explanation: '49.2 − 10.4 = 38.8 seconds — a skill of about 79% relative to the baseline.',
    reflection: 'What would make you reject a model that beats its baseline on the test set?',
  },
  {
    id: 'l16-report',
    title: '16.6 · A reproducible report',
    sections: ['Evidence someone else can check', 'What to include', 'Reproducibility', 'Limitations', 'Demonstrate understanding'],
    skill: 'Write a reproducible model report with data, method, comparisons, test result, error analysis and limitations.',
    prerequisite: 'Lessons 16.1–16.5; reproducibility (Lab 02).',
    paragraphs: [
      'A model without a report is a number nobody can check. The report is how a reviewer, a future teammate or you in six months decides whether to trust, reuse or retire it.',
      'Include: the problem statement and success criterion; the data (source, dates, rows, how the test set was separated); the features and why; every model compared with CV mean and spread; the number of configurations tried; the single test result with its interval; the error analysis; and the decision.',
      'Make it reproducible: record the code version, the random seeds, package versions and a fingerprint of the data (Lab 02). Someone with the same inputs should get the same numbers.',
      'State limitations plainly: the data are from one CI cluster; performance on new languages is unknown; errors grow for builds over 200 MB; the test set was random rather than time-based. Limitations are part of the result, not an embarrassment.',
      'You have completed this lab — and the classical ML stage — when you can take a raw tabular problem to a documented decision: framing, features, honest comparison, error analysis, a single test evaluation, and a report someone else could reproduce. The Python challenge does the same with real scikit-learn pipelines.',
    ],
    formula: 'report = problem + data + features + CV comparison + #configs + test (with CI) + errors + decision + limits',
    experiment: 'Open the generated report. Add your decision and limitations. Would a colleague be able to rerun and check it?',
    question: 'A report lists 5 models, each tried with 3 settings. How many configurations should it disclose as compared?',
    answer: 15,
    explanation: '5 × 3 = 15 configurations. Disclosing this lets readers judge how much selection optimism to expect.',
    reflection: 'Write the limitations section for a model you have built or used. What would you want a new owner to know on day one?',
  },
]

export const sources = [
  { title: 'scikit-learn · Pipelines and composite estimators (ColumnTransformer)', url: 'https://scikit-learn.org/stable/modules/compose.html' },
  { title: 'Rules of Machine Learning (Google) · best practices for ML engineering', url: 'https://developers.google.com/machine-learning/guides/rules-of-ml' },
  { title: 'Kaufman et al. (2012) · Leakage in data mining', url: 'https://doi.org/10.1145/2382577.2382579' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
