// Lab 16 runnable cells, typeset formulas and math ↔ code tables, keyed by lesson id.
// The jobs are generated with the same recipe as the playground's engine (generateJobs), drawn with
// NumPy's generator: the process is identical, the individual rows differ. Every lesson repeats the
// setup so each notebook runs on its own, and every learned step sits inside a scikit-learn pipeline.

const JOBS = `import numpy as np
import pandas as pd

def make_jobs(n=600, seed=16):
    """CI build jobs, generated by the lab's recipe. duration is the target, in seconds."""
    rng = np.random.default_rng(seed)
    size = np.exp(np.log(40) + 0.9 * rng.normal(size=n))                      # MB, long right tail
    files = np.maximum(1, np.round(size / 3 * np.exp(0.4 * rng.normal(size=n))))
    cache = (rng.random(n) < 0.6).astype(int)                                 # 1 = cache hit
    shared = (rng.random(n) < 0.5).astype(int)                                # 1 = shared runner
    lang = rng.choice(["go", "java", "python"], n)
    hour = rng.integers(0, 24, n)
    busy = ((hour >= 9) & (hour <= 17)).astype(int)
    work = np.where(cache == 1, 0.25, 1.0) * 0.9 * size * np.where(shared == 1, 1.6, 1.0)
    lang_cost = pd.Series(lang).map({"go": 0, "java": 25, "python": 10}).to_numpy()
    duration = 20 + work + lang_cost + 0.05 * files + np.where((shared == 1) & (busy == 1), 15, 0) + (5 + 0.08 * work) * rng.normal(size=n)
    duration = np.maximum(3, duration)
    failed_tests = rng.poisson(0.03 * duration)                               # known only AFTER the build
    return pd.DataFrame(dict(size_mb=size, files=files, cache_hit=cache, shared_runner=shared,
                             lang=lang, hour=hour, failed_tests=failed_tests, duration=duration))

jobs = make_jobs()
test = jobs.sample(frac=0.2, random_state=16)            # set aside FIRST; not looked at until Lesson 16.5
dev = jobs.drop(test.index)
print("development rows:", len(dev), "  test rows (locked):", len(test))`

const FEATURES = `from sklearn.model_selection import KFold, cross_val_score, cross_val_predict
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression

def engineer(df):
    """Features known when the job is queued, plus the lesson's interactions."""
    out = df[["size_mb", "files", "cache_hit", "shared_runner", "hour", "lang"]].copy()
    out["size_x_shared"] = df.size_mb * df.shared_runner
    out["size_x_miss"] = df.size_mb * (1 - df.cache_hit)
    out["shared_x_busy"] = df.shared_runner * ((df.hour >= 9) & (df.hour <= 17))
    return out

numeric = ["size_mb", "files", "cache_hit", "shared_runner", "hour", "size_x_shared", "size_x_miss", "shared_x_busy"]
prep = ColumnTransformer([("num", StandardScaler(), numeric),
                          ("lang", OneHotEncoder(drop="first"), ["lang"])])
folds = KFold(5, shuffle=True, random_state=0)            # the same five folds for every model
X_dev, y_dev = engineer(dev), dev.duration.to_numpy()
def cv_mae(model, X=X_dev):
    return -cross_val_score(model, X, y_dev, cv=folds, scoring="neg_mean_absolute_error")`

const MODELS = `from sklearn.dummy import DummyRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor
models = {                                               # declared before running: one sensible setting each
    "baseline (mean)":   make_pipeline(prep, DummyRegressor(strategy="mean")),
    "linear":            make_pipeline(prep, LinearRegression()),
    "tree (depth 6)":    make_pipeline(prep, DecisionTreeRegressor(max_depth=6, random_state=0)),
    "random forest":     make_pipeline(prep, RandomForestRegressor(n_estimators=150, min_samples_leaf=3, random_state=0)),
    "boosting":          make_pipeline(prep, HistGradientBoostingRegressor(max_iter=200, learning_rate=0.1, random_state=0)),
}`

export const extras = {
  'l16-frame': {
    formulaTex: '$$\\text{MAE} = \\frac1n\\sum_i |\\hat y_i - y_i|$$ $$\\text{skill} = 1 - \\frac{\\text{MAE}_{\\text{model}}}{\\text{MAE}_{\\text{baseline}}}$$',
    mathCode: {
      rows: [
        ['$\\frac1n\\sum_i |\\hat y_i - y_i|$', 'np.mean(np.abs(pred - y))', 'Mean absolute error, in seconds.'],
        ['$\\text{MAE}_{\\text{baseline}}$', 'DummyRegressor(strategy="mean")', 'Predict the mean duration of past builds.'],
        ['skill', '1 - mae_model / mae_baseline', 'The share of the baseline’s error removed. The success criterion is at least 0.5.'],
        ['test set', 'test = jobs.sample(frac=0.2, random_state=16)', 'Set aside before anything else is looked at.'],
      ],
    },
    notebook: {
      title: 'Lab 16.1 · Frame the problem',
      intro: 'Generate the build jobs, lock away the test set, compute the baseline the model must beat, and see what a feature from the future would do to the numbers.',
      cells: [{
        title: 'The jobs, and the locked test set',
        prose: 'The test rows are set aside in the same cell that creates the data. **Predict** which column must never be a feature.',
        code: `${JOBS}
print(dev.head().round(2).to_string())`,
      }, {
        title: 'MAE, RMSE and the baseline',
        prose: 'First the lesson’s three predictions, then the mean-duration baseline, scored by 5-fold cross-validation on development data only.',
        code: `pred, actual = np.array([100., 90, 60]), np.array([80., 90, 70])
print("MAE", np.mean(np.abs(pred - actual)), "  RMSE", round(np.sqrt(np.mean((pred - actual) ** 2)), 2))
from sklearn.dummy import DummyRegressor
from sklearn.model_selection import KFold, cross_val_score
folds = KFold(5, shuffle=True, random_state=0)
base = -cross_val_score(DummyRegressor(), dev[["size_mb"]], dev.duration, cv=folds, scoring="neg_mean_absolute_error")
print(f"baseline CV MAE: {base.mean():.1f} s  (folds {np.round(base, 1)})")
print(f"success needs MAE at most {base.mean() / 2:.1f} s")`,
      }, {
        title: 'A feature from the future',
        prose: '`failed_tests` is only known after the build ends. **Predict** what it does to cross-validated error — and why that number is worthless.',
        code: `from sklearn.linear_model import LinearRegression
queued = ["size_mb", "files", "cache_hit", "shared_runner", "hour"]
for cols, label in [(queued, "known at queue time"), (queued + ["failed_tests"], "plus failed_tests (future)")]:
    mae = -cross_val_score(LinearRegression(), dev[cols], dev.duration, cv=folds, scoring="neg_mean_absolute_error")
    print(f"{label:28s}: CV MAE {mae.mean():.1f} s")`,
      }],
    },
  },
  'l16-features': {
    formulaTex: '$$\\hat y = b + w_1 s + w_2\\,s\\,r + w_3\\,s\\,(1 - c) + \\cdots$$',
    mathCode: {
      rows: [
        ['$s,\\ r,\\ c$', 'size_mb, shared_runner, cache_hit', 'Size in MB, shared runner (1/0), cache hit (1/0).'],
        ['$s\\,r$', 'df.size_mb * df.shared_runner', 'Lets a linear model learn an extra cost per MB on shared runners.'],
        ['$s\\,(1 - c)$', 'df.size_mb * (1 - df.cache_hit)', 'Cache misses cost more the bigger the build.'],
        ['one-hot(lang)', 'OneHotEncoder(drop="first")', 'One indicator per language, minus one: the intercept already covers it.'],
        ['fit inside folds', 'make_pipeline(prep, model)', 'The scaler and encoder are fitted on each training fold only.'],
      ],
    },
    notebook: {
      title: 'Lab 16.2 · Features from domain knowledge',
      intro: 'Measure the per-MB cost on each runner type, then add interactions one at a time and watch the cross-validated error of a linear model.',
      cells: [{
        title: 'Seconds per MB, by runner',
        prose: 'Cache-miss builds only. **Predict** which runner type has the steeper slope.',
        code: `${JOBS}
miss = dev[dev.cache_hit == 0]
for shared, name in [(0, "dedicated"), (1, "shared")]:
    part = miss[miss.shared_runner == shared]
    slope = np.polyfit(part.size_mb, part.duration, 1)[0]
    print(f"{name:9s} runners: {slope:.2f} s per MB  ({len(part)} builds)")`,
      }, {
        title: 'Add features, one step at a time',
        prose: 'The same linear model and the same folds; only the columns change. **Predict** which step helps most.',
        code: `${FEATURES}
steps = [("raw columns", ["size_mb", "files", "cache_hit", "shared_runner", "hour"]),
         ("+ interactions", ["size_mb", "files", "cache_hit", "shared_runner", "hour", "size_x_shared", "size_x_miss"]),
         ("+ busy hours", numeric)]
for label, cols in steps:
    p = ColumnTransformer([("num", StandardScaler(), cols), ("lang", OneHotEncoder(drop="first"), ["lang"])])
    mae = cv_mae(make_pipeline(p, LinearRegression()))
    print(f"{label:15s}: CV MAE {mae.mean():5.1f} s ± {mae.std():.1f}")`,
        tryThis: 'Add log(size) as another column. Does it help the linear model once the interactions are there?',
      }],
    },
  },
  'l16-compare': {
    formulaTex: '$$\\text{CV-MAE}(m) = \\frac1K\\sum_{f=1}^K \\text{MAE}\\big(m_{-f},\\ \\text{fold } f\\big)$$',
    mathCode: {
      rows: [
        ['$m_{-f}$', 'model fitted on the other four folds', 'Every model is trained and scored on exactly the same splits.'],
        ['mean and spread', 'mae.mean(), mae.std()', 'Report both: a gap smaller than the spread is not evidence.'],
        ['paired difference', 'mae_a - mae_b (fold by fold)', 'Comparing on the same folds removes fold-to-fold luck.'],
      ],
    },
    notebook: {
      title: 'Lab 16.3 · Compare models on the same folds',
      intro: 'Five models, one declared setting each, the same five folds; then a fold-by-fold comparison of the two best.',
      cells: [{
        title: 'The model board',
        prose: '**Predict** whether the linear model with good features is within noise of the tree ensembles.',
        code: `${JOBS}
${FEATURES}
${MODELS}
results = {name: cv_mae(m) for name, m in models.items()}
for name, mae in sorted(results.items(), key=lambda kv: kv[1].mean()):
    print(f"{name:16s}: CV MAE {mae.mean():5.1f} s ± {mae.std():.1f}   folds {np.round(mae, 1)}")
print("configurations tried:", len(models))`,
      }, {
        title: 'The two best, fold by fold',
        prose: 'A paired comparison: the difference on each fold. **Predict** whether one model wins on every fold.',
        code: `ranked = sorted(results, key=lambda k: results[k].mean())
a, b = ranked[0], ranked[1]
diff = results[b] - results[a]
print(f"{b} − {a}, per fold: {np.round(diff, 2)}")
print(f"mean {diff.mean():.2f} s, standard deviation {diff.std(ddof=1):.2f} s; {a} wins on {np.sum(diff > 0)} of 5 folds")`,
      }],
    },
  },
  'l16-errors': {
    formulaTex: '$$\\text{MAE}_{\\text{segment}} = \\frac{1}{|S|}\\sum_{i \\in S} |\\hat y_i^{\\text{oof}} - y_i|$$',
    mathCode: {
      rows: [
        ['$\\hat y_i^{\\text{oof}}$', 'cross_val_predict(model, X_dev, y_dev, cv=folds)', 'Each development row predicted by a model that never saw it.'],
        ['$S$', 'dev.shared_runner == 1', 'A segment: the rows that share some property.'],
        ['$\\text{MAE}_{\\text{segment}}$', 'err[S].mean()', 'The error inside one segment.'],
      ],
    },
    notebook: {
      title: 'Lab 16.4 · Where does the model fail?',
      intro: 'Collect out-of-fold predictions for every development row and break the error down by segment.',
      cells: [{
        title: 'Out-of-fold errors by segment',
        prose: 'The linear model with engineered features. **Predict** which size band has the largest error.',
        code: `${JOBS}
${FEATURES}
model = make_pipeline(prep, LinearRegression())
oof = cross_val_predict(model, X_dev, y_dev, cv=folds)
err = np.abs(oof - y_dev)
print(f"overall MAE {err.mean():.1f} s")
d = dev.assign(err=err, size_band=pd.cut(dev.size_mb, [0, 20, 50, 100, 1e9], labels=["<20 MB", "20–50", "50–100", ">100"]))
for col in ["shared_runner", "cache_hit", "lang", "size_band"]:
    table = d.groupby(col, observed=True).agg(MAE=("err", "mean"), rows=("err", "size"))
    print(table.round(1).to_string(), "\\n")`,
        tryThis: 'Plot (or print) the out-of-fold residual against size_mb. Is the spread constant, or does it grow — and what does that say about the noise?',
      }],
    },
  },
  'l16-test': {
    formulaTex: '$$\\Delta = \\text{MAE}_{\\text{base}} - \\text{MAE}_{\\text{model}}$$ $$\\text{CI}_{95} = \\big[q_{2.5}(\\Delta^*),\\ q_{97.5}(\\Delta^*)\\big]$$',
    mathCode: {
      rows: [
        ['refit on all development data', 'model.fit(X_dev, y_dev)', 'The frozen pipeline, trained once on everything except the test set.'],
        ['$\\Delta$', 'np.mean(err_base) - np.mean(err_model)', 'The improvement on the test rows.'],
        ['$\\Delta^*$', 'rows = rng.integers(0, n, n); (err_base[rows] - err_model[rows]).mean()', 'One bootstrap replicate: resample test rows, keeping each row’s two errors together (paired).'],
        ['$q_{2.5},\\ q_{97.5}$', 'np.percentile(deltas, [2.5, 97.5])', 'The 2.5th and 97.5th percentiles of 1,000 replicates: the 95% bootstrap interval.'],
      ],
    },
    notebook: {
      title: 'Lab 16.5 · Open the test set once',
      intro: 'Freeze the chosen pipeline, refit it on all development data, score it once on the locked test rows, and put a bootstrap interval on the improvement over the baseline.',
      cells: [{
        title: 'The single test evaluation',
        prose: 'The choice from Lesson 16.3, frozen: the linear model with engineered features. **Predict** whether it meets the criterion (MAE at most half the baseline’s, interval above zero).',
        code: `${JOBS}
${FEATURES}
from sklearn.dummy import DummyRegressor
final = make_pipeline(prep, LinearRegression()).fit(X_dev, y_dev)      # frozen before looking at test
base = DummyRegressor().fit(X_dev, y_dev)
X_test, y_test = engineer(test), test.duration.to_numpy()
err_model = np.abs(final.predict(X_test) - y_test)
err_base = np.abs(base.predict(X_test) - y_test)
rng = np.random.default_rng(0)
deltas = []
for _ in range(1000):
    rows = rng.integers(0, len(y_test), len(y_test))         # resample test rows, keeping pairs together
    deltas.append(err_base[rows].mean() - err_model[rows].mean())
lo, hi = np.percentile(deltas, [2.5, 97.5])
print(f"test MAE: model {err_model.mean():.1f} s   baseline {err_base.mean():.1f} s   skill {1 - err_model.mean() / err_base.mean():.2f}")
print(f"improvement {err_base.mean() - err_model.mean():.1f} s, 95% CI [{lo:.1f}, {hi:.1f}]")
print("criterion met:", (err_model.mean() <= err_base.mean() / 2) and lo > 0)`,
      }],
    },
  },
  'l16-report': {
    formulaTex: '$$\\text{fingerprint} = \\operatorname{SHA256}(\\text{data})$$',
    mathCode: {
      rows: [
        ['data fingerprint', 'hashlib.sha256(jobs.to_csv().encode()).hexdigest()[:12]', 'Identifies exactly which rows were used.'],
        ['versions', 'sklearn.__version__, np.__version__', 'Package versions change results; record them.'],
        ['seeds', 'make_jobs(seed=16), KFold(random_state=0)', 'Every random choice, written down.'],
      ],
    },
    notebook: {
      title: 'Lab 16.6 · The report, and your own project',
      intro: 'Generate a reproducible report from the actual numbers, then apply the same process to a second, scaffolded problem.',
      cells: [{
        title: 'A report generated from the numbers',
        prose: 'Every number below is computed, not typed. Re-running gives the same report; changing a seed or a package version changes the fingerprint line.',
        code: `${JOBS}
${FEATURES}
import hashlib, sklearn
from sklearn.dummy import DummyRegressor
lin = cv_mae(make_pipeline(prep, LinearRegression())); base = cv_mae(make_pipeline(prep, DummyRegressor()))
final = make_pipeline(prep, LinearRegression()).fit(X_dev, y_dev)
test_mae = np.mean(np.abs(final.predict(engineer(test)) - test.duration))
print(f"""PROBLEM   Estimate CI build duration at queue time; MAE in seconds; success = at most half the baseline's MAE.
DATA      {len(jobs)} generated jobs (make_jobs seed 16), fingerprint {hashlib.sha256(jobs.to_csv().encode()).hexdigest()[:12]}; random 20% test set.
FEATURES  size, files, cache, runner, hour, language (one-hot), size×shared, size×(1−cache), shared×busy.
CV        baseline {base.mean():.1f} ± {base.std():.1f} s; linear {lin.mean():.1f} ± {lin.std():.1f} s (5 folds, 5 models compared in 16.3).
TEST      linear model {test_mae:.1f} s on {len(test)} locked rows (opened once).
VERSIONS  numpy {np.__version__}, pandas {pd.__version__}, scikit-learn {sklearn.__version__}.
LIMITS    one simulated cluster; random rather than time-based test split; errors grow with build size.""")`,
      }, {
        title: 'Your turn: a second problem, scaffolded',
        prose: 'Predict how long a **test suite** takes from its number of tests, the share that touch a database, and whether it runs in parallel. The cell runs as given: data, locked test set, baseline and a raw linear model. Follow the TODOs to add features from the recipe’s structure, compare on the same folds, and write the decision.',
        code: `import numpy as np, pandas as pd
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.dummy import DummyRegressor
rng = np.random.default_rng(7)
n = 500
suites = pd.DataFrame({"tests": rng.integers(20, 2000, n), "db_share": rng.uniform(0, 0.6, n), "parallel": rng.integers(0, 2, n)})
per_test = 0.05 + 0.4 * suites.db_share                            # database tests are slower
suites["seconds"] = suites.tests * per_test / np.where(suites.parallel == 1, 4, 1) + 5 + rng.normal(0, 3, n)
test = suites.sample(frac=0.2, random_state=7); dev = suites.drop(test.index)
folds = KFold(5, shuffle=True, random_state=0)
def cv(model, cols):
    return -cross_val_score(model, dev[cols], dev.seconds, cv=folds, scoring="neg_mean_absolute_error").mean()
print(f"baseline CV MAE {cv(DummyRegressor(), ['tests']):.1f} s")
print(f"raw linear CV MAE {cv(LinearRegression(), ['tests', 'db_share', 'parallel']):.1f} s")
# TODO 1: the recipe says time = tests × (0.05 + 0.4·db_share) / (4 if parallel else 1). Build columns a linear
#         model can use for that (hint: tests × db_share, and each of those divided by the parallel factor).
# TODO 2: score your feature set with cv(LinearRegression(), [...]) on the same folds, and one tree ensemble.
# TODO 3: open the test set once for the model you choose; write PROBLEM / DATA / CV / TEST / DECISION lines.`,
      }],
    },
  },
}
