export const lessons = [
  {
    id: 'l28-assumptions',
    title: '28.1 · A model is a set of assumptions about data',
    sections: ['Models fail quietly', 'Implicit assumptions', 'Write them down', 'Where to check', 'Put it into practice'],
    skill: 'Identify the data assumptions a model depends on and where in a pipeline to check them.',
    prerequisite: 'Labs 01–27; data cleaning (Lab 02), leakage (Lab 06), the tabular capstone (Lab 16).',
    paragraphs: [
      'A trained model does not crash when its input is wrong. Give the build-duration model a size in KB instead of MB and it confidently predicts an absurd duration. Most production ML failures are data problems that no exception ever reported.',
      'Every model silently assumes things: which columns exist, their types and units, allowed ranges and categories, how missing values are coded, that ids are unique, and that the distribution resembles training. Feature code adds more assumptions (a divisor never zero, a date always parseable).',
      'A **data contract** writes those assumptions down as checkable rules, agreed with whoever produces the data: `size_mb: number, required, 0 ≤ x ≤ 2000`; `language ∈ {go, java, python}`; `job_id unique`. Violations become explicit, reportable events instead of mysterious model behaviour.',
      'Check at every boundary: when data enters from another system, before training, and before every prediction in serving. The same contract should be used in all three places so training and serving agree (Lab 29).',
      'Procedure: list the columns the model uses; for each, write type, unit, range, allowed values and missing-value policy; add dataset-level rules (row counts, uniqueness, freshness); decide what happens on violation; then automate it.',
    ],
    formula: 'contract = { column: { type, required, min, max, allowed, unique } } + dataset rules + violation policy',
    experiment: 'In "Data contract", turn every rule off, then on one at a time. Record which injected problem each rule catches.',
    question: 'A batch has 60 rows and 8 of them violate the contract. What fraction of rows are bad? (Three decimals.)',
    answer: 0.1333, tolerance: 0.0006,
    explanation: '8/60 ≈ 0.133 — above a 10% limit, so a quarantine policy would reject the batch.',
    reflection: 'Write the contract for three columns your own model depends on. Which violation would currently go unnoticed?',
  },
  {
    id: 'l28-validation',
    title: '28.2 · Row rules, batch policies and quarantine',
    sections: ['Row-level rules', 'Types are rules too', 'Reject or quarantine?', 'Report upstream', 'Fail closed'],
    skill: 'Implement row-level validation and choose a batch policy for violations.',
    prerequisite: 'Lesson 28.1; pandas dtypes (Lab 02).',
    paragraphs: [
      'Row rules check each value: required (not missing), type, minimum and maximum, allowed categories, uniqueness. Each violation records the row, the column and the rule, so the report can say exactly what was wrong.',
      'Type errors are common and dangerous: a CSV export turns 37 into the string "37", and in Python `"37" > 1` raises an error while in JavaScript `"37" > 1` is true. Check types explicitly before comparing values, and report a value of the wrong type once, as a type error.',
      'Policies: **reject** the batch on any violation (safe, but one bad row blocks everything); **quarantine** bad rows and accept the rest (keeps data flowing) — but reject the batch if too many rows fail, because that signals a systemic upstream problem rather than a few typos.',
      'Quarantined rows go back to their owners with the violation report. A contract is a shared agreement; silently "fixing" another team\'s data in your pipeline hides the problem and makes your cleaning code a second, undocumented contract.',
      'When the contract itself cannot be evaluated — the file is missing, a column vanished — fail closed: stop and alert rather than train or predict on something unknown.',
    ],
    formula: 'bad share = |rows with ≥ 1 violation| / |rows|     accept batch if bad share ≤ limit (quarantine the bad rows)',
    experiment: 'Switch between the two batch policies and change the bad-row limit. At what limit does the incoming batch become acceptable?',
    question: 'A quarantine policy allows at most 25% bad rows. A batch of 60 rows has 8 bad rows. How many rows are accepted?',
    answer: 52,
    explanation: '8/60 ≈ 13% ≤ 25%, so the batch is accepted with the 8 bad rows quarantined: 52 rows go through.',
    reflection: 'Would you rather reject or quarantine for your data? Who should be notified in each case?',
  },
  {
    id: 'l28-distribution',
    title: '28.3 · Distribution checks catch what rows cannot',
    sections: ['Plausible but wrong', 'Compare with a reference', 'Choosing thresholds', 'Categorical shifts', 'Freshness and volume'],
    skill: 'Detect unit changes and shifts with batch-level statistics against a training reference.',
    prerequisite: 'Lessons 28.1–28.2; standard errors (Lab 05).',
    paragraphs: [
      'Upstream starts reporting some durations in minutes instead of seconds. Every value is positive and plausible, so no row rule fires. The batch\'s average duration, however, drops from about 83 s to about 46 s.',
      'Store reference statistics from the training data (mean, standard deviation, quantiles, category frequencies) and compare each batch. A simple score is the z-score of the batch mean: `(batch mean − reference mean) / (reference sd / √n)`. The playground flags |z| > 3.',
      'Thresholds trade false alarms for missed problems (Lab 09). Heavy-tailed columns need robust statistics (medians, quantiles); small batches produce noisy statistics; many columns checked at once produce chance alarms (Lab 06\'s multiple comparisons). Tune thresholds on historical batches that you know were fine.',
      'For categories, compare frequencies: a new category (like "rust") or a large change in the share of an existing one both deserve attention. Lab 30 develops these checks into monitoring.',
      'Also check that data arrived at all and on time: row counts per batch and timestamps of the newest record. An empty or stale batch that passes every rule is still a failure.',
    ],
    formula: 'z = (x̄_batch − μ_ref) / (σ_ref / √n)     flag if |z| > threshold',
    experiment: 'Read the drift warning in the contract view. Which rule could you add that would catch the minutes problem at the row level? Why is a distribution check still worth having?',
    question: 'Reference mean 83 s, reference sd 83 s, batch of 49 rows with mean 46 s. What is the z-score of the batch mean? (One decimal.)',
    answer: -3.1, tolerance: 0.051,
    explanation: 'Standard error 83/√49 = 83/7 ≈ 11.86; (46 − 83)/11.86 ≈ −3.1.',
    reflection: 'Which statistic would best reveal a silent unit change in your most important column?',
  },
  {
    id: 'l28-versioning',
    title: '28.4 · Versioning data, code and configuration',
    sections: ['A model is a function of four things', 'Content-addressed data', 'Configuration as data', 'Environments', 'Immutable storage'],
    skill: 'Version datasets by content, record configurations and environments, and explain why in-place edits break reproducibility.',
    prerequisite: 'Lessons 28.1–28.3; fingerprints and seeds (Lab 02).',
    paragraphs: [
      'A trained model is determined by its **data**, its **code**, its **configuration** (hyperparameters, features, seeds) and its **environment** (library versions, hardware). Record all four for every run, or "which model is this?" has no answer.',
      'Identify data by **content**, not by filename: hash a canonical form of the dataset (sorted columns and rows, fixed formatting). `train.csv` can change under the same name; its hash cannot. The playground shows that editing one duration by 0.1 s changes the data version.',
      'Treat configuration as data: a JSON or YAML file hashed like the dataset (with sorted keys so key order does not matter), committed with the code. Record the code version as a git commit and the environment as pinned package versions or a container image.',
      'Store datasets **immutably**: never edit a stored version in place; write a new version and record why. Tools such as DVC, lakeFS or versioned object storage automate this, but the principle is simple enough to implement with hashes and a folder per version.',
      'With these records, a run id can be derived from the three hashes: the same inputs always produce the same id, and any change produces a new one.',
    ],
    formula: 'run_id = H(H(data) ‖ H(config) ‖ code_version)     (H = a cryptographic hash such as SHA-256)',
    experiment: 'In "Lineage", train two runs with different settings, then enable the data edit. Which runs can still be rebuilt, and why?',
    question: 'A SHA-256 hash is written as hexadecimal characters, each encoding 4 bits. How many hexadecimal characters represent a 256-bit hash?',
    answer: 64,
    explanation: '256 / 4 = 64 characters.',
    reflection: 'Where is the data for your last model now? Could you prove it has not changed since training?',
  },
  {
    id: 'l28-tracking',
    title: '28.5 · Experiment tracking and rebuilding a model',
    sections: ['A registry of runs', 'What to log', 'Rebuild to verify', 'When exact is impossible', 'Demonstrate understanding'],
    skill: 'Track experiments so that any model can be rebuilt and verified.',
    prerequisite: 'Lessons 28.1–28.4.',
    paragraphs: [
      'An **experiment tracker** (MLflow, Weights & Biases, or a simple table) records each run: its id, data version, configuration, code version, environment, metrics, and the location of the trained artifact. The playground\'s registry is a minimal version.',
      'Log metrics on the same evaluation data for every run, plus the validation-set version, so comparisons stay fair (Labs 06, 16). Log failures too: they document what did not work.',
      'Verify reproducibility by rebuilding: retrain from the recorded data, configuration and code, and compare weights or predictions. The playground compares a weights fingerprint; in practice compare predictions on a fixed set within a tolerance.',
      'Bit-for-bit reproduction is not always possible: GPU kernels and parallel data loading can be nondeterministic (Lab 23). Then aim for statistical reproducibility — the same metrics within seed-to-seed variation — and record which operations were nondeterministic.',
      'You have completed this lab when you can: write a data contract; validate batches with row and distribution checks; choose a batch policy; version data by content; record configurations and environments; and rebuild a model from its records. The Python challenge implements the validator and the run records.',
    ],
    formula: 'registry row = { run_id, data, config, code, env, metrics, artifact }',
    experiment: 'Train a run, change the learning rate, train again, then enable the data edit. Explain each "rebuild" result in the notebook.',
    question: 'You recorded 3 datasets, 4 configurations and 2 code versions. How many distinct run ids can be formed from them?',
    answer: 24,
    explanation: '3 × 4 × 2 = 24 combinations, each with its own id.',
    reflection: 'Design the minimal experiment registry for your team: which columns, where stored, and who checks it?',
  },
]

export const sources = [
  { title: 'Great Expectations · data validation concepts', url: 'https://docs.greatexpectations.io/docs/reference/learn/' },
  { title: 'Polyzotis et al. (2019) · Data validation for machine learning (TFX)', url: 'https://mlsys.org/Conferences/2019/doc/2019/167.pdf' },
  { title: 'DVC · data version control', url: 'https://dvc.org/doc/start' },
  { title: 'MLflow · tracking', url: 'https://mlflow.org/docs/latest/tracking.html' },
]
