import { extras } from './notebooks.js'

export const lessons = [
  {
    id: 'l27-question',
    title: '27.1 · Start with a question and a simple model',
    sections: ['An investigation, not a leaderboard', 'Is the data suitable?', 'The simplest credible baseline', 'What would change your mind', 'Put it into practice'],
    skill: 'Frame a deep-learning project as an investigation with a baseline, a hypothesis and success criteria.',
    prerequisite: 'Labs 01–26; especially evaluation (Lab 06), convolution (Lab 24) and the tabular capstone (Lab 16).',
    paragraphs: [
      'A deep-learning project is an investigation: a question ("can we recognize digits at positions we have not trained on?"), a set of hypotheses ("convolutional features will help more than extra capacity"), and experiments designed to test them. Without the question, runs pile up and nothing is learned.',
      'Check suitability first. How many labeled examples exist, and how will more be obtained? Does the test data reflect deployment — here, digits at new positions? Are there duplicates or source effects (Lab 24)? Is the label reliable? Most deep-learning failures are data failures discovered too late.',
      'Build the simplest credible baseline before anything deep: a linear model on raw inputs, or a pretrained model with a linear probe. In the playground the linear pixel model reaches only about 38% — it memorizes where ink appears, which says a lot about the problem.',
      'Write down, before running anything, what result would change your plan: "if convolutional features do not beat pixels by 10 points, the bottleneck is elsewhere". Pre-committing protects you from rationalizing any outcome afterwards.',
      'Procedure: question → data checks → baseline → hypotheses with expected effects → a small set of planned experiments → results with uncertainty → decision. The rest of this lab follows those steps.',
    ],
    formula: 'question → data → baseline → hypotheses → planned experiments → evidence → decision',
    experiment: 'Before running anything, write in the notebook your predicted accuracy for each of the five pipelines, and which you expect to win.',
    question: 'The test set mixes shifts 0–5 equally; training covers shifts 0–3. What fraction of test images are at unseen shifts? (Three decimals.)',
    answer: 0.3333, tolerance: 0.0006,
    explanation: 'Shifts 4 and 5 are 2 of 6 equally likely positions: 1/3 of the test set.',
    reflection: 'Write the question, baseline and "what would change my mind" statement for a deep-learning idea you have.',
  },
  {
    id: 'l27-transfer',
    title: '27.2 · Representations and transfer',
    sections: ['Features decide what can be learned', 'Borrowing representations', 'Linear probes', 'Fine-tuning carefully', 'When transfer fails'],
    skill: 'Choose between learning from scratch, linear probing and fine-tuning based on data and domain.',
    prerequisite: 'Lesson 27.1; transfer learning (Lab 24).',
    paragraphs: [
      'The playground\'s biggest jump comes from changing the **representation**: convolution + pooling features let a linear model reach about 75%, where pixels give 38%. Better features often matter more than a bigger classifier.',
      'In practice those features come from a model pretrained on a large related dataset: image backbones trained on millions of photos, text encoders trained on large corpora. Reusing them is **transfer learning**.',
      'A **linear probe** freezes the pretrained model and trains only a linear classifier on its outputs. It is fast, needs little data, and measures how much task-relevant information the representation already contains — a strong baseline for any deep project.',
      '**Fine-tuning** updates some or all pretrained weights with a small learning rate. It helps when the domain differs from pretraining data but risks overfitting small datasets and "forgetting" useful general features. Compare it against the probe, on the same splits and seeds.',
      'Transfer fails when the domains are too different (natural photos versus radiographs or spectrograms may still help, but less), or when shortcuts in the pretraining data carry over. Measure; do not assume.',
    ],
    formula: 'probe: train W on f(x) (f frozen)     fine-tune: train f and W, small learning rate for f',
    experiment: 'Compare "Linear on pixels" with "Linear on conv features" — the same classifier, different representations. How large is the difference, and how many parameters does each use?',
    question: 'A frozen backbone outputs 512 features; a linear probe classifies 10 classes. How many trainable parameters does the probe have?',
    answer: 5130,
    explanation: '512 × 10 weights + 10 biases = 5,130 — tiny compared with the backbone.',
    reflection: 'Which pretrained models exist for your kind of data? How would you test whether they help?',
  },
  {
    id: 'l27-ablation',
    title: '27.3 · Ablations and seeds',
    sections: ['Change one thing at a time', 'Leave-one-out ablations', 'Seeds are part of the experiment', 'Paired comparisons', 'Interactions'],
    skill: 'Design ablations, report variation across seeds, and compare configurations fairly.',
    prerequisite: 'Lessons 27.1–27.2; standard errors (Lab 05), winner’s curse (Lab 06).',
    paragraphs: [
      'An **ablation** removes one component from the final system and measures the change. It answers "does this part matter?" far more convincingly than adding components one by one in a single order.',
      'Training involves randomness — initialization, data order, augmentation. The same configuration can differ by several points between seeds. Run each configuration over several seeds and report mean ± standard deviation; with three seeds, differences under about two standard deviations are not convincing.',
      'Compare configurations **paired by seed**: same data split, same initialization seed where possible. Paired differences cancel shared noise, just as comparing models on the same folds did in Lab 16. The playground reports the range of paired gains for each ablated component.',
      'Components interact: augmentation might help a linear pixel model a lot and a convolutional model only a little, because convolution and pooling already provide some invariance. Ablation differences therefore do not add up to the total improvement; report them as "contribution in the presence of the others".',
      'Choosing among many configurations on one test set inflates the winner (Lab 06). Select on validation data, ablate on validation data, and evaluate the final choice once on the test set.',
    ],
    formula: 'ablation effect of c = score(full) − score(full without c), per seed; report mean and range',
    experiment: 'Run the ablations with 3 seeds. Which component\'s removal hurts most? Are any paired ranges overlapping zero?',
    question: 'Across three seeds, removing a component changes accuracy by −6, −9 and −3 points. What is the mean change?',
    answer: -6,
    explanation: '(−6 − 9 − 3)/3 = −6 points, and all three paired differences are negative, which makes the effect convincing even with few seeds.',
    reflection: 'For a system you have built, which component would you ablate first? What result would surprise you?',
  },
  {
    id: 'l27-compute',
    title: '27.4 · Compute budgets and cost',
    sections: ['Three budgets', 'Parameters versus compute', 'Training versus inference', 'Justify the cost', 'Measure, do not guess'],
    skill: 'Account for parameters, compute and time, and justify a model’s cost against its benefit.',
    prerequisite: 'Lessons 27.1–27.3; serving considerations are expanded in Lab 29.',
    paragraphs: [
      'Models cost **memory** (parameters, activations), **compute** (multiply-adds per example) and **time** (training and inference latency). Each is a separate budget with a separate limit: phone memory, cloud bills, response-time targets.',
      'Parameters and compute differ. The convolutional pipeline in the playground has fewer parameters than the pixel model but more multiply-adds, because each filter is applied at every position. A dense layer\'s cost is inputs × outputs; a convolution\'s is roughly kernel area × channels in × channels out × output positions.',
      'Training cost is paid once (per retraining); inference cost is paid on every prediction, forever. A model that is 1 point more accurate but 10× slower may be the wrong choice for a live service and the right one for a nightly batch job.',
      'Write the justification explicitly: "The full pipeline improves accuracy by 42 points over the baseline for 4× the compute per image, well within our 10 ms budget." If a simpler model is within noise of the best, it usually wins on cost, maintenance and explainability.',
      'Measure on the real hardware and data sizes. Multiply-add counts are a good first estimate; actual latency depends on memory access, batching and implementation.',
    ],
    formula: 'dense MACs = n_in × n_out     conv MACs ≈ k² × C_in × C_out × H_out × W_out',
    experiment: 'In the results table, compare parameters, multiply-adds and training time for the five pipelines. Which would you deploy on a tiny microcontroller? On a server?',
    question: 'A 3 × 3 convolution with 1 input and 4 output channels produces 10 × 10 outputs per channel. How many multiply-adds does it need per image?',
    answer: 3600,
    explanation: '9 × 1 × 4 × 100 = 3,600 multiply-adds, although the layer has only 36 weights (+ 4 biases).',
    reflection: 'What is the tightest budget (memory, compute or latency) for a model you would deploy? How would you measure it?',
  },
  {
    id: 'l27-errors',
    title: '27.5 · Qualitative error analysis and reporting',
    sections: ['Look at the mistakes', 'Confusions tell stories', 'From errors to next experiments', 'Report failures too', 'Demonstrate understanding'],
    skill: 'Analyse errors qualitatively, derive next experiments from them, and write an honest investigation report.',
    prerequisite: 'Lessons 27.1–27.4; error analysis (Lab 16).',
    paragraphs: [
      'Aggregate metrics hide structure. Inspect the confusion matrix and the misclassified examples themselves: which classes are confused, at which positions, under which noise? The playground shows both for any pipeline.',
      'Confusions are hypotheses: if 7s become 1s mostly at unseen shifts, the model relies on position; if 3s and 8s swap at every shift, the features may not capture closed loops. Each hypothesis suggests an experiment (more augmentation, different filters, more data for those classes).',
      'Separate what the model cannot see from what it failed to learn: some examples are ambiguous even to a human (heavy noise), and no model will get them right. Estimate that floor before chasing the last points.',
      'An investigation report states the question, data and splits, every configuration run (including failures), results with seed spread, ablations, compute costs, qualitative findings and the decision. Negative results — "extra capacity did not help" — are findings, not embarrassments.',
      'You have completed this lab — and the neural-network stage — when you can: frame a deep-learning question with a baseline; choose between scratch training and transfer; design ablations across seeds; account for compute; and turn error analysis into the next experiment, all reported honestly. The Python challenge builds a reusable experiment harness.',
    ],
    formula: 'report = question + data + configs (all) + mean ± sd over seeds + ablations + compute + errors + decision',
    experiment: 'Inspect errors of the full pipeline and of the pixel baseline. Name one systematic confusion for each and one experiment it suggests.',
    question: 'A confusion matrix row for true digit 7 has 30 examples: 24 predicted 7, 5 predicted 1, 1 predicted 9. What is the recall for digit 7? (Decimal.)',
    answer: 0.8,
    explanation: '24/30 = 0.8. The 5 errors toward 1 suggest a specific hypothesis to test.',
    reflection: 'Write the outline of an investigation report for the experiment you ran in the playground.',
  },
]

export const sources = [
  { title: 'Karpathy · A recipe for training neural networks', url: 'https://karpathy.github.io/2019/04/25/recipe/' },
  { title: 'Google Research · Deep learning tuning playbook', url: 'https://github.com/google-research/tuning_playbook' },
  { title: 'Bouthillier et al. (2021) · Accounting for variance in machine learning benchmarks', url: 'https://arxiv.org/abs/2103.03098' },
  { title: 'Lipton & Steinhardt (2018) · Troubling trends in machine learning scholarship', url: 'https://arxiv.org/abs/1807.03341' },
]

// Runnable cells, typeset formulas and math ↔ code tables for each lesson live in notebooks.js.
for (const lesson of lessons) Object.assign(lesson, extras[lesson.id])
