export const lessons = [
  {
    id: 'l17-unsupervised',
    title: '17.1 · Learning without labels',
    sections: ['No target column', 'What clustering promises', 'What it cannot promise', 'Similarity is a choice', 'Put it into practice'],
    skill: 'Describe what clustering can and cannot establish, and why distance and scaling choices define the result.',
    prerequisite: 'Labs 01–16; distances and scaling (Lab 10).',
    paragraphs: [
      'You have thousands of build logs and no labels. Are there distinct kinds of builds — quick lint jobs, full compiles, flaky integration suites? **Unsupervised learning** looks for structure in inputs alone, with no target to predict.',
      '**Clustering** partitions observations into groups so that members of a group are more similar to each other than to members of other groups. It can suggest segments, compress data into prototypes, and flag points that fit no group.',
      'It cannot tell you that the groups are real. Every clustering algorithm returns clusters on any data — even uniformly random points. A cluster is a hypothesis about structure, to be checked for stability, usefulness and meaning, never automatically a true category.',
      'Most algorithms rely on a distance. As with k-NN (Lab 10), features must be scaled and chosen deliberately: clustering build logs by raw size in bytes and duration in seconds will cluster almost entirely by size. Choosing features and scales is choosing what "similar" means.',
      'Procedure: decide what a useful grouping would let you do; choose and scale features accordingly; run an algorithm; check stability across seeds and subsamples; inspect members of each cluster; and validate usefulness with something external (do the clusters differ in failure rate?).',
    ],
    formula: 'clustering: assign each xᵢ a group label cᵢ ∈ {1…k} using only the x values',
    experiment: 'Select "No clusters at all" and run k-means with k = 3. Does it find three clusters? What does that tell you about trusting a clustering?',
    question: 'You cluster 240 points with k = 4. How many cluster labels does k-means assign in total (one per point)?',
    answer: 240,
    explanation: 'Every point gets exactly one label: 240 labels drawn from 4 possible values.',
    reflection: 'What decision would a clustering of your data support? How would you check that the clusters are useful and not just produced by the algorithm?',
  },
  {
    id: 'l17-kmeans',
    title: '17.2 · k-means: assign and update',
    sections: ['Centres as prototypes', 'The objective', 'Two alternating steps', 'Why it converges', 'Local minima and initialization'],
    skill: 'Run k-means by hand, explain why it converges, and use k-means++ and restarts against local minima.',
    prerequisite: 'Lesson 17.1; means and squared distance.',
    paragraphs: [
      'k-means represents each cluster by a **centre** (centroid) and assigns each point to its nearest centre. The quality of a clustering is its **inertia**: the sum of squared distances from each point to its assigned centre (the within-cluster sum of squares).',
      '**Assign step**: with centres fixed, give each point to the nearest centre. **Update step**: with assignments fixed, move each centre to the mean of its points. For points at 1, 2 and 6 assigned to one cluster, the new centre is (1 + 2 + 6)/3 = 3.',
      'Each step can only lower (or keep) the inertia: choosing the nearest centre minimizes each point\'s own term, and the mean minimizes the sum of squared distances to a set of points. Inertia cannot decrease forever and the number of possible assignments is finite, so the algorithm stops — usually within a few iterations.',
      'It stops at a **local** minimum that depends on the starting centres. A bad start can place two centres in one real cluster and one centre between two others. **k-means++** starts smarter: pick the first centre at random, then each next one with probability proportional to its squared distance from the nearest chosen centre, which spreads them out. Also run several restarts and keep the lowest inertia.',
      'Step through the playground: each click alternates assign and update, with trails showing how each centre moves. With random initialization, try several seeds on "Three round clusters" and watch some runs get stuck.',
    ],
    formula: 'inertia = Σᵢ ‖xᵢ − μ_{c(i)}‖²     assign: c(i) = argmin_j ‖xᵢ − μ_j‖     update: μ_j = mean{xᵢ : c(i) = j}',
    experiment: 'Random initialization, k = 3, seeds 4, 7 and 12. Record the final inertia each time. Then switch to k-means++ and repeat.',
    question: 'A cluster contains points at 1, 2 and 6 on a line. Where does the update step move its centre?',
    answer: 3,
    explanation: 'The mean (1 + 2 + 6)/3 = 3. That point minimizes the sum of squared distances to the cluster\'s members.',
    reflection: 'Explain in your own words why k-means cannot oscillate forever.',
  },
  {
    id: 'l17-choosek',
    title: '17.3 · Choosing k and checking stability',
    sections: ['Inertia always falls', 'The elbow', 'Silhouette', 'Stability across runs', 'Usefulness decides'],
    skill: 'Use the elbow, the silhouette score and stability to choose k, and know their limits.',
    prerequisite: 'Lessons 17.1–17.2.',
    paragraphs: [
      'More centres always fit at least as well, so inertia decreases with k and reaches zero when every point is its own cluster. Minimizing inertia cannot choose k.',
      'Plot inertia against k and look for an **elbow**: the point where adding a cluster stops helping much. On well-separated data it is clear; on real data it is often a gentle curve with no obvious bend.',
      'The **silhouette** of a point compares a — its mean distance to its own cluster — with b — its mean distance to the nearest other cluster: `s = (b − a)/max(a, b)`. Values near 1 mean well inside its cluster; near 0, on a border; negative, probably misassigned. With a = 2 and b = 6, s = 4/6 ≈ 0.667. The mean silhouette over all points is a common score for k.',
      '**Stability**: run the algorithm with different seeds (or on bootstrap samples, Lab 05) and measure how often pairs of points stay together, for example with the Rand index. Real structure reappears; arbitrary splits move around.',
      'None of these proves that the clusters are meaningful. The best k is the one that serves the purpose — often chosen with domain experts looking at cluster members, and checked against external data the clustering did not use.',
    ],
    formula: 's(i) = (b(i) − a(i)) / max(a(i), b(i))     Rand index = fraction of point pairs treated the same by two clusterings',
    experiment: 'In "Choosing k", compare the three curves on "Three round clusters", "Stretched" and "No clusters at all". Which datasets give a clear answer?',
    question: 'A point has mean distance a = 2 to its own cluster and b = 6 to the nearest other cluster. What is its silhouette (b − a)/max(a, b)? (Three decimals.)',
    answer: 0.6667, tolerance: 0.0006,
    explanation: '(6 − 2)/6 = 0.667: the point is clearly closer to its own cluster.',
    reflection: 'How would you convince a colleague that the segments you found are stable and useful, not an artifact of k-means?',
  },
  {
    id: 'l17-shapes',
    title: '17.4 · When k-means fails: shapes and densities',
    sections: ['Hidden assumptions', 'Non-convex shapes', 'Unequal sizes and spreads', 'Density-based clustering', 'Choosing an algorithm'],
    skill: 'Recognize k-means’ assumptions and use DBSCAN when clusters are not round blobs.',
    prerequisite: 'Lessons 17.1–17.3.',
    paragraphs: [
      'Assigning each point to the nearest centre divides space into convex cells (Voronoi regions) with straight boundaries halfway between centres. k-means therefore prefers roughly round clusters of similar size and spread.',
      'Two interleaved moons are clearly two groups, but no straight boundary separates them: k-means cuts each moon in half. Stretched clusters get sliced across their long axis. A big diffuse cluster next to small tight ones loses points to its neighbours.',
      '**DBSCAN** defines clusters as dense regions. A point is a **core** point if at least minPts points (itself included) lie within distance ε. Clusters are grown by connecting core points within ε of each other, plus the border points they reach. Everything else is labeled **noise**.',
      'DBSCAN needs no k, finds arbitrary shapes and marks outliers. Its weaknesses: ε and minPts must be tuned; a single ε cannot fit clusters of very different density; and like every distance method it needs scaled features and suffers in high dimensions.',
      'Other families: hierarchical clustering builds a tree of merges you can cut at any level; Gaussian mixture models allow elliptical clusters with soft (probabilistic) membership. Choose by the shapes you expect and what you need out of the result.',
    ],
    formula: 'core(x) ⇔ |{x′ : ‖x − x′‖ ≤ ε}| ≥ minPts     clusters = connected components of cores (+ their border points)',
    experiment: 'On "Two moons", compare k-means (k = 2) with DBSCAN. Then on DBSCAN, sweep ε from 0.15 to 1.0 and watch the cluster count and noise.',
    question: 'With minPts = 5, a point has 4 neighbours within ε, counting itself. Is it a core point? (1 = yes, 0 = no)',
    answer: 0,
    explanation: '4 < 5, so it is not a core point. It may still be a border point if it lies within ε of some core point; otherwise it is noise.',
    reflection: 'What shape would clusters in your data likely have? Which algorithm fits that expectation?',
  },
  {
    id: 'l17-anomaly',
    title: '17.5 · Anomaly detection with distances',
    sections: ['Rare and different', 'Distance-based scores', 'Scale matters again', 'Thresholds and evaluation', 'Demonstrate understanding'],
    skill: 'Build a simple anomaly score, choose a flagging threshold, and explain its failure modes.',
    prerequisite: 'Lessons 17.1–17.4; thresholds and precision (Lab 09).',
    paragraphs: [
      'An anomaly is an observation unlike most others: a build ten times slower than similar builds, a login from an unusual place. With few or no labeled anomalies, we score how unusual each point is and investigate the highest scores.',
      'A simple score: the distance from each point to its nearest k-means centre. Points far from every centre fit no cluster well. Alternatives: distance to the k-th nearest neighbour, DBSCAN noise labels, or density estimates.',
      'Distance to a centre ignores each cluster\'s spread. In a wide cluster, ordinary members sit far from the centre and get flagged; in a tight cluster, a real outlier can still be closer than those. Dividing by each cluster\'s typical distance (or using per-cluster statistics) makes the score relative.',
      'Flagging the top 5% is a threshold choice with the trade-offs of Lab 09: more flags catch more anomalies and waste more investigation time. When a few labeled incidents exist, measure precision among the flags; otherwise, have experts review a sample of flagged and unflagged points.',
      'You have completed this lab when you can: explain what clustering can and cannot establish; run k-means by hand and explain convergence; choose k with elbow, silhouette and stability; recognize when DBSCAN is better; and build and critique a distance-based anomaly score. The Python challenge implements k-means and the silhouette.',
    ],
    formula: 'score(x) = ‖x − μ_{c(x)}‖     flag if score ≥ the (1 − share) quantile',
    experiment: 'In "Anomaly scores", compare which points are flagged on "Three round clusters" and on "unequal". Are the flagged points on "unequal" really unusual?',
    question: 'You flag the top 5% of 240 points by anomaly score. How many points are flagged?',
    answer: 12,
    explanation: '5% of 240 = 12 points for review.',
    reflection: 'If you deployed an anomaly detector, who would review the flags, and how would you learn whether it catches real problems?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 12.4: clustering methods', url: 'https://www.statlearning.com/' },
  { title: 'Arthur & Vassilvitskii (2007) · k-means++: the advantages of careful seeding', url: 'https://dl.acm.org/doi/10.5555/1283383.1283494' },
  { title: 'Ester et al. (1996) · DBSCAN: a density-based algorithm for discovering clusters', url: 'https://cdn.aaai.org/KDD/1996/KDD96-037.pdf' },
  { title: 'scikit-learn · Clustering (overview and comparison)', url: 'https://scikit-learn.org/stable/modules/clustering.html' },
]
