export const lessons = [
  {
    id: 'l15-margin',
    title: '15.1 · Many boundaries fit — which is best?',
    sections: ['Infinitely many separating lines', 'Distance to the boundary', 'The margin', 'Why wide is better', 'Put it into practice'],
    skill: 'Define the geometric margin of a linear classifier and explain why maximizing it is a sensible goal.',
    prerequisite: 'Labs 01–14; decision boundaries (Lab 08), vector norms (Lab 03).',
    paragraphs: [
      'When two groups of points can be separated by a line, infinitely many lines do it. Logistic regression on separable data keeps pushing its weights up without settling (Lab 08). We need a principle for choosing one boundary.',
      'For a linear score f(x) = w·x + b, the boundary is f(x) = 0. The perpendicular distance of a point from it is `|w·x + b| / ‖w‖`. For w = (3, 4), b = −5 and the point (3, 4): |9 + 16 − 5| / 5 = 4.',
      'The **margin** of a classifier on a dataset is the distance from the boundary to the closest training point. A boundary that passes close to some point has a small margin: a tiny shift or a little measurement noise could put a similar new point on the wrong side.',
      'The **maximum-margin** boundary sits in the middle of the widest "street" separating the classes. Intuitively it is the most robust choice, and learning theory backs this up: larger margins mean simpler classifiers in a precise sense, and better guarantees for generalization.',
      'Support vector machines (SVMs) find this boundary. In the playground on "Two blobs" with small λ, the solid line is the SVM boundary, the dashed lines are the street edges, and the circled points touch them.',
    ],
    formula: 'distance(x, boundary) = |w·x + b| / ‖w‖     margin = min_i distance(xᵢ, boundary)',
    experiment: 'On "Two blobs", compare the SVM line with the logistic-regression line. Which runs through the middle of the gap between the classes?',
    question: 'For w = (3, 4) and b = −5, how far is the point (3, 4) from the boundary w·x + b = 0?',
    answer: 4,
    explanation: 'w·x + b = 9 + 16 − 5 = 20, and ‖w‖ = 5, so the distance is 20/5 = 4.',
    reflection: 'Describe a situation in your domain where a boundary that barely separates the training data would fail on new data.',
  },
  {
    id: 'l15-hardmargin',
    title: '15.2 · The optimization problem',
    sections: ['Fix the scale', 'Margin = 2/‖w‖', 'Hard-margin SVM', 'Support vectors', 'Why only a few points matter'],
    skill: 'Formulate the hard-margin SVM and identify its support vectors.',
    prerequisite: 'Lesson 15.1.',
    paragraphs: [
      'Multiplying w and b by any positive constant leaves the boundary unchanged, so fix the scale: require `yᵢ(w·xᵢ + b) ≥ 1` for every training point, with labels yᵢ ∈ {−1, +1}, and equality for the closest points. Then the closest points satisfy f(x) = ±1.',
      'Under that scaling the street runs from f = −1 to f = +1, and its full width is `2/‖w‖`. Maximizing the margin is the same as minimizing ‖w‖ — conveniently written `½‖w‖²`.',
      'The **hard-margin SVM** solves: minimize ½‖w‖² subject to yᵢ(w·xᵢ + b) ≥ 1 for all i. It is a convex quadratic program with a unique solution when the data are separable.',
      'At the solution, only the points lying exactly on the street edges constrain it. They are the **support vectors**. Delete any other point, or move it anywhere outside the street on its own side, and the solution does not change.',
      'This sparsity is characteristic of SVMs: the model is defined by a handful of boundary cases. With ‖w‖ = 4, for example, the street is 2/4 = 0.5 wide.',
    ],
    formula: 'minimize ½‖w‖²  subject to  yᵢ(w·xᵢ + b) ≥ 1     width = 2/‖w‖',
    experiment: 'With "Two blobs" and the smallest λ, count the support vectors. Note the margin width, then increase λ and watch both change.',
    question: 'An SVM has ‖w‖ = 4. What is the width of its margin (the street), 2/‖w‖?',
    answer: 0.5,
    explanation: '2/4 = 0.5.',
    reflection: 'Why might it be useful, in practice, that a model depends only on a few boundary examples? When could it be a weakness?',
  },
  {
    id: 'l15-hinge',
    title: '15.3 · Soft margins and the hinge loss',
    sections: ['Real data overlap', 'Allow violations, at a price', 'The hinge loss', 'Regularization view', 'Train by subgradient descent'],
    skill: 'Write the soft-margin SVM as regularized hinge loss and train it with subgradient descent.',
    prerequisite: 'Lessons 15.1–15.2; regularization (Lab 07); gradient descent (Lab 08).',
    paragraphs: [
      'Overlapping classes have no separating line, so the hard constraints cannot all hold. The **soft-margin** SVM lets points violate the margin but charges for each violation.',
      'For a point with margin m = y·f(x), the **hinge loss** is `max(0, 1 − m)`. It is 0 for a point safely on its side (m ≥ 1), grows linearly as the point enters the street, and exceeds 1 when the point is misclassified (m < 0). For m = 0.4 the loss is 0.6.',
      'The soft-margin SVM minimizes `λ/2·‖w‖² + mean(max(0, 1 − yᵢ f(xᵢ)))`. This is exactly Lab 07\'s pattern — a data loss plus an L2 penalty — with the hinge in place of squared error. Libraries often write it with C instead: C ∝ 1/λ, so large C means little regularization and a narrow margin.',
      'The hinge has a corner at m = 1, so it is not differentiable there; use a **subgradient**: for points with m < 1 the gradient of their loss with respect to w is −y·x; otherwise it is 0. Gradient descent with these subgradients (plus λw from the penalty) converges with a decreasing step size — the **Pegasos** algorithm, used by the playground.',
      'Compared with logistic loss: the hinge is exactly zero for confident correct points, which produces sparsity (support vectors); logistic loss is always positive, gives calibrated-ish probabilities, and keeps every point involved. Accuracy is often similar; the right choice depends on whether you need probabilities.',
    ],
    formula: 'J(w) = λ/2·‖w‖² + (1/n) Σ max(0, 1 − yᵢ w·xᵢ)     subgradient: λw − (1/n) Σ_{mᵢ<1} yᵢxᵢ',
    experiment: 'On "Overlapping blobs", step λ from smallest to largest. Record the margin width, support vectors and validation accuracy. Which λ would you choose?',
    question: 'A point has margin m = y·f(x) = 0.4. What is its hinge loss max(0, 1 − m)?',
    answer: 0.6,
    explanation: '1 − 0.4 = 0.6. It is correctly classified (m > 0) but inside the street, so it still costs something.',
    reflection: 'Would you rather have a classifier that ignores points it already classifies confidently, or one that keeps pushing them further? Why?',
  },
  {
    id: 'l15-kernel',
    title: '15.4 · The kernel idea',
    sections: ['Lines in a bigger space', 'Feature maps', 'Kernels compute dot products', 'The RBF kernel', 'Costs and choices'],
    skill: 'Explain how feature maps and kernels let a linear margin classifier draw curved boundaries.',
    prerequisite: 'Lessons 15.1–15.3; quadratic features (Lab 08).',
    paragraphs: [
      'A ring of one class around another cannot be separated by a line in (x₁, x₂). Add the feature x₁² + x₂²: now "inside" and "outside" differ in one coordinate, and a flat boundary in the bigger space corresponds to a circle in the original space.',
      'A **feature map** φ(x) sends each point to a higher-dimensional space; the SVM finds a linear boundary w·φ(x) + b = 0 there. The degree-2 map `(x₁, x₂, x₁², x₂², √2·x₁x₂)` gives ellipses and hyperbolas. The playground\'s "Quadratic" option uses it on the circles dataset.',
      'The SVM\'s optimization can be rewritten so that data appear only through dot products φ(x)·φ(x′). A **kernel** K(x, x′) computes that dot product directly, without building φ: the degree-2 polynomial kernel is `(x·x′)²`. For x = (1, 2) and x′ = (3, 1): x·x′ = 5, K = 25 — the dot product of their six-dimensional feature vectors, computed in two dimensions.',
      'The **RBF (Gaussian) kernel** `K(x, x′) = exp(−γ‖x − x′‖²)` corresponds to an infinite-dimensional feature map. It measures similarity: 1 for identical points, near 0 for distant ones. γ sets the reach: large γ gives very local, wiggly boundaries (overfitting risk); small γ gives smooth ones. The playground approximates it with 120 random Fourier features, a practical technique for large datasets.',
      'Exact kernel SVMs need an n × n kernel matrix — fine for thousands of rows, impractical for millions. Tune λ (or C) and γ together by cross-validation, and standardize features first: the RBF kernel is distance-based, with k-NN\'s sensitivity to scale (Lab 10).',
    ],
    formula: 'K(x, x′) = φ(x)·φ(x′)     polynomial: (x·x′)^d     RBF: exp(−γ‖x − x′‖²)',
    experiment: 'On "Circle inside ring", compare linear and quadratic maps. On "Two moons", use RBF with γ = 0.3, 1 and 6, and compare training and validation accuracy.',
    question: 'For x = (1, 2) and x′ = (3, 1), compute the degree-2 polynomial kernel (x·x′)².',
    answer: 25,
    explanation: 'x·x′ = 3 + 2 = 5, and 5² = 25.',
    reflection: 'When would you prefer engineering explicit features over choosing a kernel? What does each cost in interpretability?',
  },
  {
    id: 'l15-compare',
    title: '15.5 · SVMs versus logistic regression',
    sections: ['Same shape, different loss', 'Probabilities', 'Outliers and sparsity', 'Scaling to large data', 'Demonstrate understanding'],
    skill: 'Compare linear SVMs with logistic regression and choose between them.',
    prerequisite: 'Lessons 15.1–15.4; logistic regression (Lab 08); calibration (Lab 09).',
    paragraphs: [
      'Both are linear classifiers trained by minimizing a loss of the margin plus a regularizer. On most datasets their boundaries and accuracies are close; the playground overlays them.',
      'Logistic regression outputs probabilities directly. SVM scores are distances, not probabilities; turning them into probabilities needs a calibration step such as Platt scaling (Lab 09), fitted on held-out data.',
      'Because the hinge ignores points beyond the margin, the SVM is determined by a few support vectors; logistic regression is influenced by every point. Misclassified outliers hurt both — each loss grows linearly for badly misclassified points — but only logistic regression keeps pushing on correctly classified points far from the boundary.',
      'Linear SVMs and logistic regression both scale to millions of rows and features with stochastic solvers. Kernel SVMs do not scale to very large n; for large non-linear problems, tree ensembles (Labs 13–14) or neural networks (Labs 20–26) are usually preferred.',
      'You have completed this lab when you can: compute distances to a hyperplane; state the hard- and soft-margin problems; compute hinge losses and identify support vectors; explain kernels; and choose between an SVM and logistic regression for a given need. The Python challenge trains a linear SVM with subgradient descent.',
    ],
    formula: 'logistic: log(1 + e^(−m))     hinge: max(0, 1 − m)     both + λ‖w‖²',
    experiment: 'On "Overlapping blobs", compare the SVM and logistic boundaries at several λ values. Where do they differ, and why?',
    question: 'An SVM classifies 3 points with margins m = 2.5, 0.8 and −0.5. How many of them are support vectors (m ≤ 1)?',
    answer: 2,
    explanation: '0.8 (inside the street) and −0.5 (misclassified) both have m ≤ 1. The point at 2.5 has zero loss and does not affect the solution.',
    reflection: 'For a classifier you might build, do you need probabilities? How does that affect the choice between an SVM and logistic regression?',
  },
]

export const sources = [
  { title: 'ISL with Python · Chapter 9: support vector machines', url: 'https://www.statlearning.com/' },
  { title: 'Shalev-Shwartz et al. (2011) · Pegasos: primal estimated sub-gradient solver for SVM', url: 'https://doi.org/10.1007/s10107-010-0420-4' },
  { title: 'Rahimi & Recht (2007) · Random features for large-scale kernel machines', url: 'https://papers.nips.cc/paper/2007/hash/013a006f03dbc5392effeb8f18fda755-Abstract.html' },
  { title: 'scikit-learn · Support vector machines', url: 'https://scikit-learn.org/stable/modules/svm.html' },
]
